import Mathlib

namespace ZeroDayRestrictedClosures

noncomputable section

/--
Dimensionally consistent scalar–photon effective Lagrangian density.

Conventions:
* `phi` and `mPhi` have mass dimension one;
* `X = ∂_μ phi ∂^μ phi` and `Y = F_μν F^μν` have mass dimension four;
* `lambda` is dimensionless;
* `Lambda` has mass dimension one.

The interaction is
`(lambda * Lambda^4 / 2) * (Y / Lambda^4 - X^2 / Lambda^8)^2`.
-/
def dimensionfulInvariantMatchingLagrangian
    (mPhi lambda Lambda phi X Y : ℝ) : ℝ :=
  -(1 / 4 : ℝ) * Y +
    (1 / 2 : ℝ) * X -
    (1 / 2 : ℝ) * mPhi ^ 2 * phi ^ 2 +
    (lambda * Lambda ^ 4 / 2) *
      (Y / Lambda ^ 4 - X ^ 2 / Lambda ^ 8) ^ 2

/--
Expanded form of the same effective Lagrangian.  The pure four-photon
coefficient is `lambda / (2 * Lambda^4)`.
-/
def dimensionfulInvariantMatchingLagrangianExpanded
    (mPhi lambda Lambda phi X Y : ℝ) : ℝ :=
  -(1 / 4 : ℝ) * Y +
    (1 / 2 : ℝ) * X -
    (1 / 2 : ℝ) * mPhi ^ 2 * phi ^ 2 +
    lambda / (2 * Lambda ^ 4) * Y ^ 2 -
    lambda / Lambda ^ 8 * Y * X ^ 2 +
    lambda / (2 * Lambda ^ 12) * X ^ 4

/--
The dimensionful square form expands exactly into the photon quartic,
mixed scalar–photon, and scalar octic operators.
-/
theorem dimensionfulInvariantMatchingLagrangian_eq_expanded
    (mPhi lambda Lambda phi X Y : ℝ)
    (hLambda : Lambda ≠ 0) :
    dimensionfulInvariantMatchingLagrangian
        mPhi lambda Lambda phi X Y =
      dimensionfulInvariantMatchingLagrangianExpanded
        mPhi lambda Lambda phi X Y := by
  unfold dimensionfulInvariantMatchingLagrangian
  unfold dimensionfulInvariantMatchingLagrangianExpanded
  field_simp [hLambda]
  ring

/--
CMS–TOTEM convention:
`L_4gamma = zeta1 * (F_μν F^μν)^2 + ...`.

For the present action, `zeta1 = lambda / (2 * Lambda^4)`.
-/
def fourPhotonZetaOne
    (lambda Lambda : ℝ) : ℝ :=
  lambda / (2 * Lambda ^ 4)

/--
The three disjoint contractions appearing in the four-photon contact
amplitude from `(F_μν F^μν)^2`.
-/
def fourPhotonPairingSum
    (f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  f12 * f34 + f13 * f24 + f14 * f23

/--
The field-strength invariant of four superposed on-shell external photons,
after the individual null terms `F_i · F_i` have vanished.

Here `fij` denotes the contraction `F_i · F_j`.
-/
def fourPhotonSuperposedInvariant
    (t1 t2 t3 t4 f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  2 * (
    t1 * t2 * f12 +
    t3 * t4 * f34 +
    t1 * t3 * f13 +
    t2 * t4 * f24 +
    t1 * t4 * f14 +
    t2 * t3 * f23
  )

/--
Four-variable inclusion–exclusion operator. On a polynomial of total
degree four, it extracts the coefficient of `t1 * t2 * t3 * t4`.
-/
def fourVariableMixedDifference
    (p : ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ :=
  p 1 1 1 1
    - p 0 1 1 1
    - p 1 0 1 1
    - p 1 1 0 1
    - p 1 1 1 0
    + p 0 0 1 1
    + p 0 1 0 1
    + p 0 1 1 0
    + p 1 0 0 1
    + p 1 0 1 0
    + p 1 1 0 0
    - p 0 0 0 1
    - p 0 0 1 0
    - p 0 1 0 0
    - p 1 0 0 0
    + p 0 0 0 0

/--
The mixed four-field coefficient generated by
`zeta1 * (F_μν F^μν)^2`.
-/
def fourPhotonQuarticMixedCoefficient
    (zeta1 f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  fourVariableMixedDifference
    (fun t1 t2 t3 t4 =>
      zeta1 *
        fourPhotonSuperposedInvariant
          t1 t2 t3 t4 f12 f34 f13 f24 f14 f23 ^ 2)

/--
Coefficient extraction from the quartic action gives the three disjoint
field-strength pairings with exact prefactor `8 * zeta1`.
-/
theorem fourPhotonQuarticMixedCoefficient_eq
    (zeta1 f12 f34 f13 f24 f14 f23 : ℝ) :
    fourPhotonQuarticMixedCoefficient
        zeta1 f12 f34 f13 f24 f14 f23 =
      8 * zeta1 *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
  unfold fourPhotonQuarticMixedCoefficient
  unfold fourVariableMixedDifference
  unfold fourPhotonSuperposedInvariant
  unfold fourPhotonPairingSum
  ring

/--
Tree-level four-photon contact amplitude with the overall factor of `i`
removed, defined as the mixed coefficient extracted from the quartic action.
-/
def treeLevelFourPhotonAmplitude
    (lambda Lambda f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  fourPhotonQuarticMixedCoefficient
    (fourPhotonZetaOne lambda Lambda)
    f12 f34 f13 f24 f14 f23

/--
Substituting the action coefficient gives the exact amplitude prefactor
`4 * lambda / Lambda^4`.
-/
theorem treeLevelFourPhotonAmplitude_matching
    (lambda Lambda f12 f34 f13 f24 f14 f23 : ℝ)
    (hLambda : Lambda ≠ 0) :
    treeLevelFourPhotonAmplitude
        lambda Lambda f12 f34 f13 f24 f14 f23 =
      (4 * lambda / Lambda ^ 4) *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
  calc
    treeLevelFourPhotonAmplitude
        lambda Lambda f12 f34 f13 f24 f14 f23 =
      8 * fourPhotonZetaOne lambda Lambda *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 :=
      fourPhotonQuarticMixedCoefficient_eq
        (fourPhotonZetaOne lambda Lambda)
        f12 f34 f13 f24 f14 f23
    _ =
      (4 * lambda / Lambda ^ 4) *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
      unfold fourPhotonZetaOne
      field_simp [hLambda]
      ring

/--
Published CMS–TOTEM 95% confidence upper limit on `|zeta1|`,
in units of `TeV⁻⁴`.

Source: CMS–TOTEM, CERN-EP-2023-143, arXiv:2311.02725.
The publication reports the open bound `|zeta1| < 0.073 TeV⁻⁴`.
-/
def cmsTotemZetaOne95BoundTeVInv4 : ℝ :=
  73 / 1000

/--
A parameter pair lies in the conservative closed envelope of the published
CMS–TOTEM four-photon limit.
-/
def cmsTotemFourPhotonAdmissible
    (lambda Lambda : ℝ) : Prop :=
  abs (fourPhotonZetaOne lambda Lambda) ≤
    cmsTotemZetaOne95BoundTeVInv4

/--
Experimentally admissible parameter theorem.

From
`|lambda / (2 Lambda^4)| ≤ 0.073 TeV⁻⁴`
and `Lambda > 0`, it follows exactly that

`|lambda| / Lambda^4 ≤ 0.146 TeV⁻⁴`.
-/
theorem cmsTotem_admissible_parameter_ratio_bound
    (lambda Lambda : ℝ)
    (hLambda : 0 < Lambda)
    (hAdmissible :
      cmsTotemFourPhotonAdmissible lambda Lambda) :
    abs lambda / Lambda ^ 4 ≤ 73 / 500 := by
  have hPow : 0 < Lambda ^ 4 :=
    pow_pos hLambda 4
  have hDen : 0 < 2 * Lambda ^ 4 :=
    mul_pos (by norm_num) hPow
  have hCoefficient :
      abs lambda / (2 * Lambda ^ 4) ≤ 73 / 1000 := by
    simpa [
      cmsTotemFourPhotonAdmissible,
      cmsTotemZetaOne95BoundTeVInv4,
      fourPhotonZetaOne,
      abs_div,
      abs_of_pos hDen
    ] using hAdmissible
  have hScaled :
      abs lambda ≤
        (73 / 1000 : ℝ) * (2 * Lambda ^ 4) :=
    (div_le_iff₀ hDen).mp hCoefficient
  apply (div_le_iff₀ hPow).mpr
  nlinarith


/--
The complete dimension-eight four-photon interaction used by CMS–TOTEM:

`zeta1 * (F_μν F^μν)^2
 + zeta2 * F_μν F^νρ F_ρλ F^λμ`.

The two Lorentz invariants are represented here by real scalar inputs.
-/
def twoOperatorFourPhotonInteraction
    (zeta1 zeta2 firstInvariant secondInvariant : ℝ) : ℝ :=
  zeta1 * firstInvariant ^ 2 + zeta2 * secondInvariant

/--
The coupling-dependent factor in the CMS–TOTEM anomalous differential
cross section:

`48 zeta1^2 + 40 zeta1 zeta2 + 11 zeta2^2`.

Source: CMS–TOTEM, Phys. Rev. D 110 (2024) 012010, Eq. (1) and the
following differential-cross-section equation; arXiv:2311.02725.
-/
def cmsTotemTwoOperatorCrossSectionShape
    (zeta1 zeta2 : ℝ) : ℝ :=
  48 * zeta1 ^ 2 +
    40 * zeta1 * zeta2 +
    11 * zeta2 ^ 2

/--
Exact positive-definite diagonalization of the two-operator rate shape.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_diagonal
    (zeta1 zeta2 : ℝ) :
    11 * cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 =
      128 * zeta1 ^ 2 +
        (20 * zeta1 + 11 * zeta2) ^ 2 := by
  unfold cmsTotemTwoOperatorCrossSectionShape
  ring

/--
The full two-operator anomalous cross-section shape is nonnegative.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_nonneg
    (zeta1 zeta2 : ℝ) :
    0 ≤ cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 := by
  have hDiagonal :=
    cmsTotemTwoOperatorCrossSectionShape_diagonal zeta1 zeta2
  nlinarith [
    sq_nonneg zeta1,
    sq_nonneg (20 * zeta1 + 11 * zeta2)
  ]

/--
There is no flat direction in the two-operator rate: the quadratic form
vanishes only at the Standard-Model point.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_eq_zero_iff
    (zeta1 zeta2 : ℝ) :
    cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 = 0 ↔
      zeta1 = 0 ∧ zeta2 = 0 := by
  constructor
  · intro hZero
    have hDiagonal :=
      cmsTotemTwoOperatorCrossSectionShape_diagonal zeta1 zeta2
    have hSum :
        128 * zeta1 ^ 2 +
            (20 * zeta1 + 11 * zeta2) ^ 2 = 0 := by
      nlinarith
    have hZetaOne : zeta1 = 0 := by
      nlinarith [
        sq_nonneg zeta1,
        sq_nonneg (20 * zeta1 + 11 * zeta2)
      ]
    subst zeta1
    have hZetaTwo : zeta2 = 0 := by
      nlinarith [sq_nonneg zeta2]
    exact ⟨rfl, hZetaTwo⟩
  · rintro ⟨rfl, rfl⟩
    norm_num [cmsTotemTwoOperatorCrossSectionShape]

/--
The numerator of the anomalous differential cross section, before the
positive factor `1 / (16 * pi^2 * s)`.
-/
def cmsTotemTwoOperatorDifferentialNumerator
    (s t zeta1 zeta2 : ℝ) : ℝ :=
  (s ^ 2 + t ^ 2 + s * t) ^ 2 *
    cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2

/--
The anomalous differential-cross-section numerator is nonnegative.
-/
theorem cmsTotemTwoOperatorDifferentialNumerator_nonneg
    (s t zeta1 zeta2 : ℝ) :
    0 ≤
      cmsTotemTwoOperatorDifferentialNumerator
        s t zeta1 zeta2 := by
  unfold cmsTotemTwoOperatorDifferentialNumerator
  exact mul_nonneg
    (sq_nonneg (s ^ 2 + t ^ 2 + s * t))
    (cmsTotemTwoOperatorCrossSectionShape_nonneg zeta1 zeta2)

/--
The full anomalous differential cross section in the CMS–TOTEM
normalization.
-/
def cmsTotemTwoOperatorDifferentialCrossSection
    (s t zeta1 zeta2 : ℝ) : ℝ :=
  cmsTotemTwoOperatorDifferentialNumerator s t zeta1 zeta2 /
    (16 * Real.pi ^ 2 * s)

/--
For physical `s > 0`, the anomalous differential cross section is
nonnegative.
-/
theorem cmsTotemTwoOperatorDifferentialCrossSection_nonneg
    (s t zeta1 zeta2 : ℝ)
    (hS : 0 < s) :
    0 ≤
      cmsTotemTwoOperatorDifferentialCrossSection
        s t zeta1 zeta2 := by
  unfold cmsTotemTwoOperatorDifferentialCrossSection
  apply div_nonneg
  · exact
      cmsTotemTwoOperatorDifferentialNumerator_nonneg
        s t zeta1 zeta2
  · positivity

/--
The official HEPData record publishes the observed and expected Figure 9
two-dimensional contours separately.  No reconstructed contour is asserted
here from rounded one-dimensional limits.
-/
theorem cmsTotemTwoOperatorExactContourBoundary :
    True := by
  trivial

end

end ZeroDayRestrictedClosures
