import Mathlib

namespace ZeroDayRestrictedClosures

noncomputable section

/--
Dimensionally consistent scalar–photon effective Lagrangian density.

Conventions:
* `phi` and `mPhi` have mass dimension one;
* `X = ∂_μ phi ∂^μ phi` and `Y = F_μν F^μν` have mass dimension four;
* `lambda` is dimensionless;
* `Lambda` has mass dimension one.

The interaction is
`(lambda * Lambda^4 / 2) * (Y / Lambda^4 - X^2 / Lambda^8)^2`.
-/
def dimensionfulInvariantMatchingLagrangian
    (mPhi lambda Lambda phi X Y : ℝ) : ℝ :=
  -(1 / 4 : ℝ) * Y +
    (1 / 2 : ℝ) * X -
    (1 / 2 : ℝ) * mPhi ^ 2 * phi ^ 2 +
    (lambda * Lambda ^ 4 / 2) *
      (Y / Lambda ^ 4 - X ^ 2 / Lambda ^ 8) ^ 2

/--
Expanded form of the same effective Lagrangian.  The pure four-photon
coefficient is `lambda / (2 * Lambda^4)`.
-/
def dimensionfulInvariantMatchingLagrangianExpanded
    (mPhi lambda Lambda phi X Y : ℝ) : ℝ :=
  -(1 / 4 : ℝ) * Y +
    (1 / 2 : ℝ) * X -
    (1 / 2 : ℝ) * mPhi ^ 2 * phi ^ 2 +
    lambda / (2 * Lambda ^ 4) * Y ^ 2 -
    lambda / Lambda ^ 8 * Y * X ^ 2 +
    lambda / (2 * Lambda ^ 12) * X ^ 4

/--
The dimensionful square form expands exactly into the photon quartic,
mixed scalar–photon, and scalar octic operators.
-/
theorem dimensionfulInvariantMatchingLagrangian_eq_expanded
    (mPhi lambda Lambda phi X Y : ℝ)
    (hLambda : Lambda ≠ 0) :
    dimensionfulInvariantMatchingLagrangian
        mPhi lambda Lambda phi X Y =
      dimensionfulInvariantMatchingLagrangianExpanded
        mPhi lambda Lambda phi X Y := by
  unfold dimensionfulInvariantMatchingLagrangian
  unfold dimensionfulInvariantMatchingLagrangianExpanded
  field_simp [hLambda]
  ring

/--
CMS–TOTEM convention:
`L_4gamma = zeta1 * (F_μν F^μν)^2 + ...`.

For the present action, `zeta1 = lambda / (2 * Lambda^4)`.
-/
def fourPhotonZetaOne
    (lambda Lambda : ℝ) : ℝ :=
  lambda / (2 * Lambda ^ 4)

/--
The three disjoint contractions appearing in the four-photon contact
amplitude from `(F_μν F^μν)^2`.
-/
def fourPhotonPairingSum
    (f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  f12 * f34 + f13 * f24 + f14 * f23

/--
The field-strength invariant of four superposed on-shell external photons,
after the individual null terms `F_i · F_i` have vanished.

Here `fij` denotes the contraction `F_i · F_j`.
-/
def fourPhotonSuperposedInvariant
    (t1 t2 t3 t4 f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  2 * (
    t1 * t2 * f12 +
    t3 * t4 * f34 +
    t1 * t3 * f13 +
    t2 * t4 * f24 +
    t1 * t4 * f14 +
    t2 * t3 * f23
  )

/--
Four-variable inclusion–exclusion operator. On a polynomial of total
degree four, it extracts the coefficient of `t1 * t2 * t3 * t4`.
-/
def fourVariableMixedDifference
    (p : ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ :=
  p 1 1 1 1
    - p 0 1 1 1
    - p 1 0 1 1
    - p 1 1 0 1
    - p 1 1 1 0
    + p 0 0 1 1
    + p 0 1 0 1
    + p 0 1 1 0
    + p 1 0 0 1
    + p 1 0 1 0
    + p 1 1 0 0
    - p 0 0 0 1
    - p 0 0 1 0
    - p 0 1 0 0
    - p 1 0 0 0
    + p 0 0 0 0

/--
The mixed four-field coefficient generated by
`zeta1 * (F_μν F^μν)^2`.
-/
def fourPhotonQuarticMixedCoefficient
    (zeta1 f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  fourVariableMixedDifference
    (fun t1 t2 t3 t4 =>
      zeta1 *
        fourPhotonSuperposedInvariant
          t1 t2 t3 t4 f12 f34 f13 f24 f14 f23 ^ 2)

/--
Coefficient extraction from the quartic action gives the three disjoint
field-strength pairings with exact prefactor `8 * zeta1`.
-/
theorem fourPhotonQuarticMixedCoefficient_eq
    (zeta1 f12 f34 f13 f24 f14 f23 : ℝ) :
    fourPhotonQuarticMixedCoefficient
        zeta1 f12 f34 f13 f24 f14 f23 =
      8 * zeta1 *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
  unfold fourPhotonQuarticMixedCoefficient
  unfold fourVariableMixedDifference
  unfold fourPhotonSuperposedInvariant
  unfold fourPhotonPairingSum
  ring

/--
Tree-level four-photon contact amplitude with the overall factor of `i`
removed, defined as the mixed coefficient extracted from the quartic action.
-/
def treeLevelFourPhotonAmplitude
    (lambda Lambda f12 f34 f13 f24 f14 f23 : ℝ) : ℝ :=
  fourPhotonQuarticMixedCoefficient
    (fourPhotonZetaOne lambda Lambda)
    f12 f34 f13 f24 f14 f23

/--
Substituting the action coefficient gives the exact amplitude prefactor
`4 * lambda / Lambda^4`.
-/
theorem treeLevelFourPhotonAmplitude_matching
    (lambda Lambda f12 f34 f13 f24 f14 f23 : ℝ)
    (hLambda : Lambda ≠ 0) :
    treeLevelFourPhotonAmplitude
        lambda Lambda f12 f34 f13 f24 f14 f23 =
      (4 * lambda / Lambda ^ 4) *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
  calc
    treeLevelFourPhotonAmplitude
        lambda Lambda f12 f34 f13 f24 f14 f23 =
      8 * fourPhotonZetaOne lambda Lambda *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 :=
      fourPhotonQuarticMixedCoefficient_eq
        (fourPhotonZetaOne lambda Lambda)
        f12 f34 f13 f24 f14 f23
    _ =
      (4 * lambda / Lambda ^ 4) *
        fourPhotonPairingSum
          f12 f34 f13 f24 f14 f23 := by
      unfold fourPhotonZetaOne
      field_simp [hLambda]
      ring

/--
Published CMS–TOTEM 95% confidence upper limit on `|zeta1|`,
in units of `TeV⁻⁴`.

Source: CMS–TOTEM, CERN-EP-2023-143, arXiv:2311.02725.
The publication reports the open bound `|zeta1| < 0.073 TeV⁻⁴`.
-/
def cmsTotemZetaOne95BoundTeVInv4 : ℝ :=
  73 / 1000

/--
A parameter pair lies in the conservative closed envelope of the published
CMS–TOTEM four-photon limit.
-/
def cmsTotemFourPhotonAdmissible
    (lambda Lambda : ℝ) : Prop :=
  abs (fourPhotonZetaOne lambda Lambda) ≤
    cmsTotemZetaOne95BoundTeVInv4

/--
Experimentally admissible parameter theorem.

From
`|lambda / (2 Lambda^4)| ≤ 0.073 TeV⁻⁴`
and `Lambda > 0`, it follows exactly that

`|lambda| / Lambda^4 ≤ 0.146 TeV⁻⁴`.
-/
theorem cmsTotem_admissible_parameter_ratio_bound
    (lambda Lambda : ℝ)
    (hLambda : 0 < Lambda)
    (hAdmissible :
      cmsTotemFourPhotonAdmissible lambda Lambda) :
    abs lambda / Lambda ^ 4 ≤ 73 / 500 := by
  have hPow : 0 < Lambda ^ 4 :=
    pow_pos hLambda 4
  have hDen : 0 < 2 * Lambda ^ 4 :=
    mul_pos (by norm_num) hPow
  have hCoefficient :
      abs lambda / (2 * Lambda ^ 4) ≤ 73 / 1000 := by
    simpa [
      cmsTotemFourPhotonAdmissible,
      cmsTotemZetaOne95BoundTeVInv4,
      fourPhotonZetaOne,
      abs_div,
      abs_of_pos hDen
    ] using hAdmissible
  have hScaled :
      abs lambda ≤
        (73 / 1000 : ℝ) * (2 * Lambda ^ 4) :=
    (div_le_iff₀ hDen).mp hCoefficient
  apply (div_le_iff₀ hPow).mpr
  nlinarith


/--
The complete dimension-eight four-photon interaction used by CMS–TOTEM:

`zeta1 * (F_μν F^μν)^2
 + zeta2 * F_μν F^νρ F_ρλ F^λμ`.

The two Lorentz invariants are represented here by real scalar inputs.
-/
def twoOperatorFourPhotonInteraction
    (zeta1 zeta2 firstInvariant secondInvariant : ℝ) : ℝ :=
  zeta1 * firstInvariant ^ 2 + zeta2 * secondInvariant

/--
The coupling-dependent factor in the CMS–TOTEM anomalous differential
cross section:

`48 zeta1^2 + 40 zeta1 zeta2 + 11 zeta2^2`.

Source: CMS–TOTEM, Phys. Rev. D 110 (2024) 012010, Eq. (1) and the
following differential-cross-section equation; arXiv:2311.02725.
-/
def cmsTotemTwoOperatorCrossSectionShape
    (zeta1 zeta2 : ℝ) : ℝ :=
  48 * zeta1 ^ 2 +
    40 * zeta1 * zeta2 +
    11 * zeta2 ^ 2

/--
Exact positive-definite diagonalization of the two-operator rate shape.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_diagonal
    (zeta1 zeta2 : ℝ) :
    11 * cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 =
      128 * zeta1 ^ 2 +
        (20 * zeta1 + 11 * zeta2) ^ 2 := by
  unfold cmsTotemTwoOperatorCrossSectionShape
  ring

/--
The full two-operator anomalous cross-section shape is nonnegative.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_nonneg
    (zeta1 zeta2 : ℝ) :
    0 ≤ cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 := by
  have hDiagonal :=
    cmsTotemTwoOperatorCrossSectionShape_diagonal zeta1 zeta2
  nlinarith [
    sq_nonneg zeta1,
    sq_nonneg (20 * zeta1 + 11 * zeta2)
  ]

/--
There is no flat direction in the two-operator rate: the quadratic form
vanishes only at the Standard-Model point.
-/
theorem cmsTotemTwoOperatorCrossSectionShape_eq_zero_iff
    (zeta1 zeta2 : ℝ) :
    cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2 = 0 ↔
      zeta1 = 0 ∧ zeta2 = 0 := by
  constructor
  · intro hZero
    have hDiagonal :=
      cmsTotemTwoOperatorCrossSectionShape_diagonal zeta1 zeta2
    have hSum :
        128 * zeta1 ^ 2 +
            (20 * zeta1 + 11 * zeta2) ^ 2 = 0 := by
      nlinarith
    have hZetaOne : zeta1 = 0 := by
      nlinarith [
        sq_nonneg zeta1,
        sq_nonneg (20 * zeta1 + 11 * zeta2)
      ]
    subst zeta1
    have hZetaTwo : zeta2 = 0 := by
      nlinarith [sq_nonneg zeta2]
    exact ⟨rfl, hZetaTwo⟩
  · rintro ⟨rfl, rfl⟩
    norm_num [cmsTotemTwoOperatorCrossSectionShape]

/--
The numerator of the anomalous differential cross section, before the
positive factor `1 / (16 * pi^2 * s)`.
-/
def cmsTotemTwoOperatorDifferentialNumerator
    (s t zeta1 zeta2 : ℝ) : ℝ :=
  (s ^ 2 + t ^ 2 + s * t) ^ 2 *
    cmsTotemTwoOperatorCrossSectionShape zeta1 zeta2

/--
The anomalous differential-cross-section numerator is nonnegative.
-/
theorem cmsTotemTwoOperatorDifferentialNumerator_nonneg
    (s t zeta1 zeta2 : ℝ) :
    0 ≤
      cmsTotemTwoOperatorDifferentialNumerator
        s t zeta1 zeta2 := by
  unfold cmsTotemTwoOperatorDifferentialNumerator
  exact mul_nonneg
    (sq_nonneg (s ^ 2 + t ^ 2 + s * t))
    (cmsTotemTwoOperatorCrossSectionShape_nonneg zeta1 zeta2)

/--
The full anomalous differential cross section in the CMS–TOTEM
normalization.
-/
def cmsTotemTwoOperatorDifferentialCrossSection
    (s t zeta1 zeta2 : ℝ) : ℝ :=
  cmsTotemTwoOperatorDifferentialNumerator s t zeta1 zeta2 /
    (16 * Real.pi ^ 2 * s)

/--
For physical `s > 0`, the anomalous differential cross section is
nonnegative.
-/
theorem cmsTotemTwoOperatorDifferentialCrossSection_nonneg
    (s t zeta1 zeta2 : ℝ)
    (hS : 0 < s) :
    0 ≤
      cmsTotemTwoOperatorDifferentialCrossSection
        s t zeta1 zeta2 := by
  unfold cmsTotemTwoOperatorDifferentialCrossSection
  apply div_nonneg
  · exact
      cmsTotemTwoOperatorDifferentialNumerator_nonneg
        s t zeta1 zeta2
  · positivity

/--
Published CMS–TOTEM expected 95% confidence limit on `|zeta1|`,
in units of `TeV⁻⁴`, with `zeta2 = 0`.
-/
def cmsTotemExpectedZetaOne95BoundTeVInv4 : ℝ :=
  71 / 1000

/--
Published CMS–TOTEM observed 95% confidence limit on `|zeta2|`,
in units of `TeV⁻⁴`, with `zeta1 = 0`.
-/
def cmsTotemObservedZetaTwo95BoundTeVInv4 : ℝ :=
  3 / 20

/--
Published CMS–TOTEM expected 95% confidence limit on `|zeta2|`,
in units of `TeV⁻⁴`, with `zeta1 = 0`.
-/
def cmsTotemExpectedZetaTwo95BoundTeVInv4 : ℝ :=
  3 / 20

/--
The observed one-parameter limits, encoded only on the two coordinate axes.

This is deliberately not a two-dimensional joint exclusion region:
the publication obtains each bound by setting the other coupling to zero.
-/
def cmsTotemObservedOneParameterAxisEnvelope
    (zeta1 zeta2 : ℝ) : Prop :=
  (zeta2 = 0 ∧
      abs zeta1 ≤ cmsTotemZetaOne95BoundTeVInv4) ∨
    (zeta1 = 0 ∧
      abs zeta2 ≤ cmsTotemObservedZetaTwo95BoundTeVInv4)

/--
The expected one-parameter limits, encoded only on the two coordinate axes.
-/
def cmsTotemExpectedOneParameterAxisEnvelope
    (zeta1 zeta2 : ℝ) : Prop :=
  (zeta2 = 0 ∧
      abs zeta1 ≤ cmsTotemExpectedZetaOne95BoundTeVInv4) ∨
    (zeta1 = 0 ∧
      abs zeta2 ≤ cmsTotemExpectedZetaTwo95BoundTeVInv4)

/--
The expected `zeta1` axis limit is stronger than the observed limit,
while the observed and expected `zeta2` axis limits coincide at the
published precision.
-/
theorem cmsTotem_oneParameterAxisLimit_calibration :
    cmsTotemExpectedZetaOne95BoundTeVInv4 ≤
        cmsTotemZetaOne95BoundTeVInv4 ∧
      cmsTotemObservedZetaTwo95BoundTeVInv4 =
        cmsTotemExpectedZetaTwo95BoundTeVInv4 := by
  norm_num [
    cmsTotemExpectedZetaOne95BoundTeVInv4,
    cmsTotemZetaOne95BoundTeVInv4,
    cmsTotemObservedZetaTwo95BoundTeVInv4,
    cmsTotemExpectedZetaTwo95BoundTeVInv4
  ]

/--
Every point in the expected one-parameter axis envelope also lies in
the observed one-parameter axis envelope.
-/
theorem cmsTotem_expectedAxisEnvelope_subset_observed
    (zeta1 zeta2 : ℝ)
    (hExpected :
      cmsTotemExpectedOneParameterAxisEnvelope zeta1 zeta2) :
    cmsTotemObservedOneParameterAxisEnvelope zeta1 zeta2 := by
  rcases hExpected with hZetaOne | hZetaTwo
  · left
    refine ⟨hZetaOne.1, ?_⟩
    exact le_trans hZetaOne.2 (by
      norm_num [
        cmsTotemExpectedZetaOne95BoundTeVInv4,
        cmsTotemZetaOne95BoundTeVInv4
      ])
  · right
    refine ⟨hZetaTwo.1, ?_⟩
    simpa [
      cmsTotemObservedZetaTwo95BoundTeVInv4,
      cmsTotemExpectedZetaTwo95BoundTeVInv4
    ] using hZetaTwo.2

/--
The Standard-Model point belongs to both published one-parameter
axis envelopes.
-/
theorem cmsTotem_zero_mem_observed_and_expected_axis_envelopes :
    cmsTotemObservedOneParameterAxisEnvelope 0 0 ∧
      cmsTotemExpectedOneParameterAxisEnvelope 0 0 := by
  constructor <;>
    left <;>
    constructor <;>
    norm_num [
      cmsTotemObservedOneParameterAxisEnvelope,
      cmsTotemExpectedOneParameterAxisEnvelope,
      cmsTotemZetaOne95BoundTeVInv4,
      cmsTotemExpectedZetaOne95BoundTeVInv4
    ]

/--
The exact observed and expected Figure 9 joint contours are intentionally
not encoded here because their ellipse coefficients were not present in the
paper source archive or embedded as text in the official vector figure.
-/
def cmsTotemExactJointContourImported : Prop :=
  False

/--
A diagonal positive quadratic form with threshold `a^2 * b^2`
and coordinate-axis intercepts `±a` and `±b`.
-/
def axisMatchedDiagonalQuadratic
    (a b x y : ℝ) : ℝ :=
  b ^ 2 * x ^ 2 + a ^ 2 * y ^ 2

/--
A correlated quadratic form with the same coordinate-axis intercepts.
-/
def axisMatchedCorrelatedQuadratic
    (a b x y : ℝ) : ℝ :=
  b ^ 2 * x ^ 2 + a * b * x * y + a ^ 2 * y ^ 2

theorem axisMatchedCorrelatedQuadratic_four_mul
    (a b x y : ℝ) :
    4 * axisMatchedCorrelatedQuadratic a b x y =
      (2 * b * x + a * y) ^ 2 + 3 * (a * y) ^ 2 := by
  unfold axisMatchedCorrelatedQuadratic
  ring

theorem axisMatchedDiagonalQuadratic_pos
    (a b x y : ℝ)
    (ha : 0 < a)
    (hb : 0 < b)
    (hNonzero : x ≠ 0 ∨ y ≠ 0) :
    0 < axisMatchedDiagonalQuadratic a b x y := by
  unfold axisMatchedDiagonalQuadratic
  rcases hNonzero with hx | hy
  · have hBX : 0 < b ^ 2 * x ^ 2 :=
      mul_pos
        (sq_pos_of_ne_zero (ne_of_gt hb))
        (sq_pos_of_ne_zero hx)
    nlinarith [sq_nonneg (a * y)]
  · have hAY : 0 < a ^ 2 * y ^ 2 :=
      mul_pos
        (sq_pos_of_ne_zero (ne_of_gt ha))
        (sq_pos_of_ne_zero hy)
    nlinarith [sq_nonneg (b * x)]

theorem axisMatchedCorrelatedQuadratic_pos
    (a b x y : ℝ)
    (ha : 0 < a)
    (hb : 0 < b)
    (hNonzero : x ≠ 0 ∨ y ≠ 0) :
    0 < axisMatchedCorrelatedQuadratic a b x y := by
  by_cases hy : y = 0
  · subst y
    have hx : x ≠ 0 := by
      simpa using hNonzero
    have hBX : 0 < b ^ 2 * x ^ 2 :=
      mul_pos
        (sq_pos_of_ne_zero (ne_of_gt hb))
        (sq_pos_of_ne_zero hx)
    simpa [axisMatchedCorrelatedQuadratic] using hBX
  · have hAY : 0 < (a * y) ^ 2 :=
      sq_pos_of_ne_zero (mul_ne_zero (ne_of_gt ha) hy)
    have hDecomposition :=
      axisMatchedCorrelatedQuadratic_four_mul a b x y
    nlinarith [sq_nonneg (2 * b * x + a * y)]

def PositiveAxisMatchedContour
    (a b : ℝ)
    (F : ℝ → ℝ → ℝ) : Prop :=
  (∀ x y, x ≠ 0 ∨ y ≠ 0 → 0 < F x y) ∧
    F a 0 = a ^ 2 * b ^ 2 ∧
    F (-a) 0 = a ^ 2 * b ^ 2 ∧
    F 0 b = a ^ 2 * b ^ 2 ∧
    F 0 (-b) = a ^ 2 * b ^ 2

theorem axisMatchedDiagonal_isPositiveAxisMatchedContour
    (a b : ℝ)
    (ha : 0 < a)
    (hb : 0 < b) :
    PositiveAxisMatchedContour a b
      (fun x y => axisMatchedDiagonalQuadratic a b x y) := by
  unfold PositiveAxisMatchedContour
  constructor
  · intro x y hNonzero
    exact axisMatchedDiagonalQuadratic_pos a b x y ha hb hNonzero
  constructor
  · unfold axisMatchedDiagonalQuadratic
    ring
  constructor
  · unfold axisMatchedDiagonalQuadratic
    ring
  constructor
  · unfold axisMatchedDiagonalQuadratic
    ring
  · unfold axisMatchedDiagonalQuadratic
    ring

theorem axisMatchedCorrelated_isPositiveAxisMatchedContour
    (a b : ℝ)
    (ha : 0 < a)
    (hb : 0 < b) :
    PositiveAxisMatchedContour a b
      (fun x y => axisMatchedCorrelatedQuadratic a b x y) := by
  unfold PositiveAxisMatchedContour
  constructor
  · intro x y hNonzero
    exact axisMatchedCorrelatedQuadratic_pos a b x y ha hb hNonzero
  constructor
  · unfold axisMatchedCorrelatedQuadratic
    ring
  constructor
  · unfold axisMatchedCorrelatedQuadratic
    ring
  constructor
  · unfold axisMatchedCorrelatedQuadratic
    ring
  · unfold axisMatchedCorrelatedQuadratic
    ring

theorem axisMatchedQuadratics_midpoint_values
    (a b : ℝ) :
    axisMatchedDiagonalQuadratic a b (a / 2) (b / 2) =
        (1 / 2 : ℝ) * (a ^ 2 * b ^ 2) ∧
      axisMatchedCorrelatedQuadratic a b (a / 2) (b / 2) =
        (3 / 4 : ℝ) * (a ^ 2 * b ^ 2) := by
  constructor
  · unfold axisMatchedDiagonalQuadratic
    ring
  · unfold axisMatchedCorrelatedQuadratic
    ring

/--
Positive axis intercepts do not identify a unique positive quadratic
joint contour. The witnesses agree on all four axis intercepts and
disagree at the common axis-box midpoint.
-/
theorem positiveAxisLimits_jointContour_nonidentifiable
    (a b : ℝ)
    (ha : 0 < a)
    (hb : 0 < b) :
    ∃ F G : ℝ → ℝ → ℝ,
      PositiveAxisMatchedContour a b F ∧
      PositiveAxisMatchedContour a b G ∧
      F (a / 2) (b / 2) ≠ G (a / 2) (b / 2) := by
  refine ⟨
    fun x y => axisMatchedDiagonalQuadratic a b x y,
    fun x y => axisMatchedCorrelatedQuadratic a b x y,
    axisMatchedDiagonal_isPositiveAxisMatchedContour a b ha hb,
    axisMatchedCorrelated_isPositiveAxisMatchedContour a b ha hb,
    ?_
  ⟩
  change
    axisMatchedDiagonalQuadratic
        a b (a / 2) (b / 2) ≠
      axisMatchedCorrelatedQuadratic
        a b (a / 2) (b / 2)
  have hMidpoint :=
    axisMatchedQuadratics_midpoint_values a b
  rw [hMidpoint.1, hMidpoint.2]
  have haSquare : 0 < a ^ 2 :=
    sq_pos_of_ne_zero (ne_of_gt ha)
  have hbSquare : 0 < b ^ 2 :=
    sq_pos_of_ne_zero (ne_of_gt hb)
  have hProduct : 0 < a ^ 2 * b ^ 2 :=
    mul_pos haSquare hbSquare
  nlinarith

theorem cmsTotemObservedAxisLimits_jointContour_nonidentifiable :
    ∃ F G : ℝ → ℝ → ℝ,
      PositiveAxisMatchedContour
          cmsTotemZetaOne95BoundTeVInv4
          cmsTotemObservedZetaTwo95BoundTeVInv4 F ∧
      PositiveAxisMatchedContour
          cmsTotemZetaOne95BoundTeVInv4
          cmsTotemObservedZetaTwo95BoundTeVInv4 G ∧
      F
          (cmsTotemZetaOne95BoundTeVInv4 / 2)
          (cmsTotemObservedZetaTwo95BoundTeVInv4 / 2) ≠
        G
          (cmsTotemZetaOne95BoundTeVInv4 / 2)
          (cmsTotemObservedZetaTwo95BoundTeVInv4 / 2) := by
  apply positiveAxisLimits_jointContour_nonidentifiable
  · norm_num [cmsTotemZetaOne95BoundTeVInv4]
  · norm_num [cmsTotemObservedZetaTwo95BoundTeVInv4]

theorem cmsTotemExpectedAxisLimits_jointContour_nonidentifiable :
    ∃ F G : ℝ → ℝ → ℝ,
      PositiveAxisMatchedContour
          cmsTotemExpectedZetaOne95BoundTeVInv4
          cmsTotemExpectedZetaTwo95BoundTeVInv4 F ∧
      PositiveAxisMatchedContour
          cmsTotemExpectedZetaOne95BoundTeVInv4
          cmsTotemExpectedZetaTwo95BoundTeVInv4 G ∧
      F
          (cmsTotemExpectedZetaOne95BoundTeVInv4 / 2)
          (cmsTotemExpectedZetaTwo95BoundTeVInv4 / 2) ≠
        G
          (cmsTotemExpectedZetaOne95BoundTeVInv4 / 2)
          (cmsTotemExpectedZetaTwo95BoundTeVInv4 / 2) := by
  apply positiveAxisLimits_jointContour_nonidentifiable
  · norm_num [cmsTotemExpectedZetaOne95BoundTeVInv4]
  · norm_num [cmsTotemExpectedZetaTwo95BoundTeVInv4]


end

end ZeroDayRestrictedClosures
