import intended_unrestricted_state_closure
import restricted_terminal_composition_closure_content

universe u

namespace ZeroDayRestrictedClosures

/--
Reflexive finite reachability generated by a supplied admissible-step relation.
-/
inductive StepReachableBy
    {State : Type u}
    (step : State → State → Prop) :
    State → State → Prop where
  | refl (state : State) :
      StepReachableBy step state state
  | tail
      {initial next terminal : State} :
      step initial next →
      StepReachableBy step next terminal →
      StepReachableBy step initial terminal

/--
Every finite iterate is reachable through the graph of its transition
function.
-/
theorem stepReachableBy_iterate
    {State : Type u}
    (transition : State → State)
    (n : Nat)
    (state : State) :
    StepReachableBy
      (fun current next => next = transition current)
      state
      (iterate transition n state) := by
  induction n generalizing state with
  | zero =>
      exact StepReachableBy.refl state
  | succ n ih =>
      exact
        StepReachableBy.tail
          rfl
          (ih (transition state))

/--
The intended encoded transition never decreases the encoded value.

The proposition is finite and decidable over `Fin 256`, so the existing
computational transition is checked exhaustively.
-/
theorem intendedEncodedStep_value_mono :
    ∀ encoded : Fin 256,
      encoded.val ≤
        (intendedEncodedStep encoded).val := by
  native_decide

/--
Every finite encoded-transition iterate is monotone from its starting value.
-/
theorem intendedEncodedStep_iterate_value_mono
    (n : Nat)
    (encoded : Fin 256) :
    encoded.val ≤
      (iterate intendedEncodedStep n encoded).val := by
  induction n generalizing encoded with
  | zero =>
      exact Nat.le_refl encoded.val
  | succ n ih =>
      simp only [iterate]
      exact
        Nat.le_trans
          (intendedEncodedStep_value_mono encoded)
          (ih (intendedEncodedStep encoded))

/--
The encoded component of an intended state never decreases under iteration.
-/
theorem intendedStep_iterate_encoded_value_mono
    {Payload : Type u}
    (n : Nat)
    (state : IntendedUnrestrictedState Payload) :
    state.encoded.val ≤
      (iterate intendedStep n state).encoded.val := by
  rw [intendedStep_iterate]
  exact
    intendedEncodedStep_iterate_value_mono
      n
      state.encoded

/--
The absorbing encoded value is a fixed point of the existing transition.
-/
theorem intendedEncodedStep_closed :
    intendedEncodedStep intendedClosedEncoded =
      intendedClosedEncoded := by
  native_decide

/--
The payload-preserving closed state is a fixed point of the intended
transition.
-/
theorem intendedClosedState_fixed
    {Payload : Type u}
    (state : IntendedUnrestrictedState Payload) :
    intendedStep (intendedClosedState state) =
      intendedClosedState state := by
  cases state with
  | mk encoded payload =>
      change
        IntendedUnrestrictedState.mk
            (intendedEncodedStep intendedClosedEncoded)
            payload =
          IntendedUnrestrictedState.mk
            intendedClosedEncoded
            payload
      rw [intendedEncodedStep_closed]

/--
Construct a zero-day boundary surface directly from the existing intended
finite-state model.

Existence means finite reachability from the supplied initial state. Boundary
order is strict encoded-value order. Terminal reachability comes from the
existing bounded closure theorem.
-/
def intendedZeroDayBoundarySurface
    {Payload : Type u}
    (initial : IntendedUnrestrictedState Payload) :
    ZeroDayBoundarySurface
      (IntendedUnrestrictedState Payload)
      (fun step => StepReachableBy step)
      (fun state => intendedStep state = state) where
  BoundaryOrder :=
    fun state boundary =>
      state.encoded.val < boundary.encoded.val

  ExistsAt :=
    fun state =>
      ∃ n : Nat,
        iterate intendedStep n initial = state

  Initial := initial

  Terminal := intendedClosedState initial

  AdmissibleStep :=
    fun current next =>
      next = intendedStep current

  initial_exists := by
    exact ⟨0, rfl⟩

  initial_minimal := by
    intro state hLower
    rintro ⟨n, hReach⟩
    subst state

    have hMono :
        initial.encoded.val ≤
          (iterate intendedStep n initial).encoded.val :=
      intendedStep_iterate_encoded_value_mono
        n
        initial

    omega

  terminal_exists := by
    obtain ⟨n, _, hReach⟩ :=
      intendedUnrestrictedStateClosure
        (Payload := Payload)
        initial

    exact ⟨n, hReach⟩

  terminal_reachable := by
    obtain ⟨n, _, hReach⟩ :=
      intendedUnrestrictedStateClosure
        (Payload := Payload)
        initial

    have hPath :
        StepReachableBy
          (fun current next =>
            next = intendedStep current)
          initial
          (iterate intendedStep n initial) :=
      stepReachableBy_iterate
        intendedStep
        n
        initial

    rw [hReach] at hPath
    exact hPath

  terminal_closed := by
    exact intendedClosedState_fixed initial

  no_terminal_extension := by
    intro state hStep

    calc
      state =
          intendedStep (intendedClosedState initial) :=
        hStep
      _ = intendedClosedState initial :=
        intendedClosedState_fixed initial

/--
A concrete initial state for the bounded intended-state model.
-/
def intendedUnitInitialState :
    IntendedUnrestrictedState Unit where
  encoded := ⟨0, by omega⟩
  payload := ()

/--
A concrete zero-day boundary inhabitant using the existing `Fin 256`
transition and `Unit` payload.
-/
def intendedUnitZeroDayBoundarySurface :
    ZeroDayBoundarySurface
      (IntendedUnrestrictedState Unit)
      (fun step => StepReachableBy step)
      (fun state => intendedStep state = state) :=
  intendedZeroDayBoundarySurface
    intendedUnitInitialState

/--
Transport the concrete boundary through the established bridge to an actual
terminal composite.
-/
def intendedUnitTerminalComposite :
    TerminalComposite
      (ZeroDayBoundarySurface
        (IntendedUnrestrictedState Unit)
        (fun step => StepReachableBy step)
        (fun state => intendedStep state = state))
      (IntendedUnrestrictedState Unit)
      (fun state => intendedStep state = state) :=
  zero_day_boundary_surface_implies_terminal_composite
    intendedUnitZeroDayBoundarySurface

/--
The concrete terminal composite contains exactly the payload-preserving closed
state generated from the concrete initial state.
-/
theorem intendedUnitTerminalComposite_terminal_object :
    intendedUnitTerminalComposite.terminal_object =
      intendedClosedState intendedUnitInitialState := by
  rfl

/--
The concrete terminal composite carries a proof that its terminal object is a
fixed point of the existing intended transition.
-/
theorem intendedUnitTerminalComposite_restricted_scope :
    intendedStep intendedUnitTerminalComposite.terminal_object =
      intendedUnitTerminalComposite.terminal_object := by
  exact
    intendedUnitTerminalComposite.restricted_scope_guard

end ZeroDayRestrictedClosures
