import intended_exact_closure_dynamics

universe u

namespace ZeroDayRestrictedClosures

/--
Unknown discrete hidden-sector coupling.

`χDM = 0` means no additional amplification. Positive values represent
increasing hypothetical coupling strength. This is a model parameter, not a
measured dark-matter constant.
-/
def darkMatterStepMultiplier (χDM : Nat) : Nat :=
  χDM + 1

/--
Amplitude generated by repeatedly applying the hypothetical hidden-sector
multiplier.
-/
def darkMatterAmplitude
    (χDM initialAmplitude : Nat) :
    Nat → Nat
  | 0 =>
      initialAmplitude
  | n + 1 =>
      darkMatterAmplitude χDM initialAmplitude n *
        darkMatterStepMultiplier χDM

/--
Exact solution of the hidden-sector amplification recurrence.
-/
theorem darkMatterAmplitude_closed_form
    (χDM initialAmplitude n : Nat) :
    darkMatterAmplitude χDM initialAmplitude n =
      initialAmplitude *
        (darkMatterStepMultiplier χDM) ^ n := by
  induction n with
  | zero =>
      simp [darkMatterAmplitude]
  | succ n ih =>
      simp [
        darkMatterAmplitude,
        ih,
        Nat.pow_succ,
        Nat.mul_assoc
      ]

/--
Couple the hypothetical amplitude to the exact number of transitions remaining
before closure.
-/
def darkMatterClosureAmplitude
    {Payload : Type u}
    (χDM initialAmplitude : Nat)
    (state : IntendedUnrestrictedState Payload) :
    Nat :=
  darkMatterAmplitude
    χDM
    initialAmplitude
    (intendedStateRemainingRank state)

/--
The closure amplitude is exactly the initial amplitude multiplied by the
unknown coupling factor once for every remaining transition.
-/
theorem darkMatterClosureAmplitude_closed_form
    {Payload : Type u}
    (χDM initialAmplitude : Nat)
    (state : IntendedUnrestrictedState Payload) :
    darkMatterClosureAmplitude
        χDM
        initialAmplitude
        state =
      initialAmplitude *
        (darkMatterStepMultiplier χDM) ^
          intendedStateRemainingRank state := by
  exact
    darkMatterAmplitude_closed_form
      χDM
      initialAmplitude
      (intendedStateRemainingRank state)

/--
Zero hidden-sector coupling produces no amplification.
-/
theorem darkMatterAmplitude_zero_coupling
    (initialAmplitude n : Nat) :
    darkMatterAmplitude 0 initialAmplitude n =
      initialAmplitude := by
  rw [darkMatterAmplitude_closed_form]
  simp [darkMatterStepMultiplier]

/--
Concrete rank-255 initial state for the sensitivity test.
-/
def darkMatterExplosionInitialState :
    IntendedUnrestrictedState Unit where
  encoded := ⟨0, by omega⟩
  payload := ()

/--
The sensitivity-test state has exactly 255 transitions remaining.
-/
theorem darkMatterExplosionInitialState_rank :
    intendedStateRemainingRank
        darkMatterExplosionInitialState =
      255 := by
  native_decide

/--
For an unknown coupling, the exact rank-255 response is `(1 + χDM)^255`
when the initial amplitude is one.
-/
theorem darkMatterUnknownCoupling_exact_response
    (χDM : Nat) :
    darkMatterClosureAmplitude
        χDM
        1
        darkMatterExplosionInitialState =
      (χDM + 1) ^ 255 := by
  rw [
    darkMatterClosureAmplitude_closed_form,
    darkMatterExplosionInitialState_rank
  ]
  simp [darkMatterStepMultiplier]

/--
The zero-coupling control remains exactly one.
-/
theorem darkMatterZeroCoupling_control :
    darkMatterClosureAmplitude
        0
        1
        darkMatterExplosionInitialState =
      1 := by
  native_decide

/--
A unit coupling doubles the model amplitude at every nonterminal transition.
The exact closure value is `2^255`.
-/
theorem darkMatterUnitCoupling_exact_explosion :
    darkMatterClosureAmplitude
        1
        1
        darkMatterExplosionInitialState =
      2 ^ 255 := by
  native_decide

/--
Threshold predicate for the closure-amplitude sensitivity test.
-/
def DarkMatterExplosionAtClosure
    {Payload : Type u}
    (χDM initialAmplitude threshold : Nat)
    (state : IntendedUnrestrictedState Payload) :
    Prop :=
  threshold ≤
    darkMatterClosureAmplitude
      χDM
      initialAmplitude
      state

/--
The unit-coupling rank-255 model response exceeds `10^70`.
-/
theorem darkMatterUnitCoupling_exceeds_test_threshold :
    DarkMatterExplosionAtClosure
      1
      1
      (10 ^ 70)
      darkMatterExplosionInitialState := by
  unfold DarkMatterExplosionAtClosure
  rw [darkMatterUnitCoupling_exact_explosion]
  native_decide

/--
The zero-coupling control does not reach amplitude two.
-/
theorem darkMatterZeroCoupling_fails_explosion_threshold :
    ¬ DarkMatterExplosionAtClosure
        0
        1
        2
        darkMatterExplosionInitialState := by
  unfold DarkMatterExplosionAtClosure
  rw [darkMatterZeroCoupling_control]
  native_decide

end ZeroDayRestrictedClosures
