Conditional

RequiredClassesSubsetSH(X) :=
  forall i : ZeroDayRequiredK3nHodgeClasses(X).I,
    ZeroDayRequiredK3nHodgeClasses(X).class(i) in SH^(2 * degree(i))(X,Q)

ZeroDayConditionalClosureSurface(X) :=
  required_subset_SH : RequiredClassesSubsetSH(X)
  closure_from_required_subset :
    RequiredClassesSubsetSH(X) -> ZeroDayClosure(X)

Theorem required_classes_subset_SH_implies_zero_day_closure:
  RequiredClassesSubsetSH(X) -> ZeroDayClosure(X)

Boundary:
  not UnconditionalCompletenessSourceForZeroDayRequiredK3nHodgeClasses


ExternalResult BottiniK3TwoTypeVerbitskyExhaustion(X) :=
  IsK3TwoType(X) ->
  H^*(X,Q) = SH(X,Q)

Source:
  Alessio Bottini,
  The Looijenga-Lunts-Verbitsky Algebra and Verbitsky's Theorem,
  Milan Journal of Mathematics 90 (2022), 403-416.
  Definition 4.4:
    SH(X,Q) is the graded subalgebra generated by H^2(X,Q).
  Corollary 4.6:
    SH(X,Q) is an irreducible LLV subrepresentation.
  Example 5.4:
    if X is of K3^[2]-type, the Verbitsky component is the only
    irreducible component in H^*(X,Q).

Boundary:
  external literature result imported only for K3^[2]-type
  not an internal derivation of Bottini's theorem
  not a claim for K3^[n]-type with n >= 3
  not yet RequiredClassesSubsetSH(X)
