Conditional

RequiredClassesSubsetSH(X) :=
  forall i : ZeroDayRequiredK3nHodgeClasses(X).I,
    ZeroDayRequiredK3nHodgeClasses(X).class(i) in SH^(2 * degree(i))(X,Q)

ZeroDayConditionalClosureSurface(X) :=
  required_subset_SH : RequiredClassesSubsetSH(X)
  closure_from_required_subset :
    RequiredClassesSubsetSH(X) -> ZeroDayClosure(X)

Theorem required_classes_subset_SH_implies_zero_day_closure:
  RequiredClassesSubsetSH(X) -> ZeroDayClosure(X)

Boundary:
  not UnconditionalCompletenessSourceForZeroDayRequiredK3nHodgeClasses


ExternalResult BottiniK3TwoTypeVerbitskyExhaustion(X) :=
  IsK3TwoType(X) ->
  H^*(X,Q) = SH(X,Q)

Source:
  Alessio Bottini,
  The Looijenga-Lunts-Verbitsky Algebra and Verbitsky's Theorem,
  Milan Journal of Mathematics 90 (2022), 403-416.
  Definition 4.4:
    SH(X,Q) is the graded subalgebra generated by H^2(X,Q).
  Corollary 4.6:
    SH(X,Q) is an irreducible LLV subrepresentation.
  Example 5.4:
    if X is of K3^[2]-type, the Verbitsky component is the only
    irreducible component in H^*(X,Q).

Boundary:
  external literature result imported only for K3^[2]-type
  not an internal derivation of Bottini's theorem
  not a claim for K3^[n]-type with n >= 3
  not yet RequiredClassesSubsetSH(X)


Theorem k3_two_type_one_required_class_in_SH:
  IsK3TwoType(X) ->
  forall i : ZeroDayRequiredK3nHodgeClasses(X).I,
    ZeroDayRequiredK3nHodgeClasses(X).class(i)
      in SH^(2 * degree(i))(X,Q)

Proof:
  Let X be of K3^[2]-type.
  Let i : ZeroDayRequiredK3nHodgeClasses(X).I.

  By ZeroDayRequiredK3nHodgeClasses.class,
      ZeroDayRequiredK3nHodgeClasses(X).class(i)
        in H^(2 * degree(i))(X,Q).

  By BottiniK3TwoTypeVerbitskyExhaustion(X),
      H^*(X,Q) = SH(X,Q).

  Taking the degree-(2 * degree(i)) graded component gives
      H^(2 * degree(i))(X,Q)
        = SH^(2 * degree(i))(X,Q).

  Therefore
      ZeroDayRequiredK3nHodgeClasses(X).class(i)
        in SH^(2 * degree(i))(X,Q).
Qed.

Boundary:
  one arbitrary required-class membership only
  RequiredClassesSubsetSH(X) not yet derived
  K3^[n]-type with n >= 3 not discharged


Theorem k3_two_type_required_classes_subset_SH:
  IsK3TwoType(X) ->
  RequiredClassesSubsetSH(X)

Proof:
  Let X be of K3^[2]-type.
  Unfold RequiredClassesSubsetSH(X).
  Let i : ZeroDayRequiredK3nHodgeClasses(X).I.
  Apply k3_two_type_one_required_class_in_SH(X,i).
Qed.

Boundary:
  this is only forall-i closure of the proved one-class membership
  depends on BottiniK3TwoTypeVerbitskyExhaustion(X)
  K3^[n]-type with n >= 3 is not discharged
  ZeroDayClosure(X) is not invoked
