Conditional

Theorem k3_n_type_full_degree_four_monodromy_fixed_classification:
  For n >= 4 and X of K3^[n]-type, let

    qinv_X in Sym^2 H^2(X,Q) subset H^4(X,Q)

  denote the inverse Beauville-Bogomolov class and let

    h_X := (1/2) c2(X) in H^4(X,Q).

  Then

    H^4(X,Q)^Mon(X)
      =
    Q * qinv_X direct_sum Q * h_X.

  Equivalently, for every c in H^4(X,Q),

    (forall sigma in Mon(X), sigma(c) = c)
      iff
    exists unique (a,s) in Q x Q,
      c = a * qinv_X + s * h_X.

  Moreover, for every monodromy-fixed c with decomposition

    c = a * qinv_X + s * h_X,

  its degree-four quotient and scalar obstruction are

    pi4_X(c) = s * gamma_X

  and

    K3nDegreeFourC2ScalarObstruction(X,n,c) = s,

  where

    gamma_X := (1/2)[c2(X)]
      in H^4(X,Q) / SH^4(X,Q).

Proof:
  Let c in H^4(X,Q) be fixed by every monodromy operator.

  The quotient projection pi4_X is monodromy-equivariant, so

    pi4_X(c)

  is fixed by the full monodromy action on

    Q4_Q(X) := H^4(X,Q) / Sym^2 H^2(X,Q).

  By k3_n_type_degree_four_monodromy_fixed_line,

    Q4_Q(X)^Mon(X) = Q * gamma_X.

  Hence there exists s in Q such that

    pi4_X(c) = s * gamma_X.

  Define

    d := c - s * h_X.

  Since h_X = (1/2)c2(X) is monodromy invariant and

    pi4_X(h_X) = gamma_X,

  the class d is monodromy invariant and

    pi4_X(d) = 0.

  Therefore

    d in Sym^2 H^2(X,Q).

  It remains to compute the fixed subspace of Sym^2 H^2(X,Q).

  By MarkmanK3nMonodromyZariskiClosure(X,n), the image of Mon(X)
  on H^2 is Zariski dense in the relevant orthogonal group up to
  the finite discriminant character.  The finite character acts
  trivially on Sym^2 H^2, so the fixed vectors in Sym^2 H^2 are
  the fixed vectors of the standard orthogonal-group action.

  For a nondegenerate quadratic space V over Q of dimension at least 3,

    (Sym^2 V)^{O(V)}

  is one-dimensional and generated by the inverse quadratic form.

  Applied to V = H^2(X,Q) with the Beauville-Bogomolov form, this gives

    (Sym^2 H^2(X,Q))^Mon(X)
      = Q * qinv_X.

  Hence there exists a in Q with

    d = a * qinv_X.

  Therefore

    c = a * qinv_X + s * h_X.

  Conversely, qinv_X is preserved by every isometry of the
  Beauville-Bogomolov form, and c2(X) is a characteristic class of the
  tangent bundle and is preserved by monodromy.  Thus every class of
  the displayed form is monodromy fixed.

  The sum is direct: qinv_X lies in Sym^2 H^2(X,Q), hence

    pi4_X(qinv_X) = 0,

  while

    pi4_X(h_X) = gamma_X != 0

  by MarkmanK3nDegreeFourQuotientLatticeStructure(X,n).
  Therefore qinv_X and h_X are linearly independent, and the
  coefficients a and s are unique.

  Finally, quotienting

    c = a * qinv_X + s * h_X

  kills qinv_X and sends h_X to gamma_X, so

    pi4_X(c) = s * gamma_X.

  Since a monodromy-fixed quotient has finite orbit, apply
  k3_n_type_degree_four_c2_scalar_recovers_finite_orbit_coefficient.
  The recovered coefficient is exactly s, hence

    K3nDegreeFourC2ScalarObstruction(X,n,c) = s.
Qed.


Corollary k3_n_type_fixed_degree_four_SH_criterion:
  For n >= 4 and X of K3^[n]-type and c in H^4(X,Q), if c is fixed by
  the full monodromy group, write uniquely

    c = a * qinv_X + s * (1/2)c2(X).

  Then

    c in SH^4(X,Q)
      iff
    s = 0.

Proof:
  By the theorem,

    pi4_X(c) = s * gamma_X.

  Since gamma_X != 0, this quotient vanishes exactly when s = 0.
  The kernel of pi4_X is SH^4(X,Q).
Qed.


Corollary k3_n_type_markman_kappa2_fixed_coordinates:
  For n >= 4 and X of K3^[n]-type, Markman's relation

    qinv_X = c2(X) + 2 * kappa2_X

  gives the exact fixed-basis coordinates

    kappa2_X
      =
    (1/2) * qinv_X - 1 * ((1/2)c2(X)).

  Thus the c2/2 coordinate of kappa2_X is -1, agreeing with

    K3nDegreeFourC2ScalarObstruction(X,n,kappa2_X) = -1.

Proof:
  Rearrange Markman's identity and apply
  k3_n_type_full_degree_four_monodromy_fixed_classification.
Qed.


Boundary:
  this classifies the full monodromy-fixed rational H^4 subspace for
  n >= 4 into exactly two canonical directions
  no Zero Day required class is asserted to be monodromy fixed
  no class is declared ActuallyRequired
  the theorem does not construct a required-class inventory index
  the theorem does not prove coverage of actual requirements
  the theorem does not define or prove K3n semantic ZeroDayClosure
  if a future independent theorem shows an actual required degree-four
  class is full-monodromy-fixed, its entire obstruction is now exactly
  the single c2/2 coordinate s
  no unconditional closure theorem is claimed
