Standalone closure of the multiplicity-four h=(1,3) subbranch of the
homogeneous q=4, height-three order-13 low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_e5_131_quadratic_lower_split_closed.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=4,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has Artin-reduction h-vector

    h(Cbar/ell*Cbar)=(1,3).

  The exact saturation-linkage table proves

    Hilb_T(t)=2*t^2.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The point of this file is that h=(1,3) stabilizes one full degree earlier than
the already-closed e=5, h=(1,3,1) core.  The degree-three final-cut data therefore
has a common ell^2 factor and reduces to a pair of linear forms.  In the
zerodivisor-lower case the associated colon is already saturated before any
delayed layer appears.  Thus no positive degree-gap defect survives.

Theorem exact_socle_plane_torsion:
  One has

    T_2 ~= C^2,
    T_n=0 for n!=2,
    m_B*T=0,
    Ann_B(T)=m_B.

Proof:
  The exact linkage table gives Hilb_T=2*t^2.  Multiplication by every
  positive-degree element sends T_2 to T_n with n>=3, hence to zero.  Thus
  m_B*T=0.  A unit cannot annihilate a nonzero module, so the annihilator is
  exactly m_B.
Qed.

Theorem parameter_multiplication_is_iso_from_degree_one:
  For every n>=1,

    ell:Cbar_n -> Cbar_(n+1)

  is a vector-space isomorphism.

Proof:
  Since

    Hilb_Cbar(t)=(1+3*t)/(1-t),

  one has

    dim_C Cbar_0=1,
    dim_C Cbar_n=4 for every n>=1.

  Multiplication by ell is injective in every degree because ell is a
  nonzerodivisor.  For n>=1 source and target both have dimension four, so the
  injection is an isomorphism.
Qed.

Write

  d:=deg(f)<=D:=deg(g),
  k:=D-d>=0.

Theorem final_cuts_have_a_linear_baseline:
  There exist unique linear forms

    a,b in Cbar_1

  such that

    fbar=ell^(d-1)*a,
    gbar=ell^(D-1)*b.

  Put

    s:=d-1>=2,
    K_i:=(a,ell^i*b).

  Then

    Lbar:=(fbar,gbar)=ell^s*K_k,

  and K_k is m-primary.  Moreover K_0=(a,b) is m-primary.

Proof:
  By the preceding theorem multiplication by ell^(d-1) gives an isomorphism

    Cbar_1 -> Cbar_d,

  and multiplication by ell^(D-1) gives an isomorphism

    Cbar_1 -> Cbar_D.

  This gives unique a,b and the displayed factorization.  Since Lbar is
  m-primary and ell avoids every minimal prime, K_k is m-primary.

  Since K_k subseteq K_0, every homogeneous prime containing K_0 also contains
  K_k, hence is the homogeneous maximal ideal.  Therefore K_0 is m-primary.
Qed.

Corollary final_cuts_kill_and_do_not_meet_T:
  Put L:=(f,g)B.  Then

    L*T=0,
    L intersect T=0.

Proof:
  Both final generators have degree at least three, while m_B*T=0, so they
  annihilate T.  The ideal L has no component in degree two, whereas T is
  concentrated entirely in degree two, giving the zero intersection.
Qed.

Choose an invertible constant GL_2(C) change of generators

  L=(h,k0)

such that hbar and k0bar are both nonzerodivisors on Cbar.  This is possible
because Lbar is m-primary in the one-dimensional Cohen--Macaulay ring Cbar.

Theorem regularized_annihilators_and_exact_extension:
  With

    D0:=0:_B h,
    E0:=0:_B k0,

  one has

    D0=E0=T.

  There is an exact sequence

    0 -> T -> A -> A0 -> 0,

  where A0:=Cbar/Lbar, and

    Ann_A(T)=m_A.

Proof:
  The final cuts annihilate T.  Conversely, if h*x=0 in B, then

    hbar*xbar=0

  in Cbar.  Regularity of hbar gives xbar=0, hence x belongs to T.  Thus
  0:_B h=T; the proof for k0 is identical.

  The exact sequence follows from L intersect T=0.  Since Ann_B(T)=m_B and
  L*T=0, m_A annihilates T.  Conversely, if z+L annihilates T in A, then
  z*T subseteq L.  But z*T is contained in T and L intersect T=0, so z*T=0
  already in B.  Hence z belongs to m_B.  Therefore Ann_A(T)=m_A.
Qed.

Put

  X:=m_A.

Theorem conormal_maps_reduce_to_the_linear_core:
  One has natural vector-space isomorphisms

    Hom_B(L,A)
      ~= Hom_Cbar(Lbar,X)
      ~= Hom_Cbar(K_k,X).

  If

    epsilon:=(N-1)-dim_C Hom_Cbar(K_k,X),

  then every candidate satisfying the necessary order-13 tangent gate must
  have

    epsilon>=19.

Proof:
  Since T*L=0, every B-linear map L->A has image annihilated by T, hence image
  in Ann_A(T)=X.  Since L intersect T=0, projection identifies L with Lbar as
  a Cbar-module.  This proves the first isomorphism.

  Multiplication by ell^s is injective on Cbar and identifies K_k with
  ell^s*K_k=Lbar, proving the second isomorphism.

  The general conormal exact sequence, with 0:_B h=T and Ann_A(T)=X, gives

    dim_C Hom_B(L,A)=N-1-epsilon.

  Maps I->A vanishing on Q contain Hom_B(L,A).  Therefore the necessary gate

    dim_C Hom_S(I,A)<=N-20

  forces

    N-1-epsilon<=N-20,

  hence epsilon>=19.
Qed.

Theorem universal_multiplication_annihilator_bound:
  For every i>=0,

    (N-1)-dim_C Hom_Cbar(K_i,X)
      <=dim_C(0:_X K_i).

Proof:
  Multiplication defines

    X -> Hom_Cbar(K_i,X),
    z |-> (u |-> u*z).

  Its kernel is exactly 0:_X K_i.  Rank-nullity and inclusion of its image in
  the full Hom space give the inequality.
Qed.

We split according to the lower linear form a.

SECTION REGULAR_LINEAR_LOWER.

Assume a is a nonzerodivisor on Cbar.

Theorem regular_linear_section_has_length_six:
  One has

    0:_B a=T,

    Hilb_(B/aB)(t)=1+3*t+2*t^2,

  and therefore

    length_C(B/aB)=6.

Proof:
  Because m_B*T=0, a kills T.  If a*x=0, regularity of a on Cbar forces x in
  T, proving the kernel statement.

  Hence

    0 -> T(-1)
      -> B(-1)
      --a--> B
      -> B/aB
      -> 0

  is exact.  Using

    Hilb_B=Hilb_Cbar+2*t^2,
    Hilb_Cbar=(1+3*t)/(1-t),

  gives

    Hilb_(B/aB)
      =(1-t)*Hilb_B+t*Hilb_T
      =(1-t)*Hilb_Cbar+Hilb_T
      =1+3*t+2*t^2.
Qed.

Theorem regular_linear_lower_forces_epsilon_at_most_six:
  One has

    epsilon<=6.

Proof:
  Since K_k contains a,

    0:_X K_k subseteq 0:_A a.

  Multiplication by a on finite-dimensional A has kernel and cokernel of equal
  dimension, so

    dim_C(0:_A a)=length_C(A/aA).

  The latter is at most length_C(B/aB)=6.  Apply the universal multiplication
  bound at i=k.
Qed.

Corollary regular_linear_lower_is_closed:
  No REGULAR_LINEAR_LOWER candidate can satisfy the necessary tangent gate.

Proof:
  The gate requires epsilon>=19, whereas epsilon<=6.
Qed.

END REGULAR_LINEAR_LOWER.

SECTION ZERODIVISOR_LINEAR_LOWER.

Assume a is a zerodivisor on Cbar.

Put

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem linear_colon_saturation_defect_has_no_positive_degree_part:
  One has

    (Gsat/G)_n=0

  for every n>=1.

Proof:
  Let x in Gsat be homogeneous of degree n>=1.  Choose m>=0 such that

    ell^m*x*b belongs to (a).

  Write

    ell^m*x*b=a*c

  with c homogeneous of degree n+m.  Since multiplication by ell is an
  isomorphism from degree one onward, multiplication by ell^m gives an
  isomorphism

    Cbar_n -> Cbar_(n+m).

  Hence c=ell^m*c0 for a unique c0 in Cbar_n.  Therefore

    ell^m*(x*b-a*c0)=0.

  Regularity of ell permits cancellation, giving

    x*b=a*c0.

  Thus x belongs to G.
Qed.

Theorem zerodivisor_linear_colon_is_already_saturated:
  One has

    G=Gsat.

Proof:
  Since a is a zerodivisor in the one-dimensional Cohen--Macaulay ring Cbar,
  there is a minimal prime P containing a.  Because K_0=(a,b) is m-primary,
  b is not in P.  Localizing at P gives

    G_P=(a:b)_P=(a)_P,

  a proper ideal.  Since ell is a nonzerodivisor, ell is not in P and becomes
  a unit in Cbar_P, so saturation does not change this localization:

    (Gsat)_P=G_P.

  Hence Gsat is proper.  A proper homogeneous ideal has zero degree-zero part,
  so (Gsat/G)_0=0.  The preceding theorem gives zero in every positive degree.
  Therefore Gsat/G=0.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i

and

  Delta_i
    :=dim_C Hom_Cbar(K_(i-1),X)
      -dim_C Hom_Cbar(K_i,X).

Theorem every_delayed_layer_has_nonpositive_defect:
  For every i>=1,

    Delta_i<=0.

Proof:
  The standard cyclic layer computation gives

    Ann_Cbar(V_i)=(G:ell^(i-1),ell).

  Since G is already ell-saturated,

    G:ell^(i-1)=G

  for every i>=1.  Thus every V_i is the same cyclic module

    Cbar/(G,ell)

  up to grading shift.

  Put

    N_G:=0:_X G.

  For y in N_G, define a map K_i->X by

    a |-> 0,
    ell^i*b |-> y.

  The relation coefficients on ell^i*b lie in G:ell^i=G, so the map is well
  defined.  Its connecting class in the layer sequence is represented by

    ell |-> y,
    G |-> 0.

  It vanishes exactly when y lies in ell*N_G.  Therefore these explicit
  connecting classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_Cbar(Cbar/(G,ell),X)
      =dim_C Hom_Cbar(V_i,X),

  using rank-nullity for multiplication by ell on the finite-dimensional
  module N_G.

  Applying Hom(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  gives Delta_i<=0.
Qed.

Define the baseline deficit

  eta_0
    :=(N-1)-dim_C Hom_Cbar(K_0,X).

Theorem baseline_deficit_is_at_most_six:
  One has

    eta_0<=6.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay core,
  a general constant linear combination

    q=lambda*a+mu*b

  is a linear nonzerodivisor on Cbar.

  Since m_B*T=0, the same computation as in the regular-linear section gives

    0:_B q=T,
    length_C(B/qB)=6.

  Put F:=0:_X K_0.  Since q belongs to K_0,

    F subseteq 0:_A q.

  Hence

    dim_C F
      <=length_C(A/qA)
      <=length_C(B/qB)
      =6.

  Apply the universal multiplication bound at i=0.
Qed.

Theorem zerodivisor_linear_lower_forces_epsilon_at_most_six:
  One has

    epsilon<=6.

Proof:
  Telescoping the definitions of Delta_i gives

    epsilon=eta_0+sum_(i=1)^k Delta_i.

  The baseline theorem gives eta_0<=6 and every delayed layer is nonpositive.
Qed.

Corollary zerodivisor_linear_lower_is_closed:
  No ZERODIVISOR_LINEAR_LOWER candidate can satisfy the necessary tangent gate.

Proof:
  The gate requires epsilon>=19, whereas epsilon<=6.
Qed.

END ZERODIVISOR_LINEAR_LOWER.

Theorem e4_h13_height3_subbranch_closed:
  No homogeneous q=4, ht(Q)=3, e(B)=4 candidate whose saturated-core Artin
  reduction has h-vector

    (1,3)

  can satisfy the necessary order-13 tangent-dimension gate.

Proof:
  The lower linear predecessor a is either regular or a zerodivisor on Cbar.
  Both cases give epsilon<=6, contradicting epsilon>=19.
Qed.

Interpretation:
  This h-vector is simpler than the closed e=5, h=(1,3,1) endpoint.  Its core
  stabilizes in degree one, so every higher cut comes from a linear pair after
  removing the common Noether-parameter power.  A regular lower linear form
  bounds the full defect by a six-dimensional section.  A zerodivisor lower
  linear form forces the colon to be saturated immediately, so all delayed
  Bockstein layers are compensated and the same six-dimensional bound remains.

IMPORTANT_NONCONCLUSION:
  This closes only

    q=4,
    ht(Q)=3,
    e(B)=4,
    h=(1,3).

  It does NOT close the other e=4 h-vectors

    (1,2,1),
    (1,1,1,1),

  nor the remaining e=3 or e=5 h-vectors, q=4 height two, homogeneous q<=3,
  the unrestricted nonhomogeneous local deviation-two frontier, or generic
  F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height3_low_multiplicity_tangent_closure remains open.

NEXT_BOUNDED_OBJECT:
  treat the next exact torsion profile without importing this immediate linear
  saturation conclusion:

    e=5,
    h=(1,2,2),
    Hilb_T=t+t^2+t^3.

  Determine Ann_B(T) and the first degree at which the core becomes
  ell-stable, then recompute the conormal connecting excess.  Stop at the first
  new finite colon or embedded-torsion obstruction.