Standalone saturated-curve-core profile for the homogeneous q=4, height-two
order-13 deviation-two branch.

SCOPE:
  Continue from

    order13_homogeneous_four_quadric_height_split.v
    order13_q4_height3_e3_111_linear_annihilator_height_contradiction_closed.v

  after the q=4, height-three low-multiplicity frontier has been exhausted.

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    length_C(A)=N>=32,

  where Q is minimally generated by exactly four linearly independent
  homogeneous quadrics and

    ht(Q)=2,
    deg(f),deg(g)>=3.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded structural reduction.  It determines
the exact ambient complete-intersection curve containing the saturated
height-two core, proves that the saturated curve-core multiplicity is only
1, 2, or 3, and records the key depth distinction from the already-closed
height-three branch.

No tangent closure is claimed here.

ExternalResult generic_two_element_reduction_inside_height_two_quadrics:
  Over the infinite field C, if a homogeneous ideal generated by a finite
  dimensional vector space of quadrics has height two, then two constant
  linear combinations of those quadrics can be chosen to form a regular
  sequence.

ExternalResult multiplicity_additivity_for_equal_dimension_modules:
  If

    0 -> M' -> M -> M'' -> 0

  is exact and all nonzero modules involved have the same Krull dimension d,
  then their d-dimensional Hilbert-Samuel multiplicities satisfy

    e(M)=e(M')+e(M'').

Theorem height_two_two_quadric_section_model:
  After a constant change of basis in Q_2, choose

    q1,q2,q3,q4

  so that q1,q2 is a regular sequence.  Put

    R:=S/(q1,q2),
    a:=image(q3) in R_2,
    b:=image(q4) in R_2,
    J:=(a,b) subset R.

  Then

    B:=S/Q ~= R/J,
    dim R=2,
    dim B=2,
    ht_R(J)=0.

  Moreover a,b are linearly independent in R_2.

Proof:
  The external generic-selection result gives q1,q2 regular.  Since S has
  dimension four,

    dim R=4-2=2.

  Also

    R/J ~= S/(q1,q2,q3,q4)=S/Q=B.

  The standing height-two hypothesis gives dim B=2, so J has height zero in R.

  If alpha*a+beta*b=0 in R_2, then

    alpha*q3+beta*q4 belongs to (q1,q2)_2.

  Because q1,q2 are homogeneous quadrics, the degree-two part of their ideal is
  exactly span_C(q1,q2).  Thus a nontrivial relation between a,b would give a
  constant linear dependence among q1,q2,q3,q4, contrary to the standing
  four-dimensionality of Q_2.  Hence a,b are independent.
Qed.

Theorem ambient_two_quadric_curve_has_exact_Hilbert_series:
  One has

    Hilb_R(t)
      =(1-t^2)^2/(1-t)^4
      =(1+t)^2/(1-t)^2.

  Consequently

    dim_C R_0=1,
    dim_C R_n=4*n for every n>=1.

  In particular

    dim_C R_1=4,
    dim_C R_2=8.

Proof:
  This is the Hilbert series of a complete intersection of two quadrics in four
  variables.  Expanding

    (1+2*t+t^2)/(1-t)^2

  gives coefficient one in degree zero and 4*n in every positive degree.
Qed.

Corollary projective_ambient_is_a_quartic_genus_one_complete_intersection:
  Let

    X:=Proj(R) subset P^3.

  Then X is the complete-intersection curve of two quadrics.  Its degree is
  four and its Hilbert polynomial is

    P_X(n)=4*n.

  Thus its arithmetic genus is one.
Qed.

Now let

  U:=J^sat

be saturation with respect to the irrelevant maximal ideal of R, and put

  T:=U/J,
  C:=R/U.

Equivalently, if Qsat is the saturation of Q in S, then

  C ~= S/Qsat,
  T ~= H^0_m(B).

Theorem saturation_exact_sequence_and_dimension:
  There is a graded exact sequence

    0 -> T -> B -> C -> 0,

  with T finite length.  Moreover

    U != 0,
    U != R,
    ht_R(U)=0,
    dim C=2.

Proof:
  By definition of saturation, U/J is precisely the irrelevant-maximal torsion
  of R/J=B, hence has finite length and gives the displayed exact sequence.

  The ideal J is nonzero because its degree-two generators a,b are independent,
  so U, which contains J, is nonzero.

  If U=R, then 1 belongs to J:m^infinity, so some power of the irrelevant
  maximal ideal lies in J.  This would make R/J finite length, contradicting

    dim(R/J)=dim B=2.

  Thus U is proper.

  Since quotienting B by the finite-length module T does not change its Krull
  dimension,

    dim C=dim B=2.

  As dim R=2, this says ht_R(U)=0.
Qed.

Theorem saturated_core_has_depth_at_least_one_but_not_yet_two:
  One has

    H^0_m(C)=0,

  and therefore

    depth_m(C)>=1.

  No conclusion

    depth_m(C)=2

  is available from saturation alone.

Proof:
  The quotient C=R/U is saturated by construction, so it has no irrelevant
  maximal torsion.  For a positive-dimensional finitely generated graded
  module this is equivalent to depth at the irrelevant maximal ideal being at
  least one.

  Since dim C=2, Cohen--Macaulayness would require depth two.  Saturation only
  removes H^0_m and does not in general force H^1_m to vanish, so no such
  promotion is made here.
Qed.

This is the first structural difference from the height-three branch: there,
a saturated one-dimensional quotient with H^0_m=0 was automatically
Cohen--Macaulay.  Here the saturated quotient has dimension two, so depth one
is a genuine surviving possibility.

Theorem the_height_two_curve_core_has_multiplicity_at_most_three:
  One has

    e(R)=4,

  and

    e(B)=e(C) in {1,2,3}.

Proof:
  The complete intersection R of two quadrics has multiplicity

    e(R)=2*2=4.

  The nonzero ideal J is an R-module of dimension two.  Indeed R is
  Cohen--Macaulay and therefore unmixed; every associated prime of R is
  minimal of dimension two, and every nonzero submodule of R has support
  containing at least one such minimal prime.

  Apply multiplicity additivity to

    0 -> J -> R -> B -> 0.

  Since J is nonzero of dimension two,

    e(J)>0.

  Since B has dimension two,

    e(B)>0.

  Therefore

    4=e(R)=e(J)+e(B)

  forces

    e(B) in {1,2,3}.

  Finally T has finite length in

    0 -> T -> B -> C -> 0,

  so it contributes no two-dimensional multiplicity.  Hence

    e(C)=e(B).
Qed.

Corollary saturated_projective_curve_degree_profile:
  Let

    Y:=Proj(C)=Proj(S/Qsat).

  The one-dimensional top projective part of Y has degree

    e:=e(C) in {1,2,3}.

  Thus the saturated q=4 height-two core is a proper degree-at-most-three
  projective subcurve of the quartic complete-intersection curve X, possibly
  together with lower-dimensional projective structure that does not alter e.
Qed.

Theorem exact_initial_unsaturated_Hilbert_data:
  For B=R/J one has

    dim_C B_0=1,
    dim_C B_1=4,
    dim_C B_2=6.

Proof:
  J is generated in degree two, so J_0=J_1=0.  Hence B_0=R_0 and B_1=R_1.

  In degree two, J_2 is exactly the two-dimensional span of the independent
  classes a,b.  Since dim R_2=8,

    dim B_2=8-2=6.
Qed.

Corollary exact_initial_saturation_defect_bookkeeping:
  Put

    u1:=dim_C U_1,
    u2:=dim_C U_2.

  Then

    T_0=0,
    dim_C T_1=u1,
    dim_C T_2=u2-2,

  while

    dim_C C_0=1,
    dim_C C_1=4-u1,
    dim_C C_2=8-u2.

  Equivalently

    dim T_1=4-dim C_1,
    dim T_2=6-dim C_2.
Qed.

Theorem at_most_two_independent_linear_saturation_classes:
  One has

    dim_C U_1<=2.

Proof:
  Let Uhat be the homogeneous preimage of U in S.  If U_1 contained three
  independent linear classes, then Uhat would contain three independent linear
  forms.  Their quotient in S has dimension one.  Since

    C=S/Uhat

  is a further quotient, this would force dim C<=1, contradicting dim C=2.
Qed.

Corollary exact_linear_saturation_rank_profile:
  The only possible values are

    dim_C U_1 in {0,1,2}.

  Hence the first saturation defect satisfies

    dim_C T_1 in {0,1,2}.
Qed.

Theorem two_linear_saturation_classes_force_a_line_core:
  If

    dim_C U_1=2,

  then

    C ~= C[s,t]

  as a standard graded C-algebra after a linear change of coordinates, and

    e(C)=1.

Proof:
  Lift a basis of U_1 to two independent linear forms l1,l2 in S_1.  Then

    C=S/Uhat

  is a quotient of

    S/(l1,l2) ~= C[s,t].

  Both rings have Krull dimension two.  The polynomial ring C[s,t] is a domain,
  so every nonzero proper ideal has height at least one and would make the
  quotient have dimension at most one.  Therefore the induced ideal must be
  zero, giving C~=C[s,t].  Its multiplicity is one.
Qed.

Return to the final generators f,g and let their images in C again be denoted
fbar,gbar.

Theorem final_pair_is_a_parameter_pair_on_the_saturated_curve_core:
  The ideal

    (fbar,gbar) subset C

  is m_C-primary.  Thus fbar,gbar form a homogeneous system of parameters of
  the two-dimensional ring C.

Proof:
  Since I=Q+(f,g) is m-primary, the quotient

    S/(Qsat,f,g)

  is a quotient of S/(Q,f,g)=A and is therefore finite-dimensional.  But this
  quotient is exactly

    C/(fbar,gbar).

  Hence (fbar,gbar) is m_C-primary.  As dim C=2, two generators of an
  m-primary ideal form a homogeneous system of parameters.
Qed.

IMPORTANT_NONCONCLUSION:
  Do NOT import the height-three conclusion that the saturated core is
  Cohen--Macaulay.

  In the present height-two branch we know only

    dim C=2,
    depth C>=1,
    e(C) in {1,2,3},
    (fbar,gbar) is a parameter pair.

  If depth C=2, then the parameter pair is a regular sequence and a
  two-dimensional complete-intersection/parameter-ideal analysis becomes
  available.

  If depth C=1, that regular-sequence reduction is invalid.  The obstruction is
  H^1_m(C), equivalently the one-dimensional depth defect / projective embedded
  or deficiency structure of the saturated curve core.

  Also, unlike the height-three section model, no uniform bound such as

    T_n=0 for n>=5

  has been proved here.  The previous argument used vanishing of H^1 on a
  zero-dimensional projective complete intersection.  The present ambient
  scheme X is a projective curve, so that vanishing does not transfer
  automatically.

  Therefore no m^k*T bound, no exact Ann_B(T), and no conormal tangent lower
  bound is claimed in this file.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height3_low_multiplicity_frontier_exhausted.
  q4_height2_saturated_core_profile established.
  not q4_height2_tangent_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the depth-one versus depth-two alternatives for

    C=S/Qsat,

  more precisely enough to control the parameter pair (fbar,gbar) and the
  finite saturation defect T=Qsat/Q.

NEXT_BOUNDED_OBJECT:
  Split only by

    depth_m(C)=2

  versus

    depth_m(C)=1.

  In the depth-two branch, derive the exact parameter-ideal length/multiplicity
  formula for fbar,gbar.  In the depth-one branch, identify the smallest
  deficiency module H^1_m(C) that can survive under four independent quadratic
  equations.  Stop before importing any height-three conormal estimate.