Standalone exclusion of the H11 residual Hilbert state in the homogeneous q=4,
height-two multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from the established multiplicity-one residual profile and the
  repaired H00/H10 endpoints.  Work in

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by exactly four linearly independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Ccore := S/Qsat,

with the multiplicity-one depth-one line quotient

    Qsat subset P=(l1,l2),
    D:=P/Qsat,

and enter only the exact H11 low-degree state

    (u1,u2)=(1,3),
    dim_C D_1=1,
    dim_C D_2=2,
    Hilb_D(t)>=(t+t^2)/(1-t).

No H01 argument is made.  No tangent-space estimate is used.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. H11 IS CYCLIC AND ITS ANNIHILATOR HAS TWO LINEAR GENERATORS
--------------------------------------------------------------------------

Choose l1 so that

    (Qsat)_1=C*l1,

and complete it to the line prime

    P=(l1,l2).

Theorem H11_residual_module_is_cyclic:
  The class

    dbar:=l2 mod Qsat

  generates D, and with

    J:=(Qsat:l2)

  one has

    D ~= S/J(-1).

Proof:
  The module D=P/Qsat is generated by the degree-one images of l1,l2.  The l1
  image is zero because l1 belongs to Qsat, while the l2 image is nonzero because
  dim D_1=1.  Hence dbar generates D.

  Its annihilator is exactly the set of a in S for which a*l2 belongs to Qsat,
  namely J=(Qsat:l2).  The cyclic presentation follows.
Qed.

Corollary H11_annihilator_is_one_dimensional_CM:
  The quotient S/J is one-dimensional Cohen--Macaulay.

Proof:
  The established multiplicity-one residual profile proves that D is nonzero,
  one-dimensional, and Cohen--Macaulay.  Shifting does not change dimension or
  depth, so the same holds for S/J.
Qed.

Theorem H11_annihilator_has_exact_linear_rank_two:
  One has

    dim_C J_1=2.

Proof:
  From D~=S/J(-1),

    dim_C (S/J)_1=dim_C D_2=2.

  Since dim_C S_1=4,

    dim_C J_1=4-2=2.
Qed.

--------------------------------------------------------------------------
2. THE UNKNOWN H11 TAIL IS A SINGLE CONSECUTIVE STRING
--------------------------------------------------------------------------

Theorem H11_exact_hypersurface_annihilator_form:
  After a graded linear change of coordinates there are independent linear
  forms a,b and a homogeneous form F_r of degree r>=2 such that

    J=(a,b,F_r),

  with

    F_r notin (a,b).

Proof:
  Modulo the two-dimensional linear space J_1, the ring S/(J_1) is a polynomial
  ring in two variables.  The image of J has height one because S/J has
  dimension one.  Since S/J is Cohen--Macaulay, this height-one ideal is unmixed.
  In the two-variable UFD every unmixed height-one homogeneous ideal is
  principal.  Thus J=(a,b,F_r).

  The form F_r is not in (a,b), otherwise J would equal its two-linear-generated
  part and have height two instead of height three.  Since J_1 has dimension
  exactly two, r cannot equal one; hence r>=2.
Qed.

Corollary H11_exact_residual_Hilbert_series:
  For some integer r>=2,

    Hilb_D(t)
      = t*(1+t+...+t^(r-1))/(1-t)
      = (t+t^2+...+t^r)/(1-t).

In particular the Artinian-reduction numerator is exactly

    t+t^2+...+t^r.

Proof:
  The quotient S/J is a two-variable hypersurface ring by one degree-r form, so

    Hilb_(S/J)(t)
      =(1-t^r)/(1-t)^2
      =(1+t+...+t^(r-1))/(1-t).

  Shift by one degree using D~=S/J(-1).
Qed.

Thus the previously unknown coefficients beyond t+t^2 cannot branch or grow:
they are consecutive ones ending in one finite degree r.

--------------------------------------------------------------------------
3. THE DISTINGUISHED LINE FORCES l1 INTO THE ANNIHILATOR TWO-PLANE
--------------------------------------------------------------------------

Theorem H11_exact_recovery_of_Qsat_from_J:
  One has

    Qsat=(l1)+l2*J.

Proof:
  The reverse containment is immediate because l1 belongs to Qsat and
  l2*J belongs to Qsat by definition of J.

  Conversely, every q in Qsat lies in P=(l1,l2), so write

    q=l1*A+l2*B.

  Since l1*A belongs to Qsat, also l2*B belongs to Qsat.  Therefore B belongs to
  (Qsat:l2)=J, proving the claimed equality.
Qed.

The H11 value u2=3 gives

    dim_C (Qsat)_2=2+u2=5.

On the other hand

    (Qsat)_2=l1*S_1+l2*J_1.

The two summands have dimensions four and two respectively.

Theorem H11_l1_lies_in_J1:
  One has

    l1 in J_1.

Proof:
  Since the sum has dimension five, the intersection

    l1*S_1 intersect l2*J_1

  has dimension one.

  If l2*j=l1*s for linear j,s, the independent prime linear forms l1,l2 imply
  that l1 divides j.  Thus a nonzero intersection occurs exactly when l1 belongs
  to J_1, and then it is spanned by l1*l2.  Hence l1 belongs to J_1.
Qed.

Choose a second linear form n with

    J_1=span_C(l1,n).

The hypersurface form can then be chosen with

    J=(l1,n,F_r),
    F_r notin (l1,n),
    deg(F_r)=r>=2.

Corollary H11_exact_saturated_core_form:
  One has

    Qsat=(l1,l2*n,l2*F_r).

Proof:
  Substitute J=(l1,n,F_r) into Qsat=(l1)+l2*J and absorb the redundant product
  l1*l2 into the generator l1.
Qed.

--------------------------------------------------------------------------
4. FOUR QUADRICS FORCE A PRINCIPAL QUOTIENT MODULO l1
--------------------------------------------------------------------------

Put

    V:=(Qsat)_2,
    W:=Q_2,
    L:=l1*S_1.

Then

    dim V=5,
    dim W=4,
    dim L=4.

Theorem H11_fourplane_meets_l1S1_in_exact_dimension_three:
  One has

    dim_C(W intersect L)=3.

Proof:
  The dimension formula inside the five-dimensional space V gives

    dim(W intersect L)>=4+4-5=3.

  If the intersection had dimension four, then W=L.  Since Q is generated by
  W, this would give

    Q=(l1*S_1)=l1*m_irr,

  where m_irr is the irrelevant maximal ideal.  The height-one prime (l1)
  contains Q, so ht(Q)<=1, contradicting the standing ht(Q)=2 hypothesis.

  Therefore the intersection dimension is exactly three.
Qed.

Corollary H11_fourplane_plus_l1_recovers_all_quadrics:
  One has

    W+L=V.

  Equivalently, if

    Q':=Q+(l1),

  then modulo l1 the ideal Q' is generated by the unique non-l1 quadratic
  direction of Qsat, namely

    Q'/(l1)=(l2*n)

  inside S/(l1).
Qed.

--------------------------------------------------------------------------
5. SATURATION MAKES THE PRINCIPAL QUOTIENT EXACT
--------------------------------------------------------------------------

Theorem H11_Qprime_has_the_same_saturation:
  One has

    saturation(Q')=Qsat.

Proof:
  There are inclusions

    Q subset Q' subset Qsat.

  Saturation is monotone, Q^sat=Qsat, and Qsat is saturated.  Hence

    Qsat=Q^sat subset (Q')^sat subset Qsat.
Qed.

Lemma saturation_commutes_with_quotient_by_a_member_linear_form:
  If a homogeneous ideal I contains a linear form l, then in S/(l)

    I^sat/(l) = saturation(I/(l)).

Proof:
  Because l belongs to I, the S-module S/I is already an S/(l)-module.  An
  element is killed by a power of the irrelevant maximal ideal of S exactly when
  it is killed by a power of the image irrelevant ideal in S/(l): factors
  involving l act as zero on both sides.  Thus the irrelevant torsion removed by
  saturation is identical before and after passage to the quotient.
Qed.

Lemma nonzero_principal_homogeneous_ideal_in_three_variables_is_saturated:
  In a polynomial ring in three variables over C, every nonzero principal
  homogeneous ideal is saturated with respect to the irrelevant maximal ideal.

Proof:
  Its quotient is a positive-dimensional hypersurface ring and hence
  Cohen--Macaulay of depth two.  In particular it has no irrelevant
  maximal-ideal torsion, which is equivalent to saturation of the principal
  ideal.
Qed.

Apply the two lemmas to Q' and l1.  Since

    Q'/(l1)=(l2*n)

is a nonzero principal homogeneous ideal in the three-variable ring S/(l1), it
is already saturated.  Therefore

    Qsat/(l1)
      =(Q')^sat/(l1)
      =saturation(Q'/(l1))
      =(l2*n).

--------------------------------------------------------------------------
6. THE REQUIRED H11 TAIL NOW CONTRADICTS THE PRINCIPAL QUOTIENT
--------------------------------------------------------------------------

But the exact H11 saturated-core form gives independently

    Qsat/(l1)=(l2*n,l2*F_r)

inside the domain S/(l1).

Combining this with the previous section yields

    (l2*n,l2*F_r)=(l2*n).

Hence

    l2*F_r belongs to (l2*n).

Cancellation of the nonzero element l2 in the domain S/(l1) gives

    F_r belongs to (n) modulo l1,

or equivalently

    F_r belongs to (l1,n)

in S.

This contradicts the exact annihilator presentation

    J=(l1,n,F_r)

with F_r notin (l1,n).

Theorem q4_height2_multiplicity_one_depth_one_H11_excluded:
  No ideal generated by four linearly independent quadrics of height two can
  satisfy all standing multiplicity-one depth-one hypotheses in the H11 state

    (u1,u2)=(1,3).

Proof:
  Sections 1--5 derive the contradiction in Section 6 from exactly those
  hypotheses.
Qed.

Corollary H11_residual_tail_has_no_realizable_terminal_degree:
  Although the abstract one-dimensional Cohen--Macaulay residual module would
  have Hilbert series

    (t+t^2+...+t^r)/(1-t)

  for some r>=2, no value of r is compatible with the original four-quadric
  height-two saturation problem.
Qed.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_EXCLUDED:
  q4_height2_multiplicity_one_depth_one_H11.

ALREADY_CLOSED:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.

IMPORTANT_NONCONCLUSION:
  This file does NOT enter H01.
  It does NOT close the full multiplicity-one depth-one branch.
  It does NOT close q=4 height two.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H11_excluded.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  H01:
    (u1,u2)=(0,2),
    Hilb_D(t)>=(2*t+t^2)/(1-t).

  Determine the exact two-generator Artinian-reduction tail compatible with the
  four-independent-quadric height-two saturation condition.  In particular,
  classify whether the tail is forced to terminate and recover the weakest
  saturated-core normal forms before any tangent estimate.

NEXT_ACTIONS:
  1. Leave H00, H10, and H11.
  2. Stay only in q=4 height-two multiplicity one.
  3. Enter only H01.
  4. Classify the exact two-generator Artinian-reduction tail.
  5. Stop before q<=3 or tangent estimates unless forced by that classification.
