Standalone profile of the remaining unequal-degree zerodivisor lower-cut
subbranch in the homogeneous q=4, height-three, multiplicity-six order-13
endpoint.

SCOPE:
  Work in

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  The preceding branch files prove, for a general linear nonzerodivisor ell,

    Hilb_B(z)=(1+3*z+2*z^2)/(1-z),

    B ~= C[ell]
         direct_sum C[ell](-1)^3
         direct_sum C[ell](-2)^2

  as a graded C[ell]-module, and multiplication by ell^(n-2) identifies B_2
  with B_n for every n>=2.

  Let

    I=Q+(f,g)

  be homogeneous and minimally six-generated, with

    deg(f)=d>=3,
    deg(g)=e>d,
    I m-primary.

  Put

    r:=d-2>=1,
    k:=e-d>0.

  Write uniquely

    f=ell^r*a,
    g=ell^(r+k)*b

  with a,b in B_2, and set

    J_k:=(a,ell^k*b),
    L:=ell^r*J_k,
    A:=B/L.

  The previous commit closes the case in which a is a nonzerodivisor.
  This file assumes that a is a nonzero zerodivisor and quantifies exactly
  how the degree gap k enters through the associated-prime part of a.

This is pseudo-formal mathematical documentation.  It is not Coq and does not
assert generic F_13 algebraicity.

Define

  K_a := 0:_B a,
  s := dim_C (K_a)_2,
  t := dim_C (K_a)_1.

Theorem quadratic_zerodivisor_annihilator_stabilizes_in_degree_two:
  One has

    dim_C (K_a)_n = s

  for every n>=2.

Proof:
  For n>=2, every x in B_n has a unique expression

    x=ell^(n-2)*x_2,
    x_2 in B_2.

  Since ell is a nonzerodivisor on B,

    a*x=0

  if and only if

    a*x_2=0.

  Thus multiplication by ell^(n-2) identifies (K_a)_2 with (K_a)_n.
Qed.

Theorem zerodivisor_support_rank_bounds:
  One has

    1 <= s <= 5,
    0 <= t <= s.

Proof:
  Because a is a nonzero zerodivisor, K_a is nonzero.  If a nonzero homogeneous
  annihilator first occurs in degree at least two, the preceding stabilization
  transports it to degree two; if it occurs in degree one, multiplication by
  ell injects it into degree two.  Hence s>=1.

  Multiplication by a on B_2 cannot have zero image, because

    ell^2*a != 0:

  otherwise regularity of ell would force a=0.  Since dim B_2=6, its kernel
  therefore has dimension at most five, so s<=5.

  Finally multiplication by ell injects (K_a)_1 into (K_a)_2, giving t<=s.
Qed.

Theorem annihilator_has_exact_Noether_parameter_shape:
  As a graded C[ell]-module,

    K_a ~= C[ell](-1)^t
          direct_sum C[ell](-2)^(s-t).

  Equivalently,

    Hilb_(K_a)(z)
      = (t*z + (s-t)*z^2)/(1-z).

Proof:
  The module K_a is a graded submodule of the C[ell]-free module B.  Since ell
  is B-regular, K_a is torsion-free over the PID C[ell], hence graded free.

  Its degree-zero part is zero because a is nonzero.  Its degree-one dimension
  is t, while the preceding theorem says every degree n>=2 has dimension s.
  For a graded free C[ell]-module this forces exactly t summands beginning in
  degree one and s-t additional summands beginning in degree two.
Qed.

Put

  C_a:=B/(a).

Theorem zerodivisor_quadratic_cut_has_exact_Hilbert_function:
  The graded Hilbert function of C_a is

    dim (C_a)_0 = 1,
    dim (C_a)_1 = 4,
    dim (C_a)_2 = 5,
    dim (C_a)_3 = 2+t,
    dim (C_a)_n = s for every n>=4.

Proof:
  Multiplication by a gives the exact graded sequence

    0 -> K_a(-2)
      -> B(-2)
      --times a--> B
      -> C_a
      -> 0.

  In degree n this gives

    dim (C_a)_n
      = dim B_n - dim B_(n-2) + dim (K_a)_(n-2),

  with the negative-degree terms interpreted as zero.

  Insert

    dim B_0=1,
    dim B_1=4,
    dim B_n=6 for n>=2,

  together with the annihilator dimensions above.  The displayed values
  follow immediately.
Qed.

Define the ordinary quadratic pair

  J_0:=(a,b).

Theorem delayed_mprimary_pair_forces_ordinary_pair_mprimary:
  The ideal J_0 is m-primary, and a,b are linearly independent in B_2.

Proof:
  Since

    J_k=(a,ell^k*b) subseteq (a,b)=J_0,

  one has

    rad(J_k) subseteq rad(J_0).

  The left side is the homogeneous maximal ideal m because J_k is m-primary,
  while J_0 is proper and homogeneous, so rad(J_0) is contained in m.  Hence

    rad(J_0)=m.

  If b were a scalar multiple of a, then J_k would be contained in (a), and
  the zerodivisor principal ideal (a) cannot be m-primary in the
  one-dimensional Cohen--Macaulay ring B.  Thus a,b are independent.
Qed.

Recall the already proved equal-degree quadratic-core classification:
  every m-primary ideal generated by two independent quadrics in B has
  Hilbert function

    (1,4,4,1)

  or

    (1,4,4).

Write

  epsilon in {0,1}

so that

  Hilb_(B/J_0)=(1,4,4,epsilon),
  length(B/J_0)=9+epsilon.

Define

  M:=J_0/(a).

Equivalently, inside C_a,

  M=b*C_a.

Theorem associated_support_module_has_exact_Hilbert_profile:
  The graded Hilbert function of M is

    dim M_0 = dim M_1 = 0,
    dim M_2 = 1,
    dim M_3 = 2+t-epsilon,
    dim M_n = s for every n>=4.

Proof:
  There is an exact sequence

    0 -> M -> C_a -> B/J_0 -> 0.

  Subtract the already known Hilbert function of B/J_0 from the exact Hilbert
  function of C_a established above.
Qed.

Theorem support_module_is_generated_over_Cellell_in_degrees_at_most_four:
  As a C[ell]-module, M is generated in degrees 2,3,4.

Proof:
  The ring B is generated as a C[ell]-module by one element in degree zero,
  three in degree one, and two in degree two.  Since M=b*C_a is the image of
  multiplication by the quadratic element b, the corresponding images
  generate M over C[ell] in degrees 2,3,4.
Qed.

Let

  T:=H^0_((ell))(M)

be the C[ell]-torsion submodule of M.

Theorem support_module_torsion_is_confined_to_degrees_two_and_three:
  The C[ell]-module M has rank s, and

    T_n=0

  unless n=2 or n=3.  In particular

    ell^2*T=0.

Proof:
  The Hilbert function of M is constant equal to s for every n>=4, so its
  C[ell]-rank is s.

  By the preceding generation theorem, every minimal homogeneous
  C[ell]-generator of M occurs in degree at most four.  Apply the graded
  structure theorem over the PID C[ell]:

    M = F direct_sum T

  with F free of rank s and T finite ell-primary torsion.

  Every free summand of F begins in degree at most four, so all s free
  summands already contribute to M_4.  But dim M_4=s.  Therefore T_4=0.

  A homogeneous cyclic ell-primary torsion summand occupies consecutive
  degrees starting at the degree of its generator.  Since no minimal
  generator begins after degree four and T_4=0, no torsion can occur in any
  degree >=4.  Since M vanishes below degree two, T is confined to degrees two
  and three.  Hence ell^2*T=0.
Qed.

Corollary support_module_torsion_has_uniform_length_bound:
  One has

    length_C(T)
      <= dim M_2 + dim M_3
      = 3+t-epsilon
      <= 8.
Qed.

Theorem delayed_pair_quotient_is_exactly_a_parameter_delay_of_M:
  There is a natural isomorphism

    J_0/J_k ~= M/ell^k*M.

Proof:
  Modulo the common subideal (a), the ideal J_0 is b*C_a=M while J_k is
  ell^k*b*C_a=ell^k*M.  Taking the quotient gives the result.
Qed.

Define

  tau_k:=length_C(0:_M ell^k).

Theorem exact_delayed_core_length_formula:
  One has

    length_C(B/J_k)
      = 9 + epsilon + k*s + tau_k,

  where

    0 <= tau_k <= 3+t-epsilon <= 8,

  and for every k>=2,

    tau_k=length_C(T).

Proof:
  The exact sequence

    0 -> J_0/J_k
      -> B/J_k
      -> B/J_0
      -> 0

  reduces the problem to length(M/ell^k M).

  Write M=F direct_sum T as above.  The free rank-s part contributes exactly

    k*s

  to the quotient by ell^k.  On the finite torsion part, kernel and cokernel
  of multiplication by ell^k have equal length, hence the torsion contribution
  is

    length(0:_T ell^k)=length(0:_M ell^k)=tau_k.

  The torsion-length bound was proved above.  Since ell^2*T=0, every k>=2
  kills all of T, giving tau_k=length(T).

  Finally length(B/J_0)=9+epsilon.
Qed.

Corollary original_unequal_degree_length_is_quantized:
  The full Artin quotient A=B/(ell^r J_k) has

    N:=length_C(A)
      = 6*r + 9 + epsilon + k*s + tau_k,

  with

    r>=1,
    k>=1,
    s in {1,2,3,4,5},
    epsilon in {0,1},
    0<=tau_k<=8.

Proof:
  Combine the exact length-peeling formula

    N=6*r+length(B/J_k)

  with exact_delayed_core_length_formula.
Qed.

Interpretation:
  The unequal-degree zerodivisor branch no longer contains an uncontrolled
  high-degree parameter.  Its dependence on the degree gap k is exactly

    k*s

  plus a torsion correction of size at most eight, where s is the stable
  annihilator/support rank of the lower quadratic factor.

  Geometrically, s is the multiplicity carried by the one-dimensional part
  left after the zerodivisor cut a; the delayed second cut pays k copies of
  that support rank.

IMPORTANT_NONCONCLUSION:
  This file does NOT yet prove the order-13 tangent gate impossible in the
  zerodivisor lower-cut branch.

  The multiplication-map annihilator can grow with k, so the uniform
  length(E)<20 argument used for the regular lower cut does not automatically
  extend.

  No claim is made for the height-three e(B)<=5 cases, height-two q=4,
  homogeneous q<=3, or the unrestricted nonhomogeneous local frontier.

BOUNDARY:
  The first missing object is now the conormal effect of the exact extension

    0 -> J_k -> J_0 -> M/ell^k M -> 0,

  where

    length(M/ell^k M)=k*s+tau_k,
    tau_k<=8,
    ell^2*T=0.

  One must show that the extra k*s delayed-support length produces enough
  additional B-linear maps J_k -> A to prevent a tangent deficit of twenty,
  or else construct a concrete counterexample.

NEXT_BOUNDED_OBJECT:
  apply Hom_B(-,A) to

    0 -> J_k -> J_0 -> M/ell^k M -> 0

  and compute the contribution of

    Ext^1_B(M/ell^k M,A)

  using the two-degree torsion description above.  Do not return to generic
  semiregularity or Kuga--Satake routes unless this local conormal endpoint is
  first resolved.