Standalone type-two sharpening for the Cohen--Macaulay endpoint of the homogeneous q=4, height-three order-13 deviation-two branch.

SCOPE:
  This file starts from

    order13_homogeneous_four_quadric_height_split.v
    order13_q4_height3_e6_koszul_annihilator_reduction.v

  and treats only the endpoint

    S := C[x1,x2,x3,x4],
    Q generated minimally by four independent quadrics,
    ht(Q)=3,
    B := S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  The e<=5 embedded-torsion height-three cases, the height-two q=4 core, and the unrestricted nonhomogeneous local mu(I)=6 frontier are not treated here.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Theorem multiplicity_six_core_has_forced_h_vector_132:
  Let ell in B_1 be a general linear nonzerodivisor and set

    H := B/(ell).

  Then H is an Artin standard graded C-algebra with Hilbert function

    (1,3,2)

  and zero in every degree >=3.

Proof:
  Since Q has no linear forms and has exactly four independent quadratic generators,

    dim B_0 = 1,
    dim B_1 = 4,
    dim B_2 = dim S_2 - 4 = 10-4 = 6.

  Because ell is B-regular of degree one,

    Hilb_H(n)=Hilb_B(n)-Hilb_B(n-1).

  Hence

    dim H_0=1,
    dim H_1=4-1=3,
    dim H_2=6-4=2.

  For a one-dimensional standard graded Cohen--Macaulay algebra, the multiplicity equals the total length of a linear Artin reduction.  Here

    length(H)=e(B)=6.

  The already determined pieces have total dimension

    1+3+2=6.

  Therefore all higher graded pieces vanish.
Qed.

Corollary multiplicity_six_core_has_forced_Hilbert_series:
  One has

    Hilb_B(t) = (1+3*t+2*t^2)/(1-t).
Qed.

Theorem artin_reduction_has_socle_exactly_degree_two:
  The socle of H is exactly H_2, hence

    dim_C Soc(H)=2.

Proof:
  Since H_n=0 for n>=3,

    H_2 subseteq Soc(H).

  It remains to rule out a nonzero degree-one socle element.

  Write H=P/J with P=C[u,v,w].  The four quadratic generators of Q descend to four independent quadrics generating J, because

    dim P_2=6,
    dim H_2=2,

  so dim J_2=4.

  Suppose 0 != x in H_1 lies in Soc(H).  After a linear coordinate change take x to be the image of u.  Then

    u^2, u*v, u*w in J_2.

  Since J_2 has dimension four, modulo (u) the image of J is generated by at most one quadratic form in C[v,w].  Therefore

    C[v,w]/(J+(u))/(u)

  is a quotient of a two-variable polynomial ring by at most one nonzero equation and cannot be Artinian.

  But H/(u) is a quotient of the Artin algebra H, hence must be Artinian.  Contradiction.

  Thus Soc(H)_1=0, while H_2 is entirely socle.  Therefore Soc(H)=H_2 and has dimension two.
Qed.

Corollary multiplicity_six_core_has_CohenMacaulay_type_two:
  The Cohen--Macaulay type of B is

    type(B)=2.

Proof:
  Cohen--Macaulay type is preserved by quotient by a regular parameter and, for the Artin reduction H, equals dim_C Soc(H)=2.
Qed.

Theorem multiplicity_six_core_has_forced_minimal_resolution:
  The minimal graded S-free resolution of B is

    0 -> S(-5)^2
      -> S(-3)^2 + S(-4)^3
      -> S(-2)^4
      -> S
      -> B
      -> 0.

Proof:
  From the forced Hilbert series,

    Hilb_B(t)
      = (1+3*t+2*t^2)/(1-t)
      = P(t)/(1-t)^4,

  where

    P(t)
      = (1-t)^3*(1+3*t+2*t^2)
      = 1 - 4*t^2 + 2*t^3 + 3*t^4 - 2*t^5.

  The first free module is S(-2)^4 because Q is minimally generated by four quadrics.

  Since B is one-dimensional Cohen--Macaulay in a four-variable polynomial ring, its projective dimension is three.  Its type is two, so the last free module has total rank two.

  The h-polynomial has degree two, hence reg(B)=2.  Therefore a summand S(-j) in homological degree i satisfies j-i<=2.

  Comparing the alternating Betti numerator degree by degree gives

    beta_(2,3)=2.

  The coefficient -2 at degree five, together with reg(B)=2, forces

    beta_(3,5)=2.

  Since the total third Betti number is already two, there are no other third-syzygy summands.  The degree-four coefficient then forces

    beta_(2,4)=3.

  This gives exactly the displayed resolution.
Qed.

Now return to the local two-cut setup from the preceding Koszul-annihilator reduction.

Let B_m denote the localization at the homogeneous maximal ideal.  After a constant GL_2(C) change of the two higher-degree generators, choose

  f in B_m

regular and set

  C0 := B_m/(f).

Let g be the second generator modulo f and define

  A := C0/(g),
  D := 0:_(C0) g.

The preceding file already proves

  length_C(A)=length_C(D)=N

and shows that a dangerous order-13 candidate must satisfy

  dim_C Hom_A(D,A) >= N+20.

Theorem regular_parameter_cut_preserves_type_two:
  C0 is an Artin local Cohen--Macaulay ring of type two:

    dim_C Soc(C0)=2.

Proof:
  Quotient by a nonzerodivisor preserves Cohen--Macaulay type.  Since type(B_m)=2, one has type(C0)=2.  For an Artin local ring, type equals socle dimension.
Qed.

Theorem annihilator_module_has_socle_dimension_two:
  As an A-module,

    Soc_A(D)=Soc(C0).

  Consequently

    dim_C Soc_A(D)=2.

Proof:
  Because g lies in the maximal ideal of C0, every element of Soc(C0) is killed by g, so

    Soc(C0) subseteq D.

  The maximal ideal of A is m_(C0)/(g).  For d in D, the condition

    m_A*d=0

  is equivalent to

    m_(C0)*d=0,

  because g*d=0 already holds by definition of D.  Thus the A-socle of D is exactly the C0-socle.
Qed.

Theorem dual_annihilator_module_is_at_most_two_generated:
  Let

    omega_C0 := Hom_C(C0,C)

  be the canonical module of the Artin local ring C0, and let D^vee:=Hom_C(D,C).

  Then

    D^vee ~= omega_C0 / g*omega_C0.

  In particular

    mu_A(D^vee) <= 2.

Proof:
  Dualize the exact multiplication sequence

    0 -> D -> C0 --g--> C0 -> A -> 0

  over C.  Since vector-space duality is exact, one obtains

    0 -> A^vee -> omega_C0 --g--> omega_C0 -> D^vee -> 0.

  Hence D^vee is the stated cokernel.

  The minimal number of generators of omega_C0 equals type(C0)=2.  Passing to the quotient by g cannot increase the number of generators, so D^vee is at most two-generated over A.
Qed.

Theorem cyclic_annihilator_module_cannot_be_dangerous:
  If D is cyclic as an A-module, then

    D ~= A

  and therefore

    dim_C Hom_A(D,A)=N.

  Hence a cyclic D cannot satisfy the necessary dangerous inequality

    dim_C Hom_A(D,A) >= N+20.

Proof:
  A cyclic A-module D is a quotient of A.  Since

    length(D)=length(A)=N,

  the quotient map has zero-length kernel and is therefore an isomorphism.

  Thus

    Hom_A(D,A) ~= Hom_A(A,A) ~= A,

  whose C-dimension is N.
Qed.

Corollary exact_remaining_e6_type_two_boundary:
  Any dangerous candidate in the homogeneous q=4, ht(Q)=3, e(B)=6 endpoint must produce an A-module D such that

    length(D)=length(A)=N>=32,
    dim Soc_A(D)=2,
    mu_A(D^vee)<=2,
    D is noncyclic,
    dim Hom_A(D,A)>=N+20,

  and D must arise specifically as

    D=0:_(C0)g

  inside a type-two Artin parameter section C0 of the multiplicity-six four-quadric Cohen--Macaulay core.
Qed.

IMPORTANT_NONCONCLUSION:
  No universal inequality

    dim Hom_A(D,A) < N+20

  is proved here for noncyclic equal-length type-two annihilator modules.

  In particular this file does NOT close the e=6 endpoint.

  It does not treat the q=4 height-three e<=5 embedded-torsion cases, the q=4 height-two core, homogeneous q<=3 cases, or the unrestricted nonhomogeneous local deviation-two frontier.

BOUNDARY:
  The first missing object in this endpoint is now narrower:

    either prove that every noncyclic annihilator module D arising from the above type-two four-quadric core satisfies

      dim Hom_A(D,A) < N+20,

    or construct one attaining the reverse inequality and then compute the full embedded tangent and Buchweitz--Flenner semiregularity map.

NEXT_BOUNDED_OBJECT:
  test whether the graded degrees of the original two higher-degree generators, together with the forced resolution and type-two canonical module of B, force D to be cyclic or otherwise bound Hom_A(D,A).  Stop rather than assuming a general Hom bound for arbitrary Artin modules.