Standalone conormal--Ext reduction for the remaining unequal-degree
zerodivisor lower-cut subbranch in the homogeneous q=4, height-three,
multiplicity-six order-13 endpoint.

SCOPE:
  Continue from order13_q4_e6_zerodivisor_lower_cut_profile.v.

  Let B be the one-dimensional Cohen--Macaulay multiplicity-six core, let ell
  be the fixed linear nonzerodivisor, and write

    J_k := (a, ell^k*b),
    J_0 := (a,b),
    L   := ell^r*J_k,
    A   := B/L,
    C_k := B/J_k,
    D_k := J_0/J_k.

  Here

    r>=1,
    k>=1,
    a is a nonzero quadratic zerodivisor,
    J_k and J_0 are m-primary,
    N:=length_C(A),

  and the preceding file proves

    D_k ~= M/ell^k*M,
    length(D_k)=k*s+tau_k,
    1<=s<=5,
    0<=tau_k<=8.

  This file does not close the tangent gate.  It identifies exactly the Ext
  compensation discarded by the earlier multiplication-map lower bound and
  isolates the finite ordinary-pair annihilator which remains to be bounded.

This is pseudo-formal mathematical documentation.  It is not Coq and does not
assert generic F_13 algebraicity.

Theorem exact_conormal_Ext_sequence_for_Jk:
  There is a natural exact sequence of finite-dimensional C-vector spaces

    0 -> Hom_B(C_k,A)
      -> A
      -> Hom_B(J_k,A)
      -> Ext^1_B(C_k,A)
      -> 0.

Proof:
  Apply Hom_B(-,A) to

    0 -> J_k -> B -> C_k -> 0.

  Since B is free over itself,

    Ext^1_B(B,A)=0.

  The map A=Hom_B(B,A) -> Hom_B(J_k,A) is restriction, equivalently
  multiplication by the chosen element of A.  Exactness gives the displayed
  sequence.
Qed.

Define

  h_k := dim_C Hom_B(C_k,A)
       = length_C(0:_A J_k),

  x_k := dim_C Ext^1_B(C_k,A).

Corollary exact_conormal_dimension_identity:
  One has

    dim_C Hom_B(J_k,A)=N-h_k+x_k.
Qed.

Theorem full_tangent_gate_forces_Ext_deficit_twenty:
  If the order-13 necessary tangent gate holds,

    dim_C Hom_S(I,A) <= N-20,

  then

    h_k-x_k >= 20.

Proof:
  Multiplication by ell^r is a B-module isomorphism

    J_k ~= L,

  because ell is a nonzerodivisor.  The previously established maps-killing-Q
  injection gives

    Hom_B(L,A) -> Hom_S(I,A).

  Hence

    dim Hom_S(I,A)
      >= dim Hom_B(J_k,A)
      = N-h_k+x_k.

  Combining this with the assumed upper bound N-20 gives

    h_k-x_k>=20.
Qed.

Interpretation:
  The multiplication-map argument used only

    dim Hom_B(J_k,A) >= N-h_k.

  The exact formula shows that every dimension in Ext^1_B(C_k,A) is genuine
  compensation.  Therefore a dangerous candidate needs not merely a large
  annihilator h_k; it needs an annihilator which exceeds the Ext compensation
  by at least twenty.

Now use the delayed-support extension from the preceding file:

    0 -> J_k -> J_0 -> D_k -> 0.

Theorem delayed_support_Hom_Ext_sequence:
  Applying Hom_B(-,A) gives an exact sequence

    0 -> Hom_B(D_k,A)
      -> Hom_B(J_0,A)
      -> Hom_B(J_k,A)
      -> Ext^1_B(D_k,A)
      -> Ext^1_B(J_0,A).
Qed.

Define

  rho_k := dim_C ker(
             Ext^1_B(D_k,A)
               -> Ext^1_B(J_0,A)).

Corollary exact_delayed_support_conormal_identity:
  One has

    dim_C Hom_B(J_k,A)
      = dim_C Hom_B(J_0,A)
        - dim_C Hom_B(D_k,A)
        + rho_k.

Proof:
  In the preceding exact sequence, the kernel of

    Hom_B(J_0,A) -> Hom_B(J_k,A)

  is Hom_B(D_k,A), while the cokernel of that map is exactly the displayed
  kernel in Ext^1.  Taking dimensions gives the identity.
Qed.

Define the delayed-support conormal defect

  delta_k := dim_C Hom_B(D_k,A)-rho_k.

Then

  dim_C Hom_B(J_k,A)
    = dim_C Hom_B(J_0,A)-delta_k.

Thus the growing length

  length(D_k)=k*s+tau_k

cannot be charged directly against the tangent dimension: only the part of
Hom_B(D_k,A) which is not recovered by the connecting Ext^1 kernel contributes
to delta_k.

Define the ordinary-pair annihilator

  E_0 := 0:_A J_0.

Theorem ordinary_pair_annihilator_vanishes_below_common_factor_order:
  For every n<r,

    (E_0)_n=0.

Proof:
  Let z in B_n represent a class in (E_0)_n.  Since J_0 is generated by the
  two quadrics a,b,

    z*a in L_(n+2),
    z*b in L_(n+2).

  But L=ell^r J_k starts in degree r+2, while n+2<r+2.  Therefore

    z*a=0,
    z*b=0

  already in B.

  The ideal J_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring
  B, so it contains a nonzerodivisor q.  Since z annihilates J_0, it annihilates
  q, and regularity of q forces z=0.
Qed.

Corollary ordinary_pair_multiplication_lower_bound:
  The multiplication map

    A -> Hom_B(J_0,A)

  has kernel E_0.  Hence

    dim_C Hom_B(J_0,A)>=N-length_C(E_0).
Qed.

Corollary finite_two_term_sufficient_gate:
  One has

    dim_C Hom_B(J_k,A)
      >= N-length_C(E_0)-delta_k.

  Consequently the order-13 tangent gate is impossible whenever

    length_C(E_0)+delta_k <= 19.
Qed.

IMPORTANT_NONCONCLUSION:
  No bound

    length(E_0)+delta_k <= 19

  is proved here.

  In particular, this file does not assert that rho_k recovers all k*s free
  support directions.  That is the next missing local calculation.

BOUNDARY:
  The zerodivisor unequal-degree e=6 endpoint is reduced to two finite
  quantities attached to the ordinary quadratic pair and its delayed-support
  extension:

    E_0=0:_A(a,b),

    delta_k
      = dim Hom_B(M/ell^k M,A)
        - dim ker(
            Ext^1_B(M/ell^k M,A)
              -> Ext^1_B(J_0,A)).

  A dangerous candidate must satisfy

    length(E_0)+delta_k >= 20.

NEXT_BOUNDED_OBJECT:
  compute E_0 and delta_k on the free/torsion splitting

    M = F direct_sum T,
    rank_C[ell](F)=s,
    ell^2*T=0.

  First test whether the free quotient F/ell^k F contributes zero net
  delta_k through the connecting Ext^1 map.  If so, only the uniformly bounded
  two-degree torsion T can contribute to the tangent deficit.
