Standalone conormal-rank reduction for the remaining low-multiplicity height-three
subbranch of the homogeneous q=4 order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_homogeneous_four_quadric_height_split.v
    order13_q4_height3_low_multiplicity_saturated_core_profile.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B) in {1,2,3,4,5},
    deg(f),deg(g)>=3.

  Put

    T := H^0_m(B)=Qsat/Q,
    Cbar := B/T.

  The preceding files prove

    T_n=0 for n>=5,
    T_0=0,
    Cbar is one-dimensional Cohen--Macaulay,

  and reduce the saturated higher-degree pair to degree-three data plus powers
  of a Noether parameter.

  This file does not close the tangent gate.  It sharpens the finite torsion
  edge and identifies the first genuinely new two-generator connecting-rank
  obstruction.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
does not assert generic F_13 algebraicity.

Retain the complete-intersection section model from the height split:

  R:=S/(q1,q2,q3),
  J:=(a)R,
  B=R/J,
  Jsat:=saturation(J),
  T=Jsat/J,
  X:=Proj(R).

Then X is the zero-dimensional complete intersection of three quadrics in P^3
of length eight, and

  dim_C R_2=7,
  dim_C R_n=8 for n>=3,
  R_n ~= H^0(X,O_X(n)) for n>=3.

Theorem top_saturation_defect_has_dimension_at_most_one:
  One has

    dim_C T_4 <= 1.

Proof:
  On X the sheaf ideal generated by a is the image of

    O_X(-2) -> O_X.

  Let F be its kernel.  Since X is zero-dimensional,

    H^1(X,F(4))=0.

  Hence global sections give a surjection

    H^0(X,O_X(2)) -> H^0(X,J~(4)).

  The target identifies with Jsat_4 inside R_4 because

    R_4 ~= H^0(X,O_X(4)).

  The ordinary degree-four principal piece J_4 is the image of

    R_2 -> H^0(X,O_X(2)) -> H^0(X,J~(4)).

  Now

    dim H^0(X,O_X(2))=8,
    dim R_2=7,

  and R_2 injects into H^0(X,O_X(2)) because R is one-dimensional
  Cohen--Macaulay.  Therefore replacing the full eight-dimensional source by
  R_2 can lose at most one image dimension.  Thus

    dim(Jsat_4/J_4)<=1,

  which is exactly dim T_4<=1.
Qed.

Theorem first_saturation_defect_has_dimension_at_most_three:
  One has

    dim_C T_1 <= 3.

Proof:
  Since J is generated in degree two,

    J_1=0,

  so

    T_1=Jsat_1.

  The vector space R_1 has dimension four.  If Jsat_1=R_1, then Jsat contains
  the irrelevant ideal generated by R_1, so Proj(R/Jsat) is empty.  But

    Cbar=R/Jsat

  is one-dimensional of positive multiplicity e>=1, hence has nonempty
  projective support.  Therefore Jsat_1 is a proper subspace of R_1 and has
  dimension at most three.
Qed.

Put

  L:=(f,g)B.

Theorem regular_local_combination_of_the_two_final_cuts:
  There is an invertible constant GL_2(C) change of generators

    L=(h,k)

  such that h is a nonzerodivisor on Cbar.

  Moreover

    h in m^3.

Proof:
  The image of L in Cbar is m-primary because Cbar/L*Cbar is a quotient of the
  finite-dimensional algebra A.

  Since Cbar is one-dimensional Cohen--Macaulay, its associated primes are its
  finitely many minimal primes.  No associated prime can contain both images
  of f and g, because then it would contain the m-primary ideal generated by
  them.

  For each associated prime P, the constant pairs (lambda,mu) for which

    lambda*f+mu*g belongs to P

  form a proper C-linear subspace of C^2.  Their finite union cannot fill C^2.
  Choose a pair outside the union and complete it to a GL_2(C) basis.  The
  resulting h avoids every associated prime and is therefore Cbar-regular.

  Since both original generators have degree at least three, every constant
  combination belongs to m^3.
Qed.

Define

  D:=0:_B h.

Theorem selected_principal_colon_lives_in_saturation_torsion:
  One has

    D=0:_T h,

  hence

    D subseteq T.

Proof:
  Apply multiplication by h to

    0 -> T -> B -> Cbar -> 0.

  The kernel on Cbar is zero because h is Cbar-regular.  Therefore the kernel
  on B is exactly the kernel on T.
Qed.

Lemma selected_colon_is_graded_and_has_only_one_possible_top_action:
  The vector space D is graded.  More precisely,

    T_2 direct_sum T_3 direct_sum T_4 subseteq D,

  and the only possibly nonzero contribution of h on T is the degree-three
  part of h acting

    T_1 -> T_4.

Proof:
  Every homogeneous component of h has degree at least three.

  Because T_n=0 for n>=5, every component of T of degree at least two is killed
  by h.  On T_1, every homogeneous component of h of degree at least four also
  lands in degree at least five and vanishes.  Thus only h_3:T_1->T_4 can be
  nonzero.

  Consequently

    D=ker(h_3:T_1->T_4)
      direct_sum T_2 direct_sum T_3 direct_sum T_4,

  proving the claim.
Qed.

Theorem selected_principal_annihilator_has_codimension_at_most_fourteen:
  In A, let

    Ann_A(D):={z in A : z*D=0}.

  Then

    length_C(A/Ann_A(D)) <= 14,

  equivalently

    dim_C Ann_A(D) >= N-14.

Proof:
  The four quadratic minimal generators and the absence of linear generators
  give

    dim A_0=1,
    dim A_1=4,
    dim A_2=6.

  Since D subseteq T and m^4*T=0,

    m_A^4*D=0.

  Therefore every homogeneous piece A_n for n>=4 lies in Ann_A(D).

  It remains to bound the degree-three contribution to the action of A on D.
  For z in A_3, multiplication by z kills D_n for n>=2 because the result lies
  in T_(n+3)=0.  Hence z acts only through

    D_1 -> T_4.

  The preceding bounds give

    dim D_1 <= dim T_1 <=3,
    dim T_4<=1.

  Thus the image of the action map

    A_3 -> Hom_C(D_1,T_4)

  has dimension at most three.

  The quotient A/Ann_A(D) identifies with the image of the full action
  representation A->End_C(D).  Its contribution from degrees zero, one, and
  two has dimension at most

    1+4+6=11,

  its degree-three contribution has dimension at most three, and all higher
  degrees contribute zero.  Therefore

    length(A/Ann_A(D))<=11+3=14.
Qed.

Put

  Hh:=h*B subseteq L,
  M:=L/Hh.

Theorem exact_two_generator_conormal_connecting_sequence:
  There is an exact sequence

    0 -> Hom_B(M,A)
      -> Hom_B(L,A)
      -> Ann_A(D)
      --partial--> Ext^1_B(M,A).

Proof:
  The principal ideal Hh is isomorphic to B/D by multiplication by h.  Hence

    Hom_B(Hh,A)
      ~= Hom_B(B/D,A)
      ~= Ann_A(D).

  Apply Hom_B(-,A) to

    0 -> Hh -> L -> M -> 0.
Qed.

Define

  sigma:=rank_C(partial),
  epsilon:=sigma-dim_C Hom_B(M,A).

Corollary exact_two_generator_conormal_dimension:
  One has

    dim_C Hom_B(L,A)
      = dim_C Ann_A(D)-epsilon.

Proof:
  Exactness gives

    dim Hom_B(L,A)
      = dim Hom_B(M,A)
        + dim Ann_A(D)
        - rank(partial).

  Substitute the definition of epsilon.
Qed.

Theorem order13_tangent_gate_forces_connecting_rank_excess_six:
  If the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A) <= N-20,

  then

    epsilon >= 6.

Proof:
  Maps I->A which vanish on Q contain the natural subspace

    Hom_B(L,A),

  so

    dim Hom_S(I,A)>=dim Hom_B(L,A).

  By the preceding annihilator and conormal bounds,

    dim Hom_B(L,A)
      = dim Ann_A(D)-epsilon
      >= N-14-epsilon.

  If the tangent gate holds, then

    N-14-epsilon <= N-20,

  hence

    epsilon>=6.
Qed.

Interpretation:
  The bounded embedded torsion is not itself large enough to create an
  order-13 tangent deficit.  A surviving low-multiplicity q=4 height-three
  candidate must instead exhibit a genuinely two-generator phenomenon: the
  connecting map

    Ann_A(D) -> Ext^1_B(M,A)

  must have rank at least six larger than the entire space Hom_B(M,A).

  This is the first obstruction that is absent from the q=5 principal-cut
  closure and is not removed by the saturated-core degree compression.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove epsilon<=5 and therefore does NOT close the
  multiplicity e<=5 height-three branch.

  It makes no claim for the q=4 height-two branch, homogeneous q<=3 branches,
  or the unrestricted nonhomogeneous local deviation-two frontier.

BOUNDARY:
  A dangerous q=4, ht(Q)=3, e(B)<=5 candidate must satisfy

    rank(
      Ann_A(D) -> Ext^1_B(M,A)
    )
      - dim_C Hom_B(M,A)
      >= 6,

  for

    D=0:_B h subseteq H^0_m(B),
    M=(f,g)B/hB,

  where h is a constant linear combination of f and g regular on B/H^0_m(B).

NEXT_BOUNDED_OBJECT:
  compute the connecting map explicitly from the cyclic presentation of M.
  Prove its rank excess is at most five, or construct the first concrete
  low-multiplicity q4 height-three example with excess at least six.  Do not
  move to the height-two branch before this rank test is resolved or shown to
  require an open classification theorem.
