Standalone Hilbert--Burch classification of the Cohen--Macaulay multiplicity-six
endpoint of the homogeneous q=4, height-three order-13 deviation-two branch.

SCOPE:
  Start from

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  Earlier branch files prove that after choosing a regular sequence K of three
  quadratic combinations inside Q, the residual link

    J:=K:Q

  is the complete intersection CI(1,1,2), and Q=K:J.

  This file makes that linkage presentation explicit.  It does not prove the
  remaining conormal/annihilator-Hom bound and does not treat the e<=5,
  height-two, q<=3, or unrestricted nonhomogeneous local branches.

This is pseudo-formal mathematical documentation.  It is not Coq and does not
assert generic F_13 algebraicity.

ExternalResult NorthcottDeterminantColonFormula:
  Let R be a Cohen--Macaulay ring.  Suppose

    J=(u1,u2,u3)

  and

    K=(k1,k2,k3)

  are complete intersections of the same grade three, K subset J, and

    (k1,k2,k3)^T = M * (u1,u2,u3)^T

  for a 3-by-3 matrix M over R.  Then

    K:J = K + (det M).

  This is the standard Northcott determinant/linkage formula for an almost
  complete intersection obtained by linking two complete intersections.

ExternalResult HilbertBurchForThreeQuadrics:
  If H is a height-two ideal minimally generated by the three 2-by-2 minors of
  a 2-by-3 matrix of linear forms, then H is perfect and has minimal resolution

    0 -> S(-3)^2 -> S(-2)^3 -> S -> S/H -> 0.

Theorem normalize_residual_complete_intersection:
  After a linear change of coordinates and choice of generators, write

    J=(x,y,q)

  with x,y independent linear forms and q a quadric, forming a regular
  sequence of degrees (1,1,2).

  Choose the three quadratic generators k1,k2,k3 of K.  Because K subset J,
  each has a unique homogeneous expression

    ki = x*ai + y*bi + ci*q,

  where ai,bi are linear forms and ci is a scalar.

  At least one ci is nonzero.  Otherwise K subset (x,y), contradicting
  ht(K)=3.

  A GL_3(C) change of the regular-sequence basis of K therefore normalizes

    c1=c2=0,
    c3=1.

  Replacing q by

    q0:=k3=q+x*a3+y*b3

  preserves J=(x,y,q0).  Thus one may write

    k1=x*a+y*b,
    k2=x*c+y*d,
    k3=q0,

  for linear forms a,b,c,d.
Qed.

Theorem northcott_normal_form_for_Q:
  In the preceding normalization,

    Q=(q0,
       x*a+y*b,
       x*c+y*d,
       a*d-b*c).

Proof:
  Relative to the ordered regular sequences

    J=(x,y,q0),
    K=(k1,k2,q0),

  the inclusion matrix is

    M3 = [[a,b,0],
          [c,d,0],
          [0,0,1]].

  Hence

    det(M3)=a*d-b*c.

  The already established linkage identity gives Q=K:J.  Apply the Northcott
  determinant formula to obtain

    Q=K+(det M3),

  which is exactly the displayed ideal.
Qed.

Define the 2-by-3 matrix of linear forms

  Phi := [[a,c,-y],
          [b,d, x]].

Theorem three_nonsection_quadrics_are_Hilbert_Burch_minors:
  Let

    H := (x*a+y*b,
          x*c+y*d,
          a*d-b*c).

  Then

    H=I_2(Phi).

Proof:
  The three maximal minors of Phi are, up to the harmless ordering/sign
  convention,

    a*d-b*c,
    a*x+b*y,
    c*x+d*y.

  These are exactly the displayed generators of H.
Qed.

Theorem determinantal_core_has_height_two:
  One has

    ht(H)=2.

Proof:
  Since Q=H+(q0) has height three, Krull's principal ideal theorem gives

    ht(H)>=2.

  On the other hand, the ideal of maximal minors of a 2-by-3 matrix has height
  at most

    (2-2+1)*(3-2+1)=2.

  Hence ht(H)=2.
Qed.

Corollary determinantal_core_is_degree_three_Hilbert_Burch:
  The ideal H is perfect of grade two and has minimal graded resolution

    0 -> S(-3)^2
      -> S(-2)^3
      -> S
      -> C:=S/H
      -> 0.

  Consequently C is a two-dimensional Cohen--Macaulay standard graded ring
  with

    Hilb_C(t)
      = (1-3*t^2+2*t^3)/(1-t)^4
      = (1+2*t)/(1-t)^2,

  and therefore

    e(C)=3.

  Geometrically Proj(C) is a degree-three arithmetically Cohen--Macaulay curve
  in P^3 (possibly a degeneration of the twisted-cubic configuration).
Qed.

Theorem q0_is_regular_on_determinantal_core:
  The quadric q0 is a nonzerodivisor on C=S/H.

Proof:
  C is Cohen--Macaulay and ht(H)=2.  If q0 were a zerodivisor, it would lie in
  an associated prime of C.  In a Cohen--Macaulay ring the associated primes
  here are minimal; a minimal component containing q0 would survive with
  dimension two in C/(q0), contradicting

    ht(H+(q0))=ht(Q)=3.

  Thus q0 is C-regular.
Qed.

Corollary multiplicity_six_core_is_quadric_section_of_degree_three_curve:
  Every homogeneous q=4, ht(Q)=3, e(S/Q)=6 endpoint admits the presentation

    Q=(I_2(Phi),q0)

  with Phi a 2-by-3 matrix of linear forms satisfying ht I_2(Phi)=2, and q0 a
  quadratic nonzerodivisor on S/I_2(Phi).

  Therefore

    B=S/Q ~= (S/I_2(Phi))/(q0)

  is a regular quadric section of a degree-three Hilbert--Burch curve ring.

  The multiplicity identity is transparent:

    e(B)=deg(q0)*e(S/I_2(Phi))=2*3=6.
Qed.

Compatibility with the existing forced resolution:
  Taking the Hilbert--Burch resolution of C=S/H and then the mapping cone for
  the regular quadric q0 reproduces

    0 -> S(-5)^2
      -> S(-3)^2 + S(-4)^3
      -> S(-2)^4
      -> S
      -> B
      -> 0,

  matching the previously derived type-two resolution exactly.
Qed.

IMPORTANT_NONCONCLUSION:
  This classification does NOT prove the order-13 tangent gate impossible.
  The two higher-degree cuts f,g still have to be analyzed in the explicit
  ring

    B=(S/I_2(Phi))/(q0).

  In particular, no universal bound on

    dim Hom_A(D,A)

  is inferred solely from the Hilbert--Burch presentation.

BOUNDARY:
  The q=4, ht=3, e=6 branch is no longer an abstract grade-three type-two ACI.
  It is reduced to a regular quadric section of a degree-three Hilbert--Burch
  curve, followed by the two higher-degree cuts.

NEXT_BOUNDED_OBJECT:
  test explicit nonmonomial Hilbert--Burch cores, beginning with the twisted
  cubic minors, and compute the full embedded tangent dimension for concrete
  six-generator Artin quotients in the live N>=32 range.  If these fail, use
  the 2-by-3 presentation to derive a conormal bound rather than reverting to
  an arbitrary Artin-module classification.