Standalone closure of the multiplicity-three h=(1,2) subbranch of the
homogeneous q=4, height-three order-13 low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_degree3_hvector_linkage_impossible.v
    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e4_13_linear_core_closed.v
    order13_q4_height3_e4_121_square_zero_socle_map_closed.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=3,

  and, with

    T:=H^0_m(B),
    C:=Cbar:=B/T,

  a general linear nonzerodivisor ell on C has Artin-reduction h-vector

    h(C/ell*C)=(1,2).

The exact saturation-linkage table proves

  Hilb_C(t)=(1+2*t)/(1-t),
  Hilb_T(t)=t+3*t^2+t^3,
  length_C(T)=5,
  T_n=0 for n>=4,
  m_B^3*T=0.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one structural closure.  The h=(1,2) row has a
unique linear saturation class.  A plane-section analysis shows that the
saturation hull is either generated by that linear class alone or by that
linear class together with one quadratic class.  In the second case the
fourth quadric must use the extra quadratic generator, because otherwise the
saturation quotient would still have positive dimension.  Consequently the
saturation torsion is cyclic in both cases.

That cyclicity identifies an exact length-five annihilator quotient.  The
necessary order-13 tangent gate therefore forces a fifteen-dimensional
conormal deficit.  On the Cohen--Macaulay core, however, every final cut has a
linear predecessor.  A regular lower predecessor gives a section of length at
most eight, while a zerodivisor lower predecessor has already-saturated colon,
so every delayed layer is nonpositive and the same bound eight survives.  The
required deficit fifteen is impossible.

Retain the complete-intersection section model

  R:=S/(q1,q2,q3),
  q:=image of q4 in R,
  U:=saturation(q*R),
  K:=0:_R q.

Then

  B=R/qR,
  C=R/U,
  T=U/qR,

and the established linkage identities are

  U=0:_R K,
  K=0:_R U,
  K(2)~=omega_C.

Also

  Hilb_R(t)=(1+t)^3/(1-t).

Theorem exact_e3_12_residual_Hilbert_series:
  One has

    Hilb_U(t)
      =(t+3*t^2+t^3)/(1-t),

    Hilb_K(t)
      =(2*t^2+t^3)/(1-t),

    Hilb_(R/K)(t)
      =(1+3*t+t^2)/(1-t).

  In particular

    dim_C U_1=1,
    K_1=0,
    dim_C K_2=2.

Proof:
  Since

    Hilb_C(t)=(1+2*t)/(1-t),

  subtracting from

    Hilb_R(t)
      =(1+3*t+3*t^2+t^3)/(1-t)

  gives

    Hilb_U(t)
      =(t+3*t^2+t^3)/(1-t).

  Canonical-module reciprocity gives

    Hilb_omega_C(t)
      =t*(1+2*t^(-1))/(1-t)
      =(2+t)/(1-t).

  Because K(2)~=omega_C,

    Hilb_K(t)
      =t^2*Hilb_omega_C(t)
      =(2*t^2+t^3)/(1-t).

  Subtracting Hilb_K from Hilb_R gives the displayed Hilbert series of R/K.
  Reading the first coefficients gives the final assertions.
Qed.

Choose a nonzero linear form

  v in U_1.

It is unique up to nonzero scalar.

We first determine how many additional quadratic generators U can have.
Let Uhat be the homogeneous preimage of U in S.  Then

  C=S/Uhat,

and v belongs to Uhat_1.  Put

  P:=S/(v),
  J:=Uhat/(v) subset P.

Thus P is a polynomial ring in three variables and

  C=P/J.

Theorem the_plane_ideal_of_the_e3_12_core_is_generated_by_three_quadrics:
  The ideal J has no linear generator and is generated by its three-dimensional
  degree-two piece J_2.

Proof:
  The Hilbert series of C gives

    dim_C C_0=1,
    dim_C C_n=3 for every n>=1.

  Since dim P_1=3, one has J_1=0.  Since dim P_2=6 and dim C_2=3,

    dim_C J_2=3.

  Choose a linear nonzerodivisor ell on C.  The h-vector (1,2) gives the
  C[ell]-module decomposition

    C ~= C[ell] direct_sum C[ell](-1)^2.

  Choose degree-one elements x,y whose classes together with 1 form this free
  C[ell]-basis.  Then every one of

    x^2,
    x*y,
    y^2

  is a C-linear combination of

    ell^2,
    ell*x,
    ell*y.

  Hence there are three quadratic relations whose leading x,y-products are
  respectively x^2, x*y, y^2.  These relations are linearly independent and
  lie in J_2, so they form a basis of J_2.

  Let J0 be the ideal generated by them.  Every monomial containing at least
  two factors from {x,y} reduces, using these relations, to a C[ell]-linear
  combination of 1,x,y.  Therefore P/J0 is generated over C[ell] by

    1,x,y,

  and has Hilbert series at most

    (1+2*t)/(1-t).

  Since J0 is contained in J, P/J0 surjects onto C=P/J, whose Hilbert series is
  exactly (1+2*t)/(1-t).  The Hilbert series must therefore agree in every
  degree and the surjection is an isomorphism.  Hence J=J0 and J is generated
  by its three quadrics.
Qed.

Let W be the span in P_2 of the restrictions of q1,q2,q3.

Theorem only_zero_or_one_quadratic_generator_is_missing_after_restriction:
  One has

    dim_C W in {2,3}.

  Equivalently the kernel of the restriction map

    span_C(q1,q2,q3) -> P_2

  has dimension at most one.

Proof:
  Every restricted qi lies in J_2 because qi vanishes in C.

  If dim W were at most one, then all three restricted quadrics would be
  scalar multiples of one plane quadric, allowing the zero quadric as a
  degenerate case.  Their common projective zero set inside the plane v=0
  would then contain a positive-dimensional plane curve (or the whole plane).

  But

    X:=Proj(R)=V(q1,q2,q3) subset P^3

  is the zero-dimensional complete intersection of three quadrics.  Its
  intersection with the plane v=0 cannot contain a curve.  Thus dim W>=2.

  Since W is spanned by three elements, dim W is two or three.
Qed.

Theorem exact_saturation_generator_dichotomy:
  Exactly one of the following holds.

  PRINCIPAL_U:
    U=vR.

  ONE_QUADRATIC_U:
    After a constant change of basis among q1,q2,q3 there are a nonzero linear
    form u and a quadratic class w such that

      q1=v*u,
      U=(v,w)R,
      w notin vR,
      0:_R v=uR.

Proof:
  If dim W=3, the restrictions of q1,q2,q3 form a basis of the three-dimensional
  space J_2.  Since J is generated by J_2, the preimage Uhat is generated by

    v,q1,q2,q3.

  Passing to R kills q1,q2,q3 and gives U=vR.

  Suppose dim W=2.  The one-dimensional kernel of restriction gives a nonzero
  constant combination of q1,q2,q3 divisible by v.  Rebase the regular
  sequence so that

    q1=v*u

  for a nonzero linear form u.  The remaining restrictions of q2,q3 span a
  two-dimensional subspace of J_2.  Choose a quadratic lift w of a third basis
  element of J_2.  Since J is generated by J_2,

    Uhat=(v,q2,q3,w),

  where q1=v*u is redundant once v is included.  Passing to R gives

    U=(v,w)R,

  and w is not in vR by construction.

  Finally q1,q2,q3 is a regular sequence, so after reordering

    q2,q3,v*u

  is regular.  In S/(q2,q3), the product v*u is a nonzerodivisor, hence v is a
  nonzerodivisor.  Therefore

    (v*u,q2,q3):v=(u,q2,q3).

  Modulo (v*u,q2,q3) this says

    0:_R v=uR.
Qed.

Theorem in_the_one_quadratic_case_the_extra_piece_has_positive_dimension:
  In ONE_QUADRATIC_U,

    Hilb_(vR)(t)
      =(t+2*t^2+t^3)/(1-t),

    Hilb_(U/vR)(t)
      =t^2/(1-t).

  In particular U/vR does not have finite length.

Proof:
  From 0:_R v=uR, multiplication by v identifies

    vR ~= (R/uR)(-1).

  Since q2,q3,u is a regular sequence of degrees 2,2,1,

    Hilb_(R/uR)(t)
      =(1+t)^2/(1-t)
      =(1+2*t+t^2)/(1-t).

  Shifting by one gives the displayed Hilbert series of vR.  Subtracting it
  from

    Hilb_U(t)=(t+3*t^2+t^3)/(1-t)

  gives t^2/(1-t).
Qed.

Theorem the_e3_12_saturation_torsion_is_cyclic:
  The B-module

    T=U/qR

  is cyclic, generated by the degree-one class of v.

Proof:
  In PRINCIPAL_U one has U=vR.  Since q belongs to U_2, there is a linear form
  c with

    q=v*c.

  Hence U/qR is generated by v modulo qR.

  In ONE_QUADRATIC_U write, in degree two,

    q=v*c+lambda*w

  for a linear form c and scalar lambda.

  If lambda=0, then qR is contained in vR.  The quotient U/qR would then
  surject onto U/vR.  The preceding theorem shows U/vR has Hilbert series

    t^2/(1-t)

  and is not finite-dimensional.  But T=U/qR is the finite saturation defect,
  a contradiction.  Therefore lambda is nonzero.

  Rescale w and absorb the scalar so that

    q=v*c+w.

  Then w=q-v*c belongs to (q,v), and therefore

    U=(v,w)R=(v,q)R.

  Modulo qR, U/qR is generated by the class of v.

  Thus T is cyclic in both cases.
Qed.

Put

  J_B:=Ann_B(T).

Theorem exact_e3_12_torsion_annihilator_quotient:
  One has a graded isomorphism

    T ~= (B/J_B)(-1),

  and therefore

    Hilb_(B/J_B)(t)=1+3*t+t^2,
    length_C(B/J_B)=5.

  No Gorenstein assertion for B/J_B is made.

Proof:
  The preceding theorem gives a cyclic generator of T in degree one.  The
  quotient of B by the annihilator of that generator is therefore T shifted
  down by one degree.

  The exact linkage table gives

    Hilb_T(t)=t+3*t^2+t^3.

  Dividing by the degree-one shift gives the displayed Hilbert series and
  length five.
Qed.

Return to the two final cuts.  Put

  L:=(f,g)B,
  A:=B/L,
  X:=Ann_A(T).

Theorem final_cuts_annihilate_torsion_and_leave_an_exact_length_five_quotient:
  One has

    L*T=0,
    L subseteq J_B,
    X=J_B/L,
    A/X ~= B/J_B,
    dim_C X=N-5.

Proof:
  The exact linkage table gives m_B^3*T=0, while deg(f),deg(g)>=3.  Hence both
  final cuts annihilate T and L is contained in J_B.

  The A-module structure on T therefore factors through B->A.  Its annihilator
  in A is exactly J_B/L.  Quotienting gives

    A/X
      =(B/L)/(J_B/L)
      ~=B/J_B.

  The preceding theorem gives length(B/J_B)=5, hence dim X=N-5.
Qed.

Choose a general linear nonzerodivisor

  ell in C_1.

Theorem parameter_multiplication_is_iso_from_degree_one:
  For every n>=1,

    ell:C_n -> C_(n+1)

  is a vector-space isomorphism.

Proof:
  Since

    Hilb_C(t)=(1+2*t)/(1-t),

  one has

    dim_C C_0=1,
    dim_C C_n=3 for every n>=1.

  Multiplication by ell is injective because ell is a nonzerodivisor.  For
  n>=1 source and target have equal dimension three, hence the map is an
  isomorphism.
Qed.

Write

  d:=deg(f)<=D:=deg(g),
  k:=D-d>=0.

Theorem final_cuts_have_linear_predecessors:
  There are unique linear forms

    a,b in C_1

  such that

    fbar=ell^(d-1)*a,
    gbar=ell^(D-1)*b.

  Put

    s:=d-1>=2,
    K_i:=(a,ell^i*b) subset C.

  Then

    Lbar:=(fbar,gbar)C=ell^s*K_k,

  multiplication by ell^s identifies K_k with Lbar, and both K_k and
  K_0=(a,b) are m-primary in C.

Proof:
  The parameter-isomorphism theorem gives the unique degree-one predecessors.
  The displayed factorization is immediate.

  Since C/Lbar is finite-dimensional, Lbar is m-primary.  The parameter ell
  avoids every minimal prime, so removing the common power ell^s does not
  change the radical.  Hence K_k is m-primary.  Since K_k is contained in K_0,
  the larger ideal K_0 is also m-primary.
Qed.

Theorem core_Hom_injects_into_the_actual_conormal_space:
  There is a natural injection

    Hom_C(K_k,X) -> Hom_B(L,A).

Proof:
  The B-action on X factors through C=B/T because X annihilates T.  Projection
  B->C gives a surjection L->Lbar.  Every C-linear map Lbar->X therefore
  composes with L->Lbar and X->A to give a B-linear map L->A, and this
  construction is injective.

  Multiplication by ell^s identifies K_k with Lbar.
Qed.

For every i>=0 define

  eta_i
    :=dim_C X-dim_C Hom_C(K_i,X)
     =(N-5)-dim_C Hom_C(K_i,X).

Theorem tangent_gate_forces_linear_core_deficit_fifteen:
  If the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A)<=N-20,

  then

    eta_k>=15.

Proof:
  Maps I->A vanishing on Q contain Hom_B(L,A), and the preceding theorem gives

    dim Hom_S(I,A)>=dim Hom_C(K_k,X).

  Hence the tangent gate gives

    dim Hom_C(K_k,X)<=N-20.

  Since dim X=N-5,

    eta_k
      =(N-5)-dim Hom_C(K_k,X)
      >=15.
Qed.

Theorem universal_multiplication_annihilator_bound:
  For every i>=0,

    eta_i<=dim_C(0:_X K_i).

Proof:
  Multiplication gives

    X -> Hom_C(K_i,X),
    z |-> (u |-> u*z),

  with kernel exactly 0:_X K_i.  Rank-nullity and inclusion of the image in the
  full Hom space give the displayed bound.
Qed.

Lemma every_regular_linear_section_of_B_has_length_at_most_eight:
  Let r in C_1 be a nonzerodivisor and choose a homogeneous linear lift to B.
  Then

    0:_B r subseteq T,
    length_C(0:_B r)<=5,
    length_C(B/rB)<=8.

Proof:
  If r*x=0 in B, projection to C gives r*xbar=0.  Since r is C-regular,
  xbar=0, so x belongs to T.  Thus 0:_B r is contained in T and has length at
  most five.

  The exact multiplication sequence

    0 -> (0:_B r)(-1)
      -> B(-1)
      --r--> B
      -> B/rB
      -> 0

  gives, after evaluating Hilbert series at t=1,

    length(B/rB)
      =e(B)+length(0:_B r)
      <=3+5
      =8.
Qed.

SECTION REGULAR_LINEAR_LOWER.

Assume a is a nonzerodivisor on C.

Theorem regular_linear_lower_forces_eta_at_most_eight:
  One has

    eta_k<=8.

Proof:
  Since K_k contains a,

    0:_X K_k subseteq 0:_A a.

  Multiplication by a on the finite-dimensional algebra A has kernel and
  cokernel of equal dimension, so

    dim_C(0:_A a)=length_C(A/aA).

  This quotient is a quotient of B/aB.  The regular-section lemma gives

    length_C(A/aA)<=length_C(B/aB)<=8.

  Apply the universal multiplication bound at i=k.
Qed.

Corollary regular_linear_lower_is_closed:
  No REGULAR_LINEAR_LOWER candidate satisfies the necessary order-13 tangent
  gate.

Proof:
  The gate requires eta_k>=15, whereas eta_k<=8.
Qed.

END REGULAR_LINEAR_LOWER.

SECTION ZERODIVISOR_LINEAR_LOWER.

Assume a is a zerodivisor on C.

Put

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem linear_colon_has_no_positive_degree_saturation_defect:
  One has

    (Gsat/G)_n=0

  for every n>=1.

Proof:
  Let x in Gsat be homogeneous of degree n>=1.  Choose m>=0 such that

    ell^m*x*b belongs to (a).

  Write

    ell^m*x*b=a*c

  with c homogeneous of degree n+m.  Since multiplication by ell is an
  isomorphism from degree one onward, multiplication by ell^m gives an
  isomorphism

    C_n -> C_(n+m).

  Hence c=ell^m*c0 for a unique c0 in C_n.  Therefore

    ell^m*(x*b-a*c0)=0.

  Regularity of ell permits cancellation, giving

    x*b=a*c0.

  Thus x belongs to G.
Qed.

Theorem zerodivisor_linear_colon_is_already_saturated:
  One has

    G=Gsat.

Proof:
  Since a is a zerodivisor in the one-dimensional Cohen--Macaulay ring C,
  choose a minimal prime P containing a.  Because K_0=(a,b) is m-primary,
  b is not in P.  Thus

    G_P=(a:b)_P=(a)_P

  is proper.

  The parameter ell is not in P and becomes a unit after localization, so
  saturation by ell does not change this localization:

    (Gsat)_P=G_P.

  Hence Gsat is proper.  A proper homogeneous ideal has zero degree-zero part,
  so (Gsat/G)_0=0.  The preceding theorem gives zero in every positive degree.
  Therefore Gsat=G.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i

and

  Delta_i
    :=dim_C Hom_C(K_(i-1),X)
      -dim_C Hom_C(K_i,X).

Lemma exact_delayed_layer_annihilator:
  V_i is cyclic, generated by the class of ell^(i-1)*b, and

    Ann_C(V_i)=(G:ell^(i-1),ell).

Proof:
  The generator statement is immediate.  If c kills the displayed class, then

    c*ell^(i-1)*b=p*a+r*ell^i*b

  for some p,r.  Hence

    (c-r*ell)*ell^(i-1)*b belongs to (a),

  which gives c in (G:ell^(i-1),ell).  The reverse inclusion is immediate.
Qed.

Theorem every_delayed_layer_has_nonpositive_defect:
  For every i>=1,

    Delta_i<=0.

Proof:
  Since G is already ell-saturated,

    G:ell^(i-1)=G

  for every i>=1.  Thus every V_i is, up to grading shift,

    C/(G,ell).

  Put

    N_G:=0:_X G.

  For y in N_G define a map K_i->X by

    a |-> 0,
    ell^i*b |-> y.

  The relation coefficients on ell^i*b lie in G:ell^i=G, so this map is well
  defined.  Its connecting class in the layer sequence is represented by

    ell |-> y,
    G |-> 0.

  It vanishes exactly when y lies in ell*N_G.  Hence these explicit connecting
  classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_C(C/(G,ell),X)
      =dim_C Hom_C(V_i,X),

  using rank-nullity for multiplication by ell on the finite-dimensional
  module N_G.

  Applying Hom_C(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  therefore gives Delta_i<=0.
Qed.

Theorem baseline_deficit_is_at_most_eight:
  One has

    eta_0<=8.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring C,
  a general constant combination

    r=lambda*a+mu*b

  is a linear nonzerodivisor on C.

  Since r belongs to K_0,

    0:_X K_0 subseteq 0:_A r.

  On finite-dimensional A,

    dim_C(0:_A r)=length_C(A/rA).

  The latter is at most length(B/rB), and the regular-section lemma gives

    length_C(B/rB)<=8.

  Apply the universal multiplication bound at i=0.
Qed.

Theorem zerodivisor_linear_lower_forces_eta_at_most_eight:
  One has

    eta_k<=8.

Proof:
  By definition,

    eta_i-eta_(i-1)=Delta_i.

  Hence

    eta_k=eta_0+sum_(i=1)^k Delta_i.

  The baseline theorem gives eta_0<=8 and every delayed layer is nonpositive.
Qed.

Corollary zerodivisor_linear_lower_is_closed:
  No ZERODIVISOR_LINEAR_LOWER candidate satisfies the necessary order-13
  tangent gate.

Proof:
  The gate requires eta_k>=15, whereas eta_k<=8.
Qed.

END ZERODIVISOR_LINEAR_LOWER.

Theorem e3_h12_height3_subbranch_closed:
  No homogeneous q=4, ht(Q)=3, e(B)=3 candidate whose saturated-core Artin
  reduction has h-vector

    (1,2)

  can satisfy the necessary order-13 tangent-dimension gate.

Proof:
  The lower linear predecessor a is either regular or a zerodivisor on C.  The
  two cases respectively give

    eta_k<=8,
    eta_k<=8,

  while the tangent gate requires eta_k>=15.  Both cases are impossible.
Qed.

Interpretation:
  The multiplicity-three h=(1,2) row has a unique linear saturation class.
  Even if the saturation hull has one additional quadratic generator, finite
  length of the saturation defect forces the fourth quadric to use that
  generator, making T cyclic.  The exact torsion Hilbert series then makes the
  annihilator quotient length five.

  The core stabilizes in degree one, so every final cut reduces to a linear
  predecessor pair.  Regular linear sections have length at most eight, and in
  the zerodivisor case the linear colon is already saturated, so no positive
  delayed-layer defect survives.  This is strictly below the deficit fifteen
  forced by the order-13 tangent gate.

IMPORTANT_NONCONCLUSION:
  This closes only

    q=4,
    ht(Q)=3,
    e(B)=3,
    h=(1,2).

  After the established closures and the degree-three h-vector linkage
  exclusion, the only still-open q=4, height-three low-multiplicity row is

    e=3,
    h=(1,1,1).

  This file does NOT close q=4 height two, homogeneous q<=3, the unrestricted
  nonhomogeneous local deviation-two frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

NEXT_BOUNDED_OBJECT:
  Treat only the final surviving height-three low-multiplicity row

    e=3,
    h=(1,1,1),
    Hilb_T=2*t+3*t^2+2*t^3.

  Recompute its residual saturation generators and Ann_B(T).  Its parameter
  multiplication stabilizes from degree two rather than degree one, so do not
  import the immediate linear-colon saturation conclusion from the present
  row without reproving the predecessor degree and the first delayed layer.