Standalone graded Noether-parameter factorization for the Cohen--Macaulay multiplicity-six endpoint of the homogeneous q=4, height-three order-13 branch.

SCOPE:
  Start from

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  The preceding branch files prove

    Hilb_B(t)=(1+3*t+2*t^2)/(1-t),
    type(B)=2,

  and give the minimal resolution

    0 -> S(-5)^2
      -> S(-3)^2 + S(-4)^3
      -> S(-2)^4
      -> S -> B -> 0.

  Let I=Q+(f,g) be homogeneous and m-primary with

    deg(f)=d >=3,
    deg(g)=e >=d.

  This file compresses the arbitrary higher degrees to a quadratic core.  It does not prove the remaining annihilator-Hom bound and does not treat the e<=5, height-two, q<=3, or unrestricted nonhomogeneous branches.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Theorem noether_parameter_free_module_normal_form:
  Let ell in B_1 be a general linear nonzerodivisor.  Then, as a graded C[ell]-module,

    B ~= C[ell]
         direct_sum C[ell](-1)^3
         direct_sum C[ell](-2)^2.

Proof:
  The Artin reduction H=B/(ell) has Hilbert function (1,3,2).  Choose homogeneous lifts in B of a basis consisting of one element in degree zero, three in degree one, and two in degree two.  They define a graded C[ell]-linear map

    C[ell] direct_sum C[ell](-1)^3 direct_sum C[ell](-2)^2 -> B.

  Modulo ell this map is an isomorphism onto H, hence graded Nakayama gives surjectivity.  The source has Hilbert series

    (1+3*t+2*t^2)/(1-t),

  equal to Hilb_B(t).  Therefore the graded kernel has zero Hilbert series and is zero.
Qed.

Corollary degree_compression_to_B2:
  For every n>=2, multiplication by ell^(n-2) is a C-vector-space isomorphism

    B_2 --ell^(n-2)--> B_n.

  Consequently every homogeneous h in B_n has a unique expression

    h = ell^(n-2) * h_2

  with h_2 in B_2.
Qed.

Theorem two_higher_degree_cuts_factor_through_quadratic_core:
  There are unique a,b in B_2 such that

    f = ell^(d-2) * a,
    g = ell^(e-2) * b.

  Put

    k := e-d >=0,
    J := (a, ell^k*b) subset B.

  Then

    L:=(f,g)B = ell^(d-2) * J.

  Since L is m-primary, J is m-primary as well.
Qed.

Theorem exact_length_peeling_formula:
  With J as above there is a short exact sequence

    0 -> B/J
      --ell^(d-2)-->
      B/L
      -> B/(ell^(d-2))
      -> 0.

  Hence, writing N=length_C(B/L),

    N = length_C(B/J) + 6*(d-2).

Proof:
  The displayed map sends x mod J to ell^(d-2)*x mod L.  It is injective because ell is a nonzerodivisor on B.  Its image is ell^(d-2)B/L, so the cokernel is B/(ell^(d-2)).

  Since ell is a degree-one parameter on the one-dimensional Cohen--Macaulay ring B of multiplicity six,

    length B/(ell^r)=6*r

  for every r>=1.  Taking r=d-2 gives the formula.
Qed.

Corollary arbitrary_degree_endpoint_reduces_to_one_quadratic_and_one_shifted_quadratic:
  The homogeneous e=6 endpoint contains no genuinely new high-degree shape before the quadratic core.  After removing the common Noether-parameter factor ell^(d-2), the residual m-primary ideal is always

    J=(a, ell^(e-d)*b)

  with a,b in the fixed six-dimensional vector space B_2.

  Thus the degree dependence is separated into the single integer e-d and the additive length term 6*(d-2).
Qed.

Now assume the two higher-degree generators have the same degree:

  e=d.

Then

  J=(a,b)

is an m-primary ideal generated by two independent quadrics in B.

Theorem equal_degree_quadratic_core_has_length_nine_or_ten:
  After a constant GL_2(C) change of the pair (a,b), assume a is a nonzerodivisor on B.  Put

    C:=B/(a).

  Then C is an Artin graded level algebra of type two with Hilbert function

    (1,4,5,2).

  Let

    r := rank_C( C_1 --times b--> C_3 ).

  Then

    r in {1,2},

  and

    Hilb_(B/(a,b)) =
      (1,4,4,1) if r=1,
      (1,4,4)   if r=2.

  In particular

    length B/(a,b) in {10,9}.

Proof:
  Because J is m-primary in the one-dimensional Cohen--Macaulay ring B over the infinite field C, a general constant linear combination of a,b avoids Ass(B), so it is a homogeneous quadratic nonzerodivisor.

  The Hilbert series of C is

    Hilb_C(t)=(1-t^2)Hilb_B(t)
             =(1+t)(1+3*t+2*t^2)
             =1+4*t+5*t^2+2*t^3.

  The forced last free module S(-5)^2 in the resolution of B shows that B is level of type two.  Quotient by the homogeneous nonzerodivisor a preserves levelness and type, so Soc(C)=C_3 and dim C_3=2.

  The class of b in C_2 is nonzero because a,b are independent.  If r=0, then C_1*b=0.  Since C is standard graded and C_i*b=0 automatically for i>=2 by degree, b would be a nonzero socle element in degree two, contradicting Soc(C)=C_3.  Thus r>=1.  Since dim C_3=2, r<=2.

  The principal ideal (b) in C has one-dimensional degree-two part C_0*b and degree-three part C_1*b of dimension r; there are no higher pieces.  Therefore quotienting C by b changes the Hilbert function from

    (1,4,5,2)

  to

    (1,4,4,2-r),

  giving exactly the two displayed possibilities and lengths 10 or 9.
Qed.

Corollary equal_degree_original_length_is_quantized:
  If deg(f)=deg(g)=d>=3, then

    N = 6*(d-2) + length B/(a,b)

  and therefore

    N in {6*d-2, 6*d-3}.

  In particular the order-13 frontier condition N>=32 forces

    d>=6

  in this equal-degree e=6 branch.
Qed.

Return also to the annihilator notation from the preceding type-two reduction:

  C0:=B_m/(f_reg),
  A:=C0/(g_reg),
  D:=0:_(C0) g_reg,

where f_reg is the regular first cut after an allowed constant change of the two local generators.  The preceding file proves

  length(D)=length(A)=N,
  dim Soc_A(D)=2,
  mu_A(D^vee)<=2,

with D^vee=Hom_C(D,C).

Theorem annihilator_dual_is_exactly_two_generated:
  One has

    mu_A(D^vee)=2.

Proof:
  Suppose instead that D^vee were cyclic.  Since

    length(D^vee)=length(D)=N=length(A),

  a cyclic surjection A -> D^vee would be an isomorphism.  Dualizing over C would give

    D ~= Hom_C(A,C)=omega_A.

  For every Artin local C-algebra A, the canonical module omega_A has one-dimensional socle: its socle is dual to A/m_A.  Hence dim Soc_A(D)=1, contradicting the already proved value two.

  Thus mu_A(D^vee)>=2, and the preceding upper bound mu_A(D^vee)<=2 forces equality.
Qed.

BOUNDARY:
  This file does NOT prove

    dim Hom_A(D,A) < N+20.

  It instead removes most of the apparent high-degree freedom:

    every homogeneous higher-degree pair factors through B_2,
    the common degree contributes only a 6*(d-2) length block,
    equal-degree pairs have a residual quadratic core of length exactly 9 or 10,
    equal-degree dangerous candidates must have d>=6,
    and the annihilator dual is exactly two-generated.

  The unequal-degree case is reduced to J=(a,ell^k*b), k>0.  The equal-degree case is reduced to the two rank possibilities r=1,2 above.

NEXT_BOUNDED_OBJECT:
  compute the conormal/tangent map separately for the two equal-degree quadratic-core types

    Hilbert function (1,4,4,1)
    or
    Hilbert function (1,4,4),

  using the rigid CI(1,1,2) residual link of B.  For unequal degrees, analyze the single integer k=e-d.  Stop rather than reverting to an arbitrary type-two Artin-module classification.
