Standalone complete-intersection reduction of the r-not-in-P half of the
LK3-C2 carrier in the saturated H01 minimal-chain rank-two endpoint of the
homogeneous q=4, height-two, multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_R2_LK3_koszul_normal_form.v

  and retain

    S := C[x1,x2,x3,x4],
    Q=Qsat subset P,
    P=(l1,l2),
    ht(Q)=2,
    Q minimally generated by exactly four independent quadrics,
    D:=P/Q,
    Hilb_D(t)=(2*t+t^2)/(1-t),

inside the LK3-C2 carrier.  Thus there is a nonzero linear form r such that

    dim_C(Q_2 intersect r*S_1) >= 2.

This file treats only the subcase

    r notin P.

It performs one bounded task: identify Q exactly as the intersection of the
line prime P with a (1,2,2) complete intersection.  The branch is not excluded
and no tangent-space estimate is made.

No r-in-P argument is entered.
No LK3-C3, R2-LK2, R2-QK, H01-M2-R1, or q<=3 branch is entered.
No Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE TWO r-MULTIPLES ARE THE FULL PRODUCT PLANE r*P_1
--------------------------------------------------------------------------

Choose two independent quadrics in Q_2 intersect r*S_1 and write them

    q1=r*a,
    q2=r*b

with a,b in S_1 independent.

Because Q subset P and P is prime, while r notin P, one has

    a in P,
    b in P.

Since P_1 is two-dimensional and a,b are independent, they form a basis of
P_1.  After a harmless generator basis change,

    q1=r*l1,
    q2=r*l2.

Hence

    r*P_1 subset Q_2.

Complete q1,q2 to the four-dimensional space Q_2 by independent quadrics
q3,q4.  Since Q is generated by its four quadrics,

    Q=(r*l1,r*l2,q3,q4).

Theorem H01_m2_R2_LK3_C2_r_notin_P_contains_full_product_plane:
  In the r-not-in-P half of LK3-C2,

    r*P_1 subset Q_2

  and, after a generator basis choice,

    Q=(r*l1,r*l2,q3,q4).
Qed.

--------------------------------------------------------------------------
2. MODULO r THE RESIDUAL MODULE IS Pbar/(q3bar,q4bar)
--------------------------------------------------------------------------

Put

    R:=S/(r)

and

    Pbar:=(P+(r))/(r) subset R.

Because r notin P and P is prime,

    P intersect (r)=r*P.

Therefore

    P/r*P ~= Pbar.

The two generators r*l1,r*l2 vanish modulo r.  Thus

    D=P/Q
      ~= Pbar/(q3bar,q4bar),

where q3bar,q4bar are the images of q3,q4 in R.

Since r is independent of P_1,

    R ~= C[y1,y2,y3],

and Pbar is a height-two linear prime.  Hence

    R/Pbar ~= C[t].

Theorem H01_m2_R2_LK3_C2_r_notin_P_residual_mod_r_presentation:
  One has

    D ~= Pbar/(q3bar,q4bar)

  over R=S/(r), with Pbar a height-two linear prime.
Qed.

--------------------------------------------------------------------------
3. THE TWO REMAINING QUADRICS FORM A (2,2) COMPLETE INTERSECTION
--------------------------------------------------------------------------

There is an exact sequence

    0 -> D
      -> R/(q3bar,q4bar)
      -> R/Pbar
      -> 0.

Indeed q3bar,q4bar lie in Pbar because q3,q4 lie in P.

Using

    Hilb_D(t)=(2*t+t^2)/(1-t)

and

    Hilb_(R/Pbar)(t)=1/(1-t),

one obtains

    Hilb_(R/(q3bar,q4bar))(t)
      = (1+2*t+t^2)/(1-t)
      = (1+t)^2/(1-t).

This is exactly the Hilbert series of a regular sequence of two quadrics in the
three-variable polynomial ring R:

    (1-t^2)^2/(1-t)^3=(1+t)^2/(1-t).

Equivalently, R/(q3bar,q4bar) has dimension one, so the ideal generated by the
two quadrics has height two; because R is Cohen--Macaulay, q3bar,q4bar form a
regular sequence.

Theorem H01_m2_R2_LK3_C2_r_notin_P_mod_r_complete_intersection:
  The pair

    q3bar,q4bar

  is a homogeneous regular sequence of degrees (2,2) in R.
Qed.

--------------------------------------------------------------------------
4. LIFT TO A (1,2,2) COMPLETE INTERSECTION IN S
--------------------------------------------------------------------------

Define

    J:=(r,q3,q4) subset S.

Since q3bar,q4bar form a regular sequence in S/(r), the three forms

    r,q3,q4

form a regular sequence in S of degrees

    (1,2,2).

Therefore J is a height-three homogeneous complete intersection.  In
particular S/J is one-dimensional Cohen--Macaulay and J is saturated.

Projectively Proj(S/J) is a zero-dimensional complete intersection of length

    1*2*2=4.

Theorem H01_m2_R2_LK3_C2_r_notin_P_auxiliary_CI:
  J=(r,q3,q4) is a saturated (1,2,2) complete intersection of projective length
  four.
Qed.

--------------------------------------------------------------------------
5. THE ORIGINAL SATURATED IDEAL IS EXACTLY P INTERSECT J
--------------------------------------------------------------------------

Because q3,q4 belong to P,

    Q=r*P+(q3,q4).

We claim

    P intersect J = r*P+(q3,q4).

The inclusion from right to left is immediate.

Conversely, let f belong to P intersect J.  Write

    f=r*s+c3*q3+c4*q4.

Since q3,q4 belong to P, the element r*s also belongs to P.  As P is prime and
r notin P, one gets

    s in P.

Hence r*s belongs to r*P, proving

    f in r*P+(q3,q4).

Therefore

    Q=P intersect J.

Theorem H01_m2_R2_LK3_C2_r_notin_P_intersection_normal_form:
  In the r-not-in-P half of LK3-C2,

    Q=P intersect (r,q3,q4),

  where (r,q3,q4) is a saturated complete intersection of type (1,2,2).
Qed.

This also makes the standing saturation Q=Qsat geometrically transparent:
Q is the intersection of two saturated homogeneous ideals P and J.

--------------------------------------------------------------------------
6. THE TWO COMPONENTS MEET IN EXACTLY ONE PROJECTIVE POINT
--------------------------------------------------------------------------

Because q3,q4 lie in P,

    P+J=(P,r).

The three linear forms l1,l2,r are independent because r notin P.  Thus

    S/(P+J) ~= C[t].

Projectively the line Proj(S/P) and the length-four scheme Proj(S/J) meet in
exactly one reduced point.

The standard intersection exact sequence

    0 -> S/Q
      -> S/P direct_sum S/J
      -> S/(P+J)
      -> 0

then gives the expected multiplicity-one curve core together with a residual
zero-dimensional contribution of length

    4-1=3.

This agrees exactly with

    e(D)=3

for the H01 m=2 residual module.

Corollary H01_m2_R2_LK3_C2_r_notin_P_geometric_carrier:
  The r-not-in-P half of LK3-C2 is the union of

    * the line defined by P, and
    * a (1,2,2) complete intersection of length four,

  meeting in one point; the residual length away from the line intersection is
  three.
Qed.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_notin_P_product_plane.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_notin_P_mod_r_CI22.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_notin_P_intersection_normal_form.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_notin_P_geometric_carrier.

EXACT_NORMAL_FORM:

    Q=P intersect J,
    J=(r,q3,q4),
    type(J)=(1,2,2),
    length Proj(S/J)=4,
    length Proj(S/(P+J))=1.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude the r-not-in-P carrier.
  It does NOT treat the r-in-P half of LK3-C2.
  It does NOT close LK3-C2 or R2-LK3.
  It does NOT treat LK3-C3, R2-LK2, or R2-QK.
  It does NOT make a tangent-space estimate.
  It does NOT close H01-M2-R2, H01-M2, or H01.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_R2_exact_Betti_table.
  H01_m2_R2_determinantal_factorization.
  H01_m2_R2_LK3_coefficient_rank_one_empty.
  H01_m2_R2_LK3_C2_r_notin_P_CI_carrier.
  not H01_m2_R2_LK3_C2_closed.
  not H01_m2_R2_LK3_closed.
  not H01_m2_R2_closed.
  not H01_m2_R1_closed.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in LK3-C2.  Treat the complementary case r in P.  Determine whether
  the two-dimensional space Q intersect r*S_1 forces a common product plane
  r*U with U independent of P, and whether saturation reduces that carrier to
  a finite intersection normal form.  Do not enter LK3-C3 until the r-in-P half
  is classified.

NEXT_ACTIONS:
  1. Classify the r-in-P half of LK3-C2.
