Standalone closure of the ZERODIVISOR_LOWER multiplicity-two subbranch of the
homogeneous q=4, height-three order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_e2_rank_two_core_reduction.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e2_exact_saturation_linkage_profile.v
    order13_q4_height3_e2_regular_lower_residual_colon_closed.v

  Work with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g),
    B := S/Q,
    A := B/(f,g),
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    e(B)=2.

  Put

    T := H^0_m(B),
    Cbar := B/T.

  The preceding files prove

    Hilb_T(t)=2*t+4*t^2+2*t^3,
    length_C(T)=8,
    m^3*T=0,

  and classify the saturated core as exactly one of

    REDUCED_SPLIT:
      Cbar ~= C[x,y]/(x*y),

    DOUBLE_LINE:
      Cbar ~= C[ell,v]/(v^2).

  The one-core-active e=2 case is already closed.  The REGULAR_LOWER
  two-core-active e=2 case is already closed.  Thus this file treats only the
  remaining ZERODIVISOR_LOWER case.

  Write

    d:=deg(f)<=D:=deg(g).

  The exact torsion profile strengthens the necessary numerical condition to

    d+D>=25.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is to compute the two explicit zerodivisor colons and
to prove that neither can produce the connecting-rank excess six required by
the order-13 tangent gate.

First remove the inessential same-component term of the upper cut.

Theorem homogeneous_triangular_normal_form_for_zerodivisor_lower:
  After a homogeneous triangular change preserving L=(f,g)B, the saturated
  images have one of the forms

    REDUCED_SPLIT:
      fbar=x^d,
      gbar=y^D,

    DOUBLE_LINE:
      fbar=ell^(d-1)*v,
      gbar=ell^D.

Proof:
  In the reduced split core the preceding rank-two classification gives

    fbar=x^d,
    gbar=c*x^D+b*y^D,

  with b nonzero.  Since D>=d,

    x^D=x^(D-d)*fbar.

  Replace g by

    g-c_tilde*f,

  where c_tilde is a homogeneous lift of c*x^(D-d).  This is an invertible
  triangular change of the two-generator ideal.  Rescale the new second
  generator to obtain gbar=y^D.

  In the double-line core one similarly has

    fbar=ell^(d-1)*v,
    gbar=b*ell^D+c*ell^(D-1)*v,

  with b nonzero.  The second summand equals

    c*ell^(D-d)*fbar.

  Apply the same homogeneous triangular replacement and rescale.
Qed.

Corollary final_cuts_annihilate_T_and_do_not_meet_T:
  One has

    f*T=0,
    g*T=0,
    L*T=0,
    L intersect T=0.

Proof:
  The first three statements follow from

    deg(f),deg(g)>=3,
    m^3*T=0.

  For the intersection, T is concentrated in degrees one, two, and three.
  If d>3, then L has no component in those degrees.

  If d=3, then d+D>=25 forces D>3, so

    L_3=C*f.

  Since fbar is nonzero in Cbar, no nonzero scalar multiple of f lies in T.
  Hence L_3 intersect T_3=0.  There are no other possible degrees.
Qed.

Put

  A0:=Cbar/(fbar,gbar).

Then the preceding corollary gives an exact sequence

  0 -> T -> A -> A0 -> 0.

We next reuse the residual-colon theorem proved in the REGULAR_LOWER closure.
Its computation of Ann_B(T) occurs before any use of the final cuts and depends
only on the multiplicity-two saturation presentation.  It proves that

  Ann_B(T)

is generated by the images of at most three quadratic residual minors.

Define

  N_T:=Ann_A(T).

Theorem torsion_annihilator_has_three_quadratic_generators_in_every_e2_subcase:
  One has

    N_T ~= Ann_B(T)/L,
    mu_A0(N_T)<=3.

  Moreover

    (N_T)_0=(N_T)_1=0,
    m_A^3 subseteq N_T.

Proof:
  Since L*T=0,

    L subseteq Ann_B(T).

  If b+L annihilates T in A, then

    b*T subseteq L.

  But b*T is contained in T, while L intersect T=0.  Thus b*T=0 already in B,
  so b belongs to Ann_B(T).  Hence

    N_T=Ann_B(T)/L.

  The residual-colon formula expresses Ann_B(T) as a module generated by at
  most three degree-two minors.  Their images still generate N_T.  Since T
  annihilates N_T, its A-action factors through A0, so

    mu_A0(N_T)<=3.

  The same quadratic generation gives no degree-zero or degree-one part.

  Finally m^3*T=0, hence every element of m_A^3 annihilates T and belongs to
  N_T.
Qed.

We now close the two core types separately.

SECTION REDUCED_SPLIT.

Assume

  Cbar=C[x,y]/(x*y),
  fbar=x^d,
  gbar=y^D.

Choose an invertible constant change of the two cuts

  h:=f+g,
  k:=a*f+b*g,

with

  a,b nonzero,
  a!=b.

Then hbar and kbar are both nonzerodivisors on Cbar.  Since both cuts
annihilate T,

  0:_B h=T,
  0:_B k=T.

Theorem split_core_colon_is_the_maximal_ideal:
  Put

    K:=(h:k).

  Then

    K=m_B.

Proof:
  Modulo T one has

    hbar=x^d+y^D,
    kbar=a*x^d+b*y^D.

  Since x*y=0,

    x*kbar=a*x*hbar,
    y*kbar=b*y*hbar.

  Thus the core maximal ideal (x,y) lies in

    Kbar:=(hbar:kbar).

  The element 1 is not in Kbar because hbar and kbar are not scalar multiples.
  Hence

    Kbar=(x,y)=m_Cbar.

  Now lift x and y homogeneously to B.  The two displayed colon relations can
  fail after lifting only by elements of T in degrees at least

    d+1>=4.

  But T_n=0 for n>=4, so the relations lift exactly.  Thus every positive-
  degree lift lies in K.  Also T lies in K because k*T=0.  Therefore

    m_B subseteq K.

  Conversely 1 is not in K because its image is not in Kbar.  Hence K=m_B.
Qed.

Corollary split_cyclic_quotient_is_the_residue_field:
  For

    M:=L/hB,

  one has

    M~=B/K~=C.

  Hence

    Hom_B(M,A)~=Soc_A(A).
Qed.

The core transport map is determined by

  qbar(x)=a*x,
  qbar(y)=b*y.

Theorem split_maximal_ideal_times_NT_lies_in_connecting_kernel:
  For the connecting map

    partial:N_T -> Ext^1_B(M,A),

  one has

    m_A0*N_T subseteq ker(partial).

Proof:
  Let

    z=x*u+y*w

  belong to m_A0*N_T.  Put

    c:=a*x*u+b*y*w.

  Since N_T is an A0-module, c belongs to N_T and therefore annihilates T.
  The relation x*y=0 gives

    x*c=a*x*z,
    y*c=b*y*z.

  These are exactly the extension equations for the cyclic representative

    r |-> q(r)*z

  on K/T=m_Cbar.  On T the representative is zero because

    0:_B k=T,

  while multiplication by c is also zero because c belongs to N_T.
  Thus the representative extends to B and the connecting class vanishes.
Qed.

Corollary split_connecting_excess_is_at_most_three:
  Put

    epsilon:=rank_C(partial)-dim_C Hom_B(M,A).

  Then

    epsilon<=3.

Proof:
  The preceding theorem gives

    rank(partial)<=dim_C(N_T/m_A0*N_T)=mu_A0(N_T)<=3.

  The Hom term has nonnegative dimension, so epsilon<=3.
Qed.

Corollary reduced_split_zerodivisor_lower_is_closed:
  The REDUCED_SPLIT ZERODIVISOR_LOWER e=2 case cannot satisfy the necessary
  order-13 tangent gate.

Proof:
  The general conormal-rank reduction proves that every dangerous candidate
  must have epsilon>=6.  The preceding corollary gives epsilon<=3.
Qed.

END REDUCED_SPLIT.

SECTION DOUBLE_LINE.

Assume

  Cbar=C[ell,v]/(v^2),
  fbar=ell^(d-1)*v,
  gbar=ell^D.

Put

  s:=D-d+1>=1.

Choose

  h:=f+g,
  k:=g.

Then

  hbar=ell^(d-1)*(v+ell^s),
  kbar=ell^(d-1)*ell^s.

Both hbar and kbar are nonzerodivisors on Cbar because their images modulo the
unique minimal prime (v) are nonzero.  Since h and k annihilate T,

  0:_B h=T,
  0:_B k=T.

Theorem doubled_line_core_colon_is_v_ell_s:
  Modulo T,

    Kbar:=(hbar:kbar)=(v,ell^s).

Proof:
  Since ell is a nonzerodivisor, cancel the common factor ell^(d-1).  It is
  enough to compute

    (v+ell^s : ell^s).

  Modulo the regular element v+ell^s one has

    v=-ell^s,
    v^2=0,

  hence

    ell^(2*s)=0.

  The annihilator of ell^s in

    C[ell]/(ell^(2*s))

  is generated by ell^s.  Pulling back gives

    (v+ell^s,ell^s)=(v,ell^s).
Qed.

Theorem doubled_line_full_colon_is_the_inverse_image_of_v_ell_s:
  Let v and ell also denote fixed homogeneous degree-one lifts to B.  Then

    K:=(h:k)=T+(v,ell^s)B.

Proof:
  The inclusion K -> Kbar after quotienting by T is automatic.

  Conversely the two core transport identities are

    v*kbar=v*hbar,

    ell^s*kbar=(ell^s-v)*hbar.

  After lifting to B, any discrepancy lies in T.  Every term in either
  discrepancy has degree at least d+1>=4, while T_n=0 for n>=4.  Thus both
  identities lift exactly.  Hence v and ell^s belong to K.

  Also T belongs to K because k*T=0.  Therefore the full inverse image

    T+(v,ell^s)B

  lies in K.  The reverse inclusion follows by reducing modulo T and using the
  core-colon theorem.
Qed.

Corollary doubled_line_cyclic_quotient:
  With

    J_s:=(v,ell^s) subset A0,

  one has

    M:=L/hB ~= B/K,

  and every element of Hom_B(M,A) lies in N_T.  More precisely

    Hom_B(M,A) ~= 0:_(N_T) J_s.
Qed.

The transport map modulo T is

  qbar(v)=v,
  qbar(ell^s)=ell^s-v.

Theorem doubled_line_Js_times_NT_lies_in_connecting_kernel:
  For

    partial:N_T -> Ext^1_B(M,A),

  one has

    J_s*N_T subseteq ker(partial).

Proof:
  First let z=v*a with a in N_T.  Multiplication by

    w:=z

  extends the cyclic representative because

    v*w=v*z=qbar(v)*z,

    ell^s*w=ell^s*v*a=(ell^s-v)*v*a=qbar(ell^s)*z.

  Next let z=ell^s*a.  Put

    w:=(ell^s-v)*a.

  Then

    v*w=ell^s*v*a=qbar(v)*z,

    ell^s*w=(ell^s-v)*ell^s*a=qbar(ell^s)*z.

  In both cases w belongs to N_T, so multiplication by w also vanishes on T,
  exactly as the cyclic representative does.  By linearity every element of
  J_s*N_T lies in the kernel.
Qed.

Define the doubled-line generator-annihilator defect

  delta_s(N_T)
    := dim_C(N_T/J_s*N_T)
       - dim_C(0:_(N_T) J_s).

Corollary doubled_line_connecting_excess_is_bounded_by_delta:
  One has

    epsilon<=delta_s(N_T).

Proof:
  The kernel inclusion gives

    rank(partial)<=dim_C(N_T/J_s*N_T).

  The cyclic quotient gives

    dim Hom_B(M,A)=dim_C(0:_(N_T)J_s).

  Subtract.
Qed.

It remains to bound delta_s(N_T).  Put

  U:=m_A^3 subseteq N_T,
  W:=N_T/U.

Theorem low_quotient_W_has_dimension_at_most_three:
  The module W is concentrated in degree two, is annihilated by m_A0, and

    dim_C W<=3.

Proof:
  The residual-colon presentation gives N_T no components in degrees zero or
  one and generates it by at most three quadrics.  Since U contains every
  component of degree at least three, W is exactly the degree-two generator
  quotient.  Thus dim W<=3.  Multiplication by any positive-degree element
  raises degree into U, so m_A0 kills W.
Qed.

We next compute the stable tail U.

Theorem cubic_tail_splits_off_the_top_torsion:
  As a graded A0-module,

    U ~= m_A0^3 direct_sum T_3.

  Moreover T_3 is a two-dimensional residue-field module killed by m_A0.

Proof:
  Restrict

    0 -> T -> A -> A0 -> 0

  to degrees at least three.  Since

    T_3 has dimension two,
    T_n=0 for n>=4,

  one gets

    0 -> T_3 -> m_A^3 -> m_A0^3 -> 0.

  In the doubled-line normal form

    A0=C[ell,v]/(v^2,ell^(d-1)*v,ell^D),

  the ideal m_A0^3 is generated in degree three by ell^3 and, when nonzero,
  ell^2*v.  Choose degree-three lifts of these generators in A.

  Every defining relation among those lifts has total degree at least four.
  Its image in A0 is zero, so the relation in A lies in T in degree at least
  four and is therefore zero.  Hence the chosen lifts generate a submodule
  isomorphic to m_A0^3.

  This submodule meets T_3 trivially in degree three and there is no torsion in
  higher degree.  Therefore the displayed exact sequence splits as graded
  A0-modules.

  Finally every positive-degree element sends T_3 into T_n for n>=4, which is
  zero.  Thus T_3 is a two-dimensional residue-field module.
Qed.

Define for any finite A0-module X

  delta_s(X)
    := dim_C(X/J_s*X)
       - dim_C(0:_X J_s).

Corollary residue_field_summands_have_zero_delta:
  If V is killed by m_A0, then

    delta_s(V)=0.

  In particular

    delta_s(T_3)=0.
Qed.

We now compute delta on the explicit stable core tail.

Theorem doubled_line_core_cubic_tail_has_nonpositive_delta:
  Put

    U0:=m_A0^3.

  Then

    delta_s(U0)<=0.

  More precisely:

  if d=3, then

    dim(U0/J_s*U0)=s-1,
    dim(0:_U0 J_s)=s-1,
    delta_s(U0)=0;

  if d>=4, then

    dim(U0/J_s*U0)=s+1,

    dim(0:_U0 J_s)
      =s+min(s,d-3),

    delta_s(U0)
      =1-min(s,d-3)
      <=0.

Proof:
  A vector-space basis of A0 is

    1,ell,...,ell^(D-1),
    v,ell*v,...,ell^(d-2)*v.

  Therefore U0=m_A0^3 has basis

    ell^3,...,ell^(D-1)

  together with

    ell^2*v,...,ell^(d-2)*v

  when the latter range is nonempty.

  Quotient by J_s=(v,ell^s).

  If d=3 there is no v-tail in U0, and the surviving pure powers are

    ell^3,...,ell^(D-1),

  modulo ell^s*U0.  Since D=s+2, exactly s-1 survive.

  If d>=4, the pure quotient contributes

    ell^3,...,ell^(s+2),

  namely s dimensions, while the single class ell^2*v is not in v*U0 and
  contributes one more.  Thus the quotient dimension is s+1.

  For the common annihilator of v and ell^s, a pure monomial ell^n is killed by
  both exactly when

    n>=d-1.

  In the d=3 case every pure basis element of U0 satisfies this and there are
  s-1 of them.

  For d>=4, the pure annihilator therefore has basis

    ell^(d-1),...,ell^(D-1),

  of dimension s.

  Every v-monomial is killed by v.  The monomial ell^j*v in U0 is additionally
  killed by ell^s exactly when

    j+s>=d-1.

  Among

    j=2,...,d-2,

  this contributes exactly min(s,d-3) dimensions.  Summing proves the formulas.
Qed.

Corollary full_cubic_tail_has_nonpositive_delta:
  One has

    delta_s(U)<=0.

Proof:
  By the splitting theorem

    U~=U0 direct_sum T_3.

  The defect delta_s is additive on direct sums.  The preceding theorem gives
  delta_s(U0)<=0, while the residue-field corollary gives delta_s(T_3)=0.
Qed.

Theorem extension_by_at_most_three_quadratic_generators_adds_at_most_three_to_delta:
  One has

    delta_s(N_T)<=delta_s(U)+dim_C W<=3.

Proof:
  Apply quotient by J_s to

    0 -> U -> N_T -> W -> 0.

  Right exactness gives

    dim_C(N_T/J_s*N_T)
      <= dim_C(U/J_s*U)+dim_C(W/J_s*W).

  Since J_s is contained in m_A0 and m_A0 kills W,

    W/J_s*W=W.

  On the annihilator side, the inclusion U->N_T gives an injection

    0:_U J_s -> 0:_(N_T) J_s,

  so

    dim_C(0:_(N_T)J_s)>=dim_C(0:_U J_s).

  Subtracting yields

    delta_s(N_T)
      <=delta_s(U)+dim_C W.

  Now use

    delta_s(U)<=0,
    dim W<=3.
Qed.

Corollary doubled_line_connecting_excess_is_at_most_three:
  One has

    epsilon<=3.
Qed.

Corollary double_line_zerodivisor_lower_is_closed:
  The DOUBLE_LINE ZERODIVISOR_LOWER e=2 case cannot satisfy the necessary
  order-13 tangent gate.

Proof:
  A dangerous candidate requires epsilon>=6, while the preceding corollary
  gives epsilon<=3.
Qed.

END DOUBLE_LINE.

Theorem entire_e2_zerodivisor_lower_branch_is_closed:
  No multiplicity-two q=4, ht(Q)=3 ZERODIVISOR_LOWER candidate can pass the
  necessary order-13 tangent-dimension gate.

Proof:
  The rank-two saturated-core classification has only REDUCED_SPLIT and
  DOUBLE_LINE.  Both were closed above.
Qed.

Corollary entire_multiplicity_two_height_three_branch_is_closed:
  In the homogeneous q=4, ht(Q)=3 endpoint, multiplicity e(B)=2 contributes no
  candidate passing the necessary order-13 tangent gate.

Proof:
  The preceding e=2 files already close the one-core-active case and the
  two-core-active REGULAR_LOWER case.  If neither final generator were
  core-active, the quotient of the one-dimensional saturated core would remain
  positive-dimensional, contradicting finiteness of A.  The only remaining
  two-core-active case is ZERODIVISOR_LOWER, closed by the theorem above.
Qed.

IMPORTANT_NONCONCLUSION:
  This closes only the multiplicity-two part of the homogeneous q=4,
  height-three low-multiplicity endpoint.

  It does NOT close e=3,4,5, the q=4 height-two branch, homogeneous q<=3, or the
  unrestricted nonhomogeneous local deviation-two frontier.

  It makes no claim of generic F_13 algebraicity and no machine verification of
  the new mathematical argument is asserted.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  The first remaining q=4, ht(Q)=3 low-multiplicity branch is now

    e(B) in {3,4,5}.

NEXT_BOUNDED_OBJECT:
  Return to the ten saturated-core h-vectors and remove the now-closed
  multiplicities e=1 and e=2.  Rank the remaining e=3,4,5 cores by torsion
  length and C[ell]-rank, then attack the smallest residual conormal carrier.
  Do not move to q=4 height two until the e=3,4,5 height-three frontier is
  either closed or reduced to a genuinely new obstruction.
