Standalone exclusion of the finite length-two deficiency stratum for the
homogeneous q=4, height-two DEPTH-ONE saturated-core branch in the order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_length2_deficiency_transgression_reduction.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S homogeneous,
    Q minimally generated by exactly four independent quadrics,
    ht(Q)=2,
    B := S/Q,
    Qsat := saturation(Q),
    C0 := S/Qsat,
    T := Qsat/Q,
    dim C0=2,
    depth_m(C0)=1.

Assume in this file that the Rao/deficiency module

    M := H^1_m(C0)

has finite C-dimension and ask specifically whether

    dim_C M=2

can occur.

The preceding file reduced that hypothetical stratum to a saturation
transgression.  The present file proves a stronger fact: under the exact
four-quadric height-two hypotheses the finite length-two Rao stratum is empty,
so no rank-two transgression case actually occurs.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXTERNAL FOUR-QUADRIC MULTIPLICITY INPUT
--------------------------------------------------------------------------

ExternalResult four_quadric_height_two_multiplicity_bound:
  Let k be algebraically closed and let I be a height-two ideal in a polynomial
  ring over k, minimally generated by g>=4 quadrics.  Then

    e(S/I)<=2.

  Source:
    Paolo Mantero and Matthew Mastroeni,
    Betti numbers of Koszul algebras defined by four quadrics,
    Journal of Pure and Applied Algebra 225 (2021), 106504,
    Theorem 2.11.

  The theorem itself is unconditional on Koszulness in this height-two
  multiplicity statement.

ExternalResult exact_multiplicity_two_four_quadric_classification:
  Under the same hypotheses, if

    ht(I)=e(S/I)=2,

  then I has exactly one of the following forms.

  TYPE A1:
    I=(x,y) intersect (z,w)
      =(xz,xw,yz,yw)
    for independent linear forms x,y,z,w.

  TYPE A2:
    I=((x,y)^2, xz+yw)
      =(x^2,xy,y^2,xz+yw)
    for independent linear forms x,y,z,w.

  TYPE B:
    I=(a1*x,a2*x,a3*x,q),
    where a1,a2,a3 are independent linear forms and

      q in (a1,a2,a3) \ (x).

  TYPE C:
    I=(a1*x,a2*x,a3*x,q),
    where a1,a2,a3 are independent linear forms and q is a nonzerodivisor on

      S/(a1*x,a2*x,a3*x).

  Source:
    Mantero--Mastroeni, op. cit., Theorem 3.1,
    using Engheta's classification of unmixed multiplicity-two height-two
    ideals.

--------------------------------------------------------------------------
2. FINITE RAO DEPTH ONE CANNOT HAVE MULTIPLICITY ONE
--------------------------------------------------------------------------

ExternalResult finite_lower_local_cohomology_implies_CM_on_punctured_spectrum:
  If R is a standard graded ring of dimension d and

    H^i_m(R)

  has finite length for every i<d, then every localization R_p at a homogeneous
  prime p!=m is Cohen--Macaulay.

Theorem finite_Rao_depth_one_forces_multiplicity_two:
  Under the standing assumptions and finite length of M,

    e(B)=e(C0)=2.

Proof:
  Saturation changes B only by the finite-length module T, so

    e(B)=e(C0).

  The external four-quadric bound gives

    e(B) in {1,2}.

  Suppose e(B)=1.  The unmixed height-two part of Q is then a multiplicity-one
  unmixed ideal.  Over C such an ideal is a linear height-two prime P.

  If Qsat=P, then

    C0=S/P ~= C[u,v]

  is Cohen--Macaulay of depth two, contrary to depth(C0)=1.

  Otherwise Qsat has a projective embedded associated prime p of height three.
  Since p!=m, the localization (C0)_p has depth zero and positive dimension, so
  it is not Cohen--Macaulay.  But H^0_m(C0)=0 by saturation and M=H^1_m(C0) has
  finite length by hypothesis.  Thus C0 is Cohen--Macaulay on the punctured
  spectrum by the external result, contradiction.

  Therefore e(B)!=1 and hence

    e(B)=e(C0)=2.
Qed.

Consequently the exact multiplicity-two four-quadric classification applies to
Q itself.

--------------------------------------------------------------------------
3. TYPE A1 HAS RAO LENGTH ONE
--------------------------------------------------------------------------

Theorem type_A1_has_exact_one_dimensional_Rao_module:
  If

    Q=(x,y) intersect (z,w),

  then Q is saturated and

    H^1_m(S/Q) ~= C

  concentrated in degree zero.

Proof:
  This is the exact skew-line model already established in

    order13_q4_height2_depth_one_minimal_deficiency_profile.v.

  The standard fiber-product exact sequence is

    0 -> S/Q
      -> S/(x,y) direct_sum S/(z,w)
      -> C
      -> 0.

  The two polynomial-ring components have depth two, and local cohomology gives

    H^1_m(S/Q) ~= C.
Qed.

Corollary type_A1_is_not_length_two_deficiency:
  Type A1 cannot occur when dim_C M=2.
Qed.

--------------------------------------------------------------------------
4. TYPE A2 ALSO HAS RAO LENGTH ONE
--------------------------------------------------------------------------

Assume now

    Q=(x^2,xy,y^2,xz+yw)

with x,y,z,w independent linear forms.

Put

    R:=C[z,w].

Theorem type_A2_is_saturated_depth_one_with_Rao_length_one:
  The ideal Q is saturated, S/Q has depth one, and

    H^1_m(S/Q) ~= C

  concentrated in degree zero.

Proof:
  The multiplicity-two classification identifies this ideal with its unmixed
  part.  Hence it has no embedded maximal-ideal associated component and is
  saturated.

  Because x^2=xy=y^2=0 in S/Q, every class has a unique expression consisting
  of an R-part plus an R-linear x,y-part, subject only to

    z*x+w*y=0.

  Therefore as a graded R-module

    S/Q ~= R direct_sum N,

  where N has presentation

    0 -> R(-2)
      --(z,w)^T-->
      R(-1)^2
      -> N
      -> 0.

  The R-linear map

    R(-1)^2 -> R,
    (a,b) |-> -w*a+z*b

  has image (z,w) and kernel generated by (z,w).  Hence

    N ~= (z,w) subset R.

  Thus

    S/Q ~= R direct_sum (z,w)

  as graded R-modules.

  From

    0 -> (z,w) -> R -> C -> 0

  and depth(R)=2, local cohomology gives

    H^1_(z,w)((z,w)) ~= C

  in degree zero, while H^1_(z,w)(R)=0.  Since S/Q is finite over R, this is
  the same irrelevant-support local cohomology calculation for S/Q.  Hence

    H^1_m(S/Q) ~= C.

  In particular depth(S/Q)=1 and the Rao module has C-dimension one.
Qed.

Corollary type_A2_is_not_length_two_deficiency:
  Type A2 cannot occur when dim_C M=2.
Qed.

--------------------------------------------------------------------------
5. TYPE B CANNOT HAVE FINITE RAO MODULE
--------------------------------------------------------------------------

Assume

    Q=x*A+(q),
    A:=(a1,a2,a3),
    q in A \ (x).

Theorem type_B_has_a_projective_embedded_associated_prime:
  The height-three linear prime A is associated to S/Q and remains visible
  after saturation.

Proof:
  Since q is not divisible by x, gcd(x,q)=1 in the polynomial ring S.

  We claim

    (Q:x)=A.

  Certainly A subset (Q:x).  Conversely, if r*x belongs to x*A+(q), write

    r*x=x*a+q*b

  with a in A.  Then

    x*(r-a)=q*b.

  Coprimality of x and q forces x to divide b, say b=x*c.  Therefore

    r-a=q*c belongs to A

  because q belongs to A.  Hence r belongs to A, proving the colon equality.

  Thus A is the annihilator of the nonzero class of x in S/Q and is an
  associated prime.

  The prime A has height three and is not the irrelevant maximal ideal m.
  Saturation changes Q only at m, so localization at A is unchanged:

    (Qsat)_A=Q_A.

  Hence A remains an associated prime of S/Qsat on the punctured spectrum.
Qed.

Corollary type_B_has_nonfinite_H1:
  Type B is incompatible with finite length of

    H^1_m(S/Qsat).

Proof:
  The saturated ring C0=S/Qsat has dimension two and has a nonmaximal
  associated prime A at which depth is zero.  Therefore C0 is not
  Cohen--Macaulay on the punctured spectrum.

  But if H^0_m(C0)=0 and H^1_m(C0) had finite length, the external generalized
  Cohen--Macaulay result would force Cohen--Macaulayness at every homogeneous
  nonmaximal localization.  Contradiction.
Qed.

Thus Type B cannot occur in any finite Rao stratum, in particular not when

    dim_C M=2.

--------------------------------------------------------------------------
6. TYPE C SATURATES TO A COHEN--MACAULAY PLANE CONIC
--------------------------------------------------------------------------

Assume

    Q=x*A+(q),
    A:=(a1,a2,a3),

with q a nonzerodivisor on S/(x*A).

Theorem type_C_saturation_is_the_plane_conic_unmixed_part:
  One has

    Qsat=(x,q).

Proof:
  The multiplicity-two classification identifies the unmixed part as

    Qunm=(x,q).

  The associated primes of S/(x*A) lie over the factors (x) and A.  Since q is
  a nonzerodivisor modulo x*A, it avoids those associated primes.

  After adjoining q, the height-two unmixed component is (x,q).  The only
  possible additional component comes from A+(q).  Because A is generated by
  three independent linear forms, S/A is a polynomial ring in one variable.
  Nonzerodivisorness gives q mod A !=0; being quadratic, its radical together
  with A is the homogeneous maximal ideal m.

  Hence every component beyond (x,q) is m-primary and is removed by
  saturation.  Therefore

    Qsat=(x,q).
Qed.

Corollary type_C_is_not_depth_one:
  In Type C,

    C0=S/Qsat=S/(x,q)

  is a complete intersection of a linear form and a quadric.  Therefore

    depth_m(C0)=2.

  This contradicts the standing depth-one branch.
Qed.

Thus Type C cannot occur in the present depth-one finite-Rao stratum.

--------------------------------------------------------------------------
7. LENGTH-TWO FINITE DEFICIENCY IS EMPTY
--------------------------------------------------------------------------

Theorem q4_height2_depth_one_finite_length_two_Rao_stratum_is_empty:
  Under

    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    C0=S/Qsat,
    depth_m(C0)=1,
    dim_C H^1_m(C0)<infinity,

  one cannot have

    dim_C H^1_m(C0)=2.

Proof:
  The finite-Rao depth-one hypotheses force e(S/Q)=2 by Section 2.

  Apply the exact multiplicity-two classification.

  Type A1 has Rao length one.
  Type A2 has Rao length one.
  Type B cannot have finite Rao module.
  Type C has saturated depth two.

  All possibilities contradict Rao length two.
Qed.

Corollary the_rank_two_saturation_transgression_never_arises:
  The transgression problem isolated in

    order13_q4_height2_depth_one_length2_deficiency_transgression_reduction.v

  has empty geometric input under the standing four-quadric height-two
  hypotheses.  In particular there is no actual candidate for which

    rank(delta)=2

  must be tested in a two-dimensional finite Rao module.
Qed.

--------------------------------------------------------------------------
8. SHARP NEW BOUNDARY
--------------------------------------------------------------------------

The multiplicity-two classification also reveals a distinct finite-Rao
length-one endpoint not yet closed by the previous skew-line tangent file:

    Q=((x,y)^2,xz+yw).

It is saturated, depth one, and has Rao module C in degree zero.  It should be
handled next by the same Koszul-residue-field carrier mechanism, but that
separate tangent step is NOT performed in this file.

IMPORTANT_NONCONCLUSION:
  This file does NOT close the entire q=4 height-two depth-one branch.

  It closes only the hypothetical finite Rao length-two stratum by proving it
  is empty.

  It does not yet close the Type A2 double-line endpoint.
  It does not treat depth-one cores with non-finite H^1_m.
  It does not enter q<=3.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_tangent_closed.
  q4_height2_depth_one_skew_line_endpoint_closed.
  q4_height2_depth_one_length2_deficiency_empty.
  not q4_height2_depth_one_double_line_endpoint_closed.
  not q4_height2_depth_one_core_closed.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

NEXT_ACTIONS:
  1. Stay inside q=4 height-two depth one.
  2. Treat only Q=((x,y)^2,xz+yw).
  3. Compute H_1(f,g;S/Q) from its exact Rao module C[0].
  4. Reuse the two-coordinate maximal-ideal Hom carrier.
  5. Do not enter non-finite Rao profiles or q<=3.
