Standalone tangent closure of the regular-minimal-slice subcase of the
nonreduced homogeneous q=3, height-three complete-intersection core in the
order-13 deviation-two branch.

SCOPE:
  Continue from

    order13_homogeneous_q3_height3_nonreduced_ci_rigidity_reduction.v.

  Let

    S := C[x1,x2,x3,x4],
    Q := (q1,q2,q3),
    B := S/Q,
    I := Q+(f1,f2,f3),
    L := I/Q subset B,
    A := B/L,
    N := length_C(A)>=32,

  where q1,q2,q3 form a regular sequence of quadrics, B is a one-dimensional
  graded Gorenstein complete intersection of multiplicity eight, and B may be
  nonreduced.

  Put

    d := min { n : L_n != 0 }.

  This file performs one bounded task only: close the subcase in which L_d
  contains a B-nonzerodivisor.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. A REGULAR ELEMENT IN THE MINIMAL SLICE KILLS EVERY NEGATIVE ENDOMORPHISM
--------------------------------------------------------------------------

Let

  E := End_B(L).

Because L is an m-primary ideal containing a nonzerodivisor, E embeds in the
homogeneous total quotient ring Q(B).  Let

  x in E_r

be homogeneous of degree r<0.

Assume that there exists

  g in L_d

which is a B-nonzerodivisor.

Since x is an endomorphism of L,

  x*g in L_{d+r}.

But r<0 and d is the least degree in which L is nonzero, so

  L_{d+r}=0.

Hence

  x*g=0.

The element g is a nonzerodivisor and therefore becomes a unit in Q(B).
Since x lies in Q(B), it follows that

  x=0.

Thus

  E_r=0 for every r<0,

and consequently

  delta_neg := sum_{r<0} dim_C E_r = 0.

Theorem regular_minimal_slice_has_no_negative_endomorphisms:
  If L_d contains a B-nonzerodivisor, then

    delta_neg=0.
Qed.

--------------------------------------------------------------------------
2. TANGENT CLOSURE
--------------------------------------------------------------------------

From the preceding nonreduced rigidity reduction,

  epsilon_L := length_C Ext^1_B(L,L) >= 1,

and the nonnegative endomorphism defect satisfies

  delta_nonneg <= 12.

The intrinsic tangent formula is

  length_C Hom_B(L,A)
    = N-delta_nonneg-delta_neg+epsilon_L.

Using

  delta_neg=0,
  delta_nonneg<=12,
  epsilon_L>=1,

we obtain

  length_C Hom_B(L,A) >= N-11.

The natural injection

  Hom_B(L,A) -> Hom_S(I,A)

therefore yields

  dim_C Hom_S(I,A) >= N-11 > N-20.

Hence the necessary order-13 tangent-deficit gate fails.

Theorem homogeneous_q3_height3_nonreduced_CI_regular_minimal_slice_is_closed:
  No nonreduced H3-CI candidate whose least nonzero graded slice L_d contains
  a B-nonzerodivisor satisfies

    dim_C Hom_S(I,A) <= N-20.
Qed.

--------------------------------------------------------------------------
3. EQUAL GENERATOR DEGREES ARE AUTOMATICALLY IN THE CLOSED SUBCASE
--------------------------------------------------------------------------

Suppose the three minimal generators of L all have the same degree d.
Then L is generated by L_d.

Because L is m-primary in the one-dimensional Cohen--Macaulay ring B, L is not
contained in any minimal prime of B. Over C, the union of the finitely many
proper linear subspaces

  L_d intersect p

as p ranges over the minimal primes cannot cover the finite-dimensional vector
space L_d. Therefore L_d contains an element outside every minimal prime.
Since B is Cohen--Macaulay, its zero divisors are the union of its minimal
primes. Such an element is a B-nonzerodivisor.

Corollary equal_degree_nonreduced_H3_CI_is_closed:
  If

    deg(f1)=deg(f2)=deg(f3),

  then the nonreduced H3-CI child is tangent-closed.
Qed.

RESULT:
  homogeneous_q3_height3_nonreduced_CI_regular_minimal_slice_is_closed.

IMPORTANT_NONCONCLUSION:
  This does not close the full nonreduced H3-CI child.

  Any surviving nonreduced H3-CI candidate must have the entire least-degree
  generator slice contained in the zero-divisor locus. In particular, the
  equal-degree generator case is eliminated.

  It does not close H2-CM or H2-NCM.
  It does not close homogeneous q=3, q<=2, or Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  homogeneous_q3_height3_nonreduced_CI_regular_minimal_slice_is_closed.
  not homogeneous_q3_height3_nonreduced_CI_closed.
  not homogeneous_q3_closed.

MISSING_OBJECT:
  Analyze only the residual nonreduced H3-CI case in which every element of the
  least nonzero slice L_d is a zero divisor. Equivalently, after ordering the
  generator degrees d1<=d2<=d3, the minimal-degree generator subspace is
  contained in at least one minimal prime of B.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow for this commit.
  2. If green, split the residual by the number of generators in the minimal
     degree slice: one or two (three is now closed).
  3. Use m-primaryness to force a higher-degree generator outside the trapping
     minimal prime.
  4. Do not claim full H3-CI closure before those residual degree patterns are
     eliminated.