Standalone closure of the s=1 fourth J-adic layer for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_fourth_J_adic_layer_rank_reduction.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    V := Span_C{l1,l2},
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

The preceding files prove

    G := J^2*T/J^3*T ~= C(-3)^s,

  where

    s = dim_C Syz_1(Q) in {0,1,2},

  and for the next layer

    H := J^3*T/J^4*T ~= C(-4)^h.

This file treats only

    s=1.

It proves

    h=0,
    H=0,
    J^3*T=0.

The s=2 case is not treated here.
The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Put

    P := C[l1,l2] = Sym(V).

Define the degree-three pure-transverse relation space

    K3 := Q_3 intersect P_3.

Theorem s1_gives_exactly_three_independent_pure_cubic_relations:
  If s=1, then

    dim_C K3 = 3.

Proof:
  The exact third-layer quotient established previously is

    G_3 ~= P_3 / K3.

  Since dim_C P_3=4 and s=dim_C G_3=1,

    dim_C K3=4-1=3.
Qed.

Theorem the_s1_pure_cubic_relation_space_is_basepoint_free:
  The three-dimensional space K3 has no common projective zero on

    P(V)=P^1.

Proof:
  The third-layer file constructs, in both first-conormal cases r=4 and r=3,
  two independent pure cubic relations contained in K3 whose common
  projective zero set is empty.

  In the r=4 case these are the two compatibility cubics Pz,Pw and their
  common-zero freeness follows from Qsat=J.

  In the r=3 case K3 contains l1*H0 and l2*H0 for a nonzero quadratic H0 in
  Q_2 intersect J^2_2.  The standing saturation condition Qsat=J rules out a
  projective zero of Q off the line; equivalently the complete pure-transverse
  relation space K3 cannot have a common point of P(V).  Thus K3 is
  basepoint-free.
Qed.

ExternalResult equal_degree_three_generator_Hilbert_Burch_over_two_variables:
  Let P=C[x,y], and let K be a homogeneous height-two ideal minimally generated
  by three independent cubic forms.  Then its minimal graded resolution is

    0 -> P(-5) direct_sum P(-4) -> P(-3)^3 -> K -> 0.

  Equivalently, the three cubic generators have exactly one minimal linear
  coefficient syzygy and one minimal quadratic coefficient syzygy.

  In particular,

    K_4=P_4.

Justification:
  Hilbert--Burch gives a two-generator first syzygy module.  If their
  coefficient degrees are a,b>=1, the quotient Hilbert numerator is

    1-3*t^3+t^(3+a)+t^(3+b).

  Height two forces divisibility by (1-t)^2, hence the derivative at t=1
  vanishes and

    a+b=3.

  Therefore {a,b}={1,2}.  The unique linear syzygy reduces the six-dimensional
  space P_1 tensor K_3 by exactly one dimension, so its image in P_4 has
  dimension five, which equals dim_C P_4.

Theorem s1_cubic_relations_fill_every_pure_quartic:
  If s=1, then

    V*K3 = P_4.

Proof:
  By the preceding theorems K3 is a three-dimensional basepoint-free subspace
  of P_3.  Let K=(K3) subset P be the ideal it generates.

  Basepoint freeness on P^1 means K has height two.  Since the three cubic
  forms are linearly independent, they are a minimal homogeneous generating
  set of K.

  Apply the external Hilbert--Burch result.  It gives

    K_4=P_4.

  Because K is generated in degree three,

    K_4=P_1*K3=V*K3.
Qed.

Theorem s1_forces_the_fourth_J_adic_layer_to_vanish:
  If s=1, then

    H=J^3*T/J^4*T=0.

Proof:
  The exact fourth-layer quotient is

    H ~= J^4/(J^5+(Q intersect J^4)).

  Its degree-four generator space is therefore

    H_4 ~= P_4/(Q_4 intersect P_4).

  Since K3 subset Q and Q is an ideal,

    V*K3 subset Q_4 intersect P_4.

  The preceding theorem gives

    V*K3=P_4.

  Hence

    Q_4 intersect P_4=P_4,

  so H_4=0.  The preceding fourth-layer classification proves H is generated
  in degree four and annihilated by the longitudinal maximal ideal.  Therefore

    H=0.
Qed.

Corollary s1_transverse_multiplication_rank_is_zero:
  In the s=1 case the map

    mu : V tensor_C G_3 -> H_4

  has

    rank(mu)=0.

  Thus the previously allowed values h=1 and h=2 do not occur when s=1.
Qed.

Corollary s1_closes_the_transverse_tower_at_J_cubed:
  If s=1, then

    J^3*T=0.

Proof:
  Since H=0,

    J^3*T=J^4*T=J*(J^3*T).

  The module J^3*T has finite length.  Localizing at the homogeneous maximal
  ideal and applying Nakayama gives

    J^3*T=0.
Qed.

Corollary exact_s1_initial_torsion_profile:
  In the s=1 line-core case,

    dim_C T_1=2,
    dim_C T_2=3,
    dim_C T_3=1,

  and

    J^3*T=0.

  In particular, every surviving transverse class has J-adic order at most
  two beyond the initial T/J*T layer.
Qed.

IMPORTANT_NONCONCLUSION:
  This file closes only s=1.

  The case

    s=2

  remains.  Its degree-three pure-transverse relation space has dimension two,
  and the previous third-layer proof supplies a basepoint-free pair of cubics.
  No conclusion about its fourth or fifth J-adic layers is asserted here.

  No tangent-gate contradiction is claimed in this file.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_third_J_adic_layer_bounded.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_closed.
  not q4_height2_CM_line_core_s2_closed.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Treat only s=2.  Its pure-transverse cubic relation space is the
  two-dimensional basepoint-free pair already constructed.  Determine the
  resulting degree-four and degree-five pure-transverse quotients and whether
  they force a uniform J-nilpotence bound.

NEXT_BOUNDED_OBJECT:
  In s=2, compute the Hilbert function of

    P/(K3)

  for the basepoint-free cubic pair K3 subset P_3, and transfer only the
  degree-four consequence to J^3*T/J^4*T.  Do not enter the depth-one branch.