Standalone first-conormal-layer classification for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_core_conic_closed.v

  in its surviving depth-two line-core branch.

  Work over

    S := C[x1,x2,x3,x4],
    J := Qsat = (l1,l2),
    Q subset J,

  where l1,l2 are independent linear forms, Q is minimally generated by
  exactly four independent quadrics, ht(Q)=2, and

    T := J/Q

  has finite length.

  The final high-degree generators f,g and the depth-one saturated-core branch
  are not used in this file.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Choose coordinates modulo J and put

  R := S/J ~= C[z,w],
  n := (z,w) subset R.

Since J is generated by a regular sequence of two linear forms,

  J/J^2 ~= R(-1)^2.

Define the first J-adic/conormal quotient

  E := T/J*T
     ~= J/(Q+J^2),

and shift once so that its two natural generators have degree zero:

  M := E(1).

Then M is a finite-length graded R-module with

  dim_C M_0 = 2.

Write the four quadratic generators of Q as

  q_j = l1*a_j + l2*b_j,

with a_j,b_j linear forms in S.  Reducing the coefficient pairs modulo J gives
four columns

  v_j := (abar_j,bbar_j)^T in R_1^2.

Let

  r := dim_C Span_C{v_1,v_2,v_3,v_4}.

Equivalently,

  r = 4 - dim_C(Q_2 intersect J^2_2).

Theorem exact_conormal_presentation:
  After a constant change of basis among the four generators of Q and removal
  of zero/redundant columns, M has a minimal graded presentation

    R(-1)^r  --A-->  R^2  -> M -> 0,

  where A is a 2 by r matrix of linear forms and M has finite length.

Proof:
  Modulo J^2, multiplication by an element of S factors through its residue in
  R=S/J.  Therefore the image of Q in J/J^2 is exactly the R-submodule
  generated by the four degree-one coefficient columns v_j.

  Since Q itself is generated by its four quadrics, there are no additional
  higher-degree generators of this image.  Taking a C-basis of their span gives
  the displayed presentation.

  The two generators of J/J^2 survive minimally in degree one because Q has no
  linear forms, so after shifting they give the two minimal degree-zero
  generators of M.

  Finally E is a quotient of the finite-length module T, hence E and M are
  finite length.
Qed.

ExternalResult finite_length_resolution_over_two_variable_polynomial_ring:
  Let R=C[z,w].  Every nonzero finite-length finitely generated graded
  R-module has depth zero and projective dimension two.  Thus its minimal free
  resolution has length two.  This is the Auslander--Buchsbaum formula together
  with Hilbert's syzygy theorem.

Theorem the_linear_relation_rank_is_exactly_three_or_four:
  One has

    r in {3,4}.

Proof:
  Let the minimal free resolution of M be

    0 -> F2 -> R(-1)^r -> R^2 -> M -> 0.

  Because M has rank zero over the fraction field of R,

    rank(F2)=r-2.

  Write

    F2 = direct_sum_j R(-d_j).

  Minimality gives

    d_j >= 2.

  The Hilbert numerator is

    P(t)=2-r*t+sum_j t^(d_j).

  Since M has finite length over the two-dimensional polynomial ring R,
  P(t) is divisible by (1-t)^2.  In particular

    P'(1)=0,

  so

    sum_j d_j = r.

  There are r-2 summands in F2 and each d_j is at least two.  Hence

    r = sum_j d_j >= 2*(r-2),

  which gives r<=4.

  On the other hand r=2 would give rank(F2)=0 and Hilbert numerator

    2-2*t,

  whose derivative at t=1 is nonzero, contradicting finite length.  Values
  r<2 cannot generically generate the rank-two module J/J^2 and likewise
  cannot have finite-length cokernel.

  Therefore r is exactly three or four.
Qed.

Corollary at_most_one_quadratic_generator_direction_lies_in_J_squared:
  One has

    dim_C(Q_2 intersect J^2_2) in {0,1}.

  More precisely,

    r=4  iff  Q_2 intersect J^2_2 = 0,

    r=3  iff  dim_C(Q_2 intersect J^2_2)=1.
Qed.

Theorem exact_syzygy_degrees_in_the_two_cases:
  The minimal R-resolution of M is exactly one of the following.

  FOUR-RELATION CASE:

    0 -> R(-2)^2 -> R(-1)^4 -> R^2 -> M -> 0.

  THREE-RELATION CASE:

    0 -> R(-3) -> R(-1)^3 -> R^2 -> M -> 0.

Proof:
  If r=4, then F2 has rank two and the sum of its two generator degrees is
  four.  Since each degree is at least two, both degrees are exactly two.

  If r=3, then F2 has rank one and its unique generator degree has sum three,
  hence is exactly three.
Qed.

Theorem exact_first_conormal_Hilbert_dichotomy:
  The Hilbert series of M is exactly

    Hilb_M(t)=2

  in the four-relation case, and

    Hilb_M(t)=2+t

  in the three-relation case.

Equivalently, before the shift,

    Hilb_E(t)=2*t

  or

    Hilb_E(t)=2*t+t^2.

In particular

    length_C(E) in {2,3},

and in every case

    n^2*E=0.

In the four-relation case the stronger statement

    n*E=0

holds.

Proof:
  For r=4 the resolution gives

    Hilb_M(t)
      =(2-4*t+2*t^2)/(1-t)^2
      =2.

  For r=3 it gives

    Hilb_M(t)
      =(2-3*t+t^3)/(1-t)^2
      =2+t.

  The annihilation statements follow immediately from these graded Hilbert
  functions because M is generated in degree zero.  Shifting does not change
  module length or the action of n.
Qed.

Corollary exact_degree_two_J_adic_split:
  Recall from the line-core setup that

    dim_C T_1=2,
    dim_C T_2=3.

  Then

  FOUR-RELATION CASE:
    dim_C (J*T)_2 = 3,
    E_2=0.

  THREE-RELATION CASE:
    dim_C (J*T)_2 = 2,
    dim_C E_2=1.

Proof:
  The degree-two exact quotient

    T_2 -> E_2=T_2/(J*T)_2

  together with the preceding Hilbert dichotomy gives the formulas.
Qed.

Theorem finite_length_forces_maximal_minor_support_at_the_line_origin:
  In either presentation, the ideal of maximal 2 by 2 minors of A is
  n-primary in R.

Proof:
  The support of the cokernel M is the vanishing set of its zeroth Fitting
  ideal, which is generated by the maximal minors of A.  Since M is finite
  length, its support is only the homogeneous maximal ideal n.  Hence the
  radical of the maximal-minor ideal is n.
Qed.

Corollary the_line_core_first_layer_has_no_longitudinal_projective_support:
  No nonzero point of P^1=Proj(R) can support the first conormal quotient E.

  Thus any surviving long torsion tail in T cannot come from failure of the
  four coefficient columns to generate the conormal bundle at a projective
  point of the line.  It must live in deeper J-adic layers.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does NOT yet bound the full length or top degree of

    T=J/Q.

  It classifies only

    T/J*T.

  In particular, the equalities

    n^2*(T/J*T)=0

  and

    length(T/J*T)<=3

  do not by themselves imply a uniform bound on J^k*T or on the full torsion
  tail.  The transverse actions of l1,l2 on successive J-adic layers still
  require analysis.

  No tangent-gate contradiction is claimed in this file.
  The depth-one saturated-core branch is untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the next J-adic layer

    J*T / J^2*T

  in the two exact first-layer cases r=4 and r=3, using the quadratic
  J^2-components of the four q_j and the commutativity constraints among
  l1,l2,z,w.

  Determine whether those constraints force a uniform nilpotence bound

    J^k*T=0

  strong enough to produce a large annihilator/Hom carrier in A.

NEXT_BOUNDED_OBJECT:
  Split only into r=4 and r=3.  Compute the induced multiplication maps from
  the classified first conormal quotient into J*T/J^2*T.  Do not enter the
  depth-one deficiency branch.
