Standalone tangent closure of the exact H00 endpoint in the homogeneous q=4,
height-two multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H00_residual_module_classification.v
    order13_q4_height2_depth_one_multiplicity_one_H00_saturated_incidence_classification.v
    order13_q4_height2_depth_one_multiplicity_one_H00_fourplane_classification.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset Qsat,
    B := S/Q,
    Ccore := S/Qsat,
    T := Qsat/Q,
    P := (l1,l2),
    D := P/Qsat,

  in the exact H00 state

    Hilb_D(t)=2*t/(1-t).

The completed four-plane classification proves that every valid original
four-quadric H00 core lies in one of the six P1P1/J2 families and has the exact
saturation defect

    T ~= C(-2),
    m*T=0.

The P2 saturated type is not realizable by four independent quadrics.

Let

    I := Q+(f,g),
    d := deg(f) >= 3,
    e := deg(g) >= 3,
    A := S/I = B/(f,g),
    N := length_C(A) >= 32.

The necessary order-13 tangent gate is

    t(A) := dim_C Hom_S(I,A) <= N-20.

This file proves that every valid H00 endpoint violates that gate.

No H01 or H11 branch is entered.
No q<=3 branch is entered.
No full order-13 closure is claimed.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. A UNIFORM MULTIPLICITY-TWO RESIDUAL RING
--------------------------------------------------------------------------

Put

    J := Ann_S(D).

The completed H00 residual classification leaves only the two abstract module
shapes P1P1 and J2 after the P2 four-plane exclusion.

Theorem H00_annihilator_has_uniform_three_generator_shape:
  In every surviving H00 family, after a graded linear coordinate change,

    J = L+(q)

  where L is generated by two independent linear forms and, modulo L, q is
  exactly one of

    u*(u-h),
    u^2.

  Consequently

    R0 := S/J

  is one of

    C[h,u]/(u*(u-h)),
    C[h,u]/(u^2).

  In either case R0 is a one-dimensional Cohen--Macaulay standard graded ring
  of multiplicity two, and J is generated by two linear forms and one quadric.

Proof:
  In H00-P1P1 the residual classification gives

    Ann_S(D)=L+(u*(u-h)).

  In H00-J2 it gives

    Ann_S(D)=L+(u^2).

  Quotienting by the two independent members of L leaves the displayed
  quadratic hypersurface in C[h,u].  A nonzero hypersurface in the polynomial
  ring C[h,u] is Cohen--Macaulay of dimension one; its quadratic degree gives
  multiplicity two.
Qed.

Let

    m0 := (h,u) subset R0.

Theorem H00_residual_module_is_the_irrelevant_ideal_of_R0:
  There is a graded R0-module isomorphism

    D ~= m0.

Proof:
  P1P1 case.
  In

    R0=C[h,u]/(u*(u-h)),

  the ideal m0=(h,u) has Hilbert series 2*t/(1-t).  With generators

    e0:=h-u,
    e1:=u,

  multiplication by u satisfies

    u*e0=0,
    u*e1=h*e1.

  Thus the C[h]-free rank-two module m0 has exactly the diagonal P1P1 action
  from the residual classification, hence agrees with D.

  J2 case.
  In

    R0=C[h,u]/(u^2),

  take

    e0:=u,
    e1:=h.

  Then

    u*e0=0,
    u*e1=h*e0,

  which is exactly the normalized Jordan action.  Again m0 and D are free of
  rank two over C[h], generated in degree one, so they agree.
Qed.

--------------------------------------------------------------------------
2. THE FINAL PAIR ON THE PLANE-LINE QUOTIENT
--------------------------------------------------------------------------

Put

    Rline := S/P ~= C[s,t].

Theorem H00_final_pair_is_regular_on_Rline:
  The images f_R,g_R of f,g in Rline form a homogeneous regular sequence and

    length_C Rline/(f_R,g_R)=d*e.

Proof:
  Since A is Artinian, its quotient Ccore/(f,g)Ccore is Artinian.  The further
  quotient Rline/(f_R,g_R) is therefore Artinian.

  Thus f_R,g_R form a homogeneous system of parameters in the two-dimensional
  polynomial ring Rline.  Polynomial rings are Cohen--Macaulay, so the pair is
  regular.  The complete-intersection length is d*e.
Qed.

Corollary H00_line_Koszul_homology_vanishes:
  One has

    H_2(f,g;Rline)=0,
    H_1(f,g;Rline)=0.
Qed.

--------------------------------------------------------------------------
3. THE CORE KOSZUL DEFECT IS EXACTLY THE RESIDUAL DEFECT
--------------------------------------------------------------------------

Apply the two-element Koszul complex to

    0 -> D -> Ccore -> Rline -> 0.

Put

    Hcore := H_1(f,g;Ccore).

Theorem H00_core_H1_is_residual_H1:
  There is a natural graded isomorphism

    Hcore ~= H_1(f,g;D).

Proof:
  The relevant part of the long exact Koszul sequence is

    H_2(f,g;Rline)
      -> H_1(f,g;D)
      -> Hcore
      -> H_1(f,g;Rline).

  Both outside terms vanish by regularity on Rline.
Qed.

Corollary J_annihilates_H00_core_H1:
  One has

    J*Hcore=0.

Proof:
  J annihilates D, hence it annihilates every Koszul chain and homology module
  built from D.  Transfer across the preceding isomorphism.
Qed.

--------------------------------------------------------------------------
4. A ONE-DIMENSIONAL CUT LENGTH L
--------------------------------------------------------------------------

Let the images of f,g in R0=S/J be f0,g0 and put

    K0 := (f0,g0) subset R0,
    Lcut := length_C(R0/K0).

Theorem H00_R0_cut_has_finite_length:
  Lcut is finite.

Proof:
  Since D~=m0, the quotient D/(f,g)D is the graded module

    m0/K0*m0.

  The exact sequence in the preceding section embeds this module into the finite
  length module Ccore/(f,g)Ccore.  Hence m0/K0*m0 has finite length.

  Because K0*m0 subset K0, there is a surjection

    R0/(K0*m0) -> R0/K0.

  The source has finite length: its positive-degree part is a quotient of
  m0/K0*m0 and only the one-dimensional degree-zero constants remain outside
  m0.  Therefore R0/K0 also has finite length.
Qed.

Put

    M := max(d,e).

Theorem H00_uniform_multiplicity_two_cut_bound:
  One has

    Lcut <= 2*M.

Proof:
  There are two cases.

  REDUCED P1P1 CASE.
  Here

    R0=C[h,u]/(u*(u-h))

  is the homogeneous coordinate cone over two distinct reduced points.  It
  embeds in the direct sum of the two branch rings C[h] direct_sum C[h].

  On each branch, finite colength of K0 implies that at least one of f0,g0 has
  nonzero restriction.  The induced ideal on that branch is therefore

    (h^r)

  for some r belonging to {d,e,min(d,e)} and in particular r<=M.

  Hence R0/K0 injects into a sum of two one-variable quotients, each of length at
  most M.  Therefore

    Lcut<=2*M.

  JORDAN CASE.
  Here

    R0=C[h,u]/(u^2).

  Every homogeneous element of degree n has the form

    alpha*h^n + beta*u*h^(n-1).

  Such an element is a nonzerodivisor exactly when alpha!=0.  If both f0 and g0
  had alpha=0, then K0 would be contained in (u), and R0/K0 would still surject
  onto C[h], contradicting finite length.

  Thus at least one member of {f0,g0} is a homogeneous nonzerodivisor, of degree
  at most M.  Quotienting the multiplicity-two Cohen--Macaulay ring R0 by a
  degree-r homogeneous nonzerodivisor has length 2*r.  Since adding the other
  generator can only decrease length,

    Lcut<=2*r<=2*M.
Qed.

--------------------------------------------------------------------------
5. THE RESIDUAL CUT IS AT LEAST AS LARGE AS Lcut
--------------------------------------------------------------------------

Put

    rho := length_C(D/(f,g)D)
         = length_C(m0/(K0*m0)).

Theorem H00_residual_cut_dominates_R0_cut:
  One has

    rho >= Lcut.

More precisely, if

    s := dim_C K0/(m0*K0),

then s is 1 or 2 and

    rho = Lcut+s-1.

Proof:
  Since K0 is a nonzero m0-primary ideal generated by the two displayed forms,
  its minimal number of homogeneous generators is s in {1,2}.

  The exact sequence

    0 -> m0/(K0*m0)
      -> R0/(K0*m0)
      -> C
      -> 0

  gives

    length R0/(K0*m0)=rho+1.

  The exact sequence

    0 -> K0/(K0*m0)
      -> R0/(K0*m0)
      -> R0/K0
      -> 0

  gives

    length R0/(K0*m0)=s+Lcut.

  Equating the two lengths yields

    rho=Lcut+s-1>=Lcut.
Qed.

--------------------------------------------------------------------------
6. THE FINAL ARTIN LENGTH DOMINATES d*e+Lcut
--------------------------------------------------------------------------

Theorem H00_core_cut_length:
  One has

    length_C Ccore/(f,g)Ccore = d*e+rho.

Proof:
  From

    0 -> D -> Ccore -> Rline -> 0

  and H_1(f,g;Rline)=0, the degree-zero portion of the long exact Koszul sequence
  gives a short exact sequence

    0 -> D/(f,g)D
      -> Ccore/(f,g)Ccore
      -> Rline/(f_R,g_R)
      -> 0.

  Add lengths and use the complete-intersection length d*e.
Qed.

Theorem H00_final_length_lower_bound:
  One has

    N >= d*e+rho >= d*e+Lcut.

Proof:
  The completed four-plane classification gives

    T ~= C(-2),
    m*T=0.

  Since d,e>=3, both f and g act by zero on T.  Apply the Koszul complex to

    0 -> T -> B -> Ccore -> 0.

  At H_0 one obtains

    H_1(f,g;Ccore) -> T -> A -> Ccore/(f,g)Ccore -> 0.

  Therefore

    N
      = length Ccore/(f,g)Ccore
        + length T
        - dim image(H_1(f,g;Ccore)->T).

  Here length T=1 and the image has dimension at most one, so

    N>=length Ccore/(f,g)Ccore=d*e+rho.

  The preceding theorem gives rho>=Lcut.
Qed.

--------------------------------------------------------------------------
7. THE PRODUCT mJ ANNIHILATES THE FULL B-KOSZUL H1
--------------------------------------------------------------------------

Put

    H := H_1(f,g;B),
    U := image(H_1(f,g;T) -> H).

Theorem H00_torsion_part_is_killed_by_m:
  One has

    m*U=0.

Proof:
  Since m*T=0, the maximal ideal annihilates every Koszul chain and every
  Koszul homology module built from T.  Hence it annihilates the image U.
Qed.

Theorem H00_quotient_H_by_U_is_killed_by_J:
  One has

    J*(H/U)=0.

Proof:
  The long exact sequence for

    0 -> T -> B -> Ccore -> 0

  contains

    H_1(f,g;T) -> H -> Hcore.

  Thus H/U identifies with the image of H in Hcore.  The earlier result says
  J*Hcore=0.
Qed.

Theorem H00_product_annihilator:
  One has

    m*J*H=0.

Proof:
  Let xi be in H and j in J.  Since J kills H/U, j*xi belongs to U.  The maximal
  ideal m kills U.  Hence every element of mJ kills xi.
Qed.

Pass to A and let

    E := Ann_A(H).

Corollary H00_product_carrier_inside_E:
  If m_A and J_A denote the images in A, then

    m_A*J_A subset E.
Qed.

--------------------------------------------------------------------------
8. THE PRODUCT CARRIER HAS CODIMENSION AT MOST Lcut+3
--------------------------------------------------------------------------

Theorem H00_J_quotient_length_bound:
  One has

    length_C(A/J_A) <= Lcut.

Proof:
  One has

    A/J_A ~= S/(Q,f,g,J),

  which is a quotient of

    S/(J,f,g)=R0/K0.

  The latter has length Lcut.
Qed.

Theorem H00_three_generator_conormal_bound:
  One has

    dim_C J_A/(m_A*J_A) <= 3.

Proof:
  The ideal J is generated by two linear forms and one quadric.  Their images
  generate J_A as an A-ideal, so its minimal number of generators is at most
  three.  By graded Nakayama this is exactly the dimension bound on
  J_A/(m_AJ_A).
Qed.

Theorem H00_product_carrier_codimension:
  One has

    length_C A/(m_A*J_A) <= Lcut+3.

Consequently

    dim_C(m_A*J_A) >= N-Lcut-3.

Proof:
  Since m_AJ_A subset J_A, there is a short exact sequence

    0 -> J_A/(m_AJ_A)
      -> A/(m_AJ_A)
      -> A/J_A
      -> 0.

  Apply the preceding two bounds and subtract from length(A)=N.
Qed.

--------------------------------------------------------------------------
9. THE TWO-COPY HOM CARRIER
--------------------------------------------------------------------------

Put

    Lfinal := (f,g)B.

Theorem H00_two_copy_annihilator_carrier:
  There is a natural C-linear injection

    E direct_sum E -> Hom_B(Lfinal,A).

Hence

    dim_C Hom_B(Lfinal,A) >= 2*dim_C E.

Proof:
  Let

    Msyz:=Syz_B(f,g).

  Then

    H=Msyz/B*(-g,f).

  A B-linear map Lfinal->A is represented by a pair (alpha,beta) in A^2 whose
  coordinate functional kills Msyz.  Since f=g=0 in A, the coordinate maps on
  Msyz descend to H.  If alpha,beta lie in E=Ann_A(H), multiplication by either
  coefficient kills those descended coordinate maps.  Thus every pair in E^2
  defines a map Lfinal->A.  Distinct pairs remain distinct in A^2.
Qed.

Theorem H00_two_cut_maps_embed_into_full_tangent_space:
  There is a natural injection

    Hom_B(Lfinal,A) -> Hom_S(I,A).

Proof:
  Since I/Q=Lfinal, the S-linear maps I->A that vanish on Q are exactly the
  B-linear maps Lfinal->A.  They form a C-linear subspace of Hom_S(I,A).
Qed.

Corollary H00_uniform_tangent_lower_bound:
  One has

    t(A) >= 2*N-2*Lcut-6.

Proof:
  The product carrier has dimension at least N-Lcut-3 and lies inside E.
  Combine the two-copy carrier with the injection into the full tangent space.
Qed.

--------------------------------------------------------------------------
10. H00 FAILS THE ORDER-13 TANGENT GATE
--------------------------------------------------------------------------

Theorem H00_tangent_excess_is_uniformly_positive:
  One has

    t(A)-(N-20)
      >= N-2*Lcut+14
      >= d*e-Lcut+14
      >= d*e-2*max(d,e)+14
      > 0.

Proof:
  The tangent lower bound gives

    t(A)-(N-20)
      >= (2*N-2*Lcut-6)-(N-20)
      = N-2*Lcut+14.

  The final-length estimate gives

    N>=d*e+Lcut,

  hence

    N-2*Lcut+14>=d*e-Lcut+14.

  The multiplicity-two cut bound gives

    Lcut<=2*M,
    M:=max(d,e).

  Write mdeg:=min(d,e)>=3.  Then

    d*e-2*M+14
      = M*(mdeg-2)+14
      >= M+14
      >=17.

  Thus the excess is strictly positive.
Qed.

Corollary H00_violates_the_order13_tangent_gate:
  One has

    t(A)>N-20.

Therefore no saturation-valid H00 endpoint can satisfy the necessary order-13
tangent condition.
Qed.

Corollary q4_height2_multiplicity_one_depth_one_H00_tangent_closed:
  The complete exact H00 state is closed by the tangent gate, uniformly across
  all six surviving four-plane families and all admissible dual-discriminant
  parameters.
Qed.

--------------------------------------------------------------------------
11. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_CLOSED:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.

ALREADY_CLOSED:
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.

IMPORTANT_NONCONCLUSION:
  This file does NOT treat H01 or H11.
  It does NOT close the full multiplicity-one depth-one branch.
  It does NOT close q=4 height two.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Return to the two remaining multiplicity-one Hilbert-floor states

    H01: (u1,u2)=(0,2),
         Hilb_D >= (2*t+t^2)/(1-t),

    H11: (u1,u2)=(1,3),
         Hilb_D >= (t+t^2)/(1-t),

  and attack only the smaller residual-tail problem H11 next.  Determine the
  smallest possible Artinian reduction numerator beyond t+t^2 and whether the
  four-independent-quadric condition forces that tail to terminate.

NEXT_ACTIONS:
  1. Leave H00 and H10; both are tangent-closed.
  2. Stay in q=4 height-two multiplicity one.
  3. Enter only H11.
  4. Determine the smallest possible exact Artinian reduction Hilbert function.
  5. Stop before H01 or q<=3.
