Standalone quadratic-predecessor split for the multiplicity-five h=(1,2,2)
subbranch of the homogeneous q=4, height-three order-13 low-multiplicity
problem.

SCOPE:
  Continue from

    order13_q4_height3_e5_122_cyclic_torsion_annihilator_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has

    h(Cbar/ell*Cbar)=(1,2,2).

  The preceding cyclic-torsion reduction proves

    Hilb_T(t)=t+t^2+t^3,
    length_C(T)=3,
    T ~= C[z]/(z^3)(-1),

    J:=Ann_B(T),
    length_C(B/J)=3,

    X:=Ann_A(T)=J/L,
    dim_C X=N-3,

  for L:=(f,g)B, and every final cut annihilates T.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded structural step.  It passes the final
cuts to quadratic saturated-core predecessors, closes the case in which the
lower quadratic is regular on Cbar, and reduces the zerodivisor case to one
first delayed layer.  The latter is NOT closed here.

Theorem parameter_multiplication_is_iso_from_degree_two:
  For every n>=2,

    ell:Cbar_n -> Cbar_(n+1)

  is a vector-space isomorphism.

Proof:
  From

    Hilb_Cbar(t)=(1+2*t+2*t^2)/(1-t)

  one has

    dim_C Cbar_0=1,
    dim_C Cbar_1=3,
    dim_C Cbar_n=5 for every n>=2.

  Multiplication by ell is injective in every degree because ell is a
  nonzerodivisor.  For n>=2 the source and target both have dimension five,
  hence the injection is an isomorphism.
Qed.

Write

  d:=deg(f)<=D:=deg(g),
  k:=D-d>=0.

Theorem final_cuts_have_quadratic_predecessors:
  There are unique

    a,b in Cbar_2

  such that

    fbar=ell^(d-2)*a,
    gbar=ell^(D-2)*b.

  Put

    s:=d-2>=1,
    K_i:=(a,ell^i*b).

  Then

    Lbar:=(fbar,gbar)Cbar=ell^s*K_k,

  multiplication by ell^s gives a Cbar-module isomorphism

    K_k ~= Lbar,

  and both K_k and K_0=(a,b) are m-primary in Cbar.

Proof:
  The preceding parameter-isomorphism theorem gives unique degree-two
  predecessors of fbar and gbar.

  The image Lbar is m-primary because Cbar/Lbar is a quotient of the finite
  algebra A.  Since ell avoids every minimal prime, removing the common power
  ell^s does not change the radical, so K_k is m-primary.  Since

    K_k subseteq K_0,

  the larger ideal K_0 is m-primary as well.
Qed.

Theorem core_Hom_space_injects_into_the_actual_two_cut_conormal_space:
  There is a natural injection

    Hom_Cbar(K_k,X) -> Hom_B(L,A).

Proof:
  Projection B->Cbar induces a surjection

    L -> Lbar

  whose kernel is L intersect T.  No assertion that this intersection is zero
  is needed.

  Since X=Ann_A(T), the B-action on X factors through Cbar.  Therefore every
  Cbar-linear map

    Lbar -> X

  composes with L->Lbar and X->A to give a B-linear map L->A.  The construction
  is injective because L->Lbar is surjective.

  Finally multiplication by ell^s identifies K_k with Lbar.
Qed.

Define for every i>=0

  eta_i
    :=dim_C X-dim_C Hom_Cbar(K_i,X)
     =(N-3)-dim_C Hom_Cbar(K_i,X).

Theorem tangent_gate_forces_quadratic_core_deficit_seventeen:
  If the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A)<=N-20,

  then

    eta_k>=17.

Proof:
  Maps I->A vanishing on Q contain Hom_B(L,A), and the preceding theorem gives

    dim Hom_S(I,A)
      >=dim Hom_B(L,A)
      >=dim Hom_Cbar(K_k,X).

  Hence the tangent gate implies

    dim Hom_Cbar(K_k,X)<=N-20.

  Since dim X=N-3, this is exactly eta_k>=17.
Qed.

Theorem multiplication_maps_bound_each_quadratic_core_deficit:
  For every i>=0,

    eta_i<=dim_C(0:_X K_i).

Proof:
  Multiplication gives a Cbar-linear map

    X -> Hom_Cbar(K_i,X),
    x |-> (u |-> u*x).

  Its kernel is exactly 0:_X K_i.  Rank-nullity gives an image of dimension

    dim X-dim(0:_X K_i).

  This image is contained in the full Hom space, which proves the inequality.
Qed.

SECTION REGULAR_QUADRATIC_LOWER.

Assume a is a nonzerodivisor on Cbar.

Choose any homogeneous quadratic lift of a to B, again denoted a.

Theorem regular_quadratic_kernel_is_contained_in_the_three_dimensional_torsion:
  One has

    0:_B a = 0:_T a,

  and therefore

    length_C(0:_B a)<=3.

Proof:
  If a*x=0 in B, then after projection to Cbar one has

    a*xbar=0.

  Regularity of a on Cbar gives xbar=0, hence x belongs to T.  The reverse
  equality is just the definition of the kernel on T.

  The preceding cyclic-torsion reduction gives length(T)=3.
Qed.

Theorem regular_quadratic_section_of_B_has_length_at_most_thirteen:
  One has

    length_C(B/aB)
      =10+length_C(0:_T a)
      <=13.

Proof:
  Multiplication by the quadratic a gives the exact sequence

    0 -> (0:_B a)(-2)
      -> B(-2)
      --a--> B
      -> B/aB
      -> 0.

  The finite kernel does not change the one-dimensional Hilbert polynomial of
  B.  Since e(B)=5, evaluation of the Hilbert-series identity at t=1 gives

    length(B/aB)=2*e(B)+length(0:_B a).

  Use the preceding kernel theorem.
Qed.

Theorem regular_quadratic_lower_forces_eta_at_most_thirteen:
  One has

    eta_k<=13.

Proof:
  Since a belongs to K_k,

    0:_X K_k subseteq 0:_A a.

  Multiplication by a on the finite-dimensional vector space A has kernel and
  cokernel of equal dimension, hence

    dim_C(0:_A a)=length_C(A/aA).

  The latter quotient is a quotient of B/aB, so it has length at most thirteen.
  Apply the multiplication-map bound at i=k.
Qed.

Corollary regular_quadratic_lower_is_closed:
  No candidate in REGULAR_QUADRATIC_LOWER can satisfy the necessary order-13
  tangent gate.

Proof:
  The tangent gate forces eta_k>=17, while the preceding theorem gives
  eta_k<=13.
Qed.

END REGULAR_QUADRATIC_LOWER.

SECTION ZERODIVISOR_QUADRATIC_LOWER.

Assume a is a zerodivisor on Cbar.

Put

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem the_saturated_quadratic_colon_is_proper:
  Gsat is a proper homogeneous ideal of Cbar.

Proof:
  Since Cbar is one-dimensional Cohen--Macaulay, every associated prime is
  minimal.  Choose a minimal prime P containing the zerodivisor a.

  Because K_0=(a,b) is m-primary, b does not belong to P.  Thus b is a unit in
  Cbar_P and

    G_P=(a:b)_P=(a)_P,

  which is proper.

  The parameter ell is a nonzerodivisor, hence ell is not in P and becomes a
  unit after localization.  Saturating by ell does not change the localization,
  so

    (Gsat)_P=G_P.

  Therefore Gsat is proper.
Qed.

Theorem quadratic_colon_saturates_after_one_parameter_step:
  One has

    G:ell=Gsat,

  and hence

    G:ell^j=Gsat

  for every j>=1.

Proof:
  First show that G and Gsat agree in every degree n>=2.  If x in Gsat_n, choose
  m with

    ell^m*x*b in (a).

  Write

    ell^m*x*b=a*c

  with c in Cbar_(n+m).  Since multiplication by ell is an isomorphism from
  degree two onward, write c=ell^m*c0 with c0 in Cbar_n.  Cancellation of the
  nonzerodivisor ell gives

    x*b=a*c0,

  hence x in G.

  The preceding properness theorem removes degree zero, because a proper
  homogeneous ideal has zero degree-zero part.  Thus Gsat/G can occur only in
  degree one.  Multiplying a degree-one class by ell moves it to degree two,
  where Gsat and G agree.  Therefore ell*Gsat subseteq G, proving

    G:ell=Gsat.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i

and

  Delta_i
    :=dim_C Hom_Cbar(K_(i-1),X)
      -dim_C Hom_Cbar(K_i,X).

Lemma exact_delayed_layer_annihilator:
  V_i is cyclic, generated by the class of ell^(i-1)*b, and

    Ann_Cbar(V_i)=(G:ell^(i-1),ell).

Proof:
  The generator statement follows from

    K_(i-1)=(a,ell^(i-1)*b),
    K_i=(a,ell^i*b).

  If c kills the displayed generator modulo K_i, then

    c*ell^(i-1)*b
      =p*a+q*ell^i*b.

  Hence

    (c-q*ell)*ell^(i-1)*b belongs to (a),

  giving c in (G:ell^(i-1),ell).  The reverse inclusion is immediate.
Qed.

Theorem every_delayed_layer_from_two_on_has_nonpositive_defect:
  For every i>=2,

    Delta_i<=0.

Proof:
  For i>=2, the one-step saturation theorem gives

    G:ell^(i-1)=Gsat.

  Thus every V_i is, up to grading shift, the same cyclic module

    Cbar/(Gsat,ell).

  Put

    N_G:=0:_X Gsat.

  For y in N_G define a map K_i->X by

    a |-> 0,
    ell^i*b |-> y.

  It is well defined because every relation coefficient on ell^i*b lies in
  G:ell^i=Gsat.  In the cyclic presentation of V_i, its connecting class is
  represented by

    ell |-> y,
    Gsat |-> 0.

  This class vanishes exactly when y belongs to ell*N_G.  Therefore the
  explicit connecting classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_Cbar(Cbar/(Gsat,ell),X)
      =dim_C Hom_Cbar(V_i,X).

  Applying Hom(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  then gives Delta_i<=0.
Qed.

Theorem quadratic_baseline_deficit_is_at_most_thirteen:
  Put

    eta_0:=(N-3)-dim_C Hom_Cbar(K_0,X).

  Then

    eta_0<=13.

Proof:
  Since K_0=(a,b) is m-primary, a general constant combination

    q=lambda*a+mu*b

  is a quadratic nonzerodivisor on Cbar.  Lift q homogeneously to B.

  As in the regular-quadratic section above,

    0:_B q subseteq T,
    length_C(B/qB)
      =10+length_C(0:_T q)
      <=13.

  Since q belongs to K_0,

    0:_X K_0 subseteq 0:_A q,

  whose dimension is length(A/qA)<=length(B/qB)<=13.  Apply the multiplication
  bound at i=0.
Qed.

Theorem refine_the_general_parameter_for_the_first_layer_bound:
  The general parameter ell may be chosen simultaneously so that

    ell is a nonzerodivisor on Cbar,

  the h-vector of Cbar/ell*Cbar is (1,2,2), and

    ell has nonzero image in
      B/J ~= C[z]/(z^3).

Proof:
  The first two conditions hold on a nonempty Zariski-open subset of B_1.
  Since (B/J)_1 is one-dimensional, the condition that ell have zero image in
  B/J is a proper linear hyperplane.  Over C, the intersection of the first
  open set with the complement of this hyperplane is nonempty.
Qed.

Theorem ell_annihilator_of_X_has_dimension_at_most_six:
  For the refined general choice of ell,

    dim_C(0:_X ell)<=6.

Proof:
  Since ell is regular on Cbar, every element killed by ell in B lies in T.
  Under

    T ~= C[z]/(z^3)(-1),

  the image of ell in B/J is a nonzero scalar multiple of z.  Hence

    0:_B ell=T_3,

  a one-dimensional space.

  The top line T_3 annihilates T: products with T have degree at least four,
  while T_n=0 for n>=4.  Thus

    T_3 subseteq J=Ann_B(T).

  Therefore the kernel of multiplication by ell on the one-dimensional
  B-module J is exactly T_3 and has length one.  Since B/J has finite length,
  J has the same multiplicity as B, namely five.  The multiplication exact
  sequence on J gives

    length_C(J/ell*J)=5+1=6.

  Finally X=J/L, so

    X/ell*X=J/(L+ell*J)

  is a quotient of J/ell*J.  Hence length(X/ell*X)<=6.  On the finite vector
  space X, kernel and cokernel of multiplication by ell have equal dimension,
  proving the result.
Qed.

Theorem first_delayed_layer_has_defect_at_most_six:
  One has

    Delta_1<=6.

Proof:
  The cyclic module V_1 is killed by ell.  Evaluation at its generator injects

    Hom_Cbar(V_1,X) -> 0:_X ell.

  Applying Hom(-,X) to

    0 -> K_1 -> K_0 -> V_1 -> 0

  gives

    Delta_1<=dim_C Hom_Cbar(V_1,X).

  Use the preceding six-dimensional annihilator bound.
Qed.

Theorem zerodivisor_quadratic_lower_has_only_one_uncompensated_layer:
  For every k>=0,

    eta_k
      =eta_0+sum_(i=1)^k Delta_i
      <=19.

  More precisely, all layers i>=2 are nonpositive, so

    eta_k<=eta_0+Delta_1<=13+6=19.

Proof:
  The identity follows by telescoping the definitions of Delta_i.  Combine the
  baseline bound, the first-layer bound, and stable compensation from i=2 on.
Qed.

Corollary dangerous_zerodivisor_candidates_are_confined_to_a_three_value_window:
  If the necessary order-13 tangent gate holds in the zerodivisor-lower case,
  then

    eta_k in {17,18,19}.
Qed.

Interpretation:
  The regular lower-quadratic case is closed with margin four:

    eta_k<=13<17.

  In the zerodivisor case, the entire unbounded degree-gap direction is now
  harmless after the first delayed layer.  The only unresolved quantity is the
  combined finite defect

    eta_0+Delta_1.

  The crude independent bounds give nineteen, while closure requires sixteen.
  Thus the remaining obstruction is a finite three-dimensional compensation
  problem tied to the exact cyclic torsion string C[z]/(z^3)(-1); it is no
  longer an unbounded degree-gap problem.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove eta_0+Delta_1<=16.

  Therefore it does NOT close the full e=5, h=(1,2,2) height-three branch.

  It does not import the e=2 residual-intersection presentation, does not
  classify the full multiplication algebra of Cbar, and makes no claim for the
  remaining h-vectors, q=4 height two, homogeneous q<=3, the unrestricted
  nonhomogeneous local deviation-two frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e5_h122_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  In ZERODIVISOR_QUADRATIC_LOWER, prove

    eta_0+Delta_1<=16,

  where

    eta_0=(N-3)-dim_C Hom_Cbar((a,b),X),
    Delta_1=dim_C Hom_Cbar((a,b),X)
            -dim_C Hom_Cbar((a,ell*b),X),
    X=Ann_A(T),
    T~=C[z]/(z^3)(-1).

  Equivalently, show that the exact first connecting map supplies at least
  three dimensions of compensation beyond the independent bounds

    eta_0<=13,
    Delta_1<=6.

NEXT_BOUNDED_OBJECT:
  Compute only the first delayed cyclic layer

    V_1=(a,b)/(a,ell*b)

  in the zerodivisor-lower case.  Use the exact quotient

    B/Ann_B(T)~=C[z]/(z^3)

  to relate the quadratic baseline annihilator 0:_X(a,b) to the connecting
  rank for V_1.  Prove eta_0+Delta_1<=16 or stop at the first concrete core
  where the value reaches seventeen.
