Standalone square-zero socle-map closure for the multiplicity-four h=(1,2,1)
subbranch of the homogeneous q=4, height-three order-13 low-multiplicity
problem.

SCOPE:
  Continue only from

    order13_q4_height3_e4_121_exact_zero_divisor_residual_reduction.v
    order13_q4_height3_e4_121_quadratic_predecessor_self_action_reduction.v

  and work in the unique still-open ZERO_SELF_ACTION case.

Retain

  S := C[x1,x2,x3,x4],
  I := Q+(f,g) homogeneous and m-primary,
  A := S/I,
  N := length_C(A)>=32,

  B:=S/Q,
  T:=H^0_m(B),
  C:=B/T,
  J:=Ann_B(T),
  L:=(f,g)B,
  X:=J/L,

with

  e(B)=4,
  Hilb_T(t)=t+2*t^2+t^3,
  length_C(T)=4,
  m_B^3*T=0,

and in ZERO_SELF_ACTION

  T^2=0,
  T subseteq J,
  T ~= Z(-1),

where

  Z:=B/J

is an Artin Gorenstein complete intersection with Hilbert function (1,2,1).

The quadratic-predecessor reduction writes

  K_i:=(a,ell^i*b) subset C,

with a,b in C_2, K_0=(a,b) m-primary, and in the remaining zerodivisor-lower
case a a zerodivisor.  It proves

  eta_i:=dim_C X-dim_C Hom_C(K_i,X),

  tangent gate => eta_k>=16,
  eta_0<=12,
  Delta_i<=0 for every i>=2,

where

  Delta_i:=dim Hom_C(K_(i-1),X)-dim Hom_C(K_i,X),

and it constructs a cubic

  q:=ell*(a+lambda*b) in K_1

whose image in C is a nonzerodivisor and, in ZERO_SELF_ACTION,

  length_C(J/qJ)=16.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded closure step.  The embedded square-zero
torsion contributes socle-valued maps K_1->X that are not all multiplication
maps.  This improves the universal bound by at least one dimension, changing
eta_1<=16 into eta_1<=15.  Therefore the exact equality configuration isolated
in the preceding file cannot occur.

SECTION SQUARE_ZERO_SOCLE_MAP.

Assume

  T^2=0,
  T subseteq J.

Theorem final_cut_intersection_with_torsion_is_zero_or_top_line:
  One has

    L intersect T in {0,T_3}.

Proof:
  The final-cut ideal L is homogeneous and generated in degrees at least three.
  The torsion module is concentrated in degrees one, two, and three, with

    dim_C T_3=1.

  Hence L intersect T has no degree-one or degree-two part and is a graded
  subspace of T_3.  It is therefore either zero or the full top line.
Qed.

Put

  T_X:=(T+L)/L ~= T/(L intersect T) subset X.

Theorem exact_socle_dimensions_of_the_surviving_torsion:
  The C-socle of T_X is nonzero and has dimension

    1 if L intersect T=0,
    2 if L intersect T=T_3.

More precisely,

  if L intersect T=0, then
    T_X~=T and Soc_C(T_X)=T_3;

  if L intersect T=T_3, then
    T_X~=T/T_3 and Soc_C(T_X)=T_2 mod T_3.

Proof:
  In ZERO_SELF_ACTION the action on T factors through C, and the exact residual
  reduction identifies

    T~=Z(-1)

  with Z having Hilbert function (1,2,1).  Thus

    dim T_1=1,
    dim T_2=2,
    dim T_3=1.

  If no torsion is removed, the shifted Artin Gorenstein module has top socle
  T_3, which is one-dimensional.

  If T_3 is removed, every positive-degree element sends T_2 into the vanished
  degree-three piece, so all of T_2 becomes socle.  The degree-one generator is
  not socle because multiplication by Z_1 sends it onto the nonzero
  two-dimensional space T_2.  Hence the quotient socle is exactly T_2 mod T_3
  and has dimension two.
Qed.

Assume now k>=1 and put

  K_1=(a,ell*b).

Theorem the_first_delayed_pair_is_minimally_two_generated:
  The two displayed generators a and ell*b are both minimal.

Proof:
  The degree-two element a cannot belong to the ideal generated by the
  degree-three element ell*b.

  Conversely, if ell*b belonged to (a), then

    ell belongs to (a:b)=G.

  Hence 1 belongs to G:ell=Gsat, contradicting the properness of Gsat proved in
  the preceding quadratic-predecessor reduction.
Qed.

Let

  S_X:=Soc_C(T_X),
  s:=dim_C S_X.

Thus s=1 or s=2 according to the preceding theorem.

Theorem arbitrary_socle_values_define_a_two_generator_map_space:
  Every ordered pair (sigma,tau) in S_X direct_sum S_X defines a unique
  C-linear map

    psi_(sigma,tau):K_1 -> T_X subset X

  by

    a |-> sigma,
    ell*b |-> tau.

  These maps form a subspace

    P subseteq Hom_C(K_1,X)

  of dimension

    dim_C P=2*s.

Proof:
  Since a and ell*b are a minimal generating set over the graded local ring
  (C,m_C), every coefficient in every relation

    p*a+r*ell*b=0

  lies in m_C.  The socle S_X is killed by m_C, so arbitrary values sigma and
  tau in S_X satisfy every relation.  Evaluation on the two minimal generators
  identifies this map space with S_X direct_sum S_X.
Qed.

Let

  mu:X -> Hom_C(K_1,X),
  mu(x)(w):=w*x,

and put

  A_1:=0:_X K_1.

Then

  dim_C im(mu)=dim_C X-dim_C A_1.

Theorem multiplication_intersects_the_socle_map_space_weakly:
  If

    L intersect T=0,

  then

    dim_C(P intersect im(mu))<=1.

  If

    L intersect T=T_3,

  then

    P intersect im(mu)=0.

Proof:
  First assume L intersect T=0.  Then

    S_X=T_3

  lies entirely in degree three and is one-dimensional.

  Suppose a multiplication map mu(x) lies in P.  Its value on ell*b must lie
  in degree three.  Since ell*b has degree three, a degree-three product could
  only come from X_0.  But

    X_0=J_0=0,

  because J is a proper homogeneous ideal.  Every positive-degree component of
  x would produce degree at least four, whereas a map in P has image contained
  in the degree-three line T_3.  Hence

    ell*b*x=0.

  Therefore every map in P intersect im(mu) lies in the one-dimensional line
  of maps

    a |-> T_3,
    ell*b |-> 0,

  proving the first bound.

  Now assume L intersect T=T_3.  Then S_X is the degree-two space

    T_2 mod T_3

  of dimension two.  A product by the quadratic a can land in degree two only
  from X_0, which is zero.  Multiplication by the cubic ell*b cannot produce a
  degree-two output from any nonnegative degree.  Thus every multiplication map
  lying in P is zero.
Qed.

Corollary square_zero_socle_maps_improve_the_deficit_bound:
  If L intersect T=0, then

    eta_1<=dim_C A_1-1.

  If L intersect T=T_3, then

    eta_1<=dim_C A_1-4.

Proof:
  The Hom space contains im(mu)+P.  Therefore

    dim Hom_C(K_1,X)
      >=dim im(mu)+dim P-dim(P intersect im(mu)).

  In the first case dim P=2 and the intersection has dimension at most one, so

    eta_1
      =dim X-dim Hom_C(K_1,X)
      <=dim A_1-1.

  In the second case dim P=4 and the intersection is zero, giving

    eta_1<=dim A_1-4.
Qed.

Theorem square_zero_cubic_section_bounds_the_first_annihilator_by_sixteen:
  One has

    dim_C A_1<=16.

Proof:
  The cubic q from the preceding quadratic-predecessor reduction belongs to
  K_1, so

    A_1=0:_X K_1 subseteq 0:_X q.

  On the finite-dimensional vector space X, kernel and cokernel of
  multiplication by q have equal dimension.  Hence

    dim_C(0:_X q)=length_C(X/qX).

  Since X=J/L, the quotient X/qX is a quotient of J/qJ.  In ZERO_SELF_ACTION
  the preceding exact section computation gives

    length_C(J/qJ)=16.

  Therefore dim_C A_1<=16.
Qed.

Corollary square_zero_first_layer_misses_the_tangent_gate:
  For every square-zero candidate with k>=1,

    eta_1<=15.

  More precisely,

    L intersect T=0   => eta_1<=15,
    L intersect T=T_3 => eta_1<=12.

Proof:
  Combine the improved socle-map bounds with dim A_1<=16.
Qed.

Theorem every_square_zero_degree_gap_is_closed:
  For every k>=0,

    eta_k<16.

Proof:
  If k=0, the quadratic-baseline theorem from the preceding reduction gives

    eta_0<=12.

  If k>=1, telescope

    eta_k=eta_1+sum_(i=2)^k Delta_i.

  Every later Delta_i is nonpositive, while the preceding theorem gives

    eta_1<=15.

  Hence eta_k<=15.
Qed.

Corollary zero_self_action_case_is_closed:
  No ZERO_SELF_ACTION candidate satisfies the necessary order-13 tangent gate.

Proof:
  The tangent gate forces eta_k>=16, while the preceding theorem gives

    eta_k<16.
Qed.

END SQUARE_ZERO_SOCLE_MAP.

Corollary e4_h121_height3_subbranch_closed:
  No homogeneous q=4, ht(Q)=3, e(B)=4 candidate with saturated-core h-vector

    (1,2,1)

  satisfies the necessary order-13 tangent-dimension gate.

Proof:
  The preceding quadratic-predecessor/self-action reduction closes the
  REGULAR_QUADRATIC_LOWER case and the NONZERO_SELF_ACTION part of the
  zerodivisor-lower case.

  The only remaining ZERO_SELF_ACTION part is closed by the socle-map theorem
  above.  Therefore no case remains in this h-vector row.
Qed.

Interpretation:
  The equality eta_1=16 isolated previously is impossible because the
  square-zero torsion itself forces additional Hom directions.

  If the full torsion survives in X, its one-dimensional top socle gives two
  independent generator-value maps K_1->X, at most one of which can come from
  multiplication.  This lowers the maximal deficit from sixteen to fifteen.

  If the final-cut ideal removes T_3, the quotient torsion has a
  two-dimensional degree-two socle.  The resulting four generator-value maps
  are all disjoint from multiplication and lower the maximal deficit to
  twelve.

  Thus the square-zero branch cannot reach the required deficit sixteen, and
  the full e=4, h=(1,2,1) height-three subbranch is closed.

IMPORTANT_NONCONCLUSION:
  This closes only

    q=4,
    ht(Q)=3,
    e(B)=4,
    h=(1,2,1).

  It does NOT close the other surviving e=3 or e=4 h-vectors, q=4 height two,
  homogeneous q<=3, the unrestricted nonhomogeneous local deviation-two
  frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

NEXT_BOUNDED_OBJECT:
  Return to the exact e=3,4,5 saturation table and select the next still-open
  q=4, ht(Q)=3 h-vector in repository order.  Recompute only its smallest
  torsion-annihilator or predecessor carrier; do not import this socle count
  without reproving the corresponding torsion module.