Standalone exclusion of the two-linear residual-cut types R3 and R4U for the
low-embedding-dimension H01-C5 m=3 E0/E1 branch in the homogeneous q=4,
height-two multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_E01_residual_multiplicity_five_exclusion.v

  and retain

    S = C[x1,x2,x3,x4],
    Q subset Qsat,
    B = S/Q,
    T = Qsat/Q,
    P = (l1,l2),
    D = P/Qsat,
    J_res = Ann_S(D) = (Qsat:P),
    R_res = S/J_res,

  in H01-C5 with

    m = 3,
    sigma = 5,
    tau_3 = dim_C T_3 = 1.

The H01 hypotheses also give

    (Qsat)_1 = 0,
    Q_2 = (Qsat)_2 =: W,
    dim_C W = 4,

and the multiplicity-one state gives

    e(S/Q) = e(S/Qsat) = 1.

The preceding residual-multiplicity file classifies the regular Artinian cut of
R_res into exactly three types:

  R3:
    Jbar = (v,w,u^3),

  R4U:
    Jbar = (v,w,u^4),

  R4S:
    Jbar = (w,u^3,u*v,v^2),

where h is R_res-regular and

    Jbar = (J_res+(h))/(h).

This file performs one bounded task only: prove that R3 and R4U are impossible.
The proof uses only the two-dimensional linear annihilator they force, the exact
quadratic equality Q_2=(Qsat)_2, the nonzero cubic saturation defect, and the
multiplicity-one hypothesis.

No R4S tangent estimate is made here.
No E2, H01-C4, q<=3, or full order-13 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. R3 AND R4U FORCE TWO LINEAR RESIDUAL ANNIHILATORS
--------------------------------------------------------------------------

In both R3 and R4U,

    dim_C (Jbar)_1 = 2.

The established regularity of h gives

    (J_res:h)=J_res

and

    J_res intersect (h) = h*J_res.

Because J_res is a proper homogeneous ideal,

    (J_res)_0 = 0.

Hence in degree one the quotient map

    (J_res)_1 -> (Jbar)_1

has zero kernel and is surjective.  Therefore

    dim_C (J_res)_1 = 2.

Put

    Z := (J_res)_1 subset S_1.

Thus, in either R3 or R4U,

    dim_C Z = 2.

Theorem H01_C5_m3_E01_R3_R4U_linear_annihilator_plane:
  In residual type R3 or R4U, the linear part Z=(J_res)_1 is a two-dimensional
  subspace of S_1.
Qed.

--------------------------------------------------------------------------
2. THE LINEAR ANNIHILATOR MULTIPLIES P INTO THE FOUR QUADRICS
--------------------------------------------------------------------------

By definition

    J_res = (Qsat:P).

Therefore

    Z*P subset Qsat.

Taking degree two gives

    Z*P_1 subset (Qsat)_2.

But H01 has no saturation defect in degree two:

    (Qsat)_2 = Q_2 = W,
    dim_C W = 4.

Hence

    P_1*Z subset W.

Theorem H01_C5_m3_E01_two_linear_annihilator_quadratic_shadow:
  If dim_C Z=2, then

    P_1*Z subset Q_2.
Qed.

We now split according to whether Z=P_1.

--------------------------------------------------------------------------
3. DISTINCT TWO-PLANES FORCE Q TO BE THE PRODUCT IDEAL P*Z
--------------------------------------------------------------------------

Assume

    Z != P_1.

Both P_1 and Z have dimension two.

There are two possible intersection dimensions.

CASE A: P_1 intersect Z = 0.

  Choose linear coordinates

    P_1 = span(x,y),
    Z   = span(z,w).

  Then

    P_1*Z = span(x*z,x*w,y*z,y*w),

  which has dimension four.

CASE B: dim_C(P_1 intersect Z)=1.

  Choose coordinates

    P_1 = span(x,y),
    Z   = span(x,z).

  Then

    P_1*Z = span(x^2,x*z,x*y,y*z),

  again of dimension four.

Thus whenever Z!=P_1,

    dim_C(P_1*Z)=4.

Since

    P_1*Z subset W

and dim_C W=4, one obtains

    W=P_1*Z.

The ideal Q is generated by exactly its four quadratic generators W.  Therefore

    Q=P*Z.

Theorem H01_C5_m3_E01_distinct_annihilator_planes_force_product:
  If Z!=P_1, then

    Q=P*Z.
Qed.

--------------------------------------------------------------------------
4. THE PRODUCT OF TWO DISTINCT LINEAR HEIGHT-TWO IDEALS IS SATURATED HERE
--------------------------------------------------------------------------

We verify saturation directly in the two coordinate cases above.

CASE A: P_1 intersect Z=0.

  With

    P=(x,y),
    Z=(z,w),

  one has

    P*Z=(x*z,x*w,y*z,y*w)=P intersect Z.

  This is the intersection of two homogeneous prime ideals, hence saturated.

CASE B: dim(P_1 intersect Z)=1.

  With

    P=(x,y),
    Z=(x,z),

  one has

    P*Z=(x^2,x*y,x*z,y*z).

  Let w be the fourth coordinate.  The ideal P*Z is extended from

    C[x,y,z]

  and contains no w.  Consequently multiplication by w is injective on

    S/(P*Z): if w*F lies in P*Z, comparison of powers of w shows F lies in P*Z.

  If a homogeneous class F were in the saturation of P*Z, then for some k

    m^k*F subset P*Z.

  In particular

    w^k*F lies in P*Z.

  Injectivity of multiplication by w^k gives

    F lies in P*Z.

  Hence P*Z is saturated also in this case.

Therefore for every pair of distinct two-dimensional linear subspaces P_1,Z,

    (P*Z)^sat=P*Z.

Corollary H01_C5_m3_E01_distinct_product_has_no_saturation_defect:
  If Z!=P_1, then

    Qsat=Q

  and therefore

    T=0.
Qed.

But H01-C5 has

    dim_C T_3 = tau_3 = 1.

Contradiction.

Thus the distinct-plane case is impossible.

--------------------------------------------------------------------------
5. THE COINCIDENT CASE FORCES GENERIC MULTIPLICITY AT LEAST TWO
--------------------------------------------------------------------------

It remains to assume

    Z=P_1.

Then Section 2 gives

    P_1^2 subset W=Q_2.

Since

    dim_C P_1^2 = 3

and

    dim_C W=4,

there is a quadratic

    q in W minus P_1^2

such that

    W=P_1^2 direct_sum C*q.

Because Q is generated by W,

    Q=(P^2,q).

Also Q subset Qsat subset P, so q belongs to P but not to P^2.

Localize at the height-two linear prime P.  The regular local ring S_P has
maximal ideal

    m_P=P*S_P

with two-dimensional cotangent space

    m_P/m_P^2.

The class of q is nonzero in this cotangent space because q notin P^2.
After a linear change of the two local parameters, the quotient by

    (m_P^2,q)

has residue-field basis

    1, y

for one surviving first-order parameter y.  Therefore

    length_(S_P) (S_P/Q_P)=2.

Since ht(Q)=2 and P is a height-two prime containing Q, P is a minimal prime of
Q.  The associativity formula for multiplicity therefore gives

    e(S/Q)
      >= length_(S_P)(S_P/Q_P) * e(S/P)
      = 2*1
      = 2.

But the multiplicity-one H01 branch has

    e(S/Q)=1.

Contradiction.

Theorem H01_C5_m3_E01_coincident_annihilator_plane_multiplicity_contradiction:
  The case Z=P_1 is impossible.
Qed.

--------------------------------------------------------------------------
6. R3 AND R4U ARE EMPTY
--------------------------------------------------------------------------

The two possibilities

    Z!=P_1

and

    Z=P_1

are both impossible.

Hence no H01-C5 m=3 E0/E1 state can have

    dim_C (J_res)_1=2.

Theorem q4_H01_C5_m3_E01_two_linear_residual_annihilator_excluded:
  One has

    dim_C (J_res)_1 != 2.
Qed.

Since R3 and R4U are exactly the two residual-cut types with two independent
linear generators, both are empty.

Corollary q4_H01_C5_m3_E01_R3_excluded:
  Residual type R3 does not occur.
Qed.

Corollary q4_H01_C5_m3_E01_R4U_excluded:
  Residual type R4U does not occur.
Qed.

--------------------------------------------------------------------------
7. ONLY THE R4S RESIDUAL CUT TYPE SURVIVES
--------------------------------------------------------------------------

The preceding residual classification was exhaustive:

    R3, R4U, R4S.

After Sections 1--6 only R4S remains.

Thus every surviving H01-C5 m=3 E0/E1 state satisfies, after the established
regular linear cut,

    Jbar=(w,u^3,u*v,v^2),

    e(R_res)=4,

    dim_C (J_res)_1=1,

    mu_S(J_res)=4,

and the current image-generator bound remains

    r_res<=4.

Theorem q4_H01_C5_m3_E01_residual_type_forced_R4S:
  Every surviving H01-C5 m=3 E0/E1 residual ring is of type R4S.
Qed.

The tangent estimates from the preceding file therefore reduce to the single
state

    L_res<=4*M,
    r_res<=4,

with tangent excess lower bound

    t(A)-(N-20)
      >= M*(s-8)+4*s-15,

where

    M=max(d,e),
    s=min(d,e).

No stronger numerical estimate is asserted in this file.

--------------------------------------------------------------------------
8. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_two_linear_residual_annihilator_excluded.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_R3_excluded.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_R4U_excluded.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_residual_type_forced_R4S.

CURRENT_E01_RESIDUAL_TYPE:
  R4S only:

    Jbar=(w,u^3,u*v,v^2),
    e(R_res)=4,
    dim_C(J_res)_1=1,
    mu_S(J_res)=4,
    r_res<=4.

CURRENT_UNIFORM_CLOSURE:
  min(d,e)>=8 is excluded.
  min(d,e)=7 with max(d,e)<=12 is excluded.

SURVIVING_DEGREE_FRONTIER_FROM_CURRENT_TANGENT_ESTIMATE:
  3<=min(d,e)<=6,

  or

  min(d,e)=7 and max(d,e)>=13.

IMPORTANT_NONCONCLUSION:
  This file does NOT close the R4S type.
  It does NOT improve L_res<=4*M inside R4S.
  It does NOT prove r_res<4 after the final Artin cut.
  It does NOT prove that any surviving degree pair is realizable.
  It does NOT close all H01-C5 m=3 E0/E1.
  It does NOT treat E2.
  It does NOT enter H01-C4.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_saturation_cyclic.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_colon_classified.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_torsion_Koszul_reduced.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_product_annihilator_reduced.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_residual_type_forced_R4S.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_min_final_degree_ge8_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_all_degrees_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3 E0/E1 and the forced R4S residual type.  Lift the
  exact regular-cut ideal

    (w,u^3,u*v,v^2)

  through the one-dimensional Cohen--Macaulay ring R_res.  Use its generator
  degrees (1,2,2,3) and Hilbert--Burch structure to determine the exact
  one-dimensional residual presentation.  Then test whether the final equations
  f,g force either

    L_res < 4*M

  or

    r_res < 4

  on the surviving degree frontier.

NEXT_ACTIONS:
  1. Stay only in H01-C5 m=3 E0/E1 R4S.
  2. Derive the Hilbert--Burch matrix of J_res modulo its unique linear generator.
  3. Normalize its reduction modulo h to the matrix for (u^3,u*v,v^2).
  4. Extract the first forced relation between the lifted quadratic generators and the cubic generator.
  5. Stop before E2, H01-C4, q<=3, or any full order-13 claim.
