Standalone Koszul normal-form reduction of the R2-LK3 carrier in the saturated
H01 minimal-chain rank-two endpoint of the homogeneous q=4, height-two,
multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_R2_mod_r_kernel_degree_reduction.v

  and retain

    S := C[x1,x2,x3,x4],
    Q=(q1,q2,q3,q4)=Qsat,
    ht(Q)=2,
    Q minimally generated by four independent quadrics,
    P=(l1,l2),
    Q subset P,

with exact minimal resolution

    0
      -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^4
      -> S
      -> B:=S/Q
      -> 0.

Write the second differential as

    A=[L1 L2 L3 Q4],
    L=[L1 L2 L3],

and the final differential as

    d3=(a1,a2,a3,r)^T,

where ai are quadratic and r is a nonzero linear form.  The preceding
determinantal factorization gives, after scalar normalization,

    Delta_i(L)=r*q_i

for the signed 3-by-3 maximal minors, hence

    I3(L)=(r)*Q.

Put

    Sbar:=S/(r),
    M:=L mod r.

Stay only in the R2-LK3 carrier.  Thus the primitive right-kernel vector of M
is linear and its three components span a three-dimensional C-vector space.
After a constant column basis change and a linear coordinate change on Sbar,
normalize that vector to

    y=(y1,y2,y3)^T,

so

    M*y=0,
    Sbar=C[y1,y2,y3].

This file performs one bounded task only: classify the resulting linear
Koszul matrix modulo r and split it by the constant coefficient rank.  It does
not exclude R2-LK3 and makes no tangent estimate.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE LINEAR SYZYGY SPACE OF (y1,y2,y3)
--------------------------------------------------------------------------

Use the standard skew Koszul matrix

        [  0  -y3   y2 ]
    K = [ y3    0  -y1 ]
        [-y2   y1    0 ].

Then

    K*y=0.

A row vector

    u=(u1,u2,u3)

of linear forms satisfies

    u*y=0

if and only if u is a constant C-linear combination of the three rows of K.
Indeed, the degree-two relation

    u1*y1+u2*y2+u3*y3=0

is precisely a degree-one first syzygy of the regular sequence y1,y2,y3, and
the degree-one syzygy space is generated over C by the three Koszul syzygies.

Therefore there is a constant matrix

    C0 in Mat_(4x3)(C)

such that

    M=C0*K.

Theorem H01_m2_R2_LK3_koszul_factorization:
  After the stated LK3 normalization,

    M=C0*K

  for a constant 4-by-3 matrix C0.
Qed.

--------------------------------------------------------------------------
2. THE COEFFICIENT RANK CANNOT BE ONE
--------------------------------------------------------------------------

Put

    rho:=rank_C(C0).

Because the primitive kernel components span all three variables, M is nonzero,
so rho>=1.  Also rho<=3.

Assume rho=1.  A constant invertible row change on the four generators of Q
puts M into the form

    M = [ s ]
        [ 0 ]
        [ 0 ]
        [ 0 ]

for one nonzero linear Koszul syzygy row s.

Since L has linear entries and reduces to M modulo r, the corresponding lift has
rows

    s+r*v1,
    r*v2,
    r*v3,
    r*v4

with constant rows vi in C^3.

Every 3-by-3 maximal minor of L is then divisible by r^2: the minor omitting the
first row is in fact divisible by r^3, while each other maximal minor contains
two rows divisible by r.

Using

    Delta_i(L)=r*q_i,

one gets

    r | q_i

for every i.  Hence

    Q subset (r),

so

    ht(Q)<=1,

contrary to the standing height-two hypothesis.

Theorem H01_m2_R2_LK3_coefficient_rank_one_impossible:
  In R2-LK3 one has

    rho in {2,3}.
Qed.

--------------------------------------------------------------------------
3. COEFFICIENT RANK TWO FORCES TWO r-MULTIPLE QUADRICS
--------------------------------------------------------------------------

Assume rho=2.  After a constant invertible row change, write

    M = [ s1 ]
        [ s2 ]
        [  0 ]
        [  0 ]

with s1,s2 independent linear Koszul syzygies.

Lift to

    L = [ s1+r*v1 ]
        [ s2+r*v2 ]
        [    r*v3 ]
        [    r*v4 ]

for constant rows vi.

The maximal minor omitting row 1 contains rows 2,3,4 and hence two explicit
r-divisible rows.  Therefore

    r^2 | Delta_1(L).

Likewise

    r^2 | Delta_2(L).

Since Delta_i(L)=r*q_i,

    r | q1,
    r | q2.

The four q_i are nonzero and C-linearly independent, so q1 and q2 are distinct
nonzero members of r*S_1.  Thus, after the same harmless generator basis change,

    dim_C(Q intersect r*S_1) >= 2.

Theorem H01_m2_R2_LK3_rank_two_has_two_r_multiples:
  The coefficient-rank-two LK3 carrier forces a two-dimensional subspace of Q
  consisting of quadrics divisible by r.
Qed.

This is a reduction, not an exclusion.

--------------------------------------------------------------------------
4. COEFFICIENT RANK THREE HAS THE STANDARD KOSZUL LIFT
--------------------------------------------------------------------------

Assume rho=3.  Since the three rows of K form a C-basis of the degree-one
Koszul syzygy space, a constant invertible row change puts

    M = [ K ]
        [ 0 ],

where the first three rows form K and the fourth row is zero.

Hence the full linear lift has the form

    L = [ K + r*V ]
        [   r*v^T ],

with

    V in Mat_(3x3)(C),
    v in C^3.

One has v!=0.  If v=0, then the fourth row of L is identically zero, so the
three maximal minors involving that row vanish identically.  Equivalently at
least three of q1,q2,q3,q4 would be zero, contradicting minimal generation by
four independent quadrics.

Put

    h:=v1*y1+v2*y2+v3*y3.

Because v!=0 and y1,y2,y3 are independent,

    h!=0.

Theorem H01_m2_R2_LK3_rank_three_lift:
  In coefficient rank three one may normalize

    L = [ K+rV ]
        [ r*v^T ]

  with v!=0.
Qed.

--------------------------------------------------------------------------
5. THREE QUADRICS ACQUIRE THE COMMON LINEAR FACTOR h MODULO r
--------------------------------------------------------------------------

The adjugate of the skew Koszul matrix is

    adj(K)=y*y^T.

Equivalently, the signed 2-by-2 cofactors of K are the pairwise products y_i*y_j.

For i=1,2,3, the maximal minor Delta_i(L) is obtained by deleting one of the
first three rows.  It contains the last row r*v^T.  After dividing by r and
reducing modulo r, its value is the corresponding cofactor contraction of K
with v.  With compatible harmless signs on the generators q1,q2,q3, this gives

    q1 mod r = h*y1,
    q2 mod r = h*y2,
    q3 mod r = h*y3.

For the fourth maximal minor,

    Delta_4(L)=det(K+rV).

Since det(K)=0, the coefficient of r is

    trace(adj(K)*V)
      = trace(y*y^T*V)
      = y^T*V*y.

Thus, after dividing by r and reducing modulo r,

    q4 mod r = phi,

where

    phi:=y^T*V*y

is a quadratic form in Sbar_2.

Theorem H01_m2_R2_LK3_rank_three_quadric_shadow:
  In coefficient rank three, after compatible generator signs,

    Q mod r

  is generated by the four quadratic shadows

    h*y1,
    h*y2,
    h*y3,
    phi,

  with h!=0 and phi=y^T*V*y.
Qed.

--------------------------------------------------------------------------
6. THE COMMON FACTOR h LIES IN THE IMAGE OF THE PLANE PRIME P
--------------------------------------------------------------------------

Recall the standing multiplicity-one residual inclusion

    Q subset P=(l1,l2).

Let

    Pbar:=(P+(r))/(r) subset Sbar.

Because P is a linear prime of height two, Pbar is a proper homogeneous prime:
it has height one if r lies in P and height two otherwise.

The first three rank-three shadows satisfy

    h*yi in Pbar

for i=1,2,3.

If h were not in Pbar, primality would imply

    y1,y2,y3 in Pbar.

That would force the entire irrelevant ideal (y1,y2,y3) into Pbar, impossible
because Pbar is a proper linear prime of height at most two.

Therefore

    h in Pbar.

Corollary H01_m2_R2_LK3_common_factor_is_plane_direction:
  In coefficient rank three, the common linear factor h of the first three
  quadratic shadows is the image modulo r of a nonzero linear direction from
  P+(r).
Qed.

In particular:

  * if r lies in P, then Pbar is principal and generated by h, so phi is also
    divisible by h;

  * if r does not lie in P, then after a linear basis choice

        Pbar=(h,p)

    for some linear form p independent of h, and

        phi in (h,p)_2.

Again this is only a structural reduction.

--------------------------------------------------------------------------
7. EXACT LK3 TWO-CARRIER REDUCTION
--------------------------------------------------------------------------

The coefficient-rank-one case is empty.  Hence every R2-LK3 endpoint lies in
exactly one of the following two internal carriers.

LK3-C2:
  rho=2, and after a generator basis change

    dim_C(Q intersect r*S_1) >= 2.

LK3-C3:
  rho=3, and after normalization

    L = [K+rV; r*v^T],
    h=v dot y != 0,

  with quadratic shadow

    (q1,q2,q3,q4) mod r
      = (h*y1,h*y2,h*y3,phi),

  where

    phi=y^T*V*y,
    h in Pbar.

Theorem H01_m2_R2_LK3_two_carrier_reduction:
  R2-LK3 reduces to

    LK3-C2 or LK3-C3.
Qed.

--------------------------------------------------------------------------
8. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_koszul_factorization.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_coefficient_rank_one_empty.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_rank_two_two_r_multiples.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_rank_three_koszul_lift.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_rank_three_quadric_shadow.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_common_factor_in_plane_image.

EXACT_REDUCTION:

    R2-LK3
      -> LK3-C2 or LK3-C3.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude LK3-C2.
  It does NOT exclude LK3-C3.
  It does NOT exclude R2-LK3.
  It does NOT exclude R2-LK2 or R2-QK.
  It does NOT close H01-M2-R2.
  It does NOT treat H01-M2-R1.
  It does NOT make a tangent-space estimate.
  It does NOT close H01.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_R2_exact_Betti_table.
  H01_m2_R2_determinantal_factorization.
  H01_m2_R2_constant_kernel_empty.
  H01_m2_R2_LK3_coefficient_rank_one_empty.
  not H01_m2_R2_LK3_closed.
  not H01_m2_R2_closed.
  not H01_m2_R1_closed.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in H01-M2-R2 and attack LK3-C2 first.  Use the two-dimensional
  subspace

    Q intersect r*S_1

  together with Q subset P and Q=Qsat.  Split whether r lies in P.  If r is not
  in P, primality of P forces the two independent linear cofactors into P_1,
  hence the full product plane r*P_1 lies in Q_2.  Determine whether saturation
  then forces an already-classified residual carrier or contradicts the H01-M2
  Hilbert profile.  Treat r in P only if that branch survives.

NEXT_ACTIONS:
  1. Classify LK3-C2 using Q intersect r*S_1 and the plane prime P.
