Standalone graded-Betti reduction of the saturated H01 minimal-chain rank-two endpoint
in the homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_artinian_action_betti_reduction.v

  and retain the H01-M2-R2 branch

    S := C[x1,x2,x3,x4],
    P := (l1,l2),
    Q = Qsat subset P,
    B := S/Q,
    D := P/Q,

with

    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    depth_m(B)=1,
    e(B)=1,
    sigma=3,
    tau_3=0,
    Hilb_D(t)=(2*t+t^2)/(1-t),

and the exact minimal S-resolution of D

    0
      -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^5
      -> S(-1)^2
      -> D
      -> 0.

This file performs one bounded task only: determine the exact minimal graded
free resolution of B from the R2 residual resolution and the exact sequence

    0 -> D -> B -> S/P -> 0.

No coefficient-matrix classification, tangent estimate, H01-M2-R1 argument,
q<=3 argument, or Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXACT HILBERT SERIES OF B
--------------------------------------------------------------------------

Because Q=Qsat and D=P/Q, there is an exact sequence

    0 -> D -> B -> S/P -> 0.

Since

    Hilb_(S/P)(t)=1/(1-t)^2

and

    Hilb_D(t)=(2*t+t^2)/(1-t),

one gets

    Hilb_B(t)
      = 1/(1-t)^2 + (2*t+t^2)/(1-t)
      = (1+2*t-t^2-t^3)/(1-t)^2.

Hence

    dim_C B_0=1,
    dim_C B_1=4,
    dim_C B_2=6,
    dim_C B_3=7,

and for every n>=2,

    dim_C B_n=n+4.

Multiplying by (1-t)^4 gives the exact ambient Hilbert numerator

    (1-t)^4 Hilb_B(t)
      = 1-4*t^2+3*t^3+t^4-t^5.

The coefficient 3 in degree three agrees with the standing value sigma=3.

--------------------------------------------------------------------------
2. THIRD EXT OF B IS IDENTICAL TO THIRD EXT OF D
--------------------------------------------------------------------------

The line ring S/P has projective dimension two over S. Therefore

    Ext^i_S(S/P,S(-4))=0

for every i>=3.

Apply Hom_S(-,S(-4)) to

    0 -> D -> B -> S/P -> 0.

The long exact Ext sequence gives a graded isomorphism

    Ext^3_S(B,S(-4)) ~= Ext^3_S(D,S(-4)).

Theorem H01_m2_R2_ext3_transfer:
  The natural map induced by D -> B gives

    Ext^3_S(B,S(-4)) ~= Ext^3_S(D,S(-4)).
Qed.

This is the key rigidity input: the last syzygy module of B must encode the
same minimal generator structure as the already-known R2 canonical module of D.

--------------------------------------------------------------------------
3. THIRD EXT OF D IS CYCLIC WITH GENERATOR DEGREE -1
--------------------------------------------------------------------------

Dualize the exact R2 resolution of D by S(-4).

The final dual target is

    Hom_S(S(-5),S(-4)) = S(1).

The preceding dual source is

    Hom_S(S(-3)^3 direct_sum S(-4),S(-4))
      = S(-1)^3 direct_sum S.

All entries in the original minimal differential lie in the homogeneous maximal
ideal, so the image in S(1) contains no degree-zero unit. Therefore the cokernel

    Ext^3_S(D,S(-4))

is minimally generated by the single class of the generator of S(1), in graded
degree -1.

Equivalently, for suitable homogeneous forms

    r in S_1,
    q1,q2,q3 in S_2,

one may write

    Ext^3_S(D,S(-4)) ~= S/(r,q1,q2,q3)(1).

Theorem H01_m2_R2_ext3_is_cyclic:
  Ext^3_S(D,S(-4)) has exactly one minimal generator, in degree -1.
Qed.

By Section 2 the same is true for Ext^3_S(B,S(-4)).

--------------------------------------------------------------------------
4. CYCLIC THIRD EXT FORCES ONE LAST SYZYGY OF B
--------------------------------------------------------------------------

Since depth_m(B)=1 and S has depth four, Auslander--Buchsbaum gives

    pd_S(B)=3.

Thus a minimal resolution of B has the form

    0 -> F3 -> F2 -> S(-2)^4 -> S -> B -> 0.

After dualizing by S(-4), the module Ext^3_S(B,S(-4)) is the cokernel of

    Hom_S(F2,S(-4)) -> Hom_S(F3,S(-4)).

Because the resolution is minimal, every entry of this dual presentation lies
in the homogeneous maximal ideal. Therefore the minimal generators of Ext^3
are exactly the dual basis generators contributed by the summands of F3.

Section 3 says Ext^3_S(B,S(-4)) has exactly one minimal generator, and that its
degree is -1. Consequently

    F3 = S(-5).

Theorem H01_m2_R2_last_syzygy_is_unique:
  The minimal resolution of B has exactly one third-syzygy summand, namely

    beta_{3,5}(B)=1,

  and beta_{3,j}(B)=0 for j!=5.
Qed.

In particular all possible quartic or higher ghost-pair alternatives are
eliminated without a tangent estimate.

--------------------------------------------------------------------------
5. THE HILBERT NUMERATOR NOW DETERMINES F2 EXACTLY
--------------------------------------------------------------------------

The Hilbert numerator of a minimal resolution is

    1 - 4*t^2 + sum_j beta_{2,j}*t^j - sum_j beta_{3,j}*t^j.

Section 4 gives

    sum_j beta_{3,j}*t^j = t^5.

Comparing with

    1-4*t^2+3*t^3+t^4-t^5

forces

    beta_{2,3}=3,
    beta_{2,4}=1,
    beta_{2,j}=0 for j!=3,4.

Therefore the exact minimal resolution is

    0
      -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^4
      -> S
      -> B
      -> 0.

Theorem H01_m2_R2_exact_Betti_table:
  Every H01-M2-R2 endpoint has the unique graded Betti table

    beta_{1,2}=4,
    beta_{2,3}=3,
    beta_{2,4}=1,
    beta_{3,5}=1,

  with all other graded Betti numbers equal to zero.
Qed.

--------------------------------------------------------------------------
6. COEFFICIENT-MATRIX FORM FOR THE NEXT STEP
--------------------------------------------------------------------------

Choose bases so that the second differential is written as a 4-by-4 matrix

    A = [ L1  L2  L3  Q4 ],

where

    L1,L2,L3

are columns of linear forms and

    Q4

is a column of quadratic forms.

The final differential is a single column

    d3 = (a1,a2,a3,r)^T

with

    a1,a2,a3 in S_2,
    r in S_1.

Exactness gives

    A*d3=0.

Moreover r is nonzero. Indeed, the presentation

    Ext^3_S(B,S(-4)) ~= S/(r,a1,a2,a3)(1)

must have degree-zero dimension three, because the exact R2 residual module has

    dim_C H^1_m(D)_0=3

and Section 2 identifies the corresponding third Ext modules. If r=0, the
degree-zero piece would have dimension four. Hence

    r != 0.

Thus the unique quartic first syzygy is coupled to the three linear first
syzygies by a nonzero final linear coefficient.

This is the first exact coefficient-matrix normal form for H01-M2-R2.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_ext3_transfer.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_ext3_cyclic.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_unique_last_syzygy.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_exact_Betti_table.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_nonzero_final_linear_entry.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-M2-R2.
  It does NOT classify the 4-by-4 mixed linear/quadratic matrix A up to changes
  of basis.
  It does NOT prove a tangent carrier or tangent-space estimate.
  It does NOT treat H01-M2-R1.
  It does NOT close H01.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_R2_exact_Betti_table.
  not H01_m2_R2_closed.
  not H01_m2_R1_closed.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in H01-M2-R2 and use

    0 -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^4
      -> S -> B -> 0

  together with the mixed syzygy matrix

    A=[L1 L2 L3 Q4]

  and final relation

    A*(a1,a2,a3,r)^T=0,
    r!=0,

  to determine whether the three linear columns force a height-one factor,
  a multiplicity-two product component, or a direct tangent carrier.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow run for this commit.
