Standalone exact saturation-defect table for the remaining multiplicities
three, four, and five in the homogeneous q=4, height-three order-13
low-multiplicity endpoint.

SCOPE:
  Continue from

    order13_homogeneous_four_quadric_height_split.v
    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_e2_exact_saturation_linkage_profile.v
    order13_q4_height3_e2_zerodivisor_lower_closed.v

  Work with

    S := C[x1,x2,x3,x4],
    Q subset S minimally generated by four independent quadrics,
    ht(Q)=3,
    B:=S/Q,
    T:=H^0_m(B),
    Cbar:=B/T,

  and assume

    e(B) in {3,4,5}.

  The saturated-core profile proves that Cbar is one-dimensional
  Cohen--Macaulay and, for a general linear nonzerodivisor ell,

    Cbar/ell*Cbar

  has one of the following eight h-vectors:

    e=3:
      (1,2),
      (1,1,1),

    e=4:
      (1,3),
      (1,2,1),
      (1,1,1,1),

    e=5:
      (1,3,1),
      (1,2,2),
      (1,2,1,1).

  Earlier files used only upper bounds on length(T).  This file computes the
  Hilbert series of T exactly from the canonical module of Cbar.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

Retain the three-quadric complete-intersection section model

  R:=S/(q1,q2,q3),
  a:=image of the fourth quadric,
  J:=a*R,
  B=R/J,
  U:=saturation(J),
  Cbar=R/U,
  T=U/J.

Then R is one-dimensional graded Gorenstein with

  Hilb_R(t)=(1+t)^3/(1-t),
  omega_R ~= R(2).

Put

  K:=0:_R a.

Theorem saturated_hull_is_double_annihilator_without_e2_restriction:
  One has

    U=0:_R K.

Proof:
  The proof used in the multiplicity-two linkage file does not use e=2.

  Since a*K=0,

    J=aR subseteq 0:_R K.

  Away from the irrelevant maximal ideal, R is zero-dimensional Gorenstein.
  There the annihilator involution gives

    0:(0:(a))=(a),

  so

    (0:_R K)_p=J_p

  at every nonirrelevant homogeneous prime p.  Hence

    (0:_R K)/J

  has finite length and 0:_R K is contained in U.

  Conversely, if x belongs to U, some power of the irrelevant ideal sends x
  into J.  Choose a linear nonzerodivisor ell on the one-dimensional
  Cohen--Macaulay ring R.  For every k in K,

    ell^n*x*k belongs to J*K=0

  for n sufficiently large.  Since ell is R-regular,

    x*k=0.

  Thus x belongs to 0:_R K, proving equality.
Qed.

Theorem residual_annihilator_is_K_without_e2_restriction:
  One has

    0:_R U=K.

Proof:
  Again the multiplicity-two proof is multiplicity-independent.

  The inclusion K subseteq 0:_R U follows from U=0:_R K.

  Conversely, if x annihilates U, then away from the irrelevant maximal ideal
  zero-dimensional Gorenstein duality places x in K.  Thus x modulo K has
  finite length.  For a linear R-regular ell and sufficiently large n,

    ell^n*x belongs to K.

  Multiplication by a gives

    ell^n*a*x=0.

  Regularity of ell implies a*x=0, hence x belongs to K.
Qed.

Theorem residual_module_is_shifted_canonical_module:
  There is a graded isomorphism

    K(2) ~= omega_Cbar.

Proof:
  Since Cbar=R/U is one-dimensional Cohen--Macaulay of the same dimension as
  R,

    omega_Cbar
      ~= Hom_R(Cbar,omega_R)
      ~= Hom_R(R/U,R(2))
      ~= (0:_R U)(2).

  The preceding theorem identifies 0:_R U with K.
Qed.

Corollary Hilbert_series_of_K_from_the_core_canonical_module:
  One has

    Hilb_K(t)=t^2*Hilb_omega_Cbar(t).
Qed.

Theorem Hilbert_series_of_B_from_the_core_canonical_module:
  One has

    Hilb_B(t)
      =(1+t)^4+t^4*Hilb_omega_Cbar(t).

Proof:
  Multiplication by the quadratic a gives

    0 -> K(-2)
      -> R(-2)
      --a--> R
      -> B
      -> 0.

  Therefore

    Hilb_B
      =(1-t^2)*Hilb_R+t^2*Hilb_K.

  Since

    (1-t^2)*Hilb_R=(1+t)^4

  and

    Hilb_K=t^2*Hilb_omega_Cbar,

  the displayed formula follows.
Qed.

ExternalResult GradedCanonicalModuleHilbertSeriesDimensionOne:
  If C is a standard graded one-dimensional Cohen--Macaulay C-algebra with

    Hilb_C(t)=h(t)/(1-t),

  then

    Hilb_omega_C(t)
      =-Hilb_C(t^(-1))
      =t*h(t^(-1))/(1-t).

  This is graded local duality / canonical-module Hilbert-series reciprocity.

Theorem exact_torsion_formula_from_h_vector:
  If

    Hilb_Cbar(t)=h(t)/(1-t),

  then

    Hilb_T(t)
      =(1+t)^4
       + t^5*h(t^(-1))/(1-t)
       - h(t)/(1-t).

Proof:
  From

    0 -> T -> B -> Cbar -> 0

  one has

    Hilb_T=Hilb_B-Hilb_Cbar.

  Substitute the preceding formula for Hilb_B and the canonical-module
  reciprocity formula.
Qed.

We now evaluate this identity on each surviving h-vector.

Theorem exact_e3_torsion_table:
  For e=3:

  if h=(1,2), then

    Hilb_T(t)=t+3*t^2+t^3,

    dim T_1=1,
    dim T_2=3,
    dim T_3=1,
    length_C(T)=5;

  if h=(1,1,1), then

    Hilb_T(t)=2*t+3*t^2+2*t^3,

    dim T_1=2,
    dim T_2=3,
    dim T_3=2,
    length_C(T)=7.

Proof:
  Substitute h(t)=1+2*t and h(t)=1+t+t^2 into the exact torsion formula and
  simplify.
Qed.

Theorem exact_e4_torsion_table:
  For e=4:

  if h=(1,3), then

    Hilb_T(t)=2*t^2,

    dim T_1=0,
    dim T_2=2,
    dim T_3=0,
    length_C(T)=2;

  if h=(1,2,1), then

    Hilb_T(t)=t+2*t^2+t^3,

    dim T_1=1,
    dim T_2=2,
    dim T_3=1,
    length_C(T)=4;

  if h=(1,1,1,1), then

    Hilb_T(t)=2*t+4*t^2+2*t^3,

    dim T_1=2,
    dim T_2=4,
    dim T_3=2,
    length_C(T)=8.

Proof:
  Substitute the three h-polynomials into the exact torsion formula.
Qed.

Theorem exact_e5_torsion_table:
  For e=5:

  if h=(1,3,1), then

    Hilb_T(t)=t^2,

    dim T_1=0,
    dim T_2=1,
    dim T_3=0,
    length_C(T)=1;

  if h=(1,2,2), then

    Hilb_T(t)=t+t^2+t^3,

    dim T_1=1,
    dim T_2=1,
    dim T_3=1,
    length_C(T)=3;

  if h=(1,2,1,1), then

    Hilb_T(t)=t+3*t^2+t^3,

    dim T_1=1,
    dim T_2=3,
    dim T_3=1,
    length_C(T)=5.

Proof:
  Substitute the three h-polynomials into the exact torsion formula.
Qed.

Corollary all_remaining_low_multiplicity_torsion_vanishes_from_degree_four_onward:
  For every surviving e in {3,4,5} and every allowed h-vector,

    T_n=0

  for n=0 and for every n>=4.
Qed.

Corollary cubic_power_annihilates_all_remaining_torsion:
  For every surviving e in {3,4,5},

    m^3*T=0.

Proof:
  T begins in positive degree and has no component in degree four or above.
Qed.

Corollary every_final_higher_cut_annihilates_T:
  Every homogeneous element of degree at least three annihilates T.

  In particular, throughout every remaining e=3,4,5 height-three branch,

    f*T=0,
    g*T=0.
Qed.

Corollary exact_remaining_torsion_lengths:
  The old worst-case upper bounds

    e=3: length(T)<=15,
    e=4: length(T)<=13,
    e=5: length(T)<=9

  can be replaced by the exact h-vector-dependent values

    e=3:
      (1,2)     -> 5,
      (1,1,1)   -> 7;

    e=4:
      (1,3)       -> 2,
      (1,2,1)     -> 4,
      (1,1,1,1)   -> 8;

    e=5:
      (1,3,1)     -> 1,
      (1,2,2)     -> 3,
      (1,2,1,1)   -> 5.
Qed.

Corollary smallest_remaining_embedded_defect_is_e5_131:
  The h-vector

    e=5,
    h=(1,3,1)

  has

    T ~= C(-2)

  as a graded vector space and is annihilated by the homogeneous maximal ideal.

  Consequently

    Ann_B(T)=m_B.

Proof:
  The exact table says T is one-dimensional and concentrated in degree two.
  Every positive-degree element sends it to degree at least three, where T is
  zero.  Thus m_B*T=0.  A unit cannot annihilate the nonzero module T, so the
  annihilator is exactly m_B.
Qed.

Interpretation:
  The remaining height-three low-multiplicity frontier has no unknown torsion
  Hilbert function.  Its embedded defect is completely determined by the
  saturated-core h-vector.

  In particular the entire e=3,4,5 frontier now shares

    m^3*T=0,

  so the two final cuts annihilate T automatically.  The smallest unresolved
  core is e=5 with h-vector (1,3,1), where T has length one and

    Ann_B(T)=m_B.

IMPORTANT_NONCONCLUSION:
  This file does NOT close any of the e=3,4,5 tangent branches by itself.

  It does NOT classify the multiplication algebra of the saturated cores from
  their h-vectors alone, and it does not import the e=2 residual-colon argument
  to higher multiplicity.

  It makes no claim for q=4 height two, homogeneous q<=3, or the unrestricted
  nonhomogeneous local deviation-two frontier.

  No generic F_13 algebraicity theorem is claimed.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  The first remaining q=4, ht(Q)=3 branch is still

    e(B) in {3,4,5},

  but its saturation torsion is now exact and every final cut annihilates it.

NEXT_BOUNDED_OBJECT:
  Treat first

    e=5,
    h=(1,3,1),
    Hilb_T=t^2,
    Ann_B(T)=m_B.

  Recompute the conormal connecting sequence with D=E=T after choosing regular
  core combinations.  The domain Ann_A(T) is then the maximal ideal of A when
  L intersect T=0.  Determine the resulting required connecting excess and the
  finite core colon carrier.  Stop before moving to the other seven h-vectors
  unless this smallest case is closed or exposes a genuinely new obstruction.
