Standalone residual-profile reduction for the remaining multiplicity-one,
depth-one saturated core in the homogeneous q=4, height-two branch of the
order-13 deviation-two program.

SCOPE:
  Continue only from the current q=4 height-two saturated-core profile and the
  already closed multiplicity-two Type-A/Type-B/Type-C endpoints.

  Let

    S := C[x1,x2,x3,x4],
    Q subset S

  be generated by four linearly independent quadrics with ht(Q)=2.  Put

    B := S/Q,
    Qsat := saturation(Q),
    Ccore := S/Qsat,
    T := Qsat/Q.

  Retain the standing conclusions

    dim Ccore = 2,
    depth_m(Ccore) >= 1,
    e(Ccore) in {1,2,3},

  together with

    dim B_0 = 1,
    dim B_1 = 4,
    dim B_2 = 6.

  This file treats only the still-open alternative

    e(Ccore)=1,
    depth_m(Ccore)=1.

It performs one bounded reduction: the multiplicity-one depth defect is
identified with a one-dimensional Cohen--Macaulay residual module supported
projectively in dimension zero, and its first two graded pieces are tied
exactly to the saturation defect T.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. LINEAR SATURATION RANK DROPS TO ZERO OR ONE
--------------------------------------------------------------------------

Write

    u1 := dim_C (Qsat)_1,
    u2 := dim_C (Qsat/(q1,q2))_2

with u2 interpreted as in the preceding saturated-core profile, so that

    dim Ccore_1 = 4-u1,
    dim Ccore_2 = 8-u2,
    dim T_1 = u1,
    dim T_2 = u2-2.

Theorem multiplicity_one_depth_one_has_at_most_one_linear_saturation_class:
  One has

    u1 in {0,1}.

Proof:
  The preceding profile proves u1<=2.  It also proves that u1=2 forces

    Ccore ~= C[s,t],

  which has depth two.  This contradicts the present depth-one hypothesis.
  Hence u1<=1, and u1 is a nonnegative integer.
Qed.

Corollary first_saturation_defect_profile:
  One has

    dim T_1 in {0,1},

  and

    dim Ccore_1 in {4,3}.
Qed.

--------------------------------------------------------------------------
2. THE TOP-DIMENSIONAL DEGREE-ONE SUPPORT IS A LINE
--------------------------------------------------------------------------

ExternalResult degree_one_projective_curve_has_linear_top_component:
  Over an algebraically closed field, a one-dimensional projective scheme whose
  top-dimensional cycle has total degree one has exactly one one-dimensional
  associated component; that component has generic multiplicity one and its
  reduced support is a projective line.

Theorem canonical_line_quotient:
  There is a homogeneous height-two linear prime

    P=(l1,l2) subset S

  such that

    Qsat subset P

  and therefore a graded exact sequence

    0 -> D -> Ccore -> S/P -> 0,

  where

    D := P/Qsat.

  Moreover

    S/P ~= C[s,t].

Proof:
  The multiplicity-one hypothesis says that the top-dimensional projective
  cycle of Proj(Ccore) has degree one.  Apply the external degree-one result to
  obtain its unique line L and let P=I(L).  Every element of Qsat vanishes on
  Proj(Ccore), hence on L, so Qsat subset P.  Quotienting gives the displayed
  exact sequence.  A line in P^3 has homogeneous coordinate ring C[s,t].
Qed.

--------------------------------------------------------------------------
3. THE RESIDUAL MODULE IS EXACTLY THE DEPTH-ONE OBSTRUCTION
--------------------------------------------------------------------------

Theorem residual_module_is_nonzero_one_dimensional_CM:
  The module D=P/Qsat is nonzero, has Krull dimension one, and is
  Cohen--Macaulay.

Proof:
  If D=0, then Ccore~=S/P~=C[s,t], which has depth two, contradicting the
  standing depth-one hypothesis.  Hence D is nonzero.

  In the exact sequence

    0 -> D -> Ccore -> S/P -> 0,

  both Ccore and S/P have dimension two and multiplicity one.  Therefore D has
  dimension at most one: a two-dimensional submodule would contribute positive
  two-dimensional multiplicity and force e(Ccore)>e(S/P).

  Since Ccore is saturated,

    H^0_m(Ccore)=0.

  Any finite-length submodule of D would also be a finite-length submodule of
  Ccore, so

    H^0_m(D)=0.

  Thus D cannot have dimension zero.  Consequently dim D=1 and depth_m(D)>=1.
  Since dim D=1, D is Cohen--Macaulay.
Qed.

Theorem residual_local_cohomology_is_the_core_deficiency:
  There is a natural graded isomorphism

    H^1_m(D) ~= H^1_m(Ccore).

Proof:
  Apply local cohomology to

    0 -> D -> Ccore -> S/P -> 0.

  One has

    H^0_m(D)=0,
    H^0_m(Ccore)=0,

  by the preceding theorem and saturation.  Also S/P~=C[s,t] has depth two, so

    H^0_m(S/P)=0,
    H^1_m(S/P)=0.

  The long exact sequence therefore identifies H^1_m(D) with H^1_m(Ccore).
Qed.

Corollary the_remaining_depth_defect_is_projectively_zero_dimensional:
  The only obstruction separating Ccore from its line quotient is the
  one-dimensional graded Cohen--Macaulay module D.  Its projective support has
  dimension zero, and its local cohomology is exactly the depth-one deficiency
  of Ccore.
Qed.

--------------------------------------------------------------------------
4. EXACT FIRST TWO DEGREE CONSERVATION LAWS
--------------------------------------------------------------------------

Theorem exact_degree_one_residual_size:
  One has

    dim_C D_1 = 2-u1.

  In particular

    dim_C D_1 in {2,1}.

Proof:
  Since S/P is the coordinate ring of a line,

    dim_C (S/P)_1=2.

  Taking degree one in

    0 -> D -> Ccore -> S/P -> 0

  gives

    dim D_1
      = dim Ccore_1 - 2
      = (4-u1)-2
      = 2-u1.
Qed.

Corollary exact_degree_one_defect_conservation:
  One has

    dim_C D_1 + dim_C T_1 = 2.
Qed.

Theorem exact_degree_two_residual_size:
  One has

    dim_C D_2 = 5-u2.

Proof:
  The line ring has

    dim_C (S/P)_2=3.

  The preceding saturated-core bookkeeping gives

    dim_C Ccore_2=8-u2.

  Hence the degree-two part of the exact line-quotient sequence gives

    dim D_2=(8-u2)-3=5-u2.
Qed.

Corollary exact_degree_two_defect_conservation:
  One has

    dim_C D_2 + dim_C T_2 = 3.

Proof:
  Combine

    dim D_2=5-u2

  with

    dim T_2=u2-2.
Qed.

--------------------------------------------------------------------------
5. COHEN--MACAULAY MONOTONICITY SHARPENS THE SECOND DEFECT
--------------------------------------------------------------------------

Theorem residual_Hilbert_function_is_nondecreasing:
  For every n>=1,

    dim_C D_n >= dim_C D_(n-1).

Proof:
  The module D is one-dimensional Cohen--Macaulay over the infinite field C.
  Choose a linear form h avoiding its associated primes.  Then multiplication
  by h is injective on D:

    0 -> D(-1) --times h--> D.

  Therefore, degree by degree,

    dim D_n - dim D_(n-1)
      = dim (D/hD)_n
      >= 0.
Qed.

Theorem second_saturation_rank_bound:
  One has

    u2 <= 3+u1.

  Equivalently,

    dim_C T_2 <= 1+u1.

Proof:
  Apply monotonicity in degrees one and two:

    5-u2
      = dim D_2
      >= dim D_1
      = 2-u1.

  Rearranging gives

    u2<=3+u1.

  Since dim T_2=u2-2, the equivalent form follows.
Qed.

Corollary two_case_initial_defect_profile:
  Exactly one of the following numerical cases holds:

    Case L0:
      u1=0,
      dim T_1=0,
      dim D_1=2,
      u2<=3,
      dim T_2<=1.

    Case L1:
      u1=1,
      dim T_1=1,
      dim D_1=1,
      u2<=4,
      dim T_2<=2.
Qed.

--------------------------------------------------------------------------
6. SHARP BOUNDARY
--------------------------------------------------------------------------

The multiplicity-one depth-one q=4 height-two core is now reduced to a
one-dimensional Cohen--Macaulay residual module

    D=P/Qsat

sitting in

    0 -> D -> Ccore -> C[s,t] -> 0,

with

    H^1_m(D) ~= H^1_m(Ccore),

and with exact low-degree conservation

    dim D_1 + dim T_1 = 2,
    dim D_2 + dim T_2 = 3.

The remaining numerical alternatives begin only with

    (dim T_1, upper_bound(dim T_2))
      = (0,1)

or

      = (1,2).

IMPORTANT_NONCONCLUSION:
  This file does NOT classify D, does NOT prove a uniform annihilator of D or T,
  and does NOT close the multiplicity-one depth-one branch.

  In particular it does not promote the full q=4 height-two parent and does not
  promote the full order-13 frontier.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_reduced_to_residual_CM_module.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the one-dimensional Cohen--Macaulay residual module

    D=P/Qsat

  under the four-independent-quadric containment Q subset Qsat subset P,
  starting from the two exact low-degree alternatives above.

NEXT_BOUNDED_OBJECT:
  Split only by u1=0 versus u1=1.  In each case determine the smallest possible
  Hilbert series of D compatible with four independent quadrics in Q and the
  exact degree-one/degree-two conservation laws.  Stop before any tangent-space
  estimate.
