Standalone rho_Q=0 normal-form classification inside the P-subset-J contained
rank-defect leaf of the r-in-P LK3-C2 carrier in the saturated H01 minimal-chain
rank-two endpoint of the homogeneous q=4, height-two, multiplicity-one,
depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_R2_LK3_C2_r_in_P_contained_rank_defect_P_incidence_reduction.v

  and retain

    S=C[x1,x2,x3,x4],
    Q=Qsat subset P,
    dim_C Q_2=4,
    ht(Q)=2,
    e(S/Q)=1,
    K=(Q:r)=(a,b,F) subset J,
    K_1=span_C{a,b},
    dim_C(Q_2 intersect r*S_1)=2,

  together with

    P subset J

  and the contained rank formula

    rho_Q = 4 - dim_C(Q_2 intersect (J*K)_2).

This file treats only the subcase

    rho_Q=0.

It performs one bounded task: classify the rho_Q=0 leaf exactly.  No tangent
closure of the resulting normal form is claimed.  No rho_Q=1 or rho_Q=2 leaf,
no r-not-in-P leaf, no LK3-C3, R2-LK2, R2-QK, H01-M2-R1, or q<=3 branch is
entered.  No Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. RANK ZERO PUTS ALL FOUR QUADRICS IN J_1*K_1
--------------------------------------------------------------------------

Since rho_Q=0, the rank-defect intersection formula gives

    Q_2 subset (J*K)_2.

Because K has only the two linear generators a,b in degree one,

    (J*K)_2 = J_1*K_1.

Put

    A:=K_1=span_C{a,b}.

Thus

    Q_2 subset A*J_1.

We also retain

    Q_2 subset P*S_1

because Q subset P.

--------------------------------------------------------------------------
2. P DISTINCT FROM A WOULD FORCE MULTIPLICITY TWO
--------------------------------------------------------------------------

Assume first that

    P != A.

Both P and A are two-dimensional subspaces of the three-dimensional space J_1.
Choose independent linear forms s,u,v such that

    A=(s,u),
    P=(s,v),
    J=(s,u,v).

The degree-two space A*J_1 is

    span_C{s^2,s*u,s*v,u^2,u*v},

while P*J_1 is

    span_C{s^2,s*u,s*v,u*v,v^2}.

Hence

    (A*J_1) intersect (P*J_1)
      = span_C{s^2,s*u,s*v,u*v}
      = (A*P)_2.

The left side contains Q_2.  Since both it and Q_2 have dimension four,

    Q_2=(A*P)_2.

Because Q is generated by its four quadrics,

    Q=A*P.

The two height-two linear primes A and P are distinct.  Therefore S/(A*P) has
two degree-one minimal components and

    e(S/Q)=2.

This contradicts the standing H01 multiplicity

    e(S/Q)=1.

Therefore

    P=A=K_1.

Theorem H01_m2_R2_LK3_C2_r_in_P_contained_rho_zero_forces_P_eq_K1:
  In the contained rho_Q=0 leaf,

    P=K_1.
Qed.

--------------------------------------------------------------------------
3. NORMALIZE P=K_1 AND THE FOUR-DIMENSIONAL QUADRIC SPACE
--------------------------------------------------------------------------

Since r belongs to P, choose p independent of r with

    P=K_1=(r,p).

Choose c so that

    J=(r,p,c).

Now

    (J*K)_2 = J_1*P_1

has basis

    r^2, r*p, p^2, r*c, p*c.

The exact r-multiple statement says

    dim_C(Q_2 intersect r*S_1)=2.

The two-dimensional space r*P_1=span_C{r^2,r*p} is already contained in Q_2,
so it is exactly the full r-multiple subspace.  In particular no nonzero
combination of the remaining two generators of Q_2 can reduce to r*c.

After changing the remaining generator basis, there are scalars alpha,beta in C
such that

    Q_2 = span_C{
      r^2,
      r*p,
      p^2 + alpha*r*c,
      p*c + beta*r*c
    }.

Replace p by p+beta*r.  Modulo the first two basis vectors this leaves p^2
unchanged and replaces p*c+beta*r*c by p*c.  Hence we may normalize beta=0:

    Q=(r^2, r*p, p^2+alpha*r*c, p*c).

--------------------------------------------------------------------------
4. THE COLON CANNOT BE THE REDUCED-POINT TYPE
--------------------------------------------------------------------------

The displayed generators involve only r,p,c.  Thus Q is extended from the
three-variable subring C[r,p,c], and so is its colon

    K=(Q:r).

Modulo P=(r,p), the ideal K/P in

    S/P ~= C[c,t]

is therefore extended from an ideal in C[c].

But the already-proved contained classification says K/P is generated by one
nonzero quadratic Fbar.  A homogeneous quadratic generator coming from C[c]
can only be a nonzero scalar multiple of c^2.

Therefore the reduced-point possibility

    Fbar=c*ell,
    ell independent of c

is impossible here.  The rho_Q=0 leaf is necessarily the double-point type:

    K=(r,p,c^2).

Theorem H01_m2_R2_LK3_C2_r_in_P_contained_rho_zero_double_only:
  The contained rho_Q=0 leaf cannot be the reduced-point K type.  It has

    K=(r,p,c^2).
Qed.

--------------------------------------------------------------------------
5. THE QUADRATIC COEFFICIENT alpha IS NONZERO
--------------------------------------------------------------------------

Because c^2 belongs to K=(Q:r),

    r*c^2 belongs to Q.

If alpha=0, then

    Q=(r^2,r*p,p^2,p*c).

In the quotient S/Q, the class of r*c^2 is nonzero: the four displayed
relations kill r^2, r*p, p^2, and p*c, but impose no relation on r*c^2.
Equivalently, after passing to the C[c,t]-module decomposition, r survives with
no c-torsion.

Hence alpha=0 would imply

    c^2 notin (Q:r),

contradicting K=(r,p,c^2).

Therefore

    alpha != 0.

Rescale c and the third quadratic generator to normalize alpha=1.  We obtain

    Q=(r^2, r*p, p^2+r*c, p*c).

Moreover

    r*c^2
      = c*(p^2+r*c) - p*(p*c)
      belongs to Q,

so (r,p,c^2) is visibly contained in (Q:r).  Both ideals have the already-known
Hilbert series

    (1+t)/(1-t),

hence equality holds:

    (Q:r)=(r,p,c^2).

Theorem H01_m2_R2_LK3_C2_r_in_P_contained_rho_zero_normal_form:
  Every contained rho_Q=0 carrier is, after homogeneous linear coordinates and
  generator changes, exactly

    P=(r,p),
    J=(r,p,c),
    K=(r,p,c^2),

    Q=(r^2,
       r*p,
       p^2+r*c,
       p*c).
Qed.

--------------------------------------------------------------------------
6. THE NORMAL FORM HAS EXACTLY THE H01 m=2 HILBERT PROFILE
--------------------------------------------------------------------------

In C[r,p,c]/Q the relations are

    r^2=0,
    r*p=0,
    p*c=0,
    p^2=-r*c,
    r*c^2=0.

As a graded C[c]-module it has one free generator 1, two degree-one torsion
classes r,p, and one degree-two class r*c.  Thus after adjoining the fourth
free variable t,

    Hilb_(S/Q)(z)
      = 1/(1-z)^2 + (2*z+z^2)/(1-z)
      = (1+2*z-z^2-z^3)/(1-z)^2.

So the rho_Q=0 normal form is compatible with the exact H01 m=2 Hilbert
profile.  It is a genuine surviving carrier, not an algebraic impossibility.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  rho_Q=0 => P=K_1.
  rho_Q=0 => contained-double type.
  rho_Q=0 => unique normal form

    Q=(r^2,r*p,p^2+r*c,p*c),
    K=(r,p,c^2),
    J=(r,p,c).

SURVIVES:
  The displayed rho_Q=0 normal form has the exact H01 m=2 Hilbert series.

NOT_PROVED:
  tangent exclusion of the rho_Q=0 normal form.
  rho_Q=1 classification or exclusion.
  all-degree contained r-in-P closure.
  H01_m2_R2_LK3_C2 closure.
  H01 closure.
  q=4 height-two full closure.
  homogeneous q<=3 closure.
  Oblivion Closure.

BOUNDARY:
  not H01_m2_R2_LK3_C2_r_in_P_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in the unique rho_Q=0 normal form

    Q=(r^2,r*p,p^2+r*c,p*c).

  Compute its final-pair tangent carrier directly from this monomial-plus-one-
  relation presentation, or else classify rho_Q=1 if that gives the smaller
  next obstruction.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow run for this commit.
