Standalone fifth J-adic-layer closure for the s=2 branch of the homogeneous
q=4, height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_s2_cubic_profile.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    P := C[l1,l2],
    V := Span_C{l1,l2},
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

This file treats only

    s := dim_C Syz_1(Q)=2.

The preceding file proves

    G := J^2*T/J^3*T ~= C(-3)^2,

    H := J^3*T/J^4*T ~= C(-4)^h,

with

    h in {0,1}.

The h=0 case already gives J^3*T=0 by Nakayama.  This file treats only the
residual h=1 case and proves that the next layer vanishes:

    J^4*T/J^5*T = 0.

Consequently

    J^4*T=0

throughout the entire s=2 branch.

The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Define the fifth transverse layer

    L := J^4*T/J^5*T.

Theorem exact_fifth_layer_degree_five_model:
  There is a natural graded identification

    L_5 ~= P_5/(Q_5 intersect P_5).

  Moreover L is generated in ordinary degree five.

Proof:
  Since T=J/Q,

    J^4*T=(J^5+Q)/Q,
    J^5*T=(J^6+Q)/Q.

  Hence

    L ~= J^5/(J^6+(Q intersect J^5)).

  The degree-five pure-transverse part of J^5/J^6 is P_5.  Since the quotient
  is generated by that degree-five part, the displayed model follows.
Qed.

We split only by the already classified first-conormal rank r in {4,3}.

Theorem r4_s2_h1_fifth_layer_vanishes:
  Assume

    r=4,
    s=2,
    h=1.

  Then

    Q_5 intersect P_5=P_5,

  and therefore

    L=0.

Proof:
  The preceding s=2 cubic-profile file proves

    K3:=Q_3 intersect P_3
      = Span_C{Pz,Pw}

  with

    gcd(Pz,Pw)=1,

  where Pz,Pw are independent cubics.

  It also proves that in the residual h=1 case

    Q_4 intersect P_4=P_1*K3.

  Since Q is an ideal,

    P_1*(Q_4 intersect P_4)
      = P_2*K3
      subset Q_5 intersect P_5.

  We claim

    P_2*K3=P_5.

  Indeed, the ideal (Pz,Pw) is a complete intersection of two coprime cubics in
  the two-variable polynomial ring P.  Its quotient has Hilbert series

    (1-t^3)^2/(1-t)^2.

  The degree-five coefficient of this quotient is zero:

    dim P_5 - 2*dim P_2
      = 6-2*3
      = 0,

  because the first relation between two coprime cubics occurs in degree six.
  Hence every quintic belongs to P_2*K3.

  Therefore

    P_5=P_2*K3 subset Q_5 intersect P_5 subset P_5,

  proving equality.  The exact fifth-layer model gives L_5=0, and since L is
  generated in degree five, L=0.
Qed.

We now treat r=3.

Recall the normalized generators

    q1 = z*l1 + h1,
    q2 = w*l1 + z*l2 + h2,
    q3 = w*l2 + h3,
    q4 = H0,

with h1,h2,h3,H0 in P_2, and the canonical quartic

    C4 := l2^2*h1-l1*l2*h2+l1^2*h3.

The preceding s=2 file proves

    K3=H0*V

and

    C4 in Q_4 intersect P_4,
    C4 notin H0*P_2.

Theorem r3_s2_saturation_forces_H0_and_C4_coprime:
  In the r=3,s=2 case,

    gcd(H0,C4)=1.

Proof:
  Suppose H0 and C4 had a nonconstant common divisor.  Over C this divisor has
  a projective root

    [a:b] in P^1

  with

    H0(a,b)=0,
    C4(a,b)=0.

  Evaluate q1,q2,q3 at l1=a,l2=b.  Solving q1=q2=q3=0 for z,w gives

    a*z       = -h1(a,b),
    b*z+a*w   = -h2(a,b),
        b*w   = -h3(a,b).

  For every nonzero pair (a,b), the coefficient matrix

    [ a  0 ]
    [ b  a ]
    [ 0  b ]

  has rank two.  Its unique compatibility condition is

    b^2*h1(a,b)-a*b*h2(a,b)+a^2*h3(a,b)=0,

  exactly C4(a,b)=0.

  Hence there exist z0,w0 satisfying q1=q2=q3=0.  Together with
  q4=H0=0, this produces a projective common zero

    [a:b:z0:w0]

  of Q with (a,b) nonzero.

  This lies off the saturated line V(J)={l1=l2=0}, contradicting

    Qsat=J,

  equivalently Proj(S/Q)=Proj(S/J).

  Therefore H0 and C4 are coprime.
Qed.

Theorem r3_s2_h1_fifth_layer_vanishes:
  Assume

    r=3,
    s=2,
    h=1.

  Then

    Q_5 intersect P_5=P_5,

  and therefore

    L=0.

Proof:
  The preceding s=2 cubic-profile file proves that h=1 forces

    Q_4 intersect P_4
      = H0*P_2 + C*C4,

  a four-dimensional subspace of P_4.

  Multiply by P_1.  Since Q is an ideal,

    H0*P_3 + C4*P_1
      subset Q_5 intersect P_5.

  The first summand has dimension four and the second has dimension two.
  Their intersection is zero.

  Indeed, an equality

    H0*A3=C4*L1

  with A3 in P_3 and L1 in P_1, together with gcd(H0,C4)=1, forces H0 to divide
  L1.  This is impossible by degree unless L1=0, and then A3=0.

  Hence

    dim_C(H0*P_3+C4*P_1)=4+2=6.

  Since dim_C P_5=6,

    H0*P_3+C4*P_1=P_5.

  Thus

    P_5 subset Q_5 intersect P_5 subset P_5,

  proving equality.  The exact fifth-layer model gives L=0.
Qed.

Theorem s2_fifth_layer_vanishes_universally:
  If s=2, then

    J^4*T/J^5*T=0.

Proof:
  If h=0, the preceding fourth-layer result already gives J^3*T=0, hence the
  displayed quotient vanishes.

  If h=1, the r=4 and r=3 theorems above prove L=0 in the two exhaustive
  first-conormal cases.
Qed.

Corollary s2_transverse_tower_closes_at_J_fourth:
  If s=2, then

    J^4*T=0.

Proof:
  The vanishing of the fifth layer says

    J^4*T=J^5*T=J*(J^4*T).

  The module J^4*T has finite length and J lies in the homogeneous maximal
  ideal.  Nakayama's lemma gives

    J^4*T=0.
Qed.

Corollary universal_CM_line_core_J_nilpotence_bound:
  In every q=4 height-two Cohen--Macaulay line-core case,

    J^4*T=0.

Proof:
  The earlier branches give

    s=0 ==> J^2*T=0,
    s=1 ==> J^3*T=0,

  while the present theorem gives

    s=2 ==> J^4*T=0.

  Since s in {0,1,2}, the universal bound follows.
Qed.

IMPORTANT_NONCONCLUSION:
  This file closes the transverse J-adic tower for the s=2 branch and proves a
  universal bound

    J^4*T=0

  throughout the q=4 height-two Cohen--Macaulay line core.

  It does NOT yet prove that the entire line-core branch violates the order-13
  tangent gate.  Turning the nilpotence bound into a sufficiently large
  annihilator/Hom carrier requires one additional argument involving the final
  high-degree parameter pair f,g and the finite module T.

  No assertion is made for the depth-one saturated-core branch.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_closed.
  q4_height2_CM_line_core_s2_transverse_tower_closed.
  q4_height2_CM_line_core_uniform_J4_nilpotence_proved.
  not q4_height2_CM_line_core_tangent_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Use the universal line-core bound

    J^4*T=0

  together with the exact initial torsion Hilbert data and the final homogeneous
  parameter pair f,g of degree at least three to construct a large
  annihilator/Hom carrier in A=S/(Q,f,g), strong enough to compare with the
  order-13 tangent bound.

NEXT_BOUNDED_OBJECT:
  Stay in the depth-two CM line core.  Determine the strongest uniform bound on

    length_C(B/Ann_B(T))

  or an equivalent Hom carrier implied by J^4*T=0 and the established torsion
  Hilbert profile.  Do not enter the depth-one deficiency branch.