Standalone cyclic connecting-map reduction for the remaining low-multiplicity
height-three subbranch of the homogeneous q=4 order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v

  Work with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B) in {1,2,3,4,5}.

  Put

    T := H^0_m(B),
    Cbar := B/T.

  The preceding reduction chooses a constant change of generators

    L:=(f,g)B=(h,k)B

  with h a nonzerodivisor on Cbar and defines

    D:=0:_B h,
    Hh:=hB,
    M:=L/Hh.

  It proves

    D subseteq T,
    dim_C Ann_A(D)>=N-14,

  and shows that any order-13 tangent-gate candidate must have connecting-rank
  excess at least six.

  The purpose of this file is to compute that connecting map from a cyclic
  presentation of M and to isolate the smallest finite module on which positive
  excess can live.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
does not assert generic F_13 algebraicity.

Theorem second_cut_can_also_be_chosen_regular_without_changing_the_frontier:
  Keeping h fixed, one may replace k by

    k' := k + lambda*h

  for a suitable constant lambda in C so that k' is also a nonzerodivisor on
  Cbar.

  This replacement preserves

    L=(h,k),
    D=0:_B h,
    (h:k),
    M=L/hB,

  and the connecting map

    Ann_A(D) -> Ext^1_B(M,A).

Proof:
  The associated primes of the one-dimensional Cohen--Macaulay ring Cbar are
  its finitely many minimal primes.  Since h is a nonzerodivisor, h lies in none
  of them.

  For a fixed associated prime P, the condition

    k+lambda*h in P

  excludes at most one scalar lambda.  Avoid the finite union of these bad
  scalars.  Then k' avoids every associated prime and is regular on Cbar.

  The triangular change

    (h,k) -> (h,k+lambda*h)

  is invertible and preserves L and hB, hence preserves M=L/hB and D.

  Also

    c*(k+lambda*h) in hB

  if and only if c*k in hB, so

    (h:k')=(h:k).

  Finally the short exact sequence

    0 -> hB -> L -> M -> 0

  is unchanged as an inclusion and quotient, so its connecting homomorphism is
  unchanged.
Qed.

From now on make this normalization and again write k for k'.  Define

  E := 0:_B k.

Corollary both_principal_annihilators_live_in_saturation_torsion:
  One has

    D subseteq T,
    E subseteq T.

Proof:
  The first inclusion is established in the preceding file.  Apply the same
  multiplication-kernel argument to k and

    0 -> T -> B -> Cbar -> 0,

  using regularity of k on Cbar, to obtain the second.
Qed.

Define the colon ideals

  K := (h:k) = { c in B : c*k in hB },
  J := (k:h) = { q in B : q*h in kB }.

Theorem cyclic_presentation_of_the_two_generator_quotient:
  The map

    pi : B -> M,
    pi(c) := c*k mod hB,

  is surjective with kernel K.  Hence

    M ~= B/K.

  Consequently

    Hom_B(M,A) ~= 0:_A K.

Proof:
  The class of k generates M=L/hB, so pi is surjective.  Its kernel is exactly
  the defining colon ideal K=(h:k).  This gives M~=B/K.

  A B-linear map B/K->A is determined by the image of 1, and that image must be
  killed by K.  Hence Hom_B(M,A)~=0:_A K.
Qed.

Theorem canonical_colon_transport_map:
  There is a canonical B-linear map

    q : K -> B/D

  characterized by

    c*k = q(c)*h

  in B.

  It satisfies

    ker(q)=E,
    im(q)=J/D,

  and therefore induces an isomorphism

    K/E ~= J/D.

Proof:
  If c belongs to K, then c*k lies in hB, so choose q0 in B with

    c*k=q0*h.

  Any two such q0 differ by an element of D=0:_B h.  Thus q(c):=q0 mod D is
  well defined.  B-linearity is immediate.

  If q(c)=0 in B/D, choose q0 in D.  Then

    c*k=q0*h=0,

  so c belongs to E.  Conversely c in E maps to zero.  Hence ker(q)=E.

  For c in K, the relation q0*h=c*k shows q0 in J, so im(q) is contained in
  J/D.

  Conversely if q0 belongs to J, write

    q0*h=c*k

  for some c in B.  Then c belongs to K and q(c)=q0 mod D.  Thus im(q)=J/D.
Qed.

Theorem explicit_connecting_class_from_the_cyclic_presentation:
  Under the identifications

    Hom_B(hB,A) ~= Ann_A(D),
    M ~= B/K,

  the connecting map

    partial : Ann_A(D) -> Ext^1_B(B/K,A)

  sends z in Ann_A(D) to the class represented by the B-linear map

    f_z : K -> A,
    f_z(c) := q(c)*z.

Proof:
  Multiplication by h identifies hB with B/D.  A map hB->A corresponding to z
  sends

    a*h -> a*z.

  The extension

    0 -> hB -> L -> B/K -> 0

  is the pushout of

    0 -> K -> B -> B/K -> 0

  along the map

    sigma : K -> hB,
    sigma(c)=c*k.

  Writing c*k=q(c)*h, the composite K->hB->A is exactly

    c -> q(c)*z.

  Applying Hom_B(-,A) to

    0 -> K -> B -> B/K -> 0

  identifies Ext^1_B(B/K,A) with the cokernel of

    A=Hom_B(B,A) -> Hom_B(K,A).

  Therefore the connecting class is represented by f_z as claimed.
Qed.

Define the finite colon carrier

  P := K/(E+hB).

Theorem connecting_cocycle_factors_through_the_finite_colon_carrier:
  For every z in Ann_A(D), the representative f_z vanishes on E+hB.
  Hence it factors through a B-linear map

    P -> A.

Proof:
  It vanishes on E because E=ker(q).

  For c=h*b one has

    c*k = b*h*k,

  so q(c)=b*k mod D.  Since k=0 in A=B/(h,k),

    f_z(c)=b*k*z=0.

  Thus f_z vanishes on E+hB.
Qed.

Theorem P_is_an_A_module:
  The ideal L=(h,k) annihilates P.  Hence P is naturally an A=B/L module and

    Hom_B(P,A)=Hom_A(P,A).

Proof:
  Multiplication by h sends K into hB, so h kills P.

  If c belongs to K, then c*k belongs to hB by definition of K.  Thus k also
  kills the class of c in P.  Therefore L kills P.
Qed.

Theorem symmetric_colon_description_of_P:
  The transport map q induces an A-linear isomorphism

    P ~= J/(D+kB).

Proof:
  The map q already induces K/E ~= J/D.

  Under this isomorphism the image of hB is

    (kB+D)/D,

  because

    q(h*b)=b*k mod D.

  Therefore quotienting K/E by the image of hB gives

    K/(E+hB)
      ~= (J/D)/((kB+D)/D)
      ~= J/(D+kB).

  Both sides are killed by h and k, so the isomorphism is A-linear.
Qed.

Let

  H1 := H_1(h,k;B)

be first Koszul homology.

Theorem colon_carrier_is_a_quotient_of_first_Koszul_homology:
  There is an exact sequence

    0 -> D/kD
      -> H1
      -> K/hB
      -> 0.

  Consequently P is a quotient of H1.

Proof:
  A Koszul one-cycle is a pair (a,b) with

    a*h+b*k=0.

  Its second coordinate b lies in K.  Sending its homology class to

    b mod hB

  is well defined because a Koszul boundary changes b by a multiple of h.
  Every b in K lifts to a cycle by choosing q with b*k=q*h and taking

    (-q,b), so the map is surjective.

  If b lies in hB, write b=c*h.  Then

    (a+c*k)*h=0,

  so d:=a+c*k lies in D.  Modulo the Koszul boundary determined by c, the cycle
  is represented by (d,0).

  Two such representatives differ by a boundary with second coordinate zero
  exactly when the boundary parameter lies in D; the first coordinate then
  changes by an element of kD.  Thus the kernel is D/kD.

  Finally P is the further quotient of K/hB by the image of E, so P is a
  quotient of H1.
Qed.

Define as before

  sigma := rank_C(partial),
  epsilon := sigma - dim_C Hom_B(M,A).

Theorem connecting_rank_is_bounded_by_the_colon_carrier_dual:
  One has

    sigma <= dim_C Hom_A(P,A),

  and therefore

    epsilon
      <= dim_C Hom_A(P,A)
         - dim_C(0:_A K).

Proof:
  Every connecting representative f_z factors through P.  Hence the image of
  partial inside Ext^1_B(B/K,A) is contained in the image of

    Hom_A(P,A) -> Hom_B(K,A) -> Ext^1_B(B/K,A).

  Its rank is therefore at most dim Hom_A(P,A).

  The cyclic presentation gives

    Hom_B(M,A)~=0:_A K.

  Subtract this dimension from the rank bound.
Qed.

Corollary dangerous_candidate_forces_finite_Koszul_colon_Hom_excess_six:
  If the order-13 tangent gate holds, then necessarily

    dim_C Hom_A(P,A)
      - dim_C(0:_A K)
      >= 6,

  where

    K=(h:k),
    E=0:_B k,
    P=K/(E+hB)
      ~= (k:h)/(D+kB),
    D=0:_B h,

  and both D and E lie in the finite saturation torsion T.

Proof:
  The preceding conormal-rank reduction proves that the tangent gate forces

    epsilon>=6.

  The present theorem gives

    epsilon
      <= dim Hom_A(P,A)-dim(0:_A K).

  Combining the inequalities gives the claim.
Qed.

Interpretation:
  The first genuinely new obstruction is no longer an arbitrary Ext^1 rank.
  Positive connecting-rank excess can only be carried by the finite A-module

    P=K/(E+hB),

  equivalently by the symmetric colon quotient

    (k:h)/(D+kB).

  This module is a quotient of first Koszul homology and is unchanged at the
  level of K and M by the regularizing triangular change k->k+lambda*h.

  Therefore a dangerous low-multiplicity q=4 height-three candidate must
  produce at least six dimensions of A-dual Hom excess on this finite
  Koszul-colon carrier.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove

    dim Hom_A(P,A)-dim(0:_A K) <= 5.

  Hence it does NOT close the e(B)<=5 height-three branch.

  It does not classify P on the ten saturated-core Artin reductions and makes
  no claim for the q=4 height-two branch, homogeneous q<=3 branches, or the
  unrestricted nonhomogeneous local deviation-two frontier.

BOUNDARY:
  A dangerous q=4, ht(Q)=3, e(B)<=5 candidate must satisfy

    dim_C Hom_A(
      (h:k)/((0:k)+hB),
      A
    )
      - dim_C(0:_A(h:k))
      >= 6.

  Equivalently, after the symmetric regular normalization,

    dim_C Hom_A(
      (k:h)/((0:h)+kB),
      A
    )
      - dim_C(0:_A(h:k))
      >= 6.

NEXT_BOUNDED_OBJECT:
  compute the A-module P on the ten possible saturated-core Artin reductions.
  First test whether its image modulo the embedded torsion T has nonpositive
  net Hom excess, as in the closed e=6 Bockstein compensation argument.  If so,
  only the finite T-supported kernel/cokernel remains to be bounded.  Stop at
  the first saturated-core h-vector for which the excess can reach six rather
  than moving to the height-two branch.
