Standalone quadratic-relation reduction for the unique remaining H01-C5 m=3
colon type E2 in the homogeneous q=4, height-two multiplicity-one, depth-one
order-13 deviation-two program.

SCOPE:
  Continue only after the E0/E1 exclusion and retain

    S = C[x1,x2,x3,x4],
    Q = (q1,q2,q3,q4),
    B = S/Q,
    Qsat = Q^sat,
    Ccore = S/Qsat,
    T = Qsat/Q,

  in H01-C5 with

    m = 3,
    sigma = 5,
    tau_3 = 1.

The preceding m=3 persistence file gives a cubic gamma such that

    Qsat = Q + (gamma),
    T ~= S/(Q:gamma)(-3).

The colon classification leaves only E2 after E0/E1 are excluded.  Thus, after
linear coordinates,

    K := (Q:gamma) = (z1,z2) + I(u,v),

where I is a homogeneous (u,v)-primary ideal with

    I_1 = 0.

Put

    R := C[u,v]/I.

Then

    T ~= R(-3),
    dim R_0 = 1,
    dim R_1 = 2.

This file performs one bounded task only: prove that I already has a nonzero
quadratic relation.  Equivalently,

    dim R_2 <= 2.

No classification of I_2 is made beyond nonvanishing.  No E2 tangent estimate,
H01-C4, q<=3, or full order-13 statement is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE EXACT DEGREE-FOUR VALUE IN E2
--------------------------------------------------------------------------

For m=3 the residual module D=P/Qsat has Hilbert series

    Hilb_D(t) = (2*t+t^2+t^3)/(1-t).

Hence

    dim D_n = 4

for every n>=3.  Since S/P is the coordinate ring of a line,

    dim (S/P)_n = n+1.

From

    0 -> D -> Ccore -> S/P -> 0

one therefore gets

    dim Ccore_n = n+5

for every n>=3.

In particular

    dim Ccore_4 = 9,
    dim Ccore_5 = 10.

Because T~=R(-3), E2 gives

    dim T_4 = dim R_1 = 2.

Thus the graded exact sequence

    0 -> T -> B -> Ccore -> 0

gives

    dim B_4 = 9+2 = 11.

Theorem H01_C5_m3_E2_degree_four_value:
  In E2,

    dim_C B_4 = 11.
Qed.

--------------------------------------------------------------------------
2. IF THERE IS NO QUADRATIC COLON RELATION THEN B_5=13
--------------------------------------------------------------------------

Assume for contradiction

    I_2 = 0.

The degree-two piece of C[u,v] has dimension three, so

    dim R_2 = 3.

Again using T~=R(-3),

    dim T_5 = dim R_2 = 3.

Since

    dim Ccore_5 = 10,

one gets

    dim B_5 = 10+3 = 13.

Theorem H01_C5_m3_E2_no_quadratic_relation_forces_B5_13:
  If I_2=0, then

    dim_C B_5 = 13.
Qed.

--------------------------------------------------------------------------
3. 11 TO 13 IS EXACT MAXIMAL MACAULAY GROWTH
--------------------------------------------------------------------------

The fourth Macaulay representation of eleven is

    11
      = binom(5,4)
        + binom(4,3)
        + binom(2,2)
        + binom(1,1)
      = 5+4+1+1.

Therefore its fourth Macaulay successor is

    11^{<4>}
      = binom(6,5)
        + binom(5,4)
        + binom(3,3)
        + binom(2,2)
      = 6+5+1+1
      = 13.

Thus the hypothetical values

    dim B_4 = 11,
    dim B_5 = 13

realize equality in Macaulay growth from degree four to degree five.

Theorem H01_C5_m3_E2_no_quadratic_relation_maximal_growth:
  Under I_2=0,

    H_B(5) = H_B(4)^{<4>} = 13.
Qed.

--------------------------------------------------------------------------
4. GOTZMANN PERSISTENCE WOULD FORCE MULTIPLICITY TWO
--------------------------------------------------------------------------

The ideal Q is generated by quadrics, hence in degrees at most four.  Gotzmann
persistence therefore applies to equality in Section 3.

The Macaulay expansion persists.  For every n>=4 one obtains

    H_B(n)
      = binom(n+1,n)
        + binom(n,n-1)
        + binom(n-2,n-2)
        + binom(n-3,n-3)
      = (n+1)+n+1+1
      = 2*n+3.

Hence the Hilbert polynomial of B would be

    2*n+3.

Because ht(Q)=2 in the four-variable polynomial ring S, B has dimension two.
For a two-dimensional standard graded algebra, the leading coefficient of the
linear Hilbert polynomial is its multiplicity.  Therefore the hypothetical
persistent Hilbert polynomial forces

    e(B)=2.

But the standing multiplicity-one H01 branch has

    e(B)=e(Ccore)=1.

Contradiction.

Theorem H01_C5_m3_E2_no_quadratic_relation_multiplicity_contradiction:
  The assumption I_2=0 is impossible.
Qed.

--------------------------------------------------------------------------
5. E2 HAS A NONZERO QUADRATIC ANNIHILATOR
--------------------------------------------------------------------------

Therefore

    I_2 != 0.

Equivalently,

    dim_C R_2 <= 2,

and hence

    dim_C T_5 <= 2.

Choose any nonzero

    rho_2(u,v) in I_2.

Viewed in S, rho_2 belongs to K=(Q:gamma), so

    rho_2 * gamma in Q_5.

Thus E2 necessarily supplies a genuine quadratic annihilator of the cyclic
cubic saturation class.

Theorem q4_H01_C5_m3_E2_quadratic_relation_forced:
  In every surviving H01-C5 m=3 E2 state,

    I_2 != 0,

  equivalently

    dim_C (C[u,v]/I)_2 <= 2.

  In particular there exists a nonzero binary quadratic rho_2 with

    rho_2*gamma in Q_5.
Qed.

--------------------------------------------------------------------------
6. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E2_quadratic_relation_forced.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E2_T5_at_most_two.

CURRENT_H01_C5_M3_STATUS:
  E0 is empty.
  E1 is empty.
  E2 is the only remaining colon type.
  In E2 the binary Artin colon ideal I has a nonzero quadratic piece.

IMPORTANT_NONCONCLUSION:
  This file does NOT classify dim I_2 as 1,2,or3.
  It does NOT exclude E2.
  It does NOT close H01-C5 m=3.
  It does NOT close H01.
  It does NOT make a tangent-space estimate.
  It does NOT enter H01-C4.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E2_quadratic_relation_forced.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_E2_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3 E2.  Split according to

    dim_C R_2 in {0,1,2}

  or equivalently

    dim_C I_2 in {3,2,1}.

  Start with the smallest surviving quadratic shadow.  Determine whether the
  forced quadratic annihilator rho_2*gamma in Q_5 creates an additional
  coefficient-rank or second-syzygy obstruction beyond c-a=4.

NEXT_ACTIONS:
  1. Re-read the exact terminal run for this commit.
