Standalone structural exclusion of the H01-M2-R1 endpoint in the homogeneous
q=4, height-two, multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Retain the established H01-M2-R1 data

    S := C[x1,x2,x3,x4],
    P := (l1,l2),
    Q subset Qsat subset P,
    D := P/Qsat,
    T := Qsat/Q,

with

    Q generated by exactly four independent quadrics,
    Q_2=(Qsat)_2,
    Qsat=Q+(gamma),
    deg(gamma)=3,
    T ~= S/Kgamma(-3),
    Kgamma:=(Q:gamma),

and T nonzero finite length.  Retain also the rank-one Artinian normal form for
a general D-regular linear form h:

    R:=S/(h)=C[u,v,w],
    E:=D/hD ~= C(-1) direct_sum C[u]/(u^2)(-1),

where v,w annihilate both summands.

The H01-M2-R2 branch is already closed.  This file performs one bounded task
only: show that the unique cubic saturation generator in R1 is incompatible
with the finiteness of the saturation defect.  Hence H01-M2-R1 is structurally
empty.

No q<=3 or Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE CYCLIC SATURATION COLON IS m-PRIMARY
--------------------------------------------------------------------------

Because

    T=Qsat/Q

is the saturation defect, T has finite length.  Since Qsat=Q+(gamma), the map

    S -> T,
    s |-> s*gamma+Q

is surjective with kernel

    Kgamma=(Q:gamma).

Thus

    T ~= S/Kgamma(-3).

Since T is nonzero finite length, Kgamma is a proper homogeneous m-primary
ideal.  Therefore for some N>>0,

    m^N subset Kgamma.

For every linear form h, its image

    Kbar:=(Kgamma+(h))/(h)

in R=S/(h) is consequently m_R-primary.

Theorem H01_m2_R1_saturation_colon_mprimary:
  Kgamma is homogeneous m-primary, and its image Kbar modulo the chosen general
  D-regular h is homogeneous m_R-primary.
Qed.

--------------------------------------------------------------------------
2. REDUCE THE MINIMAL R1 PRESENTATION MODULO h
--------------------------------------------------------------------------

The established R1 minimal resolution remains minimal after the D-regular cut.
In particular the presentation of

    E=D/hD

has two generators in degree one, five minimal relations in degree two, and one
minimal relation in degree three.

Choose the rank-one normal-form basis

    e0,e1 in E_1

so that

    m_R*e0=0,
    v*e1=w*e1=0,
    u*e1!=0,
    u^2*e1=0.

Thus the full degree-two relation space is

    R_1*e0 direct_sum span_C{v,w}*e1,

and the unique minimal cubic relation is represented by

    u^2*e1.

A constant GL_2 change of the two generators of P induces the same change on
the two degree-one generators of E.  Choose homogeneous linear generators

    a,b

of the image Pbar=(P+(h))/(h) so that a maps to e0 and b maps to e1.

The intrinsic P-Koszul relation is then

    b*e0-a*e1=0.

Because the coefficient of e1 in every degree-two relation belongs to
span_C{v,w}, the intrinsic relation forces

    a in span_C{v,w}.

Since a,b are independent, exactly two incidence types remain:

  TYPE I:
    b also belongs to span_C{v,w};

  TYPE II:
    b does not belong to span_C{v,w}.

Theorem H01_m2_R1_Artinian_P_incidence_split:
  After coordinates, every R1 endpoint lies in exactly one of these two types.
Qed.

--------------------------------------------------------------------------
3. TYPE I NORMAL FORM AND ITS REDUCED COLON
--------------------------------------------------------------------------

Assume Type I.  Since a,b are independent in span_C{v,w}, change coordinates
inside that plane and normalize

    a=v,
    b=w.

The map from a degree-two relation

    A*e0+B*e1

back to the ideal Qsat modulo h sends it to

    A*a+B*b=A*v+B*w.

The degree-two relation space is

    R_1*e0 direct_sum (v,w)*e1.

After quotienting by the one intrinsic relation

    w*e0-v*e1,

the image is the four-dimensional quadratic space

    Qbar_2
      = span_C{u*v,v^2,v*w,w^2}.

Because Q and Qsat have exactly the same degree-two part and Q is generated by
its four quadrics,

    Qbar=(u*v,v^2,v*w,w^2)

inside R.

The unique minimal cubic relation u^2*e1 maps to the cubic saturation class

    gammabar=u^2*w

modulo Qbar, after replacing gamma by an equivalent representative modulo Q_3
if necessary.

Now compute the monomial colon.  A monomial multiple of u^2*w belongs to Qbar
exactly when the multiplier belongs to (v,w).  Hence

    (Qbar:gammabar)=(v,w).

Theorem H01_m2_R1_TypeI_reduced_colon:
  In Type I one has

    Qbar=(u*v,v^2,v*w,w^2),
    gammabar=u^2*w,
    (Qbar:gammabar)=(v,w).
Qed.

--------------------------------------------------------------------------
4. TYPE II NORMAL FORM AND ITS REDUCED COLON
--------------------------------------------------------------------------

Assume Type II.  Normalize

    a=v.

Since b is outside span_C{v,w}, its image in the one-dimensional quotient
R_1/span_C{v,w} is nonzero.  Replace the chain coordinate u by b and then
change the basis inside span_C{v,w}; this preserves the rank-one module normal
form.  Thus we may take

    a=v,
    b=u,
    span_C{v,w}=Ann_R(e1)_1.

The degree-two relation space again maps by

    A*e0+B*e1 |-> A*v+B*u.

After removing the intrinsic relation

    u*e0-v*e1,

the four-dimensional quadratic image is

    Qbar_2
      = span_C{u*v,v^2,v*w,u*w}.

Hence

    Qbar=(u*v,v^2,v*w,u*w).

The unique cubic relation u^2*e1 maps to

    gammabar=u^3

modulo Qbar.

A direct monomial colon calculation gives

    (Qbar:u^3)=(v,w).

Indeed v*u^3 is divisible by u*v and w*u^3 is divisible by u*w, while no power
of u alone lies in Qbar.

Theorem H01_m2_R1_TypeII_reduced_colon:
  In Type II one has

    Qbar=(u*v,v^2,v*w,u*w),
    gammabar=u^3,
    (Qbar:gammabar)=(v,w).
Qed.

--------------------------------------------------------------------------
5. REDUCTION OF THE GLOBAL COLON LIES IN THE REDUCED COLON
--------------------------------------------------------------------------

Let

    Kbar=(Kgamma+(h))/(h)

be the image in R of the global saturation colon.

For every k in Kgamma,

    k*gamma in Q.

Reducing modulo h gives

    kbar*gammabar in Qbar.

Therefore

    Kbar subset (Qbar:gammabar).

This containment is purely functorial; it does not assert that colon commutes
with reduction modulo h.

By Sections 3 and 4, in either incidence type

    (Qbar:gammabar)=(v,w).

Thus universally in R1,

    Kbar subset (v,w).

Theorem H01_m2_R1_global_colon_reduction_containment:
  The image of Kgamma modulo h is contained in the height-two linear prime

    (v,w) subset R=C[u,v,w].
Qed.

--------------------------------------------------------------------------
6. m-PRIMARY FINITENESS CONTRADICTS THE HEIGHT-TWO CONTAINMENT
--------------------------------------------------------------------------

Section 1 proves that Kbar is m_R-primary.  Hence some power of the irrelevant
maximal ideal

    m_R=(u,v,w)

is contained in Kbar.  In particular there exists N>=1 with

    u^N in Kbar.

But Section 5 gives

    Kbar subset (v,w).

No positive power u^N belongs to the prime ideal (v,w).  Contradiction.

Therefore neither Type I nor Type II can occur.

Theorem H01_m2_R1_empty:
  The H01-M2-R1 endpoint is structurally impossible.
Qed.

--------------------------------------------------------------------------
7. H01 m=2 CLOSES
--------------------------------------------------------------------------

The established exhaustive H01 m=2 split is

    H01-M2-R2,
    H01-M2-R1,

with the numerical tau_3=2 state already excluded.

The R2 branch is already excluded at the necessary order-13 tangent gate, and
Section 6 excludes R1 structurally.  Hence no H01 m=2 endpoint survives.

Corollary H01_m2_closed:
  The full H01 m=2 branch is CLOSED.
Qed.

This is only the exhaustive promotion of the two established m=2 children.  It
does not by itself promote H01, q4 height-two, q<=3, or OC.

--------------------------------------------------------------------------
8. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  H01_m2_R1_Artinian_P_incidence_split.
  H01_m2_R1_TypeI_reduced_colon.
  H01_m2_R1_TypeII_reduced_colon.
  H01_m2_R1_global_colon_reduction_containment.
  H01_m2_R1_empty.
  H01_m2_closed.

CLOSED:
  H01-M2-R2.
  H01-M2-R1.
  H01 m=2.

NOT_PROVED:
  H01 closure.
  q4 height-two full closure.
  homogeneous q<=3 closure.
  Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Promote H01 only after rechecking that the existing chain-length reduction is
  exhaustive and that every m>=3 H01 child is already closed on the current
  branch.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow run for this commit.
