Standalone quartic reduction for the unique surviving H01-C5 chain value m=3
in the homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_linear_syzygy_reduction.v
    order13_q4_height2_depth_one_multiplicity_one_H01_C5_quartic_colon_reduction.v
    order13_q4_height2_depth_one_multiplicity_one_H01_C5_mge4_gotzmann_saturation_closed.v

  and retain the unique surviving H01-C5 state

    m=3,
    sigma=5,
    tau_3=1.

Write

    S=C[x1,x2,x3,x4],
    Q=(q1,q2,q3,q4),
    B=S/Q,
    Qsat=Q^sat,
    Ccore=S/Qsat,
    T=Qsat/Q,
    P=(l1,l2),
    D=P/Qsat.

The H01 chain has

    Hilb_D(t)=(2*t+t^2+t^3)/(1-t),

and the line quotient is

    0 -> D -> Ccore -> S/P -> 0,

with S/P ~= C[s,t].

The C5 state has

    dim_C((Qsat)_3/Q_3)=1.

This file performs one bounded task only.  Adjoin a lift gamma of the unique
cubic saturation class, set J=Q+(gamma), and determine the exact degree-four
Hilbert value of S/J.  The maximal value ten is incompatible with the
multiplicity-one saturation, so the only surviving value is nine.  It follows
that J already agrees with Qsat through degree four and that the entire fourth
saturation layer is generated by the cubic class.

No exclusion of H01-C5 m=3 is claimed.
No H01-C4, tangent estimate, q<=3 branch, or full order-13 closure is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXACT CORE VALUES FOR m=3
--------------------------------------------------------------------------

For

    Hilb_D(t)=(2*t+t^2+t^3)/(1-t),

one has

    dim_C D_3=4,
    dim_C D_4=4.

The line quotient S/P ~= C[s,t] has

    dim_C(S/P)_3=4,
    dim_C(S/P)_4=5.

Therefore the exact line-quotient sequence gives:

Theorem H01_C5_m3_exact_core_34:
  One has

    dim_C Ccore_3=8,
    dim_C Ccore_4=9.
Qed.

--------------------------------------------------------------------------
2. ADJOIN THE UNIQUE CUBIC SATURATION CLASS
--------------------------------------------------------------------------

Choose

    gamma in (Qsat)_3

whose class spans

    (Qsat)_3/Q_3.

Define

    J:=Q+(gamma).

Then

    Q subset J subset Qsat.

Since Q is generated by quadrics and gamma has degree three, J is generated in
degrees at most three.

Theorem H01_C5_m3_intermediate_matches_saturation_in_degree_three:
  One has

    J_3=(Qsat)_3.

Proof:
  Q_3 has codimension one in (Qsat)_3 and gamma maps to a generator of that
  quotient.  Hence adjoining gamma fills the degree-three saturation defect.
Qed.

Corollary H01_C5_m3_intermediate_degree_three_value:
  One has

    dim_C(S/J)_3=8.
Qed.

--------------------------------------------------------------------------
3. DEGREE FOUR HAS ONLY THE VALUES NINE OR TEN
--------------------------------------------------------------------------

Because

    J subset Qsat,

there is a graded surjection

    S/J -> S/Qsat=Ccore.

Therefore

    dim_C(S/J)_4 >= dim_C Ccore_4 = 9.

On the other hand,

    dim_C(S/J)_3=8.

The third Macaulay expansion is

    8=binom(4,3)+binom(3,2)+binom(1,1),

so

    8^{<3>}
      =binom(5,4)+binom(4,3)+binom(2,2)
      =5+4+1
      =10.

Macaulay growth therefore gives

    dim_C(S/J)_4<=10.

Thus:

Theorem H01_C5_m3_quartic_two_value_frontier:
  One has

    dim_C(S/J)_4 in {9,10}.
Qed.

--------------------------------------------------------------------------
4. THE VALUE TEN IS IMPOSSIBLE
--------------------------------------------------------------------------

Assume for contradiction that

    dim_C(S/J)_4=10.

Then

    dim_C(S/J)_3=8,
    dim_C(S/J)_4=10=8^{<3>}.

Thus S/J has maximal Macaulay growth from degree three to degree four.
Because J is generated in degrees at most three, standard Gotzmann persistence
applies.

Exactly as in the already closed m>=4 C5 branch, persistence yields

    dim_C(S/J)_n=2*n+2

for every n>=3.  Hence S/J has dimension two and multiplicity two:

    e(S/J)=2.

But Q subset J subset Qsat and Qsat is saturated.  Therefore

    Qsat=Q^sat subset J^sat

by monotonicity of saturation, while

    J^sat subset Qsat

because J subset Qsat and Qsat is saturated.  Hence

    J^sat=Qsat.

Saturation preserves the Hilbert polynomial, so

    e(S/J)=e(S/J^sat)=e(S/Qsat)=1,

using the standing multiplicity-one H01 hypothesis.

This contradicts e(S/J)=2.

Therefore:

Theorem H01_C5_m3_quartic_value_ten_is_impossible:
  One has

    dim_C(S/J)_4 != 10.
Qed.

--------------------------------------------------------------------------
5. THE QUARTIC VALUE IS FORCED TO NINE
--------------------------------------------------------------------------

Combine the two-value frontier with the exclusion of ten.

Theorem H01_C5_m3_exact_intermediate_degree_four:
  One has

    dim_C(S/J)_4=9.
Qed.

Since

    dim_C(S/Qsat)_4=dim_C Ccore_4=9

and J_4 subset (Qsat)_4, the induced surjection

    (S/J)_4 -> (S/Qsat)_4

is an isomorphism.

Therefore:

Theorem H01_C5_m3_intermediate_matches_saturation_in_degree_four:
  One has

    J_4=(Qsat)_4.
Qed.

Together with the degree-three equality:

Corollary H01_C5_m3_no_new_quartic_saturation_generator:
  The intermediate ideal J=Q+(gamma) agrees with Qsat in degrees three and
  four.  In particular Qsat has no minimal generator of degree four modulo J.
Qed.

--------------------------------------------------------------------------
6. THE ENTIRE FOURTH TORSION LAYER COMES FROM THE CUBIC CLASS
--------------------------------------------------------------------------

Let

    eta:=gamma+Q in T_3.

Because

    J_4=Q_4+S_1*gamma

and

    J_4=(Qsat)_4,

one has

    T_4
      =(Qsat)_4/Q_4
      =J_4/Q_4
      =(Q_4+S_1*gamma)/Q_4
      =S_1*eta.

Therefore:

Theorem H01_C5_m3_quartic_torsion_is_generated_from_degree_three:
  One has

    T_4=S_1*T_3=S_1*eta.
Qed.

In particular there is no independent quartic saturation class.

The preceding C5 quartic-colon file already gives

    dim_C T_4<=2

for m=3.  Hence the multiplication map

    S_1 -> T_4,
    ell |-> ell*eta

has rank at most two, and its kernel

    (Q:gamma)_1

has dimension at least two.

Corollary H01_C5_m3_cubic_colon_linear_rank_recalled:
  One has

    dim_C(Q:gamma)_1>=2,

and this linear annihilator controls all of T_4 because T_4=S_1*eta.
Qed.

No claim is made that T has no new generators in degree five or higher.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_intermediate_B4_exactly_9.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_J4_equals_Qsat4.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_no_quartic_saturation_generator.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_T4_generated_by_T3.

CLOSED_ALTERNATIVE:
  H01-C5 m=3 with dim_C(S/J)_4=10.

SURVIVING_SUBCASE:
  H01-C5 m=3 with

    dim_C(S/J)_4=9,
    J_3=(Qsat)_3,
    J_4=(Qsat)_4,
    T_4=S_1*T_3,
    dim_C(Q:gamma)_1>=2.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-C5 m=3.
  It does NOT prove J=Qsat in degrees >=5.
  It does NOT prove all of T is generated by eta.
  It does NOT enter H01-C4.
  It does NOT make a tangent-space estimate.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_quartic_reduced.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_excluded.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3.  The cubic class eta generates all of T_4 and has a
  linear annihilator of dimension at least two.  Determine whether the next
  degree forces J_5=(Qsat)_5, or whether a genuinely new degree-five saturation
  generator can occur.  Any proof that no new generator occurs would make the
  cubic defect substantially closer to a finite two-variable colon model.

NEXT_ACTIONS:
  1. Stay only in H01-C5 m=3.
  2. Compute the Macaulay upper bound from dim(S/J)_4=9.
  3. Compare it with the exact core value dim Ccore_5.
  4. Determine whether J_5=(Qsat)_5 is forced or whether one degree-five defect survives.
  5. Stop before H01-C4, tangent estimates, or q<=3.
