Standalone next-smallest finite-deficiency reduction for the homogeneous q=4,
height-two DEPTH-ONE saturated-core branch in the order-13 deviation-two
program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_minimal_deficiency_profile.v
    order13_q4_height2_depth_one_skew_line_tangent_closed.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S homogeneous,
    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    B := S/Q,
    Qsat := saturation(Q),
    T := Qsat/Q = H^0_m(B),
    C0 := S/Qsat,
    dim C0=2,
    depth_m(C0)=1.

Let

    M := H^1_m(C0)

be the deficiency/Rao module of the saturated core.

This file treats only the next-smallest FINITE deficiency stratum

    dim_C M = 2.

No assertion is made here that every depth-one core has finite Rao module, and
no assertion is made that every two-dimensional deficiency profile is realized
by a four-quadric core.

Let

    I := Q+(f,g)

be homogeneous and m-primary, with

    deg(f),deg(g)>=3,

and put

    A := S/I = B/(f,g).

The purpose of this file is one bounded reduction:

  (1) classify every two-dimensional graded deficiency module abstractly;
  (2) compute the corresponding first Koszul homology on the SATURATED core;
  (3) identify the exact transgression that can prevent that class from
      surviving in H_1(f,g;B).

This file does NOT close the full length-two deficiency stratum, because the
finite saturation defect T may absorb some or all of the deficiency through
that transgression.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. ABSTRACT CLASSIFICATION OF A TWO-DIMENSIONAL GRADED DEFICIENCY MODULE
--------------------------------------------------------------------------

Theorem every_length_two_deficiency_is_annihilated_by_m_squared:
  If

    dim_C M=2,

  then

    m^2*M=0.

Proof:
  Since M has finite length and is nonzero, graded Nakayama gives

    m*M != M.

  Hence dim_C(m*M) is zero or one.

  If m*M=0 there is nothing to prove.

  If dim_C(m*M)=1, apply Nakayama to the nonzero finite module m*M.  One cannot
  have

    m*(m*M)=m*M,

  so the proper submodule m^2*M of the one-dimensional vector space m*M must be
  zero.
Qed.

Corollary exact_two_shape_classification:
  Exactly one of the following module-theoretic shapes occurs.

  SEMISIMPLE SHAPE:
    m*M=0, and for some integers a,b

      M ~= C(-a) direct_sum C(-b).

  CYCLIC LENGTH-TWO SHAPE:
    dim_C(m*M)=1.  Then M/m*M and m*M are each one-dimensional, M is generated
    by one homogeneous element, and after a linear change of coordinates and
    a grading shift one may write

      M ~= S/(x2,x3,x4,x1^2)(-a).

    Equivalently its graded Hilbert support is one copy of C in degree a and
    one copy in degree a+1.

Proof:
  In the first case every homogeneous component is a direct sum of residue
  field modules because m acts trivially.

  In the second case M/m*M is one-dimensional.  Graded Nakayama therefore says
  that M is cyclic.  Choose a homogeneous generator u.  The one-dimensional
  space m*M is generated by a nonzero degree-one multiple of u.  Multiplication
  S_1 -> Hom_C(C*u,m*M) is a nonzero linear functional, so after a linear change
  of coordinates x1 has nonzero action and x2,x3,x4 kill u.  The preceding
  theorem gives x1^2*u=0.  This gives exactly the displayed cyclic module.
Qed.

Corollary the_final_high_degree_pair_annihilates_M:
  One has

    f*M=0,
    g*M=0.

Proof:
  The standing degree hypothesis gives f,g in m^3, while m^2*M=0.
Qed.

--------------------------------------------------------------------------
2. MACAULAYFICATION OF THE SATURATED DEPTH-ONE CORE
--------------------------------------------------------------------------

ExternalResult dimension_two_ideal_transform_macaulayfication:
  Let C be a finitely generated standard graded C-algebra of dimension two
  with

    H^0_m(C)=0

  and finite-length H^1_m(C).  Its homogeneous ideal transform / section ring

    D := D_m(C)

  is finite over C and fits into a natural graded exact sequence

    0 -> C -> D -> H^1_m(C) -> 0.

  Moreover

    H^0_m(D)=H^1_m(D)=0,

  so depth_m(D)=2.  Thus D is Cohen--Macaulay of dimension two.

Apply this external result to C0 and put

    D := D_m(C0).

Then

    0 -> C0 -> D -> M -> 0

is exact and D is Cohen--Macaulay of dimension two.

Theorem the_final_pair_is_regular_on_the_macaulayfication:
  The images of f,g in D form a regular sequence.

Proof:
  The saturated-core profile proves that the images of f,g form an m-primary
  parameter pair on C0.

  The module D is finite over C0.  Therefore

    D/(f,g)D

  is finite over C0/(f,g)C0 and hence has finite length.  Thus f,g form a
  homogeneous system of parameters on the two-dimensional ring/module D.

  Since D is Cohen--Macaulay of dimension two, that parameter pair is regular.
Qed.

--------------------------------------------------------------------------
3. EXACT KOSZUL DEFECT ON THE SATURATED CORE
--------------------------------------------------------------------------

Define

    D1_sat := H_1(f,g;C0).

Theorem length_two_Rao_module_is_exactly_the_saturated_core_Koszul_H1:
  There is a natural graded isomorphism

    D1_sat ~= M(-deg(f)-deg(g)).

  In particular

    dim_C D1_sat=2,
    m^2*D1_sat=0.

Proof:
  Apply the two-element Koszul complex K(f,g;-) to

    0 -> C0 -> D -> M -> 0.

  This gives a short exact sequence of complexes.

  The pair f,g is regular on D, so

    H_2(f,g;D)=0,
    H_1(f,g;D)=0.

  The final high-degree pair annihilates M.  Therefore the Koszul differential
  on K(f,g;M) is zero and

    H_2(f,g;M) ~= M(-deg(f)-deg(g)).

  The relevant long exact homology segment is

    0
      -> H_2(f,g;M)
      -> H_1(f,g;C0)
      -> 0.

  This gives the claimed isomorphism.  The annihilation statement follows from
  m^2*M=0.
Qed.

--------------------------------------------------------------------------
4. THE SATURATION TRANSGRESSION IS THE EXACT REMAINING OBSTRUCTION
--------------------------------------------------------------------------

Return to the saturation exact sequence

    0 -> T -> B -> C0 -> 0.

Define

    D1_B := H_1(f,g;B).

Theorem exact_saturation_transgression_sequence:
  There is a natural graded exact sequence

    H_1(f,g;T)
      -> D1_B
      -> M(-deg(f)-deg(g))
      --delta-->
         T/(f,g)T.

  Consequently

    image(D1_B -> M(-deg(f)-deg(g))) = ker(delta).

Proof:
  Apply K(f,g;-) to

    0 -> T -> B -> C0 -> 0

  and take the long exact homology sequence.  The degree-zero Koszul homology of
  T is

    H_0(f,g;T)=T/(f,g)T,

  while the preceding theorem identifies

    H_1(f,g;C0)=M(-deg(f)-deg(g)).

  Substitution gives exactly the displayed segment.
Qed.

Corollary exact_rank_trichotomy_for_the_length_two_deficiency:
  Since the source of delta has C-dimension two, exactly one of

    rank(delta)=0,
    rank(delta)=1,
    rank(delta)=2

  occurs.

  RANK ZERO:
    both saturated-core deficiency classes lie in the image of D1_B.

  RANK ONE:
    exactly one C-dimensional deficiency direction survives in the image of
    D1_B.

  RANK TWO:
    delta is injective, and T/(f,g)T contains a graded two-dimensional submodule
    isomorphic to M(-deg(f)-deg(g)).

Proof:
  This is immediate from exactness and dim_C M=2.  In the rank-two case the
  image of delta is isomorphic to its source as a graded module.
Qed.

Corollary a_complete_absorption_of_the_Rao_defect_forces_a_matching_torsion_tail:
  If no nonzero length-two deficiency class survives from the saturated core to
  D1_B, equivalently if delta is injective, then the saturation defect has a
  quotient modulo (f,g) containing exactly the same two-dimensional graded
  module shape as M, shifted upward by deg(f)+deg(g).

  Thus complete cancellation of the Rao contribution is not free: it requires
  a matching graded tail in T/(f,g)T.
Qed.

--------------------------------------------------------------------------
5. WHY THE TANGENT CLOSURE STOPS HERE
--------------------------------------------------------------------------

The previous skew-line endpoint had T=0.  There the transgression target
vanished, so delta=0 automatically and the residue-field Koszul class survived
fully in H_1(f,g;B).

In the present length-two stratum T is not known to vanish and no universal
high-degree support bound for T has yet been established.  Therefore delta may
have rank zero, one, or two.

Knowing only that the saturated-core module

    M(-deg(f)-deg(g))

is annihilated by m^2 does NOT by itself imply that the full module

    D1_B=H_1(f,g;B)

is annihilated by m^2.  Hence the two-coordinate Hom-carrier theorem cannot yet
be promoted to a universal tangent lower bound for this stratum.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove

    q4_height2_depth_one_length2_deficiency_closed.

  It does NOT prove that delta has rank less than two.

  It does NOT bound the high-degree tail of T.

  It does NOT enter any larger deficiency profile or q<=3 branch.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_tangent_closed.
  q4_height2_depth_one_skew_line_endpoint_closed.
  q4_height2_depth_one_length2_deficiency_classified.
  q4_height2_depth_one_length2_transgression_reduced.
  not q4_height2_depth_one_length2_deficiency_closed.
  not q4_height2_depth_one_core_closed.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Control the graded transgression

    delta:
      M(-deg(f)-deg(g)) -> T/(f,g)T

  in the length-two deficiency stratum.

  The sharp next question is whether the four-quadric height-two presentation
  permits a saturation-torsion tail capable of absorbing both deficiency
  classes.  Equivalently, determine whether rank(delta)=2 is possible.

NEXT_ACTIONS:
  1. Stay only in the finite length-two deficiency stratum.
  2. Use the exact initial data B_0=1, B_1=4, B_2=6 to constrain the grading of M.
  3. Translate those degree constraints through the shift deg(f)+deg(g).
  4. Test whether T/(f,g)T can contain the required rank-two image.
  5. Do not enter length>=3 deficiency or q<=3.
