Standalone Artinian-reduction classification of the remaining H01 endpoint in the
homogeneous q=4, height-two multiplicity-one, depth-one order-13 deviation-two
program.

SCOPE:
  Continue only from the established multiplicity-one residual profile and the
  exclusions/closures of H00, H10, and H11.

Retain

  S := C[x1,x2,x3,x4],
  P := (l1,l2),
  Q subset Qsat subset P,
  D := P/Qsat,

with

  dim D = 1,
  depth_m(D)=1,
  D generated in degree one.

Treat only H01:

  (u1,u2)=(0,2).

Thus

  dim_C D_1 = 2,
  dim_C D_2 = 3,

and for a general D-regular linear form h,

  E := D/hD

has

  dim_C E_1=2,
  dim_C E_2=1.

The earlier Hilbert-floor file only gave

  Hilb_E(t)=2*t+t^2+sum_(n>=3) a_n*t^n,
  a_n>=0.

This file performs one bounded task only: classify the possible higher tail of
E using generation in degree one and commutativity.  The result is that no
branching or later growth is possible: the tail is a single cyclic string of
ones.

No saturation classification is attempted here.
No tangent-space estimate is made.
No q<=3 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. REDUCE TO A THREE-VARIABLE ARTINIAN MODULE
--------------------------------------------------------------------------

Put

  R := S/(h) ~= C[y1,y2,y3].

Since D is generated by D_1, the quotient E=D/hD is generated as a graded
R-module by

  V := E_1,
  dim_C V=2.

Put

  W := E_2,
  dim_C W=1.

Multiplication in degree one gives a C-linear map

  mu : R_1 -> Hom_C(V,W).

Because E is generated in degree one and W is nonzero,

  im(mu) != 0.

Since

  dim_C Hom_C(V,W)=2,

there are only two possibilities:

  rank(mu)=1,
  rank(mu)=2.

--------------------------------------------------------------------------
2. RANK TWO FORCES IMMEDIATE TERMINATION
--------------------------------------------------------------------------

Theorem H01_rank_two_action_kills_E3:
  If rank(mu)=2, then

    E_3=0.

Proof:
  Choose x,y in R_1 such that

    mu_x,
    mu_y

  are linearly independent elements of V^*.

  Choose v_x in V with

    mu_x(v_x) != 0,
    mu_y(v_x) = 0.

  Since W is one-dimensional, x*v_x spans W.  Commutativity gives

    y*(x*v_x)=x*(y*v_x)=0,

  so y kills W.

  Similarly choose v_y with

    mu_y(v_y) != 0,
    mu_x(v_y)=0.

  Then x kills W.

  For arbitrary z in R_1, rank(mu)=2 implies

    mu_z = a*mu_x+b*mu_y

  for some a,b in C.  Since x kills W,

    z*(x*v_x)=x*(z*v_x)=0.

  The vector x*v_x spans W, hence z kills W.

  Therefore

    R_1*W=0.

  Since E is generated by E_1,

    E_3=R_1*E_2=R_1*W=0.
Qed.

Corollary H01_rank_two_exact_Hilbert_numerator:
  If rank(mu)=2, then

    Hilb_E(t)=2*t+t^2.

Proof:
  Once E_3=0, generation in degree one forces E_n=0 for all n>=3.
Qed.

Thus the rank-two action gives the smallest exact H01 residual profile.

--------------------------------------------------------------------------
3. RANK ONE HAS A TWO-DIMENSIONAL LINEAR KERNEL
--------------------------------------------------------------------------

Assume now

  rank(mu)=1.

Choose u in R_1 with

  mu_u != 0

and put

  K := ker(mu) subset R_1.

Then

  dim_C K=2.

Choose e1 in V such that

  u*e1 != 0.

Because W is one-dimensional,

  w2 := u*e1

spans W.

Theorem H01_rank_one_kernel_kills_E2:
  Every k in K annihilates W.

Proof:
  Since k belongs to ker(mu),

    k*e1=0.

  Therefore by commutativity

    k*w2
      = k*(u*e1)
      = u*(k*e1)
      = 0.

  Since w2 spans W, k kills all of W.
Qed.

Corollary H01_rank_one_E3_is_at_most_one_dimensional:
  One has

    E_3 = u*E_2,

so

    dim_C E_3 in {0,1}.

Proof:
  R_1 is spanned by u together with K, and K kills E_2.
Qed.

--------------------------------------------------------------------------
4. THE KERNEL K KILLS THE ENTIRE HIGHER TAIL
--------------------------------------------------------------------------

Theorem H01_rank_one_kernel_kills_all_higher_degrees:
  For every n>=2,

    K*E_n=0.

Proof:
  The n=2 case is the preceding theorem.

  Assume K kills E_n.  Since E is generated in degree one and

    R_1 = C*u + K,

  one has

    E_(n+1)=R_1*E_n=u*E_n.

  For k in K and xi in E_n,

    k*(u*xi)=u*(k*xi)=0

  by commutativity and the induction hypothesis.

  Hence K kills E_(n+1).  Induct on n.
Qed.

Corollary H01_rank_one_tail_is_generated_by_one_variable:
  For every n>=2,

    E_(n+1)=u*E_n.

Consequently

    dim_C E_n <= 1

for every n>=2.
Qed.

--------------------------------------------------------------------------
5. NONZERO HIGHER PIECES CANNOT REAPPEAR AFTER VANISHING
--------------------------------------------------------------------------

Theorem H01_tail_has_no_gaps:
  If E_n=0 for some n>=2, then

    E_j=0

for every j>=n.

Proof:
  This is immediate from generation in degree one:

    E_(n+1)=R_1*E_n=0,

and induction gives all later vanishing.
Qed.

Since E has finite length, there is a largest integer m>=2 such that

  E_m != 0.

By the previous section every nonzero E_n for n>=2 is one-dimensional, and by
no-gap vanishing every degree from two through m is nonzero.

Therefore

  dim_C E_1=2,
  dim_C E_n=1 for 2<=n<=m,
  E_n=0 for n>m.

--------------------------------------------------------------------------
6. EXACT H01 ARTINIAN HILBERT NUMERATOR
--------------------------------------------------------------------------

Theorem q4_H01_exact_Artinian_reduction_Hilbert_classification:
  There exists an integer

    m>=2

such that

    Hilb_E(t)=2*t+t^2+t^3+...+t^m.

No other Hilbert numerator can occur.

More precisely:

  if rank(mu)=2, then m=2;

  if rank(mu)=1, then m>=2 and the entire tail from degree two through degree m
  is a single one-dimensional cyclic string.

Proof:
  Rank two is Section 2.
  Rank one is Sections 3--5.
Qed.

This sharpens the previous coefficientwise floor

  Hilb_E(t)>=(2*t+t^2)

into a complete one-parameter list.

--------------------------------------------------------------------------
7. EXACT RANK-ONE MODULE NORMAL FORM
--------------------------------------------------------------------------

Assume rank(mu)=1 and retain u and K.

Choose a basis

  e0,e1

of V such that

  u*e0=0,
  u*e1=w2 != 0.

Such a basis exists because mu_u:V->W is a nonzero linear functional and
therefore has one-dimensional kernel.

Theorem H01_rank_one_Artinian_module_normal_form:
  After a linear coordinate change in R with

    R=C[u,v,w],
    K=(v,w),

one has a graded R-module isomorphism

    E ~= C(-1) direct_sum C[u]/(u^m)(-1),

where v,w annihilate both summands.

Proof:
  The element e0 is killed by u and by K, hence by the full irrelevant ideal of
  R.  It spans a copy of C(-1).

  The element e1 generates the second summand.  The preceding results give

    u^(j)*e1 != 0 for 0<=j<=m-1,
    u^m*e1=0,

and K kills every term in this string.  Thus the cyclic module generated by e1
is exactly C[u]/(u^m)(-1).

  The two summands are independent already in degree one and together have the
  exact Hilbert function of E, so their direct sum is all of E.
Qed.

Interpretation:
  In the rank-one H01 branch there is one degree-one socle class and one
  curvilinear chain of length m.

--------------------------------------------------------------------------
8. CONSEQUENCES FOR THE ONE-DIMENSIONAL RESIDUAL MODULE D
--------------------------------------------------------------------------

Since h is D-regular,

  Hilb_D(t)=Hilb_E(t)/(1-t).

Corollary H01_exact_residual_Hilbert_series:
  For some m>=2,

    Hilb_D(t)
      = (2*t+t^2+t^3+...+t^m)/(1-t).

Therefore

    dim_C D_1=2,

    dim_C D_n=n+1 for 2<=n<=m,

    dim_C D_n=m+1 for n>=m.
Qed.

Corollary H01_residual_multiplicity:
  One has

    e(D)=m+1>=3.
Qed.

Thus H01 is exactly the multiplicity-one line core together with a projective
zero-dimensional residual module of length m+1, with m>=2.

--------------------------------------------------------------------------
9. DEGREE-TWO SATURATION AGREES WITH THE ORIGINAL FOUR QUADRICS
--------------------------------------------------------------------------

The H01 values u1=0,u2=2 give

  dim_C (Qsat)_2 = 2+u2 = 4.

But Q_2 is already four-dimensional and

  Q_2 subset (Qsat)_2.

Hence

  Q_2=(Qsat)_2.

Corollary H01_has_no_degree_one_or_degree_two_saturation_defect:
  For

    T:=Qsat/Q,

one has

    T_1=0,
    T_2=0.
Qed.

Therefore any H01 saturation defect must begin in degree at least three.

This is the first structural distinction from H00 and H10: the original four
quadrics already exhaust the quadratic part of the saturated core, and all
remaining saturation information is encoded in higher degree.

--------------------------------------------------------------------------
10. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_CLASSIFIED:
  q4_height2_multiplicity_one_depth_one_H01_Artinian_chain_hilbert_profile.
  q4_height2_multiplicity_one_depth_one_H01_rank_one_module_normal_form.
  q4_height2_multiplicity_one_depth_one_H01_Q2_equals_Qsat2.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove that every integer m>=2 is realizable.
  It does NOT prove that rank(mu)=1 can occur for arbitrary m.
  It does NOT classify Qsat from the H01 module.
  It does NOT classify the higher-degree saturation defect T.
  It does NOT make a tangent-space estimate.
  It does NOT close H01 or the full multiplicity-one depth-one branch.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H11_empty.
  q4_height2_multiplicity_one_depth_one_H01_Artinian_chain_classified.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Determine which chain lengths m and which rank-one/rank-two action types are
  compatible with a saturated quotient presentation

    D=P/Qsat,
    Qsat_2=Q_2,

  where Q is generated by exactly four independent quadrics and Qsat/Q has no
  degree-one or degree-two part.

NEXT_ACTIONS:
  1. Stay only in H01.
  2. Use Q_2=(Qsat)_2 and the exact chain parameter m.
  3. Compute the forced number of linear first syzygies of Q from D_3.
  4. Test whether m>=3 forces a multiplicity-two/product configuration.
  5. Stop before q<=3 or tangent estimates.
