Standalone exact tangent theorem for all zero-dimensional almost-complete intersections in the order-13 F_13 semiregularity problem.

This file strengthens order13_monomial_aci_tangent_exact.v.  The preceding local-Artin reduction showed that a local zero-dimensional decoration Q on a smooth fourfold can satisfy the necessary order-13 repair gate only if

  t(Q) := dim_C Hom_R(I_Q,A) <= N - 20,

where A=R/I_Q and N=length_C(A).  It also reduced every possible positive tangent deficit to non-Gorenstein embedding-dimension-four Artin algebras with at least five defining generators.

The present file closes the ENTIRE five-generator branch, not only the monomial subclass.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Setup:
  k := C,
  P is a regular local/analytic k-algebra of embedding dimension m>=2,
  I subset m_P^2 is m_P-primary,
  A := P/I is Artinian of length N and embedding dimension m,
  I is an almost-complete-intersection ideal:

    height(I)=m,
    mu(I)=m+1,

  equivalently I contains a P-regular sequence of length m and is minimally generated by one additional element.

Notation:
  T_i(A) denotes cotangent homology,
  T^i(A) denotes cotangent cohomology.

ExternalResult FundamentalCotangentCohomologySequence:
  For A=P/I there is an exact sequence

    0 -> T^0(A)
      -> Hom_A(Omega^1_{P/k} tensor_P A, A)
      -> Hom_A(I/I^2,A)
      -> T^1(A)
      -> 0.

  Since P is regular of embedding dimension m,

    Omega^1_{P/k} tensor_P A ~= A^m.

  Also

    Hom_A(I/I^2,A) ~= Hom_P(I,A),

  because I annihilates A, so every P-linear map I->A factors uniquely through I/I^2.

ExternalResult AleksandrovArtinianACIEquality:
  If A is a zero-dimensional almost complete intersection of embedding dimension m>=2, then

    dim_k T^1(A) = dim_k T^0(A).

  Source:
    A. G. Aleksandrov,
    Deformations of commutative Artinian algebras,
    Algebra i Analiz 34:6 (2022), 1-33;
    English translation: St. Petersburg Math. J. 34:6 (2023), 889-911,
    Section 7, Theorem 1.

  The same theorem also gives a relation among the lower cotangent groups, but only the displayed cohomology equality is used here.

Theorem all_artinian_ACI_embedded_tangent_dimension_exact:
  Under the setup above,

    dim_k Hom_P(I,A) = m*N.

Proof:
  Take k-dimensions in the fundamental exact sequence:

    dim Hom_A(I/I^2,A)
      = dim Hom_A(Omega^1_{P/k} tensor A,A)
        - dim T^0(A)
        + dim T^1(A).

  The regularity of P gives

    dim Hom_A(Omega^1_{P/k} tensor A,A) = m*N.

  AleksandrovArtinianACIEquality cancels the two cotangent-cohomology terms:

    -dim T^0(A) + dim T^1(A) = 0.

  Therefore

    dim Hom_P(I,A)
      = dim Hom_A(I/I^2,A)
      = m*N.
Qed.

Corollary codim4_five_generator_tangent_dimension_exact:
  Let R=C[[x1,x2,x3,x4]], let I subset m_R^2 be m_R-primary with exactly five minimal generators, and put A=R/I.  Equivalently, R -> A is a minimal Cohen presentation and embdim(A)=4.  Then

    height(I)=4,
    mu(I)=5=height(I)+1,

  so A is a zero-dimensional almost complete intersection of embedding dimension four.  Hence

    dim_C Hom_R(I,A) = 4*length_C(A).
Qed.

Corollary entire_mu5_order13_repair_branch_closed:
  A local order-13 zero-dimensional decoration of length N must satisfy

    t(A) <= N-20

  in order to pass the necessary ideal-sheaf semiregularity dimension gate.

  Every embedding-dimension-four five-generator local algebra, written in its minimal Cohen presentation, satisfies instead

    t(A)=4N.

  Since N>0,

    4N > N-20.

  Therefore NO embedding-dimension-four codimension-four Artinian almost complete intersection can supply positive tangent deficit.  This conclusion is independent of whether the ideal is monomial, homogeneous, smoothable, or non-smoothable.
Qed.

Corollary strengthened_structure_of_any_dangerous_local_component:
  Combine this theorem with order13_artin_local_tangent_reduction.v.

  If a local finite scheme A in a smooth complex fourfold itself satisfies

    dim Hom(I,A) <= length(A)-20,

  then necessarily

    embedding dimension(A) = 4,
    A is non-Gorenstein,
    socle dimension s >= 2,
    mu(I) >= 6

  in its minimal embedding-dimension-four Cohen presentation.

  The socle-generator estimate

    dim Hom(I,A) >= mu(I)*s

  therefore implies

    length(A) >= mu(I)*s + 20 >= 6*2+20 = 32.
Qed.

Relation to the preceding monomial computation:
  order13_monomial_aci_tangent_exact.v independently derived

    t(A)=4*length(A)

  by an explicit Taylor-syzygy/monomial-kernel count for monomial ACIs.  The present theorem subsumes that result and shows that the equality is a structural property of ALL zero-dimensional ACIs, via cotangent cohomology.

Boundary:
  The mu(I)=5 branch in embedding dimension four is closed completely.

  Any surviving local zero-dimensional decoration capable of supplying the required tangent deficit 20 must now be a genuinely higher-deviation Artin algebra:

    embedding dimension = 4,
    non-Gorenstein,
    mu(I) >= 6,
    socle dimension >= 2,
    length >= 32.

  No theorem here proves the required tangent lower bound for arbitrary deviation >=2.

First missing object after this closure:
  either

    (A) prove that every non-Gorenstein embedding-dimension-four Artin algebra with mu(I)>=6 satisfies

          dim Hom(I,A) > length(A)-20,

  or

    (B) construct a concrete higher-deviation local algebra with

          dim Hom(I,A) <= length(A)-20

        and then compute the actual Buchweitz--Flenner semiregularity map for the decorated graph ideal.
