Standalone corrected semiregularity audit for the full order-13 F_13
real-multiplication correspondence.

This file strengthens the earlier graph-only semiregularity obstructions by
including the divisor-product correction C_K from order13_cm_point_on_rm_curve.v.
It is pseudo-formal mathematical documentation and does not assert generic
algebraicity.

Setup:
  X := X_13,
  Y := X x X,
  L1 := U direct_sum <-4> direct_sum <-4>,
  T_L1 := L1^perp in H^2(X,Z),
  F := Q(zeta_13 + zeta_13^(-1)),
  alpha := zeta_13 + zeta_13^(-1).

  Let

    Z_alpha := Graph(sigma) + Graph(sigma^(-1)) + C_K

  be the corrected algebraic rational codimension-two correspondence from
  order13_cm_point_on_rm_curve.v.  Its action on H^2(X,Q) is

    alpha on T_L1,Q,
    2*Id on L1,Q.

  The two graph components contribute coefficient 2 to each of the outer
  Kunneth summands H^0(X) tensor H^4(X) and H^4(X) tensor H^0(X).

ExternalResult CorrespondenceIntersectionTrace:
  For a self-adjoint middle Kunneth class on X x X corresponding to an
  operator A on H^2(X,Q), its middle self-intersection is Tr(A^2).  The two
  outer Kunneth pieces pair only with one another.

Theorem trace_alpha_squared_is_11:
  Tr_F/Q(alpha^2) = 11.

Proof:
  alpha = zeta_13 + zeta_13^(-1), so

    alpha^2 = zeta_13^2 + zeta_13^(-2) + 2.

  The trace to Q of zeta_13^2 + zeta_13^(-2) from the maximal real subfield
  is -1, while Tr_F/Q(2)=12 because [F:Q]=6. Hence the trace is 11.
Qed.

Theorem corrected_alpha_self_intersection_is_57:
  integral_Y [Z_alpha]^2 = 57.

Proof:
  On T_L1,Q, which has F-dimension 3,

    Tr_Q(alpha^2 | T_L1,Q)
      = 3 * Tr_F/Q(alpha^2)
      = 3*11
      = 33.

  On L1,Q, the operator is 2*Id and rank(L1)=4, so

    Tr((2*Id)^2 | L1,Q) = 4*4 = 16.

  Thus the middle Kunneth contribution is

    33 + 16 = 49.

  Each outer Kunneth coefficient is 2.  Their cross-pairing contributes

    2 * 2 * 2 = 8.

  Therefore

    [Z_alpha]^2 = 49 + 8 = 57.
Qed.

ExternalResult CY4RankZeroEulerPairing:
  Let E be a perfect complex on the smooth Calabi-Yau fourfold Y with

    ch_0(E)=0,
    ch_1(E)=0.

  Then Hirzebruch-Riemann-Roch gives

    chi(E,E) = integral_Y ch_2(E)^2.

  Indeed ch_2 is the smallest nonzero possible Chern-character component,
  so no positive-degree Todd term can contribute to total degree eight.

Theorem exact_corrected_class_simple_complex_not_semiregular:
  Suppose E is a simple perfect complex on Y with

    ch_0(E)=0,
    ch_1(E)=0,
    ch_2(E)=[Z_alpha].

  Then

    dim Ext^2_Y(E,E) >= 55.

  Hence E cannot be Buchweitz--Flenner semiregular because the full
  semiregularity target on a K3 product has dimension 44.

Proof:
  By corrected_alpha_self_intersection_is_57 and RR,

    chi(E,E)=57.

  Since K_Y is trivial, Serre duality gives e_4=e_0 and e_3=e_1.  Simplicity
  gives e_0=e_4=1.  Therefore

    57 = 2 - 2*e_1 + e_2,

  so

    e_2 = 55 + 2*e_1 >= 55 > 44.
Qed.

Now remove only algebraically persistent pieces.

Define P_L1 in CH^2(X x X)_Q to be the rational divisor-product
correspondence acting as Id on L1,Q and as zero on T_L1,Q.  It is algebraic
because L1 is generated by divisor classes and its Gram matrix is invertible.
Choose a point p in X and set

  Z_prim := Z_alpha
            - 2*(X x {p})
            - 2*({p} x X)
            - 2*P_L1.

Theorem primitive_normalization_action:
  Z_prim has no outer Kunneth component and its middle action on H^2 is

    alpha on T_L1,Q,
    0 on L1,Q.

  Therefore generic algebraicity of Z_prim is equivalent to generic
  algebraicity of the primitive alpha correspondence, because every
  subtracted term is algebraic throughout the L1-polarized family.
Qed.

Theorem primitive_normalization_self_intersection_is_33:
  integral_Y [Z_prim]^2 = 33.

Proof:
  There are no outer Kunneth pieces.  The middle operator is alpha on the
  F-dimension-3 space T_L1,Q and zero on L1,Q. Hence

    [Z_prim]^2
      = Tr_Q(alpha^2 | T_L1,Q)
      = 3*11
      = 33.
Qed.

Corollary primitive_simple_complex_dimension_window:
  If E is simple with ch_0(E)=ch_1(E)=0 and ch_2(E)=[Z_prim], then

    dim Ext^2(E,E) = 31 + 2*dim Ext^1(E,E).

  Thus the raw 44-dimensional Buchweitz--Flenner target no longer gives an
  automatic dimension contradiction exactly when

    dim Ext^1(E,E) <= 6.

  This is only a numerical window, not a proof of semiregularity.
Qed.

The next point is integral and closes that exact simple rank-zero window.

ExternalResult K3LatticeGluing:
  The integral K3 lattice Lambda=H^2(X,Z) is unimodular.  For a primitive
  sublattice L1 with orthogonal complement T_L1, Lambda is the unimodular
  overlattice of L1 direct_sum T_L1 determined by an anti-isometry of
  discriminant groups

    A_L1 ~= A_T_L1.

  Since U is unimodular and each <-4> contributes Z/4,

    A_L1 ~= (Z/4)^2,

  so A_T_L1 is nonzero of order 16.

Theorem primitive_alpha_tensor_is_not_integral:
  The middle Kunneth class [Z_prim] is not an integral class in

    H^2(X,Z) tensor H^2(X,Z) subset H^4(Y,Z).

Proof:
  Suppose it were integral.  Unimodularity of Lambda identifies integral
  middle tensors with integral endomorphisms of Lambda.  Thus the associated
  operator B would be an integral lattice endomorphism satisfying

    B|L1 = 0,
    B|T_L1,Q = alpha.

  In particular alpha would preserve T_L1 integrally.  The minimal polynomial
  of alpha is

    x^6+x^5-5*x^4-4*x^3+6*x^2+3*x-1,

  whose constant term is -1, so

    Norm_F/Q(alpha) = -1.

  Since T_L1 has F-dimension 3,

    det_Q(alpha | T_L1,Q) = Norm_F/Q(alpha)^3 = -1.

  Therefore an integral alpha on T_L1 would be a lattice automorphism and
  would induce an automorphism of the nonzero discriminant group A_T_L1.

  Now use the unimodular gluing.  A glued element of Lambda has discriminant
  classes (a,phi(a)) in A_L1 direct_sum A_T_L1.  Applying B gives

    (0, alpha*phi(a)).

  For this to lie in Lambda for every a, the gluing condition forces

    alpha*phi(a)=0 in A_T_L1

  for every a.  Since phi is onto, alpha would induce the zero map on
  A_T_L1, contradicting that it is a lattice automorphism of T_L1.

  Hence [Z_prim] is not integral.
Qed.

ExternalResult RankZeroC1ZeroCh2Integrality:
  For a perfect complex E on a smooth variety,

    ch_2(E) = (c_1(E)^2 - 2*c_2(E))/2.

  Hence if ch_0(E)=0 and ch_1(E)=0, then

    ch_2(E) = -c_2(E)

  is integral modulo torsion.

Corollary no_exact_rankzero_c1zero_perfect_complex_for_Zprim:
  There is no perfect complex E with

    ch_0(E)=0,
    ch_1(E)=0,
    ch_2(E)=[Z_prim].

Proof:
  Such ch_2(E) would be integral, contradicting
  primitive_alpha_tensor_is_not_integral.
Qed.

Corollary simple_rankzero_semiregularity_route_closed:
  The corrected order-13 class cannot be spread by the following strategy:

    1. subtract the persistent algebraic Kunneth/L1 pieces;
    2. realize the resulting primitive class exactly as ch_2 of a simple
       rank-zero, c_1=0 perfect complex;
    3. apply Buchweitz--Flenner semiregularity.

  The full corrected class fails the BF dimension bound (57 -> Ext^2 >=55),
  while the primitive normalization enters the numerical window (square 33)
  but is not integral and therefore cannot be ch_2 of any rank-zero c_1=0
  perfect complex exactly.

Important limitation:
  This does NOT rule out:

    - a perfect complex of nonzero rank;
    - a perfect complex with nonzero persistent c_1;
    - a non-simple complex whose deformation theory is controlled by a
      different obstruction mechanism;
    - a cycle-theoretic semiregularity representative not encoded by the
      exact rank-zero c_1=0 Chern-character package;
    - a direct non-similarity algebraic correspondence.

Boundary:
  generic algebraicity of the primitive F_13 generator alpha remains open.

First missing object after this audit:
  a semiregular perfect complex whose Chern character has primitive
  degree-four component proportional to Z_prim but uses nonzero rank and/or
  persistent first Chern class so that the integral/K-theoretic obstruction
  above is avoided without reintroducing a source-dimension obstruction.