Standalone determinantal factorization of the saturated H01 minimal-chain rank-two
endpoint in the homogeneous q=4, height-two multiplicity-one, depth-one
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_R2_betti_frontier.v

  and retain

    S := C[x1,x2,x3,x4],
    Q=(q1,q2,q3,q4)=Qsat,
    B:=S/Q,

with exact minimal resolution

    0
      -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^4
      -> S
      -> B
      -> 0.

Write the second differential as

    A=[L1 L2 L3 Q4],

where L1,L2,L3 are 4-by-1 columns of linear forms and Q4 is a 4-by-1
column of quadratic forms.  Write

    L:=[L1 L2 L3]

for the 4-by-3 linear submatrix.  The final differential has the form

    d3=(a1,a2,a3,r)^T,

with ai quadratic, r linear, r!=0, and

    A*d3=0.

This file performs one bounded task only: identify the maximal minors of L
with the original four quadrics up to the already-forced final linear factor r.

No tangent estimate is made.
No exclusion of H01-M2-R2 is claimed.
No H01-M2-R1 or q<=3 branch is entered.
No Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE THREE LINEAR COLUMNS HAVE GENERIC RANK THREE
--------------------------------------------------------------------------

Let

    K:=Frac(S).

Exactness of the minimal resolution over K gives

    rank_K(A)=3,
    dim_K ker(A_K)=1.

The one-dimensional kernel is generated by the nonzero vector

    (a1,a2,a3,r)^T.

Theorem H01_m2_R2_linear_submatrix_has_rank_three:
  One has

    rank_K(L)=3.

Proof:
  Suppose rank_K(L)<=2. Then L_K has a nonzero right-kernel vector

    v in K^3.

  Hence

    (v,0) in K^4

  is a nonzero vector in ker(A_K).

  But ker(A_K) is one-dimensional and generated by

    (a1,a2,a3,r)^T,

  whose fourth coordinate r is nonzero in K. No nonzero scalar multiple of
  that generator can have fourth coordinate zero. Contradiction.
Qed.

Thus at least one 3-by-3 maximal minor of L is nonzero.

--------------------------------------------------------------------------
2. THE COFACTOR VECTOR IS THE QUADRIC ROW TIMES ONE LINEAR FORM
--------------------------------------------------------------------------

Let

    q:=(q1,q2,q3,q4)

be the row of the four minimal quadratic generators. Since d1*d2=0, the first
three columns give

    q*L=0.

Because rank_K(L)=3, its left kernel over K is one-dimensional.

Let

    Delta=(Delta1,Delta2,Delta3,Delta4)

be the signed cofactor row of L: Deltai is, with the standard alternating sign,
the determinant of the 3-by-3 matrix obtained by deleting row i. Then

    Delta*L=0.

Since rank_K(L)=3, Delta is nonzero and spans the same one-dimensional left
kernel as q. Therefore there is a nonzero rational homogeneous function f with

    Delta=f*q.

Each Deltai has degree three and each qi has degree two, so f has homogeneous
degree one.

Theorem H01_m2_R2_quadric_row_is_primitive:
  The four quadrics q1,q2,q3,q4 have no common nonconstant polynomial factor.

Proof:
  If a nonconstant g divided every qi, then

    Q subset (g),

  so ht(Q)<=1. This contradicts the standing hypothesis ht(Q)=2.
Qed.

Write f=a/b in lowest terms with homogeneous coprime polynomials a,b. From

    Deltai=(a/b)*qi

one has

    b | a*qi

for every i. Since gcd(a,b)=1, b divides every qi. The preceding theorem forces
b to be a unit. Hence f is a polynomial. Degree comparison then gives a nonzero
linear form ell in S_1 such that

    Deltai=ell*qi

for all i, with the chosen cofactor signs.

Theorem H01_m2_R2_maximal_minors_have_linear_factor:
  There exists a nonzero linear form ell such that

    Delta=ell*q.
Qed.

Equivalently,

    I3(L)=(ell)*Q,

where I3(L) denotes the ideal generated by the 3-by-3 maximal minors of L.

--------------------------------------------------------------------------
3. THE FINAL QUADRATIC VECTOR IS NONZERO MODULO r
--------------------------------------------------------------------------

The final syzygy identity is

    L*(a1,a2,a3)^T + r*Q4=0.

Theorem H01_m2_R2_final_quadratic_vector_nonzero_mod_r:
  Not all of a1,a2,a3 belong to the principal ideal (r).

Proof:
  Suppose

    ai=r*bi

  for linear forms bi. Then

    r*(L*(b1,b2,b3)^T+Q4)=0.

  Since S is a domain and r!=0,

    Q4=-L*(b1,b2,b3)^T.

  Thus the degree-four first-syzygy column Q4 is generated by the three
  degree-three first-syzygy columns using linear coefficients. This contradicts
  minimality of the S(-4) summand in the exact minimal free resolution.
Qed.

Therefore the image

    abar:=(a1,a2,a3) mod r

is a nonzero vector over

    Sbar:=S/(r).

--------------------------------------------------------------------------
4. MODULO r THE LINEAR MATRIX DROPS RANK
--------------------------------------------------------------------------

Reducing

    L*a+r*Q4=0

modulo r gives

    Lbar*abar=0

with abar nonzero.

Because r is a nonzero linear form, Sbar is a polynomial ring in three
variables and hence a domain. Passing to Frac(Sbar) gives a nonzero right-kernel
vector of Lbar. Therefore

    rank_Frac(Sbar)(Lbar)<=2.

Theorem H01_m2_R2_maximal_minors_vanish_mod_r:
  Every 3-by-3 maximal minor Deltai of L lies in (r).
Qed.

Equivalently,

    r | Deltai

for every i.

--------------------------------------------------------------------------
5. THE COMMON MINOR FACTOR IS EXACTLY r
--------------------------------------------------------------------------

From Section 2,

    Deltai=ell*qi.

From Section 4,

    r | ell*qi

for every i.

The linear form r is irreducible, hence prime in S. If r did not divide ell,
then r would divide every qi, contradicting primitivity of the quadric row.
Therefore

    r | ell.

Both r and ell are nonzero linear forms, so they differ by a nonzero scalar.
After rescaling the generator of the rank-one final free module S(-5), normalize
that scalar to one.

Theorem H01_m2_R2_final_linear_entry_is_minor_factor:
  After the harmless scalar normalization of the final syzygy generator,

    ell=r.
Qed.

Consequently the signed maximal minors satisfy the exact identities

    Deltai=r*qi

for i=1,2,3,4.

--------------------------------------------------------------------------
6. EXACT DETERMINANTAL FACTORIZATION
--------------------------------------------------------------------------

Theorem H01_m2_R2_determinantal_factorization:
  For the 4-by-3 linear first-syzygy matrix L one has

    I3(L)=(r)*Q.

  Since r is a nonzerodivisor in the polynomial ring S,

    (I3(L):(r))=Q.
Qed.

Thus the original saturated four-quadric ideal is recovered exactly by
removing the unique common linear factor from the maximal-minor ideal of the
three linear first syzygies.

This is stronger than the preceding Betti-table classification but is not an
exclusion: the determinantal configuration itself is not shown to be empty.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_linear_submatrix_rank_three.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_maximal_minor_linear_factor.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_final_quadratic_vector_nonzero_mod_r.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_rank_drop_mod_r.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_determinantal_factorization.

EXACT_FACTORING_IDENTITY:

    I3(L)=(r)*Q,
    (I3(L):(r))=Q.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-M2-R2.
  It does NOT prove that the determinantal matrix is equivalent to a previously
  classified product configuration.
  It does NOT make a tangent-space estimate.
  It does NOT treat H01-M2-R1.
  It does NOT close H01.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_R2_exact_Betti_table.
  H01_m2_R2_determinantal_factorization.
  not H01_m2_R2_closed.
  not H01_m2_R1_closed.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in H01-M2-R2.  Classify the rank-drop matrix

    L mod r

  over S/(r)~=C[y1,y2,y3], where rank(L mod r)<=2 and

    I3(L)=(r)*Q,
    Q=Qsat,
    ht(Q)=2,
    e(S/Q)=1.

  Determine whether this forced determinantal degeneration yields either an
  excluded geometric configuration or a direct tangent carrier.  Do not enter
  H01-M2-R1 before resolving this R2 endpoint.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow run for this commit.
