Standalone trapped-component reduction for the residual nonreduced homogeneous
q=3, height-three complete-intersection core in the order-13 deviation-two
branch.

SCOPE:
  Continue from

    order13_homogeneous_q3_height3_nonreduced_ci_minimal_slice_regular_closed.v.

  Let

    S := C[x1,x2,x3,x4],
    Q := (q1,q2,q3),
    B := S/Q,
    I := Q+(f1,f2,f3),
    L := I/Q subset B,
    A := B/L,

  with B a one-dimensional graded Gorenstein complete intersection of three
  quadrics.  The reduced H3-CI child and the nonreduced regular-minimal-slice
  child are already closed.

  Order the three minimal homogeneous generators of L so that

    d1 <= d2 <= d3,

  where di := deg(fi), and put

    d := d1,
    U := L_d.

  This file treats only the residual case in which every element of U is a zero
  divisor in B.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE MINIMAL SLICE IS TRAPPED IN A MINIMAL PRIME
--------------------------------------------------------------------------

Because B is a one-dimensional complete intersection, it is Cohen--Macaulay
and unmixed. Hence its zero divisors are the union of its finitely many minimal
primes.

By assumption every element of the finite-dimensional C-vector space U is a
zero divisor, so

  U subset union_{p in Min(B)} p.

Over the infinite field C, a finite-dimensional vector space cannot be the
union of finitely many proper linear subspaces. Therefore there exists at least
one minimal prime p with

  U subset p.

Theorem residual_minimal_slice_is_trapped:
  Every residual nonreduced H3-CI candidate admits a minimal prime p of B such
  that U subset p.
Qed.

If all three generators had degree d, then L would be generated by U. Since L
is m-primary, L cannot be contained in a minimal prime, contradicting U subset
p. Thus the equal-degree case is absent, consistently with the preceding
closure theorem.

Consequently the number

  r := number of minimal generators having degree d

satisfies

  r in {1,2}.

Corollary residual_degree_multiplicity_split:
  Every residual nonreduced H3-CI candidate lies in exactly one of

    R1: d1 < d2 <= d3,
    R2: d1 = d2 < d3.
Qed.

--------------------------------------------------------------------------
2. NEGATIVE ENDOMORPHISMS ARE GENERICALLY SUPPORTED ONLY ON TRAPPED COMPONENTS
--------------------------------------------------------------------------

Let

  E := End_B(L),

viewed inside the homogeneous total quotient ring Q(B).

Take a homogeneous

  x in E_{-s},
  s>0.

For every u in U one has

  x*u in L_{d-s}=0,

so

  xU=0.

Let q be a minimal prime with U not subset q. Choose u in U with u notin q.
Then u is a unit in the zero-dimensional local ring B_q. Localizing x*u=0 at q
gives

  x_q=0.

Therefore every negative-degree endomorphism is generically supported only on

  T(U) := { q in Min(B) : U subset q }.

Theorem negative_endomorphisms_live_on_trapped_components:
  For x in E_{<0},

    x_q=0

  at every minimal prime q not in T(U).
Qed.

--------------------------------------------------------------------------
3. m-PRIMARYNESS FORCES AN ESCAPE GENERATOR ON EACH TRAPPED COMPONENT
--------------------------------------------------------------------------

Fix q in T(U).

Because L is m-primary and q is a minimal prime,

  L not subset q.

Hence at least one of the higher-degree minimal generators lies outside q.
Define

  e_q := min { di : fi notin q }.

Since U subset q,

  e_q > d.

For q in T(U), the chosen generator f_{j(q)} of degree e_q becomes a unit in
B_q.

In the R2 case d1=d2<d3, both minimal-degree generators lie in every trapped
prime, so necessarily

  e_q=d3

for each q in T(U).

--------------------------------------------------------------------------
4. FINITE DEGREE-WINDOW FOR THE NEGATIVE DEFECT
--------------------------------------------------------------------------

Set

  D := max_{q in T(U)} (e_q-d).

Take x in E_{-s} with s>D.

At every q in T(U), choose the escape generator f_{j(q)} of degree e_q. Since

  e_q-s < d,

and d is the least degree in which L is nonzero,

  x*f_{j(q)} in L_{e_q-s}=0.

But f_{j(q)} is a unit in B_q, so

  x_q=0.

Section 2 already gives x_q=0 at every minimal prime outside T(U). Thus x
vanishes after localization at every minimal prime of B.

Because B is unmixed and Q(B) embeds in the product of its total quotient
rings at the minimal primes, this forces

  x=0.

Therefore

  E_{-s}=0 for every s>D.

Theorem residual_negative_defect_has_finite_degree_window:
  Every residual nonreduced H3-CI candidate satisfies

    E_n=0 for n < -D,

  where

    D=max_{q in T(U)}(e_q-d).
Qed.

In particular, in the R2 case

  D=d3-d1.

Thus the only possible negative-degree defect is concentrated in the explicit
finite window

  -D <= n <= -1.

--------------------------------------------------------------------------
5. UPDATED FRONTIER
--------------------------------------------------------------------------

RESULT:
  residual_nonreduced_H3_CI_negative_defect_localized_to_trapped_components
  and finite degree window.

IMPORTANT_NONCONCLUSION:
  This does not bound the total dimension delta_neg by eight.
  It does not prove delta_neg-epsilon_L<=7.
  It does not close R1 or R2.
  It does not close the full nonreduced H3-CI child.
  It does not close H2-CM, H2-NCM, homogeneous q=3, q<=2, or Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  The residual nonreduced H3-CI obstruction is now supported only on minimal
  components containing the least-degree generator slice and only in finitely
  many negative degrees determined by escape-generator degree gaps.

MISSING_OBJECT:
  In R1 and R2, compare the finite trapped-component negative filtration

    direct_sum_{s=1..D} E_{-s}

  with Ext^1_B(L,L), strongly enough to prove

    delta_neg - epsilon_L <= 7.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow for this commit.
  2. If green, attack R2 first: d1=d2<d3, where every trapped component has the
     same escape degree d3 and D=d3-d1.
  3. Identify the successive negative layers with annihilator/colon layers on
     the trapped generic Artin rings.
  4. Pair repeated lowering layers with self-extension classes rather than
     trying to bound delta_neg alone.
  5. Do not promote the H3-CI parent until R1 and R2 are both closed.