Standalone second J-adic-layer classification for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_conormal_classification.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    R := S/J ~= C[z,w],
    n := (z,w) subset R,
    Q subset J,
    T := J/Q,

  where Q is minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T has finite length.

  The first conormal quotient is

    E := T/J*T ~= J/(Q+J^2),

  and the preceding file proves exactly two cases:

    r=4: Hilb_E(t)=2*t and n*E=0,
    r=3: Hilb_E(t)=2*t+t^2 and n^2*E=0.

  This file classifies only the next layer

    F := J*T / J^2*T.

  The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Put

  U := R_1 = Span_C{z,w},
  V := J_1 = Span_C{l1,l2}.

Then

  J/J^2 ~= R tensor V,
  J^2/J^3 ~= R tensor Sym^2(V).

Write the four quadratic generators as

  q_j = L_j + h_j,

where

  L_j in U tensor V

is the first J-adic initial form and

  h_j in Sym^2(V)

is its pure J^2 component.

Let

  W := Span_C{L_1,L_2,L_3,L_4} subset U tensor V.

The first-layer rank is

  r=dim_C(W) in {3,4}.

Theorem exact_second_layer_quotient:
  There is a natural graded R-module identification

    F
      ~= J^2 / (J^3 + (Q intersect J^2)).

  In particular F is generated in ordinary degree two by the image of

    Sym^2(V).

Proof:
  Since T=J/Q,

    J*T=(J^2+Q)/Q

  and

    J^2*T=(J^3+Q)/Q.

  Taking the quotient and restricting the numerator to J^2 gives

    F ~= J^2/(J^3+(Q intersect J^2)).

  The ideal J^2 is generated in degree two, and modulo J^3 its degree-two
  generators are exactly Sym^2(V).
Qed.

Lemma tensor_hyperplane_switch_in_dimension_two:
  Let U and V be two-dimensional C-vector spaces and let

    W subset U tensor V

  be a hyperplane.  Suppose

    Sym^2(U) tensor V = U*W,

  where U*W denotes the image of multiplication in the U-factor.
  Then

    U tensor Sym^2(V) = V*W.

Proof:
  A hyperplane W is the kernel of a nonzero bilinear form

    phi in U^* tensor V^*.

  If phi had rank one, choose nonzero u in ker(U -> V^*) and nonzero v with
  phi(-,v)=0.  Then the class of u tensor v would survive the first quotient,
  and multiplication by a suitable nonzero element of U would give a nonzero
  class in

    (Sym^2(U) tensor V)/(U*W),

  contradicting the hypothesis.  Hence phi has rank two.

  After independent basis changes in U and V, W therefore has the normal form

    W = Span_C{
          z tensor l1,
          w tensor l1 + z tensor l2,
          w tensor l2
        }.

  Multiplying these three tensors by l1 and l2 gives

    z tensor l1^2,
    z tensor l1*l2,
    w tensor l1^2 + z tensor l1*l2,
    w tensor l1*l2 + z tensor l2^2,
    w tensor l1*l2,
    w tensor l2^2.

  These span all six basis tensors of

    U tensor Sym^2(V).

  Therefore V*W=U tensor Sym^2(V).
Qed.

Theorem four_relation_case_second_layer:
  Assume r=4.  Then

    F ~= C(-2)^3

  as a graded R-module.  Equivalently,

    Hilb_F(t)=3*t^2,
    dim_C F=3,
    n*F=0.

Proof:
  The preceding first-layer classification gives

    E ~= C(-1)^2

  as an R-module, so the image of the four first initial forms is exactly

    W=U tensor V.

  Let s be any element of Sym^2(V), and let u be z or w.  It is enough to show

    u*s=0 in F.

  Every pure tensor u tensor v in U tensor V is a C-linear combination of the
  L_j.  Choose q in Q whose first J-adic initial form is u*v.  Multiplying q by
  the remaining V-factor of s gives an element of Q whose class modulo J^3 is
  u*s.  Hence

    n*Sym^2(V) maps to zero in F.

  Therefore n*F=0.

  Since r=4, the preceding file proves

    Q_2 intersect J^2_2 = 0.

  Thus no nonzero constant relation occurs among the three degree-two basis
  vectors of Sym^2(V).  Consequently

    dim_C F_2=dim_C Sym^2(V)=3.

  Because F is generated in degree two and n annihilates it, no higher degree
  survives, proving the result.
Qed.

Theorem three_relation_case_second_layer:
  Assume r=3.  Then

    F ~= C(-2)^2

  as a graded R-module.  Equivalently,

    Hilb_F(t)=2*t^2,
    dim_C F=2,
    n*F=0.

Proof:
  Now W is a hyperplane in U tensor V.  The preceding first-layer resolution
  gives

    Hilb_{E(1)}(t)=2+t.

  Hence the degree-two part of E(1) vanishes.  Since E(1) is presented by the
  three degree-one relations W, this is exactly the statement

    Sym^2(U) tensor V = U*W.

  Apply the tensor_hyperplane_switch_in_dimension_two lemma to obtain

    U tensor Sym^2(V)=V*W.

  Each element of V*W is the second J-adic initial form of a V-multiple of an
  element of Q.  Therefore every element of

    n*Sym^2(V)

  maps to zero in F, so

    n*F=0.

  In the r=3 case the preceding file proves

    dim_C(Q_2 intersect J^2_2)=1.

  Let

    0 != h in Sym^2(V)

  span this intersection.  It gives exactly one constant degree-two relation
  in F.  Therefore

    dim_C F_2
      = dim_C Sym^2(V)-1
      = 3-1
      = 2.

  Since F is generated in degree two and n annihilates it, no higher degree
  survives.
Qed.

Corollary exact_second_J_adic_layer_dichotomy:
  The next transverse layer is completely classified:

    r=4:
      Hilb_{J*T/J^2*T}(t)=3*t^2,
      length_C(J*T/J^2*T)=3;

    r=3:
      Hilb_{J*T/J^2*T}(t)=2*t^2,
      length_C(J*T/J^2*T)=2.

  Universally,

    n*(J*T/J^2*T)=0.
Qed.

Corollary longitudinal_action_pushes_one_layer_deeper:
  In both cases,

    n*(J*T) subset J^2*T.

  Together with the first-layer classification this gives

    r=4:
      n*T subset J*T,
      n*(J*T) subset J^2*T;

    r=3:
      n^2*T subset J*T,
      n*(J*T) subset J^2*T.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove a uniform exponent k with

    J^k*T=0.

  It also does not classify

    J^2*T/J^3*T.

  The new annihilation

    n*(J*T/J^2*T)=0

  controls longitudinal motion along the saturated line, but it does not by
  itself stop repeated transverse multiplication by l1,l2.  Finite length says
  the transverse tower eventually ends for each Q, but a uniform bound still
  requires a new argument from the lifted quadratic relations h_j and their
  higher J-adic compatibility.

  No tangent-gate contradiction is claimed here.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Determine whether the lifted quadratic relations h_j force a uniform bound
  on the third and deeper transverse layers

    J^2*T/J^3*T,
    J^3*T/J^4*T,
    ... .

  In particular, classify the induced pure-transverse relations produced by
  first-layer syzygies after one further J-adic lift, and test whether they
  force a bounded nilpotence exponent for J acting on T.

NEXT_BOUNDED_OBJECT:
  Compute only

    J^2*T/J^3*T

  in the r=4 and r=3 cases from the lifted syzygies of the normalized first
  relation matrix.  Do not enter the depth-one deficiency branch.