Standalone homogeneous quadratic-generator reduction for the order-13 deviation-two local-Artin search.

SCOPE:
  This file applies only to the graded/homogeneous six-generator branch, where I is a homogeneous m-primary ideal and phrases such as I_2, quadratic generator, and degree are literal homogeneous degrees.

  It does NOT prove the analogous statements for an arbitrary nonhomogeneous local Artin ideal whose minimal generators merely have m-adic order two.  In particular, the unrestricted local mu(I)=6 deviation-two frontier remains open outside this homogeneous branch.

Within this stated scope, the file excludes six genuine quadratic generators and identifies the geometry forced when the maximal surviving quadratic count is five.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Homogeneous setup:
  k := C,
  P := k[x1,x2,x3,x4] localized at the homogeneous maximal ideal m (or the equivalent graded calculation before localization),
  I subset P is homogeneous and m-primary,
  A := P/I is graded Artinian,
  embedding dimension(A)=4,
  mu(I)=6,
  length(A)=N>=32.

Notation:
  q := dim_k I_2,
  equivalently the number of minimal homogeneous quadratic generators because embedding dimension four implies I has no linear generators.

ExternalResult GenericQuadraticReduction:
  Let J be an m-primary homogeneous ideal in k[x1,x2,x3,x4] generated in degree two.  Since k is infinite and the polynomial ring is Cohen--Macaulay of dimension four, four sufficiently general k-linear combinations of the quadratic generators form a homogeneous system of parameters, hence a regular sequence of four quadrics.

  Therefore there exists a complete-intersection ideal

    K=(q1,q2,q3,q4) subseteq J

  with deg(qi)=2, and

    length(P/J) <= length(P/K)=2^4=16.

ExternalResult PrincipalIdealHeightBound:
  For a Noetherian ring and an ideal Q,

    ht(Q+(f)) <= ht(Q)+1.

  This is the standard one-generator form of Krull's height theorem.

Theorem homogeneous_six_quadratic_generators_cannot_reach_order13_length_frontier:
  Assume all six minimal homogeneous generators of I are quadrics.

  Then I is generated in degree two.  Since A=P/I is Artinian, I is m-primary.  Apply GenericQuadraticReduction to obtain four quadratic linear combinations q1,...,q4 in I forming a regular sequence.

  Hence

    N=length(P/I) <= length(P/(q1,q2,q3,q4))=16,

  contradicting N>=32.

  Therefore, in this homogeneous branch, not all six minimal generators can be quadratic.
Qed.

Corollary homogeneous_branch_at_most_five_quadratic_generators:
  q <= 5.
Qed.

Corollary homogeneous_branch_second_Hilbert_value_at_least_five:
  Since dim_k P_2=10 and dim_k I_2=q,

    h_2(A)=dim_k A_2=10-q >= 5.
Qed.

Theorem homogeneous_five_quadratic_core_has_height_three:
  Assume q=5 and let

    Q := (I_2) subset P

  be the homogeneous ideal generated by the five minimal quadrics.  Since mu(I)=6 and no further quadratic generator exists, homogeneity gives

    I = Q + (f)

  for one homogeneous generator f with deg(f)>=3.

  Then

    ht(Q)=3.

Proof:
  Because I is m-primary in the four-dimensional regular local ring P,

    ht(I)=4.

  PrincipalIdealHeightBound applied to I=Q+(f) gives

    4=ht(I) <= ht(Q)+1,

  so

    ht(Q)>=3.

  Suppose ht(Q)=4.  Then Q is m-primary.  It is generated entirely by homogeneous quadrics, so GenericQuadraticReduction gives four quadratic linear combinations inside Q forming a regular sequence K with

    length(P/Q) <= length(P/K)=16.

  Since Q subset I,

    N=length(P/I) <= length(P/Q) <=16,

  contradicting N>=32.

  Hence ht(Q) is not 4.  Combined with ht(Q)>=3, this forces

    ht(Q)=3.
Qed.

Corollary homogeneous_five_quadratic_case_is_one_dimensional_core_plus_final_cut:
  Under q=5,

    dim(P/Q)=1,

  and the sixth homogeneous generator f of degree at least three raises the height from three to four, producing

    A = (P/Q)/(f).

  Thus the maximal-quadratic-count homogeneous branch is a single higher-degree hypersurface cut of a one-dimensional five-quadric core.
Qed.

Corollary classical_H143_elementary_component_cannot_compress_to_homogeneous_mu6:
  A homogeneous Artin algebra with Hilbert function

    (1,4,3)

  has

    dim I_2 = 10-3 = 7.

  Because there are no degree-one generators, all seven independent quadrics are minimal.  Hence every such homogeneous algebra has mu(I)>=7.

  Therefore the classical homogeneous H=(1,4,3) locus cannot remain in that Hilbert stratum while dropping to mu(I)=6.
Qed.

Literature context:
  Cartwright--Erman--Velasco--Viray, Hilbert schemes of 8 points, Algebra Number Theory 3 (2009), identify the second component of Hilb^8(A^4) as the local homogeneous Hilbert-function (1,4,3) locus.

  This source is used only for the historical/nonsmoothable-component context.  The seven-quadrics count itself is elementary dimension arithmetic.

Homogeneous frontier after this reduction:
  A homogeneous dangerous order-13 six-generator algebra must satisfy the previously established local requirements and, additionally,

    q<=5,
    h_2(A)>=5.

  In its maximal q=5 homogeneous subcase:

    I=Q+(f),
    Q generated by five homogeneous quadrics,
    ht(Q)=3,
    dim(P/Q)=1,
    f homogeneous with deg(f)>=3.

UNRESTRICTED_LOCAL_BOUNDARY:
  No statement in this file proves q<=5, h_2>=5, or the height-three-core description for an arbitrary nonhomogeneous local Artin ideal.

  The unrestricted local frontier therefore remains the earlier one:

    embedding dimension(A)=4,
    mu(I)=6,
    deviation(I)=2,
    A non-Gorenstein,
    A nonmonomial,
    A nonsmoothable,
    socle dimension(A)>=2,
    length(A)=N>=32,
    dim Hom_P(I,A)<=N-20.

Next bounded object inside the homogeneous branch:
  combine the height-three five-quadric description with the regular-final-cut tangent obstruction, while keeping the nonhomogeneous local branch explicitly separate.