Standalone quadratic classification of the embedding-dimension-two colon in the
exact H10 endpoint of the homogeneous q=4, height-two multiplicity-one,
depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H10_quadratic_subspace_reduction.v
    order13_q4_height2_depth_one_multiplicity_one_H10_incidence_realizability.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Qsat=Q+(l1),
    T:=Qsat/Q,
    C:=(Q:l1),

with

    C m-primary,
    dim_C C_1=2,
    T ~= S/C(-1).

The H10 incidence is known to have two realizable forms, OFF and ON.  This file
performs one bounded task only: determine the full generating degrees of C and
classify the resulting two-variable quadratic Artinian quotient.

No tangent-space estimate is made.
No H00, H01, or H11 branch is entered.
No q<=3 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. COMMON NORMALIZATION OF THE FOUR-PLANE
--------------------------------------------------------------------------

Put

    A:=C_1=(Q:l1)_1.

The previous quadratic-subspace reduction proves

    dim_C A=2,
    Q_2 intersect l1*S_1 = l1*A.

In either H10 incidence, the quotient

    (Qsat)_2 / l1*S_1

is two-dimensional, and Q_2 surjects onto it.  Therefore one may choose two
quadrics q1,q2 in Q_2 whose images form a basis of that quotient, so that

    Q_2 = l1*A direct_sum C*q1 direct_sum C*q2.

Because Q is generated by Q_2,

    Q=(l1*A,q1,q2).

The precise non-l1 parts of q1,q2 depend on the incidence.

--------------------------------------------------------------------------
2. H10-OFF: THE COLON IS GENERATED BY ONE LINEAR PAIR AND THREE QUADRICS
--------------------------------------------------------------------------

In H10-OFF choose coordinates

    S=C[x,y,z,w],
    l1=x,
    l2=y,

with

    Qsat=(x,yz,yw).

Then one may choose linear forms alpha,beta in S_1 such that

    qz := yz + x*alpha,
    qw := yw + x*beta,

and

    Q_2 = x*A direct_sum C*qz direct_sum C*qw.

Define the quadratic syzygy defect

    hoff := w*alpha - z*beta.

Theorem H10_OFF_basic_syzygy_defect_lies_in_C:
  One has

    hoff in C=(Q:x).

Proof:
  The identity

    w*qz-z*qw
      = w*(yz+x*alpha)-z*(yw+x*beta)
      = x*(w*alpha-z*beta)
      = x*hoff

lies in Q.  Hence hoff belongs to (Q:x).
Qed.

Theorem H10_OFF_colon_is_generated_in_degrees_one_and_two:
  One has

    C=(A,qz,qw,hoff).

Proof:
  The inclusion from right to left is immediate:

    A subset C

by definition of A=C_1,

    qz,qw in Q subset C,

and hoff lies in C by the preceding theorem.

  For the reverse inclusion, let h be a homogeneous element of C of degree

    n>=2.

  Since x*h lies in Q and Q is generated by its four quadrics, there exist

    u in A*S_(n-1),
    r,s in S_(n-1)

  such that

    x*h = x*u + r*qz + s*qw.

  Reduce modulo x.  In

    S/(x)=C[y,z,w]

  one obtains

    0 = rbar*(y*z)+sbar*(y*w)
      = y*(z*rbar+w*sbar).

  The ring C[y,z,w] is a domain, so

    z*rbar+w*sbar=0.

  The syzygy module on the pair (z,w) is generated by (w,-z).  Hence there is

    cbar in C[y,z,w]_(n-2)

  such that

    rbar=w*cbar,
    sbar=-z*cbar.

  Lift cbar to c in S_(n-2).  Then

    r=w*c+x*r1,
    s=-z*c+x*s1

  for some r1,s1 in S_(n-2).

  Substitute:

    r*qz+s*qw
      = c*(w*qz-z*qw)+x*r1*qz+x*s1*qw
      = x*(c*hoff+r1*qz+s1*qw).

  Therefore

    x*h=x*(u+c*hoff+r1*qz+s1*qw).

  Since S is a domain, cancel x and obtain

    h=u+c*hoff+r1*qz+s1*qw.

  Thus h lies in (A,qz,qw,hoff).
Qed.

--------------------------------------------------------------------------
3. H10-ON: THE SAME THREE-QUADRIC COLON PATTERN
--------------------------------------------------------------------------

In H10-ON choose coordinates

    S=C[x,y,z,w],
    l1=x,
    l2=y,

with

    Qsat=(x,y^2,yz).

Choose linear forms alpha,beta in S_1 such that

    q0 := y^2 + x*alpha,
    q1 := y*z + x*beta,

and

    Q_2 = x*A direct_sum C*q0 direct_sum C*q1.

Define

    hon := z*alpha-y*beta.

Theorem H10_ON_basic_syzygy_defect_lies_in_C:
  One has

    hon in C=(Q:x).

Proof:
  The identity

    z*q0-y*q1
      = z*(y^2+x*alpha)-y*(yz+x*beta)
      = x*(z*alpha-y*beta)
      = x*hon

lies in Q.
Qed.

Theorem H10_ON_colon_is_generated_in_degrees_one_and_two:
  One has

    C=(A,q0,q1,hon).

Proof:
  As before the displayed generators all lie in C.

  Let h in C be homogeneous of degree n>=2.  Write

    x*h=x*u+r*q0+s*q1

with

    u in A*S_(n-1),
    r,s in S_(n-1).

  Reducing modulo x gives

    0=rbar*y^2+sbar*y*z
     =y*(y*rbar+z*sbar)

in the domain C[y,z,w].  Thus

    y*rbar+z*sbar=0.

  The syzygy module on (y,z) is generated by (z,-y), so for some lift

    c in S_(n-2)

one may write

    r=z*c+x*r1,
    s=-y*c+x*s1.

  Then

    r*q0+s*q1
      =c*(z*q0-y*q1)+x*r1*q0+x*s1*q1
      =x*(c*hon+r1*q0+s1*q1).

  Cancelling x gives

    h=u+c*hon+r1*q0+s1*q1.

  Hence C=(A,q0,q1,hon).
Qed.

--------------------------------------------------------------------------
4. QUOTIENT BY THE TWO LINEAR COLON DIRECTIONS
--------------------------------------------------------------------------

The two incidence calculations have the same formal consequence.

Let

    R:=S/A.

Since A consists of two independent linear forms,

    R ~= C[s,t]

as a standard graded polynomial ring in two variables.

Let

    Cbar:=C/A subset R.

Corollary H10_colon_reduction_is_generated_by_quadrics:
  The ideal Cbar is generated entirely in degree two by at most three
  quadrics.

More precisely, in H10-OFF it is generated by the images of

    qz,qw,hoff,

and in H10-ON by the images of

    q0,q1,hon.

Proof:
  This is immediate from the two exact colon-generation theorems after quotient
  by A.
Qed.

Corollary Cbar_is_m_primary:
  The ideal Cbar is the homogeneous maximal-primary ideal of R.

Proof:
  C is m-primary in S and contains A.  Therefore

    S/C ~= R/Cbar

has finite length.  Thus Cbar is (s,t)-primary.
Qed.

--------------------------------------------------------------------------
5. ONLY TWO QUADRATIC ARTINIAN QUOTIENTS CAN OCCUR
--------------------------------------------------------------------------

Put

    kappa:=dim_C (Cbar)_2.

Because R_2 has dimension three,

    0<=kappa<=3.

Theorem H10_quadratic_colon_rank_is_two_or_three:
  One has

    kappa in {2,3}.

Proof:
  The ideal Cbar is generated by quadrics and is (s,t)-primary.

  If kappa=0, then Cbar=0, which is not primary to (s,t).

  If kappa=1, then Cbar is generated by one nonzero homogeneous quadratic.
  Its radical has height one, so R/Cbar has positive dimension and cannot have
  finite length.

  Hence kappa>=2.  Since dim R_2=3, only kappa=2 or3 remain.
Qed.

Theorem H10_kappa_three_is_the_square_of_the_maximal_ideal:
  If kappa=3, then

    Cbar=(s,t)^2

and

    Hilb_(R/Cbar)(t)=1+2*t.

Proof:
  Three-dimensionality means

    (Cbar)_2=R_2.

  Since Cbar is generated in degree two, it equals the ideal generated by R_2,
  namely (s,t)^2.  The quotient has basis 1,s,t.
Qed.

Theorem H10_kappa_two_is_a_quadratic_complete_intersection:
  If kappa=2, then Cbar is generated by two linearly independent quadrics with
  no common linear factor.  Consequently it is a complete intersection of type

    (2,2)

and

    Hilb_(R/Cbar)(t)=1+2*t+t^2.

Proof:
  Choose a basis f,g of (Cbar)_2.  Since Cbar is generated in degree two,

    Cbar=(f,g).

  If f and g had a common nonconstant factor, then their common factor would be
  linear and the radical of (f,g) would have a height-one component.  This would
  contradict (s,t)-primaryness.

  Therefore gcd(f,g)=1.  In the two-variable polynomial ring R, the pair f,g is
  a regular sequence.  Hence Cbar is a complete intersection of degrees two and
  two.

  Its Hilbert series is

    ((1-t^2)^2)/(1-t)^2=(1+t)^2=1+2*t+t^2.
Qed.

Corollary exact_H10_colon_Hilbert_dichotomy:
  Exactly one of the following occurs.

  SHORT COLON:
    Cbar=(s,t)^2,
    Hilb_(S/C)(t)=1+2*t,
    length_C(S/C)=3.

  LONG COLON:
    Cbar is a (2,2) complete intersection,
    Hilb_(S/C)(t)=1+2*t+t^2,
    length_C(S/C)=4.
Qed.

--------------------------------------------------------------------------
6. THE SATURATION DEFECT HAS ONLY TWO POSSIBLE HILBERT SERIES
--------------------------------------------------------------------------

Recall the exact cyclic presentation

    T ~= S/C(-1).

Theorem exact_H10_saturation_defect_Hilbert_dichotomy:
  Exactly one of

    Hilb_T(t)=t+2*t^2

or

    Hilb_T(t)=t+2*t^2+t^3

occurs.

Proof:
  Shift the two Hilbert series of S/C upward by one degree.
Qed.

Corollary H10_torsion_length_is_three_or_four:
  One has

    length_C(T) in {3,4}.
Qed.

Corollary universal_H10_cubic_nilpotence:
  One has

    m^3*T=0.

Proof:
  In the short case S/C is killed by m^2.
  In the long (2,2)-complete-intersection case its Hilbert support stops in
  degree two, so m^3*(S/C)=0.  Transfer through the grading shift.
Qed.

IMPORTANT_NONCONCLUSION:
  The present file does NOT decide whether both colon Hilbert cases occur in
  both incidence classes.

  It does NOT classify the two-dimensional quadratic subspace in the complete
  intersection case up to coordinates.

  It does NOT make a tangent-space estimate.
  It does NOT close H10.
  It does NOT close the multiplicity-one branch, q=4 height two, or order 13.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H10_colon_generated_in_degrees_1_2.
  q4_height2_multiplicity_one_depth_one_H10_colon_quadratic_rank_2_or_3.
  q4_height2_multiplicity_one_depth_one_H10_torsion_Hilbert_two_case.
  q4_height2_multiplicity_one_depth_one_H10_m3T_zero.
  not q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Propagate the universal H10 bound

    m^3*T=0

through the final two-cut Koszul sequence and determine whether it forces a
large enough annihilator in

    H_1(f,g;S/Q)

to violate the order-13 tangent gate.

NEXT_ACTIONS:
  1. Stay only in H10.
  2. Use m^3*T=0 and the exact saturated residual line-plus-point/embedded-point
     structure.
  3. Compute the annihilator of the full first Koszul homology after f,g.
  4. Derive the strongest two-copy Hom carrier.
  5. Stop if the order-13 tangent gate is not forced to fail.
