Standalone Hilbert-floor refinement for the remaining multiplicity-one,
depth-one saturated core in the homogeneous q=4, height-two branch of the
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_residual_profile.v

  and retain its notation

    S := C[x1,x2,x3,x4],
    P := (l1,l2),
    Q subset Qsat subset P,
    D := P/Qsat,
    T := Qsat/Q,

  with

    dim D = 1,
    depth_m(D)=1,
    dim D_1 = 2-u1,
    dim D_2 = 5-u2,
    dim T_1 = u1,
    dim T_2 = u2-2,

  and

    u1 in {0,1},
    u2 <= 3+u1.

This file performs one bounded task only: it determines the smallest Hilbert
numerator permitted by the exact degree-one/degree-two data in each remaining
(u1,u2) case.  It does not claim that every lower-envelope case is realized by
an actual four-quadric ideal, and it makes no tangent-space deduction.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE RESIDUAL MODULE IS GENERATED IN DEGREE ONE
--------------------------------------------------------------------------

Theorem residual_module_is_generated_in_degree_one:
  The graded S-module D=P/Qsat is generated by D_1.

Proof:
  The linear prime P=(l1,l2) is generated by its degree-one part.  Since D is a
  quotient of P, the images of l1,l2 generate D.  Any linear member of Qsat
  simply removes the corresponding degree-one generator.  Hence D is generated
  by D_1.
Qed.

Corollary minimal_number_of_residual_generators:
  The minimal number of degree-one generators is

    dim_C D_1 = 2-u1.

  Thus

    u1=0  =>  D has two degree-one generators,
    u1=1  =>  D has one degree-one generator.
Qed.

--------------------------------------------------------------------------
2. HILBERT NUMERATOR FROM A REGULAR LINEAR FORM
--------------------------------------------------------------------------

Choose a linear nonzerodivisor h on the one-dimensional Cohen--Macaulay module
D and put

  E:=D/hD.

Then E has finite length and, because D is generated in degree one, E is also
generated in degree one.

Theorem residual_Hilbert_series_is_the_Artinian_reduction_numerator:
  One has

    Hilb_D(t)=Hilb_E(t)/(1-t).

  Moreover

    dim E_1 = dim D_1 = 2-u1,

    dim E_2 = dim D_2-dim D_1
            = (5-u2)-(2-u1)
            = 3+u1-u2.

Proof:
  Since h is D-regular there is an exact sequence

    0 -> D(-1) --times h--> D -> E -> 0.

  Taking Hilbert series gives

    Hilb_E(t)=(1-t)Hilb_D(t).

  Because D_0=0, the degree-one identity is immediate.  The degree-two identity
  is the first difference of the Hilbert function.
Qed.

Corollary the_second_numerator_coefficient_is_small:
  The exact possibilities are

    u1=0:
      u2 in {2,3},
      dim E_2 in {1,0};

    u1=1:
      u2 in {2,3,4},
      dim E_2 in {2,1,0}.

Proof:
  The lower bound u2>=2 follows from Q_2 subset (Qsat)_2 and the four-dimensional
  space Q_2 of independent quadrics.  Combine this with u2<=3+u1 and the formula
  dim E_2=3+u1-u2.
Qed.

--------------------------------------------------------------------------
3. ONCE THE ARTIAN REDUCTION VANISHES, IT STAYS ZERO
--------------------------------------------------------------------------

Theorem zero_in_one_degree_forces_zero_in_all_later_degrees:
  If E_n=0 for some n>=1, then E_m=0 for every m>=n.

Proof:
  The module E is generated in degree one.  Therefore every degree m>1 is
  obtained by multiplying lower-degree elements by positive-degree elements of
  S.  If E_n=0, then

    E_(n+1)=S_1 E_n=0,

  and induction gives all later vanishing.
Qed.

This elementary point makes the cases with dim E_2=0 exact rather than merely
lower bounds.

--------------------------------------------------------------------------
4. EXACT CASE L0 WITH u2=3
--------------------------------------------------------------------------

Theorem L0_u2_3_has_exact_Hilbert_series:
  If

    u1=0,
    u2=3,

  then

    Hilb_E(t)=2*t

  and therefore

    Hilb_D(t)=2*t/(1-t).

  Equivalently,

    dim_C D_n=2

  for every n>=1.

Proof:
  Here

    dim E_1=2,
    dim E_2=0.

  The preceding vanishing theorem kills every E_n for n>=2.  Substitute into
  Hilb_D=Hilb_E/(1-t).
Qed.

Corollary L0_u2_3_has_residual_multiplicity_two:
  In this case

    e(D)=2.
Qed.

--------------------------------------------------------------------------
5. LOWER ENVELOPE FOR L0 WITH u2=2
--------------------------------------------------------------------------

Theorem L0_u2_2_Hilbert_floor:
  If

    u1=0,
    u2=2,

  then

    Hilb_E(t)=2*t+t^2+sum_{n>=3} a_n t^n

  with every a_n>=0.  Hence coefficientwise

    Hilb_D(t) >= (2*t+t^2)/(1-t).

Proof:
  The exact low-degree formulas give

    dim E_1=2,
    dim E_2=1.

  All later Artinian-reduction dimensions are nonnegative.  Dividing by 1-t
  gives the coefficientwise Hilbert-series floor.
Qed.

IMPORTANT_NONCONCLUSION_L0_u2_2:
  No claim is made here that all higher a_n vanish.  Thus the displayed floor
  is the smallest Hilbert numerator allowed by the current information, not an
  existence or classification theorem.

--------------------------------------------------------------------------
6. EXACT CASE L1 WITH u2=4
--------------------------------------------------------------------------

Theorem L1_u2_4_has_exact_Hilbert_series:
  If

    u1=1,
    u2=4,

  then

    Hilb_E(t)=t

  and therefore

    Hilb_D(t)=t/(1-t).

  Equivalently,

    dim_C D_n=1

  for every n>=1.

Proof:
  Here

    dim E_1=1,
    dim E_2=0.

  Generatedness in degree one forces all later E_n to vanish.  The Hilbert
  series follows.
Qed.

Corollary L1_u2_4_has_residual_multiplicity_one:
  In this case

    e(D)=1.
Qed.

--------------------------------------------------------------------------
7. LOWER ENVELOPES FOR THE OTHER L1 CASES
--------------------------------------------------------------------------

Theorem L1_u2_3_Hilbert_floor:
  If

    u1=1,
    u2=3,

  then

    Hilb_E(t)=t+t^2+sum_{n>=3} b_n t^n

  with every b_n>=0.  Hence coefficientwise

    Hilb_D(t) >= (t+t^2)/(1-t).
Qed.

Theorem L1_u2_2_Hilbert_floor:
  If

    u1=1,
    u2=2,

  then

    Hilb_E(t)=t+2*t^2+sum_{n>=3} c_n t^n

  with every c_n>=0.  Hence coefficientwise

    Hilb_D(t) >= (t+2*t^2)/(1-t).
Qed.

IMPORTANT_NONCONCLUSION_L1:
  The higher coefficients b_n and c_n have not been classified.  Their
  vanishing is not inferred from the low-degree data alone.

--------------------------------------------------------------------------
8. EXACT FIVE-WAY HILBERT FRONTIER
--------------------------------------------------------------------------

Corollary multiplicity_one_depth_one_residual_Hilbert_frontier:
  The remaining multiplicity-one depth-one branch has exactly five initial
  numerical Hilbert alternatives:

    H00:
      (u1,u2)=(0,3),
      Hilb_D(t)=2*t/(1-t).

    H01:
      (u1,u2)=(0,2),
      Hilb_D(t)>=(2*t+t^2)/(1-t) coefficientwise.

    H10:
      (u1,u2)=(1,4),
      Hilb_D(t)=t/(1-t).

    H11:
      (u1,u2)=(1,3),
      Hilb_D(t)>=(t+t^2)/(1-t) coefficientwise.

    H12:
      (u1,u2)=(1,2),
      Hilb_D(t)>=(t+2*t^2)/(1-t) coefficientwise.

  No sixth pair (u1,u2) is compatible with the already proved bounds.
Qed.

--------------------------------------------------------------------------
9. SHARP BOUNDARY
--------------------------------------------------------------------------

The previous two coarse alternatives

  u1=0
  u1=1

are now refined to five exact initial Hilbert states.  Two states have fully
forced Hilbert series because their Artinian reductions vanish in degree two:

  (u1,u2)=(0,3)  =>  Hilb_D=2*t/(1-t),
  (u1,u2)=(1,4)  =>  Hilb_D=t/(1-t).

The other three states have sharp low-degree Hilbert floors but may still carry
higher Artinian-reduction tails.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove that any of the five states is realized by an actual
  saturated ideal arising from four independent quadrics.

  It does NOT classify the annihilator of D, does NOT classify the saturation
  defect T beyond degrees one and two, and makes no tangent-space estimate.

  Therefore it does not close the multiplicity-one depth-one branch, the full
  q=4 height-two branch, or the full order-13 frontier.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_Hilbert_frontier_five_states.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Use the containment

    Q subset Qsat subset P

  and the fact that Q has exactly four independent quadratic generators to
  determine which of the five Hilbert states can actually occur, starting with
  the two exact-series endpoints H00 and H10.

NEXT_BOUNDED_OBJECT:
  Test only H10, the smallest cyclic residual endpoint

    (u1,u2)=(1,4),
    Hilb_D=t/(1-t).

  Derive the exact colon presentation of D and Qsat forced by one surviving
  degree-one generator.  Stop before tangent-space estimates.
