Standalone degree-five reduction for the unique surviving H01-C5 chain value
m=3 in the homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_quartic_forced.v

  and retain

    S = C[x1,x2,x3,x4],
    Q = (q1,q2,q3,q4),
    B = S/Q,
    Qsat = Q^sat,
    Ccore = S/Qsat,
    T = Qsat/Q,

  together with the H01-C5 state

    m = 3,
    sigma = 5,
    tau_3 = 1.

Choose a cubic

    gamma in (Qsat)_3

whose class spans (Qsat)_3/Q_3, and define

    J := Q + (gamma).

The preceding file proves

    J_3 = (Qsat)_3,
    J_4 = (Qsat)_4,

and therefore

    dim_C(S/J)_3 = 8,
    dim_C(S/J)_4 = 9.

It also proves that the entire quartic saturation layer is generated by the
cubic class eta = gamma + Q:

    T_4 = S_1 * eta.

This file performs one bounded task only: push the same intermediate ideal J
through degree five.  The degree-five value is forced to equal the saturated
core, so there is no independent quintic saturation generator and

    T_5 = S_2 * eta.

No degree-six persistence argument is entered here.
No H01-C4, tangent estimate, q<=3 branch, or full order-13 closure is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXACT SATURATED-CORE VALUE IN DEGREE FIVE
--------------------------------------------------------------------------

For m=3 the H01 residual module has Hilbert series

    Hilb_D(t) = (2*t + t^2 + t^3)/(1-t).

Hence

    dim_C D_n = 4

for every n>=3.  In particular

    dim_C D_5 = 4.

The exact line-quotient sequence is

    0 -> D -> Ccore -> S/P -> 0,

where

    S/P ~= C[s,t].

The line ring has

    dim_C C[s,t]_5 = 6.

Therefore:

Theorem H01_C5_m3_exact_core_degree_five:
  One has

    dim_C Ccore_5 = 10.

Proof:
  Take degree five in the line-quotient sequence:

    dim Ccore_5
      = dim D_5 + dim C[s,t]_5
      = 4 + 6
      = 10.
Qed.

--------------------------------------------------------------------------
2. THE INTERMEDIATE QUOTIENT HAS DEGREE-FIVE VALUE TEN OR ELEVEN
--------------------------------------------------------------------------

The preceding quartic file gives

    dim_C(S/J)_4 = 9.

Since

    J subset Qsat,

there is a graded surjection

    S/J -> S/Qsat = Ccore.

Therefore

    dim_C(S/J)_5 >= dim_C Ccore_5 = 10.

Now compute the fourth Macaulay successor of nine.

The degree-four Macaulay representation is

    9 = binom(5,4) + binom(4,3)
      = 5 + 4.

Hence

    9^{<4>}
      = binom(6,5) + binom(5,4)
      = 6 + 5
      = 11.

Macaulay growth for the standard graded algebra S/J gives

    dim_C(S/J)_5 <= 11.

Thus:

Theorem H01_C5_m3_quintic_two_value_frontier:
  One has

    dim_C(S/J)_5 in {10,11}.
Qed.

--------------------------------------------------------------------------
3. THE VALUE ELEVEN WOULD FORCE MULTIPLICITY TWO
--------------------------------------------------------------------------

Assume for contradiction that

    dim_C(S/J)_5 = 11.

Then

    dim_C(S/J)_4 = 9,
    dim_C(S/J)_5 = 11 = 9^{<4>}.

Thus S/J has maximal Macaulay growth from degree four to degree five.

The ideal J is generated in degrees at most three: Q is generated by four
quadrics and gamma is cubic.  In particular J is generated in degrees at most
four, so standard Gotzmann persistence applies to the equality above.

Theorem H01_C5_m3_quintic_eleven_Gotzmann_profile:
  Under the assumption dim_C(S/J)_5=11, one has

    dim_C(S/J)_n = 2*n + 1

  for every n>=4.

Proof:
  At degree four,

    9 = 2*4 + 1
      = binom(5,4) + binom(4,3).

  Its Macaulay successor is

    binom(6,5) + binom(5,4)
      = 6 + 5
      = 11
      = 2*5 + 1.

  Once equality holds, Gotzmann persistence propagates the same two-term
  Macaulay pattern.  At degree d>=4,

    2*d + 1
      = binom(d+1,d) + binom(d,d-1),

  whose successor is

    binom(d+2,d+1) + binom(d+1,d)
      = (d+2) + (d+1)
      = 2*d + 3
      = 2*(d+1) + 1.

  Induction gives the stated formula.
Qed.

Corollary H01_C5_m3_quintic_eleven_forces_multiplicity_two:
  Under the same assumption,

    dim(S/J) = 2

  and

    e(S/J) = 2.

Proof:
  The eventual Hilbert function is the linear polynomial

    2*n + 1.

  Therefore the quotient has Krull dimension two and multiplicity equal to the
  slope two.
Qed.

--------------------------------------------------------------------------
4. SATURATION FORCES MULTIPLICITY ONE
--------------------------------------------------------------------------

The inclusions

    Q subset J subset Qsat

imply

    J^sat = Qsat.

Indeed, Q subset J gives

    Q^sat subset J^sat,

so

    Qsat subset J^sat.

Conversely, J subset Qsat and Qsat is saturated, so

    J^sat subset Qsat.

Hence equality holds.

Saturation changes a homogeneous ideal only by irrelevant-primary finite-length
data, so S/J and S/J^sat have the same Hilbert polynomial and multiplicity.
Therefore

    e(S/J)
      = e(S/J^sat)
      = e(S/Qsat)
      = 1,

using the standing multiplicity-one H01 hypothesis.

This contradicts the multiplicity-two conclusion obtained from the hypothetical
value eleven.

Therefore:

Theorem H01_C5_m3_quintic_value_eleven_is_impossible:
  One has

    dim_C(S/J)_5 != 11.
Qed.

--------------------------------------------------------------------------
5. THE DEGREE-FIVE VALUE IS FORCED TO TEN
--------------------------------------------------------------------------

Combine the two-value frontier with the exclusion of eleven.

Theorem H01_C5_m3_exact_intermediate_degree_five:
  One has

    dim_C(S/J)_5 = 10.
Qed.

But the saturated core has exactly the same degree-five value:

    dim_C(S/Qsat)_5 = dim_C Ccore_5 = 10.

The inclusion

    J_5 subset (Qsat)_5

therefore induces a surjection between two ten-dimensional quotient spaces,
so it is an isomorphism.

Theorem H01_C5_m3_intermediate_matches_saturation_in_degree_five:
  One has

    J_5 = (Qsat)_5.
Qed.

Corollary H01_C5_m3_no_new_quintic_saturation_generator:
  The saturated ideal Qsat has no new minimal degree-five generator modulo
  J=Q+(gamma).
Qed.

--------------------------------------------------------------------------
6. THE ENTIRE QUINTIC TORSION LAYER COMES FROM THE CUBIC CLASS
--------------------------------------------------------------------------

Let

    eta := gamma + Q in T_3.

Since J is generated from Q by gamma,

    J_5 = Q_5 + S_2*gamma.

The preceding theorem gives

    J_5 = (Qsat)_5.

Therefore

    T_5
      = (Qsat)_5 / Q_5
      = J_5 / Q_5
      = (Q_5 + S_2*gamma)/Q_5
      = S_2*eta.

Thus:

Theorem H01_C5_m3_entire_quintic_torsion_generated_by_cubic:
  One has

    T_5 = S_2*T_3.
Qed.

Together with the preceding quartic result,

    T_4 = S_1*T_3,

we now know that the unique cubic saturation class generates all saturation
torsion through degree five.

IMPORTANT:
  This file does not claim that T is globally cyclic in every degree.  A new
  minimal saturation generator could, a priori, first appear in degree six or
  higher.  That possibility is deliberately left for the next bounded step.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_exact_core_degree_five.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_SJ5_equals_10.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_J5_equals_Qsat5.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_T5_generated_by_T3.

CURRENT_C5_STATUS:
  H01-C5 with m>=4 is empty.
  H01-C5 with m=3 remains open but Qsat/Q is generated by its unique cubic class
  through degrees three, four, and five.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-C5 with m=3.
  It does NOT prove all of T is cyclic.
  It does NOT enter degree six.
  It does NOT enter H01-C4.
  It does NOT make a tangent-space estimate.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_quintic_reduced.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 with m=3 and push J one degree further.  The exact core
  degree-six value is eleven.  Starting from

    dim_C(S/J)_5 = 10,

  compare the fifth Macaulay successor with that core value.  Determine whether
  J_6=(Qsat)_6 and whether the resulting equality triggers a multiplicity-one
  Gotzmann persistence profile that makes the entire saturation defect cyclic.

NEXT_ACTIONS:
  1. Stay only in H01-C5 with m=3.
  2. Compute dim_C Ccore_6 and 10^{<5>}.
  3. Determine J_6 versus (Qsat)_6.
  4. If equality is forced, test Gotzmann persistence from degrees five to six.
  5. Stop before H01-C4, tangent estimates, or q<=3.
