Standalone rank-two saturated-core reduction for the multiplicity-two subbranch of
the homogeneous q=4, height-three order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e1_split_torsion_closed.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=2,
    deg(f),deg(g)>=3.

  Put

    T := H^0_m(B)=Qsat/Q,
    Cbar := B/T.

  The saturated-core profile proves that the unique multiplicity-two linear
  Artin-reduction h-vector is

    (1,1),

  and that Cbar is a one-dimensional Cohen--Macaulay graded algebra free over a
  general Noether parameter C[ell] with graded module structure

    Cbar ~= C[ell] direct_sum C[ell](-1).

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
does not assert generic F_13 algebraicity.

The purpose of this file is to classify that rank-two core, sharpen its finite
saturation-torsion budget, close the subcase in which only one final generator
is active on the saturated core, and reduce the two-core-active case to two
explicit normal forms.  It does NOT close the whole e=2 branch.

Theorem multiplicity_two_saturated_core_is_a_quadratic_rank_two_algebra:
  Choose a homogeneous degree-one lift u in Cbar_1 of the nontrivial basis
  element of Cbar/ell*Cbar.  Then Cbar is generated as a graded C-algebra by
  ell and u, and there are constants a,b in C such that

    Cbar ~= C[ell,u]/(u^2-b*ell*u-a*ell^2).

Proof:
  The C[ell]-module profile gives

    Cbar_n = C*ell^n direct_sum C*ell^(n-1)*u

  for every n>=1.  In particular ell and u generate Cbar as an algebra.

  Since u^2 has degree two, there are unique constants a,b with

    u^2=a*ell^2+b*ell*u.

  This gives a graded surjection

    C[ell,u]/(u^2-b*ell*u-a*ell^2) -> Cbar.

  The source is free of rank two over C[ell] with basis 1,u, exactly as Cbar is.
  The surjection therefore has zero kernel and is an isomorphism.
Qed.

Corollary only_split_or_double_line_core_occurs:
  After replacing

    v:=u-(b/2)*ell,

  there is a constant Delta in C with

    Cbar ~= C[ell,v]/(v^2-Delta*ell^2).

  Because C is algebraically closed, exactly the following two algebra types
  occur:

    REDUCED_SPLIT:
      Cbar ~= C[x,y]/(x*y).

    DOUBLE_LINE:
      Cbar ~= C[ell,v]/(v^2).

Proof:
  Completing the square gives the displayed relation.

  If Delta=0 this is the double-line algebra.

  If Delta is nonzero, choose c in C with c^2=Delta and put

    x:=v-c*ell,
    y:=v+c*ell.

  Then x*y=0, while ell and v are C-linear combinations of x and y.  Hence the
  algebra is C[x,y]/(xy).
Qed.

Corollary multiplicity_two_core_Hilbert_function:
  One has

    dim_C Cbar_0=1,
    dim_C Cbar_n=2 for every n>=1.

  Moreover multiplication by ell is an isomorphism

    ell:Cbar_n -> Cbar_(n+1)

  for every n>=1.
Qed.

Retain the complete-intersection section model

  R:=S/(q1,q2,q3),
  J:=(a)R,
  B=R/J,
  Jsat:=saturation(J),
  Cbar=R/Jsat,
  X:=Proj(R).

Then X has length eight and

  dim R_1=4,
  dim R_2=7,
  dim R_n=8 for n>=3.

Theorem multiplicity_two_degree_three_torsion_has_dimension_at_most_four:
  One has

    dim_C T_3<=4.

Proof:
  Since dim Cbar_3=2 and dim R_3=8,

    dim Jsat_3=6.

  The ordinary degree-three piece is

    J_3=a*R_1.

  On X, multiplication by the quadratic section a gives a map

    H^0(X,O_X(1)) -> H^0(X,O_X(3)).

  Its cokernel is H^0(Y,O_Y(3)), where

    Y:=Proj(Cbar)

  has length two.  Source and target both have dimension eight, so the kernel
  has dimension two.

  The natural map R_1->H^0(X,O_X(1)) is injective because R is
  one-dimensional Cohen--Macaulay.  Hence the kernel of

    a:R_1->R_3

  has dimension at most two.  Since dim R_1=4,

    dim J_3>=2.

  Therefore

    dim T_3=dim(Jsat_3/J_3)<=6-2=4.
Qed.

Corollary multiplicity_two_total_embedded_torsion_has_length_at_most_eleven:
  One has

    dim T_1=2,
    dim T_2=4,
    dim T_3<=4,
    dim T_4<=1,

  and consequently

    length_C(T)<=11.

Proof:
  The first two equalities follow from the h-vector (1,1) in the saturated-core
  profile.  The degree-four bound was proved in the conormal-rank reduction.
  Combine them with the preceding degree-three bound and T_n=0 outside degrees
  one through four.
Qed.

Now inspect the two original homogeneous final minimal generators f,g.  Say a
final generator is CORE-ACTIVE if its image in Cbar is nonzero.

Theorem one_core_active_multiplicity_two_subcase_is_closed:
  Suppose exactly one of f,g is core-active.  Then this subcase cannot satisfy
  the necessary order-13 tangent gate.

Proof:
  Call the core-active generator h, put n:=deg(h), and call the other generator
  k.  Then

    k in T,

  so deg(k) belongs to {3,4}.

  Since A is finite length and k has zero image in Cbar, the principal ideal

    hbar*Cbar

  is m-primary.  In the one-dimensional Cohen--Macaulay ring Cbar this makes
  hbar a homogeneous nonzerodivisor.

  Therefore

    length_C(Cbar/hbar*Cbar)=2*n.

  The exact torsion/core quotient sequence gives

    N=2*n+kappa

  with

    0<=kappa<=length(T)<=11.

  Since N>=32,

    n>=ceil((32-11)/2)=11.

  Hence h lies in m^11, in particular in m^4.  Since m^4*T=0,

    h*T=0.

  If h*b=0 in B, regularity of hbar on Cbar forces bbar=0, so b lies in T.
  Thus

    0:_B h=T.

  Likewise, if h*b lies in T then hbar*bbar=0, hence b lies in T and therefore
  h*b=0.  Consequently

    hB intersect T=0.

  Since kB is contained in T,

    hB intersect kB=0.

  Thus for

    L=(h,k)B

  one has a B-linear direct sum

    L=hB direct_sum kB.

  The extension

    0 -> hB -> L -> L/hB -> 0

  therefore splits.  Its connecting homomorphism is zero, so the connecting
  excess epsilon from the conormal-rank reduction satisfies

    epsilon<=0.

  But every dangerous order-13 candidate must satisfy epsilon>=6.  This is a
  contradiction.
Qed.

From now on suppose both f and g are core-active.  After relabeling assume

  d:=deg(f)<=D:=deg(g).

Theorem regular_lower_core_cut_forces_equal_degrees:
  Suppose fbar is a nonzerodivisor on Cbar.  Then any candidate with N>=32 and
  six minimal generators must satisfy

    d=D>=11.

  Moreover fbar and gbar are linearly independent in Cbar_d and

    (fbar,gbar)=ell^(d-1)*m_Cbar.

  Consequently

    length_C(Cbar/(fbar,gbar))=2*d-1.

Proof:
  Regularity gives

    length(Cbar/fbar*Cbar)=2*d.

  Since adding g can only decrease the saturated-core quotient length and the
  torsion correction has length at most eleven,

    N<=2*d+11.

  Thus N>=32 implies d>=11.

  The Hilbert series of Cbar is

    (1+t)/(1-t).

  Hence for a regular degree-d element,

    Hilb_(Cbar/fbar*Cbar)
      =(1-t^d)*(1+t)/(1-t),

  whose graded pieces vanish in every degree strictly larger than d.

  If D>d, then gbar belongs to fbar*Cbar.  Choose a homogeneous lift c in B of
  the required quotient coefficient.  Since

    D>=d+1>=12>=5

  and T_D=0, the relation modulo T lifts exactly to

    g=c*f

  in B.  This makes g redundant modulo Q, contradicting minimality.  Therefore

    D=d.

  If fbar and gbar were linearly dependent in Cbar_d, their difference after a
  constant scalar change would lie in T_d=0 because d>=11.  Again one final
  generator would be redundant.  Hence they are independent.

  Multiplication by ell^(d-1) identifies Cbar_1 with Cbar_d.  Thus there are
  independent F,G in Cbar_1 with

    fbar=ell^(d-1)*F,
    gbar=ell^(d-1)*G.

  Since dim Cbar_1=2 and Cbar is standard graded, F,G generate m_Cbar.  Hence

    (fbar,gbar)=ell^(d-1)*m_Cbar.

  This ideal contains every graded piece of degree at least d and none below
  degree d.  Therefore

    length(Cbar/(fbar,gbar))
      = dim Cbar_0 + sum_(n=1)^(d-1) dim Cbar_n
      = 1+2*(d-1)
      = 2*d-1.
Qed.

Theorem zerodivisor_lower_core_cut_has_exact_length_shape:
  Suppose fbar is a zerodivisor on Cbar.  Then

    length_C(Cbar/(fbar,gbar))=d+D-1.

  In particular every N>=32 candidate in this subcase satisfies

    d+D>=22.

Proof:
  Use the split/double-line classification.

  REDUCED_SPLIT:
    Write

      Cbar=C[x,y]/(xy).

    In every positive degree n, Cbar_n has basis x^n,y^n.  A nonzero
    homogeneous zerodivisor has support on exactly one component.  After
    interchanging x and y and rescaling,

      fbar=x^d.

    Because (fbar,gbar) is m-primary, the y^D coefficient of gbar is nonzero.
    Write

      gbar=c*x^D+b*y^D,

    with b nonzero.  Since D>=d, x^D already lies in (x^d).  Therefore

      (fbar,gbar)=(x^d,y^D),

    and a vector-space basis of the quotient is

      1,
      x,...,x^(d-1),
      y,...,y^(D-1).

    Its length is

      1+(d-1)+(D-1)=d+D-1.

  DOUBLE_LINE:
    Write

      Cbar=C[ell,v]/(v^2).

    A homogeneous element of degree d is a zerodivisor exactly when its
    ell^d coefficient vanishes.  After rescaling,

      fbar=ell^(d-1)*v.

    Since (fbar,gbar) is m-primary, gbar must avoid the unique minimal prime
    (v), so its ell^D coefficient is nonzero.  Write

      gbar=b*ell^D+c*ell^(D-1)*v,

    with b nonzero.

    Because D>=d, the second term belongs to (ell^(d-1)*v).  Thus the quotient
    has basis

      1,ell,...,ell^(D-1),
      v,ell*v,...,ell^(d-2)*v,

    of total length

      D+(d-1)=d+D-1.

  Finally the original quotient A fits into

    0 -> T/(T intersect (f,g)B)
      -> A
      -> Cbar/(fbar,gbar)
      -> 0.

  Hence

    N<=d+D-1+length(T)<=d+D+10.

  Since N>=32,

    d+D>=22.
Qed.

Interpretation:
  The e=2 branch has no unclassified saturated-core algebra.  The core is
  either two reduced lines or one doubled line, and the embedded torsion has
  length at most eleven.

  The one-core-active case is closed by the same split-extension mechanism as
  e=1.

  Every remaining two-core-active candidate lies in exactly one of two
  numerical/core shapes:

    REGULAR_LOWER:
      d=D>=11,
      (fbar,gbar)=ell^(d-1)*m_Cbar,
      length(Cbar/(fbar,gbar))=2*d-1.

    ZERODIVISOR_LOWER:
      d<=D,
      d+D>=22,
      length(Cbar/(fbar,gbar))=d+D-1,
      with the explicit split-line or double-line normal forms above.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove the connecting-rank excess is at most five in the
  two-core-active cases.  Therefore it does NOT close the full multiplicity-two
  branch.

  It makes no claim for e=3,4,5, the q=4 height-two branch, homogeneous q<=3,
  or the unrestricted nonhomogeneous local deviation-two frontier.

BOUNDARY:
  The first remaining e=2 obstruction is the finite Koszul-colon carrier P in
  the two-core-active normal forms above.  A dangerous candidate still has to
  satisfy

    dim_C Hom_A(P,A)-dim_C(0:_A(h:k))>=6.

NEXT_BOUNDED_OBJECT:
  compute P separately in the REGULAR_LOWER and ZERODIVISOR_LOWER normal forms.
  First quotient by the embedded torsion T and prove the saturated-core Hom
  excess is nonpositive or explicitly bounded.  Then isolate the T-supported
  correction.  Stop at the first normal form whose correction can reach six.
