Standalone tangent closure for the remaining multiplicity-two Type-B
non-finite-Rao profile in the homogeneous q=4, height-two DEPTH-ONE branch of
the order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_length2_deficiency_empty.v
    order13_q4_height2_depth_one_double_line_tangent_closed.v

  and retain

    S := C[x1,x2,x3,x4],
    Jlin := (a1,a2,a3),

  where a1,a2,a3 are independent linear forms, x is a linear form, and

    q in Jlin \ (x)

  is quadratic.  The Type-B ideal is

    Q := (a1*x,a2*x,a3*x,q)
       = x*Jlin + (q),

  and

    B := S/Q.

The preceding multiplicity-two four-quadric classification isolates this as the
remaining Type-B profile.  Its height-three associated prime Jlin survives on
the punctured spectrum, so its saturated depth-one core has non-finite Rao
module.  This file does NOT try to classify that Rao module.

Instead it uses the exact colon

    (Q:x)=Jlin

and the multiplication-by-x sequence to compute the final two-cut Koszul H1
through the one-variable module S/Jlin.  This gives a large annihilator directly
and closes the Type-B tangent gate.

Let

    I := Q+(f,g)

be homogeneous and m-primary, with

    d:=deg(f)>=3,
    e:=deg(g)>=3,

and put

    A := S/I = B/(f,g),
    N := length_C(A)>=32.

The order-13 repair route requires the necessary tangent gate

    t(A):=dim_C Hom_S(I,A) <= N-20.

This file proves that Type B cannot satisfy that gate.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXACT COLON AND ONE-DIMENSIONAL SUBMODULE
--------------------------------------------------------------------------

Theorem typeB_exact_colon_by_x:
  One has

    (Q:x)=Jlin.

Proof:
  Certainly Jlin subset (Q:x), because x*Jlin subset Q.

  Conversely suppose r*x belongs to Q.  Write

    r*x = x*j + q*b

  with j in Jlin.  Then

    x*(r-j)=q*b.

  Since q is not in the principal prime (x), x does not divide q.  The
  polynomial ring S is a UFD, so gcd(x,q)=1 and x divides b.  Write b=x*c.
  Cancelling x gives

    r-j=q*c.

  Since q belongs to Jlin, the right side belongs to Jlin, so r belongs to
  Jlin.  Hence (Q:x)=Jlin.
Qed.

Put

    K:=S/Jlin.

Because Jlin is generated by three independent linear forms in a polynomial
ring in four variables,

    K ~= C[t]

as a standard graded C-algebra.

Corollary multiplication_by_x_gives_an_exact_TypeB_extension:
  There is a graded exact sequence

    0 -> K(-1)
      --times x-->
      B
      -> R
      -> 0,

  where

    R:=S/(x,q).

Proof:
  The standard multiplication-by-x exact sequence for S/Q is

    0 -> S/(Q:x)(-1)
      --times x-->
      S/Q
      -> S/(Q,x)
      -> 0.

  The colon theorem identifies the left term with K(-1).  Also

    Q+(x)=(x,q),

  because the three generators x*a_i already lie in (x).  Thus the right term
  is R.
Qed.

Theorem the_TypeB_curve_quotient_is_a_multiplicity_two_CM_conic_ring:
  The ring

    R=S/(x,q)

  is a two-dimensional Cohen--Macaulay complete intersection of multiplicity
  two.

Proof:
  The linear form x is a nonzerodivisor in S.  Modulo x, the quadric q remains
  nonzero because q is not in (x).  Since S/(x) is a polynomial domain, q mod x
  is a nonzerodivisor.  Hence x,q form a regular sequence.

  Therefore dim R=2 and R is Cohen--Macaulay.  Its multiplicity is

    1*2=2.
Qed.

--------------------------------------------------------------------------
2. THE FINAL PARAMETER PAIR IS REGULAR ON THE CONIC QUOTIENT
--------------------------------------------------------------------------

Theorem final_pair_is_regular_on_R:
  The images f_R,g_R of f,g in R form a regular sequence.

Proof:
  The quotient map B->R induces a surjection

    A=B/(f,g) -> R/(f_R,g_R).

  Since A has finite length, R/(f_R,g_R) has finite length.  Thus f_R,g_R form
  a homogeneous system of parameters on the two-dimensional ring R.

  Since R is Cohen--Macaulay, every parameter pair is a regular sequence.
Qed.

Corollary conic_Koszul_homology_vanishes_in_positive_degree:
  One has

    H_2(f,g;R)=0,
    H_1(f,g;R)=0.
Qed.

--------------------------------------------------------------------------
3. EXACT REDUCTION OF TYPE-B KOSZUL H1 TO ONE VARIABLE
--------------------------------------------------------------------------

Define

    D1:=H_1(f,g;B).

Theorem TypeB_Koszul_H1_is_exactly_the_one_variable_Koszul_H1:
  There is a natural graded B-module isomorphism

    D1 ~= H_1(f,g;K)(-1).

Proof:
  Apply the two-element Koszul complex K(f,g;-) to

    0 -> K(-1) -> B -> R -> 0.

  This gives a short exact sequence of complexes.  The relevant part of the
  long exact homology sequence is

    H_2(f,g;R)
      -> H_1(f,g;K)(-1)
      -> H_1(f,g;B)
      -> H_1(f,g;R).

  Both outside terms vanish by regularity on R.  Therefore the middle map is an
  isomorphism.
Qed.

Corollary at_least_one_final_generator_is_nonzero_on_K:
  At least one of the restrictions

    f_K,g_K in K=C[t]

  is nonzero.

Proof:
  The module D1 is a finitely generated B-module annihilated by f and g, hence
  it is a finitely generated A-module.  Since A has finite C-length, D1 has
  finite C-dimension.

  If f_K=g_K=0, then the Koszul differential on K(f,g;K) is zero and

    H_1(f,g;K) ~= K direct_sum K

  up to grading shifts, which has infinite C-dimension.  This contradicts the
  preceding isomorphism with D1.
Qed.

Because K=C[t] and f,g are homogeneous, each nonzero restriction is a scalar
multiple of the corresponding pure power:

    f_K !=0  =>  f_K=lambda*t^d,
    g_K !=0  =>  g_K=mu*t^e.

Define

    r:=min { degree of a nonzero member among f_K,g_K }.

Then r is a positive integer and

    (f_K,g_K)=(t^r) subset K.

Theorem exact_one_variable_Koszul_H1_shape:
  Up to a grading shift,

    H_1(f,g;K) ~= K/(t^r).

  In particular

    dim_C D1=r.

Proof:
  If both restrictions are nonzero, write

    f_K=t^r*f',
    g_K=t^r*g'

  with gcd(f',g')=1 in the PID K.  The first syzygy module is generated by

    (-g',f'),

  while the Koszul syzygy is t^r times that generator.  Therefore first Koszul
  homology is K/(t^r), up to the grading of the generator.

  If exactly one restriction is nonzero, say g_K=0 and f_K is a scalar multiple
  of t^r, then the syzygy module is generated by the coordinate corresponding
  to the zero element and the Koszul submodule is t^r times that generator.
  The same quotient K/(t^r) results.

  The previous theorem transfers this shape to D1, with the additional (-1)
  shift from K(-1).
Qed.

--------------------------------------------------------------------------
4. THE HEIGHT-THREE LINEAR PRIME ANNIHILATES THE FULL KOSZUL DEFECT
--------------------------------------------------------------------------

Theorem Jlin_annihilates_the_full_TypeB_Koszul_H1:
  The B-action on D1 factors through K=S/Jlin.  Consequently

    Jlin*D1=0.

Proof:
  The exact isomorphism

    D1 ~= H_1(f,g;K)(-1)

  is B-linear, where B acts on the right side through its action on the
  submodule K(-1) in the multiplication-by-x exact sequence.  That action
  factors through S/Jlin=K.  Hence every element of Jlin acts by zero.
Qed.

Since every first Koszul homology module is annihilated by f and g, D1 is
naturally an A-module.  Let

    E:=Ann_A(D1).

Corollary the_image_of_Jlin_is_a_large_Koszul_annihilator:
  If J_A denotes the image of Jlin in A, then

    J_A subset E.
Qed.

Theorem exact_codimension_of_the_Jlin_carrier:
  One has

    A/J_A ~= K/(t^r)

  and therefore

    length_C(A/J_A)=r,
    dim_C J_A=N-r.

Proof:
  Since Q=x*Jlin+(q) is contained in Jlin,

    A/J_A
      ~= S/(Q,f,g,Jlin)
      ~= S/(Jlin,f,g)
      ~= K/(f_K,g_K)
      ~= K/(t^r).

  The length and dimension statements follow.
Qed.

--------------------------------------------------------------------------
5. TWO-COPY HOM CARRIER
--------------------------------------------------------------------------

Put

    L:=(f,g)B.

Let

    Syz:=Syz_B(f,g)
        ={(u,v) in B^2 : u*f+v*g=0}.

Then

    D1=Syz/B*(-g,f).

Theorem square_of_the_Koszul_annihilator_is_a_two_cut_Hom_carrier:
  There is a natural C-linear injection

    E direct_sum E -> Hom_B(L,A).

Proof:
  The presentation

    B^2 -> L,
    (u,v) |-> u*f+v*g

  has kernel Syz.  Hence Hom_B(L,A) is the set of pairs (alpha,beta) in A^2
  satisfying

    u*alpha+v*beta=0

  for every (u,v) in Syz.

  Because f=g=0 in A, every coordinate functional on B^2 with values in A kills
  the Koszul submodule B*(-g,f), so its restriction to Syz factors through D1.

  The coordinate reductions

    rho_1,rho_2:D1->A

  are A-linear.  If alpha,beta belong to E=Ann_A(D1), then

    alpha*rho_i(xi)=0,
    beta*rho_i(xi)=0

  for every xi in D1 and i=1,2.  Thus each pair in E^2 kills all syzygies and
  defines a map L->A.  Distinct pairs remain distinct in A^2, proving the
  injection.
Qed.

Corollary TypeB_linear_prime_gives_a_two_copy_carrier:
  There is an injection

    J_A direct_sum J_A -> Hom_B(L,A),

  and consequently

    dim_C Hom_B(L,A) >= 2*(N-r).
Qed.

Theorem maps_killing_Q_embed_into_the_full_tangent_space:
  There is a natural injection

    Hom_B(L,A) -> Hom_S(I,A).

Proof:
  Since I=Q+(f,g), one has I/Q=L as a B-module.  S-linear maps I->A which
  vanish on Q are exactly B-linear maps L->A.  They form a C-linear subspace of
  Hom_S(I,A).
Qed.

Corollary preliminary_TypeB_tangent_lower_bound:
  One has

    t(A):=dim_C Hom_S(I,A) >= 2*(N-r).
Qed.

--------------------------------------------------------------------------
6. THE CONIC QUOTIENT MAKES THE CARRIER LARGE ENOUGH
--------------------------------------------------------------------------

Theorem conic_parameter_section_has_length_two_d_e:
  One has

    length_C R/(f_R,g_R)=2*d*e.

Proof:
  The ring R is standard graded Cohen--Macaulay of dimension two and
  multiplicity two.  The regular sequence f_R,g_R has homogeneous degrees d,e.
  Multiplying the Hilbert series by

    (1-t^d)(1-t^e)

  gives the finite quotient, whose total length is e(R)*d*e=2*d*e.
Qed.

Corollary total_length_dominates_the_conic_section:
  Since A surjects onto R/(f_R,g_R),

    N>=2*d*e.
Qed.

Theorem one_variable_tail_is_at_most_one_sixth_of_total_length:
  One has

    N>=6*r.

Proof:
  By definition r is the degree of one of the nonzero restrictions f_K or g_K,
  or the smaller degree if both are nonzero.

  If r=d, then e>=3, so

    2*d*e>=6*r.

  If r=e, then d>=3, so again

    2*d*e>=6*r.

  If both restrictions are nonzero and r=min(d,e), the same inequality follows
  because the other degree is at least three.

  Combine with N>=2*d*e.
Qed.

Theorem TypeB_fails_the_order13_tangent_gate:
  One has

    t(A)>N-20.

  Hence the necessary order-13 tangent condition

    t(A)<=N-20

  is impossible throughout the Type-B profile.

Proof:
  The carrier bound gives

    t(A)>=2*(N-r).

  Therefore

    t(A)-(N-20)
      >= N-2*r+20.

  Since N>=6*r,

    N-2*r+20 >=4*r+20>0.

  Thus t(A)>N-20.
Qed.

Corollary q4_height2_depth_one_TypeB_profile_is_closed:
  No homogeneous order-13 deviation-two candidate with multiplicity-two
  Type-B four-quadric core

    Q=x*(a1,a2,a3)+(q),
    q in (a1,a2,a3)\(x),

  can pass the necessary tangent-deficit gate.
Qed.

--------------------------------------------------------------------------
7. SHARP BOUNDARY AFTER TYPE B
--------------------------------------------------------------------------

The multiplicity-two q=4 height-two inventory now has the following status:

  Type A1 skew-line endpoint:
    CLOSED.

  Type A2 saturated double-line endpoint:
    CLOSED.

  Type B punctured-spectrum-defective endpoint:
    CLOSED in this file.

  Type C:
    saturates to the already-closed Cohen--Macaulay plane-conic branch.

Thus the multiplicity-two height-two q=4 branch is exhausted by the current
pseudo-formal tangent arguments.

IMPORTANT_NONCONCLUSION:
  This file does NOT by itself close every q=4 height-two branch.  The previous
  use of the multiplicity-two classification does not automatically classify
  possible multiplicity-one, non-finite-Rao depth-one saturated cores.

  Therefore no full q=4 height-two closure and no full order-13 closure is
  claimed here.

  It does not enter homogeneous q<=3 or the unrestricted nonhomogeneous local
  deviation-two frontier.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_tangent_closed.
  q4_height2_depth_one_skew_line_endpoint_closed.
  q4_height2_depth_one_double_line_endpoint_closed.
  q4_height2_depth_one_TypeB_profile_closed.
  q4_height2_multiplicity_two_frontier_closed.
  not q4_height2_multiplicity_one_nonfinite_Rao_closed.
  not q4_height2_depth_one_core_closed.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

NEXT_ACTIONS:
  1. Stay inside q=4 height two.
  2. Audit only the multiplicity-one depth-one possibility left outside the
     multiplicity-two classification.
  3. Determine whether saturation forces the line core already handled, or a
     projective lower-dimensional component can remain.
  4. If such a component remains, derive its exact multiplication/colon
     sequence before any tangent claim.
  5. Do not enter q<=3.
