Standalone cubic-profile classification for the s=2 branch of the homogeneous
q=4, height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_s1_closed.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    P := C[l1,l2],
    V := Span_C{l1,l2},
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

This file treats only

    s := dim_C Syz_1(Q)=2.

The preceding files prove

    G := J^2*T/J^3*T ~= C(-3)^2

and

    H := J^3*T/J^4*T ~= C(-4)^h

with the earlier coarse bound h<=4.

The purpose here is only to classify

    K3 := Q_3 intersect P_3

and use its quartic span to sharpen h.  No deeper J-adic layer is entered.
The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Theorem s2_has_exactly_two_pure_cubic_relations:
  If s=2, then

    dim_C K3=2.

Proof:
  The exact third-layer quotient gives

    G_3 ~= P_3/K3.

  Since dim_C P_3=4 and dim_C G_3=s=2,

    dim_C K3=2.
Qed.

We split only by the already classified first-conormal rank r in {4,3}.

Theorem r4_s2_cubic_space_is_exactly_the_basepoint_free_canonical_pair:
  Assume r=4 and s=2.  In the normalized r=4 quadratic form

    q1 = z*l1 + h1,
    q2 = w*l1 + h2,
    q3 = z*l2 + h3,
    q4 = w*l2 + h4,

  define the canonical pure cubics

    Pz := l2*h1-l1*h3,
    Pw := l2*h2-l1*h4.

  Then

    K3 = Span_C{Pz,Pw},

  and

    gcd(Pz,Pw)=1.

Proof:
  The third-layer classification proves that Pz and Pw are independent elements
  of Q intersect P_3 and have no common projective zero in P(V)=P^1.

  Since the present s=2 hypothesis gives dim_C K3=2, these two independent
  cubics already form a basis of K3.

  Two homogeneous forms in two variables have a nonconstant common divisor if
  and only if they have a common projective zero over C.  Therefore the absence
  of a common projective zero gives gcd(Pz,Pw)=1.
Qed.

Corollary r4_s2_quartic_span_has_codimension_one:
  In the r=4,s=2 case,

    dim_C(P_1*K3)=4,

  hence

    codim_{P_4}(P_1*K3)=1.

Proof:
  The multiplication map

    P_1 tensor K3 -> P_4

  has four-dimensional source.  A nonzero kernel vector would be a linear
  syzygy

    A*Pz+B*Pw=0

  with A,B linear.  Since gcd(Pz,Pw)=1, Pz divides B and Pw divides A, which is
  impossible by degree unless A=B=0.  Thus the map is injective and its image
  has dimension four.  Since dim_C P_4=5, the codimension is one.
Qed.

Theorem r3_s2_cubic_space_is_exactly_H0_times_V:
  Assume r=3 and s=2.  Let

    0 != H0 in Q_2 intersect P_2

  span the unique pure-transverse quadratic direction from the first-conormal
  classification.  Then

    K3 = H0*V.

  In particular the gcd of the two-dimensional cubic space K3 has degree two.

Proof:
  Since H0 belongs to Q, both

    l1*H0,
    l2*H0

  belong to K3 and are independent.  Hence H0*V is a two-dimensional subspace
  of K3.  The theorem s2_has_exactly_two_pure_cubic_relations gives
  dim_C K3=2, so equality holds.
Qed.

Corollary r3_s2_linear_quartic_span_has_dimension_three:
  In the r=3,s=2 case,

    P_1*K3=H0*P_2

  and therefore

    dim_C(P_1*K3)=3.
Qed.

We now use the canonical r=3 quartic compatibility already established in the
s=1 closure.

Theorem r3_s2_canonical_quartic_is_not_an_H0_multiple:
  Normalize the r=3 generators as

    q1 = z*l1 + h1,
    q2 = w*l1 + z*l2 + h2,
    q3 = w*l2 + h3,
    q4 = H0,

  with h1,h2,h3,H0 in P_2, and define

    C4 := l2^2*h1-l1*l2*h2+l1^2*h3.

  Then

    C4 in Q_4 intersect P_4

  but

    C4 notin H0*P_2.

Proof:
  The canonical compatibility identity

    l2^2*q1-l1*l2*q2+l1^2*q3=C4

  proves C4 belongs to Q_4 intersect P_4.

  Suppose for contradiction that H0 divides C4.  Choose a projective root

    [a:b] in P^1

  of the nonzero quadratic H0.  Such a root exists over C.  Then

    H0(a,b)=0,
    C4(a,b)=0.

  Evaluate q1,q2,q3 at l1=a,l2=b.  Solving them for z,w gives the linear system

    a*z       = -h1(a,b),
    b*z+a*w   = -h2(a,b),
        b*w   = -h3(a,b).

  For every nonzero pair (a,b), its 3 by 2 coefficient matrix has rank two and
  its unique compatibility condition is

    b^2*h1(a,b)-a*b*h2(a,b)+a^2*h3(a,b)=0,

  exactly C4(a,b)=0.  Therefore there exist z0,w0 satisfying q1=q2=q3=0.
  Together with q4=H0=0 this produces a projective common zero

    [a:b:z0:w0]

  of Q with (a,b) nonzero.

  This point is off the line V(J)={l1=l2=0}, contradicting Qsat=J, equivalently
  Proj(S/Q)=Proj(S/J).  Hence C4 is not divisible by H0.
Qed.

Corollary r3_s2_quartic_relation_space_has_dimension_at_least_four:
  In the r=3,s=2 case,

    H0*P_2 + C*C4

  is a four-dimensional subspace of

    Q_4 intersect P_4.

Proof:
  H0*P_2 has dimension three.  The preceding theorem says C4 is not in that
  subspace, so adjoining C4 raises the dimension to four.
Qed.

Theorem s2_fourth_layer_has_dimension_at_most_one:
  In every s=2 line-core case,

    h<=1.

  Equivalently,

    H=J^3*T/J^4*T

  is either zero or C(-4).

Proof:
  The exact fourth-layer quotient in degree four is

    H_4 ~= P_4/(Q_4 intersect P_4).

  In the r=4 case, P_1*K3 is a four-dimensional subspace of Q_4 intersect P_4.
  Hence the quotient has dimension at most one.

  In the r=3 case, the preceding corollary supplies the four-dimensional
  subspace

    H0*P_2 + C*C4

  inside Q_4 intersect P_4.  Again dim_C P_4=5, so the quotient has dimension
  at most one.
Qed.

Corollary exact_s2_gcd_profile:
  The pure cubic space K3 has exactly the following two profiles:

    r=4:
      K3=Span_C{Pz,Pw},
      gcd(K3)=1;

    r=3:
      K3=H0*V,
      deg gcd(K3)=2.

  No gcd-degree-one s=2 case occurs.
Qed.

Corollary s2_fourth_layer_rank_window_collapses:
  The previous coarse window

    0<=h<=4

  sharpens to

    h in {0,1}.

  If h=0, then

    J^3*T=0

  by the earlier Nakayama argument.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does NOT rule out

    s=2,
    h=1.

  Thus it does not yet close the full q=4 height-two CM line core.

  In the r=4 branch, h=1 means

    Q_4 intersect P_4 = P_1*K3

  is the four-dimensional quartic span of the basepoint-free canonical cubic
  pair.

  In the r=3 branch, h=1 means

    Q_4 intersect P_4 = H0*P_2 + C*C4

  is exactly four-dimensional.

  No fifth J-adic layer is analyzed here.
  No tangent-gate contradiction is claimed.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_closed.
  q4_height2_CM_line_core_s2_cubic_profile_classified.
  not q4_height2_CM_line_core_s2_closed.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Treat only the residual

    s=2,
    h=1

  cases.  Determine whether the unique surviving quartic class dies under one
  further transverse multiplication, i.e. compute

    J^4*T/J^5*T.

  Use the exact r=4 and r=3 quartic normal forms above rather than returning to
  an unrestricted module classification.

NEXT_BOUNDED_OBJECT:
  Split only the residual s=2,h=1 branch into r=4 and r=3.  Compute the two
  l1,l2 multiples of the unique quartic class modulo Q_5 intersect P_5 and test
  whether the fifth transverse layer vanishes.  Do not enter the depth-one
  deficiency branch.