Standalone tangent closure for the homogeneous q=4, height-two Cohen--Macaulay
LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from the completed line-core J-adic chain through

    order13_q4_height2_cm_line_core_s2_fifth_layer_closed.v

  and retain

    S := C[l1,l2,z,w],
    m := (l1,l2,z,w),
    J := (l1,l2),
    Q subset J,
    B := S/Q,
    T := J/Q,
    C0 := S/J ~= C[z,w],

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=2,
    Qsat=J,

  and T has finite length.

  Let

    I := Q+(f,g)

  be homogeneous and m-primary, with

    deg(f),deg(g) >= 3,

  and put

    A := S/I = B/(f,g),
    N := length_C(A) >= 32.

The order-13 repair route requires the necessary tangent gate

    t(A) := dim_C Hom_S(I,A) <= N-20.

This file proves that the completed Cohen--Macaulay line-core branch cannot
satisfy that gate.

The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Theorem exact_total_line_core_torsion_Hilbert_support:
  There are

    s in {0,1,2},
    h in {0,1},

  with h=0 unless s=2, such that

    Hilb_T(t)
      = 2*t + 3*t^2 + s*t^3 + h*t^4.

  In particular

    T_n=0 for every n>=5.

Proof:
  Filter T by powers of J:

    T superset J*T superset J^2*T superset J^3*T superset J^4*T=0.

  The completed line-core files identify the successive quotients.

  FIRST LAYER.
  For r=4,

    Hilb_(T/J*T)=2*t,

  while for r=3,

    Hilb_(T/J*T)=2*t+t^2.

  SECOND LAYER.
  For r=4,

    Hilb_(J*T/J^2*T)=3*t^2,

  while for r=3,

    Hilb_(J*T/J^2*T)=2*t^2.

  Thus in either first-conormal case the sum of the first two layers is

    2*t+3*t^2.

  THIRD LAYER.
  The third-layer classification proves

    J^2*T/J^3*T ~= C(-3)^s,

  with s in {0,1,2}.

  FOURTH LAYER.
  The s=0 branch closes at J^2*T=0.
  The s=1 branch closes at J^3*T=0.
  The s=2 cubic-profile classification proves

    J^3*T/J^4*T ~= C(-4)^h,

  with h in {0,1}, and the fifth-layer closure proves universally in s=2 that

    J^4*T=0.

  Hilbert series are additive across the finite filtration, giving exactly

    Hilb_T(t)=2*t+3*t^2+s*t^3+h*t^4.
Qed.

Corollary fourth_power_of_the_maximal_ideal_annihilates_T:
  One has

    m^4*T=0.

Proof:
  T is concentrated in ordinary degrees 1 through 4.  Every homogeneous element
  of m^4 has degree at least four, so multiplying any homogeneous element of T
  lands in degree at least five, where T vanishes.
Qed.

Corollary line_core_annihilator_quotient_has_length_at_most_seventeen:
  Put

    K := Ann_B(T).

  Then

    m_B^4 subset K

  and

    length_C(B/K) <= 15+s <= 17.

Proof:
  The previous corollary gives m_B^4*T=0, hence m_B^4 subset K.

  Therefore B/K is a quotient of B/m_B^4.  From

    0 -> T -> B -> C0 -> 0

  and the exact torsion Hilbert data,

    dim B_0 = 1,
    dim B_1 = 2+2 = 4,
    dim B_2 = 3+3 = 6,
    dim B_3 = 4+s.

  Consequently

    length(B/m_B^4)
      = 1+4+6+(4+s)
      = 15+s
      <=17.
Qed.

We now return to the final pair f,g.

Theorem final_pair_is_regular_on_the_saturated_line_quotient:
  The images

    fbar,gbar in C0=C[z,w]

  form a regular sequence.

Proof:
  The saturated-core profile already proves that (fbar,gbar) is an
  m_C0-primary homogeneous parameter pair.  The polynomial ring C[z,w] is
  Cohen--Macaulay of dimension two, so every homogeneous system of parameters
  is a regular sequence.
Qed.

Define the first Koszul homology over B

    D1 := H_1(f,g;B).

Equivalently, if

    M := Syz_B(f,g)
       = { (a,b) in B^2 : a*f+b*g=0 },

then

    D1 = M / B*(-g,f).

Theorem all_two_cut_Koszul_H1_is_inherited_from_the_saturation_torsion:
  There is a natural isomorphism

    D1 ~= H_1(f,g;T).

Proof:
  Apply the two-element Koszul complex K(f,g;-) to

    0 -> T -> B -> C0 -> 0.

  Because the Koszul complex is built from free modules, this gives a short
  exact sequence of complexes

    0 -> K(f,g;T)
      -> K(f,g;B)
      -> K(fbar,gbar;C0)
      -> 0.

  The preceding theorem says fbar,gbar is a regular sequence on C0, hence

    H_2(fbar,gbar;C0)=0,
    H_1(fbar,gbar;C0)=0.

  The long exact homology sequence therefore gives

    H_1(f,g;T) ~= H_1(f,g;B)=D1.
Qed.

Corollary the_Koszul_defect_is_an_A_module_annihilated_by_m4:
  The B-action on D1 factors through A and

    m_A^4*D1=0.

Proof:
  First, every first Koszul homology module is annihilated by f and g.  Directly,
  for a syzygy (a,b),

    f*(a,b)=b*(-g,f),
    g*(a,b)=-a*(-g,f),

  modulo the Koszul submodule.  Thus (f,g)D1=0 and D1 is naturally an A-module.

  By the preceding theorem D1 is a subquotient of the Koszul chain module T^2.
  Since m_B^4*T=0, also m_B^4*D1=0.  Passing to A gives

    m_A^4*D1=0.
Qed.

Theorem square_of_the_Koszul_annihilator_is_a_two_cut_Hom_carrier:
  Put

    E := Ann_A(D1).

  Then there is a natural C-linear injection

    E direct_sum E -> Hom_B((f,g)B,A).

  Consequently

    dim_C Hom_B((f,g)B,A) >= 2*dim_C E.

Proof:
  The presentation

    B^2 -> (f,g)B,
    (u,v) |-> u*f+v*g

  has kernel M=Syz_B(f,g).  Hence Hom_B((f,g)B,A) identifies with the pairs

    (alpha,beta) in A^2

  whose functional

    (a,b) |-> a*alpha+b*beta

  vanishes on M.

  Since f=g=0 in A, every such A-valued functional kills the Koszul submodule

    B*(-g,f),

  so restriction to M factors through

    D1=M/B*(-g,f).

  The coordinate reductions

    rho_1,rho_2 : D1 -> A,
    rho_1([a,b])=a mod (f,g),
    rho_2([a,b])=b mod (f,g)

  are well-defined because changing (a,b) by a Koszul pair changes the two
  coordinates by multiples of g and f.

  If alpha belongs to E=Ann_A(D1), then for every x in D1,

    alpha*rho_i(x)
      = rho_i(alpha*x)
      = 0

  for i=1,2.  The same holds for beta in E.  Therefore every pair

    (alpha,beta) in E^2

  gives zero restriction on D1 and hence defines a B-linear map (f,g)B -> A.

  Under the standard identification with the kernel inside A^2, distinct pairs
  remain distinct, giving the asserted injection.
Qed.

Corollary fourth_power_gives_a_large_explicit_Hom_carrier:
  One has

    m_A^4 subset E

  and therefore

    dim_C Hom_B((f,g)B,A)
      >= 2*dim_C(m_A^4).

Proof:
  The previous annihilation result gives m_A^4*D1=0, so m_A^4 subset Ann_A(D1)=E.
  Apply the carrier theorem.
Qed.

Theorem the_fourth_power_has_codimension_at_most_seventeen_in_A:
  One has

    length_C(A/m_A^4) <= 17,

  hence

    dim_C(m_A^4) >= N-17.

Proof:
  Since A is a homogeneous quotient of B,

    dim A_i <= dim B_i

  in every degree.  The exact line-core initial data give

    dim B_0=1,
    dim B_1=4,
    dim B_2=6,
    dim B_3=4+s <=6.

  Therefore

    length(A/m_A^4)
      = dim A_0+dim A_1+dim A_2+dim A_3
      <= 1+4+6+6
      =17.

  Since length(A)=N,

    dim m_A^4
      = N-length(A/m_A^4)
      >= N-17.
Qed.

Theorem maps_killing_Q_contain_the_two_cut_Hom_carrier:
  There is a natural injection

    Hom_B((f,g)B,A) -> Hom_S(I,A).

Proof:
  The quotient I/Q is exactly the B-ideal (f,g)B.  S-linear maps I->A that
  vanish on Q are therefore exactly B-linear maps (f,g)B->A.  They form a
  linear subspace of Hom_S(I,A).
Qed.

Theorem CM_line_core_tangent_lower_bound:
  One has

    t(A) := dim_C Hom_S(I,A) >= 2*N-34.

Proof:
  Combine the preceding three results:

    t(A)
      >= dim Hom_B((f,g)B,A)
      >= 2*dim(m_A^4)
      >= 2*(N-17)
      = 2*N-34.
Qed.

Theorem q4_height2_CM_line_core_fails_the_order13_tangent_gate:
  Under the standing order-13 length condition N>=32,

    t(A) > N-20.

  Therefore the necessary order-13 tangent gate

    t(A) <= N-20

  is impossible throughout the q=4 height-two Cohen--Macaulay line-core branch.

Proof:
  The tangent lower bound gives

    t(A) >= 2*N-34.

  Compare with the gate:

    (2*N-34) - (N-20) = N-14.

  Since N>=32,

    N-14 >=18 >0.

  Hence

    t(A) > N-20.
Qed.

Corollary q4_height2_CM_line_core_tangent_closed:
  No homogeneous order-13 deviation-two candidate with

    four quadratic minimal generators,
    ht(Q)=2,
    Qsat=(l1,l2),
    saturated depth two line core,

  can pass the necessary tangent-deficit gate.
Qed.

IMPORTANT_NONCONCLUSION:
  This closes only the Cohen--Macaulay LINE CORE inside the homogeneous q=4,
  height-two branch.

  It does not treat the depth-one saturated-core branch.
  It does not close homogeneous q<=3.
  It does not close the unrestricted nonhomogeneous local deviation-two frontier.
  No generic order-13 semiregularity or algebraicity theorem is claimed.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_closed.
  q4_height2_CM_line_core_s2_closed.
  q4_height2_CM_line_core_tangent_closed.
  not q4_height2_depth_one_core_closed.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

NEXT_BOUNDED_OBJECT:
  Leave the now-closed Cohen--Macaulay line core.  Return only to the remaining
  q=4 height-two depth-one saturated-core branch and identify the smallest
  deficiency module H^1_m(C) compatible with four independent quadratic
  generators.  Do not claim full order-13 closure.