Standalone colon-filtration reduction of the r-in-P half of the LK3-C2 carrier
in the saturated H01 minimal-chain rank-two endpoint of the homogeneous q=4,
height-two, multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_m2_R2_LK3_koszul_normal_form.v

  and retain

    S := C[x1,x2,x3,x4],
    Q=Qsat subset P,
    P=(l1,l2),
    B:=S/Q,
    D:=P/Q,

with

    ht(Q)=2,
    Q minimally generated by exactly four independent quadrics,
    Hilb_B(t)=(1+2*t-t^2-t^3)/(1-t)^2,
    Hilb_D(t)=(2*t+t^2)/(1-t),

inside the LK3-C2 carrier. Thus there is a nonzero linear form r such that

    dim_C(Q_2 intersect r*S_1) >= 2.

This file treats only the complementary subcase

    r in P.

It performs one bounded task: prove that the r-multiple plane has dimension
exactly two, classify K:=(Q:r) as a (1,1,2) complete intersection, and derive
the exact two-step filtration of D. No tangent estimate or branch closure is
claimed.

No r-not-in-P argument is repeated.
No LK3-C3, R2-LK2, R2-QK, H01-M2-R1, or q<=3 branch is entered.
No Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. NORMALIZE THE TWO r-MULTIPLE QUADRICS
--------------------------------------------------------------------------

Since r lies in the two-dimensional linear prime P, choose p independent of r
with

    P=(r,p).

Choose independent quadrics in Q_2 intersect r*S_1 and write

    q1=r*a,
    q2=r*b

with a,b independent linear forms. Complete them to a basis

    q1,q2,q3,q4

of Q_2.

Put

    W:=Q_2 intersect r*S_1.

The standing LK3-C2 hypothesis gives dim_C W>=2.

--------------------------------------------------------------------------
2. A THIRD r-MULTIPLE IS IMPOSSIBLE BY HILBERT POSITIVITY
--------------------------------------------------------------------------

Assume for contradiction that dim_C W>=3. After a generator basis change,
three independent quadratic generators are divisible by r. Modulo r only one
quadratic generator can remain.

Set

    R:=S/(r) ~= C[y1,y2,y3].

Because Q subset P=(r,p), every surviving quadratic image lies in the principal
linear ideal generated by pbar, the image of p in R. Thus

    (Q+(r))/(r)

is generated by at most one quadratic pbar*u.

If that quadratic is nonzero, then

    Hilb_(S/(Q+(r)))(t)
      = Hilb_(R/(pbar*u))(t)
      = (1+t)/(1-t)^2.

If it vanishes, the quotient is R itself and has even larger Hilbert function.

Let

    K:=(Q:r).

Multiplication by r gives the exact sequence

    0 -> S/K(-1)
      -> B
      -> S/(Q+(r))
      -> 0.

In the nonzero-quadratic case this would force

    Hilb_(S/K)(t)
      = (Hilb_B(t)-Hilb_(S/(Q+(r)))(t))/t
      = (1-t-t^2)/(1-t)^2.

Its coefficient sequence begins

    1, 1, 0, -1, -2, ...,

which is impossible for a graded quotient. The zero-quadratic case gives an
even larger right-hand quotient and is impossible a fortiori.

Therefore

    dim_C(Q_2 intersect r*S_1)=2.

Theorem H01_m2_R2_LK3_C2_r_in_P_exact_r_multiple_dimension:
  In the r-in-P half of LK3-C2,

    dim_C(Q_2 intersect r*S_1)=2.
Qed.

Consequently q3bar,q4bar are nonzero and independent modulo r.

--------------------------------------------------------------------------
3. THE MOD-r PAIR HAS THE FORM pbar*u, pbar*v
--------------------------------------------------------------------------

Because q3,q4 lie in P=(r,p), their images in R satisfy

    q3bar=pbar*u,
    q4bar=pbar*v

for linear forms u,v in R_1.

The independence of q3bar,q4bar implies that u,v are independent. Therefore
there is an exact sequence

    0 -> R/(u,v)(-1)
      -- multiplication by pbar --> R/(pbar*u,pbar*v)
      -> R/(pbar)
      -> 0.

Indeed cancellation by the nonzero element pbar in the domain R shows that the
left map is injective.

Hence

    Hilb_(S/(Q+(r)))(t)
      = 1/(1-t)^2 + t/(1-t).

Theorem H01_m2_R2_LK3_C2_r_in_P_exact_mod_r_Hilbert_series:
  One has

    Hilb_(S/(Q+(r)))(t)
      = 1/(1-t)^2 + t/(1-t).
Qed.

--------------------------------------------------------------------------
4. THE COLON K=(Q:r) IS A (1,1,2) COMPLETE INTERSECTION
--------------------------------------------------------------------------

Use again

    0 -> S/K(-1) -> B -> S/(Q+(r)) -> 0.

The exact Hilbert series now gives

    Hilb_(S/K)(t)
      = (Hilb_B(t)-Hilb_(S/(Q+(r)))(t))/t
      = (1+t)/(1-t).

Since q1=r*a and q2=r*b belong to Q,

    a,b in K_1.

They are independent. The coefficient of t in (1+t)/(1-t) is two, so

    dim_C(S/K)_1=2,
    dim_C K_1=2.

Therefore

    K_1=span_C{a,b}.

Pass to

    T:=S/(a,b) ~= C[s,t].

The image Kbar of K has no linear forms and

    Hilb_(T/Kbar)(t)=(1+t)/(1-t)
                     =(1-t^2)/(1-t)^2.

Thus Kbar has exactly one quadratic generator Fbar and no further Hilbert
defect. Hence

    K=(a,b,F)

for a quadric F whose image modulo (a,b) is nonzero.

The three forms a,b,F are a regular sequence of degrees (1,1,2). Therefore K
is a saturated height-three complete intersection and

    e(S/K)=2.

Theorem H01_m2_R2_LK3_C2_r_in_P_colon_complete_intersection:
  For K=(Q:r),

    K=(a,b,F)

  with a,b independent linear forms and F a quadric nonzero modulo (a,b).
  In particular K is a saturated complete intersection of type (1,1,2), and

    Hilb_(S/K)(t)=(1+t)/(1-t).
Qed.

--------------------------------------------------------------------------
5. EXACT TWO-STEP FILTRATION OF THE RESIDUAL MODULE D
--------------------------------------------------------------------------

Multiplication by r lands inside D=P/Q because r belongs to P. By definition
of K=(Q:r), it gives an injective graded map

    S/K(-1) -> D,
    s |-> r*s mod Q.

The cokernel is

    P/(Q+r*S).

Modulo r this becomes

    (pbar)/(pbar*u,pbar*v)
      ~= R/(u,v)(-1).

Choose lifts of u,v to S and put

    J:=(r,u,v).

Because u,v are independent modulo r, J is a height-three linear prime. Thus

    R/(u,v)(-1) ~= S/J(-1).

Therefore there is an exact sequence

    0 -> S/K(-1)
      -> D
      -> S/J(-1)
      -> 0,

where

    K=(a,b,F) is a (1,1,2) complete intersection,
    J=(r,u,v) is a height-three linear prime.

The Hilbert series check is exact:

    t*(1+t)/(1-t) + t/(1-t)
      = (2*t+t^2)/(1-t)
      = Hilb_D(t).

Theorem H01_m2_R2_LK3_C2_r_in_P_exact_residual_filtration:
  D has the exact two-step filtration

    0 -> S/K(-1) -> D -> S/J(-1) -> 0

  with K and J as above.
Qed.

--------------------------------------------------------------------------
6. PRODUCT ANNIHILATOR FOR THE ENTIRE RESIDUAL MODULE
--------------------------------------------------------------------------

The quotient S/J(-1) is annihilated by J. Therefore

    J*D

lands inside the submodule S/K(-1). The latter is annihilated by K. Hence

    K*J*D=0.

Corollary H01_m2_R2_LK3_C2_r_in_P_product_annihilator:
  One has

    K*J subset Ann_S(D).
Qed.

This product annihilator is the next bounded bridge toward a tangent carrier,
but no tangent-space estimate is made here.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_in_P_exact_two_r_multiples.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_in_P_colon_CI_112.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_in_P_residual_filtration.
  q4_height2_multiplicity_one_depth_one_H01_m2_R2_LK3_C2_r_in_P_product_annihilator.

EXACT_STRUCTURE:

    dim_C(Q_2 intersect r*S_1)=2,

    K=(Q:r)=(a,b,F),
    type(K)=(1,1,2),

    J=(r,u,v) linear height-three prime,

    0 -> S/K(-1) -> D -> S/J(-1) -> 0,

    K*J*D=0.

IMPORTANT_NONCONCLUSION:
  This file does NOT close the r-in-P carrier.
  It does NOT close LK3-C2 or R2-LK3.
  It does NOT exclude LK3-C3, R2-LK2, or R2-QK.
  It does NOT treat H01-M2-R1.
  It does NOT make a tangent-space estimate.
  It does NOT close H01.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_R2_exact_Betti_table.
  H01_m2_R2_determinantal_factorization.
  H01_m2_R2_LK3_coefficient_rank_one_empty.
  H01_m2_R2_LK3_C2_r_notin_P_CI_carrier.
  H01_m2_R2_LK3_C2_r_in_P_colon_filtration.
  not H01_m2_R2_LK3_C2_closed.
  not H01_m2_R2_LK3_closed.
  not H01_m2_R2_closed.
  not H01_m2_R1_closed.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Stay only in LK3-C2. Both r-not-in-P and r-in-P halves are now reduced to
  explicit finite carriers. The weakest next step is a tangent/Koszul estimate
  for the r-in-P filtration using the product annihilator

    K*J*D=0,

  with K a (1,1,2) complete intersection and J a height-three linear prime.
  Compare this carrier with the already-closed H10 product-annihilator route,
  but do not import its numerical bound without proving the new cut-length
  constants for this multiplicity-two submodule.

NEXT_ACTIONS:
  1. Derive the r-in-P final-pair cut-length bound from the exact K/J filtration.
