Standalone closure of the multiplicity-one saturated-core subbranch in the
homogeneous q=4, height-three order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=1,
    deg(f),deg(g)>=3.

  Put

    T := H^0_m(B)=Qsat/Q,
    Cbar := B/T.

  The preceding profile proves that Cbar is one-dimensional Cohen--Macaulay,
  that T is concentrated in degrees one through four, and that the only
  possible linear Artin-reduction h-vector at multiplicity one is

    (1).

  The purpose of this file is to close this first low-multiplicity h-vector.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
does not assert generic F_13 algebraicity.

Retain the complete-intersection section model

  R := S/(q1,q2,q3),
  J := (a)R,
  B = R/J,
  Jsat := saturation(J),
  Cbar = R/Jsat,
  X := Proj(R).

Then X is the zero-dimensional complete intersection of three quadrics in P^3
of length eight and

  dim_C R_1=4,
  dim_C R_2=7,
  dim_C R_n=8 for n>=3.

The preceding files also prove

  dim_C T_1=3,
  dim_C T_2=5,
  dim_C T_4<=1,
  T_n=0 for n>=5.

Theorem multiplicity_one_saturated_core_is_a_polynomial_ring:
  For a general linear nonzerodivisor ell in Cbar_1, the natural graded map

    C[ell] -> Cbar

  is an isomorphism.  Hence

    Cbar ~= C[ell].

Proof:
  The saturated-core profile gives the graded C[ell]-module decomposition

    Cbar ~= C[ell]

  when the Artin-reduction h-vector is (1).  The degree-zero generator is the
  unit of Cbar, so this module isomorphism is the natural algebra map generated
  by ell.  Therefore it is an isomorphism of graded C-algebras.
Qed.

Theorem multiplicity_one_degree_three_torsion_has_dimension_at_most_four:
  One has

    dim_C T_3 <= 4.

Proof:
  Since dim Cbar_3=1 and dim R_3=8,

    dim_C Jsat_3=7.

  The ordinary degree-three principal piece is

    J_3=a*R_1.

  We bound the kernel of multiplication by a on R_1.

  On X, multiplication by the quadratic section a gives

    H^0(X,O_X(1)) --a--> H^0(X,O_X(3)).

  Its cokernel is the degree-three section space of the zero scheme of a on X,
  namely Y=Proj(Cbar).  Since e(Cbar)=length(Y)=1, that cokernel has dimension
  one.  Source and target both have dimension eight, so the kernel also has
  dimension one.

  Because R is one-dimensional Cohen--Macaulay, H^0_m(R)=0.  Hence the natural
  map

    R_1 -> H^0(X,O_X(1))

  is injective.  The kernel of a:R_1->R_3 therefore has dimension at most one.
  Since dim R_1=4,

    dim J_3=rank(a:R_1->R_3)>=3.

  Thus

    dim T_3
      = dim(Jsat_3/J_3)
      <= 7-3
      =4.
Qed.

Corollary multiplicity_one_total_embedded_torsion_has_length_at_most_thirteen:
  One has

    length_C(T)<=13.

Proof:
  Sum the degree bounds

    dim T_1=3,
    dim T_2=5,
    dim T_3<=4,
    dim T_4<=1,

  with T_n=0 outside degrees one through four.
Qed.

Now return to the two homogeneous final minimal generators f,g.  At least one
has nonzero image in Cbar, because otherwise the quotient Cbar/(fbar,gbar)
would remain one-dimensional while A is finite length.

Choose one such generator h whose degree is minimal among the final generators
with nonzero image in Cbar.  Put

  n:=deg(h).

Let k denote the other final homogeneous generator.  This is a relabeling of
the original homogeneous minimal pair, not the nonhomogeneous regularized pair
used in the preceding cyclic-connecting file.

Theorem active_core_cut_has_degree_at_least_nineteen:
  One has

    n>=19.

Proof:
  Since Cbar~=C[ell], every nonzero homogeneous element of degree n is a scalar
  multiple of ell^n.  Therefore the saturated final ideal is principal:

    (fbar,gbar)=(ell^n).

  Hence

    length_C(Cbar/(fbar,gbar))=n.

  The exact torsion/core quotient sequence gives

    0 -> T/(T intersect (f,g)B)
      -> A
      -> Cbar/(fbar,gbar)
      -> 0.

  Thus

    N=n+kappa

  with

    0<=kappa<=length(T)<=13.

  Since N>=32,

    n>=32-13=19.
Qed.

Theorem the_second_minimal_cut_is_pure_embedded_torsion:
  The other final generator k has zero image in Cbar.  Hence

    k in T.

  Moreover

    deg(k) in {3,4}.

Proof:
  Suppose instead that kbar is nonzero.  By the choice of h,

    deg(k)>=n.

  Since Cbar=C[ell], there is a scalar c such that

    kbar=c*ell^(deg(k)-n)*hbar.

  Therefore in B

    t:=k-c*ell^(deg(k)-n)*h

  belongs to T_(deg(k)).

  But

    deg(k)>=n>=19>=5

  and T_m=0 for every m>=5.  Hence t=0, so

    k in hB.

  This makes k redundant in the B-ideal (f,g)B.  Equivalently, it is redundant
  modulo Q in I=Q+(f,g), contradicting the assumption that I has exactly six
  minimal generators with four quadratic generators and the two displayed
  higher-degree generators minimal.

  Thus kbar=0 and k belongs to T.

  Since k is a nonzero homogeneous minimal generator, deg(k)>=3.  Since T has
  no components in degree five or above, deg(k)<=4.  Therefore

    deg(k) in {3,4}.
Qed.

Theorem high_core_cut_annihilates_all_embedded_torsion:
  One has

    h*T=0.

Proof:
  The degree bound n>=19 implies h belongs to m^4.  The saturated-core profile
  gives

    m^4*T=0.

  Therefore h*T=0.
Qed.

Theorem active_cut_annihilator_is_exactly_the_saturation_torsion:
  One has

    0:_B h = T.

Proof:
  The preceding theorem gives T subseteq 0:_B h.

  Conversely suppose h*b=0 in B.  Modulo T,

    hbar*bbar=0

  in Cbar=C[ell].  Since hbar is nonzero and C[ell] is a domain, bbar=0.
  Thus b belongs to T.
Qed.

Theorem active_principal_ideal_meets_torsion_trivially:
  One has

    hB intersect T = 0.

Proof:
  Suppose h*b belongs to T.  Modulo T,

    hbar*bbar=0.

  Again hbar is nonzero in the domain Cbar=C[ell], so b belongs to T.  But
  h*T=0, hence h*b=0.
Qed.

Corollary the_two_final_principal_ideals_are_disjoint:
  Since k belongs to T,

    kB subseteq T.

  Therefore

    hB intersect kB=0.
Qed.

Theorem multiplicity_one_two_cut_ideal_splits:
  Put

    L:=(h,k)B.

  Then as B-modules

    L=hB direct_sum kB.

  Consequently the natural short exact sequence

    0 -> hB -> L -> L/hB -> 0

  splits B-linearly and

    L/hB ~= kB.

Proof:
  The sum hB+kB is L by definition, and the preceding corollary proves that
  the intersection is zero.  Projection onto the kB factor gives the splitting.
Qed.

Recall the connecting-rank notation from the preceding conormal reduction.
For

  D:=0:_B h=T,
  M:=L/hB,

apply Hom_B(-,A) to

  0 -> hB -> L -> M -> 0

to obtain

  partial : Ann_A(T) -> Ext^1_B(M,A).

Define

  sigma:=rank_C(partial),
  epsilon:=sigma-dim_C Hom_B(M,A).

Theorem multiplicity_one_connecting_excess_is_nonpositive:
  One has

    partial=0,
    sigma=0,
    epsilon<=0.

Proof:
  The defining short exact sequence splits B-linearly, so its extension class
  is zero and every connecting homomorphism obtained from it is zero.  Hence
  sigma=0.

  Therefore

    epsilon=-dim_C Hom_B(M,A)<=0.
Qed.

Theorem multiplicity_one_height_three_branch_fails_the_order13_tangent_gate:
  No algebra in this e(B)=1 subbranch can satisfy the necessary order-13
  tangent gate

    dim_C Hom_S(I,A)<=N-20.

Proof:
  The preceding low-multiplicity conormal-rank theorem proves that any candidate
  satisfying this tangent gate must have

    epsilon>=6.

  The present splitting theorem instead gives

    epsilon<=0.

  Contradiction.
Qed.

Corollary multiplicity_one_height_three_subbranch_closed:
  The homogeneous q=4, ht(Q)=3, e(B)=1 subbranch contributes no order-13
  candidate passing the necessary tangent-dimension gate.
Qed.

IMPORTANT_NONCONCLUSION:
  This closes only the multiplicity-one h-vector

    (1).

  It does NOT close the remaining low-multiplicity height-three cases

    e=2,3,4,5,

  and makes no claim for the q=4 height-two branch, homogeneous q<=3 branches,
  or the unrestricted nonhomogeneous local deviation-two frontier.

  In particular, no full order-13 algebraicity theorem is claimed.

BOUNDARY:
  The first remaining saturated-core h-vector in the q=4 height-three
  low-multiplicity branch is

    e=2: (1,1).

  The multiplicity-one branch is excluded because length forces the unique
  core-active final cut to have degree at least nineteen, while minimality
  forces the second cut into the degree-three/four embedded torsion.  The two
  principal ideals then meet trivially, so the two-cut extension splits and
  cannot supply the required connecting-rank excess six.

NEXT_BOUNDED_OBJECT:
  Treat only the e=2 h-vector (1,1).  Use its rank-two graded C[ell]-algebra
  structure to determine whether two core-active cuts become associates modulo
  T or leave a single bounded rank-two Koszul-colon carrier.  Do not move to
  the q=4 height-two branch before this test is resolved.