Standalone Cohen--Macaulay saturated-core reduction for the homogeneous q=4,
height-two order-13 deviation-two branch.

SCOPE:
  Continue from

    order13_q4_height2_saturated_curve_core_profile.v

  and retain

    S := C[x1,x2,x3,x4],
    I := Q+(f,g),
    A := S/I,
    length_C(A)=N>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=2,
    deg(f),deg(g)>=3.

Let

  Qsat := saturation(Q),
  B := S/Q,
  T := Qsat/Q = H^0_m(B),
  C := S/Qsat.

The preceding profile proves

  dim C=2,
  depth C>=1,
  e(C) in {1,2,3},

and that the images fbar,gbar form a homogeneous parameter pair on C.

This file treats only the branch

  depth C=2.

It is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

ExternalResult linear_parameter_reduction_for_standard_graded_CM_rings:
  If C is a standard graded Cohen--Macaulay C-algebra of dimension two, two
  general linear forms ell1,ell2 form a regular sequence and

    length(C/(ell1,ell2)) = e(C).

ExternalResult grade_one_CM_ideal_is_principal:
  If P=C[y1,y2,y3] and H is a homogeneous height-one ideal such that P/H is
  Cohen--Macaulay of dimension two, then H is principal.

Theorem the_CM_core_has_a_linear_saturation_equation:
  One has

    (Qsat)_1 != 0.

Proof:
  Suppose (Qsat)_1=0.  Then

    dim C_0=1,
    dim C_1=4.

  Choose a general linear regular sequence ell1,ell2 on C and put

    H:=C/(ell1,ell2).

  Hilbert-series multiplication by (1-t)^2 gives

    dim H_0=1,
    dim H_1=dim C_1-2*dim C_0=2.

  Hence length(H)>=3.  Since length(H)=e(C)<=3, equality holds and

    Hilb_H(t)=1+2*t.

  Therefore

    Hilb_C(t)=(1+2*t)/(1-t)^2,

  whose degree-two coefficient is seven.  Thus dim C_2=7.

  But C is a quotient of B and the established initial height-two profile gives

    dim B_2=6.

  This is impossible.  Hence (Qsat)_1 is nonzero.
Qed.

Corollary the_CM_core_is_line_or_plane_hypersurface:
  Put

    u1:=dim_C (Qsat)_1.

  Then u1 is either one or two.

  If u1=2, then

    C ~= C[s,t]

  and e(C)=1.

  If u1=1, then after a linear change of coordinates

    Qsat=(l,F)

  with l linear and F homogeneous of degree r in S/(l), where

    r=e(C) in {2,3}.

Proof:
  The preceding profile already proves u1<=2 and proves that u1=2 forces the
  line core C~=C[s,t].

  Now assume u1=1 and choose a generator l.  Modulo l, write

    P:=S/(l) ~= C[y1,y2,y3].

  The image H of Qsat in P has height one, and

    P/H ~= C

  is Cohen--Macaulay of dimension two.  By the external grade-one result,

    H=(F)

  is principal.  Since u1 is exactly one, deg(F)>=2.  The multiplicity of the
  plane hypersurface P/(F) is deg(F), and the previous profile gives e(C)<=3.
  Hence deg(F) is two or three.
Qed.

Theorem the_plane_cubic_CM_core_is_incompatible_with_htQ_two:
  The case

    Qsat=(l,F_3)

  with F_3 cubic cannot occur.

Proof:
  In degree two the cubic contributes nothing, so

    (Qsat)_2=l*S_1.

  This space has dimension four.  Since Q_2 is also four-dimensional and

    Q_2 subseteq (Qsat)_2,

  one has

    Q_2=l*S_1.

  Because Q is generated by Q_2,

    Q=l*m.

  The prime (l) contains Q, so ht(Q)<=1, contradicting ht(Q)=2.
Qed.

Corollary exact_CM_height_two_core_inventory:
  In the depth-two branch, the saturated core is exactly one of

    LINE CORE:
      Qsat=(l1,l2),
      e(C)=1,

    PLANE CONIC CORE:
      Qsat=(l,q),
      deg(q)=2,
      e(C)=2.

  No multiplicity-three Cohen--Macaulay core survives.
Qed.

We now close the plane-conic branch.

Assume

  Qsat=(l,q),

where l is linear and q is quadratic not divisible by l.

Theorem exact_four_quadric_normal_form_for_the_conic_core:
  There is a three-dimensional subspace W subset S_1 and a quadratic

    q' = q + l*r

  defining the same saturated ideal (l,q')=(l,q), such that

    Q=(q', l*W).

Proof:
  The degree-two space of Qsat is

    (Qsat)_2=l*S_1 direct_sum C*q

  and has dimension five.

  The four-dimensional subspace Q_2 cannot equal l*S_1, because that would
  again give Q=l*m of height at most one.  Therefore

    dim(Q_2 intersect l*S_1)=3.

  Write this intersection as l*W with dim W=3.  Choose any element of Q_2
  outside l*S_1 and scale it to have q-coefficient one; it has the form

    q'=q+l*r.

  Then q' together with l*W is a basis of Q_2.  Since Q is generated by Q_2,

    Q=(q',l*W).
Qed.

Theorem exact_conic_saturation_torsion:
  One has

    T ~= S/(W,q')(-1),

  and

    Hilb_T(t)=t+t^2,
    length_C(T)=2,
    m^2*T=0.

Proof:
  Since q' already belongs to Q, the quotient

    T=Qsat/Q=(l,q')/(q',l*W)

  is cyclic, generated by the class of l.

  Its annihilator in S is Q:l.  Because q' is not divisible by l,

    (q',l*W):l=(q',W).

  Hence

    T ~= S/(W,q')(-1).

  The subspace W consists of three independent linear forms, so S/W is a
  polynomial ring C[z] in one variable.  The module T is finite length because
  Qsat/Q is a saturation defect.  Therefore q' has nonzero image modulo W.
  Being quadratic, that image is a nonzero scalar multiple of z^2.  Thus

    S/(W,q') ~= C[z]/(z^2),

  proving all assertions.
Qed.

Corollary exact_conic_torsion_annihilator_quotient:
  In B=S/Q,

    length_C(B/Ann_B(T))=2.

Proof:
  Since T is generated by the class of l,

    Ann_B(T)=(Q:l)/Q.

  Therefore

    B/Ann_B(T) ~= S/(Q:l) ~= S/(W,q'),

  which has length two by the preceding theorem.
Qed.

Theorem final_high_degree_pair_kills_and_does_not_intersect_T:
  Put

    L:=(f,g)B.

  Then

    L*T=0,
    L intersect T=0.

Proof:
  The torsion T is supported only in degrees one and two, while f and g have
  degree at least three.  Thus multiplication by either generator sends every
  homogeneous component of T beyond its support, so L*T=0.

  Also every nonzero homogeneous element of L has degree at least three,
  whereas T has no component in degree at least three.  Hence L intersect T=0.
Qed.

Corollary exact_conic_annihilator_inside_A:
  The torsion T embeds into A=B/L, and

    dim_C Ann_A(T)=N-2.

Proof:
  The intersection statement gives the embedding.  Since L*T=0,

    L subseteq Ann_B(T).

  Hence

    A/Ann_A(T) ~= B/Ann_B(T),

  which has length two.  Since length(A)=N, the result follows.
Qed.

Theorem exact_conic_colon_for_the_final_parameter_pair:
  In B,

    (fB : g)=fB+T.

Proof:
  Modulo T the ring is the Cohen--Macaulay conic core C, and fbar,gbar form a
  parameter pair.  Hence they are a regular sequence and

    (fbar : gbar)=(fbar)

  in C.

  If x*g belongs to fB, then modulo T one has

    xbar*gbar in fbar*C,

  so xbar belongs to fbar*C.  Thus x=f*y+t for some t in T.  Conversely every
  such element belongs to the colon because g*T=0.  Therefore

    (fB:g)=fB+T.
Qed.

Put

  M:=L/fB.

Corollary the_second_generator_carrier_is_the_conic_parameter_section:
  There is a B-module isomorphism, up to grading shift,

    M ~= B/(fB+T) ~= C/(fbar).

  Consequently

    Hom_B(M,A) ~= Ann_A(T)

  as C-vector spaces, and

    dim_C Hom_B(M,A)=N-2.

Proof:
  Multiplication by g gives a surjection B->M with kernel (fB:g).  Apply the
  preceding colon theorem.  For Hom, a map from B/(fB+T) to A is determined by
  the image of one, which must be annihilated by f and by T.  The element f is
  already zero in A, leaving exactly Ann_A(T).
Qed.

Theorem plane_conic_CM_core_violates_the_order13_tangent_gate:
  One has

    dim_C Hom_S(I,A) >= N-2.

  Hence the necessary order-13 tangent condition

    dim_C Hom_S(I,A) <= N-20

  is impossible.

Proof:
  From

    0 -> fB -> L -> M -> 0,

  applying Hom_B(-,A) gives an injection

    Hom_B(M,A) -> Hom_B(L,A).

  Maps L->A define maps I->A vanishing on Q, so Hom_B(L,A) is a natural
  subspace of Hom_S(I,A).  Therefore

    dim Hom_S(I,A)
      >= dim Hom_B(L,A)
      >= dim Hom_B(M,A)
      = N-2.

  Since N-2>N-20, the tangent gate fails.
Qed.

Corollary q4_height2_CM_conic_subbranch_is_closed:
  The depth-two, multiplicity-two plane-conic saturated-core branch cannot be
  an order-13 tangent-gate survivor.
Qed.

IMPORTANT_NONCONCLUSION:
  The depth-two LINE CORE

    Qsat=(l1,l2)

  is not closed in this file.  Its finite saturation defect

    T=(l1,l2)/Q

  is a two-generated finite-length module with linear presentation data that
  still requires classification.

  The depth-one saturated-core branch is also untouched.

  No conclusion is asserted for homogeneous q<=3 or for the unrestricted
  nonhomogeneous local deviation-two frontier.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height3_low_multiplicity_frontier_exhausted.
  q4_height2_CM_conic_core_closed.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the finite-length module

    T=(l1,l2)/Q

  when Qsat=(l1,l2), Q is generated by four independent quadrics, and ht(Q)=2.
  Determine whether the four linear coefficient columns force a bounded torsion
  tail strong enough to repeat the conic Hom-carrier closure.

NEXT_BOUNDED_OBJECT:
  Attack only the depth-two line core.  Write the four quadrics as

    q_j=l1*a_j+l2*b_j

  and classify the resulting finite-length cokernel of the linear coefficient
  matrix.  Stop before entering the depth-one deficiency branch.