Standalone four-plane classification for the exact H00 endpoint in the
homogeneous q=4, height-two multiplicity-one, depth-one order-13 deviation-two
program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H00_saturated_incidence_classification.v

  and retain

    S := C[x,y,z,w],
    Q subset Qsat,
    Q generated minimally by exactly four independent quadrics,
    Qsat saturated,
    dim_C (Qsat)_2 = 5,
    T := Qsat/Q,

  in the exact H00 state

    (u1,u2)=(0,3),
    Hilb_(P/Qsat)(t)=2*t/(1-t).

The preceding file classifies Qsat, up to graded linear coordinate change, into
exactly seven quadratic normal forms.  This file performs one bounded task only:
classify the four-dimensional hyperplanes

    Q_2 subset (Qsat)_2

whose generated ideal Q has

    Q^sat = Qsat.

The answer is an exact dual-discriminant criterion.  One of the seven saturated
normal forms admits no such four-plane.  Each of the other six admits precisely
the complement of one explicit quadric in the dual projective four-space.  For
every admissible four-plane the saturation defect is as small as possible:

    T ~= C(-2),
    m*T=0.

No tangent-space estimate is made here.
No H01, H11, or q<=3 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. HYPERPLANES AND THE CYCLIC SATURATION DEFECT
--------------------------------------------------------------------------

Let

    V := (Qsat)_2,
    dim_C V = 5.

Every four-dimensional quadratic generator space is a hyperplane

    W=Q_2=ker(lambda)

for a nonzero covector

    lambda in V^*.

Choose any r in V with lambda(r)=1.  Since Qsat is generated by V and Q is
generated by W,

    Qsat = Q + (r).

Hence T=Qsat/Q is cyclic, generated in degree two by the class tau of r.

Theorem H00_fourplane_defect_is_a_cyclic_colon_module:
  One has

    T ~= S/(Q:r)(-2).

Proof:
  The map

    S(-2) -> T,
    1 |-> tau

  is surjective because Qsat=Q+(r).  Its kernel consists exactly of the
  polynomials a with a*r in Q, namely (Q:r).
Qed.

Theorem H00_fourplane_saturates_back_iff_the_defect_is_finite_length:
  One has

    Q^sat=Qsat

  if and only if T has finite length.

Proof:
  Since Qsat is saturated and contains Q, one always has

    Q^sat subseteq Qsat.

  If T=Qsat/Q has finite length, every homogeneous element of Qsat is killed
  modulo Q by a sufficiently high power of m, so Qsat subseteq Q^sat.
  Hence equality holds.

  Conversely, if Q^sat=Qsat, then Qsat/Q is the homogeneous m-torsion removed by
  saturation, hence is finite length.
Qed.

Thus the four-plane problem is exactly a finite-length problem for one cyclic
module.

--------------------------------------------------------------------------
2. THE H00 SATURATED IDEALS HAVE A LINEAR FIRST-SYZYGY PRESENTATION
--------------------------------------------------------------------------

For every one of the seven H00 saturated normal forms, order its five displayed
quadratic generators as

    f1,f2,f3,f4,f5.

Let

    F0:=S(-2)^5 -> Qsat,
    ei |-> fi.

The H00 Hilbert series gives

    Hilb_(S/Qsat)(t)
      = 1/(1-t)^2 + 2*t/(1-t)
      = (1+2*t-2*t^2)/(1-t)^2.

Consequently

    Hilb_Qsat(t)
      = (5*t^2-6*t^3+2*t^4)/(1-t)^4.

Theorem H00_saturated_ideal_has_pure_linear_resolution:
  For each of the seven normal forms there is an exact minimal graded resolution

    0 -> S(-4)^2
      -> S(-3)^6
      -> S(-2)^5
      -> Qsat
      -> 0.

  In particular the full first-syzygy module of the five quadrics is generated
  by six linear syzygies.

Proof:
  For each normal form the six linear syzygies displayed in Section 4 below are
  direct polynomial identities among f1,...,f5.

  They are C-linearly independent in degree three.  Since

    dim_C S_3 = 20,
    dim_C (S/Qsat)_3 = 6,
    dim_C (Qsat)_3 = 14,

  the kernel of

    S_1 tensor_C V -> (Qsat)_3

  has dimension 20-14=6.  Hence the displayed six syzygies are all minimal
  degree-three first syzygies.

  In each case there are exactly two independent linear relations among those
  six syzygies; direct substitution gives a complex

    0 -> S(-4)^2 -> S(-3)^6 -> S(-2)^5 -> Qsat -> 0.

  The two columns of the left map are independent over Frac(S), so the left map
  is injective.  The alternating Hilbert series of this complex is

    (5*t^2-6*t^3+2*t^4)/(1-t)^4,

  exactly the already determined Hilbert series of Qsat.  Therefore no further
  homology remains and the complex is exact.
Qed.

--------------------------------------------------------------------------
3. SYZYGY CONTRACTION GIVES THE EXACT DEFECT ANNIHILATOR
--------------------------------------------------------------------------

Write

    lambda(fi)=lambda_i.

Let

    s=(a1,...,a5)

be a first syzygy, so

    a1*f1+...+a5*f5=0.

Define its lambda-contraction by

    c_lambda(s):=lambda_1*a1+...+lambda_5*a5 in S.

Let J_lambda be the ideal generated by the contractions of the six minimal
linear first syzygies.

Theorem exact_H00_hyperplane_defect_presentation:
  One has

    T ~= S/J_lambda(-2).

Equivalently,

    (Q:r)=J_lambda.

Proof:
  Let F0=S(-2)^5 with basis ei mapping to fi.  The covector lambda extends
  S-linearly to

    lambda_S:F0 -> S(-2).

  Its kernel is precisely the free S-submodule generated by the quadratic
  hyperplane W=ker(lambda).

  Modding the presentation

    S(-3)^6 -> F0 -> Qsat -> 0

  by that hyperplane submodule leaves one generator in degree two.  The only
  relations on that surviving generator are the images under lambda_S of the
  full first-syzygy module.  Since the first-syzygy module is generated by the
  six displayed linear syzygies, its image is exactly J_lambda.

  Hence

    Qsat/Q ~= S/J_lambda(-2).
Qed.

Corollary exact_H00_saturation_rank_criterion:
  Since J_lambda is generated by linear forms,

    Q^sat=Qsat

  if and only if

    J_lambda=m=(x,y,z,w).

Equivalently, the six contracted linear forms must span S_1.
Qed.

For every admissible hyperplane it then follows immediately that

    T ~= C(-2),
    length_C T=1,
    m*T=0.

--------------------------------------------------------------------------
4. THE SEVEN CONTRACTION MATRICES
--------------------------------------------------------------------------

In every case write

    lambda=(a,b,c,d,e)

in the ordered dual basis to (f1,...,f5).

The rows below are the six minimal linear syzygies.  Contracting a row with
(a,b,c,d,e) produces one linear generator of J_lambda.

--------------------------------------------------
TYPE H00-P2
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x^2, x*y, y^2, x*z, y*z).

Six syzygies:

    (-y,  x,  0,  0,  0)
    ( 0, -y,  x,  0,  0)
    (-z,  0,  0,  x,  0)
    ( 0, -z,  0,  y,  0)
    ( 0, -z,  0,  0,  x)
    ( 0,  0, -z,  0,  y)

Thus every contraction belongs to span_C{x,y,z}.  No contraction contains w.
Therefore

    dim_C (J_lambda)_1 <= 3

for every lambda.

Conclusion:

    H00-P2 admits no saturation-valid four-plane.

--------------------------------------------------
TYPE H00-P1P1-R2
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x*y, x*z, x*w, y*z, y*w).

Six syzygies:

    (-z,  y,  0,  0,  0)
    (-w,  0,  y,  0,  0)
    ( 0, -w,  z,  0,  0)
    (-z,  0,  0,  x,  0)
    (-w,  0,  0,  0,  x)
    ( 0,  0,  0, -w,  z)

The contraction matrix, in the basis (x,y,z,w) of S_1, is

    [ 0, b,-a, 0 ]
    [ 0, c, 0,-a ]
    [ 0, 0, c,-b ]
    [ d, 0,-a, 0 ]
    [ e, 0, 0,-a ]
    [ 0, 0, e,-d ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_P1P1_R2 := b*e-c*d != 0.

--------------------------------------------------
TYPE H00-P1P1-R1
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x*y, x*z, x*w, y^2, y*z).

Six syzygies:

    (-z,  y,  0,  0,  0)
    (-w,  0,  y,  0,  0)
    ( 0, -w,  z,  0,  0)
    (-y,  0,  0,  x,  0)
    (-z,  0,  0,  0,  x)
    ( 0,  0,  0, -z,  y)

The contraction matrix is

    [ 0, b,-a, 0 ]
    [ 0, c, 0,-a ]
    [ 0, 0, c,-b ]
    [ d,-a, 0, 0 ]
    [ e, 0,-a, 0 ]
    [ 0, e,-d, 0 ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_P1P1_R1 := a*e-b*d != 0.

--------------------------------------------------
TYPE H00-P1P1-R0
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x^2, x*y, x*z, y^2, y*w).

Six syzygies:

    (-y,  x,  0,  0,  0)
    (-z,  0,  x,  0,  0)
    ( 0, -z,  y,  0,  0)
    ( 0, -y,  0,  x,  0)
    ( 0, -w,  0,  0,  x)
    ( 0,  0,  0, -w,  y)

The contraction matrix is

    [ b,-a, 0, 0 ]
    [ c, 0,-a, 0 ]
    [ 0, c,-b, 0 ]
    [ d,-b, 0, 0 ]
    [ e, 0, 0,-b ]
    [ 0, e, 0,-d ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_P1P1_R0 := a*d-b^2 != 0.

--------------------------------------------------
TYPE H00-J2-R2
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x^2, x*z, x*w, y*z, y*w).

Six syzygies:

    (-z,  x,  0,  0,  0)
    (-w,  0,  x,  0,  0)
    ( 0, -w,  z,  0,  0)
    ( 0, -y,  0,  x,  0)
    ( 0,  0, -y,  0,  x)
    ( 0,  0,  0, -w,  z)

The contraction matrix is

    [ b, 0,-a, 0 ]
    [ c, 0, 0,-a ]
    [ 0, 0, c,-b ]
    [ d,-b, 0, 0 ]
    [ e,-c, 0, 0 ]
    [ 0, 0, e,-d ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_J2_R2 := b*e-c*d != 0.

--------------------------------------------------
TYPE H00-J2-R1
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x^2, x*y, x*z, y*z, y^2-w*x).

Six syzygies:

    (-y,  x,  0,  0,  0)
    (-z,  0,  x,  0,  0)
    ( 0, -z,  y,  0,  0)
    ( 0, -z,  0,  x,  0)
    ( w, -y,  0,  0,  x)
    ( 0,  0,  w, -y,  z)

The contraction matrix is

    [ b,-a, 0, 0 ]
    [ c, 0,-a, 0 ]
    [ 0, c,-b, 0 ]
    [ d, 0,-b, 0 ]
    [ e,-b, 0, a ]
    [ 0,-d, e, c ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_J2_R1 := a*d-b*c != 0.

--------------------------------------------------
TYPE H00-J2-R0
--------------------------------------------------

Generators:

    (f1,f2,f3,f4,f5)
      =(x^2, x*y, y^2, x*z, y*z-w*x).

Six syzygies:

    (-y,  x,  0,  0,  0)
    ( 0, -y,  x,  0,  0)
    (-z,  0,  0,  x,  0)
    ( 0, -z,  0,  y,  0)
    ( w, -z,  0,  0,  x)
    ( 0,  w, -z,  0,  y)

The contraction matrix is

    [ b,-a, 0, 0 ]
    [ c,-b, 0, 0 ]
    [ d, 0,-a, 0 ]
    [ 0, d,-b, 0 ]
    [ e, 0,-b, a ]
    [ 0, e,-c, b ].

Direct maximal-minor elimination gives

    rank=4  <=>  Delta_J2_R0 := a*c-b^2 != 0.

--------------------------------------------------------------------------
5. WHY THE DISPLAYED QUADRICS ARE THE EXACT DISCRIMINANTS
--------------------------------------------------------------------------

Theorem H00_maximal_minor_discriminant_test:
  For each of the six non-P2 contraction matrices, all 4 by 4 minors vanish
  exactly on the displayed quadric Delta=0 in P(V^*).

Proof:
  Direct determinant expansion gives the following common factors:

    P1P1-R2:  b*e-c*d,
    P1P1-R1:  a*e-b*d,
    P1P1-R0:  a*d-b^2,
    J2-R2:    b*e-c*d,
    J2-R1:    a*d-b*c,
    J2-R0:    a*c-b^2.

  Every maximal minor is the corresponding Delta times a quadratic monomial or
  quadratic expression in a,b,c,d,e.

  Conversely, if Delta!=0, the coordinates entering Delta cannot all vanish in
  the combinations multiplying the maximal minors.  Inspecting the displayed
  matrices yields at least one nonzero 4 by 4 minor.  Hence rank=4.

  If Delta=0, every maximal minor vanishes, so rank<=3.
Qed.

Thus the invalid four-planes form one explicit dual quadric for each of the six
realizable saturated types.

--------------------------------------------------------------------------
6. EXACT H00 FOUR-PLANE CLASSIFICATION
--------------------------------------------------------------------------

Theorem q4_H00_exact_fourplane_classification:
  Let Qsat be one of the seven exact H00 saturated normal forms and let

    W=ker(lambda) subset (Qsat)_2

  be a four-dimensional hyperplane.  Let Q=(W).

  Then Q^sat=Qsat exactly in the following cases.

  H00-P2:
    never.

  H00-P1P1-R2:
    b*e-c*d != 0.

  H00-P1P1-R1:
    a*e-b*d != 0.

  H00-P1P1-R0:
    a*d-b^2 != 0.

  H00-J2-R2:
    b*e-c*d != 0.

  H00-J2-R1:
    a*d-b*c != 0.

  H00-J2-R0:
    a*c-b^2 != 0.

Proof:
  By the exact defect presentation,

    T ~= S/J_lambda(-2).

  The four-plane saturates back to Qsat iff T has finite length, iff the linear
  ideal J_lambda is m-primary, iff its six generators span S_1, iff the
  contraction matrix has rank four.

  Section 4 and the maximal-minor test give exactly the displayed conditions.
Qed.

Corollary H00_P2_saturated_incidence_is_not_realizable_by_four_quadrics:
  The saturated normal form

    (x^2,x*y,y^2,x*z,y*z)

  cannot occur as the saturation of an ideal generated by exactly four
  independent quadrics.
Qed.

Corollary six_H00_saturated_types_are_generically_fourplane_realizable:
  For each of the other six saturated normal forms, saturation-valid
  four-planes form the nonempty Zariski-open subset

    P(V^*) minus V(Delta).

  In particular each of those six saturated types is realized by some
  four-independent-quadric ideal Q of height two.
Qed.

Proof:
  Each displayed Delta is a nonzero quadratic polynomial, so its complement is
  nonempty and Zariski open.  For lambda in that complement, Q^sat=Qsat.
  Saturation changes only m-torsion, so Q and Qsat have the same projective
  minimal primes; since ht(Qsat)=2, one has ht(Q)=2.  The four independent
  quadrics in W are minimal because Q has no linear generators.
Qed.

--------------------------------------------------------------------------
7. THE SATURATION DEFECT COLLAPSES TO ONE SOCLE QUADRIC
--------------------------------------------------------------------------

Theorem universal_H00_valid_fourplane_defect:
  For every saturation-valid H00 four-plane,

    T=Qsat/Q ~= C(-2).

  Hence

    length_C T=1,
    T_2 ~= C,
    T_n=0 for every n!=2,
    m*T=0.

Proof:
  Saturation validity is exactly J_lambda=m.  Substitute into

    T ~= S/J_lambda(-2).
Qed.

Corollary H00_valid_fourplane_has_no_higher_saturation_tail:
  Every valid H00 four-plane has

    T_1=0,
    dim_C T_2=1,
    T_3=0,

  and therefore no degree-three or higher saturation defect survives.
Qed.

This strengthens the earlier H00 bookkeeping, which knew only T_1=0 and
 dim_C T_2=1.

--------------------------------------------------------------------------
8. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_CLASSIFIED:
  q4_height2_multiplicity_one_depth_one_H00_fourplane_discriminants.
  q4_height2_multiplicity_one_depth_one_H00_P2_fourplane_excluded.
  q4_height2_multiplicity_one_depth_one_H00_valid_T_equals_C_shift2.

EXACT_SURVIVING_H00_SATURATED_TYPES:
  H00-P1P1-R2 with b*e-c*d != 0.
  H00-P1P1-R1 with a*e-b*d != 0.
  H00-P1P1-R0 with a*d-b^2 != 0.
  H00-J2-R2 with b*e-c*d != 0.
  H00-J2-R1 with a*d-b*c != 0.
  H00-J2-R0 with a*c-b^2 != 0.

IMPORTANT_NONCONCLUSION:
  This file classifies the original four-dimensional quadratic generator space
  Q_2 inside every H00 saturated normal form and determines the complete
  saturation defect T for every valid four-plane.

  It does NOT yet analyze the final pair f,g.
  It does NOT make a tangent-space estimate.
  It does NOT close H00.
  It does NOT enter H01 or H11.
  It does NOT close the multiplicity-one depth-one branch.
  It does NOT close q=4 height two or full order 13.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H00_residual_module_classified.
  q4_height2_multiplicity_one_depth_one_H00_saturated_incidence_classified.
  q4_height2_multiplicity_one_depth_one_H00_fourplane_classified.
  q4_height2_multiplicity_one_depth_one_H00_saturation_defect_socle_closed.
  not q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  For the six surviving H00 four-plane families, analyze the final homogeneous
  parameter pair f,g on

    0 -> D -> Ccore -> C[s,t] -> 0

  together with the now exact one-dimensional saturation defect

    T ~= C(-2),
    m*T=0,

  and determine a uniform annihilator carrier for H_1(f,g;B) strong enough to
  test the necessary order-13 tangent gate.

NEXT_ACTIONS:
  1. Stay only in H00.
  2. Use m*T=0, so every final form of degree at least three kills T.
  3. Analyze H_1(f,g;Ccore) through the classified H00 residual module D.
  4. Build the weakest uniform annihilator carrier for H_1(f,g;B).
  5. Stop at the first exact tangent inequality; do not enter H01 or H11.
