Standalone exact tangent closure for a syzygy-controlled higher-deviation subclass in the order-13 F_13 semiregularity problem.

This file follows order13_all_artinian_aci_tangent_exact.v.  The current necessary zero-dimensional repair gate is

  t(A) := dim_C Hom_P(I,A) <= N - 20,

for a local Artin algebra A=P/I of length N in a minimal embedding-dimension-four Cohen presentation.

The five-generator / deviation-one branch is already closed by the exact ACI identity t(A)=4N.  The present file records a further published higher-deviation subclass for which the same exact tangent identity follows.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Setup:
  k := C,
  P is a regular local/analytic k-algebra of embedding dimension m>=2,
  I subset m_P^2 is m_P-primary,
  A := P/I is Artinian of length N and embedding dimension m,

  choose a complete-intersection subideal

    J=(f1,...,fm) subset I

  and additional minimal generators

    g1,...,gd

  so that

    I=(J,g1,...,gd),
    mu(I)=m+d.

  For the application below we conservatively assume d>=3.

ExternalResult AleksandrovSyzygyControlledHigherDeviationEquality:
  In Section 8, Proposition 9 of

    A. G. Aleksandrov,
    Deformations of commutative Artinian algebras,
    Algebra i Analiz 34:6 (2022), 1-33;
    English translation: St. Petersburg Math. J. 34:6 (2023), 889-911,

  consider an Artin algebra represented as

    I=(J,g1,...,gd)

  with J a zero-dimensional complete intersection.  Assume that the first
  syzygy module of I is generated by

    (i) the trivial/Koszul-type syzygies coming from J, and
    (ii) the relations of the form labelled (12) in that paper for every gi.

  Under this explicit syzygy-generation hypothesis, Proposition 9 gives

    dim_k T^1(A) = dim_k T^0(A).

  The PDF text extraction renders the section's deviation inequality
  ambiguously.  To remain fail-closed, this certificate uses the proposition
  only for d>=3.  It makes no claim here for deviation d=2.

Imported fundamental cotangent-cohomology sequence:
  For a minimal Cohen presentation A=P/I,

    0 -> T^0(A)
      -> Hom_A(Omega^1_{P/k} tensor_P A,A)
      -> Hom_A(I/I^2,A)
      -> T^1(A)
      -> 0.

  Since P is regular of embedding dimension m,

    Hom_A(Omega^1_{P/k} tensor_P A,A) ~= A^m,

  so its k-dimension is m*N.  Moreover

    Hom_A(I/I^2,A) ~= Hom_P(I,A).

Theorem syzygy_controlled_higher_deviation_tangent_dimension_exact:
  Under the setup and Aleksandrov's explicit syzygy-generation hypothesis,

    dim_k Hom_P(I,A) = m*N.

Proof:
  Taking dimensions in the fundamental exact sequence gives

    dim Hom_P(I,A)
      = m*N - dim T^0(A) + dim T^1(A).

  Aleksandrov's Proposition 9 gives

    dim T^1(A)=dim T^0(A).

  Therefore

    dim Hom_P(I,A)=m*N.
Qed.

Corollary embdim4_syzygy_controlled_higher_deviation_fails_order13_gate:
  If m=4, then

    t(A)=4N.

  Since N>0,

    4N > N-20.

  Hence no embedding-dimension-four Artin algebra in this syzygy-controlled
  higher-deviation subclass can supply positive tangent deficit for the
  zero-dimensional ideal-sheaf repair route.
Qed.

Corollary no_disjoint_union_of_such_components_repairs_the_graph_ideal:
  The tangent deficit

    delta(A):=N-t(A)

  equals

    -3N<0

  on every local component in this subclass.  Since tangent deficits add over
  disjoint support components, adjoining any number of such components cannot
  help reach the required total deficit at least 20.
Qed.

What this does NOT close:
  The argument does not establish Aleksandrov's syzygy-generation hypothesis
  for an arbitrary higher-deviation Artin ideal.

  It also deliberately does not apply Proposition 9 to deviation d=2 in this
  certificate because the accessible PDF text extraction does not resolve the
  inequality symbol reliably enough for a fail-closed use of that endpoint.

  Therefore the smallest untouched local class is now especially sharp:

    embedding dimension = 4,
    deviation d = 2,
    mu(I)=6,
    non-Gorenstein,
    socle dimension >=2,
    length >=32.

  Higher deviations d>=3 also remain open when their first syzygy module is
  not generated by the specific classes required in Proposition 9.

Boundary:
  A large syzygy-controlled higher-deviation subclass is closed with the exact
  identity t(A)=4N, but no universal higher-deviation tangent bound is proved.

First missing object after this closure:
  attack deviation two directly.  Either prove for every minimal
  embedding-dimension-four six-generator Artin algebra

    dim Hom(I,A) > length(A)-20,

  or exhibit a concrete length>=32 counterexample and compute its tangent
  space exactly.
