Standalone socle-map reduction for the unique surviving square-zero torsion
subbranch of the multiplicity-five h=(1,2,2), homogeneous q=4, height-three
order-13 low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e5_122_torsion_self_action_split_reduction.v
    order13_q4_height3_e5_122_first_layer_saturation_compensation_reduction.v

  and work only in the surviving ZERO_SELF_ACTION case

    T^2=0,
    T subseteq J:=Ann_B(T).

Retain

  C:=Cbar=B/T,
  X:=J/L,
  K_1:=(a,ell*b) subset C,

with a,b in C_2, a a zerodivisor, K_0=(a,b) m-primary, and

  eta_1:=dim_C X-dim_C Hom_C(K_1,X).

The preceding reductions prove that every tangent-gate candidate requires

  eta_1>=17,

while every later delayed layer is nonpositive.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded sharpening.  In the square-zero case
the embedded torsion surviving inside X has a one-dimensional graded socle.
Because K_1 is minimally two-generated, arbitrary images of its two minimal
generators into that socle give a two-dimensional plane of C-linear maps.
Grading shows that this plane intersects the ordinary multiplication maps in
at most one dimension, and in zero dimensions when the final-cut ideal already
contains the top torsion line T_3.

Combining this with the exact length-eighteen regular-cubic section in the
square-zero case closes the T_3-contained subcase and reduces the other subcase
to a rigid equality configuration with eta_1=17.

Theorem final_cut_intersection_with_square_zero_torsion_is_top_line_or_zero:
  One has

    L intersect T in {0,T_3}.

Proof:
  The final-cut ideal L is homogeneous and generated in degrees at least three.
  The torsion module T is concentrated in degrees one, two, and three, with

    dim_C T_3=1.

  Therefore L intersect T has no degree-one or degree-two part and is a graded
  subspace of the one-dimensional degree-three line T_3.  Hence it is either
  zero or all of T_3.
Qed.

Put

  T_X:=(T+L)/L ~= T/(T intersect L) subset X.

Theorem the_surviving_torsion_in_X_has_a_one_dimensional_graded_socle:
  The module T_X is nonzero and has one-dimensional C-socle.

  More precisely:

    if L intersect T=0, then
      T_X~=T and Soc_C(T_X)=T_3;

    if L intersect T=T_3, then
      T_X~=T/T_3 and Soc_C(T_X)=T_2 mod T_3.

Proof:
  In ZERO_SELF_ACTION the B-action on T factors through C and the preceding
  cyclic-torsion reduction gives

    T ~= C[z]/(z^3)(-1)

  as a module for the faithful length-three action quotient.  Thus T is a
  length-three uniserial graded string with one-dimensional pieces in degrees
  one, two, and three and one-dimensional top socle T_3.

  Apply the preceding intersection dichotomy.  If no torsion is removed, the
  socle remains T_3.  If T_3 is removed, the quotient is the length-two string
  with top line represented by T_2, which becomes its one-dimensional socle.
Qed.

Let

  S_X:=Soc_C(T_X),

so dim_C S_X=1 and S_X subseteq Soc_C(X).

Theorem the_first_delayed_pair_is_minimally_two_generated:
  The ideal

    K_1=(a,ell*b)

  requires both displayed generators.

Proof:
  The degree-two element a cannot lie in the ideal generated by the degree-three
  element ell*b in the standard graded ring C.

  Conversely, suppose ell*b belonged to (a).  Then

    ell in (a:b)=G.

  Hence 1 belongs to G:ell=Gsat.  But the preceding first-layer saturation file
  proves Gsat is proper.  Contradiction.
Qed.

Theorem arbitrary_socle_values_define_two_independent_square_zero_maps:
  For every ordered pair (s,t) in S_X direct_sum S_X there is a unique C-linear
  homomorphism

    psi_(s,t):K_1 -> T_X subset X

  satisfying

    a |-> s,
    ell*b |-> t.

  Consequently these maps form a two-dimensional subspace

    P subseteq Hom_C(K_1,X).

Proof:
  Because a and ell*b form a minimal generating set of K_1 over the graded
  local ring (C,m_C), every coefficient in every relation

    p*a+q*ell*b=0

  belongs to m_C.  Since S_X is killed by m_C, both p*s and q*t vanish for
  arbitrary s,t in S_X.  Thus every assignment of the two generators to S_X
  respects all relations and defines a C-linear map.

  Evaluation on the two minimal generators identifies the resulting map space
  with S_X direct_sum S_X.  Since dim_C S_X=1, this plane has dimension two.
Qed.

Let

  mu:X -> Hom_C(K_1,X),
  mu(x)(v):=v*x

be the ordinary multiplication map and put

  A_1:=0:_X K_1.

Then

  dim im(mu)=dim X-dim A_1.

Theorem the_square_zero_socle_plane_has_at_most_one_multiplication_direction:
  One has

    dim_C(P intersect im(mu))<=1.

  If L intersect T=T_3, then in fact

    P intersect im(mu)=0.

Proof:
  First suppose L intersect T=0.  Then S_X=T_3 lies in degree three.

  If a multiplication map mu(x) belongs to P, both

    a*x and ell*b*x

  lie in the single degree-three line T_3.  The element ell*b has degree three.
  A degree-three output from multiplication by ell*b could only come from the
  degree-zero part of x.  But

    X_0=J_0=0,

  because J=Ann_B(T) is a proper homogeneous ideal and T is nonzero.  All
  positive-degree parts of x produce degree at least four.  Since mu(x) belongs
  to P, those higher-degree outputs must vanish.  Therefore

    ell*b*x=0.

  Hence every element of P intersect im(mu) lies in the one-dimensional line of
  socle maps

    a |-> S_X,
    ell*b |-> 0.

  Thus the intersection has dimension at most one.

  Now suppose L intersect T=T_3.  Then S_X is represented by T_2 and lies in
  degree two.  Multiplication by a has degree two, so a degree-two output would
  require a degree-zero component of x, which is zero.  Multiplication by
  ell*b has degree three and cannot produce degree two from any nonnegative
  degree.  Hence both generator images vanish, so the multiplication map is
  zero.  Therefore P intersect im(mu)=0.
Qed.

Corollary square_zero_socle_maps_improve_the_universal_deficit_bound:
  One always has

    eta_1<=dim_C A_1-1.

  If L intersect T=T_3, then

    eta_1<=dim_C A_1-2.

Proof:
  The Hom space contains the sum

    im(mu)+P.

  Therefore

    dim Hom_C(K_1,X)
      >=dim im(mu)+dim P-dim(P intersect im(mu)).

  Use

    dim im(mu)=dim X-dim A_1,
    dim P=2,

  together with the preceding intersection bounds, and rearrange the
  definition

    eta_1=dim X-dim Hom_C(K_1,X).
Qed.

Theorem square_zero_regular_cubic_section_has_length_eighteen:
  There is a homogeneous cubic

    q=ell*(a+lambda*b) in K_1

  whose image in C is a nonzerodivisor and such that

    0:_B q=T,
    0:_J q=T.

  Consequently

    length_C(J/qJ)=18,
    dim_C(0:_X q)<=18,
    dim_C A_1<=18.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring C,
  a general constant combination

    q0:=a+lambda*b

  is a nonzerodivisor on C.  Then q:=ell*q0 is again regular on C and belongs
  to K_1 because

    q=ell*a+lambda*ell*b.

  The element q has degree three and m_B^3*T=0, so q kills T.  Conversely,
  regularity on C shows every element killed by q in B belongs to T.  Hence

    0:_B q=T.

  In ZERO_SELF_ACTION one has T subseteq J, so

    0:_J q=J intersect (0:_B q)=T,

  of length three.

  Since B/J has finite length, J has multiplicity five.  The multiplication
  exact sequence by the cubic q on J therefore gives

    length(J/qJ)
      =3*e(J)+length(0:_J q)
      =15+3
      =18.

  Since X=J/L, the quotient X/qX is a quotient of J/qJ, so

    dim(0:_X q)=length(X/qX)<=18.

  Finally K_1 contains q, hence

    A_1=0:_X K_1 subseteq 0:_X q.
Qed.

Corollary the_top_torsion_intersection_subcase_is_closed:
  If

    L intersect T=T_3,

  then

    eta_1<=16.

  Hence no such candidate satisfies the necessary order-13 tangent gate.

Proof:
  The strengthened socle-map bound gives

    eta_1<=dim A_1-2,

  while the cubic section gives dim A_1<=18.  Therefore eta_1<=16, contradicting
  the required eta_1>=17.
Qed.

Theorem every_remaining_dangerous_square_zero_candidate_is_an_exact_equality_case:
  If a ZERO_SELF_ACTION candidate satisfies the necessary order-13 tangent gate,
  then necessarily

    L intersect T=0,
    eta_1=17,
    dim_C(0:_X K_1)=18,
    dim_C(0:_X q)=18,
    length_C(X/qX)=18,
    length_C(J/qJ)=18,
    L subseteq qJ,
    dim_C(P intersect im(mu))=1.

Proof:
  The preceding corollary excludes L intersect T=T_3, so L intersect T=0.

  In this case the socle-map bound and cubic bound give

    eta_1
      <=dim(0:_X K_1)-1
      <=dim(0:_X q)-1
      <=17.

  The tangent gate requires eta_1>=17.  Hence equality holds throughout:

    eta_1=17,
    dim(0:_X K_1)=18,
    dim(0:_X q)=18.

  On finite-dimensional X,

    dim(0:_X q)=length(X/qX),

  so this quotient has length eighteen.  It is a quotient of J/qJ, which also
  has length eighteen.  Therefore the quotient map is an isomorphism and

    L subseteq qJ.

  Finally the dimension estimate for im(mu)+P must also be sharp.  Since P has
  dimension two and eta_1 is only one less than dim(0:_X K_1), the intersection
  P intersect im(mu) must have dimension exactly one.
Qed.

Corollary the_unique_remaining_multiplication_direction_has_fixed_shape:
  In every remaining dangerous candidate there exists x in X_1 such that

    a*x spans T_3 subset X,
    ell*b*x=0.

  Moreover every multiplication map lying in P is a scalar multiple of this
  one.

Proof:
  The equality theorem gives a one-dimensional intersection

    P intersect im(mu).

  In the proof of the intersection bound, every multiplication map in this
  intersection has the form

    a |-> s in T_3,
    ell*b |-> 0.

  Nonzeroness of the intersection makes s nonzero.  The degree-three output
  a*x with deg(a)=2 comes from the degree-one component of x, so one may replace
  x by that homogeneous component.  Since T_3 is one-dimensional, all such
  maps are scalar multiples.
Qed.

Interpretation:
  The square-zero residual is no longer an arbitrary eta_1>=17 case.

  Two socle-valued maps are forced by the embedded torsion.  If the final cut
  already removes T_3, both are genuinely new beyond multiplication and the
  branch closes at eta_1<=16.

  The only surviving configuration has

    T injects into X,
    eta_1=17 exactly,
    0:_X K_1 = 0:_X q of dimension eighteen,
    L subseteq qJ,

  and exactly one socle-valued map is already a multiplication map, represented
  by a degree-one class x with

    a*x !=0 in T_3,
    ell*b*x=0.

IMPORTANT_NONCONCLUSION:
  This file does NOT rule out that exact equality configuration.

  Therefore it does NOT close the full e=5, h=(1,2,2) branch.

  It makes no claim for other h-vectors, q=4 height two, homogeneous q<=3, the
  unrestricted nonhomogeneous frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e5_h122_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Rule out, or realize explicitly, the equality configuration

    T^2=0,
    L intersect T=0,
    eta_1=17,
    dim(0:_X K_1)=18,
    L subseteq qJ,

  together with a degree-one x in X satisfying

    a*x spans T_3,
    ell*b*x=0.

NEXT_BOUNDED_OBJECT:
  Use L subseteq qJ and the exact cubic section J/qJ of length eighteen.
  Determine the degreewise Hilbert function of X/qX.  Equality of total length
  forces X/qX~=J/qJ; combine that with the injected torsion string T subset X
  and the degree-one witness x to test whether the required one-dimensional
  overlap P intersect im(mu) can occur.  Stop at the first exact graded
  multiplication type that realizes eta_1=17.