Standalone tangent closure of the homogeneous q=3, height-one quadratic-core
order-13 deviation-two branch.

SCOPE:
  Let

    S := C[x1,x2,x3,x4],
    I := Q+(f1,f2,f3),
    A := S/I,
    N := length_C(A) >= 32,

  where I is homogeneous and m-primary, mu(I)=6, Q=I_2 is minimally generated
  by exactly three independent quadrics, ht(Q)=1, and

    di := deg(fi) >= 3.

This file performs one bounded task only: prove that the q=3, ht(Q)=1 child
cannot satisfy the necessary order-13 tangent-deficit gate

    dim_C Hom_S(I,A) <= N-20.

No q=3 height-two or height-three child, q<=2 child, unrestricted local branch,
or Oblivion Closure promotion is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

ExternalResult regular_sequence_syzygies_are_Koszul:
  If g1,g2,g3 is a regular sequence in a ring R, then every first syzygy

    p1*g1+p2*g2+p3*g3=0

  is generated by the Koszul syzygies.  Equivalently, modulo the ideal
  (g1,g2,g3), every coefficient pi of a syzygy vanishes.

--------------------------------------------------------------------------
1. CLASSIFY A HEIGHT-ONE NET OF QUADRICS
--------------------------------------------------------------------------

Theorem height_one_three_quadric_core_has_a_common_linear_factor:
  There are a nonzero linear form l and a three-dimensional subspace

    W subset S_1

  such that

    Q=l*W.

Proof:
  Since S is a UFD and ht(Q)=1, the three quadratic generators have a common
  nonconstant factor.

  A common quadratic factor would make all three generators scalar multiples
  of one quadratic, contradicting their linear independence.  Hence the common
  factor has degree one.  Write

    q_i=l*w_i.

  Independence of the q_i implies independence of the w_i, so

    W=span_C{w1,w2,w3}

  has dimension three and Q=l*W.
Qed.

After a linear change of coordinates,

    S/W ~= C[t].

--------------------------------------------------------------------------
2. THE TOP HYPERPLANE CUT IS A THREE-FOLD COMPLETE INTERSECTION
--------------------------------------------------------------------------

Put

    R := S/(l),
    A0 := A/l*A
        ~= R/(fbar1,fbar2,fbar3),

where fbari is the image of fi in R.

Theorem hyperplane_images_form_a_regular_sequence:
  The sequence

    fbar1,fbar2,fbar3

  is a homogeneous regular sequence in the three-dimensional polynomial ring
  R.

Proof:
  Since I is m-primary, A0 is finite-dimensional over C.  Thus the ideal

    (fbar1,fbar2,fbar3)

  has height three in R.  It is generated by exactly three elements in the
  Cohen--Macaulay ring R, hence those elements form a regular sequence.
Qed.

Corollary hyperplane_cut_length:
  Put

    M := length_C(A0).

  Then

    M=d1*d2*d3.
Qed.

--------------------------------------------------------------------------
3. EXPLICIT 3M-DIMENSIONAL TANGENT SUBSPACE
--------------------------------------------------------------------------

Put

    K := Ann_A(l).

The finite-length multiplication sequence for l gives

    dim_C K = dim_C A/l*A = M.

Theorem three_generator_variations_in_the_l_annihilator_are_tangent:
  There is an injective C-linear map

    K^3 -> Hom_S(I,A).

Proof:
  For (a1,a2,a3) in K^3 define a candidate S-linear map by

    Q |-> 0,
    fi |-> ai.

  It remains only to verify the relations.

  Take a relation

    q+p1*f1+p2*f2+p3*f3=0,
    q in Q.

  Reduce modulo l.  Since Q=l*W vanishes modulo l,

    pbar1*fbar1+pbar2*fbar2+pbar3*fbar3=0

  in R.

  By the regular-sequence theorem above, this syzygy is Koszul.  Hence, after
  lifting its Koszul coefficients to S, each pi has the form

    pi = sum_j cij*fj + l*ri

  with the cij arranged in a skew-symmetric Koszul matrix.

  In A all fj vanish, while l*ai=0 because ai belongs to K.  Therefore

    sum_i pi*ai=0.

  Thus the assignment respects every relation and defines an S-linear map

    I -> A.

  Evaluation on f1,f2,f3 recovers a1,a2,a3, so the map K^3 -> Hom_S(I,A) is
  injective.
Qed.

Corollary q3_height1_tangent_lower_bound:

    dim_C Hom_S(I,A) >= 3*M
                         = 3*d1*d2*d3.

--------------------------------------------------------------------------
4. CONTROL THE EMBEDDED HEIGHT-THREE PIECE
--------------------------------------------------------------------------

The multiplication-by-l exact sequence is

    0 -> S/(I:l)(-1) -> A -> A/l*A -> 0.

Hence

    N = M + E,

where

    E := length_C S/(I:l).

Because Q=l*W,

    W subset I:l.

Also fi belongs to I:l for every i, since l*fi belongs to I.  Therefore

    W+(f1,f2,f3) subset I:l,

and consequently

    E <= length_C S/(W,f1,f2,f3).

Now S/W ~= C[t].  Since I is m-primary, not all images of f1,f2,f3 in C[t]
vanish.  Every nonzero homogeneous image is a scalar multiple of t^di.  Thus

    length_C S/(W,f1,f2,f3) <= D,

where

    D := max{d1,d2,d3}.

Therefore

    N <= M+D.

Since the other two degrees are at least three,

    M=d1*d2*d3 >= 9*D.

--------------------------------------------------------------------------
5. TANGENT GATE CONTRADICTION
--------------------------------------------------------------------------

Theorem homogeneous_q3_height1_is_tangent_closed:
  Under the standing hypotheses,

    dim_C Hom_S(I,A) > N-20.

Proof:
  The explicit tangent subspace gives

    dim_C Hom_S(I,A) >= 3*M.

  The length estimate gives

    N-20 <= M+D-20.

  Since M>=9D and D>=3,

    3M-(M+D-20)
      = 2M-D+20
      > 0.

  Hence

    dim_C Hom_S(I,A) >= 3M > N-20.
Qed.

Corollary homogeneous_q3_height1_child_is_excluded:
  No homogeneous q=3 candidate with ht(Q)=1 satisfies the necessary order-13
  tangent-deficit gate.
Qed.

RESULT:
  homogeneous_q3_height1_is_tangent_closed.

IMPORTANT_NONCONCLUSION:
  This file does NOT close q=3 height two or height three.
  It does NOT close q<=2.
  It does NOT close the unrestricted nonhomogeneous local deviation-two branch.
  It does NOT promote Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  homogeneous_q3_height1_is_tangent_closed.
  not homogeneous_q3_closed.
  not homogeneous_q_le_3_closure.
  not OC.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow for this commit.
  2. If green, split the remaining q=3 core by ht(Q)=2 or 3 and attack only
     the first child admitting an unconditional tangent estimate.
