Standalone exact tangent computation for monomial codimension-four almost-complete intersections in the order-13 F_13 semiregularity problem.

This file follows order13_artin_local_tangent_reduction.v.  It closes the monomial subclass of the surviving non-Gorenstein embedding-dimension-four, five-generator Artin algebras.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Setup:
  R := C[x1,x2,x3,x4] localized/completed at the homogeneous maximal ideal.

  Choose integers
    a_i >= 2,
    0 <= b_i < a_i,
  and assume the support of b=(b1,b2,b3,b4) has size at least two, so that

    m := x1^b1 x2^b2 x3^b3 x4^b4

  is not contained in the pure-power complete-intersection ideal and none of the
  four pure powers is redundant.

  Put

    I := (x1^a1, x2^a2, x3^a3, x4^a4, m),
    A := R/I,
    c_i := a_i-b_i > 0.

  Then I is an m-primary monomial almost-complete intersection of height four
  with exactly five minimal generators.

Length formula:
  The standard monomials of A are the exponent vectors

    0 <= e_i < a_i

  that are not componentwise >= b.  Therefore

    N := length_C(A)
       = product_i a_i - product_i c_i.

Theorem pairwise_lcm_syzygy_reduction:
  Let y_1,...,y_4,y_5 in A be the proposed images of the five generators of I
  under an R-linear map I -> A.

  The first syzygy module of a monomial ideal is generated by the pairwise Taylor
  lcm syzygies.  For pairs of pure-power generators, both coefficients are pure
  powers and hence vanish in A, so these relations impose no condition.

  For the pair (x_i^a_i,m), put

    u_i := m / x_i^b_i = product_{j != i} x_j^b_j.

  Its lcm relation becomes exactly

    u_i y_i = x_i^c_i y_5,              (E_i)

  for i=1,2,3,4.

  Hence Hom_R(I,A) is the solution space of these four equations in A^5.
Qed.

Theorem rank_of_u_i_multiplication:
  Multiplication

    M_{u_i}: A -> A

  has rank

    r_i = b_i * product_{j != i} c_j.

Proof:
  A standard monomial x^e survives multiplication by u_i precisely when

    e_i < b_i

  (otherwise the product becomes divisible by m) and

    e_j < c_j = a_j-b_j  for every j != i

  (otherwise a pure power x_j^a_j is reached).

  Thus there are exactly

    b_i * product_{j != i} c_j

  nonzero images.  Since multiplication by a monomial sends distinct surviving
  monomials to distinct monomials, these images are linearly independent.
Qed.

Corollary kernel_of_u_i_multiplication:
  dim ker(M_{u_i}) = N-r_i.
Qed.

Theorem allowable_fifth_generator_images:
  Define

    V := { y in A : x_i^c_i y lies in im(M_{u_i}) for every i }.

  Then

    dim_C V = sum_i r_i.

Proof:
  Because all maps are monomial, the condition may be checked on the standard
  monomial basis x^e of A.

  Fix i.  If x_i^c_i x^e is nonzero in A, then necessarily e_i<b_i and at
  least one coordinate j!=i satisfies e_j<b_j; otherwise the raised monomial
  would be divisible by m and hence zero.

  On the other hand, every nonzero monomial in im(M_{u_i}) has all coordinates
  j!=i at least b_j, because u_i contributes exactly those factors.

  Therefore a nonzero x_i^c_i x^e can never lie in im(M_{u_i}).  Consequently

    x_i^c_i x^e in im(M_{u_i})

  holds if and only if

    x_i^c_i x^e = 0 in A.

  Let

    L(e) := { i : e_i < b_i }.

  Since x^e is a standard monomial of A, L(e) is nonempty.  The equality

    x_i^c_i x^e = 0

  holds automatically for i not in L(e), because e_i+c_i >= b_i+c_i=a_i.

  For i in L(e), the pure-power bound does not kill the product; it is zero in A
  exactly when every j!=i satisfies e_j>=b_j, equivalently when L(e)={i}.

  Hence x^e belongs to V exactly when L(e) has cardinality one.

  For fixed i, the monomials with L(e)={i} are counted by

    b_i choices for e_i in [0,b_i-1]

  and

    c_j choices for e_j in [b_j,a_j-1], j!=i.

  Their number is r_i.  The four classes L(e)={i} are disjoint, so

    dim V = sum_i r_i.
Qed.

Theorem monomial_codim4_ACI_tangent_dimension_exact:
  For every monomial codimension-four almost-complete intersection above,

    dim_C Hom_R(I,A) = 4*N.

Proof:
  Choose y_5 first.  The equations (E_i) are solvable exactly for y_5 in V.
  For such y_5 the previous theorem shows x_i^c_i y_5=0 for every i, so (E_i)
  reduces to

    u_i y_i = 0.

  Thus y_i may be chosen independently from ker(M_{u_i}).  Therefore

    dim Hom_R(I,A)
      = dim V + sum_i dim ker(M_{u_i})
      = (sum_i r_i) + sum_i (N-r_i)
      = 4*N.
Qed.

Corollary monomial_ACI_cannot_supply_order13_tangent_deficit:
  The order-13 ideal-sheaf repair gate requires a finite decoration Q of length N
  to satisfy

    t(Q) <= N-20.

  A monomial codimension-four almost-complete-intersection local component has

    t(Q)=4N.

  Since N>0,

    4N > N-20.

  Therefore no such monomial ACI can contribute positive tangent deficit, and no
  disjoint union built only from these components can repair the graph-union
  Buchweitz--Flenner semiregularity obstruction.
Qed.

Compatibility with linkage:
  Let

    K := (x1^a1,x2^a2,x3^a3,x4^a4).

  Then

    K:m = (x1^c1,x2^c2,x3^c3,x4^c4),

  another complete intersection.  Thus this monomial subclass lies inside the
  one-link-from-a-complete-intersection branch of the general ACI linkage theory.
  The tangent calculation above is stronger for the present purpose because it
  computes the embedded Hilbert tangent dimension exactly rather than merely
  describing the linked resolution.

Boundary:
  The monomial five-generator codimension-four ACI subclass is closed completely:

    t(A)=4*length(A).

  What remains of the mu(I)=5 branch is genuinely nonmonomial.  No general
  linkage theorem located so far transfers the known Gorenstein T^1 lower bound
  across the direct CI link strongly enough to prove

    dim Hom(I,A) > length(A)-20

  for every nonmonomial codimension-four ACI.

First missing object after this closure:
  either

    (A) a tangent/T^1 inequality for nonmonomial grade-four Artinian almost-
        complete intersections strong enough to rule out a tangent deficit of 20,

  or

    (B) a concrete nonmonomial five-generator Artin algebra of embedding dimension
        four and length at least 30 with unexpectedly small Hom(I,A), followed by
        an exact tangent computation.
