Standalone fourth J-adic-layer rank reduction for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_third_J_adic_layer.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    R := S/J ~= C[z,w],
    n := (z,w) subset R,
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

The preceding file proves

  G := J^2*T/J^3*T ~= C(-3)^s,

where

  s = dim_C Syz_1(Q) in {0,1,2},

and closes s=0.  This file treats only the residual cases

  s=1 or s=2

and computes the next layer only up to its exact transverse multiplication
rank.  No stronger vanishing is asserted without an additional argument.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Put

  U := Span_C{z,w},
  V := Span_C{l1,l2}.

Define the fourth transverse layer

  H := J^3*T/J^4*T.

Theorem exact_fourth_layer_quotient:
  There is a natural graded R-module identification

    H ~= J^4/(J^5+(Q intersect J^4)).

  Hence H is generated in ordinary degree four by the image of

    Sym^4(V).

Proof:
  Since T=J/Q,

    J^3*T=(J^4+Q)/Q,
    J^4*T=(J^5+Q)/Q.

  Taking the quotient gives the displayed identification.
Qed.

Theorem the_longitudinal_maximal_ideal_annihilates_the_fourth_layer:
  In both first-layer cases r=4 and r=3,

    n*H=0.

Proof:
  FOUR-RELATION CASE r=4.

  The first J-adic initial forms span

    W=U tensor V.

  Let u be in U and let s4 be in Sym^4(V).  Write s4=v*t with

    v in V,
    t in Sym^3(V).

  Since u*v lies in W, choose a constant combination q of the four quadratic
  generators whose first J-adic initial form is u*v.  Write

    q=u*v+h,

  with h in Sym^2(V).  Then

    q*t = u*s4 + h*t belongs to Q,

  while h*t belongs to J^5.  Therefore u*s4 is zero in H.

  THREE-RELATION CASE r=3.

  The second-layer classification proves

    V*W = U tensor Sym^2(V).

  Multiply this equality by Sym^2(V).  One obtains

    Sym^3(V)*W = U tensor Sym^4(V).

  Thus every element of U tensor Sym^4(V) is a sum of first initial forms
  multiplied by cubic pure-transverse forms.  Replacing each first initial form
  by its lifted quadratic generator changes the sum only by J^5, because the
  J^2 correction is then multiplied by J^3.  Hence every longitudinal multiple
  vanishes in H.
Qed.

Corollary fourth_layer_is_semisimple_over_R:
  There is an integer h with

    0 <= h <= 5

  such that

    H ~= C(-4)^h

  and

    Hilb_H(t)=h*t^4.

Proof:
  H is generated in degree four by a quotient of Sym^4(V), whose dimension is
  five.  The preceding theorem says n annihilates H, so no degree above four
  survives.
Qed.

Theorem fourth_layer_is_generated_by_transverse_multiplication_from_G:
  Multiplication by J induces a surjection

    mu : V tensor_C G_3 -> H_4.

  Consequently

    h <= 2*s.

  Therefore the residual cases satisfy exactly the numerical bounds

    s=1  ==>  h in {0,1,2},
    s=2  ==>  h in {0,1,2,3,4}.

Proof:
  By definition

    J^3*T = J*(J^2*T).

  Passing modulo J^4*T, multiplication by J depends only on the class modulo
  J^3*T, so it factors through G.  In degree four, J contributes only its
  two-dimensional degree-one space V and G contributes only G_3.  Hence the
  displayed map is surjective.

  Since dim V=2 and dim G_3=s,

    h=dim H_4 <= 2*s.
Qed.

Theorem exact_fourth_layer_dimension_from_quadratic_coefficient_syzygies:
  Let

    Syz_2(Q)

  denote the C-vector space of degree-two coefficient syzygies among the four
  minimal quadratic generators of Q, i.e. the kernel of

    S_2 tensor_C Q_2 -> Q_4.

  Put

    a := dim_C Syz_2(Q).

  Then

    h = a-10.

  Equivalently,

    a = 10+h.

Proof:
  The source S_2 tensor Q_2 has dimension

    dim S_2 * dim Q_2 = 10*4 = 40.

  Hence

    dim Q_4 = 40-a.

  Since dim S_4=35,

    dim (S/Q)_4 = 35-(40-a)=a-5.

  The saturated line quotient S/J has degree-four dimension five.  From

    0 -> T -> S/Q -> S/J -> 0

  one gets

    dim T_4=(a-5)-5=a-10.

  The earlier three J-adic quotients are concentrated respectively in degrees
  at most one, two, and three:

    T/J*T has no degree-four part,
    J*T/J^2*T has no degree-four part,
    J^2*T/J^3*T has no degree-four part.

  Therefore

    T_4=(J^3*T)_4.

  Also T begins in degree one, so

    (J^4*T)_4=0.

  Thus

    H_4 ~= T_4,

  and h=a-10.
Qed.

Corollary exact_quadratic_syzygy_windows_in_the_residual_cases:
  One has

    s=1:
      dim_C Syz_2(Q) in {10,11,12};

    s=2:
      dim_C Syz_2(Q) in {10,11,12,13,14}.
Qed.

Corollary zero_fourth_layer_closes_the_transverse_tower_at_J_cubed:
  If

    h=0,

  then

    J^3*T=0.

Proof:
  The condition H=0 says

    J^3*T=J^4*T=J*(J^3*T).

  The finite-length module J^3*T is supported at the homogeneous maximal ideal,
  and J lies in that maximal ideal.  Nakayama's lemma therefore gives

    J^3*T=0.
Qed.

IMPORTANT_NONCONCLUSION:
  The present hypotheses do NOT determine h from s alone.

  In particular, this file does not prove

    s=1 ==> h=0

  and does not prove

    s=2 ==> h<=1

  or any other sharper rank statement.

  The unresolved datum is exactly the rank of

    mu : V tensor G_3 -> H_4,

  equivalently the number

    h=dim H_4=dim Syz_2(Q)-10.

  Any further closure requires a new compatibility statement connecting the
  actual linear syzygies of Q with their degree-two coefficient lifts.  The
  current first-, second-, and third-layer classifications do not by themselves
  supply that statement.

  No tangent-gate contradiction is claimed here.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_third_J_adic_layer_bounded.
  q4_height2_CM_line_core_fourth_layer_reduced_to_rank.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Prove a compatibility constraint on the transverse multiplication map

    mu : V tensor G_3 -> H_4

  using the explicit linear syzygies of Q.  Equivalently, bound or determine

    dim_C Syz_2(Q)-10

  in the cases dim Syz_1(Q)=1 and 2.

NEXT_BOUNDED_OBJECT:
  Normalize one actual linear syzygy in the s=1 case and compute the induced
  degree-two coefficient-syzygy subspace.  Test whether its commutativity
  identities force rank(mu)<2.  Do not enter the depth-one deficiency branch.