Standalone quadratic-subspace reduction for the exact H10 endpoint in the
multiplicity-one, depth-one saturated core of the homogeneous q=4, height-two
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H10_colon_profile.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Ccore := S/Qsat,
    T := Qsat/Q,

with the exact H10 data

    e(Ccore)=1,
    depth_m(Ccore)=1,
    (u1,u2)=(1,4),

and the H10 colon normal form

    P=(l1,l2),
    D:=P/Qsat,
    Hilb_D(t)=t/(1-t),
    J:=(Qsat:l2),
    J is a height-three linear prime,
    l1 in J,
    Qsat=(l1)+l2*J.

The previous file leaves two incidence possibilities for J relative to P.  The
present file does NOT decide that incidence.  Instead it imposes only the
original four-dimensional quadratic generator space

    W:=Q_2 subset (Qsat)_2

and the saturation equality sat(Q)=Qsat.

It proves that W can meet the four-dimensional l1-multiple space in dimension
only two.  The apparent dimension-three alternative would force Qsat to be a
linear--quadric complete intersection of multiplicity two, contradicting H10.

As a consequence the entire saturation defect T is cyclic, generated by the
single class of l1 in degree one, and is controlled by one m-primary colon ideal
of embedding dimension two.

No tangent-space estimate is made.
No H00, H01, or H11 branch is entered.
No q<=3 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE SIX-DIMENSIONAL QUADRATIC SATURATION SPACE
--------------------------------------------------------------------------

Put

    V := (Qsat)_2,
    W := Q_2,
    L := l1*S_1 subset V.

The H10 bookkeeping gives

    dim_C V=6,
    dim_C W=4.

Since l1 is a nonzero linear form,

    dim_C L=4.

The H10 colon normal form also gives

    V = l1*S_1 + l2*J_1.

Because J_1 has dimension three and contains l1, while l2 is independent of
l1, one has

    dim_C (l1*S_1 intersect l2*J_1)=1,

with intersection spanned by l1*l2.  Hence

    dim_C V=4+3-1=6,

consistent with the exact H10 degree-two count.

Define

    r := dim_C(W intersect L).

Theorem H10_quadratic_intersection_rank_is_at_least_two:
  One has

    r>=2.

Proof:
  Both W and L are four-dimensional subspaces of the six-dimensional space V.
  Therefore

    dim(W intersect L)
      >= dim W + dim L - dim V
      =4+4-6
      =2.
Qed.

Theorem H10_quadratic_intersection_rank_is_not_four:
  One has

    r!=4.

Proof:
  If r=4, then W=L=l1*S_1.

  Since Q is generated by its degree-two space W,

    Q=l1*m,

where m is the homogeneous maximal ideal of S.  Thus Q is contained in the
height-one prime (l1), so

    ht(Q)<=1,

contrary to the standing height-two hypothesis.
Qed.

Thus a priori

    r in {2,3}.

--------------------------------------------------------------------------
2. THE RANK-THREE ALTERNATIVE WOULD FORCE MULTIPLICITY TWO
--------------------------------------------------------------------------

Assume for contradiction that

    r=3.

Then there is a three-dimensional subspace

    A subset S_1

such that

    W intersect L=l1*A.

Since W has dimension four, choose

    q in W \ L.

Then

    W = l1*A direct_sum C*q

and, because Q is generated by W,

    Q=(l1*A,q).

The condition q notin L says exactly that q is not divisible by l1.

Theorem rank_three_forces_linear_quadric_saturation:
  Under r=3,

    Qsat=(l1,q).

Proof:
  Since l1 belongs to Qsat=sat(Q), and q belongs to Q, one has

    (l1,q) subset Qsat.

  Conversely every generator of Q lies in (l1,q), so

    Q subset (l1,q).

  Because q is not divisible by l1, the sequence

    l1,q

is regular in the polynomial ring S.  Hence S/(l1,q) is a two-dimensional
Cohen--Macaulay complete intersection.  In particular the homogeneous ideal

    (l1,q)

is saturated with respect to the irrelevant maximal ideal.

  Saturation is monotone, so from Q subset (l1,q) one obtains

    Qsat subset sat(l1,q)=(l1,q).

  Combining both containments gives

    Qsat=(l1,q).
Qed.

Corollary rank_three_has_multiplicity_two:
  Under r=3,

    e(S/Qsat)=2.

Proof:
  The quotient S/(l1,q) is the complete intersection of a linear form and a
  quadric.  Its multiplicity is

    1*2=2.
Qed.

Theorem H10_rank_three_is_impossible:
  The case r=3 cannot occur.

Proof:
  H10 lies in the multiplicity-one branch, so

    e(S/Qsat)=1.

  The preceding corollary would give multiplicity two.  Contradiction.
Qed.

Combining all rank bounds gives the exact value

    r=2.

--------------------------------------------------------------------------
3. EXACT CONSEQUENCE: Qsat IS OBTAINED BY ADJOINING l1
--------------------------------------------------------------------------

Theorem H10_exact_quadratic_intersection_rank:
  One has

    dim_C(Q_2 intersect l1*S_1)=2.
Qed.

Let

    pi:V -> V/L

be the quotient map.  Since dim W=4 and dim(W intersect L)=2,

    dim pi(W)=2.

But dim(V/L)=2.  Hence pi(W)=V/L.

Theorem H10_quadrics_surject_onto_the_non_l1_saturation_directions:
  One has

    W+L=V.

Proof:
  This is equivalent to surjectivity of pi|_W, proved above.
Qed.

Theorem H10_saturation_is_Q_plus_the_single_linear_form:
  One has

    Qsat=Q+(l1).

Proof:
  The H10 colon profile gives

    Qsat=(l1)+l2*J.

  Thus Qsat is generated by l1 together with its degree-two space V.

  The preceding theorem gives

    V=W+l1*S_1.

  The space W is Q_2 and l1*S_1 lies in the ideal (l1).  Therefore every
  degree-two generator of Qsat lies in Q+(l1).

  Hence

    Qsat subset Q+(l1).

  The reverse containment is immediate because Q subset Qsat and l1 in Qsat.
Qed.

Corollary H10_saturation_defect_is_cyclic:
  The finite-length module

    T=Qsat/Q

is generated by the single degree-one class

    tau := l1 mod Q.
Qed.

This excludes any new minimal saturation generator in degree two in H10.

--------------------------------------------------------------------------
4. THE CYCLIC SATURATION DEFECT HAS AN m-PRIMARY COLON
--------------------------------------------------------------------------

Define

    C := (Q:l1).

Theorem H10_exact_cyclic_torsion_presentation:
  Multiplication by l1 induces a graded isomorphism

    S/C(-1) ~= T.

Proof:
  Since Qsat=Q+(l1), every class in T is represented by a multiple of l1.
  Therefore the map

    S(-1) -> T,
    f |-> f*l1 mod Q

is surjective.

  Its kernel is exactly

    (Q:l1)=C.

  The first isomorphism theorem gives the result.
Qed.

Corollary H10_colon_C_is_m_primary:
  The ideal C=(Q:l1) is m-primary.

Proof:
  The saturation defect T is finite-dimensional over C.  The preceding
  isomorphism identifies S/C with a grading shift of T, so S/C has finite
  length.  Hence C is m-primary.
Qed.

Theorem H10_colon_C_has_exactly_two_linear_forms:
  One has

    dim_C C_1=2.

Proof:
  A linear form a lies in C_1 exactly when

    a*l1 in Q_2=W.

  Multiplication by the nonzero linear form l1 identifies S_1 with L=l1*S_1.
  Therefore

    dim C_1
      =dim(W intersect L)
      =2.
Qed.

Corollary H10_cyclic_torsion_has_embedding_dimension_two:
  The Artinian quotient S/C satisfies

    dim_C(S/C)_0=1,
    dim_C(S/C)_1=2.

  Equivalently, after a linear coordinate change, C contains exactly two
  independent linear forms and S/C is an Artinian quotient of a polynomial
  ring in two variables with embedding dimension two.
Qed.

The known H10 degree data become

    dim_C T_1=1,
    dim_C T_2=2,

which agree with

    T ~= S/C(-1).

Indeed the degree-one value of S/C is exactly two.

--------------------------------------------------------------------------
5. UNIFORMITY ACROSS H10-OFF AND H10-ON
--------------------------------------------------------------------------

The entire rank argument above used only

    Qsat=(l1)+l2*J,
    dim J_1=3,
    l1 in J,
    dim Q_2=4,
    e(S/Qsat)=1,
    sat(Q)=Qsat.

It did NOT use whether

    l2 in J

or

    l2 notin J.

Therefore both incidence cases from the preceding H10 colon profile inherit the
same exact quadratic reduction:

    dim(Q_2 intersect l1*S_1)=2,
    Qsat=Q+(l1),
    T ~= S/(Q:l1)(-1),
    (Q:l1) is m-primary,
    dim_C(Q:l1)_1=2.

The incidence bit remains genuinely separate and is not decided here.

--------------------------------------------------------------------------
6. SHARP H10 BOUNDARY AFTER THE QUADRATIC REDUCTION
--------------------------------------------------------------------------

The H10 endpoint is now reduced to the following exact data.

SATURATED CORE:

    Qsat=(l1)+l2*J,
    J a height-three linear prime,
    l1 in J.

INCIDENCE:

    H10-OFF: l2 notin J,
    H10-ON:  l2 in J.

ORIGINAL FOUR QUADRICS:

    W=Q_2 subset (Qsat)_2,
    dim W=4,
    dim(W intersect l1*S_1)=2,
    W+l1*S_1=(Qsat)_2.

SATURATION DEFECT:

    Qsat=Q+(l1),
    T=Qsat/Q is cyclic on l1 mod Q,
    T ~= S/C(-1),
    C=(Q:l1) m-primary,
    dim C_1=2.

This removes the only other possible quadratic intersection rank.

IMPORTANT_NONCONCLUSION:
  This file does NOT determine whether H10-OFF or H10-ON is realizable.

  It does NOT classify the m-primary embedding-dimension-two colon

    C=(Q:l1)

beyond its exact linear rank.

  It does NOT classify the higher Hilbert function of T.
  It does NOT make a tangent-space estimate.
  It does NOT close H10, the multiplicity-one branch, q=4, or order 13.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H10_colon_classified.
  q4_height2_multiplicity_one_depth_one_H10_quadratic_rank_exact_two.
  q4_height2_multiplicity_one_depth_one_H10_torsion_cyclic.
  not q4_height2_multiplicity_one_depth_one_H10_incidence_closed.
  not q4_height2_multiplicity_one_depth_one_H10_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the embedding-dimension-two m-primary colon

    C=(Q:l1)

using the two explicit saturated incidence forms

    H10-OFF: Qsat=(l1,l2*m1,l2*m2),
    H10-ON:  Qsat=(l1,l2^2,l2*m),

and the condition that Q_2 is a four-dimensional subspace of (Qsat)_2 whose
intersection with l1*S_1 has dimension exactly two.

NEXT_ACTIONS:
  1. Stay only in H10.
  2. Split H10-OFF and H10-ON.
  3. Normalize the two-dimensional linear space C_1=(Q:l1)_1.
  4. Determine the forced quadratic part C_2 from the two remaining quadrics.
  5. Stop before tangent-space estimates.
