Standalone cyclic-colon classification for the unique surviving H01-C5 chain
value m=3 in the homogeneous q=4, height-two multiplicity-one, depth-one
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_degree6_persistence.v

  and retain

    S = C[x1,x2,x3,x4],
    Q = (q1,q2,q3,q4),
    B = S/Q,
    Qsat = Q^sat,
    Ccore = S/Qsat,
    T = Qsat/Q,

  in the unique surviving H01-C5 state

    m = 3,
    sigma = 5.

The preceding file proves that there is a cubic

    gamma in (Qsat)_3

such that

    Qsat = Q + (gamma)

and the full saturation defect is cyclic:

    T ~= S/K(-3),
    K := (Q:gamma).

This file performs one bounded task only: classify the possible linear embedding
dimension of the Artinian colon quotient S/K and identify it exactly with the
previous quartic Betti gap.  The result is a three-way trichotomy: residue-field,
one-variable chain, or genuine two-variable Artin quotient.

No branch of the trichotomy is excluded here.
No tangent-space estimate is made.
No H01-C4, q<=3, or full order-13 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE COLON IS ARTINIAN AND HAS EMBEDDING DIMENSION AT MOST TWO
--------------------------------------------------------------------------

Put

    R := S/K = S/(Q:gamma).

Because

    T ~= R(-3)

and T has finite length, R has finite length.  Therefore K is homogeneous
m-primary.

The preceding m=3 quartic reduction proves

    dim_C K_1 >= 2.

Hence

    e_col := dim_C R_1
           = dim_C S_1 - dim_C K_1
           = 4 - dim_C K_1
           <= 2.

Since R is a nonzero standard graded quotient,

    e_col in {0,1,2}.

Theorem H01_C5_m3_cyclic_colon_embedding_dimension_at_most_two:
  The Artinian colon quotient R=S/(Q:gamma) has embedding dimension

    e_col in {0,1,2}.
Qed.

Equivalently,

    dim_C K_1 in {4,3,2}.

--------------------------------------------------------------------------
2. THE BETTI GAP IS EXACTLY THE COLON LINEAR CODIMENSION
--------------------------------------------------------------------------

Retain the quartic Betti notation used in the preceding C5 files:

    a := beta_(2,4)(B),
    c := beta_(3,4)(B).

Those files prove the exact identity

    dim_C B_4 = 15 + a - c.

On the other hand, because

    0 -> T -> B -> Ccore -> 0

is graded exact and

    T ~= R(-3),

one has

    dim_C T_4 = dim_C R_1 = e_col.

For m=3 the exact saturated-core value is

    dim_C Ccore_4 = 9.

Therefore

    dim_C B_4 = 9 + e_col.

Comparing with the Betti identity gives

    15 + a - c = 9 + e_col,

so

    c - a = 6 - e_col.

Theorem H01_C5_m3_Betti_gap_equals_colon_codimension:
  One has

    beta_(3,4)(B) - beta_(2,4)(B)
      = 6 - dim_C R_1
      = 2 + dim_C K_1.
Qed.

Thus the previously known possibilities

    c-a in {4,5,6}

are not merely numerical alternatives: they are exactly the three possible
linear-colon types.

--------------------------------------------------------------------------
3. TYPE E0: RESIDUE-FIELD COLON
--------------------------------------------------------------------------

Assume

    e_col = 0.

Then

    dim_C K_1 = 4,

so K contains all of S_1.  Since K is a proper homogeneous ideal,

    K subset m,

while S_1 subset K implies

    m subset K.

Hence

    K = m.

Therefore

    R ~= C

and

    T ~= C(-3).

Its Hilbert series is

    Hilb_R(t) = 1,
    Hilb_T(t) = t^3.

The Betti gap is

    c-a = 6.

Theorem H01_C5_m3_colon_type_E0:
  The following are equivalent:

    dim_C R_1 = 0,
    dim_C K_1 = 4,
    K = m,
    T ~= C(-3),
    c-a = 6.
Qed.

No contradiction with the H01-C5 hypotheses is claimed here.

--------------------------------------------------------------------------
4. TYPE E1: ONE-VARIABLE CHAIN COLON
--------------------------------------------------------------------------

Assume

    e_col = 1.

Then

    dim_C K_1 = 3.

Choose independent linear forms z1,z2,z3 spanning K_1 and complete them to
coordinates

    S = C[z1,z2,z3,u].

Put

    L := (z1,z2,z3).

Modulo L, the m-primary homogeneous ideal K becomes a homogeneous finite-colength
ideal in C[u].  Every such ideal is generated by one power u^s.  Since e_col=1,
u is not in K, so s>=2.

Therefore, after a linear coordinate change,

    K = L + (u^s)

for a unique integer s>=2, and

    R ~= C[u]/(u^s).

Hence

    Hilb_R(t) = 1+t+...+t^(s-1),

and

    Hilb_T(t) = t^3+t^4+...+t^(s+2).

The Betti gap is

    c-a = 5.

Theorem H01_C5_m3_colon_type_E1:
  If dim_C R_1=1, then after a linear coordinate change

    K=(z1,z2,z3,u^s),
    s>=2,

    R ~= C[u]/(u^s),
    T ~= C[u]/(u^s)(-3),
    c-a=5.
Qed.

Thus the entire saturation defect is a consecutive one-dimensional chain in
this branch.

--------------------------------------------------------------------------
5. TYPE E2: GENUINE TWO-VARIABLE ARTIN COLON
--------------------------------------------------------------------------

Assume

    e_col = 2.

Then

    dim_C K_1 = 2.

Choose independent linear forms z1,z2 spanning K_1 and complete them to
coordinates

    S=C[z1,z2,u,v].

Put

    L:=(z1,z2).

The image of K in

    S/L ~= C[u,v]

is a homogeneous (u,v)-primary ideal I with

    I_1=0,

because K_1=L_1 exactly.

Therefore

    K = L + I,
    R ~= C[u,v]/I,

where I is homogeneous, (u,v)-primary, and contains no linear form.

Consequently the Hilbert function of R begins

    1,2,h_2,h_3,...,0

with

    0 <= h_n <= n+1

and the standard Macaulay growth conditions.  No sharper tail is forced by the
current hypotheses alone.

The saturation defect is

    T ~= (C[u,v]/I)(-3),

and the Betti gap is

    c-a = 4.

Theorem H01_C5_m3_colon_type_E2:
  If dim_C R_1=2, then after a linear coordinate change

    K=(z1,z2)+I(u,v),

where I is a homogeneous (u,v)-primary ideal with I_1=0.  Moreover

    T ~= (C[u,v]/I)(-3),
    c-a=4.
Qed.

This is the only branch in which the cyclic defect can have genuinely
2-dimensional degree-one growth.

--------------------------------------------------------------------------
6. EXACT THREE-WAY CLASSIFICATION
--------------------------------------------------------------------------

Theorem q4_H01_C5_m3_cyclic_colon_trichotomy:
  Exactly one of the following occurs.

  H01-C5-E0:
    K=m,
    Hilb_R=1,
    T~=C(-3),
    c-a=6.

  H01-C5-E1:
    K=(z1,z2,z3,u^s) after coordinates for a unique s>=2,
    Hilb_R=1+t+...+t^(s-1),
    T~=C[u]/(u^s)(-3),
    c-a=5.

  H01-C5-E2:
    K=(z1,z2)+I(u,v) after coordinates,
    I homogeneous (u,v)-primary with I_1=0,
    R~=C[u,v]/I,
    T~=R(-3),
    c-a=4.

Proof:
  Sections 1--5 classify the three possible values e_col=0,1,2.  They are
  mutually exclusive because e_col=dim_C R_1 is intrinsic, and exhaustive
  because e_col<=2.
Qed.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_colon_embedding_dimension_at_most_two.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_Betti_gap_colon_identity.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_cyclic_colon_trichotomy.

CURRENT_C5_STATUS:
  H01-C5 with m>=4 is empty.
  H01-C5 with m=3 has cyclic saturation defect and exactly three colon types
  E0, E1, E2 as above.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude E0, E1, or E2.
  It does NOT close H01-C5 m=3.
  It does NOT close H01.
  It does NOT make a tangent-space estimate.
  It does NOT enter H01-C4.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_saturation_cyclic.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_colon_classified.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3.  Test the E0 and E1 colon types first against the
  five-linear-first-syzygy matrix and the exact identity c-a=6 or 5.  Determine
  whether either low-embedding-dimension colon forces a common factor, an
  impossible coefficient rank, or a direct tangent carrier.  Leave the genuine
  two-variable E2 type untouched until E0/E1 are decided.

NEXT_ACTIONS:
  1. Stay only in H01-C5 m=3.
  2. Treat E0 and E1 before E2.
  3. Push the linear colon generators through the Qsat syzygies involving gamma.
  4. Record the first forced coefficient-rank consequence.
  5. Stop before E2, H01-C4, tangent estimates outside C5, or q<=3.
