Standalone linkage-height contradiction for the final multiplicity-three
h=(1,1,1) row of the homogeneous q=4, height-three order-13
low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_degree3_hvector_linkage_impossible.v
    order13_q4_height3_e4_121_square_zero_socle_map_closed.v
    order13_q4_height3_e3_12_cyclic_torsion_linear_core_closed.v

  and work only with

    S := C[x1,x2,x3,x4],
    Q := (q1,q2,q3,q4),

  where q1,q2,q3,q4 are linearly independent homogeneous quadrics and

    ht(Q)=3.

Put

  R := S/(q1,q2,q3),
  q := image of q4 in R,
  U := saturation(q*R),
  K := 0:_R q,
  Cbar := R/U.

Assume the final surviving height-three row

  e(S/Q)=3,
  h(Cbar/ell*Cbar)=(1,1,1)

for a general linear nonzerodivisor ell on Cbar.

The established linkage identities are

  U=0:_R K,
  K=0:_R U,
  K(2) ~= omega_Cbar.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded closure step.  For h=(1,1,1),
canonical linkage forces U to contain two independent linear classes while K
contains one nonzero linear class.  Because K annihilates U, that one linear
class annihilates both independent linear saturation classes.  Lifting to S
then places two independent quadrics of the regular-sequence span inside one
common linear factor.  The three-quadric ideal is consequently contained in a
two-generated ideal, contradicting height three.

No conormal or tangent-rank estimate is needed.

Theorem exact_Hilbert_series_for_the_e3_111_linkage_pair:
  One has

    Hilb_Cbar(t)=(1+t+t^2)/(1-t),

    Hilb_U(t)=(2*t+2*t^2+t^3)/(1-t),

    Hilb_K(t)=(t+t^2+t^3)/(1-t).

  Consequently

    dim_C U_1=2,
    dim_C K_1=1.

Proof:
  The assumed Artin-reduction h-vector gives

    Hilb_Cbar(t)=(1+t+t^2)/(1-t).

  Since

    R=S/(q1,q2,q3)

  is the one-dimensional complete intersection of three quadrics,

    Hilb_R(t)=(1+t)^3/(1-t)
             =(1+3*t+3*t^2+t^3)/(1-t).

  Therefore

    Hilb_U
      =Hilb_R-Hilb_Cbar
      =(2*t+2*t^2+t^3)/(1-t).

  For K, the established canonical-linkage identity gives

    K(2) ~= omega_Cbar.

  Graded canonical-module reciprocity in dimension one gives

    Hilb_omega_Cbar(t)
      =t*(1+t^(-1)+t^(-2))/(1-t).

  Hence

    Hilb_K(t)
      =t^2*Hilb_omega_Cbar(t)
      =(t+t^2+t^3)/(1-t).

  Reading degree one gives

    dim_C U_1=2,
    dim_C K_1=1.
Qed.

Choose a basis

  v,w in U_1

and choose

  0 != z in K_1.

Because the defining ideal (q1,q2,q3) has no linear forms, the natural map

  S_1 -> R_1

is an isomorphism.  We therefore use the same symbols v,w,z for their unique
linear lifts to S_1.

Theorem the_unique_linear_annihilator_kills_two_independent_linear_classes:
  In R one has

    z*v=0,
    z*w=0.

Proof:
  The established double-annihilator identity is

    K=0:_R U.

  Thus every element of K annihilates every element of U.  Apply this to

    z in K_1

  and

    v,w in U_1.
Qed.

Corollary two_independent_factored_quadrics_lie_in_the_three_quadric_span:
  In S,

    z*v,
    z*w

  belong to the C-linear span of q1,q2,q3, and they are linearly independent.

Proof:
  The preceding products vanish in R, so they belong to

    (q1,q2,q3) subset S.

  They have degree two.  Since q1,q2,q3 are homogeneous quadrics, the degree-two
  part of their ideal is exactly their C-linear span.  Thus both products lie in
  that span.

  For independence, suppose

    alpha*z*v + beta*z*w = 0

  in S.  Then

    z*(alpha*v+beta*w)=0.

  The polynomial ring S is a domain and z is a nonzero linear form, so

    alpha*v+beta*w=0.

  The classes v,w form a basis of U_1 and hence are independent in R_1; because
  S_1 -> R_1 is an isomorphism, their lifts are independent in S_1.  Therefore

    alpha=beta=0.
Qed.

Theorem two_common_factor_quadrics_force_height_at_most_two:
  The ideal

    (q1,q2,q3)

  has height at most two.

Proof:
  The three quadrics q1,q2,q3 are linearly independent because they form a
  regular sequence of quadrics.  The preceding corollary supplies two
  independent elements

    z*v,
    z*w

  in their three-dimensional degree-two span.  Extend them to a basis

    z*v,
    z*w,
    p

  of that span.

  A constant invertible change of basis among homogeneous generators does not
  change the generated ideal, so

    (q1,q2,q3)=(z*v,z*w,p).

  But

    (z*v,z*w,p) subseteq (z,p).

  The ideal (z,p) is generated by two elements.  By the height theorem,

    ht(z,p)<=2.

  Hence

    ht(q1,q2,q3)<=2.
Qed.

Theorem e3_h111_height3_row_is_impossible:
  There is no homogeneous four-independent-quadric height-three configuration
  satisfying

    e(S/Q)=3,
    h(Cbar/ell*Cbar)=(1,1,1).

Proof:
  The standing construction of R uses q1,q2,q3 as a regular sequence, so

    ht(q1,q2,q3)=3.

  The preceding theorem forces

    ht(q1,q2,q3)<=2,

  a contradiction.
Qed.

Corollary final_q4_height3_low_multiplicity_row_is_closed_negatively:
  The final surviving row

    e=3,
    h=(1,1,1),
    Hilb_T=2*t+3*t^2+2*t^3

  is unrealizable in the four-independent-quadric height-three model.
Qed.

Corollary q4_height3_low_multiplicity_frontier_is_exhausted:
  Combining the established row inventory with the previously closed or
  excluded rows, there is no remaining e in {1,2,3,4,5,6} height-three
  low-multiplicity row for q=4.

Proof:
  The degree-three h-polynomial linkage file reduced the then-open inventory to

    e=4, h=(1,2,1),
    e=3, h=(1,2),
    e=3, h=(1,1,1).

  The e=4, h=(1,2,1) row was subsequently closed by the square-zero socle-map
  argument.

  The e=3, h=(1,2) row was subsequently closed by the cyclic linear-core
  argument.

  The present theorem excludes the last row e=3, h=(1,1,1).

  Therefore the q=4, height-three low-multiplicity row inventory is exhausted.
Qed.

Interpretation:
  The final height-three row does not survive long enough to reach the conormal
  connecting-rank gate.  Its canonical residual annihilator already creates a
  forbidden common linear factor pattern among two independent members of the
  three-quadric regular-sequence span.

  Thus the bounded homogeneous q=4, ht(Q)=3 low-multiplicity frontier is closed
  at the level of the established row inventory.

IMPORTANT_NONCONCLUSION:
  This file does NOT close

    q=4, ht(Q)=2,
    homogeneous q<=3,
    the unrestricted nonhomogeneous local deviation-two frontier,
    full order-13 closure,
    or generic F_13 algebraicity.

  It does not promote any pseudo-formal theorem to Lean or Coq verification.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height3_low_multiplicity_frontier_exhausted.
  not q4_height2_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

NEXT_BOUNDED_OBJECT:
  Return to the established four-quadric height split and isolate only the
  q=4, ht(Q)=2 branch.  Determine its exact saturated-core dimensional profile
  before importing any height-three conormal estimates.
