Standalone quadratic-core/two-step Bockstein sharpening for the multiplicity-five
h=(1,3,1) subbranch of the homogeneous q=4, height-three order-13
low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_e5_131_three_step_bockstein_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has

    h(Cbar/ell*Cbar)=(1,3,1).

  The exact linkage table gives

    Hilb_T(t)=t^2,
    m_B*T=0,
    Ann_B(T)=m_B.

  The preceding three-step reduction writes

    fbar=ell^r*alpha,
    gbar=ell^(r+k)*beta,

  with

    r=d-3>=0,
    k=D-d>=0,
    alpha,beta in Cbar_3,
    J_i:=(alpha,ell^i*beta),

  and proves that a tangent-gate candidate must have total connecting excess

    epsilon>=19.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one structural sharpening: the h=(1,3,1) core
stabilizes already in degree two.  Therefore the degree-three baseline itself
has a common ell factor, and only two delayed Bockstein layers can contribute
positively.  The remaining obstruction is a quadratic baseline deficit in a
finite interval.

Theorem parameter_multiplication_is_iso_from_degree_two:
  For every n>=2,

    ell:Cbar_n -> Cbar_(n+1)

  is a vector-space isomorphism.

Proof:
  Since

    Hilb_Cbar(t)=(1+3*t+t^2)/(1-t),

  one has

    dim_C Cbar_0=1,
    dim_C Cbar_1=4,
    dim_C Cbar_n=5 for every n>=2.

  Multiplication by ell is injective in every degree because ell is a
  nonzerodivisor on Cbar.  For n>=2 the source and target both have dimension
  five, hence the injection is an isomorphism.
Qed.

Corollary cubic_baseline_has_unique_quadratic_predecessors:
  There are unique

    a,b in Cbar_2

  such that

    alpha=ell*a,
    beta=ell*b.

  Put

    K_i:=(a,ell^i*b).

  Then for every i>=0,

    J_i=ell*K_i,

  and multiplication by ell gives a Cbar-module isomorphism

    K_i ~= J_i.

  Moreover

    Lbar=(fbar,gbar)=ell^(r+1)*K_k.

  Writing

    s:=r+1=d-2,

  one has s>=1.
Qed.

Theorem quadratic_baseline_is_m_primary:
  The ideal

    K_0=(a,b)

  is m-primary in Cbar.

Proof:
  The preceding low-multiplicity reduction proves J_k is m-primary.  Since

    J_k subseteq J_0,

  the larger homogeneous ideal J_0 is also m-primary.

  Now J_0=ell*K_0.  If a homogeneous prime contains K_0, then it contains
  ell*K_0=J_0, hence it is the homogeneous maximal ideal.  Thus the radical of
  K_0 is the homogeneous maximal ideal.
Qed.

Define

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem quadratic_colon_saturation_is_reached_after_two_steps:
  One has

    (Gsat/G)_n=0

  for every n>=2.  Consequently

    ell^2*(Gsat/G)=0,
    G:ell^2=Gsat,

  and

    G:ell^j=Gsat

  for every j>=2.

Proof:
  Let x in Gsat be homogeneous of degree n>=2.  Choose m>=0 such that

    ell^m*x*b belongs to (a).

  Write

    ell^m*x*b=a*c

  with c homogeneous of degree n+m.  By the first theorem, multiplication by
  ell^m gives an isomorphism

    Cbar_n -> Cbar_(n+m).

  Hence c=ell^m*c0 for a unique c0 in Cbar_n.  Therefore

    ell^m*(x*b-a*c0)=0.

  Since ell is a nonzerodivisor, cancellation gives

    x*b=a*c0,

  so x belongs to G.  Thus G and Gsat agree in every degree at least two.

  If x in Gsat has degree below two, ell^2*x has degree at least two and still
  belongs to Gsat, hence lies in G.  Therefore ell^2*Gsat subseteq G, which is
  equivalent to Gsat subseteq G:ell^2.  The reverse inclusion is automatic
  from the definition of saturation.  Hence G:ell^2=Gsat, and all later
  colons are equal as well.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i.

Lemma exact_quadratic_layer_annihilator:
  The class

    u_i:=ell^(i-1)*b mod K_i

  generates V_i and has annihilator

    Ann_Cbar(u_i)=(G:ell^(i-1),ell).

  In particular, for every i>=3,

    V_i ~= Cbar/(Gsat,ell)

  up to grading shift.

Proof:
  The generator statement is immediate.  If c*u_i=0, then

    c*ell^(i-1)*b
      =p*a+q*ell^i*b

  for some p,q.  Thus

    (c-q*ell)*ell^(i-1)*b belongs to (a),

  so

    c-q*ell belongs to G:ell^(i-1).

  This gives one containment in the annihilator formula; the reverse
  containment is immediate.  For i>=3 one has i-1>=2, so the preceding theorem
  identifies G:ell^(i-1) with Gsat.
Qed.

Put

  X:=m_A

and define

  Delta_i
    :=dim_C Hom_Cbar(K_(i-1),X)
      -dim_C Hom_Cbar(K_i,X).

Theorem every_layer_from_three_on_has_nonpositive_Bockstein_defect:
  For every i>=3,

    Delta_i<=0.

Proof:
  The proof is the same cyclic connecting-rank argument already verified for
  the stable layers in the preceding e=5 reduction, with the stabilization
  index lowered from four to three.

  Indeed V_i~=Cbar/(Gsat,ell).  Put

    N_G:=0:_X Gsat.

  For y in N_G define

    phi_y:K_i->X

  by

    phi_y(a)=0,
    phi_y(ell^i*b)=y.

  A relation p*a+q*ell^i*b=0 forces

    q in G:ell^i=Gsat,

  so phi_y is well defined.  The extension

    0 -> K_i -> K_(i-1) -> V_i -> 0

  is the pushout of the cyclic presentation of Cbar/(Gsat,ell).  The resulting
  explicit connecting classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_Cbar(V_i,X),

  using rank-nullity on the finite-dimensional ell-stable module N_G.

  Exactness therefore gives Delta_i<=0.
Qed.

Theorem ell_annihilator_of_the_target_has_dimension_six:
  One has

    dim_C(0:_X ell)=6.

Proof:
  Since X=m_A and ell has positive degree, every element of 0:_A ell has zero
  scalar part.  Hence

    0:_X ell=0:_A ell.

  Multiplication by ell on finite-dimensional A has kernel and cokernel of the
  same dimension, so

    dim_C(0:_A ell)=length_C(A/ell*A).

  The quadratic factorization gives s>=1 and Lbar=ell^s*K_k.  Because T is
  concentrated in degree two while the final cuts have degree at least three,
  the divisibility by ell lifts from Cbar to B.  Thus L subseteq ell*B and

    A/ell*A ~= B/ell*B.

  Since ell is regular on Cbar and m_B*T=0,

    0:_B ell=T.

  From

    Hilb_Cbar(t)=(1+3*t+t^2)/(1-t),
    Hilb_T(t)=t^2,

  the multiplication-by-ell exact sequence gives

    Hilb_(B/ell*B)(t)
      =(1-t)*Hilb_B(t)+t*Hilb_T(t)
      =1+3*t+2*t^2.

  Its length is six.
Qed.

Theorem only_two_layers_can_contribute_positive_defect:
  For i=1,2,

    Delta_i<=6,

  and for every k>=0,

    sum_(i=1)^k Delta_i<=12.

Proof:
  Each V_i is cyclic and killed by ell.  Evaluation at its cyclic generator
  injects

    Hom_Cbar(V_i,X) -> 0:_X ell,

  so

    dim Hom_Cbar(V_i,X)<=6.

  Applying Hom(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  gives

    Delta_i<=dim Hom(V_i,X)<=6

  for i=1,2.  Every i>=3 has Delta_i<=0 by the stable compensation theorem.
  Summing proves the bound twelve.
Qed.

Define the quadratic baseline deficit

  eta_0
    :=(N-1)-dim_C Hom_Cbar(K_0,X).

Corollary quadratic_and_cubic_baseline_deficits_agree:
  If epsilon_0 denotes the preceding degree-three baseline deficit, then

    eta_0=epsilon_0.

Proof:
  Multiplication by ell gives K_0~=J_0 as Cbar-modules, hence their Hom spaces
  into X have equal dimension.
Qed.

Theorem dangerous_candidate_forces_quadratic_baseline_deficit_at_least_seven:
  If the necessary order-13 tangent gate holds, then

    eta_0>=7.

Proof:
  The preceding file proves

    epsilon
      =epsilon_0+sum_(i=1)^k Delta_i

  and that the tangent gate forces epsilon>=19.  The previous corollary gives
  epsilon_0=eta_0, while the two-layer theorem gives

    sum Delta_i<=12.

  Hence

    eta_0>=19-12=7.
Qed.

Theorem quadratic_baseline_deficit_is_at_most_eleven:
  One has

    eta_0<=11.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring
  Cbar, a general constant linear combination

    q=lambda*a+mu*b

  is a quadratic nonzerodivisor on Cbar.

  Choose its homogeneous quadratic lift to B, still denoted q.  Because
  m_B*T=0, q kills T.  Since q is regular on Cbar, the multiplication kernel
  on B is exactly T.

  Put

    F:=0:_X K_0.

  Then F subseteq 0:_X q.  Multiplication by q on finite-dimensional X has
  kernel and cokernel of the same dimension, so

    length(F)<=length(X/qX).

  The element q is nonzero in A_2 because the final cut ideal starts in degree
  at least three.  Since X=m_A and q has degree two, the graded decomposition
  shows

    length(X/qX)=length(A/qA).

  The latter is a quotient of B/qB.

  The exact sequence

    0 -> T(-2) -> B(-2) --q--> B -> B/qB -> 0

  gives

    Hilb_(B/qB)
      =(1-t^2)*Hilb_B+t^2*Hilb_T
      =(1-t^2)*Hilb_Cbar+t^2
      =1+4*t+5*t^2+t^3.

  Therefore

    length(B/qB)=11,

  and hence length(F)<=11.

  Multiplication gives a natural map

    X -> Hom_Cbar(K_0,X)

  with kernel F.  Consequently

    dim Hom_Cbar(K_0,X)
      >=(N-1)-length(F)
      >=(N-1)-11,

  which is exactly eta_0<=11.
Qed.

Corollary surviving_baseline_deficit_is_finite:
  Every dangerous candidate in this h-vector must satisfy

    7<=eta_0<=11.
Qed.

Interpretation:
  The apparent degree-three baseline was not intrinsic.  The special
  h=(1,3,1) Hilbert function forces one more common Noether-parameter factor,
  exposing an m-primary quadratic pair K_0=(a,b).

  This lowers the saturation stabilization index by one.  Arbitrarily large
  degree gaps are harmless after the second delayed layer.  A surviving
  tangent candidate must therefore concentrate its obstruction in a quadratic
  baseline deficit of only five possible integer sizes, together with the
  first two cyclic ell-killed layers.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove eta_0<=6 and therefore does NOT close the
  e=5, h=(1,3,1) branch.

  It does NOT classify the multiplication algebra of Cbar from its h-vector
  alone, and it makes no claim for the other e=3,4,5 h-vectors, the q=4
  height-two branch, homogeneous q<=3, the unrestricted nonhomogeneous local
  frontier, or generic F_13 algebraicity.

BOUNDARY:
  A dangerous e=5, h=(1,3,1), q=4, ht(Q)=3 candidate must have

    7<=eta_0<=11,

  where

    eta_0=(N-1)-dim_C Hom_Cbar((a,b),m_A),

  and its only potentially positive degree-gap contributions are Delta_1 and
  Delta_2, each at most six.

NEXT_BOUNDED_OBJECT:
  compute the two quadratic-core cyclic layers jointly with the baseline colon

    G=(a:b)

  inside the Artin quadratic section Cbar/(q), whose Hilbert function is

    (1,4,4,1).

  Prove eta_0+Delta_1+Delta_2<=18, or construct the first explicit core for
  which the sum reaches nineteen.  Stop at the first such core rather than
  moving to another h-vector.