Standalone quadratic-predecessor/self-action reduction for the multiplicity-four
h=(1,2,1) subbranch of the homogeneous q=4, height-three order-13
low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e4_121_exact_zero_divisor_residual_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=4,

  and, with

    T:=H^0_m(B),
    C:=Cbar:=B/T,

  a general linear nonzerodivisor ell on C has

    h(C/ell*C)=(1,2,1).

The preceding exact-zero-divisor residual reduction proves

  Hilb_T(t)=t+2*t^2+t^3,
  length_C(T)=4,
  m_B^3*T=0,

and, with

  J:=Ann_B(T),
  Z:=B/J,

it proves

  length_C(Z)=4,
  Z is an Artin Gorenstein complete intersection with h=(1,2,1),
  T~=Z(-1),

and exactly one of

  ZERO_SELF_ACTION:
    J intersect T=T,
    T^2=0;

  NONZERO_SELF_ACTION:
    Hilb_(J intersect T)=t^2+t^3,
    length_C(J intersect T)=2.

Every final cut annihilates T, so for

  L:=(f,g)B,
  X:=Ann_A(T)=J/L,

one has

  A/X~=B/J=Z,
  dim_C X=N-4.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded structural step.  It passes the final
cuts to their degree-two saturated-core predecessors.  The regular lower
quadratic closes immediately.  In the zerodivisor-lower branch all delayed
layers from the second onward are compensated.  The NONZERO_SELF_ACTION case
then closes by an exact length-fourteen cubic section of J.  The only surviving
possibility is a ZERO_SELF_ACTION equality configuration in which every bound
is forced to be sharp.

Theorem parameter_multiplication_is_iso_from_degree_two:
  For every n>=2,

    ell:C_n -> C_(n+1)

  is a vector-space isomorphism.

Proof:
  Since

    Hilb_C(t)=(1+2*t+t^2)/(1-t),

  one has

    dim_C C_0=1,
    dim_C C_1=3,
    dim_C C_n=4 for every n>=2.

  Multiplication by ell is injective because ell is a nonzerodivisor.  For
  n>=2 the source and target both have dimension four, so the injection is an
  isomorphism.
Qed.

Write

  d:=deg(f)<=D:=deg(g),
  k:=D-d>=0.

Theorem final_cuts_have_quadratic_predecessors:
  There are unique

    a,b in C_2

  such that

    fbar=ell^(d-2)*a,
    gbar=ell^(D-2)*b.

  Put

    s:=d-2>=1,
    K_i:=(a,ell^i*b).

  Then

    Lbar:=(fbar,gbar)C=ell^s*K_k,

  multiplication by ell^s identifies

    K_k ~= Lbar,

  and both K_k and K_0=(a,b) are m-primary in C.

Proof:
  The parameter-isomorphism theorem gives the unique degree-two predecessors.
  Since C/Lbar is finite-dimensional, Lbar is m-primary.  The parameter ell
  avoids every minimal prime, so removing its common power does not change the
  radical; hence K_k is m-primary.  Since K_k is contained in K_0, the larger
  ideal K_0 is also m-primary.
Qed.

Theorem core_Hom_injects_into_the_actual_conormal_space:
  There is a natural injection

    Hom_C(K_k,X) -> Hom_B(L,A).

Proof:
  Projection B->C gives a surjection L->Lbar.  Since X annihilates T, the
  B-action on X factors through C.  Thus every C-linear map Lbar->X composes
  with L->Lbar and X->A to give a B-linear map L->A.  This construction is
  injective.  Finally use K_k~=Lbar.
Qed.

For every i>=0 define

  eta_i:=dim_C X-dim_C Hom_C(K_i,X)
        =(N-4)-dim_C Hom_C(K_i,X).

Theorem tangent_gate_forces_quadratic_core_deficit_sixteen:
  If the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A)<=N-20,

  then

    eta_k>=16.

Proof:
  Maps I->A vanishing on Q contain Hom_B(L,A), and the preceding theorem gives

    dim Hom_S(I,A)>=dim Hom_C(K_k,X).

  Hence the tangent gate gives

    dim Hom_C(K_k,X)<=N-20.

  Since dim X=N-4, this is eta_k>=16.
Qed.

Theorem multiplication_bound_for_every_predecessor:
  For every i>=0,

    eta_i<=dim_C(0:_X K_i).

Proof:
  Multiplication gives

    X -> Hom_C(K_i,X),
    x |-> (u |-> u*x),

  with kernel 0:_X K_i.  Rank-nullity and inclusion of the image in the full
  Hom space give the displayed inequality.
Qed.

Theorem quadratic_baseline_deficit_is_at_most_twelve:
  One has

    eta_0<=12.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring C,
  a general constant combination

    q0:=a+lambda*b

  is a quadratic nonzerodivisor on C.  Choose a homogeneous lift to B.

  Any element killed by q0 in B maps to an element killed by q0 in C, hence
  lies in T.  Therefore

    length_C(0:_B q0)<=length_C(T)=4.

  Multiplication by the quadratic q0 on the one-dimensional ring B gives

    length_C(B/q0*B)
      =2*e(B)+length_C(0:_B q0)
      <=8+4
      =12.

  Since q0 belongs to K_0,

    0:_X K_0 subseteq 0:_A q0.

  On the finite-dimensional algebra A, kernel and cokernel of multiplication
  by q0 have equal dimension.  Hence

    dim_C(0:_A q0)=length_C(A/q0*A)<=length_C(B/q0*B)<=12.

  Apply the multiplication bound at i=0.
Qed.

SECTION REGULAR_QUADRATIC_LOWER.

Assume a is a nonzerodivisor on C.

Theorem regular_quadratic_lower_forces_eta_at_most_twelve:
  One has

    eta_k<=12.

Proof:
  Lift a homogeneously to B.  As above,

    0:_B a subseteq T,

  so length(0:_B a)<=4 and

    length(B/aB)<=2*e(B)+4=12.

  Since a belongs to K_k,

    0:_X K_k subseteq 0:_A a,

  whose dimension is length(A/aA)<=length(B/aB)<=12.  Apply the universal
  multiplication bound.
Qed.

Corollary regular_quadratic_lower_is_closed:
  No REGULAR_QUADRATIC_LOWER candidate satisfies the necessary order-13
  tangent gate.

Proof:
  The gate requires eta_k>=16, whereas eta_k<=12.
Qed.

END REGULAR_QUADRATIC_LOWER.

SECTION ZERODIVISOR_QUADRATIC_LOWER.

Assume a is a zerodivisor on C.

Put

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem quadratic_colon_saturates_after_one_parameter_step:
  One has

    G:ell=Gsat,

  and therefore

    G:ell^j=Gsat

  for every j>=1.

Proof:
  First Gsat is proper.  Choose a minimal prime P containing a.  Since
  K_0=(a,b) is m-primary, b is not in P, so

    G_P=(a:b)_P=(a)_P

  is proper.  The parameter ell is a unit after localization at P, hence
  saturation does not change this localization and Gsat is proper.

  Now let x in (Gsat)_n with n>=2.  Choose m such that

    ell^m*x*b=a*c.

  Here c has degree n+m.  Multiplication by ell^m is an isomorphism from C_n
  to C_(n+m), so c=ell^m*c0 for a unique c0 in C_n.  Cancel ell^m to obtain

    x*b=a*c0,

  hence x belongs to G.  Thus Gsat/G is concentrated in degree one; degree zero
  is absent because Gsat is proper.  Multiplying a degree-one saturation class
  by ell lands in degree two, where Gsat and G agree.  Therefore

    ell*Gsat subseteq G,

  which is equivalent to G:ell=Gsat.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i

and

  Delta_i:=dim_C Hom_C(K_(i-1),X)-dim_C Hom_C(K_i,X).

Lemma exact_delayed_layer_annihilator:
  V_i is cyclic, generated by the class of ell^(i-1)*b, and

    Ann_C(V_i)=(G:ell^(i-1),ell).

Proof:
  The generator statement is immediate.  If c kills the displayed class, then

    c*ell^(i-1)*b=p*a+q*ell^i*b

  for some p,q.  Hence

    (c-q*ell)*ell^(i-1)*b belongs to (a),

  which gives c in (G:ell^(i-1),ell).  The reverse inclusion is immediate.
Qed.

Theorem every_delayed_layer_from_two_on_is_nonpositive:
  For every i>=2,

    Delta_i<=0.

Proof:
  For i>=2 the saturation theorem gives

    G:ell^(i-1)=Gsat.

  Hence V_i is, up to grading shift, C/(Gsat,ell).  Put

    N_G:=0:_X Gsat.

  For y in N_G define a map K_i->X by

    a |-> 0,
    ell^i*b |-> y.

  It is well defined because every relation coefficient on ell^i*b belongs to
  G:ell^i=Gsat.  Its connecting class in

    0 -> K_i -> K_(i-1) -> V_i -> 0

  vanishes exactly when y lies in ell*N_G.  Therefore the explicit connecting
  classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_C(V_i,X).

  Exactness after applying Hom(-,X) gives Delta_i<=0.
Qed.

Choose a scalar lambda so that

  q0:=a+lambda*b

is a quadratic nonzerodivisor on C, and put

  q:=ell*q0=ell*a+lambda*ell*b.

Then q is a homogeneous cubic nonzerodivisor on C and

  q belongs to K_1.

Theorem regular_first_layer_cubic_has_kernel_exactly_T:
  One has

    0:_B q=T.

Proof:
  Since q has degree three and m_B^3*T=0, it annihilates T.  Conversely, if
  q*x=0 in B, then q*xbar=0 in C.  Regularity of q on C forces xbar=0, hence
  x lies in T.
Qed.

Theorem exact_first_layer_cubic_section_lengths:
  One has

    NONZERO_SELF_ACTION => length_C(J/qJ)=14,
    ZERO_SELF_ACTION    => length_C(J/qJ)=16.

Proof:
  Since 0:_B q=T,

    0:_J q=J intersect T.

  The exact-zero-divisor residual reduction gives length(J intersect T)=2 in
  NONZERO_SELF_ACTION and length(J intersect T)=4 in ZERO_SELF_ACTION.

  The quotient B/J has finite length four, so J and B have the same
  one-dimensional multiplicity e(J)=e(B)=4.  The multiplication exact sequence
  by the cubic q therefore gives

    length(J/qJ)=3*e(J)+length(0:_J q)
                =12+length(J intersect T).

  Substitute the two exact intersection lengths.
Qed.

SECTION NONZERO_SELF_ACTION.

Assume

  length_C(J intersect T)=2.

Theorem nonzero_self_action_first_layer_has_deficit_at_most_fourteen:
  One has

    eta_1<=14.

Proof:
  Since q belongs to K_1,

    0:_X K_1 subseteq 0:_X q.

  The universal multiplication bound gives

    eta_1<=dim_C(0:_X K_1)<=dim_C(0:_X q).

  Multiplication by q on finite-dimensional X has kernel and cokernel of equal
  dimension, so

    dim_C(0:_X q)=length_C(X/qX).

  Since X=J/L,

    X/qX=J/(L+qJ)

  is a quotient of J/qJ.  The preceding exact section theorem gives

    length_C(X/qX)<=14.
Qed.

Theorem every_nonzero_self_action_degree_gap_is_closed:
  For every k>=0,

    eta_k<16.

Proof:
  If k=0, the baseline theorem gives eta_0<=12.

  If k>=1, telescope

    eta_k=eta_1+sum_(i=2)^k Delta_i.

  The first-layer theorem gives eta_1<=14 and every later Delta_i is
  nonpositive.  Hence eta_k<=14.
Qed.

Corollary nonzero_self_action_case_is_closed:
  No NONZERO_SELF_ACTION candidate satisfies the necessary order-13 tangent
  gate.

Proof:
  The tangent gate requires eta_k>=16, while the preceding theorem gives
  eta_k<16.
Qed.

END NONZERO_SELF_ACTION.

SECTION ZERO_SELF_ACTION.

Assume

  J intersect T=T,
  T^2=0.

Theorem square_zero_first_layer_has_deficit_at_most_sixteen:
  One has

    eta_1<=16.

Proof:
  Repeat the multiplication chain with the same cubic q in K_1:

    eta_1
      <=dim_C(0:_X K_1)
      <=dim_C(0:_X q)
      =length_C(X/qX)
      <=length_C(J/qJ)
      =16.
Qed.

Theorem square_zero_tangent_candidate_forces_exact_equality:
  Assume the necessary tangent gate holds.

  Then k>=1 and

    eta_k=eta_1=16.

  Moreover

    Delta_i=0

  for every 2<=i<=k.

Proof:
  The case k=0 is impossible because eta_0<=12 while the tangent gate requires
  eta_k>=16.

  For k>=1,

    16<=eta_k
      =eta_1+sum_(i=2)^k Delta_i
      <=eta_1
      <=16.

  Therefore every inequality is equality.  Since each Delta_i<=0 and their
  sum is zero, every Delta_i vanishes.
Qed.

Corollary square_zero_equality_identifies_the_two_annihilator_kernels:
  Under the tangent-gate hypothesis,

    dim_C(0:_X K_1)=16,
    dim_C(0:_X q)=16,

  and

    0:_X K_1=0:_X q.

Proof:
  The proof of the sixteen-dimensional upper bound gave the chain

    eta_1
      <=dim(0:_X K_1)
      <=dim(0:_X q)
      =length(X/qX)
      <=length(J/qJ)
      =16.

  The preceding theorem gives eta_1=16, so every term in the chain equals
  sixteen.  Since 0:_X K_1 is contained in 0:_X q and the two spaces have the
  same finite dimension, they are equal.
Qed.

Corollary square_zero_equality_forces_final_cuts_into_the_cubic_section:
  Under the tangent-gate hypothesis,

    L subseteq qJ.

Proof:
  Equality in the preceding chain gives

    length_C(X/qX)=length_C(J/qJ)=16.

  But

    X/qX=J/(L+qJ)

  is a quotient of J/qJ.  Equal finite lengths force

    L+qJ=qJ,

  hence L subseteq qJ.
Qed.

Corollary square_zero_equality_makes_multiplication_onto_the_first_core_Hom:
  Under the tangent-gate hypothesis, the multiplication map

    X -> Hom_C(K_1,X)

  is surjective.

Proof:
  Its kernel is 0:_X K_1, whose dimension is sixteen.  Equality eta_1=16 means

    dim X-dim Hom_C(K_1,X)=16.

  Hence

    dim Hom_C(K_1,X)=dim X-16,

  which is exactly the rank of the multiplication map.  Therefore its image is
  the full Hom space.
Qed.

END ZERO_SELF_ACTION.

Interpretation:
  The degree-two predecessor reduction removes every unbounded degree-gap
  direction in the e=4, h=(1,2,1) branch.  The regular lower quadratic is
  impossible, and in the zerodivisor-lower case every delayed layer after the
  first is nonpositive.

  The exact torsion self-action then separates the first layer sharply.
  NONZERO_SELF_ACTION gives the cubic section

    length(J/qJ)=14,

  so that entire case misses the required deficit sixteen.

  ZERO_SELF_ACTION gives the borderline section

    length(J/qJ)=16.

  A dangerous candidate can survive only by attaining equality everywhere:

    eta_1=eta_k=16,
    0:_X K_1=0:_X q,
    L subseteq qJ,
    Delta_i=0 for all i>=2 up to k,

  and multiplication X->Hom_C(K_1,X) must be surjective.

IMPORTANT_NONCONCLUSION:
  This file does NOT rule out the ZERO_SELF_ACTION equality configuration.

  Therefore it does NOT close the full e=4, h=(1,2,1) height-three branch.

  It makes no claim for the remaining e=3 rows, q=4 height two, homogeneous
  q<=3, the unrestricted nonhomogeneous frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e4_h121_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Rule out, or explicitly realize, the unique ZERO_SELF_ACTION equality
  configuration

    T^2=0,
    eta_1=16,
    0:_X K_1=0:_X q,
    L subseteq qJ,

  with

    q=ell*(a+lambda*b) in K_1.

NEXT_BOUNDED_OBJECT:
  Work only in that equality configuration.  Use the exact linkage model

    R=S/(u*v,p2,p3),
    K=uR,
    U=vR,
    q4=v*c,
    T~=Z(-1),
    Z=S/(u,c,p2,p3),

  together with ZERO_SELF_ACTION to derive the linear alignment of v modulo
  (u,c), and test whether the equality L subseteq qJ can coexist with the
  nonzero top torsion line T_3.  Stop at the first contradiction or the first
  explicit equality model; do not move to e=3 before this is settled.