Standalone exact height split for the homogeneous q=3 order-13 deviation-two
branch.

SCOPE:
  Let

    S := C[x1,x2,x3,x4],
    I := Q+(f1,f2,f3),
    A := S/I,
    N := length_C(A)>=32,

  where I is homogeneous and m-primary, mu(I)=6, and Q=I_2 is minimally
generated by exactly three independent quadrics.  The remaining generators
satisfy

    deg(fi)>=3.

This file performs one bounded structural task only: determine the exact
possible heights of Q and record the algebraic shape of each height-two and
height-three child.  It imports the already-closed height-one child but does
not promote the q=3 parent.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

ExternalResult KrullHeightTheorem:
  If an ideal J is enlarged by r elements, then

    ht(J+(g1,...,gr)) <= ht(J)+r.

ExternalResult HilbertBurch:
  A perfect height-two ideal minimally generated by three homogeneous elements
  has a two-column Hilbert--Burch presentation.

--------------------------------------------------------------------------
1. EXACT HEIGHT INVENTORY
--------------------------------------------------------------------------

Theorem homogeneous_q3_core_has_height_one_two_or_three:

    ht(Q) in {1,2,3}.

Proof:
  Since I is m-primary in the four-dimensional polynomial ring,

    ht(I)=4.

  Because

    I=Q+(f1,f2,f3),

  KrullHeightTheorem gives

    4<=ht(Q)+3,

  hence ht(Q)>=1.

  Since Q is generated by three elements, Krull's height theorem also gives

    ht(Q)<=3.

  Therefore

    ht(Q) in {1,2,3}.
Qed.

--------------------------------------------------------------------------
2. HEIGHT ONE IS ALREADY CLOSED
--------------------------------------------------------------------------

The established theorem

    homogeneous_q3_height1_is_tangent_closed

proves that the child

    ht(Q)=1

cannot satisfy the necessary order-13 tangent-deficit gate.

Hence every surviving homogeneous q=3 candidate must have

    ht(Q) in {2,3}.

--------------------------------------------------------------------------
3. HEIGHT TWO: PERFECT VERSUS NONPERFECT
--------------------------------------------------------------------------

Assume

    ht(Q)=2,
    B:=S/Q.

Then dim(B)=2.

Theorem q3_height2_perfect_core_has_linear_HilbertBurch_matrix:
  If B is Cohen--Macaulay, equivalently Q is perfect of grade two, then Q has
  minimal graded resolution

    0 -> S(-3)^2 -> S(-2)^3 -> Q -> 0.

  Consequently

    Hilb_B(t)=(1+2*t)/(1-t)^2

  and

    e(B)=3.

Proof:
  Hilbert--Burch gives

    0 -> S(-a) plus S(-b) -> S(-2)^3 -> Q -> 0

  for integers a,b.  Minimality forces

    a>=3,
    b>=3.

  The Hilbert numerator of B is

    p(t)=1-3*t^2+t^a+t^b.

  Since dim(B)=2, p(t) is divisible by (1-t)^2.  The derivative condition at
  t=1 gives

    -6+a+b=0,

  so a+b=6.  Together with a,b>=3 this forces

    a=b=3.

  Thus

    p(t)=1-3*t^2+2*t^3
        =(1-t)^2*(1+2*t),

  proving the stated Hilbert series and multiplicity three.
Qed.

Corollary q3_height2_exact_depth_split:
  Every height-two q=3 core belongs to exactly one of

    H2-CM:
      depth(B)=2,
      Q perfect,
      resolution 0 -> S(-3)^2 -> S(-2)^3 -> Q -> 0,
      e(B)=3;

    H2-NCM:
      depth(B)<=1,
      Q nonperfect.
Qed.

No tangent exclusion for either height-two child is asserted in this file.

--------------------------------------------------------------------------
4. HEIGHT THREE IS A THREE-QUADRIC COMPLETE INTERSECTION
--------------------------------------------------------------------------

Assume

    ht(Q)=3.

Theorem q3_height3_core_is_complete_intersection:
  The three quadratic generators of Q form an S-regular sequence.  Hence

    B:=S/Q

  is a one-dimensional graded complete intersection and Gorenstein ring with

    Hilb_B(t)
      =(1-t^2)^3/(1-t)^4
      =(1+t)^3/(1-t).

  In particular

    dim_C B_0=1,
    dim_C B_1=4,
    dim_C B_2=7,
    dim_C B_n=8 for n>=3,

  and

    e(B)=8.

Proof:
  S is Cohen--Macaulay and Q is generated by three elements of height three,
  so the generators form a regular sequence.  The complete-intersection
  Hilbert-series formula gives the displayed series and Hilbert function.
Qed.

In this child

    A=B/(f1,f2,f3)

is a finite-length quotient of the one-dimensional complete-intersection
curve core B.

No universal lower bound for

    dim_C Hom_B((f1,f2,f3),A)

is asserted here.

--------------------------------------------------------------------------
5. EXACT q=3 FRONTIER AFTER THE HEIGHT-ONE CLOSURE
--------------------------------------------------------------------------

Corollary homogeneous_q3_remaining_frontier:
  Every homogeneous q=3 candidate still capable of satisfying the necessary
  tangent gate lies in exactly one of

    H2-CM,
    H2-NCM,
    H3-CI.

The height-one child is excluded.

RESULT:
  homogeneous_q3_remaining_frontier = {H2-CM,H2-NCM,H3-CI}.

IMPORTANT_NONCONCLUSION:
  This file is a structural reduction, not a parent exclusion theorem.

  It does NOT close H2-CM.
  It does NOT close H2-NCM.
  It does NOT close H3-CI.
  It does NOT close homogeneous q=3.
  It does NOT close q<=2.
  It does NOT promote Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  homogeneous_q3_height1_is_tangent_closed.
  homogeneous_q3_remaining_frontier={H2-CM,H2-NCM,H3-CI}.
  not homogeneous_q3_closed.
  not homogeneous_q_le_3_closure.
  not OC.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow for this commit.
  2. If green, attack H3-CI through the intrinsic curve-core tangent module
     Hom_B((f1,f2,f3),A), proving only a verified lower bound.
