Standalone third J-adic-layer classification for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_second_J_adic_layer.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    R := S/J ~= C[z,w],
    n := (z,w) subset R,
    Q subset J,
    T := J/Q,

  where Q is minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T has finite length.

  The preceding two files prove the first two J-adic layers:

    E := T/J*T,
    F := J*T/J^2*T,

  with

    r=4:
      Hilb_E(t)=2*t,
      Hilb_F(t)=3*t^2;

    r=3:
      Hilb_E(t)=2*t+t^2,
      Hilb_F(t)=2*t^2;

  and universally

    n*F=0.

This file computes only

  G := J^2*T/J^3*T.

The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Put

  U := Span_C{z,w},
  V := Span_C{l1,l2}.

Then

  J^3/J^4 ~= R tensor Sym^3(V).

Theorem exact_third_layer_quotient:
  There is a natural graded R-module identification

    G ~= J^3/(J^4+(Q intersect J^3)).

  Hence G is generated in ordinary degree three by the image of Sym^3(V).

Proof:
  Since T=J/Q,

    J^2*T=(J^3+Q)/Q,
    J^3*T=(J^4+Q)/Q.

  Therefore

    G
      ~= (J^3+Q)/(J^4+Q)
      ~= J^3/(J^4+(Q intersect J^3)).
Qed.

Theorem the_longitudinal_maximal_ideal_annihilates_the_third_layer:
  In both first-layer cases r=4 and r=3,

    n*G=0.

Proof:
  FOUR-RELATION CASE r=4.

  The first initial forms span

    W=U tensor V.

  Let u be z or w and let s be any element of Sym^3(V).  Write s as a sum of
  terms v*t with v in V and t in Sym^2(V).  Since u*v belongs to W, choose a
  constant combination q of the four quadratic generators whose first J-adic
  initial form is u*v.  Multiplying q by t gives an element of Q whose class
  modulo J^4 has leading term u*v*t=u*s; its pure J^2 correction is multiplied
  by t and therefore lies in J^4.  Hence u*s is zero in G.

  THREE-RELATION CASE r=3.

  The preceding second-layer file proves

    V*W = U tensor Sym^2(V).

  Multiplying this equality once more by V gives

    Sym^2(V)*W = U tensor Sym^3(V).

  Therefore every u*s in U tensor Sym^3(V) is a sum of first initial forms
  multiplied by elements of Sym^2(V).  Replacing each first initial form by
  its lifted quadratic generator changes the result only by J^4.  Thus every
  longitudinal multiple again vanishes in G.
Qed.

We now produce two independent degree-three pure-transverse relations in each
case.

Theorem r4_has_two_independent_pure_cubic_relations:
  Assume r=4.  After constant changes of generator basis and bases of U,V, write

    q1 = z*l1 + h1,
    q2 = w*l1 + h2,
    q3 = z*l2 + h3,
    q4 = w*l2 + h4,

  with each h_i in Sym^2(V).

  Define

    Pz := l2*h1-l1*h3,
    Pw := l2*h2-l1*h4.

  Then

    Pz,Pw belong to Q intersect Sym^3(V)

  and are C-linearly independent.  In fact they have no common projective zero
  in P(V)=P^1.

Proof:
  The identities

    l2*q1-l1*q3=Pz,
    l2*q2-l1*q4=Pw

  prove membership in Q.

  Suppose Pz and Pw had a common projective zero [a:b] with (a,b) nonzero.
  Compatibility Pz(a,b)=0 gives a scalar z0 satisfying

    a*z0=-h1(a,b),
    b*z0=-h3(a,b).

  Likewise Pw(a,b)=0 gives w0 satisfying

    a*w0=-h2(a,b),
    b*w0=-h4(a,b).

  Thus

    [l1:l2:z:w]=[a:b:z0:w0]

  is a projective zero of all four q_i with (l1,l2) nonzero.  But Qsat=J says
  Proj(S/Q)=Proj(S/J), whose points all satisfy l1=l2=0.  Contradiction.

  Hence Pz,Pw have no common projective zero.  In particular they are nonzero
  and linearly independent.
Qed.

Theorem r3_has_two_independent_pure_cubic_relations:
  Assume r=3.  The preceding first-layer classification gives

    dim_C(Q_2 intersect J^2_2)=1.

  Choose a nonzero generator

    H in Q_2 intersect Sym^2(V).

  Then

    l1*H,
    l2*H

  are linearly independent elements of Q intersect Sym^3(V).

Proof:
  Membership is immediate because H belongs to Q.  Since C[l1,l2] is a domain
  and H is nonzero, multiplication by H is injective on V.  Therefore l1*H and
  l2*H are independent.
Qed.

Corollary universal_third_layer_dimension_bound:
  In either r=4 or r=3,

    dim_C G_3 <= 2.

Proof:
  The space Sym^3(V) has dimension four.  In both cases the preceding theorem
  gives at least two independent constant degree-three relations in its image
  inside G.
Qed.

Theorem exact_third_layer_is_a_small_semisimple_R_module:
  There exists

    s in {0,1,2}

  such that

    G ~= C(-3)^s

  as a graded R-module.  Equivalently,

    Hilb_G(t)=s*t^3.

Proof:
  G is generated in degree three.  The longitudinal maximal ideal n annihilates
  G, so no degree above three survives.  The universal dimension bound gives
  dim_C G_3<=2.  Put s=dim_C G_3.
Qed.

Theorem third_layer_dimension_equals_the_number_of_linear_syzygies_of_Q:
  Let

    Syz_1(Q)

  denote the C-vector space of degree-one coefficient syzygies among the four
  minimal quadratic generators of Q.  Then

    dim_C Syz_1(Q)=s.

  Consequently

    dim_C Syz_1(Q) in {0,1,2}.

Proof:
  Put B=S/Q and C=S/J.  Since Q has four independent minimal quadratic
  generators, the degree-three multiplication map

    S_1 tensor Q_2 -> Q_3

  has sixteen-dimensional source and kernel Syz_1(Q).  Hence

    dim_C Q_3 = 16-dim_C Syz_1(Q).

  Since dim_C S_3=20,

    dim_C B_3=4+dim_C Syz_1(Q).

  For the saturated line core C=S/J,

    dim_C C_3=4.

  From

    0 -> T -> B -> C -> 0

  it follows that

    dim_C T_3=dim_C Syz_1(Q).

  On the other hand the established first-layer Hilbert functions have no
  degree-three part, and the established second layer F is concentrated in
  degree two.  Thus

    T_3=(J^2*T)_3.

  Also T starts in degree one, so

    (J^3*T)_3=0.

  Therefore

    T_3 ~= G_3,

  and its dimension is s.
Qed.

Corollary exact_initial_total_torsion_Hilbert_data:
  The full saturation defect begins

    dim_C T_1=2,
    dim_C T_2=3,
    dim_C T_3=s,

  with

    s in {0,1,2}.
Qed.

Corollary zero_linear_syzygy_case_closes_the_transverse_tower_at_J_squared:
  If

    s=0,

  then

    J^2*T=0.

Proof:
  If s=0, then G=0, so

    J^2*T=J^3*T=J*(J^2*T).

  The module J^2*T has finite length and is supported at the homogeneous maximal
  ideal.  Nakayama's lemma after localizing there gives J^2*T=0.
Qed.

Corollary longitudinal_action_pushes_the_third_stage_one_layer_deeper:
  Universally,

    n*(J^2*T) subset J^3*T.
Qed.

IMPORTANT_NONCONCLUSION:
  The cases

    s=1,
    s=2

  are not closed here.  The present argument proves only that the third layer
  is at most two-dimensional and identifies it exactly with the linear-syzygy
  count.

  It does not determine the fourth transverse layer

    J^3*T/J^4*T

  when s is nonzero, and therefore does not yet prove a uniform exponent k with

    J^k*T=0

  in all line-core cases.

  No tangent-gate contradiction is claimed here.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_third_J_adic_layer_bounded.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify only the residual cases s=1 and s=2 by computing

    J^3*T/J^4*T.

  Use the actual linear syzygies of Q and their next lifted compatibility with
  the pure-transverse cubic relations.  Determine whether these residual cases
  force J^3*T=0 or a uniformly bounded fourth layer.

NEXT_BOUNDED_OBJECT:
  Split only by

    s=1

  versus

    s=2,

  and compute J^3*T/J^4*T.  Do not enter the depth-one deficiency branch.