Standalone three-step Bockstein reduction for the multiplicity-five h=(1,3,1)
subbranch of the homogeneous q=4, height-three order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e345_exact_saturation_linkage_table.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has Artin-reduction h-vector

    h(Cbar/ell*Cbar)=(1,3,1).

  The exact linkage table proves

    Hilb_T(t)=t^2,
    T~=C(-2) as a graded vector space,
    m_B*T=0,
    Ann_B(T)=m_B.

  The low-multiplicity core profile writes, after ordering d:=deg(f)<=deg(g)=D,

    fbar=ell^r*alpha,
    gbar=ell^(r+k)*beta,

  where

    r=d-3>=0,
    k=D-d>=0,
    alpha,beta in Cbar_3,
    J_i:=(alpha,ell^i*beta),
    Lbar:=(fbar,gbar)=ell^r*J_k,

  and multiplication by ell is an isomorphism

    ell:Cbar_n -> Cbar_(n+1)

  for every n>=3.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is to isolate the full unbounded degree-gap direction.
It proves that every layer after the first three has nonpositive Bockstein
defect and that the first three layers together contribute at most eighteen.
Since the socle-line torsion sharpens the tangent-gate requirement to nineteen,
the entire subbranch reduces to one finite equal-degree degree-three baseline
colon calculation.  That baseline is NOT closed here.

Theorem socle_line_torsion_does_not_meet_the_final_cut_ideal:
  Put

    L:=(f,g)B.

  Then

    L*T=0,
    L intersect T=0.

Proof:
  Both final generators have degree at least three, while m_B*T=0, so L*T=0.

  The ideal L is homogeneous and has no component in degrees below three.
  The module T is concentrated entirely in degree two.  Hence their
  intersection is zero.
Qed.

Corollary both_final_generators_are_core_active:
  The images fbar and gbar in Cbar are both nonzero.

Proof:
  If, for example, fbar=0, then f belongs to T.  But deg(f)>=3 while T has only
  degree two, forcing f=0, contradicting minimality of the final generator.
  The argument for g is identical.
Qed.

Theorem regularized_principal_annihilators_are_exactly_the_socle_line:
  After an invertible constant GL_2(C) change

    L=(h,k)

  one may choose both hbar and kbar nonzerodivisors on Cbar.  For such a choice

    D:=0:_B h=T,
    E:=0:_B k=T.

Proof:
  As in the general cyclic connecting reduction, the m-primary image of L in
  the one-dimensional Cohen--Macaulay ring Cbar permits a constant generator
  change avoiding all associated primes for each selected generator.

  Since L*T=0, both h and k kill T.  Conversely, if h*b=0 in B, then in Cbar

    hbar*bbar=0.

  Regularity of hbar gives bbar=0, so b lies in T.  Thus 0:_B h=T.  The same
  proof applies to k.
Qed.

Put

  A0:=Cbar/Lbar.

Theorem exact_socle_line_extension_and_annihilator:
  There is an exact sequence

    0 -> T -> A -> A0 -> 0,

  and

    Ann_A(T)=m_A.

Proof:
  The exact sequence follows from L intersect T=0.

  Since Ann_B(T)=m_B and L*T=0, the image of m_B in A annihilates T, so

    m_A subseteq Ann_A(T).

  Conversely, if b+L annihilates T in A, then

    b*T subseteq L.

  But b*T is contained in T and L intersect T=0.  Hence b*T=0 already in B,
  so b belongs to Ann_B(T)=m_B.  Therefore Ann_A(T)=m_A.
Qed.

Theorem socle_line_sharpens_required_connecting_excess_to_nineteen:
  With the regularized choice L=(h,k), put

    M:=L/hB

  and let

    partial:m_A -> Ext^1_B(M,A)

  be the connecting map from

    0 -> hB -> L -> M -> 0.

  Define

    sigma:=rank_C(partial),
    epsilon:=sigma-dim_C Hom_B(M,A).

  Then

    dim_C Hom_B(L,A)=N-1-epsilon.

  Consequently, if the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A)<=N-20,

  then

    epsilon>=19.

Proof:
  The general conormal sequence gives

    0 -> Hom_B(M,A)
      -> Hom_B(L,A)
      -> Ann_A(D)
      --partial--> Ext^1_B(M,A).

  Here D=T and Ann_A(T)=m_A, whose dimension is N-1 because A is a standard
  graded Artin C-algebra with A_0=C.  Exactness therefore gives

    dim Hom_B(L,A)=N-1-epsilon.

  Maps I->A vanishing on Q contain Hom_B(L,A), so the tangent gate forces

    N-1-epsilon<=N-20,

  hence epsilon>=19.
Qed.

Theorem conormal_maps_factor_exactly_through_the_saturated_core:
  One has natural vector-space isomorphisms

    Hom_B(L,A)
      ~= Hom_Cbar(Lbar,m_A)
      ~= Hom_Cbar(J_k,m_A).

  Therefore

    epsilon
      =(N-1)-dim_C Hom_Cbar(J_k,m_A).

Proof:
  Because T*L=0 and L intersect T=0, projection B->Cbar identifies L with
  Lbar as a Cbar-module.

  If phi:L->A is B-linear and t belongs to T, then for every x in L,

    t*phi(x)=phi(t*x)=0.

  Hence im(phi) lies in Ann_A(T)=m_A.  Conversely every Cbar-linear map
  Lbar->m_A defines a B-linear map L->A because T acts trivially on both
  modules.  This proves the first isomorphism.

  The core profile gives Lbar=ell^r*J_k.  Since ell is a nonzerodivisor on
  Cbar, multiplication by ell^r gives a Cbar-module isomorphism

    J_k -> ell^r*J_k=Lbar.

  This proves the second isomorphism.  Compare with the preceding exact
  conormal dimension formula to obtain the displayed identity for epsilon.
Qed.

Define the homogeneous colon

  H:=(alpha:beta),
  Hsat:=H:ell^infinity.

Theorem colon_saturation_is_reached_after_three_parameter_steps:
  One has

    (Hsat/H)_n=0

  for every n>=3.  Consequently

    ell^3*(Hsat/H)=0,
    H:ell^3=Hsat,

  and therefore

    H:ell^j=Hsat

  for every j>=3.

Proof:
  Let x in Hsat be homogeneous of degree n>=3.  Choose m>=0 such that

    ell^m*x*beta belongs to (alpha).

  Thus

    ell^m*x*beta=alpha*c

  for some homogeneous c of degree n+m.  Since multiplication by ell is an
  isomorphism in every degree starting at degree three, multiplication by
  ell^m gives an isomorphism

    Cbar_n -> Cbar_(n+m).

  Hence c=ell^m*c0 for some c0 in Cbar_n.  Substitution gives

    ell^m*(x*beta-alpha*c0)=0.

  The element ell is a nonzerodivisor on Cbar, so cancellation yields

    x*beta=alpha*c0.

  Thus x belongs to H.  This proves equality of H and Hsat in every degree at
  least three.

  For any homogeneous x in Hsat of degree below three, ell^3*x has degree at
  least three and remains in Hsat, hence lies in H.  Therefore

    ell^3*Hsat subseteq H,

  which is equivalent to Hsat subseteq H:ell^3.  The reverse inclusion follows
  from the definition of saturation.  Thus H:ell^3=Hsat, and all higher colons
  are the same.
Qed.

For i>=1 put

  W_i:=J_(i-1)/J_i.

Lemma exact_layer_annihilator:
  The class

    t_i:=ell^(i-1)*beta mod J_i

  generates W_i and has annihilator

    Ann_Cbar(t_i)=(H:ell^(i-1),ell).

  In particular, for every i>=4,

    W_i ~= Cbar/(Hsat,ell)

  up to grading shift.

Proof:
  The generator statement is immediate from

    J_(i-1)=(alpha,ell^(i-1)*beta).

  If c*t_i=0, then

    c*ell^(i-1)*beta
      =u*alpha+v*ell^i*beta

  for some u,v.  Therefore

    (c-v*ell)*ell^(i-1)*beta belongs to (alpha),

  so

    c-v*ell belongs to
      (alpha:ell^(i-1)*beta)
      =H:ell^(i-1).

  This proves one containment in the annihilator formula; the reverse
  containment is immediate.  For i>=4, the preceding theorem gives

    H:ell^(i-1)=Hsat.
Qed.

For the finite Cbar-module

  X:=m_A,

put

  Delta_i
    :=dim_C Hom_Cbar(J_(i-1),X)
      -dim_C Hom_Cbar(J_i,X).

Theorem every_layer_from_four_on_has_nonpositive_Bockstein_defect:
  For every i>=4,

    Delta_i<=0.

Proof:
  Fix i>=4.  The exact layer-annihilator theorem gives

    W_i~=Cbar/I,
    I:=(Hsat,ell),

  up to grading shift.  Put

    N_H:=0:_X Hsat.

  For y in N_H define

    phi_y:J_i->X

  by

    phi_y(alpha)=0,
    phi_y(ell^i*beta)=y.

  This is well defined: a relation

    u*alpha+v*ell^i*beta=0

  forces

    v in (alpha:ell^i*beta)
      =H:ell^i
      =Hsat,

  and therefore v*y=0.

  The extension

    0 -> J_i -> J_(i-1) -> W_i -> 0

  is the pushout of

    0 -> I -> Cbar -> Cbar/I -> 0

  along c |-> c*ell^(i-1)*beta.  Under the resulting cyclic presentation, the
  connecting class of phi_y is represented on I by a map satisfying

    ell |-> y,
    Hsat |-> 0.

  This class vanishes exactly when there is z in X with

    Hsat*z=0,
    ell*z=y,

  namely exactly when y belongs to ell*N_H.  Thus these explicit classes have
  rank

    dim_C(N_H/ell*N_H).

  Since N_H is finite-dimensional and stable under ell, rank-nullity gives

    dim_C(N_H/ell*N_H)
      =dim_C(0:_N_H ell)
      =dim_C Hom_Cbar(Cbar/(Hsat,ell),X)
      =dim_C Hom_Cbar(W_i,X).

  Hence the connecting map has rank at least dim Hom(W_i,X).  Applying Hom(-,X)
  to the layer sequence gives

    Delta_i
      =dim Hom(W_i,X)-rank(connecting)
      <=0.
Qed.

Theorem each_of_the_first_three_layers_has_defect_at_most_six:
  For i in {1,2,3},

    Delta_i<=6.

Proof:
  Applying Hom_Cbar(-,X) to

    0 -> J_i -> J_(i-1) -> W_i -> 0

  gives

    Delta_i<=dim_C Hom_Cbar(W_i,X).

  Every W_i is killed by ell, so the image of every map W_i->X lies in

    0:_X ell.

  Therefore

    dim Hom_Cbar(W_i,X)
      <=dim_C(0:_X ell)
      <=dim_C(0:_A ell).

  Since A is finite-dimensional,

    dim_C(0:_A ell)=dim_C(A/ell*A).

  The quotient A/ell*A is a quotient of B/ell*B, so it remains to compute the
  latter dimension.

  Here

    Hilb_Cbar(t)=(1+3*t+t^2)/(1-t),
    Hilb_T(t)=t^2,
    Hilb_B=Hilb_Cbar+t^2.

  Moreover 0:_B ell=T because ell is regular on Cbar and kills the socle line
  T.  The multiplication-by-ell exact sequence therefore gives

    Hilb_(B/ell*B)
      =(1-t)*Hilb_B+t*Hilb_T
      =1+3*t+2*t^2.

  Hence

    dim_C(B/ell*B)=6,

  proving the claim.
Qed.

Corollary entire_degree_gap_contribution_is_at_most_eighteen:
  For every k>=0,

    sum_(i=1)^k Delta_i<=18.

Proof:
  There are at most three layers with i<=3, each contributing at most six.
  Every layer with i>=4 has nonpositive defect.  If k<3, omit the absent terms.
Qed.

Define the equal-degree degree-three baseline excess

  epsilon_0
    :=(N-1)-dim_C Hom_Cbar(J_0,m_A),

where

  J_0=(alpha,beta).

Theorem exact_baseline_plus_degree_gap_decomposition:
  One has

    epsilon
      =epsilon_0+sum_(i=1)^k Delta_i.

  Consequently every candidate satisfying the necessary order-13 tangent gate
  must have

    epsilon_0>=1.

Proof:
  By definition

    Delta_i
      =dim Hom(J_(i-1),m_A)-dim Hom(J_i,m_A).

  Telescoping gives

    dim Hom(J_k,m_A)
      =dim Hom(J_0,m_A)-sum_(i=1)^k Delta_i.

  Substitute this into

    epsilon=(N-1)-dim Hom(J_k,m_A).

  If the tangent gate holds, the sharpened conormal theorem gives epsilon>=19,
  while the total degree-gap contribution is at most eighteen.  Hence

    epsilon_0>=1.
Qed.

Interpretation:
  The unbounded degree difference D-d is no longer an obstruction in the
  multiplicity-five h=(1,3,1) branch.

  All layers after the first three are automatically compensated by the same
  cyclic Bockstein mechanism that closed the stable multiplicity-six sector,
  now using only the degree-three stabilization of the low-multiplicity
  C[ell]-free core.  The first three layers together can contribute at most
  eighteen, one less than the nineteen dimensions required by the socle-line
  conormal gate.

  Therefore a dangerous candidate must already have positive excess at the
  finite equal-degree degree-three baseline

    J_0=(alpha,beta) subset Cbar.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove epsilon_0<=0.

  Therefore it does NOT close the e=5, h=(1,3,1) branch.

  It does not classify the multiplication algebra of Cbar from the h-vector
  alone and does not claim that the Artin reduction with h-vector (1,3,1) is
  Gorenstein.

  It makes no claim for the other e=3,4,5 h-vectors, q=4 height two,
  homogeneous q<=3, the unrestricted nonhomogeneous local frontier, or generic
  F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  NOT PROVED:

    the e=5, h=(1,3,1), q=4, ht(Q)=3 tangent branch is closed.

MISSING_OBJECT:
  Prove or disprove the finite baseline inequality

    dim_C Hom_Cbar((alpha,beta),m_A)>=N-1,

  equivalently

    epsilon_0<=0,

  for the degree-three m-primary pair alpha,beta in the h=(1,3,1) saturated
  core with the one-dimensional degree-two socle extension T.

NEXT_BOUNDED_OBJECT:
  Compute the equal-degree degree-three baseline connecting map for

    J_0=(alpha,beta).

  After a constant GL_2(C) change make alpha regular, write

    H_0:=(alpha:beta),

  and compute whether the cyclic connecting rank can exceed

    dim_C Hom_Cbar(Cbar/H_0,m_A).

  Stop at the first example with epsilon_0>0, or prove epsilon_0<=0 and close
  this h-vector before moving to the other seven low-multiplicity cores.
