Standalone Artinian-action/Betti reduction of the H01 minimal-chain m=2 endpoint
in the homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_artinian_chain_classification.v
    order13_q4_height2_depth_one_multiplicity_one_H01_linear_syzygy_reduction.v

  and retain

    S := C[x1,x2,x3,x4],
    P := (l1,l2),
    Q subset Qsat subset P,
    D := P/Qsat,
    T := Qsat/Q,

with

    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    e(S/Qsat)=1,
    depth_m(S/Qsat)=1,
    Q_2=(Qsat)_2,
    T_1=T_2=0,

and the H01 minimal Artinian-chain value

    m=2.

Thus, for a general D-regular linear form h,

    R:=S/(h) ~= C[y1,y2,y3],
    E:=D/hD,

one has

    Hilb_E(t)=2*t+t^2,
    Hilb_D(t)=(2*t+t^2)/(1-t).

The earlier cubic reduction left three numerical states

    (sigma,tau_3)=(3,0),(4,1),(5,2).

This file performs one bounded task only: use the rank-one/rank-two Artinian
action classification together with preservation of the minimal resolution
under the D-regular cut to determine which of those three cubic states can
occur.

No tangent estimate is made.
No q<=3 branch is entered.
No closure of H01 or Oblivion Closure is claimed.

This is pseudo-formal mathematical documentation. It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE D-REGULAR CUT PRESERVES THE MINIMAL BETTI TABLE
--------------------------------------------------------------------------

Because h is D-regular, the short free resolution of S/(h) gives

    Tor_i^S(D,S/(h))=0

for every i>0.

Hence tensoring a minimal graded S-free resolution of D with R=S/(h) remains
exact and resolves

    E=D/hD.

Every differential in a minimal graded resolution of D has entries in the
homogeneous maximal ideal of S. Reducing modulo h leaves those entries in the
homogeneous maximal ideal of R, so no degree-zero cancellation is introduced.
Therefore the reduced resolution remains minimal.

Theorem H01_m2_regular_cut_preserves_Betti_numbers:
  For every homological degree i and internal degree j,

    beta^S_{i,j}(D)=beta^R_{i,j}(E).
Qed.

Thus the Artinian normal form of E determines the exact graded Betti data of D.

--------------------------------------------------------------------------
2. THE CUBIC SATURATION DEFECT IS beta_{1,3}(D)
--------------------------------------------------------------------------

The standard presentation of P gives

    0 -> S(-2) -> S(-1)^2 -> P -> 0.

Pull back Qsat subset P along S(-1)^2 -> P. If K denotes the resulting relation
module for D, then

    0 -> S(-2) -> K -> Qsat -> 0.

The intrinsic S(-2) summand is the Koszul relation between l1 and l2.

Since

    Q_2=(Qsat)_2

and Q is generated by its four quadratic generators,

    S_1*(Qsat)_2=S_1*Q_2=Q_3.

Therefore minimal degree-three generators of Qsat are measured by

    (Qsat)_3 / Q_3 = T_3.

The intrinsic Koszul relation is already generated in degree two, so it adds no
new minimal generator of K in degree three.

Theorem H01_m2_tau3_is_beta13:
  One has

    beta^S_{1,3}(D)=dim_C T_3=tau_3.
Qed.

Combining with Section 1 gives

    tau_3=beta^R_{1,3}(E).

Thus the previously numerical saturation defect is visible directly in the
minimal Artinian presentation.

--------------------------------------------------------------------------
3. RANK-TWO ARTINIAN ACTION GIVES tau_3=0
--------------------------------------------------------------------------

Let

    mu:R_1 -> Hom_C(E_1,E_2)

be the multiplication map from the Artinian-chain classification.

Assume

    rank(mu)=2.

Choose x,y in R_1 whose multiplication functionals form a basis of
Hom_C(E_1,E_2), and choose a basis e1,e2 of E_1 together with a generator z2 of
E_2 such that

    x*e1=z2,
    x*e2=0,
    y*e1=0,
    y*e2=z2.

After replacing a third linear coordinate by its difference from a suitable
linear combination of x and y, choose w in R_1 with

    w*E_1=0.

The rank-two argument already proves R_1*E_2=0. Hence E has the presentation
with generators e1,e2 in degree one and exactly the five degree-two relations

    y*e1=0,
    x*e2=0,
    x*e1-y*e2=0,
    w*e1=0,
    w*e2=0.

These relations already force

    x*z2=y*z2=w*z2=0,

so they generate the full relation module: the presented module has Hilbert
series exactly 2*t+t^2.

Equivalently, first over C[x,y] one has the finite-length resolution

    0 -> C[x,y](-4)
      -> C[x,y](-2)^3
      -> C[x,y](-1)^2
      -> E
      -> 0,

and adjoining the annihilating variable w gives the minimal R-resolution

    0
      -> R(-5)
      -> R(-3)^3 direct_sum R(-4)
      -> R(-2)^5
      -> R(-1)^2
      -> E
      -> 0.

Therefore

    beta^R_{1,3}(E)=0.

By Section 2:

Theorem H01_m2_rank_two_forces_tau3_zero:
  If rank(mu)=2, then

    tau_3=0,
    sigma=3.
Qed.

There is no minimal cubic generator of Qsat in this case.

--------------------------------------------------------------------------
4. RANK-ONE ARTINIAN ACTION GIVES tau_3=1
--------------------------------------------------------------------------

Assume

    rank(mu)=1.

The established H01 rank-one normal form gives, after coordinates

    R=C[u,v,w],

an isomorphism

    E ~= C(-1) direct_sum C[u]/(u^2)(-1),

with v and w annihilating both summands.

The first summand C(-1) has the shifted Koszul resolution

    0 -> R(-4)
      -> R(-3)^3
      -> R(-2)^3
      -> R(-1)
      -> C(-1)
      -> 0.

The second summand is

    R/(v,w,u^2)(-1),

whose shifted complete-intersection resolution is

    0 -> R(-5)
      -> R(-3) direct_sum R(-4)^2
      -> R(-2)^2 direct_sum R(-3)
      -> R(-1)
      -> R/(v,w,u^2)(-1)
      -> 0.

Taking the direct sum yields the exact minimal R-resolution

    0
      -> R(-4) direct_sum R(-5)
      -> R(-3)^4 direct_sum R(-4)^2
      -> R(-2)^5 direct_sum R(-3)
      -> R(-1)^2
      -> E
      -> 0.

Therefore

    beta^R_{1,3}(E)=1.

By Section 2:

Theorem H01_m2_rank_one_forces_tau3_one:
  If rank(mu)=1, then

    tau_3=1,
    sigma=4.
Qed.

Thus the rank-one minimal chain has exactly one minimal cubic saturation class.

--------------------------------------------------------------------------
5. THE tau_3=2 CUBIC STATE IS IMPOSSIBLE
--------------------------------------------------------------------------

The Artinian-chain classification proves that im(mu) is nonzero and

    dim_C Hom_C(E_1,E_2)=2.

Therefore exactly one of

    rank(mu)=1,
    rank(mu)=2

occurs.

Sections 3 and 4 give respectively

    rank(mu)=2 -> tau_3=0,
    rank(mu)=1 -> tau_3=1.

No Artinian action type produces tau_3=2.

Theorem H01_m2_tau3_two_is_impossible:
  The numerical cubic state

    (sigma,tau_3)=(5,2)

cannot occur.
Qed.

Hence the earlier three-state frontier collapses to exactly two possible
Artinian-action states:

  H01-M2-R2:
    rank(mu)=2,
    sigma=3,
    tau_3=0.

  H01-M2-R1:
    rank(mu)=1,
    sigma=4,
    tau_3=1.

No claim is made here that either surviving state is realizable.

--------------------------------------------------------------------------
6. EXACT S-RESOLUTIONS OF D
--------------------------------------------------------------------------

By Section 1 the minimal S-resolution of D has exactly the same graded Betti
numbers as the corresponding R-resolution of E.

In H01-M2-R2:

    0
      -> S(-5)
      -> S(-3)^3 direct_sum S(-4)
      -> S(-2)^5
      -> S(-1)^2
      -> D
      -> 0.

In H01-M2-R1:

    0
      -> S(-4) direct_sum S(-5)
      -> S(-3)^4 direct_sum S(-4)^2
      -> S(-2)^5 direct_sum S(-3)
      -> S(-1)^2
      -> D
      -> 0.

Both tables have Hilbert numerator

    (1-t)^4 Hilb_D(t)
      = 2*t-5*t^2+3*t^3+t^4-t^5,

as required by

    Hilb_D(t)=(2*t+t^2)/(1-t).

--------------------------------------------------------------------------
7. CONSEQUENCES FOR Qsat
--------------------------------------------------------------------------

Recall that the relation module K for D sits in

    0 -> S(-2) -> K -> Qsat -> 0.

The five degree-two generators of K consist of the intrinsic Koszul relation
plus the four independent quadrics in (Qsat)_2=Q_2.

H01-M2-R2:
  The minimal resolution of D has no degree-three or higher generator in its
  first syzygy module. Therefore Qsat has no minimal generator above degree two.
  Since Qsat_2=Q_2 and Q is generated by Q_2,

    Qsat=Q,
    T=0.

Thus the rank-two m=2 state is a saturated H01 endpoint.

H01-M2-R1:
  The first syzygy module has exactly one additional generator, in degree three,
  and no higher minimal generators. Therefore there is a cubic

    gamma in (Qsat)_3 \ Q_3

  such that

    Qsat=Q+(gamma),

and T=Qsat/Q is generated by the class

    eta:=gamma+Q

in degree three.

Thus the rank-one m=2 state has a unique cubic saturation generator.

Theorem H01_m2_exact_saturation_split:
  Every H01 m=2 state lies in exactly one of the two structural branches

    H01-M2-R2: Q=Qsat, sigma=3, tau_3=0,

    H01-M2-R1: Qsat=Q+(gamma), sigma=4, tau_3=1.

  The state sigma=5,tau_3=2 is empty.
Qed.

--------------------------------------------------------------------------
8. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_REDUCED:
  q4_height2_multiplicity_one_depth_one_H01_m2_Betti_action_type.
  q4_height2_multiplicity_one_depth_one_H01_m2_tau3_two_empty.
  q4_height2_multiplicity_one_depth_one_H01_m2_exact_saturation_two_case.

EXACT_SURVIVING_M2_FRONTIER:
  H01-M2-R2:
    rank(mu)=2,
    sigma=3,
    tau_3=0,
    Q=Qsat.

  H01-M2-R1:
    rank(mu)=1,
    sigma=4,
    tau_3=1,
    Qsat=Q+(gamma),
    T generated in degree three by gamma+Q.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove either surviving m=2 state exists.
  It does NOT exclude H01-M2-R2.
  It does NOT exclude H01-M2-R1.
  It does NOT make a tangent estimate.
  It does NOT close H01.
  It does NOT close q=4 height two.
  It does NOT enter q<=3.
  It does NOT prove Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  H01_mge3_closed.
  H01_m2_tau3_two_empty.
  H01_m2_reduced_to_R2_or_R1.
  not H01_m2_closed.
  not H01_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not OC.

MISSING_OBJECT:
  Treat the two surviving H01 m=2 structural states separately.

  First attack the saturated rank-two state

    H01-M2-R2:
      Q=Qsat,
      sigma=3,
      Hilb_D(t)=(2*t+t^2)/(1-t),

  and use the exact 3-linear-syzygy matrix / saturated four-quadric structure to
  classify its coefficient matrix or derive the weakest tangent carrier.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow run for this commit.
