Standalone linkage classification for the Cohen--Macaulay multiplicity-six endpoint of the homogeneous q=4, height-three order-13 branch.

SCOPE:
  This file starts from the verified setup

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  It uses standard complete-intersection linkage for grade-three almost-complete intersections.  It does not prove the remaining annihilator-Hom bound and does not treat the e<=5, height-two, q<=3, or unrestricted nonhomogeneous local branches.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

ExternalResult GradeThreeACIResidualIsGorenstein:
  Let R be a Gorenstein ring and I a grade-three perfect almost-complete-intersection ideal.  If K subset I is generated by a regular sequence of length three and J:=K:I, then I and J are directly linked by K and J is grade-three Gorenstein.

ExternalResult MultiplicityAdditionUnderDirectLinkage:
  If homogeneous unmixed ideals I,J of the same codimension are directly linked by a homogeneous complete intersection K, then

    e(S/I)+e(S/J)=e(S/K).

Theorem choose_quadratic_complete_intersection_inside_Q:
  There exist three C-linear combinations q1,q2,q3 of the four quadratic generators of Q forming an S-regular sequence.

Proof:
  Since Q has height three over the infinite field C, generic elements of its degree-two generating space contain a homogeneous regular sequence of length three.
Qed.

Notation:
  K := (q1,q2,q3),
  J := K:Q.

Theorem residual_link_is_height_three_Gorenstein:
  J is a homogeneous grade-three Gorenstein ideal, and Q=K:J.

Proof:
  Q is a grade-three perfect almost-complete intersection: it is perfect because B=S/Q is Cohen--Macaulay of codimension three, and it has four minimal generators.  Apply GradeThreeACIResidualIsGorenstein to the regular sequence K subset Q.
Qed.

Theorem residual_link_has_multiplicity_two:
  One has

    e(S/J)=2.

Proof:
  K is a complete intersection of three quadrics, hence

    e(S/K)=2*2*2=8.

  Direct linkage gives

    e(S/Q)+e(S/J)=e(S/K).

  Since e(S/Q)=6,

    e(S/J)=8-6=2.
Qed.

Theorem residual_link_has_h_vector_11:
  The one-dimensional Cohen--Macaulay Gorenstein algebra R:=S/J has Hilbert series

    Hilb_R(t)=(1+t)/(1-t).

Proof:
  Let ell be a general linear nonzerodivisor on R.  Then H:=R/(ell) is an Artin standard graded Gorenstein algebra of length

    length(H)=e(R)=2.

  Since H_0=C and H is not the zero ring, its only possible standard graded Hilbert function of total length two is

    (1,1).

  Therefore the h-polynomial of R is 1+t, giving the displayed Hilbert series.
Qed.

Corollary residual_link_contains_exactly_two_independent_linear_forms:
  One has

    dim_C (S/J)_1=2,

  hence

    dim_C J_1=2.

  Thus J contains two linearly independent linear forms l1,l2.
Qed.

Theorem residual_link_is_complete_intersection_112:
  There exists a quadric q such that

    J=(l1,l2,q),

  and l1,l2,q form a regular sequence.  Equivalently, the residual Gorenstein link is a complete intersection of degrees

    (1,1,2).

Proof:
  Modulo the two independent linear forms l1,l2, write

    S/(l1,l2) ~= C[u,v].

  Let Jbar be the image of J.  Since ht(J)=3 and l1,l2 are part of a homogeneous system cutting the two linear directions, Jbar has height one in C[u,v], while

    C[u,v]/Jbar ~= S/J

  remains Cohen--Macaulay of dimension one.

  A height-one Cohen--Macaulay homogeneous ideal in the regular UFD C[u,v] is principal.  Write

    Jbar=(qbar)

  for a homogeneous form qbar.

  The multiplicity of the hypersurface C[u,v]/(qbar) equals deg(qbar).  Since e(S/J)=2, deg(qbar)=2.

  Lifting qbar gives a quadric q with

    J=(l1,l2,q).

  Height three then implies l1,l2,q is a regular sequence.
Qed.

Corollary multiplicity_six_four_quadric_core_is_linked_to_degree_two_residual:
  Every homogeneous q=4, ht(Q)=3, e(S/Q)=6 Cohen--Macaulay core admits a direct (2,2,2)-link to the rigid residual complete intersection

    CI(1,1,2).

  Thus the abstract type-two core from the preceding files is not an arbitrary grade-three ACI: its residual link is forced up to linear change of coordinates to two linear equations plus one quadric.
Qed.

Connection with the forced canonical module:
  Standard complete-intersection linkage identifies the canonical module of S/Q, up to the usual grading shift determined by the (2,2,2) link, with the residual module J/K.

  Since J=(l1,l2,q), this gives a geometric origin for the two canonical generators already proved in

    order13_q4_height3_e6_canonical_restriction.v.

  This observation is structural only; no additional Hom_A(D,A) bound is inferred from it here.

IMPORTANT_NONCONCLUSION:
  The residual classification does NOT prove that the annihilator module

    D=0:_(C0)g

  is cyclic, nor that

    dim Hom_A(D,A)<N+20.

  It therefore does not close the e=6 endpoint.

BOUNDARY:
  The first missing object remains the exceptional annihilator-Hom estimate, now under the additional rigid fact that the ambient four-quadric core is directly linked through a (2,2,2) complete intersection to CI(1,1,2).

NEXT_BOUNDED_OBJECT:
  use the explicit CI(1,1,2) residual-link presentation to express the last differential/canonical generators concretely and test whether the two higher-degree cuts can force the noncyclic equal-length module D to have Hom_A(D,A)>=N+20.  Stop if this becomes a general classification problem for type-two Artin annihilator modules.