Standalone cubic-shadow exclusion of the forced R4S residual type in the
H01-C5 m=3 E0/E1 branch of the homogeneous q=4, height-two multiplicity-one,
depth-one order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_E01_R3_R4U_exclusion.v
    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_E01_residual_route_terminal_boundary.v

  and retain

    S = C[x1,x2,x3,x4],
    Q = (W),
    W = Q_2 = (Qsat)_2,
    dim_C W = 4,
    P = (l1,l2),
    Qsat subset P,
    J_res = (Qsat:P),

  in H01-C5 with

    sigma := dim ker(S_1 tensor W -> Q_3) = 5.

The preceding E0/E1 residual analysis excludes R3 and R4U.  Hence the only
remaining E0/E1 residual type is R4S, and in that type

    dim_C (J_res)_1 = 1.

This file performs one bounded task only: use that single linear residual
annihilator together with W subset P_1*S_1 to show that the cubic shadow S_1*W
has dimension at least twelve, unless Q has height one.  Therefore sigma<=4,
contradicting the defining C5 value sigma=5.

No E2 statement is made.
No H01-C4, q<=3, or full order-13 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE FORCED R4S LINEAR ANNIHILATOR
--------------------------------------------------------------------------

Since R4S has

    dim_C (J_res)_1 = 1,

choose a nonzero linear form

    z in (J_res)_1.

By definition

    J_res=(Qsat:P),

so

    z*P subset Qsat.

Taking degree two and using the H01 equality

    (Qsat)_2=Q_2=W

gives

    z*P_1 subset W.

Also Qsat subset P, hence

    W subset P_1*S_1.

Thus the four-dimensional quadratic space W satisfies simultaneously

    z*P_1 subset W subset P_1*S_1.

Theorem H01_C5_m3_E01_R4S_quadratic_sandwich:
  There is a nonzero z in S_1 such that

    z*P_1 subset W subset P_1*S_1,

  with dim P_1=2 and dim W=4.
Qed.

--------------------------------------------------------------------------
2. CUBIC SHADOW NOTATION
--------------------------------------------------------------------------

Because Q is generated by W in degree two,

    Q_3=S_1*W.

The multiplication map

    S_1 tensor W -> S_1*W

has source dimension

    4*4=16.

Therefore

    sigma = 16-dim_C(S_1*W).

The C5 hypothesis sigma=5 is equivalent to

    dim_C(S_1*W)=11.

We prove instead that every height-two configuration satisfying the quadratic
sandwich has

    dim_C(S_1*W)>=12.

--------------------------------------------------------------------------
3. CASE z NOT IN P_1
--------------------------------------------------------------------------

Assume first

    z notin P_1.

Then

    (z*S_1) intersect (P_1*S_1)=z*P_1.

Indeed, if z*l lies in P_1*S_1, reduce modulo P.  Since S/P is a domain and the
class of z is nonzero, the class of l must vanish, so l lies in P_1.

Because W subset P_1*S_1 and z*P_1 subset W, this gives

    W intersect z*S_1 = z*P_1,

so the image Wbar of W in

    Sbar:=S/(z)

has dimension two.

Let

    A:=z*P_1 subset W.

Then

    S_1*A=z*(P_1*S_1)

has dimension seven, because the degree-two part of the linear ideal P has

    dim_C(P_1*S_1)=10-dim_C(S/P)_2=10-3=7.

Modulo z, the image of S_1*W is

    Sbar_1*Wbar.

Lemma two_independent_quadrics_have_shadow_at_least_five:
  If U is a two-dimensional space of quadrics in a polynomial ring in three
  variables, then

    dim(Sbar_1*U)>=5.

Proof:
  Choose independent quadrics q1,q2 spanning U.  The source of

    Sbar_1 tensor U -> Sbar_3

  has dimension six.  A linear first syzygy

    a*q1+b*q2=0

  is unique up to scalar whenever it exists: writing out the gcd of q1,q2,
  independence rules out a quadratic common factor, and a nonzero linear
  syzygy forces a common linear factor, leaving the unique Koszul relation
  between the two residual linear factors.  Thus the kernel has dimension at
  most one and the image has dimension at least five.
Qed.

The seven-dimensional subspace S_1*A lies in the kernel of reduction modulo z,
while the quotient image has dimension at least five.  Hence

    dim_C(S_1*W)>=7+5=12.

Therefore

    sigma<=16-12=4,

contrary to sigma=5.

Theorem H01_C5_m3_E01_R4S_z_outside_P_excluded:
  The case z notin P_1 is impossible in C5.
Qed.

--------------------------------------------------------------------------
4. CASE z IN P_1: INTERSECTION PARAMETER
--------------------------------------------------------------------------

Assume now

    z in P_1.

Put

    A:=W intersect z*S_1

and

    r:=dim_C A.

Since

    z*P_1 subset A

and dim P_1=2,

    r in {2,3,4}.

We treat the three values separately.

--------------------------------------------------------------------------
5. SUBCASE r=2
--------------------------------------------------------------------------

If r=2, then

    A=z*P_1.

As above,

    dim_C(S_1*A)=dim_C z*(P_1*S_1)=7.

The image Wbar in Sbar=S/(z) has dimension

    dim Wbar=4-r=2.

Because W subset P_1*S_1 and P_1=(z,y) after choosing a second generator y,
every element of Wbar is divisible by y.  Thus

    Wbar=y*U

for a two-dimensional subspace

    U subset Sbar_1.

For two independent linear forms in three variables,

    dim_C(Sbar_1*U)=5,

since the quotient by their ideal is a polynomial ring in one variable and its
degree-two piece has dimension one.  Multiplication by y is injective, hence

    dim_C(Sbar_1*Wbar)=5.

Therefore

    dim_C(S_1*W)>=7+5=12,

so sigma<=4, contradiction.

Theorem H01_C5_m3_E01_R4S_z_in_P_r2_excluded:
  The subcase r=2 is impossible in C5.
Qed.

--------------------------------------------------------------------------
6. SUBCASE r=3
--------------------------------------------------------------------------

If r=3, division by z writes

    A=z*L

for a three-dimensional linear subspace

    L subset S_1.

Because z*P_1 subset A,

    P_1 subset L.

For a three-dimensional linear subspace L of the four-dimensional space S_1,
its degree-two ideal part has dimension nine:

    dim_C(S_1*L)=10-1=9,

because S/(L) is a polynomial ring in one variable.

Hence

    dim_C(S_1*A)=9.

The image Wbar in S/(z) has dimension

    4-r=1.

A nonzero quadric in a polynomial domain multiplied by the three-dimensional
linear space Sbar_1 produces a three-dimensional cubic space.  Therefore

    dim_C(Sbar_1*Wbar)=3.

Thus

    dim_C(S_1*W)>=9+3=12,

again giving sigma<=4.

Theorem H01_C5_m3_E01_R4S_z_in_P_r3_excluded:
  The subcase r=3 is impossible in C5.
Qed.

--------------------------------------------------------------------------
7. SUBCASE r=4 IS HEIGHT ONE
--------------------------------------------------------------------------

If r=4, then

    W subset z*S_1.

Both spaces have dimension four, so

    W=z*S_1.

Therefore

    Q=(W)=z*(x1,x2,x3,x4).

The prime ideal (z) is then a minimal prime of Q, so

    ht(Q)=1,

contrary to the standing hypothesis

    ht(Q)=2.

Theorem H01_C5_m3_E01_R4S_z_in_P_r4_height_contradiction:
  The subcase r=4 is impossible in the height-two branch.
Qed.

--------------------------------------------------------------------------
8. FORCED R4S IS EMPTY
--------------------------------------------------------------------------

Sections 3--7 exhaust all positions of z relative to P_1 and all possible values
of

    dim(W intersect z*S_1).

Every height-two case gives

    dim_C(S_1*W)>=12,

hence

    sigma<=4.

But H01-C5 requires

    sigma=5.

Contradiction.

Theorem q4_H01_C5_m3_E01_R4S_cubic_shadow_excluded:
  The forced residual type R4S does not occur in H01-C5 m=3 E0/E1.
Qed.

The preceding file already excluded R3 and R4U.  Therefore all E0/E1 residual
states are empty.

Corollary q4_H01_C5_m3_E01_closed:
  H01-C5 m=3 has no E0 or E1 cyclic-colon state.
Qed.

--------------------------------------------------------------------------
9. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_R4S_cubic_shadow_excluded.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_closed.

CURRENT_C5_M3_STATUS:
  E0 closed.
  E1 closed.
  E2 remains untouched by this file.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude the E2 two-variable cyclic-colon type.
  It does NOT close all H01-C5 m=3.
  It does NOT close H01.
  It does NOT enter H01-C4.
  It does NOT enter q<=3.
  It does NOT prove full q4 height-two closure.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_E2_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3.  The E0/E1 branches are now empty, so move to the
  genuine two-variable cyclic-colon type E2:

    K=(Q:gamma)=(z1,z2)+I(u,v),
    T ~= (C[u,v]/I)(-3),
    c-a=4.

  Determine the weakest consequence of the five-linear-first-syzygy matrix for
  the quadratic part I_2 or for the first nonzero higher piece of T.  Do not
  return to the exhausted E0/E1 residual route.

NEXT_ACTIONS:
  1. Re-read the exact terminal run for this commit.
