Standalone closure of the regular-lower-cut unequal-degree subbranch in the
homogeneous q=4, height-three, multiplicity-six order-13 endpoint.

SCOPE:
  Work in the already established setup

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q one-dimensional Cohen--Macaulay,
    e(B)=6.

  The preceding branch files prove

    Hilb_B(t)=(1+3*t+2*t^2)/(1-t)

  and, for a general linear nonzerodivisor ell,

    B ~= C[ell]
         direct_sum C[ell](-1)^3
         direct_sum C[ell](-2)^2

  as a graded C[ell]-module.  Consequently multiplication by ell^(n-2)
  identifies B_2 with B_n for every n>=2.

  Let

    I=Q+(f,g)

  be homogeneous and minimally six-generated, with

    deg(f)=d>=3,
    deg(g)=e>d,
    I m-primary.

  Put

    r:=d-2>=1,
    k:=e-d>0.

  The graded Noether-parameter factorization gives unique a,b in B_2 such that

    f=ell^r*a,
    g=ell^(r+k)*b,

  and, with

    J_k:=(a,ell^k*b),
    L:=(f,g)B=ell^r*J_k,
    A:=B/L,
    N:=length_C(A),

  the ideal J_k is m-primary.

  This file treats only the subbranch in which the lower-degree quadratic
  factor a is a nonzerodivisor on B.  Equivalently, f is a nonzerodivisor,
  because ell is a nonzerodivisor.

  No regularity of a is inferred merely from the unequal-degree hypotheses.

This is pseudo-formal mathematical documentation.  It is not Coq and does not
assert generic F_13 algebraicity.

Theorem regular_quadratic_cut_has_fixed_Artin_Hilbert_function:
  Assume a is a nonzerodivisor on B and put

    C0:=B/(a).

  Then

    Hilb_C0(t)
      =(1-t^2)Hilb_B(t)
      =1+4*t+5*t^2+2*t^3.

  Hence C0_n=0 for every n>=4.
Qed.

Theorem regular_lower_cut_forces_degree_gap_one:
  Under the hypotheses above,

    k=1.

Proof:
  Suppose k>=2.  The image of ell^k*b in C0 has degree

    k+2>=4,

  so the preceding Hilbert-function computation gives

    ell^k*b in (a)B.

  Multiplying by ell^r yields

    g=ell^r*(ell^k*b) in ell^r*(a)B=(f)B.

  Therefore Q+(f,g)=Q+(f), contradicting the assumption that I is minimally
  generated by the four quadratic generators of Q together with both f and g.

  Since k>0, the only remaining value is k=1.
Qed.

From now on write

  J:=(a,ell*b),
  L=ell^r*J,
  A=B/L.

Theorem top_degree_second_cut_is_nonzero:
  The class

    c:=ell*b mod (a)

  is nonzero in (C0)_3.

Proof:
  If c=0, then ell*b belongs to (a)B, hence

    g=ell^r*(ell*b) belongs to (f)B,

  again contradicting minimal six-generation of I.
Qed.

Corollary residual_quadratic_core_has_Hilbert_function_1451:
  Since c is a nonzero element of the top degree (C0)_3 and C0_n=0 for n>=4,

    B/J ~= C0/(c)

  has Hilbert function

    (1,4,5,1)

  and length eleven.
Qed.

Define the multiplication-kernel module

  E:=0:_A J
    =(ell^r*J :_B J)/(ell^r*J).

Theorem annihilator_vanishes_below_common_parameter_order:
  For every n<r,

    E_n=0.

Proof:
  Let x in B_n represent a class in E_n.  Then

    x*a in L_(n+2).

  The first generator of L has degree r+2 and the second has degree r+3.
  Since n<r,

    L_(n+2)=0.

  Thus x*a=0.  Regularity of a gives x=0.
Qed.

Theorem first_middle_degree_has_dimension_one:
  One has

    dim_C E_r=1.

Proof:
  In degree r+2,

    L_(r+2)=C*(ell^r*a).

  If x in B_r represents a class in E_r, then

    x*a=lambda*ell^r*a

  for some scalar lambda.  Since a is a nonzerodivisor,

    x=lambda*ell^r.

  Conversely ell^r annihilates both generators of J modulo L:

    ell^r*a in L,
    ell^r*(ell*b) in L.

  Since L_r=0, the degree-r part of E is exactly C*ell^r.
Qed.

Theorem second_middle_degree_has_dimension_at_most_six:
  One has

    dim_C E_(r+1)<=6.

Proof:
  The degree-(r+1) part of E is a subquotient of B_(r+1).  Because r+1>=2,
  the fixed Hilbert series of B gives

    dim_C B_(r+1)=6.

  Therefore dim_C E_(r+1)<=6.
Qed.

Theorem annihilator_tail_is_the_shifted_residual_core_tail:
  For every n>=r+2 there is a natural vector-space isomorphism

    E_n ~= (B/J)_(n-r).

Proof:
  Put m:=n-r>=2.  Multiplication by ell^r is a vector-space isomorphism

    B_m --times ell^r--> B_n.

  Thus every x in B_n has a unique expression

    x=ell^r*y,
    y in B_m.

  Then

    x*J=ell^r*(yJ) subseteq ell^r*J=L,

  so the whole degree B_n lies in the colon (L:J)_n.  Dividing the quotient

    B_n/L_n

  through the displayed multiplication isomorphism identifies it with

    B_m/J_m=(B/J)_m.
Qed.

Corollary annihilator_length_is_at_most_thirteen:
  One has

    length_C(E)<=13.

Proof:
  Degrees below r contribute zero.  Degree r contributes exactly one.
  Degree r+1 contributes at most six.

  The tail theorem identifies all degrees n>=r+2 with the part of B/J in
  degrees at least two.  Since

    Hilb_(B/J)=(1,4,5,1),

  that tail has length

    5+1=6.

  Hence

    length(E)<=1+6+6=13.
Qed.

Theorem multiplication_maps_give_large_unequal_cut_conormal_space:
  The map

    A -> Hom_B(J,A),
    z |-> (j |-> z*j),

  has kernel E.  Therefore

    dim_C Hom_B(J,A)>=N-13.

Proof:
  The kernel consists exactly of classes z annihilating all of J, namely E.
  Hence the image has dimension N-length(E)>=N-13.
Qed.

Theorem common_parameter_factor_identifies_J_and_L:
  Multiplication by ell^r is a B-module isomorphism

    J --times ell^r--> L.

Proof:
  Surjectivity is L=ell^r*J.  Injectivity follows because ell is a
  nonzerodivisor on B.
Qed.

Theorem regular_lower_cut_unequal_e6_branch_cannot_pass_order13_tangent_gate:
  In this subbranch,

    dim_C Hom_S(I,A)>=N-13.

  Consequently the necessary order-13 tangent gate

    dim_C Hom_S(I,A)<=N-20

  is impossible.

Proof:
  The preceding isomorphism gives

    Hom_B(L,A) ~= Hom_B(J,A),

  so

    dim_C Hom_B(L,A)>=N-13.

  The already established maps-killing-Q injection gives

    Hom_B(L,A) -> Hom_S(I,A).

  Therefore

    dim_C Hom_S(I,A)>=N-13>N-20.
Qed.

Corollary regular_lower_cut_unequal_degree_endpoint_is_closed:
  No homogeneous q=4, ht(Q)=3, e(B)=6 candidate with deg(f)<deg(g) and regular
  lower-degree cut f can satisfy the order-13 tangent deficit twenty.
Qed.

IMPORTANT_NONCONCLUSION:
  The full unequal-degree e(B)=6 endpoint is not closed here.

  The unresolved subbranch is precisely the case in which the lower-degree
  homogeneous generator f, equivalently its quadratic factor a, is a
  zerodivisor on B.  A general local constant combination of f and g can be
  made regular, but when deg(f)<deg(g) that combination is not homogeneous and
  does not preserve the graded Noether-parameter factorization used above.

  No conclusion is drawn for that zerodivisor lower-cut subbranch, for the
  height-three e(B)<=5 cases, for the height-two q=4 core, for homogeneous
  q<=3, or for the unrestricted nonhomogeneous local frontier.

BOUNDARY:
  The weakest remaining gap inside the Cohen--Macaulay multiplicity-six
  height-three endpoint is:

    deg(f)<deg(g),
    f is a zerodivisor on B,
    (f,g) is m-primary,
    and the full tangent deficit-twenty obstruction is not yet proved.

NEXT_BOUNDED_OBJECT:
  analyze the associated-prime support of the lower-degree zerodivisor factor
  a in the Hilbert--Burch quadric-section presentation

    B=(S/I_2(Phi))/(q0).

  Determine whether m-primary J_k=(a,ell^k*b) forces a bounded degree gap k or
  a direct conormal lower bound.  Stop rather than importing the equal-degree
  regularization into the unequal-degree graded branch.
