Standalone closure of two formal repair operations for the order-13
F_13 semiregularity route: persistent line-bundle twists and direct-sum
stabilization by algebraic perfect complexes.

This file is pseudo-formal mathematical documentation.  It uses only the
functorial form of the Buchweitz--Flenner semiregularity map and does not
assert generic algebraicity.

Setup:
  Let Y := X_13 x X_13.

ExternalResult BuchweitzFlennerSemiregularityFormula:
  For a perfect complex E on a smooth complex variety Y, the semiregularity
  map has the form

    sigma_E(c) = Tr(exp(-At(E)) o c)

  for c in Ext^2_Y(E,E), with components in

    product_(q>=0) H^(q+2)(Y,Omega_Y^q).

  Source:
    Ragnar-Olaf Buchweitz, Hubert Flenner,
    A Semiregularity Map for Modules and Applications to Deformations,
    Compositio Mathematica 137 (2003), 135-210.

Theorem line_bundle_twist_preserves_semiregularity_kernel:
  Let E be a perfect complex on Y and L a line bundle on Y.  Tensoring by L
  identifies

    Ext^2_Y(E,E) ~= Ext^2_Y(E tensor L, E tensor L).

  Under this identification the two semiregularity maps differ by
  multiplication by the invertible cohomology class exp(-c1(L)).

  Consequently

    ker(sigma_E) ~= ker(sigma_(E tensor L)).

  In particular E is Buchweitz--Flenner semiregular if and only if
  E tensor L is semiregular.

Proof:
  The Atiyah class satisfies the tensor-product identity

    At(E tensor L)
      = At(E) tensor Id_L + Id_E tensor At(L).

  The two summands commute.  Since At(L)=c1(L), exponentiation gives

    exp(-At(E tensor L))
      = exp(-At(E)) * exp(-c1(L)).

  Tensoring by L is an autoequivalence, so it identifies the Ext^2 source.
  Taking the categorical trace yields

    sigma_(E tensor L)(c tensor Id_L)
      = exp(-c1(L)) cup sigma_E(c).

  The class exp(-c1(L)) has constant term 1 and inverse exp(c1(L)); hence
  multiplication by it is an automorphism of the finite-dimensional Hodge
  target.  Therefore the kernels agree.
Qed.

Corollary persistent_L1_twist_cannot_repair_order13_obstruction:
  Twisting any already non-semiregular order-13 candidate by a line bundle
  whose first Chern class lies in the persistent algebraic L1 subsystem
  cannot make it semiregular.

  Such a twist may alter rank-dependent Chern-character bookkeeping, but it
  does not remove a nonzero semiregularity kernel.
Qed.

Theorem direct_sum_stabilization_preserves_existing_kernel:
  Let E and V be perfect complexes on Y.  Suppose

    0 != c in ker(sigma_E) subset Ext^2_Y(E,E).

  Then E direct_sum V is not semiregular.

Proof:
  For the direct sum, At(E direct_sum V) and its exponential are block
  diagonal.  Embed c as the diagonal block

    diag(c,0) in Ext^2_Y(E direct_sum V,E direct_sum V).

  This class is nonzero because the diagonal Ext decomposition contains
  Ext^2_Y(E,E) as a direct summand.  The Buchweitz--Flenner categorical trace
  is additive over diagonal blocks, so

    sigma_(E direct_sum V)(diag(c,0))
      = sigma_E(c)
      = 0.

  Hence the stabilized complex has a nonzero semiregularity kernel.
Qed.

Corollary adding_algebraic_rank_cannot_repair_closed_rankzero_packages:
  Let E be any order-13 perfect-complex candidate already known to have a
  nonzero Buchweitz--Flenner kernel, including the canonical graph packages
  ruled out in

    order13_semiregularity_cross_ext_obstruction.v

  and

    order13_graph_union_semiregularity_dimension_obstruction.v.

  For every algebraic vector bundle or perfect complex V, the direct sum

    E direct_sum V

  remains non-semiregular.  In particular, introducing nonzero rank merely by
  stabilization cannot evade the established obstruction.
Qed.

Corollary twist_then_stabilize_and_stabilize_then_twist_are_closed:
  Any finite sequence generated by

    (1) tensoring with persistent line bundles, and
    (2) taking direct sums with algebraic perfect complexes

  cannot turn an already non-semiregular candidate into a semiregular one.
Qed.

Important limitation:
  This does NOT rule out a genuinely indecomposable nonzero-rank perfect
  complex whose primitive degree-four Chern-character component is
  proportional to Z_prim.

  It also does NOT rule out a non-split extension or mutation in which the
  deformation complex itself changes rather than retaining the obstructed
  object as a direct summand.

Boundary:
  generic algebraicity of the primitive F_13 generator alpha remains open.

First missing object after this no-go:
  a genuinely new indecomposable nonzero-rank or non-split perfect complex,
  not obtained from a closed rank-zero/graph package by persistent line-bundle
  twisting or direct-sum stabilization, together with an explicit injectivity
  proof for its Buchweitz--Flenner semiregularity map.