Standalone degree-six persistence closure for the unique surviving H01-C5 chain
value m=3 in the homogeneous q=4, height-two multiplicity-one, depth-one
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_quintic_forced.v

  and retain

    S = C[x1,x2,x3,x4],
    Q = (q1,q2,q3,q4),
    B = S/Q,
    Qsat = Q^sat,
    Ccore = S/Qsat,
    T = Qsat/Q,
    P = (l1,l2),
    D = P/Qsat,

  together with the H01-C5 state

    m = 3,
    sigma = 5,
    tau_3 = 1.

Choose a cubic

    gamma in (Qsat)_3

whose class spans

    T_3 = (Qsat)_3/Q_3,

and define

    J := Q + (gamma).

The preceding H01-C5 m=3 files prove

    J_3 = (Qsat)_3,
    J_4 = (Qsat)_4,
    J_5 = (Qsat)_5,

and

    dim_C(S/J)_3 = 8,
    dim_C(S/J)_4 = 9,
    dim_C(S/J)_5 = 10.

They also prove

    T_4 = S_1*T_3,
    T_5 = S_2*T_3.

This file performs one bounded task only: push J through degree six.  Macaulay
growth is exactly sharp at the saturated-core value, and standard Gotzmann
persistence then forces the Hilbert function of S/J to agree with the saturated
core in every later degree.  Together with the already established equality in
low degrees, this proves

    J = Qsat.

Consequently the full finite saturation defect is cyclic on its unique cubic
class:

    T ~= S/(Q:gamma)(-3).

This does NOT exclude the m=3 H01-C5 state.  It only closes the saturation-
generator problem inside that state.  No tangent estimate, H01-C4 argument,
q<=3 branch, or full order-13 closure is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. EXACT SATURATED-CORE VALUE IN DEGREE SIX
--------------------------------------------------------------------------

For m=3 the H01 residual module has Hilbert series

    Hilb_D(t) = (2*t + t^2 + t^3)/(1-t).

Hence

    dim_C D_n = 4

for every n>=3.

The exact line-quotient sequence is

    0 -> D -> Ccore -> S/P -> 0,

where

    S/P ~= C[s,t].

Therefore for every n>=3,

    dim_C Ccore_n
      = dim_C D_n + dim_C C[s,t]_n
      = 4 + (n+1)
      = n+5.

In particular:

Theorem H01_C5_m3_exact_core_degree_six:
  One has

    dim_C Ccore_6 = 11.
Qed.

Corollary H01_C5_m3_eventual_core_Hilbert_function:
  For every n>=3,

    dim_C Ccore_n = n+5.
Qed.

--------------------------------------------------------------------------
2. THE FIFTH MACAULAY SUCCESSOR OF TEN IS ELEVEN
--------------------------------------------------------------------------

The preceding quintic file proves

    dim_C(S/J)_5 = 10.

Write ten in its degree-five Macaulay expansion:

    10
      = binom(6,5)
        + binom(4,4)
        + binom(3,3)
        + binom(2,2)
        + binom(1,1)
      = 6+1+1+1+1.

Therefore its fifth Macaulay successor is

    10^{<5>}
      = binom(7,6)
        + binom(5,5)
        + binom(4,4)
        + binom(3,3)
        + binom(2,2)
      = 7+1+1+1+1
      = 11.

Theorem H01_C5_m3_fifth_Macaulay_successor:
  One has

    10^{<5>} = 11.
Qed.

--------------------------------------------------------------------------
3. DEGREE SIX IS FORCED TO THE SATURATED VALUE
--------------------------------------------------------------------------

Because

    J subset Qsat,

there is a graded surjection

    S/J -> S/Qsat = Ccore.

Hence in degree six,

    dim_C(S/J)_6 >= dim_C Ccore_6 = 11.

On the other hand, Macaulay growth for the standard graded algebra S/J gives

    dim_C(S/J)_6
      <= (dim_C(S/J)_5)^{<5>}
      = 10^{<5>}
      = 11.

Thus both inequalities are equalities.

Theorem H01_C5_m3_exact_intermediate_degree_six:
  One has

    dim_C(S/J)_6 = 11.
Qed.

Since

    dim_C(S/Qsat)_6 = 11

and J_6 subset (Qsat)_6, the induced surjection

    (S/J)_6 -> (S/Qsat)_6

is an isomorphism.

Theorem H01_C5_m3_intermediate_matches_saturation_in_degree_six:
  One has

    J_6 = (Qsat)_6.
Qed.

Corollary H01_C5_m3_no_new_degree_six_saturation_generator:
  Qsat has no new minimal generator of degree six modulo J.
Qed.

--------------------------------------------------------------------------
4. THE DEGREE-FIVE-TO-SIX GROWTH IS GOTZMANN
--------------------------------------------------------------------------

We have proved

    dim_C(S/J)_5 = 10,
    dim_C(S/J)_6 = 11 = 10^{<5>}.

Thus S/J has maximal Macaulay growth from degree five to degree six.

The ideal J is generated by the four quadrics of Q together with the cubic
gamma.  Hence J is generated in degrees at most three, in particular in degrees
at most five.

Therefore the hypotheses of standard Gotzmann persistence apply at degree five.

Theorem H01_C5_m3_Gotzmann_persistence_from_degree_five:
  For every n>=5,

    dim_C(S/J)_n = n+5.

Proof:
  Gotzmann persistence propagates equality in Macaulay growth from degree five
  onward.

  At degree d>=5, the number d+5 has the degree-d Macaulay representation

    d+5
      = binom(d+1,d)
        + binom(4,4)
        + binom(3,3)
        + binom(2,2)
        + binom(1,1).

  The top indices satisfy

    d+1 > 4 > 3 > 2 > 1

  because d>=5.  Its Macaulay successor is therefore

    binom(d+2,d+1)
      + binom(5,5)
      + binom(4,4)
      + binom(3,3)
      + binom(2,2)

    = (d+2)+1+1+1+1
    = d+6.

  Starting from the established value

    dim_C(S/J)_5 = 10 = 5+5,

  persistence and induction give

    dim_C(S/J)_n = n+5

  for every n>=5.
Qed.

Corollary H01_C5_m3_intermediate_has_multiplicity_one:
  The eventual Hilbert polynomial of S/J is

    n+5.

  Hence S/J has dimension two and multiplicity one.
Qed.

This is consistent with

    J^sat = Qsat

and

    e(S/Qsat)=1;

unlike the excluded larger-growth alternatives in the preceding files, no
multiplicity contradiction occurs here.

--------------------------------------------------------------------------
5. J AGREES WITH Qsat IN EVERY DEGREE >=5
--------------------------------------------------------------------------

For every n>=5, Section 4 gives

    dim_C(S/J)_n = n+5.

Section 1 gives exactly the same saturated-core value

    dim_C(S/Qsat)_n = dim_C Ccore_n = n+5

for every n>=5.

Because J subset Qsat, the natural map

    (S/J)_n -> (S/Qsat)_n

is surjective.  It is a surjection between finite-dimensional vector spaces of
the same dimension, hence an isomorphism.

Theorem H01_C5_m3_intermediate_matches_saturation_in_all_high_degrees:
  For every n>=5,

    J_n = (Qsat)_n.
Qed.

--------------------------------------------------------------------------
6. THE INTERMEDIATE IDEAL IS THE FULL SATURATION
--------------------------------------------------------------------------

The preceding m=3 files already prove

    J_3 = (Qsat)_3,
    J_4 = (Qsat)_4,
    J_5 = (Qsat)_5.

Section 5 proves equality for every degree n>=5.

It remains only to note the lower degrees.

The H01 Artinian-chain classification proves

    Q_2 = (Qsat)_2,
    T_1 = T_2 = 0.

Since J=Q+(gamma) and gamma has degree three,

    J_2 = Q_2 = (Qsat)_2.

Also Q has no linear generators and T_1=0, so

    J_1 = Q_1 = (Qsat)_1 = 0.

Degree zero agrees trivially.

Therefore J and Qsat agree in every graded degree.

Theorem H01_C5_m3_intermediate_is_the_full_saturation:
  One has

    J = Qsat.

Equivalently,

    Qsat = Q + (gamma).
Qed.

This is the exact saturation-generator closure for the H01-C5 m=3 state.

--------------------------------------------------------------------------
7. THE FULL SATURATION DEFECT IS CYCLIC
--------------------------------------------------------------------------

Let

    eta := gamma + Q in T_3.

Since

    Qsat = Q + (gamma),

we have

    T = Qsat/Q
      = (Q+(gamma))/Q
      = S*eta.

Thus eta generates all of T, not merely its degree-three-through-five truncation.

Put

    K := Ann_S(eta).

Then by definition

    K = (Q:gamma).

The standard cyclic-module map

    S(-3) -> T,
    r |-> r*eta

is surjective and has kernel K(-3).  Therefore:

Theorem H01_C5_m3_full_saturation_defect_is_cyclic:
  There is a graded S-module isomorphism

    T ~= S/K(-3)

  with

    K = (Q:gamma).
Qed.

Because T has finite length, S/K has finite length.

Corollary H01_C5_m3_cubic_colon_is_m_primary:
  The homogeneous colon ideal

    K = (Q:gamma)

  is m-primary.
Qed.

Corollary H01_C5_m3_no_later_saturation_generators:
  Qsat/Q has no minimal generators in degree four or higher.

  Its unique minimal generator is the cubic class eta.
Qed.

--------------------------------------------------------------------------
8. WHAT THIS DOES AND DOES NOT CLOSE
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_exact_core_degree_six.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_J6_equals_Qsat6.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_Gotzmann_persistence.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_J_equals_Qsat.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_saturation_defect_cyclic.

CURRENT_C5_STATUS:
  H01-C5 with m>=4 is empty.
  H01-C5 with m=3 remains geometrically possible at this stage, but its
  saturation defect is now completely rigid:

    Qsat = Q+(gamma),
    T ~= S/(Q:gamma)(-3),

  where gamma is the unique cubic saturation generator and (Q:gamma) is
  homogeneous m-primary.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-C5 with m=3.
  It does NOT prove a particular Hilbert function or length for T.
  It does NOT classify the m-primary colon (Q:gamma).
  It does NOT enter H01-C4.
  It does NOT make a tangent-space estimate.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_saturation_cyclic.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 with m=3.  Use the now exact cyclic presentation

    T ~= S/(Q:gamma)(-3)

  together with the five linear first syzygies of Q and the H01 saturated-core
  Hilbert series to determine the weakest possible Hilbert function of the
  m-primary colon K=(Q:gamma).  Test whether its first two graded pieces already
  force a tangent carrier or a contradiction with the four-quadric coefficient
  matrix.

NEXT_ACTIONS:
  1. Stay only in H01-C5 with m=3.
  2. Compute the lowest possible Hilbert function of S/(Q:gamma).
  3. Translate that Hilbert function into linear/quadratic generators of K.
  4. Test only the resulting coefficient-rank or tangent-carrier consequence.
  5. Stop before H01-C4, q<=3, or any full order-13 claim.
