Standalone regular-cut tangent obstruction for the maximal five-quadratic order-13 deviation-two frontier.

The preceding quadratic-generator reduction proves that if a dangerous six-generator Artin ideal has five quadratic minimal generators, then

  I = Q + (f),
  ht(Q)=3,
  dim(P/Q)=1,
  deg(f)>=3,

where Q is generated by the five quadrics and A=P/I has finite length N>=32.

This file proves that the final cut f cannot be regular on P/Q.  Consequently every dangerous five-quadratic core is necessarily non-Cohen--Macaulay/non-perfect and carries embedded zero-dimensional torsion.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

Setup:
  k := C,
  P is the four-dimensional regular local/analytic k-algebra,
  Q subset P has height three and is generated by five quadrics,
  B := P/Q has dimension one,
  f in P has degree at least three,
  I := Q+(f) is m-primary,
  A := P/I = B/(f),
  N := length_k(A)>0.

Notation:
  t(A) := dim_k Hom_P(I,A).

The order-13 semiregularity route requires the necessary tangent gate

  t(A) <= N-20.

Theorem regular_final_cut_injects_A_into_embedded_tangent_space:
  Assume f is a nonzerodivisor on B=P/Q, equivalently

    Q:f = Q.

  Then there is a natural injective k-linear map

    A -> Hom_P(I,A).

Proof:
  For a in A define

    phi_a : I -> A

  by

    phi_a(q+p f) := p a

  for q in Q and p in P, with the right-hand side taken in A.

  Well-definedness:
    If

      q+p f = q'+p' f,

    then

      (p-p')f in Q.

    Since Q:f=Q,

      p-p' in Q subset I,

    and therefore (p-p')a=0 in A.  Hence phi_a is independent of the chosen representation.

  P-linearity is immediate from the formula.

  Finally

    phi_a(f)=a.

  Thus phi_a=0 implies a=0, proving injectivity.
Qed.

Corollary regular_final_cut_fails_order13_tangent_gate:
  Under the regular-cut hypothesis,

    t(A) >= dim_k A = N.

  Since

    N > N-20,

  the necessary order-13 tangent gate cannot hold.
Qed.

Corollary dangerous_five_quadratic_cut_must_be_zero_divisor:
  If

    t(A) <= N-20,

  then f is a zerodivisor on B, equivalently

    Q:f strictly contains Q.
Qed.

Corollary perfect_or_CohenMacaulay_five_quadric_core_is_closed:
  Suppose Q is perfect of grade three.  Since P is regular and ht(Q)=3, this is equivalent here to B=P/Q being Cohen--Macaulay of dimension one.

  Because A=B/(f) has finite length, f is a parameter of the one-dimensional local ring B.  Every parameter of a one-dimensional Cohen--Macaulay local ring is a nonzerodivisor.

  Therefore Q:f=Q, so the preceding theorem gives

    t(A)>=N>N-20.

  Hence no perfect/Cohen--Macaulay five-quadric core can be dangerous.
Qed.

Corollary surviving_five_quadratic_core_has_depth_zero:
  Any five-quadratic core capable of passing the tangent gate must satisfy

    dim(B)=1,
    depth(B)=0,
    H^0_m(B) != 0.

  Equivalently, Q is not perfect and B has embedded zero-dimensional m-torsion.
Qed.

Refined colon-defect form:
  Let

    D := (Q:f)/Q = 0:_B f.

  The maps I->A that kill Q identify with

    Hom_B((f),A)
      ~= Hom_B(B/D,A)
      ~= Ann_A(D).

  Thus

    dim_k Hom_P(I,A) >= dim_k Ann_A(D).

  In particular a dangerous candidate must have nonzero colon defect D large/effective enough that

    dim_k Ann_A(D) <= N-20

  is at least possible.  No such bound is claimed here; this only isolates the surviving defect mechanism.

Comparison with grade-three perfect-ideal structure theory:
  There is extensive structure theory for special classes of grade-three perfect ideals with five generators (for example Brown 1987; Kang--Cho--Ko 2009; Celikbas--Laxmi--Kraskiewicz--Weyman 2020).  Those results are not used to assert that every height-three five-quadric ideal is perfect.

  The present argument is deliberately stronger in one direction and weaker in another:

    * if Q is perfect/CM, the order-13 tangent route closes immediately;
    * the only live q=5 case is precisely the non-perfect depth-zero case not covered by a blanket perfect-ideal classification.

Boundary:
  The q=5 frontier is reduced to

    Q generated by five quadrics,
    ht(Q)=3,
    dim(P/Q)=1,
    depth(P/Q)=0,
    f a parameter but a zerodivisor,
    D=(Q:f)/Q != 0,
    I=Q+(f) m-primary,
    length(A)=N>=32,
    dim Hom_P(I,A) <= N-20.

  No theorem here rules out all such embedded-torsion cores.

Next bounded object:
  analyze the finite-length torsion module H^0_m(P/Q) and the colon defect D=0:_B f; seek a lower bound on Ann_A(D) or on the full Hom_P(I,A) that exceeds N-20.  Stop if this becomes an open arbitrary non-Cohen--Macaulay five-quadric tangent problem.