Standalone closure of the multiplicity-five h=(1,3,1) subbranch of the
homogeneous q=4, height-three order-13 low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_e5_131_three_step_bockstein_reduction.v
    order13_q4_height3_e5_131_quadratic_core_two_step_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has

    h(Cbar/ell*Cbar)=(1,3,1).

  The preceding files prove

    Hilb_T(t)=t^2,
    m_B*T=0,
    Ann_B(T)=m_B,

  and write

    fbar=ell^s*a,
    gbar=ell^(s+k)*b,

  with

    s=d-2>=1,
    k=D-d>=0,
    a,b in Cbar_2,
    K_i:=(a,ell^i*b).

  They also prove K_0=(a,b) is m-primary, define X:=m_A, and identify

    epsilon
      =(N-1)-dim_C Hom_Cbar(K_k,X).

  The necessary order-13 tangent gate requires

    epsilon>=19.

  Finally, with

    G:=(a:b),
    Gsat:=G:ell^infinity,

  the preceding quadratic-core reduction proves

    (Gsat/G)_n=0 for every n>=2,

  and gives the layer formula

    Ann(K_(i-1)/K_i)=(G:ell^(i-1),ell).

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is to split according to whether the lower quadratic
predecessor a is regular on Cbar.  The regular case closes directly.  In the
zerodivisor case the properness of Gsat removes the possible degree-zero
saturation defect, so stabilization occurs after one ell-step rather than two.
This closes the remaining h=(1,3,1) branch.

Theorem multiplication_maps_give_a_universal_annihilator_bound:
  For every i>=0, multiplication defines a Cbar-linear map

    mu_i:X -> Hom_Cbar(K_i,X),
    mu_i(z)(u):=u*z.

  Its kernel is

    ker(mu_i)=0:_X K_i.

  Consequently

    (N-1)-dim_C Hom_Cbar(K_i,X)
      <=dim_C(0:_X K_i).

Proof:
  Cbar-linearity is immediate from commutativity.  The multiplication map
  mu_i(z) is zero exactly when every element of K_i kills z, namely exactly
  when z belongs to 0:_X K_i.

  Since dim_C X=N-1, rank-nullity gives

    dim im(mu_i)
      =(N-1)-dim_C(0:_X K_i).

  The image is a subspace of Hom_Cbar(K_i,X), so the displayed inequality
  follows.
Qed.

SECTION REGULAR_QUADRATIC_LOWER.

Assume a is a nonzerodivisor on Cbar.

Theorem regular_quadratic_has_only_the_socle_line_as_kernel_in_B:
  One has

    0:_B a=T.

Proof:
  Since a has positive degree and m_B*T=0, one has T subseteq 0:_B a.

  Conversely, if a*x=0 in B, then after projection to Cbar,

    a*xbar=0.

  Regularity of a on Cbar gives xbar=0, hence x belongs to T.
Qed.

Theorem regular_quadratic_section_of_B_has_length_eleven:
  One has

    Hilb_(B/aB)(t)=1+4*t+5*t^2+t^3,

  and therefore

    length_C(B/aB)=11.

Proof:
  The kernel theorem gives the multiplication exact sequence

    0 -> T(-2)
      -> B(-2)
      --a--> B
      -> B/aB
      -> 0.

  Since

    Hilb_B=Hilb_Cbar+t^2,
    Hilb_Cbar=(1+3*t+t^2)/(1-t),
    Hilb_T=t^2,

  one gets

    Hilb_(B/aB)
      =(1-t^2)*Hilb_B+t^2*Hilb_T
      =(1-t^2)*Hilb_Cbar+Hilb_T
      =1+4*t+5*t^2+t^3.
Qed.

Theorem regular_quadratic_lower_forces_epsilon_at_most_eleven:
  One has

    epsilon<=11.

Proof:
  Since K_k contains a,

    0:_X K_k subseteq 0:_A a.

  Multiplication by a on the finite-dimensional algebra A has kernel and
  cokernel of equal dimension, hence

    dim_C(0:_A a)=length_C(A/aA).

  The quotient A/aA is a quotient of B/aB, so

    dim_C(0:_A a)<=11.

  Apply the universal multiplication bound at i=k and use

    epsilon=(N-1)-dim Hom_Cbar(K_k,X).
Qed.

Corollary regular_quadratic_lower_is_closed:
  No candidate with a regular on Cbar can satisfy the necessary tangent gate.

Proof:
  The gate requires epsilon>=19, while the preceding theorem gives
  epsilon<=11.
Qed.

END REGULAR_QUADRATIC_LOWER.

SECTION ZERODIVISOR_QUADRATIC_LOWER.

Assume a is a zerodivisor on Cbar.

Theorem the_saturated_colon_is_proper:
  The ideal

    Gsat=(a:b):ell^infinity

  is a proper homogeneous ideal of Cbar.

Proof:
  Because Cbar is one-dimensional Cohen--Macaulay, it has no embedded
  associated primes.  Since a is a zerodivisor, there is a minimal prime P of
  Cbar with

    a in P.

  Since K_0=(a,b) is m-primary, b cannot belong to P.  Thus b is a unit after
  localizing at P, and

    G_P=(a:b)_P=(a)_P.

  This is a proper ideal of the zero-dimensional local ring Cbar_P because
  a belongs to its maximal ideal.

  The parameter ell is a nonzerodivisor on Cbar, so ell is not in P and becomes
  a unit in Cbar_P.  Saturating by powers of ell therefore does not change this
  localization:

    (Gsat)_P=G_P.

  Since the latter is proper, Gsat itself is proper.
Qed.

Corollary the_quadratic_colon_has_no_degree_zero_saturation_defect:
  One has

    (Gsat/G)_0=0.

Proof:
  A proper homogeneous ideal of the standard graded C-algebra Cbar has zero
  degree-zero part.  Thus (Gsat)_0=0, and the same is true of its subideal G.
Qed.

Theorem zerodivisor_quadratic_colon_saturates_after_one_parameter_step:
  One has

    G:ell=Gsat,

  and hence

    G:ell^j=Gsat

  for every j>=1.

Proof:
  The preceding quadratic-core reduction already proves

    (Gsat/G)_n=0

  for every n>=2.  The preceding corollary removes degree zero.  Therefore the
  finite saturation quotient Gsat/G can occur only in degree one.

  Let x be homogeneous in Gsat.

  If deg(x)>=2, then x already belongs to G.

  There is no nonzero degree-zero case because Gsat is proper.

  If deg(x)=1, then ell*x has degree two and lies in Gsat_2=G_2.  Hence

    x belongs to G:ell.

  Thus Gsat subseteq G:ell.  The reverse inclusion is automatic from the
  definition of saturation, proving equality.  All later colons are then equal
  to Gsat as well.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i

and retain

  Delta_i
    :=dim_C Hom_Cbar(K_(i-1),X)
      -dim_C Hom_Cbar(K_i,X).

Theorem every_layer_from_two_on_has_nonpositive_Bockstein_defect:
  For every i>=2,

    Delta_i<=0.

Proof:
  The exact layer-annihilator formula gives

    Ann_Cbar(V_i)=(G:ell^(i-1),ell).

  For i>=2, the one-step saturation theorem gives

    G:ell^(i-1)=Gsat.

  Hence every such layer is the same stable cyclic module

    V_i ~= Cbar/(Gsat,ell)

  up to grading shift.

  The stable cyclic connecting-map argument proved in the preceding quadratic
  reduction now applies verbatim with stabilization index two instead of
  three.  Put

    N_G:=0:_X Gsat.

  For y in N_G, the map K_i->X which sends

    a |-> 0,
    ell^i*b |-> y

  is well defined because every coefficient relation on ell^i*b lies in
  G:ell^i=Gsat.  Its connecting class is represented by the cyclic relation
  ell |-> y and Gsat |-> 0.  This class vanishes exactly for

    y in ell*N_G.

  Therefore the explicit connecting classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_Cbar(Cbar/(Gsat,ell),X)
      =dim_C Hom_Cbar(V_i,X),

  where the middle equality is rank-nullity for multiplication by ell on the
  finite-dimensional module N_G.

  Applying Hom(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  therefore gives Delta_i<=0.
Qed.

Theorem only_the_first_delayed_layer_can_be_positive_in_the_zerodivisor_case:
  For every k>=0,

    sum_(i=1)^k Delta_i<=6.

Proof:
  The preceding quadratic reduction proves Delta_1<=6.  Every i>=2 is
  nonpositive by the one-step stable compensation theorem.  Sum the bounds.
Qed.

Theorem zerodivisor_quadratic_lower_forces_epsilon_at_most_seventeen:
  One has

    epsilon<=17.

Proof:
  The exact baseline-plus-gap decomposition gives

    epsilon=eta_0+sum_(i=1)^k Delta_i.

  The preceding quadratic-core reduction proves universally

    eta_0<=11.

  The preceding theorem gives

    sum Delta_i<=6.

  Hence

    epsilon<=11+6=17.
Qed.

Corollary zerodivisor_quadratic_lower_is_closed:
  No candidate with a a zerodivisor on Cbar can satisfy the necessary tangent
  gate.

Proof:
  The gate requires epsilon>=19, while the preceding theorem gives
  epsilon<=17.
Qed.

END ZERODIVISOR_QUADRATIC_LOWER.

Theorem e5_h131_height3_subbranch_closed:
  No homogeneous q=4, ht(Q)=3, e(B)=5 candidate with saturated-core h-vector

    (1,3,1)

  can satisfy the necessary order-13 tangent-dimension gate.

Proof:
  The quadratic predecessor a is either regular or a zerodivisor on the
  one-dimensional Cohen--Macaulay core Cbar.

  The regular case has epsilon<=11.
  The zerodivisor case has epsilon<=17.

  Both contradict the required epsilon>=19.
Qed.

Interpretation:
  The five-point h=(1,3,1) core does not require a classification of its full
  multiplication algebra.  The only distinction needed is whether the lower
  quadratic predecessor a meets every minimal component.

  If it does, the degree-two section itself bounds the entire connecting
  excess by eleven.

  If it does not, the saturated colon is necessarily proper.  Properness
  removes the degree-zero part of the two-step saturation defect, forcing
  G:ell=Gsat.  The second and all later delayed layers are then compensated,
  leaving at most

    eta_0+Delta_1<=11+6=17.

IMPORTANT_NONCONCLUSION:
  This closes only

    q=4,
    ht(Q)=3,
    e(B)=5,
    h=(1,3,1).

  It does NOT close the other e=5 h-vectors

    (1,2,2),
    (1,2,1,1),

  nor any e=3 or e=4 h-vector, the q=4 height-two branch, homogeneous q<=3,
  the unrestricted nonhomogeneous local deviation-two frontier, or generic
  F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  The first remaining q=4, ht(Q)=3 low-multiplicity core is one of the seven
  h-vectors other than the now-closed e=5, h=(1,3,1) case.

NEXT_BOUNDED_OBJECT:
  recompute the same regular-versus-zerodivisor quadratic-predecessor split for
  the next smallest exact torsion profile,

    e=4,
    h=(1,3),
    Hilb_T=2*t^2,

  or, if the repository's ordering treats e=5 first, for

    e=5,
    h=(1,2,2),
    Hilb_T=t+t^2+t^3.

  Do not import the socle-line identity Ann_B(T)=m_B unless it is reproved for
  that torsion module.