Standalone Gotzmann-saturation contradiction closing the H01-C5 subcase m>=4
in the homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_linear_syzygy_reduction.v
    order13_q4_height2_depth_one_multiplicity_one_H01_C5_quartic_colon_reduction.v

  and retain the H01-C5 state

    m>=4,
    sigma=5,
    tau_3=1.

Write

    S=C[x1,x2,x3,x4],
    Q=(q1,q2,q3,q4),
    B=S/Q,
    Qsat=Q^sat,
    Ccore=S/Qsat.

The preceding H01 classification gives

    Hilb_D(t)=(2*t+t^2+...+t^m)/(1-t)

for the one-dimensional Cohen--Macaulay residual module D, together with the
line quotient

    0 -> D -> Ccore -> C[s,t] -> 0.

In H01-C5 one also has

    dim_C((Qsat)_3/Q_3)=1.

This file performs one bounded task only: adjoin a lift of that unique cubic
saturation class and compare its Macaulay growth with its saturation.  For
m>=4 the two are incompatible, so H01-C5 with m>=4 is empty.

No m=3 claim is made.
No H01-C4, tangent estimate, q<=3 branch, or full order-13 closure is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE SATURATED CORE HAS HILBERT VALUES 8 AND 10 IN DEGREES 3 AND 4
--------------------------------------------------------------------------

For m>=4, the residual Hilbert series gives

    dim_C D_3=4,
    dim_C D_4=5.

The line ring C[s,t] has

    dim_C C[s,t]_3=4,
    dim_C C[s,t]_4=5.

Hence the exact line-quotient sequence gives

Theorem H01_C5_mge4_exact_core_34:
  One has

    dim_C Ccore_3=8,
    dim_C Ccore_4=10.
Qed.

These are the only core Hilbert values needed below.

--------------------------------------------------------------------------
2. ADJOIN THE UNIQUE CUBIC SATURATION CLASS
--------------------------------------------------------------------------

Because tau_3=1, choose

    gamma in (Qsat)_3

whose class spans

    (Qsat)_3/Q_3.

Define the intermediate homogeneous ideal

    J:=Q+(gamma).

Then

    Q subset J subset Qsat.

Since Q is generated by quadrics and gamma has degree three, J is generated in
degrees at most three.

Theorem H01_C5_intermediate_cubic_matches_saturation_in_degree_three:
  One has

    J_3=(Qsat)_3.

Proof:
  By construction Q_3 has codimension one in (Qsat)_3 and gamma maps to a
  generator of that one-dimensional quotient.  Therefore

    J_3=Q_3+C*gamma=(Qsat)_3.
Qed.

Corollary H01_C5_intermediate_degree_three_value:
  One has

    dim_C(S/J)_3=8.
Qed.

--------------------------------------------------------------------------
3. MACAULAY FORCES THE INTERMEDIATE QUOTIENT TO HAVE VALUE 10 IN DEGREE FOUR
--------------------------------------------------------------------------

Since J subset Qsat, there is a graded surjection

    S/J -> S/Qsat=Ccore.

Therefore

    dim_C(S/J)_4 >= dim_C Ccore_4 = 10.

On the other hand, the degree-three value is eight.  Its third Macaulay
expansion is

    8=binom(4,3)+binom(3,2)+binom(1,1),

so

    8^{<3>}
      =binom(5,4)+binom(4,3)+binom(2,2)
      =5+4+1
      =10.

Macaulay growth for the standard graded algebra S/J therefore gives

    dim_C(S/J)_4<=10.

Combining the two inequalities yields:

Theorem H01_C5_intermediate_has_maximal_3_to_4_growth:
  One has

    dim_C(S/J)_3=8,
    dim_C(S/J)_4=10=8^{<3>}.
Qed.

Corollary H01_C5_no_new_saturation_generator_in_degree_four:
  One has

    J_4=(Qsat)_4.

Proof:
  The inclusion J_4 subset (Qsat)_4 induces the degree-four surjection

    (S/J)_4 -> (S/Qsat)_4.

  Both source and target have dimension ten, so the kernel is zero.
Qed.

--------------------------------------------------------------------------
4. GOTZMANN PERSISTENCE MAKES J A MULTIPLICITY-TWO IDEAL
--------------------------------------------------------------------------

The ideal J is generated in degrees at most three and its quotient has maximal
Macaulay growth from degree three to degree four.  Standard Gotzmann
persistence therefore propagates the maximal growth for every later degree.

Theorem H01_C5_intermediate_Gotzmann_profile:
  For every n>=3,

    dim_C(S/J)_n=2*n+2.

Proof:
  The degree-three value is

    8=2*3+2.

  For a degree d>=3, the Macaulay representation of 2*d+2 is

    2*d+2
      =binom(d+1,d)+binom(d,d-1)+binom(1,1).

  Its successor is

    binom(d+2,d+1)+binom(d+1,d)+binom(2,2)
      =(d+2)+(d+1)+1
      =2*d+4
      =2*(d+1)+2.

  Gotzmann persistence starts from the equality in degrees three and four and
  iterates this successor profile.
Qed.

Corollary H01_C5_intermediate_multiplicity_two:
  The quotient S/J has Krull dimension two and multiplicity

    e(S/J)=2.

Proof:
  The eventual Hilbert function is the linear polynomial 2*n+2.  Thus the
  quotient has dimension two and its multiplicity is the slope two.
Qed.

--------------------------------------------------------------------------
5. BUT J HAS THE SAME SATURATION AS Q
--------------------------------------------------------------------------

Theorem H01_C5_intermediate_saturation_is_Qsat:
  One has

    J^sat=Qsat.

Proof:
  Since

    Q subset J,

  monotonicity of saturation gives

    Q^sat subset J^sat.

  Hence

    Qsat subset J^sat.

  Conversely,

    J subset Qsat,

  and Qsat is saturated.  Therefore

    J^sat subset Qsat.

  The two inclusions give

    J^sat=Qsat.
Qed.

Corollary H01_C5_intermediate_and_core_have_same_Hilbert_polynomial:
  The quotients S/J and S/Qsat have the same Hilbert polynomial and the same
  multiplicity.

Proof:
  Saturation changes a homogeneous ideal only by an irrelevant-primary
  finite-length quotient.  Therefore a homogeneous ideal and its saturation
  have the same Hilbert polynomial.  Apply the preceding theorem.
Qed.

But the standing H01 branch has

    e(S/Qsat)=e(Ccore)=1.

Thus the same intermediate quotient S/J would have to satisfy simultaneously

    e(S/J)=2

from Gotzmann persistence and

    e(S/J)=1

from saturation invariance.

This is impossible.

--------------------------------------------------------------------------
6. CLOSURE OF H01-C5 FOR m>=4
--------------------------------------------------------------------------

Theorem q4_H01_C5_mge4_is_empty:
  There is no homogeneous ideal Q satisfying all of

    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    e(S/Qsat)=1,
    depth_m(S/Qsat)=1,
    H01 residual chain parameter m>=4,
    sigma=5,
    tau_3=1.

Proof:
  The preceding sections produce the contradiction

    e(S/J)=2=1.
Qed.

The contradiction occurs before any classification of the four-by-five linear
syzygy matrix is needed.

The cubic-colon conclusions from the previous file remain valid as conditional
reductions, but the m>=4 state to which they apply is now excluded.

--------------------------------------------------------------------------
7. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_empty.
  q4_height2_multiplicity_one_depth_one_H01_C5_intermediate_cubic_Gotzmann_contradiction.

CLOSED_SUBCASE:
  H01-C5 with m>=4.

SURVIVING_H01_C5_SUBCASE:
  m=3 only.

IMPORTANT_NONCONCLUSION:
  This file does NOT exclude H01-C5 with m=3.
  It does NOT exclude H01-C4.
  It does NOT close the full H01 branch.
  It does NOT close the multiplicity-one depth-one parent.
  It does NOT enter tangent estimates.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_open.
  q4_height2_multiplicity_one_depth_one_H01_C4_open.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 and treat the unique surviving chain value m=3.  For

    J=Q+(gamma)

  one has

    dim_C(S/J)_3=8,
    dim_C Ccore_4=9.

  Determine the exact degree-four value of S/J.  The value ten would reproduce
  the Gotzmann-saturation contradiction above, so any surviving m=3 state must
  have strict submaximal growth in degree four.

NEXT_ACTIONS:
  1. Stay only in H01-C5 with m=3.
  2. Use 9<=dim_C(S/J)_4<=10.
  3. Exclude the value 10 by the same Gotzmann-saturation contradiction.
  4. Record the forced value dim_C(S/J)_4=9 and the resulting quartic torsion image.
  5. Stop before H01-C4, tangent estimates, or q<=3.
