Standalone height split for the homogeneous q=4 order-13 deviation-two branch.

SCOPE:
  This file applies only to homogeneous six-generator ideals

    S := C[x1,x2,x3,x4],
    I subset S homogeneous and m-primary,
    A := S/I Artinian,
    mu(I)=6,
    length(A)=N>=32,

  with exactly four quadratic minimal generators.

  Write

    Q := (I_2),

  so Q is generated by four independent quadrics.  Because the remaining two minimal generators have degree at least three, write

    I = Q + (f,g),
    deg(f),deg(g)>=3.

  The unrestricted nonhomogeneous local deviation-two frontier is not affected.

This is pseudo-formal mathematical documentation.  It is not Coq and does not assert generic F_13 algebraicity.

ExternalResult TwoGeneratorHeightBound:
  For a Noetherian ring and ideal Q,

    ht(Q+(f,g)) <= ht(Q)+2.

  This is the two-generator form of Krull's height theorem.

Theorem four_quadric_core_has_height_two_or_three:
  Since I is m-primary in the four-dimensional polynomial/local ring,

    ht(I)=4.

  From I=Q+(f,g) and TwoGeneratorHeightBound,

    4 <= ht(Q)+2,

  hence

    ht(Q)>=2.

  Suppose ht(Q)=4.  Then the four independent quadratic generators of Q form a homogeneous system of parameters in the Cohen--Macaulay ring S and therefore a regular sequence.  Thus Q is a complete intersection of type (2,2,2,2), and

    length(S/Q)=2^4=16.

  Since Q subseteq I,

    N=length(S/I) <= length(S/Q)=16,

  contradicting N>=32.

  Therefore

    ht(Q) in {2,3}.
Qed.

Corollary homogeneous_q4_splits_into_curve_core_or_one_dimensional_core:
  If ht(Q)=2, then

    dim(S/Q)=2,

  and the two higher-degree generators f,g make the final Artinian cut.

  If ht(Q)=3, then

    dim(S/Q)=1,

  and f,g cut a one-dimensional four-quadric core to finite length.
Qed.

The remainder of this file treats only the height-three branch.

ExternalResult FourQuadraticAlmostCompleteIntersectionMultiplicity:
  Let Q be a homogeneous height-three ideal minimally generated by four quadrics in a polynomial ring over a field.  Then

    e(S/Q) <= 6.

  If

    e(S/Q)=6,

  then S/Q is Cohen--Macaulay.

  Source: the multiplicity bound for quadratic almost complete intersections used in Huneke--Mantero--McCullough--Seceleanu, A Tight Bound on the Projective Dimension of Four Quadrics, J. Pure Appl. Algebra 222 (2018), together with the maximal-multiplicity Cohen--Macaulay criterion cited there.

Corollary height_three_four_quadric_multiplicity_is_small:
  In the ht(Q)=3 branch,

    1 <= e(S/Q) <=6.

  The endpoint e=6 is Cohen--Macaulay.
Qed.

Theorem height_three_four_quadric_section_model:
  Assume ht(Q)=3.

  After changing the four-dimensional basis of Q_2, choose generators

    q1,q2,q3,a

  such that

    K := (q1,q2,q3)

  is a regular sequence of three quadrics.

  Set

    R := S/K,
    J := (a)R.

  Then

    S/Q = R/J,

  and X:=Proj(R) is the zero-dimensional complete intersection of three quadrics in P^3, of length eight.
Qed.

Theorem complete_intersection_sections_stabilize_in_degree_three:
  The Hilbert series of R is

    Hilb_R(t)=(1-t^2)^3/(1-t)^4=(1+t)^3/(1-t).

  Hence

    dim R_0=1,
    dim R_1=4,
    dim R_2=7,
    dim R_n=8 for n>=3.

  Since X is finite of length eight,

    dim H^0(X,O_X(n))=8

  for every n.  Since R is one-dimensional Cohen--Macaulay, H^0_m(R)=0, so the natural maps

    R_n -> H^0(X,O_X(n))

  are injective and therefore isomorphisms for every n>=3.
Qed.

Theorem height_three_four_quadric_saturation_defect_vanishes_from_degree_five:
  Let

    Qsat := saturation of Q with respect to m,
    B := S/Q,
    T := H^0_m(B)=Qsat/Q.

  Then

    T_n=0

  for every n>=5.

Proof:
  In R=S/K, Q/K is the principal quadratic ideal J=(a).
  Let Jsat denote its saturation in R.

  On X=Proj(R), the sheaf ideal J~ is generated by the section a, giving a surjection

    O_X(-2) -> J~ -> 0.

  Its kernel is coherent on the zero-dimensional scheme X, hence has vanishing H^1.  After twisting by n, global sections therefore give a surjection

    H^0(X,O_X(n-2)) -> H^0(X,J~(n)).

  For n>=5, both n and n-2 are at least three.  The preceding theorem identifies

    R_n ~= H^0(X,O_X(n)),
    R_(n-2) ~= H^0(X,O_X(n-2)).

  Therefore the degree-n principal piece

    J_n = a R_(n-2)

  equals the full saturated degree-n piece Jsat_n.

  Hence

    T_n=(Jsat/J)_n=0

  for all n>=5.
Qed.

Corollary height_three_four_quadric_saturation_torsion_is_m4_killed:
  Since Qsat is proper, T_0=0.  Together with T_n=0 for n>=5, T is supported in degrees 1 through 4.  Therefore

    m^4 T=0.
Qed.

IMPORTANT_NONCONCLUSION:
  The q=5 tangent closure does not automatically repeat here.

  In the present q=4 branch the final ideal is

    I=Q+(f,g)

  with two higher-degree generators.  There is no single distinguished principal final cut whose variation is already identified with Ann_A(D).  The preceding saturation result therefore supplies low-degree control of the embedded torsion but, by itself, does not prove

    dim Hom_S(I,A) > N-20.

  No tangent lower bound for the two-generator final cut is asserted here.

HEIGHT_THREE_Q4_BOUNDARY:
  Q is generated by four quadrics,
  ht(Q)=3,
  e(S/Q)<=6,
  T=H^0_m(S/Q),
  m^4 T=0,
  I=Q+(f,g) m-primary,
  deg(f),deg(g)>=3,
  length(A)=N>=32,
  and the required tangent gate remains

    dim Hom_S(I,A)<=N-20.

HEIGHT_TWO_Q4_BOUNDARY:
  Q is generated by four quadrics,
  ht(Q)=2,
  dim(S/Q)=2,
  I=Q+(f,g) m-primary.

  No saturation/tangent closure for this two-dimensional core is claimed here.

UNRESTRICTED_LOCAL_BOUNDARY:
  unchanged.  None of these homogeneous quadratic-core reductions is asserted for arbitrary nonhomogeneous local six-generator ideals.

NEXT_BOUNDED_OBJECT:
  attack the ht(Q)=3 branch first.  Analyze the two-generated B-ideal L=(f,g) in B=S/Q and its conormal module Hom_B(L,B/L), separating the Cohen--Macaulay e=6 endpoint from the embedded-torsion e<=5 cases.  Stop rather than assuming a general Hilbert-scheme tangent lower bound for arbitrary one-dimensional singular B.