Standalone s=1 rank-two exclusion for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_fourth_J_adic_layer_rank_reduction.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    V := Span_C{l1,l2},
    P := C[l1,l2] = Sym(V),
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

The preceding files prove

    G := J^2*T/J^3*T ~= C(-3)^s,

  where

    s = dim_C Syz_1(Q) in {0,1,2},

  and

    H := J^3*T/J^4*T ~= C(-4)^h,

  with a surjection

    mu : V tensor_C G_3 -> H_4.

This file treats only

    s=1.

It proves

    rank(mu)=h <= 1.

Thus the previously allowed rank-two value h=2 is impossible.
The r=4 subcase closes with h=0.  The r=3 subcase is reduced to one exact
common-linear-factor obstruction.

The s=2 case is not treated here.
The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Define the pure-transverse cubic relation space

    K3 := Q_3 intersect P_3.

Theorem s1_has_exactly_three_pure_cubic_relations:
  If s=1, then

    dim_C K3=3.

Proof:
  The exact third-layer quotient gives

    G_3 ~= P_3/K3.

  Since dim_C P_3=4 and dim_C G_3=s=1,

    dim_C K3=3.
Qed.

ExternalResult Hilbert_Burch_for_three_cubics_in_two_variables:
  Let K subset C[x,y] be a height-two homogeneous ideal minimally generated by
  three independent cubic forms.  Then

    0 -> P(-5) direct_sum P(-4) -> P(-3)^3 -> K -> 0

  is its minimal graded resolution.

  Consequently

    K_4=P_4.

Justification:
  Hilbert--Burch gives two minimal first syzygies.  If their coefficient
  degrees are a,b>=1, the quotient Hilbert numerator is

    1-3*t^3+t^(3+a)+t^(3+b).

  Height two forces divisibility by (1-t)^2.  Differentiating at t=1 gives

    a+b=3.

  Hence {a,b}={1,2}.  The degree-four part of K therefore has dimension

    3*dim P_1 - 1 = 6-1=5=dim P_4.
Qed.

Theorem r4_s1_forces_h_zero:
  Assume s=1 and the first-conormal case is r=4.  Then

    H=0,
    h=0,
    J^3*T=0.

Proof:
  The third-layer file constructs two independent pure cubic relations

    Pz,Pw in K3

  and proves that Pz,Pw have no common projective zero in P(V)=P^1.
  Therefore gcd(Pz,Pw)=1.

  Since K3 contains Pz,Pw, the ideal

    K:=(K3) subset P

  has height two.  The three-dimensionality of K3 says its three cubic forms
  are a minimal homogeneous generating set.

  Apply the external Hilbert--Burch result:

    P_1*K3=P_4.

  Because K3 subset Q and Q is an ideal,

    P_1*K3 subset Q_4 intersect P_4.

  Hence

    Q_4 intersect P_4=P_4.

  The exact fourth-layer quotient in degree four is

    H_4 ~= P_4/(Q_4 intersect P_4),

  so H_4=0.  The previous file proves H is generated in degree four, hence
  H=0 and h=0.

  Finally H=0 gives

    J^3*T=J^4*T=J*(J^3*T),

  and Nakayama applied to the finite-length module J^3*T yields J^3*T=0.
Qed.

We now treat r=3 without assuming basepoint freeness.

Theorem r3_s1_exact_cubic_normal_form:
  Assume s=1 and r=3.  Let

    0 != H0 in Q_2 intersect P_2

  span the unique pure-transverse quadratic direction established in the
  first-conormal classification.

  Then there exists a cubic

    R3 in P_3

  with

    R3 notin H0*V

  such that

    K3 = H0*V direct_sum C*R3.

Proof:
  Since H0 belongs to Q, both

    l1*H0,
    l2*H0

  belong to K3 and are independent.  Thus H0*V is a two-dimensional subspace
  of K3.

  Since dim_C K3=3, choose R3 in K3 outside H0*V.  The displayed direct-sum
  decomposition follows.
Qed.

Corollary the_common_factor_degree_is_at_most_one:
  In the r=3,s=1 normal form above,

    deg gcd(H0,R3) in {0,1}.

Proof:
  Since H0 is quadratic, a gcd of degree two would mean H0 divides R3.  Then

    R3=H0*L

  for some linear form L, contradicting R3 notin H0*V.
Qed.

Theorem r3_s1_quartic_span_has_codimension_at_most_one:
  In the r=3,s=1 case,

    codim_{P_4}(P_1*K3) <= 1.

  More precisely:

    gcd(H0,R3)=1
      ==> P_1*K3=P_4;

    deg gcd(H0,R3)=1
      ==> dim_C(P_1*K3)=4.

Proof:
  From the exact cubic normal form,

    P_1*K3
      = H0*P_2 + R3*P_1.

  The first summand has dimension three and the second has dimension two.

  COPRIME CASE.

  Suppose

    H0*A2 = R3*L1

  for A2 in P_2 and L1 in P_1.  Since gcd(H0,R3)=1, H0 divides L1.
  This is impossible by degree unless L1=0, and then A2=0.  Thus the two
  summands have zero intersection and their sum has dimension five.  Since
  dim_C P_4=5, it equals P_4.

  COMMON-LINEAR-FACTOR CASE.

  Write

    H0=D*H1,
    R3=D*R2,

  where D,H1 are linear and R2 is quadratic.  Since H0 does not divide R3,
  H1 does not divide R2, so gcd(H1,R2)=1.

  An equality

    H0*A2=R3*L1

  becomes

    H1*A2=R2*L1.

  Coprimality forces H1 to divide L1.  Hence L1=c*H1 and A2=c*R2.
  Therefore the intersection of H0*P_2 and R3*P_1 is exactly one-dimensional.

  Its sum has dimension

    3+2-1=4.
Qed.

Theorem s1_rank_two_is_impossible:
  If s=1, then

    h<=1.

  Equivalently,

    rank(mu)<2.

Proof:
  The r=4 case has h=0 by the preceding theorem.

  In the r=3 case, the exact fourth-layer quotient gives

    H_4 ~= P_4/(Q_4 intersect P_4).

  Since K3 subset Q,

    P_1*K3 subset Q_4 intersect P_4.

  The preceding quartic-span theorem shows P_1*K3 has codimension at most one
  in P_4.  Therefore the further quotient H_4 has dimension at most one.

  Thus h=dim_C H_4<=1 in every s=1 case.
Qed.

Corollary exact_remaining_s1_obstruction:
  If s=1 and h=1, then necessarily

    r=3,
    deg gcd(H0,R3)=1,

  and

    Q_4 intersect P_4 = P_1*K3

  has dimension four.

  In every other s=1 configuration,

    h=0

  and therefore

    J^3*T=0.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does NOT rule out the single residual configuration

    s=1,
    r=3,
    deg gcd(H0,R3)=1,
    h=1.

  In that case the fourth layer is exactly one-dimensional:

    H ~= C(-4).

  Closing it requires proving either

    Q_4 intersect P_4 strictly contains P_1*K3

  or that the surviving quartic class dies after one further transverse
  multiplication.

  No assertion is made here for s=2.
  No tangent-gate contradiction is claimed.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_third_J_adic_layer_bounded.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_rank2_excluded.
  not q4_height2_CM_line_core_s1_closed.
  not q4_height2_CM_line_core_s2_closed.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Treat only the residual s=1,r=3 common-linear-factor case

    K3=H0*V direct_sum C*R3,
    deg gcd(H0,R3)=1,
    h=1.

  Determine the fifth transverse layer

    J^4*T/J^5*T

  from this explicit factorization, or prove an additional pure quartic relation
  already forces h=0.

NEXT_BOUNDED_OBJECT:
  In the residual h=1 case, write

    H0=D*H1,
    R3=D*R2,

  with gcd(H1,R2)=1, identify the unique quartic class in

    P_4/(P_1*K3),

  and compute its l1,l2 multiples in degree five.  Do not enter s=2 or the
  depth-one branch.