Standalone Hilbert-floor refinement for the remaining multiplicity-one,
depth-one saturated core in the homogeneous q=4, height-two branch of the
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_residual_profile.v

  and retain its notation

    S := C[x1,x2,x3,x4],
    P := (l1,l2),
    Q subset Qsat subset P,
    D := P/Qsat,
    T := Qsat/Q,

  with

    dim D = 1,
    depth_m(D)=1,
    dim D_1 = 2-u1,
    dim D_2 = 5-u2,
    dim T_1 = u1,
    dim T_2 = u2-2,

  and

    u1 in {0,1},
    u2 <= 3+u1.

This file determines the smallest Hilbert numerator permitted by the exact
low-degree data.  The four-independent-quadric hypothesis is used explicitly
to remove the stale numerical state (u1,u2)=(1,2).

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. DEGREE-ONE GENERATION AND ARTINIAN REDUCTION
--------------------------------------------------------------------------

Theorem residual_module_is_generated_in_degree_one:
  The graded S-module D=P/Qsat is generated by D_1.

Proof:
  The linear prime P=(l1,l2) is generated by P_1.  Passing to the quotient by
  Qsat shows that the images of l1,l2 generate D.  Any linear element of Qsat
  removes the corresponding generator.  Hence D is generated by D_1.
Qed.

Choose a linear nonzerodivisor h on the one-dimensional Cohen--Macaulay module
D and put

    E:=D/hD.

Then E has finite length and is generated in degree one.

Theorem residual_Hilbert_series_is_the_Artinian_reduction_numerator:
  One has

    Hilb_D(t)=Hilb_E(t)/(1-t),

and

    dim E_1 = 2-u1,
    dim E_2 = 3+u1-u2.

Proof:
  Since h is D-regular,

    0 -> D(-1) --h--> D -> E -> 0

is exact.  Therefore

    Hilb_E(t)=(1-t)Hilb_D(t).

  Because D_0=0,

    dim E_1=dim D_1=2-u1.

  In degree two,

    dim E_2=dim D_2-dim D_1
           =(5-u2)-(2-u1)
           =3+u1-u2.
Qed.

Theorem zero_in_one_degree_forces_zero_in_all_later_degrees:
  If E_n=0 for some n>=1, then E_m=0 for every m>=n.

Proof:
  Since E is generated in degree one,

    E_(n+1)=S_1*E_n.

  Thus E_n=0 implies E_(n+1)=0, and induction gives all later vanishing.
Qed.

--------------------------------------------------------------------------
2. FOUR QUADRICS REMOVE THE STALE (u1,u2)=(1,2) STATE
--------------------------------------------------------------------------

Theorem universal_lower_bound_u2_at_least_two:
  One has

    u2>=2.

Proof:
  The saturated-core bookkeeping gives

    dim (Qsat)_2=2+u2.

  Since the four-dimensional space Q_2 is contained in (Qsat)_2,

    2+u2>=4.
Qed.

Theorem u1_one_forces_u2_at_least_three:
  If

    u1=1,

then

    u2>=3.

Proof:
  Let l span (Qsat)_1.  Then l*S_1 is a four-dimensional subspace of
  (Qsat)_2.

  Suppose u2=2.  Then

    dim (Qsat)_2=2+u2=4,

so

    (Qsat)_2=l*S_1.

  But Q_2 is also four-dimensional and contained in this space.  Therefore

    Q_2=l*S_1.

  Since Q is generated by Q_2,

    Q=l*m,

which is contained in the height-one prime (l).  Hence

    ht(Q)<=1,

contradicting the standing ht(Q)=2 hypothesis.
Qed.

Corollary exact_allowed_u_pairs:
  The only allowed low-degree pairs are

    (u1,u2)=(0,2),
    (u1,u2)=(0,3),
    (u1,u2)=(1,3),
    (u1,u2)=(1,4).

In particular

    (u1,u2)=(1,2)

is impossible.
Qed.

--------------------------------------------------------------------------
3. EXACT L0 ENDPOINT AND FLOOR
--------------------------------------------------------------------------

Theorem L0_u2_3_has_exact_Hilbert_series:
  If

    (u1,u2)=(0,3),

then

    Hilb_E(t)=2*t,
    Hilb_D(t)=2*t/(1-t),

and

    dim D_n=2

for every n>=1.

Proof:
  Here

    dim E_1=2,
    dim E_2=0.

  The vanishing theorem kills every later E_n.  Divide Hilb_E by 1-t.
Qed.

Theorem L0_u2_2_Hilbert_floor:
  If

    (u1,u2)=(0,2),

then

    Hilb_E(t)=2*t+t^2+sum_(n>=3) a_n*t^n

with every a_n>=0.  Hence coefficientwise

    Hilb_D(t)>=(2*t+t^2)/(1-t).
Qed.

Corollary exact_L0_saturation_defect_start:
  In L0:

    u2=3 => (dim T_1,dim T_2)=(0,1),
    u2=2 => (dim T_1,dim T_2)=(0,0).
Qed.

--------------------------------------------------------------------------
4. EXACT L1 ENDPOINT AND FLOOR
--------------------------------------------------------------------------

Theorem L1_u2_4_has_exact_Hilbert_series:
  If

    (u1,u2)=(1,4),

then

    Hilb_E(t)=t,
    Hilb_D(t)=t/(1-t),

and

    dim D_n=1

for every n>=1.

Proof:
  Here

    dim E_1=1,
    dim E_2=0.

  Degree-two vanishing forces all later E_n to vanish.  Divide by 1-t.
Qed.

Theorem L1_u2_3_Hilbert_floor:
  If

    (u1,u2)=(1,3),

then

    Hilb_E(t)=t+t^2+sum_(n>=3) b_n*t^n

with every b_n>=0.  Hence coefficientwise

    Hilb_D(t)>=(t+t^2)/(1-t).
Qed.

Corollary exact_L1_saturation_defect_start:
  In L1:

    u2=4 => (dim T_1,dim T_2)=(1,2),
    u2=3 => (dim T_1,dim T_2)=(1,1).
Qed.

--------------------------------------------------------------------------
5. EXACT FOUR-STATE HILBERT FRONTIER
--------------------------------------------------------------------------

Corollary multiplicity_one_depth_one_residual_Hilbert_frontier:
  The remaining multiplicity-one depth-one branch has exactly four initial
  Hilbert states:

    H00:
      (u1,u2)=(0,3),
      Hilb_D(t)=2*t/(1-t).

    H01:
      (u1,u2)=(0,2),
      Hilb_D(t)>=(2*t+t^2)/(1-t) coefficientwise.

    H10:
      (u1,u2)=(1,4),
      Hilb_D(t)=t/(1-t).

    H11:
      (u1,u2)=(1,3),
      Hilb_D(t)>=(t+t^2)/(1-t) coefficientwise.

There is no H12 state.
Qed.

Corollary exact_coefficientwise_minima:
  The two coefficientwise smallest residual Hilbert series in the two linear
  saturation branches are

    u1=0:
      Hilb_D(t)=2*t/(1-t),

    u1=1:
      Hilb_D(t)=t/(1-t).
Qed.

--------------------------------------------------------------------------
6. SHARP BOUNDARY
--------------------------------------------------------------------------

The multiplicity-one residual frontier is now coherent with the four-quadric
height-two condition:

  H00 and H10 have exact Hilbert series;
  H01 and H11 have sharp degree-two Hilbert floors;
  the former H12 numerical state is impossible because it would force
  Q=l*m and height at most one.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove that every one of H00,H01,H10,H11 is realized by an
  actual saturated four-quadric configuration.

  It does NOT classify Qsat up to coordinates.
  It does NOT classify the high-degree tail of T.
  It makes no tangent-space estimate.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_Hilbert_frontier_four_states.
  q4_height2_multiplicity_one_depth_one_H12_excluded.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Test the exact cyclic endpoint

    H10:
      (u1,u2)=(1,4),
      Hilb_D=t/(1-t).

  Recover Qsat from the single surviving degree-one residual generator and
  derive its exact annihilator/colon presentation.

NEXT_ACTIONS:
  1. Stay inside q=4 height-two multiplicity one.
  2. Treat only H10.
  3. Recover Qsat from D=P/Qsat with Hilb_D=t/(1-t).
  4. Determine Ann_S(D) and the corresponding intersection/colon form.
  5. Stop before any tangent-space estimate.
