Standalone quadratic-predecessor/one-step-colon reduction for the multiplicity-five
h=(1,2,2) subbranch of the homogeneous q=4, height-three order-13
low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_e5_122_cyclic_torsion_annihilator_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has Artin-reduction h-vector

    h(Cbar/ell*Cbar)=(1,2,2).

  The preceding cyclic-torsion reduction proves

    T ~= C[z]/(z^3)(-1),
    Hilb_T(t)=t+t^2+t^3,
    m_B^3*T=0,
    length_C(B/Ann_B(T))=3.

  After a constant GL_2(C) regularization of the two final cuts L=(f,g)B,
  it also proves

    0:_B h = 0:_B k = T,

  and, if epsilon is the two-generator connecting excess, the necessary
  order-13 tangent gate forces

    epsilon>=17.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded reduction.  The h=(1,2,2) core
stabilizes in degree two, so the degree-three final-cut data have quadratic
predecessors.  The regular quadratic predecessor is excluded.  In the
zerodivisor case every degree-gap layer after the first is Bockstein-compensated.
Thus every surviving candidate is already visible in the single one-step
quadratic colon

  K_1=(a,ell*b).

No classification of that one-step colon is claimed here.

Theorem choose_parameter_active_on_the_cyclic_torsion:
  One may choose the Noether parameter ell so that

    ell is a nonzerodivisor on Cbar,

  and simultaneously the degree-one class of ell is not contained in

    Ann_B(T)_1.

  For such a choice, multiplication by ell gives isomorphisms

    T_1 -> T_2,
    T_2 -> T_3,

  and

    0:_T ell = T_3,
    0:_B ell = T_3.

Proof:
  The set of linear zerodivisors on the one-dimensional Cohen--Macaulay ring
  Cbar is the finite union of the degree-one parts of its associated, hence
  minimal, primes.  Its complement is a nonempty Zariski-open subset of
  Cbar_1.

  The preceding cyclic-torsion file identifies

    B/Ann_B(T) ~= C[z]/(z^3)

  as a standard graded Artin algebra.  Its degree-one part is one-dimensional,
  so Ann_B(T)_1 is a proper linear subspace of B_1.  Avoiding that subspace is
  one further nonempty open condition.  Choose ell satisfying both conditions.

  Under

    T ~= C[z]/(z^3)(-1),

  the image of ell in B/Ann_B(T) is a nonzero scalar multiple of z.  Hence its
  action is nonzero between the one-dimensional successive pieces

    T_1 -> T_2 -> T_3,

  and therefore both maps are isomorphisms.  It kills T_3 for degree reasons,
  so 0:_T ell=T_3.

  Finally project

    0 -> T -> B -> Cbar -> 0

  through multiplication by ell.  Since ell is regular on Cbar, every element
  killed by ell in B lies in T.  Therefore

    0:_B ell=0:_T ell=T_3.
Qed.

Theorem exact_active_parameter_section_has_length_six:
  One has

    Hilb_(B/ell*B)(t)=1+3*t+2*t^2,

  and hence

    length_C(B/ell*B)=6.

Proof:
  The h=(1,2,2) core has

    Hilb_Cbar(t)=(1+2*t+2*t^2)/(1-t),

  while

    Hilb_T(t)=t+t^2+t^3.

  Thus Hilb_B=Hilb_Cbar+Hilb_T.  The preceding theorem gives

    Hilb_(0:_B ell)(t)=t^3.

  The multiplication exact sequence

    0 -> (0:_B ell)(-1)
      -> B(-1)
      --ell--> B
      -> B/ell*B
      -> 0

  yields

    Hilb_(B/ell*B)
      =(1-t)*Hilb_B+t*Hilb_(0:_B ell)
      =1+3*t+2*t^2.
Qed.

Theorem the_h122_core_has_quadratic_predecessors:
  Order the final degrees as

    d:=deg(f)<=D:=deg(g),

  and put

    r:=d-3>=0,
    k:=D-d>=0.

  Then there are unique alpha,beta in Cbar_3 with

    fbar=ell^r*alpha,
    gbar=ell^(r+k)*beta.

  Moreover there are unique a,b in Cbar_2 such that

    alpha=ell*a,
    beta=ell*b.

  Put

    K_i:=(a,ell^i*b)

  for i>=0 and

    s:=r+1=d-2>=1.

  Then

    J_i:=(alpha,ell^i*beta)=ell*K_i,
    Lbar=(fbar,gbar)=ell^s*K_k,

  and K_0=(a,b) is m-primary in Cbar.

Proof:
  The low-multiplicity core profile gives the first degree-three factorization.

  Since

    Hilb_Cbar(t)=(1+2*t+2*t^2)/(1-t),

  one has

    dim_C Cbar_n=5

  for every n>=2.  Multiplication by the regular parameter ell is injective in
  every degree, hence

    ell:Cbar_n -> Cbar_(n+1)

  is an isomorphism for every n>=2.  In particular alpha and beta have unique
  quadratic predecessors a and b.

  The displayed ideal identities follow immediately.  The preceding core
  profile proves J_k is m-primary.  Since J_k is contained in J_0=ell*K_0, any
  homogeneous prime containing K_0 also contains J_0 and hence J_k.  Therefore
  K_0 is m-primary.
Qed.

Theorem the_actual_final_cut_ideal_is_divisible_by_the_active_parameter:
  For

    L:=(f,g)B,

  one has

    L subseteq ell*B.

Proof:
  On Cbar the preceding theorem gives

    fbar=ell^s*a,
    gbar=ell^(s+k)*b,

  with s>=1.

  Choose homogeneous lifts of a and b to B.  If d>=4, the difference between
  f and ell^s*a lies in T_d=0, so f is divisible by ell in B.  If d=3, then
  s=1 and

    f-ell*a lies in T_3.

  The active-parameter theorem makes

    ell:T_2 -> T_3

  surjective, so this discrepancy is itself an ell-multiple.  Thus f belongs
  to ell*B also in the cubic case.

  The same argument applies to g.  Hence L subseteq ell*B.
Qed.

Corollary exact_parameter_annihilator_in_A_has_dimension_six:
  One has

    A/ell*A ~= B/ell*B,

  and therefore

    dim_C(0:_A ell)=6.

  In particular, for

    X:=Ann_A(T),

  one has

    dim_C(0:_X ell)<=6.

Proof:
  Since L subseteq ell*B,

    A/ell*A
      =B/(L,ell)
      ~=B/ell*B.

  The preceding section theorem gives length six.  Multiplication by ell on
  the finite-dimensional vector space A has kernel and cokernel of equal
  dimension, so

    dim_C(0:_A ell)=length_C(A/ell*A)=6.

  The final containment is immediate from X subseteq A.
Qed.

Theorem saturated_core_maps_inject_into_actual_conormal_maps:
  Put

    X:=Ann_A(T).

  Then

    dim_C X=N-3

  and there is a natural injection

    Hom_Cbar(K_k,X) -> Hom_B(L,A).

Proof:
  The preceding cyclic-torsion reduction proves dim_C X=N-3 and L*T=0.
  Hence L is naturally a Cbar-module.

  If phi:L->A is B-linear and t belongs to T, then

    t*phi(x)=phi(t*x)=0

  for every x in L.  Therefore the image of phi lies in X.  Conversely T acts
  trivially on both L and X, so every Cbar-linear map L->X is B-linear.  Thus

    Hom_B(L,A)=Hom_Cbar(L,X).

  Projection B->Cbar gives a surjection of Cbar-modules

    L -> Lbar

  with kernel L intersect T.  Precomposition therefore injects

    Hom_Cbar(Lbar,X) -> Hom_Cbar(L,X).

  Finally multiplication by ell^s is a Cbar-module isomorphism

    K_k -> ell^s*K_k=Lbar

  because ell is a nonzerodivisor on Cbar.  Combining these maps gives the
  required injection.
Qed.

For i>=0 define the quadratic-core deficit

  delta_i
    :=(N-3)-dim_C Hom_Cbar(K_i,X).

Theorem dangerous_candidate_forces_quadratic_core_deficit_seventeen:
  If the necessary order-13 tangent gate holds, then

    delta_k>=17.

Proof:
  The preceding cyclic-torsion conormal formula gives

    dim_C Hom_B(L,A)=N-3-epsilon,

  and the tangent gate forces epsilon>=17.

  The injection of the preceding theorem gives

    N-3-epsilon
      =dim Hom_B(L,A)
      >=dim Hom_Cbar(K_k,X).

  Therefore

    epsilon
      <=(N-3)-dim Hom_Cbar(K_k,X)
      =delta_k.

  Thus delta_k>=17.
Qed.

Theorem multiplication_maps_give_a_universal_quadratic_deficit_bound:
  For every i>=0, multiplication gives a Cbar-linear map

    mu_i:X -> Hom_Cbar(K_i,X),
    mu_i(x)(u):=u*x,

  whose kernel is

    0:_X K_i.

  Consequently

    delta_i<=dim_C(0:_X K_i).

Proof:
  The kernel identity is immediate from the definition.  Rank-nullity gives

    dim im(mu_i)
      =(N-3)-dim_C(0:_X K_i).

  Since the image is a subspace of Hom_Cbar(K_i,X), rearranging gives the
  displayed inequality.
Qed.

Theorem every_regular_quadratic_core_section_has_length_at_most_thirteen:
  Let qbar in Cbar_2 be a nonzerodivisor and let q in B_2 be any homogeneous
  lift.  Then

    length_C(B/qB)<=13.

  Consequently

    dim_C(0:_A q)<=13.

Proof:
  Since qbar is regular on Cbar, projection through

    0 -> T -> B -> Cbar -> 0

  gives

    0:_B q=0:_T q.

  The torsion module is the shifted cubic string

    T ~= C[z]/(z^3)(-1).

  A degree-two element can act on T only from T_1 to T_3; it kills T_2 and
  T_3 for degree reasons.  Hence

    length_C(0:_T q)<=3.

  The multiplication sequence by q shows that the zero-dimensional quotient
  B/qB has length

    2*e(Cbar)+length_C(0:_B q)
      <=2*5+3
      =13.

  Since A/qA is a quotient of B/qB,

    length_C(A/qA)<=13.

  Multiplication by q on finite-dimensional A has kernel and cokernel of equal
  dimension, so

    dim_C(0:_A q)=length_C(A/qA)<=13.
Qed.

SECTION REGULAR_QUADRATIC_LOWER.

Assume a is a nonzerodivisor on Cbar.

Theorem regular_quadratic_lower_has_deficit_at_most_thirteen:
  One has

    delta_k<=13.

Proof:
  Since K_k contains a,

    0:_X K_k subseteq 0:_A a.

  Choose a homogeneous quadratic lift of a to B.  The preceding quadratic
  section theorem gives

    dim_C(0:_A a)<=13.

  Apply the universal multiplication bound to K_k.
Qed.

Corollary regular_quadratic_lower_is_closed:
  No candidate with a regular on Cbar can satisfy the necessary order-13
  tangent gate.

Proof:
  A dangerous candidate requires delta_k>=17, while the preceding theorem gives
  delta_k<=13.
Qed.

END REGULAR_QUADRATIC_LOWER.

SECTION ZERODIVISOR_QUADRATIC_LOWER.

Assume a is a zerodivisor on Cbar.

Put

  G:=(a:b),
  Gsat:=G:ell^infinity.

Theorem the_zerodivisor_quadratic_colon_saturation_is_proper:
  Gsat is a proper homogeneous ideal of Cbar.

Proof:
  Since Cbar is one-dimensional Cohen--Macaulay, its associated primes are its
  minimal primes.  Because a is a zerodivisor, choose a minimal prime P with

    a in P.

  Since K_0=(a,b) is m-primary, b is not in P.  Thus b becomes a unit after
  localizing at P and

    G_P=(a:b)_P=(a)_P,

  which is proper in the local ring Cbar_P.

  The parameter ell is a nonzerodivisor, hence ell is not in P and becomes a
  unit in Cbar_P.  Saturating by powers of ell therefore does not change this
  localization:

    (Gsat)_P=G_P.

  Thus Gsat is proper.
Qed.

Theorem the_quadratic_colon_saturates_after_one_parameter_step:
  One has

    (Gsat/G)_n=0

  for every n>=2, and consequently

    G:ell=Gsat,
    G:ell^j=Gsat

  for every j>=1.

Proof:
  Let x in Gsat be homogeneous of degree n>=2.  Choose m>=0 with

    ell^m*x*b in (a),

  say

    ell^m*x*b=a*c.

  Here c has degree n+m.  Since multiplication by ell is an isomorphism on
  Cbar in every degree starting with degree two, there is c0 in Cbar_n with

    c=ell^m*c0.

  Hence

    ell^m*(x*b-a*c0)=0.

  Regularity of ell permits cancellation, giving x*b=a*c0 and therefore x in
  G.  This proves equality of G and Gsat in all degrees at least two.

  Properness of the homogeneous ideal Gsat gives (Gsat)_0=0, so the finite
  quotient Gsat/G can occur only in degree one.  Multiplication by ell sends
  that degree into degree two, where Gsat and G agree.  Thus

    ell*Gsat subseteq G,

  equivalently Gsat subseteq G:ell.  The reverse inclusion follows from the
  definition of saturation.  Hence G:ell=Gsat, and all later ell-colons agree
  with Gsat as well.
Qed.

For i>=1 put

  V_i:=K_(i-1)/K_i.

Lemma exact_quadratic_layer_annihilator:
  The class

    v_i:=ell^(i-1)*b mod K_i

  generates V_i and has annihilator

    Ann_Cbar(v_i)=(G:ell^(i-1),ell).

  In particular, for every i>=2,

    V_i ~= Cbar/(Gsat,ell)

  up to grading shift.

Proof:
  If c*v_i=0, then

    c*ell^(i-1)*b
      =p*a+q*ell^i*b

  for suitable p,q.  Therefore

    (c-q*ell)*ell^(i-1)*b in (a),

  so

    c-q*ell in G:ell^(i-1).

  This proves one containment in the annihilator formula; the reverse is
  immediate.  For i>=2, the preceding one-step saturation theorem gives

    G:ell^(i-1)=Gsat.
Qed.

Put

  Delta_i
    :=dim_C Hom_Cbar(K_(i-1),X)
      -dim_C Hom_Cbar(K_i,X).

Theorem every_layer_after_the_first_has_nonpositive_Bockstein_defect:
  For every i>=2,

    Delta_i<=0.

Proof:
  For i>=2 the layer theorem gives, up to grading shift,

    V_i ~= Cbar/(Gsat,ell).

  Put

    N_G:=0:_X Gsat.

  For y in N_G define a map K_i->X by

    a |-> 0,
    ell^i*b |-> y.

  It is well defined because every coefficient relation on ell^i*b belongs to

    G:ell^i=Gsat.

  In the cyclic presentation of

    0 -> K_i -> K_(i-1) -> V_i -> 0,

  the connecting class of this map is represented by

    ell |-> y,
    Gsat |-> 0.

  The class vanishes exactly when y belongs to ell*N_G.  Hence these explicit
  connecting classes have rank

    dim_C(N_G/ell*N_G)
      =dim_C(0:_N_G ell)
      =dim_C Hom_Cbar(V_i,X),

  where the middle equality is rank-nullity for multiplication by ell on the
  finite-dimensional module N_G.

  Applying Hom_Cbar(-,X) to

    0 -> K_i -> K_(i-1) -> V_i -> 0

  gives

    Delta_i
      =dim Hom_Cbar(V_i,X)-rank(connecting)
      <=0.
Qed.

Theorem the_first_delayed_layer_has_defect_at_most_six:
  One has

    Delta_1<=6.

Proof:
  Applying Hom_Cbar(-,X) to

    0 -> K_1 -> K_0 -> V_1 -> 0

  gives

    Delta_1<=dim_C Hom_Cbar(V_1,X).

  The cyclic module V_1 is killed by ell, so evaluation at its generator embeds

    Hom_Cbar(V_1,X) -> 0:_X ell.

  The active-parameter section theorem gives

    dim_C(0:_X ell)<=6.

  Hence Delta_1<=6.
Qed.

Theorem equal_degree_quadratic_baseline_has_deficit_at_most_thirteen:
  One has

    delta_0<=13.

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring
  Cbar, a general constant linear combination

    qbar=lambda*a+mu*b

  avoids every associated prime and is therefore a quadratic nonzerodivisor.

  Then

    0:_X K_0 subseteq 0:_A q.

  The regular quadratic section theorem gives dim_C(0:_A q)<=13.  Apply the
  universal multiplication bound at i=0.
Qed.

Theorem every_zerodivisor_survivor_is_visible_at_the_one_step_colon:
  For every k>=0,

    delta_k
      =delta_0+sum_(i=1)^k Delta_i.

  If k=0, then

    delta_k<=13.

  If k>=1, then

    delta_k<=delta_1<=19.

  Consequently, any candidate satisfying the necessary order-13 tangent gate
  must have

    k>=1,
    17<=delta_1<=19.

  In particular such a survivor must also satisfy

    delta_0>=11,
    Delta_1>=4.

Proof:
  The displayed decomposition is the telescoping identity obtained directly
  from the definitions of delta_i and Delta_i.

  The k=0 bound is the preceding baseline theorem.  For k>=1, every Delta_i
  with i>=2 is nonpositive, so

    delta_k<=delta_0+Delta_1=delta_1.

  The baseline and first-layer bounds give

    delta_1<=13+6=19.

  A dangerous candidate has delta_k>=17, hence delta_1>=17.  Combining with
  the upper bound gives 17<=delta_1<=19.  Since delta_1=delta_0+Delta_1 with
  delta_0<=13 and Delta_1<=6, the lower bound seventeen forces

    delta_0>=11,
    Delta_1>=4.
Qed.

END ZERODIVISOR_QUADRATIC_LOWER.

Interpretation:
  The h=(1,2,2) branch no longer has an unbounded degree-gap obstruction.

  The exact cyclic torsion lets one choose the Noether parameter actively on
  T, giving the six-dimensional section B/ell*B.  This bounds the only
  potentially positive delayed quadratic layer by six.

  If the lower quadratic predecessor a is regular, the entire branch is
  excluded by delta_k<=13.

  If a is a zerodivisor, properness of the saturated colon forces

    (a:b):ell=(a:b):ell^infinity,

  so every layer after the first is Bockstein-compensated.  Any surviving
  candidate is therefore already detected by

    K_1=(a,ell*b)

  and its deficit lies in the three-value window

    17,18,19.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove delta_1<=16 and therefore does NOT close the
  e=5, h=(1,2,2) height-three branch.

  It does not classify the multiplication algebra of the finite one-step
  quadratic colon, and it does not construct an example with delta_1>=17.

  It makes no claim for h=(1,2,1,1), the remaining lower-multiplicity cores,
  q=4 height two, homogeneous q<=3, the unrestricted nonhomogeneous local
  deviation-two frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e5_h122_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Prove the finite one-step bound

    delta_1
      =(N-3)-dim_C Hom_Cbar((a,ell*b),Ann_A(T))
      <=16

  in the zerodivisor-a case, under

    T ~= C[z]/(z^3)(-1),
    K_0=(a,b) m-primary,
    G=(a:b),
    G:ell=G:ell^infinity,

  or construct the first concrete one-step core with delta_1>=17.

NEXT_BOUNDED_OBJECT:
  Analyze only the exact sequence

    0 -> K_1 -> K_0 -> V_1 -> 0,

  together with the finite quadratic section B/qB of length at most thirteen
  and the six-dimensional ell-section.  Determine whether the simultaneous
  extremal requirements

    delta_0>=11,
    Delta_1>=4

  can occur.  Stop at the first explicit one-step colon reaching delta_1>=17
  rather than moving to another h-vector.
