Standalone Hilbert-profile classification for the remaining multiplicity-one,
depth-one saturated core in the homogeneous q=4, height-two branch of the
order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_residual_profile.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Ccore := S/Qsat,
    T := Qsat/Q,

with

    dim Ccore=2,
    depth_m(Ccore)=1,
    e(Ccore)=1.

The preceding residual-profile reduction constructs a height-two linear prime

    P=(l1,l2)

and a one-dimensional Cohen--Macaulay module

    D:=P/Qsat

sitting in

    0 -> D -> Ccore -> S/P -> 0,

where

    S/P ~= C[s,t].

It also proves, with

    u1:=dim_C (Qsat)_1,

that

    u1 in {0,1},
    dim D_1 = 2-u1,
    dim T_1 = u1,

and, writing u2 as in the saturated-core bookkeeping,

    dim D_2 = 5-u2,
    dim T_2 = u2-2,
    u2 <= 3+u1.

This file performs exactly one bounded next step:

  classify the smallest possible Hilbert series of D in each u1 branch,
  using only one-dimensional Cohen--Macaulayness, the four-quadric degree-two
  containment, and the exact degree-one/degree-two conservation laws.

No tangent-space estimate is made here.
No q<=3 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE RESIDUAL h-VECTOR
--------------------------------------------------------------------------

Because D is one-dimensional Cohen--Macaulay over the infinite field C, choose
one linear form h which is D-regular.  Put

    H:=D/hD.

Then H has finite length and

    Hilb_D(t)=Hilb_H(t)/(1-t).

Write

    c_n:=dim_C H_n
       =dim_C D_n-dim_C D_(n-1)

for n>=0, with D_(-1)=0.

Theorem residual_h_vector_is_nonnegative_and_starts_in_degree_one:
  One has

    c_n>=0

for every n, and

    c_0=0,
    c_1=2-u1.

Proof:
  Regularity of h gives exact sequences in every degree

    0 -> D_(n-1) --h--> D_n -> H_n -> 0.

  Thus c_n is the displayed nonnegative difference.

  Since P and Qsat are homogeneous proper ideals with no degree-zero part,

    D_0=0,

so c_0=0.  The preceding residual profile proves

    D_1=2-u1,

hence

    c_1=D_1-D_0=2-u1.
Qed.

Corollary exact_residual_Hilbert_numerator:
  There are nonnegative integers

    c_2,c_3,c_4,...

with finite support such that

    Hilb_D(t)
      = ((2-u1)*t + c_2*t^2 + c_3*t^3 + ...)/(1-t).

Moreover

    e(D)=sum_(n>=1) c_n.

Proof:
  The first statement is the standard Hilbert-series identity from the regular
  linear section H=D/hD.

  Since H has finite length, only finitely many c_n are nonzero.
  For a one-dimensional Cohen--Macaulay graded module, the multiplicity equals
  length(H), which is the sum of its Hilbert-function values c_n.
Qed.

--------------------------------------------------------------------------
2. THE DEGREE-TWO INCREMENT IS EXACTLY BINARY
--------------------------------------------------------------------------

Theorem exact_formula_for_the_second_h_vector_entry:
  One has

    c_2 = 1+u1-dim_C T_2.

Proof:
  By definition,

    c_2=dim D_2-dim D_1.

  The exact degree-two conservation law gives

    dim D_2=3-dim T_2,

while the degree-one law gives

    dim D_1=2-u1.

  Subtracting yields

    c_2=(3-dim T_2)-(2-u1)
       =1+u1-dim T_2.
Qed.

We now sharpen the possible values of dim T_2.

Theorem four_quadrics_force_u2_at_least_two:
  One has

    u2>=2.

Equivalently

    dim T_2>=0.

Proof:
  The saturated-core bookkeeping gives

    dim_C (Qsat)_2=2+u2.

  Since Q_2 is four-dimensional and Q_2 subset (Qsat)_2,

    2+u2>=4.

  Hence u2>=2.
Qed.

Theorem in_the_u1_one_branch_u2_cannot_equal_two:
  If

    u1=1,

then

    u2>=3.

Proof:
  Let l span the one-dimensional space (Qsat)_1.
  Then

    l*S_1 subset (Qsat)_2

is four-dimensional.

  If u2=2, then

    dim (Qsat)_2=2+u2=4,

so necessarily

    (Qsat)_2=l*S_1.

  But Q_2 is also four-dimensional and sits inside this space, hence

    Q_2=l*S_1.

  Since Q is generated by its degree-two part,

    Q=l*m.

  The height-one prime (l) contains Q, forcing

    ht(Q)<=1,

contrary to the standing ht(Q)=2 hypothesis.

  Therefore u2!=2, and the previous theorem gives u2>=3.
Qed.

Corollary exact_low_degree_integer_inventory:
  Exactly one of the following occurs.

  CASE L0:
    u1=0,
    u2 in {2,3},
    dim T_1=0,
    dim T_2 in {0,1},
    dim D_1=2,
    dim D_2 in {3,2}.

  CASE L1:
    u1=1,
    u2 in {3,4},
    dim T_1=1,
    dim T_2 in {1,2},
    dim D_1=1,
    dim D_2 in {2,1}.

Proof:
  For L0, the preceding residual profile gives u2<=3 and the lower bound gives
  u2>=2.

  For L1, the preceding profile gives u2<=4 and the previous theorem gives
  u2>=3.

  The displayed T and D dimensions follow from

    dim T_2=u2-2,
    dim D_2=5-u2.
Qed.

Corollary the_second_h_vector_entry_is_zero_or_one:
  In both L0 and L1,

    c_2 in {0,1}.

More precisely,

  L0:
    u2=3 <=> dim T_2=1 <=> c_2=0,
    u2=2 <=> dim T_2=0 <=> c_2=1.

  L1:
    u2=4 <=> dim T_2=2 <=> c_2=0,
    u2=3 <=> dim T_2=1 <=> c_2=1.
Qed.

--------------------------------------------------------------------------
3. SHARP SMALLEST HILBERT SERIES IN EACH LINEAR-SATURATION BRANCH
--------------------------------------------------------------------------

Theorem L0_has_coefficientwise_minimal_residual_series:
  In Case L0 one has coefficientwise

    Hilb_D(t) >= 2*t/(1-t).

  Equality holds if and only if

    c_n=0 for every n>=2.

  In particular equality forces

    u2=3,
    dim T_1=0,
    dim T_2=1,
    dim D_n=2 for every n>=1,
    e(D)=2.

Proof:
  In L0 the first h-vector entry is

    c_1=2.

  All later c_n are nonnegative, so

    Hilb_D(t)
      =(2*t+sum_(n>=2)c_n*t^n)/(1-t)
      >=2*t/(1-t)

coefficientwise.

  Equality holds exactly when every later c_n vanishes.
  In particular c_2=0, which by the exact inventory is equivalent to u2=3 and
  dim T_2=1.

  With numerator 2*t, every positive-degree Hilbert-function value is two, and
  the multiplicity is the numerator value at t=1, namely two.
Qed.

Theorem L1_has_coefficientwise_minimal_residual_series:
  In Case L1 one has coefficientwise

    Hilb_D(t) >= t/(1-t).

  Equality holds if and only if

    c_n=0 for every n>=2.

  In particular equality forces

    u2=4,
    dim T_1=1,
    dim T_2=2,
    dim D_n=1 for every n>=1,
    e(D)=1.

Proof:
  In L1 the first h-vector entry is

    c_1=1.

  Again all later c_n are nonnegative, so

    Hilb_D(t)
      =(t+sum_(n>=2)c_n*t^n)/(1-t)
      >=t/(1-t).

  Equality is equivalent to vanishing of all later c_n.
  In particular c_2=0, which in L1 is equivalent to u2=4 and dim T_2=2.

  The resulting Hilbert function is one in every positive degree and the
  multiplicity is one.
Qed.

Corollary exact_smallest_residual_profiles:
  The two coefficientwise smallest possible residual Hilbert series allowed by
  the established q=4 multiplicity-one constraints are

    L0 minimum:
      Hilb_D(t)=2*t/(1-t),
      (dim T_1,dim T_2)=(0,1),
      e(D)=2.

    L1 minimum:
      Hilb_D(t)=t/(1-t),
      (dim T_1,dim T_2)=(1,2),
      e(D)=1.
Qed.

--------------------------------------------------------------------------
4. THE ONLY IMMEDIATE NONMINIMAL LOW-DEGREE ALTERNATIVES
--------------------------------------------------------------------------

Corollary L0_nonminimality_starts_with_one_new_degree_two_h_class:
  If L0 is not already at its coefficientwise minimum in degree two, then

    c_2=1,
    u2=2,
    dim T_2=0,

and

    Hilb_D(t)
      =(2*t+t^2+sum_(n>=3)c_n*t^n)/(1-t)

with all c_n>=0.
Qed.

Corollary L1_nonminimality_starts_with_one_new_degree_two_h_class:
  If L1 is not already at its coefficientwise minimum in degree two, then

    c_2=1,
    u2=3,
    dim T_2=1,

and

    Hilb_D(t)
      =(t+t^2+sum_(n>=3)c_n*t^n)/(1-t)

with all c_n>=0.
Qed.

Thus the four-quadric containment has removed any larger degree-two jump:
there is no residual h-vector beginning

    2*t + 2*t^2 + ...

in L0, and no residual h-vector beginning

    t + 2*t^2 + ...

in L1.

--------------------------------------------------------------------------
5. GEOMETRIC MEANING OF THE MINIMAL NUMERATORS
--------------------------------------------------------------------------

The module D has projective support of dimension zero.  Its one-dimensional
multiplicity e(D) is therefore the total projective length of that residual
support, counted with module multiplicity.

Corollary minimal_L0_has_projective_residual_length_two:
  If

    Hilb_D(t)=2*t/(1-t),

then the residual projective module has total length two.
Qed.

Corollary minimal_L1_has_projective_residual_length_one:
  If

    Hilb_D(t)=t/(1-t),

then the residual projective module has total length one.
Qed.

IMPORTANT_NONCONCLUSION:
  These statements classify the SHARPEST HILBERT-SERIES LOWER ENVELOPE and the
  exact low-degree integer inventory.  They do not yet classify Qsat up to
  coordinates.

  In particular this file does NOT prove that the L0 minimum must be two reduced
  isolated points, nor that the L1 minimum must be one reduced isolated point.
  Nonreduced length-two residual structure is not excluded here.

  It also does NOT prove that every numerically allowed h-vector is realized by
  a four-quadric Q.

  No tangent-space estimate is asserted.
  No q<=3 branch is entered.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_residual_h_vector_classified.
  q4_height2_multiplicity_one_depth_one_minimal_Hilbert_profiles_identified.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Classify the equality cases

    Hilb_D(t)=2*t/(1-t)   in L0,
    Hilb_D(t)=t/(1-t)     in L1,

as saturated extensions of the line quotient, and determine whether the
four-quadric subideal Q can realize them without already producing a large
Koszul/tangent carrier.

NEXT_ACTIONS:
  1. Stay inside q=4 height-two multiplicity one.
  2. Treat only the L1 minimum Hilb_D=t/(1-t) first.
  3. Recover the exact saturated ideal Qsat from the cyclic residual module.
  4. Determine the resulting colon sequence before any tangent estimate.
  5. Do not enter L0, q<=3, or the full order-13 parent.
