Standalone residual-colon closure of the REGULAR_LOWER multiplicity-two
subbranch of the homogeneous q=4, height-three order-13 deviation-two problem.

SCOPE:
  Continue from

    order13_q4_height3_e2_rank_two_core_reduction.v
    order13_q4_height3_e2_regular_lower_connecting_reduction.v
    order13_q4_height3_e2_exact_saturation_linkage_profile.v

  Work only with

    S := C[x1,x2,x3,x4],
    Q subset S generated minimally by four independent quadrics,
    ht(Q)=3,
    B:=S/Q,
    e(B)=2,
    T:=H^0_m(B),
    Cbar:=B/T,

  in the two-core-active REGULAR_LOWER case.

  The preceding reductions prove

    Cbar ~= C[x,y]/(x*y)

  or

    Cbar ~= C[ell,v]/(v^2),

  the two final cuts have one common degree

    d>=13,

  the exact saturation defect is

    Hilb_T(t)=2*t+4*t^2+2*t^3,
    length_C(T)=8,
    m^3*T=0,

  and every dangerous order-13 candidate would have to satisfy

    mu_A0(N_T)-dim_C Soc_A0(N_T)>=6,

  where

    A:=B/(h,k),
    A0:=Cbar/(hbar,kbar),
    N_T:=Ann_A(T).

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is to compute Ann_B(T) from the residual-intersection
presentation of the saturation defect and thereby close REGULAR_LOWER.

ExternalResult ThreeResidualIntersectionOfTwoGeneratedCompleteIntersection:
  Let V be a Cohen--Macaulay ring and let

    J=(x,y)

  be generated by a V-regular sequence.  Let

    G=(g1,g2,g3) subseteq J

  with

    [g1,g2,g3]^T = Psi*[x,y]^T

  for a 3-by-2 matrix Psi.  If

    ht(G:J)>=3,

  then the standard residual-intersection formula gives

    G:J = G + I_2(Psi),

  where I_2(Psi) is the ideal generated by the three 2-by-2 minors of Psi.

  This is the codimension-two, three-residual-intersection specialization of
  the Bruns--Kustin--Miller resolution of residual intersections of complete
  intersections.  The easy inclusion I_2(Psi) subseteq G:J follows directly
  from the 2-by-2 Cramer identities; the height-three hypothesis is the
  residual-intersection condition needed for the reverse inclusion.

We now put the e=2 saturation into that form.

Theorem normalize_the_e2_saturation_complete_intersection:
  After a linear change of coordinates, the saturated ideal Qsat has the form

    Qsat=(x,y,q0),

  where x,y are independent linear forms and q0 is a quadric, and x,y,q0 form
  an S-regular sequence.

Proof:
  The rank-two core Cbar=S/Qsat is a one-dimensional graded Gorenstein algebra
  with h-vector (1,1).  Equivalently it is a quadratic hypersurface after two
  independent linear equations.  Thus its defining height-three ideal is the
  complete intersection CI(1,1,2).  Choose the two linear generators as x,y
  and the quadratic generator as q0.
Qed.

Theorem normalize_three_quadrics_inside_Qsat:
  After changing the basis of three quadratic generators inside Q, one may
  write

    q1=x*a+y*b,
    q2=x*c+y*d0,
    q3=q0,

  for linear forms a,b,c,d0.

Proof:
  Choose any regular sequence of three quadratic combinations q1,q2,q3 inside
  Q.  Since Q subseteq Qsat=(x,y,q0), every qi has an expression

    qi=x*ai+y*bi+lambda_i*q0

  with ai,bi linear and lambda_i scalar.

  At least one lambda_i is nonzero; otherwise all three quadrics would lie in
  (x,y), contradicting height three.  A GL_3(C) change of the regular-sequence
  basis makes

    lambda_1=lambda_2=0,
    lambda_3=1.

  Replacing the chosen quadratic generator q0 of Qsat by q3 preserves
  Qsat=(x,y,q0).  This yields the displayed form.
Qed.

Let r be the fourth quadratic generator of Q after the preceding basis choice.

Theorem fourth_quadric_has_one_more_row_form:
  Modulo q0 one may write

    r=x*p+y*s

  for linear forms p,s.

  Consequently, in

    V:=S/(q0),

  the ideal defining B is

    G=(x*a+y*b,
       x*c+y*d0,
       x*p+y*s).

  The saturated ideal becomes

    J=(x,y) subset V,

  and

    B=V/G,
    T=J/G.

Proof:
  Since r belongs to Q subseteq Qsat=(x,y,q0), write

    r=x*p+y*s+lambda*q0.

  Replacing r by r-lambda*q0 is an invertible change among the four quadratic
  generators and gives the displayed form.  Passing to V kills q0.

  The image of Qsat in V is exactly (x,y).  Since T=Qsat/Q, its image in the
  quotient B is J/G.
Qed.

Define the 3-by-2 matrix

  Psi := [[a,b],
          [c,d0],
          [p,s]].

Then

  [x*a+y*b,
   x*c+y*d0,
   x*p+y*s]^T
    = Psi*[x,y]^T.

Theorem x_y_is_a_regular_sequence_in_V:
  The elements x,y form a V-regular sequence.

Proof:
  The sequence x,y,q0 is S-regular by the saturation complete-intersection
  theorem.  Quotienting first by q0 leaves x,y as a regular sequence in
  V=S/(q0).
Qed.

Theorem residual_colon_has_height_three:
  Put

    H:=G:J=G:(x,y)

  in V.  Then

    ht(H)=3.

Proof:
  The quotient J/G=T is finite length because J is the homogeneous saturation
  of G.  Hence for every homogeneous prime P different from the irrelevant
  maximal ideal,

    G_P=J_P.

  Localizing the colon gives

    H_P=G_P:J_P=J_P:J_P=V_P.

  Therefore no nonmaximal homogeneous prime contains H.  Since V has dimension
  three, H is supported at the irrelevant maximal ideal and has height three.
Qed.

Theorem exact_residual_colon_formula_for_the_e2_defect:
  One has

    G:(x,y)=G+I_2(Psi).

Proof:
  The ring V is Cohen--Macaulay because it is a hypersurface quotient of S.
  The preceding theorems give that x,y is a regular sequence and that the
  residual colon has height three.  Apply
  ThreeResidualIntersectionOfTwoGeneratedCompleteIntersection.
Qed.

For completeness, write the three minors as

  Delta12:=a*d0-b*c,
  Delta13:=a*s-b*p,
  Delta23:=c*s-d0*p.

The Cramer identities are

  x*Delta12 = d0*(x*a+y*b)-b*(x*c+y*d0),
  y*Delta12 = a*(x*c+y*d0)-c*(x*a+y*b),

and similarly for Delta13 and Delta23.  Thus each Delta_ij visibly annihilates
J/G inside B; the residual-intersection theorem proves that they generate the
whole annihilator.

Theorem annihilator_of_saturation_torsion_has_at_most_three_generators:
  In B=V/G,

    Ann_B(T)
      = (G:J)/G
      = (G+I_2(Psi))/G.

  Hence Ann_B(T) is generated as a B-module by the images of

    Delta12, Delta13, Delta23,

  and therefore

    mu_B(Ann_B(T))<=3.

Proof:
  Since T=J/G, an element b+G in B annihilates T exactly when

    b*J subseteq G,

  namely when b belongs to G:J.  This identifies Ann_B(T) with (G:J)/G.
  Substitute the exact residual-colon formula.  The three minors generate
  I_2(Psi).
Qed.

Now restore the two final REGULAR_LOWER cuts h,k and put

  L:=(h,k)B,
  A:=B/L.

The exact saturation profile proves that every homogeneous element of degree at
least three annihilates T.  Since d>=13,

  L*T=0,

so

  L subseteq Ann_B(T).

The preceding regular-lower reduction also proves

  L intersect T=0.

Theorem torsion_annihilator_after_the_final_cuts_is_the_residual_colon_quotient:
  The natural map gives

    N_T:=Ann_A(T)
       ~= Ann_B(T)/L.

Proof:
  Because L*T=0, the ideal L is contained in Ann_B(T), so the displayed
  quotient maps naturally into A.

  Conversely let b+L annihilate T in A.  Then

    b*T subseteq L.

  Since T is an ideal of B, b*T is contained in T.  Therefore

    b*T subseteq L intersect T=0.

  Thus b annihilates T already in B, so b belongs to Ann_B(T).  This proves the
  equality.
Qed.

Corollary NT_has_at_most_three_generators:
  One has

    mu_A(N_T)<=3.

  Because T annihilates N_T, the A-action on N_T factors through

    A/T ~= A0,

  and therefore

    mu_A0(N_T)=mu_A(N_T)<=3.

Proof:
  N_T is a quotient of the three-generated B-module Ann_B(T), so its image is
  generated by at most the three residual minors.  Since T acts trivially on
  N_T by definition, passing from A to A0=A/T does not change the generated
  submodule or the minimal generator count.
Qed.

Corollary generator_socle_defect_is_at_most_three:
  One has

    mu_A0(N_T)-dim_C Soc_A0(N_T)<=3.

Proof:
  The socle dimension is nonnegative, while mu_A0(N_T)<=3.
Qed.

Theorem regular_lower_e2_fails_the_order13_tangent_gate:
  No homogeneous q=4, ht(Q)=3, e(B)=2 candidate in the REGULAR_LOWER subcase
  can satisfy the necessary order-13 tangent gate.

Proof:
  The preceding connecting reduction proves that every dangerous candidate
  would have to satisfy

    mu_A0(N_T)-dim_C Soc_A0(N_T)>=6.

  The residual-colon computation gives instead

    mu_A0(N_T)-dim_C Soc_A0(N_T)<=3.

  Contradiction.
Qed.

Corollary regular_lower_e2_subbranch_closed:
  The two-core-active REGULAR_LOWER multiplicity-two subbranch contributes no
  order-13 candidate passing the necessary tangent-dimension gate.
Qed.

IMPORTANT_NONCONCLUSION:
  This closes only the e=2 REGULAR_LOWER subcase.

  It does NOT close the remaining e=2 ZERODIVISOR_LOWER case.  In that case the
  lower homogeneous core cut is a zerodivisor, so the cyclic connecting
  presentation and its annihilator domains have a different normal form and
  must be recomputed rather than imported from REGULAR_LOWER.

  It also makes no claim for e=3,4,5, the q=4 height-two branch, homogeneous
  q<=3, or the unrestricted nonhomogeneous local deviation-two frontier.

  In particular, no full order-13 algebraicity theorem is claimed.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  The first remaining multiplicity-two height-three obstruction is

    ZERODIVISOR_LOWER,

  where

    d:=deg(f)<=D:=deg(g),
    d+D>=25,
    length(Cbar/(fbar,gbar))=d+D-1,

  and the saturated core is explicitly either the split two-line algebra or the
  double-line algebra.

NEXT_BOUNDED_OBJECT:
  Treat only e=2 ZERODIVISOR_LOWER.  Compute the cyclic colon K=(h:k), the
  transport map, and the finite carrier using the explicit normal forms

    (x^d,y^D)

  or

    (ell^(d-1)*v, ell^D).

  Use the same exact torsion profile T:(2,4,2), but do not import the regular
  lower annihilator formula without checking the changed principal
  annihilators.  Stop if the resulting connecting excess can reach six.