Standalone multiplicity-three exclusion for the homogeneous q=4, height-two
order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_saturated_curve_core_profile.v
    order13_q4_height2_cm_core_conic_closed.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S homogeneous,
    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    U := Qsat,
    C0 := S/U,
    dim C0=2,
    e(C0) in {1,2,3}.

This file performs one bounded task only: exclude

    e(C0)=3

without assuming depth(C0)=2.

No q<=3 branch and no Oblivion Closure promotion is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

ExternalResult codimension_two_complete_intersection_linkage:
  Let X be a complete intersection of two quadrics in P^3, and let Y be an
  unmixed degree-three curve contained in X.  The residual curve Z linked to Y
  by X has degree one.  Hence Z is a line.  Direct complete-intersection
  linkage preserves arithmetic Cohen--Macaulayness, so Y is arithmetically
  Cohen--Macaulay.  If Y is nondegenerate, its Hilbert series is

    (1+2*t)/(1-t)^2,

  equivalently

    dim_C (S/I_Y)_2=7,
    dim_C (I_Y)_2=3.

This is the standard (2,2)-link between a degree-three minimal curve and a
line; it is the same liaison calculation that gives the twisted-cubic
quadratic count.

--------------------------------------------------------------------------
1. REDUCE TO THE LINEAR-SATURATION RANK
--------------------------------------------------------------------------

Put

    u1:=dim_C U_1.

The saturated-core profile proves

    u1 in {0,1,2}.

Assume for contradiction throughout this file that

    e(C0)=3.

Theorem multiplicity_three_excludes_u1_two:
  One cannot have u1=2.

Proof:
  The preceding saturated-core profile proves that u1=2 forces

    C0 ~= C[s,t]

and hence e(C0)=1, contradicting e(C0)=3.
Qed.

Thus only u1=0 or u1=1 remain.

--------------------------------------------------------------------------
2. ONE LINEAR SATURATION EQUATION COLLAPSES Q TO HEIGHT ONE
--------------------------------------------------------------------------

Theorem multiplicity_three_excludes_u1_one:
  One cannot have u1=1.

Proof:
  Choose a nonzero l in U_1.  Modulo l, the one-dimensional top projective part
  of Proj(C0) has degree three in P^2.

  A nonzero quadratic equation modulo l would contain that top-dimensional
  plane curve in a conic and would force its degree to be at most two.
  Therefore there is no quadratic equation modulo l, so

    U_2=l*S_1.

  This space has dimension four.  Since Q_2 is four-dimensional and

    Q_2 subset U_2,

  one has

    Q_2=l*S_1.

  Because Q is generated by its four quadratic generators,

    Q=l*m.

  Hence ht(Q)<=1, contradicting the standing hypothesis ht(Q)=2.
Qed.

Therefore a multiplicity-three survivor would have to satisfy

    U_1=0.

--------------------------------------------------------------------------
3. THE NONDEGENERATE TOP CURVE HAS AT MOST THREE QUADRICS
--------------------------------------------------------------------------

Let Uunm be the unmixed height-two part of U, obtained by removing all
projective embedded components of dimension zero.  Then

    U subset Uunm,
    e(S/Uunm)=3.

Choose two constant linear combinations q1,q2 of the four quadrics forming a
regular sequence, as in the saturated-core profile.  Since

    (q1,q2) subset Q subset U subset Uunm,

  the unmixed degree-three curve Y:=Proj(S/Uunm) lies on the complete
  intersection X:=V(q1,q2) of degree four.

Theorem the_unmixed_degree_three_core_has_at_most_three_quadrics:
  Under U_1=0,

    dim_C (Uunm)_2<=3.

Proof:
  First suppose (Uunm)_1=0.  Then Y is nondegenerate.  Apply the external
  (2,2)-linkage result: the residual degree-one curve is a line, Y is ACM, and

    dim_C (Uunm)_2=3.

  Now suppose (Uunm)_1 is nonzero.  Its top-dimensional degree-three curve is
  planar.  Choose l in (Uunm)_1.  As in the u1=1 argument, no quadratic
  equation survives modulo l without lowering the top degree below three.
  Thus

    (Uunm)_2=l*S_1,

  a four-dimensional space.

  Since U_2 subset (Uunm)_2, if dim U_2 were four then U_2=l*S_1.  Hence U
  would contain l*m.  Because U is saturated and

    saturation(l*m)=(l),

  it would follow that l belongs to U_1, contradicting U_1=0.

  Therefore in the planar-unmixed case

    dim_C U_2<=3.

  Since U_2 subset (Uunm)_2, the only quantity needed below is in either case

    dim_C U_2<=3.
Qed.

Corollary four_independent_quadrics_exclude_the_u1_zero_case:
  The case U_1=0 and e(C0)=3 is impossible.

Proof:
  The standing four independent quadratic generators give

    dim_C Q_2=4.

  Since Q subset U,

    Q_2 subset U_2.

  But the preceding theorem gives

    dim_C U_2<=3.

  Contradiction.
Qed.

--------------------------------------------------------------------------
4. MULTIPLICITY THREE IS EMPTY
--------------------------------------------------------------------------

Theorem q4_height2_multiplicity_three_is_impossible:
  Under the standing homogeneous q=4, height-two hypotheses,

    e(S/Qsat) != 3.

Proof:
  The saturated-core profile gives u1 in {0,1,2}.

  u1=2 is excluded by multiplicity one.
  u1=1 forces Q=l*m and contradicts ht(Q)=2.
  u1=0 contradicts the quadratic bound for the degree-three unmixed core.

  Hence no multiplicity-three saturated core exists.
Qed.

Corollary exact_height_two_multiplicity_inventory:
  Every surviving q=4 height-two saturated core has multiplicity

    e(S/Qsat) in {1,2}.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does not by itself close the multiplicity-one or multiplicity-two
  tangent branches; it only removes the previously unhandled e=3 sibling.

  It does not enter q<=3 and does not promote Oblivion Closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_three_is_impossible.
  not q4_height2_full_closure in this file alone.
  not homogeneous_q_le_3_closure.
  not OC.

NEXT_ACTIONS:
  1. Re-read the exact terminal workflow for this commit.
  2. If green, combine e=1, e=2, and e=3 child results into the q=4
     height-two parent closure.
