Standalone minimal-deficiency profile for the homogeneous q=4, height-two
DEPTH-ONE saturated-core branch in the order-13 deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_saturated_curve_core_profile.v
    order13_variant_truth_lattice.v

  and retain

    S := C[x1,x2,x3,x4],
    Q subset S homogeneous,
    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    C := S/Qsat,
    dim C=2,
    depth_m(C)=1.

The preceding profile proves

    H^0_m(C)=0,
    e(C) in {1,2,3}.

This file answers only the first bounded depth-one question:

  how small can H^1_m(C) actually be under the four-quadric height-two
  hypotheses?

It proves that the sharp answer is one copy of C in degree zero.  In
particular the four-quadric hypotheses do NOT force a larger deficiency
module and do NOT force nonzero saturation torsion Qsat/Q.

No tangent-gate exclusion is claimed in this file.
The truth state of the depth-one parent therefore remains UNKNOWN.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE MINIMAL FOUR-QUADRIC MODEL
--------------------------------------------------------------------------

Put

  P1 := (x1,x2),
  P2 := (x3,x4),

and define

  Q0 := P1 intersect P2.

Because the variable sets are disjoint,

  Q0 = P1*P2
     = (x1*x3, x1*x4, x2*x3, x2*x4).

Theorem skew_line_core_has_exact_four_quadric_presentation:
  Q0 is minimally generated by exactly four linearly independent quadrics and

    ht(Q0)=2.

Proof:
  The displayed four monomials are distinct degree-two monomials, hence are
  linearly independent.

  Since Q0 has no degree-one elements, none of those quadrics can be generated
  from lower degree.  Since its degree-two part is exactly their span, all four
  are minimal generators.

  The minimal primes P1 and P2 both have height two, so

    ht(Q0)=2.
Qed.

Theorem skew_line_core_is_already_saturated:
  One has

    Q0sat=Q0.

Proof:
  Each Pi is generated by linear forms and is saturated with respect to

    m=(x1,x2,x3,x4).

  Suppose m^r*f is contained in Q0=P1 intersect P2 for some r.  Then m^r*f is
  contained in each Pi.  Saturation of Pi gives f in Pi for i=1,2.  Therefore

    f in P1 intersect P2=Q0.

  Hence Q0 is saturated.
Qed.

Corollary minimal_model_has_zero_saturation_torsion:
  For

    B0:=S/Q0,
    T0:=Q0sat/Q0,

  one has

    T0=0.
Qed.

--------------------------------------------------------------------------
2. EXACT DEPTH AND DEFICIENCY
--------------------------------------------------------------------------

There is a standard exact sequence

  0 -> B0
    -> S/P1 direct_sum S/P2
    -> S/(P1+P2)
    -> 0,

where the second map is the difference of the two quotient maps.

Since

  P1+P2=m,

its right-hand term is C concentrated in degree zero.

Theorem skew_line_core_has_depth_exactly_one:
  One has

    depth_m(B0)=1.

Proof:
  The rings

    S/P1 ~= C[x3,x4],
    S/P2 ~= C[x1,x2]

  both have depth two at the homogeneous maximal ideal, while

    S/m ~= C

  has depth zero.

  The displayed exact sequence therefore gives depth(B0)=1 by the depth
  lemma.
Qed.

Theorem skew_line_core_has_minimal_deficiency_module:
  As a graded B0-module,

    H^1_m(B0) ~= C

  concentrated in degree zero.

Proof:
  Apply local cohomology with support in m to

    0 -> B0
      -> S/P1 direct_sum S/P2
      -> C
      -> 0.

  Because Q0 is saturated,

    H^0_m(B0)=0.

  The two polynomial rings S/Pi have depth two, hence

    H^0_m(S/Pi)=0,
    H^1_m(S/Pi)=0.

  The finite-length module C has

    H^0_m(C)=C.

  The beginning of the long exact sequence is therefore

    0 -> C -> H^1_m(B0) -> 0.

  Thus H^1_m(B0) is exactly one copy of C, and the grading is degree zero
  because the right-hand C is S/m in degree zero.
Qed.

Corollary one_dimensional_depth_one_deficiency_is_sharp:
  In the standing depth-one branch one always has

    H^1_m(C) != 0

  by the definition of depth one together with H^0_m(C)=0.

  The model B0 above realizes the smallest possible nonzero vector-space
  dimension:

    dim_C H^1_m(B0)=1.

  Therefore no universal consequence of the standing four-quadric,
  height-two, saturation hypotheses can strengthen nonvanishing to

    dim_C H^1_m(C) >= 2.
Qed.

--------------------------------------------------------------------------
3. HILBERT DATA OF THE MINIMAL MODEL
--------------------------------------------------------------------------

Theorem skew_line_core_has_exact_Hilbert_series:
  One has

    Hilb_B0(t)
      = 2/(1-t)^2 - 1
      = (1+2*t-t^2)/(1-t)^2.

  Equivalently,

    dim_C (B0)_0 = 1,
    dim_C (B0)_n = 2*(n+1) for every n>=1.

  In particular

    dim_C (B0)_1=4,
    dim_C (B0)_2=6,
    e(B0)=2.

Proof:
  Take Hilbert series in

    0 -> B0
      -> S/P1 direct_sum S/P2
      -> C
      -> 0.

  Each S/Pi is a polynomial ring in two variables and has Hilbert series
  1/(1-t)^2, while C has Hilbert series one.  This gives the displayed
  formula.

  The coefficient statement follows immediately.  The eventual linear
  Hilbert polynomial is

    2*n+2,

  so the multiplicity is two.
Qed.

Corollary minimal_depth_one_model_matches_the_forced_initial_q4_data:
  The minimal model has exactly

    dim (B0)_0=1,
    dim (B0)_1=4,
    dim (B0)_2=6,

  which is the same initial unsaturated Hilbert data forced for every q=4,
  height-two four-quadric core before saturation.

  Thus this model is not excluded by the degree-zero, degree-one, or
  degree-two dimension bookkeeping used in the preceding saturated-core
  profile.
Qed.

--------------------------------------------------------------------------
4. PROJECTIVE INTERPRETATION
--------------------------------------------------------------------------

Corollary minimal_deficiency_model_is_two_skew_lines:
  Proj(B0) is the disjoint union of the two coordinate lines

    L1:=V(P1),
    L2:=V(P2)

  in P^3.

  They are disjoint because a projective point lying on both would satisfy

    x1=x2=x3=x4=0.

  Therefore the degree-two depth-one core already occurs as a reduced,
  saturated projective curve; no embedded nilpotent structure is required to
  create the deficiency.
Qed.

Theorem degree_zero_deficiency_measures_the_missing_second_constant:
  The exact sequence in degree zero is

    0 -> (B0)_0
      -> (S/P1)_0 direct_sum (S/P2)_0
      -> C
      -> 0,

  i.e.

    0 -> C -> C direct_sum C -> C -> 0.

  The one-dimensional deficiency H^1_m(B0)_0 is exactly the discrepancy
  between one global degree-zero scalar in the homogeneous coordinate ring and
  the two independent constants on the two disconnected projective lines.
Qed.

--------------------------------------------------------------------------
5. CONSEQUENCE FOR THE ORDER-13 SEARCH
--------------------------------------------------------------------------

Theorem four_quadrics_do_not_force_a_torsion_carrier_in_depth_one:
  The standing q=4, ht(Q)=2, depth-one hypotheses admit a model with

    Qsat=Q,
    T=Qsat/Q=0,
    H^1_m(S/Q)=C in degree zero.

  Therefore the tangent strategy that closed the Cohen--Macaulay line core by
  first proving a short saturation-torsion tail cannot be imported as a
  universal depth-one argument.
Qed.

Corollary first_depth_one_object_is_the_minimal_deficiency_endpoint:
  The smallest deficiency compatible with the four-quadratic height-two
  hypotheses is already realized by

    Q0=(x1*x3,x1*x4,x2*x3,x2*x4).

  Any universal depth-one tangent closure must therefore handle this endpoint
  even when the saturation defect T vanishes identically.
Qed.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove that the skew-line endpoint satisfies the order-13
  tangent gate.

  It also does NOT prove that every depth-one saturated core is a union of two
  skew lines, or that every deficiency module is concentrated in degree zero.

  The current truth-lattice state remains

    q4_height2_depth_one_core : UNKNOWN.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_tangent_closed.
  q4_height2_depth_one_minimal_deficiency_isolated.
  not q4_height2_depth_one_core_closed.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Compute the two-cut conormal/tangent contribution for the exact minimal
  depth-one core

    B0=S/(x1*x3,x1*x4,x2*x3,x2*x4)

  under a homogeneous m-primary parameter pair f,g of degrees at least three.

  Determine whether this sharp one-dimensional-deficiency endpoint can satisfy
  the necessary order-13 tangent gate

    dim_C Hom_S((Q0,f,g),A) <= length_C(A)-20.

NEXT_ACTIONS:
  1. Stay on the exact skew-line fiber-product core B0.
  2. Write the final parameter pair on the two polynomial-ring components.
  3. Compute H_1(f,g;B0) from the fiber-product exact sequence.
  4. Extract the largest forced subspace of Hom_S((Q0,f,g),A).
  5. Do not enter any larger deficiency profile or q<=3 branch.
