Standalone no-go / reduction for producing the primitive degree-six F_13
correspondence from the RM period/Shimura curve and its Hecke correspondences.

This file is pseudo-formal mathematical documentation. It does not assert the
Hodge conjecture, the invariant-cycle conjecture, or algebraicity of the generic
primitive F_13 generator.

Setup:
  Let X be a very general member of the one-dimensional F_13-RM family already
  constructed on this branch, with

    F_13 = Q(zeta_13 + zeta_13^(-1)),
    alpha = zeta_13 + zeta_13^(-1),
    End_Hdg(T(X)_Q) = F_13,
    dim_F13 T(X)_Q = 3.

  The polarization is represented by an F_13-valued symmetric form b on the
  three-dimensional F_13-space W = T(X)_Q, followed by a trace form over Q.
  The RM period domain is the one-dimensional orthogonal domain attached to W.

ExternalResult RMOrthogonalGroup:
  For a very general K3-type Hodge structure with totally real multiplication F,
  the generic Hodge group is the restriction of scalars of the F-orthogonal group
  of the underlying F-quadratic space. In particular, the orthogonal monodromy /
  Shimura group acts F-linearly and preserves the F-valued quadratic form b.

ExternalResult OrthogonalHeckeCorrespondence:
  Hecke correspondences on an orthogonal / GSpin Shimura variety are generated by
  the corresponding orthogonal or spin group. Their action on the standard
  quadratic local system is therefore by orthogonal transport; they do not turn
  an element of the commutant End_F(W) into a new scalar action on W.

Lemma primitive_F13_scalar_is_not_in_orthogonal_group:
  Let a in F_13 act on W by scalar multiplication. If this scalar action belongs
  to O_F13(W,b), then for every x,y in W,

    b(a*x, a*y) = b(x,y).

  Since b is F_13-bilinear,

    a^2 * b(x,y) = b(x,y).

  Nondegeneracy gives

    a^2 = 1,

  hence a = +/-1.

  Since alpha has degree six over Q, alpha != +/-1. Therefore multiplication by
  alpha is not an element of the orthogonal group generating Hecke transport.
Qed.

Lemma alpha_is_commutant_not_Hecke_direction:
  The F_13-action on W commutes with the F_13-orthogonal Hodge group. Thus alpha
  is a Hodge endomorphism lying in the commutant of the generic Hodge/monodromy
  group, not a group element producing orthogonal Hecke transport.

  Therefore the fact that the RM locus is an arithmetic orthogonal curve does not
  itself produce a fiberwise algebraic cycle on X x X inducing alpha.
Qed.

Lemma closed_Hecke_loop_reduces_to_isometry_route:
  Any Hecke path that starts at a very general marked RM fiber and returns to the
  same rational Hodge structure acts on T(X)_Q by a Hodge isometry.

  On a very general F_13-RM fiber, a scalar Hodge isometry in F_13 satisfies
  a^2 = 1, hence is +/-1. Thus a closed Hecke loop cannot equal the primitive
  degree-six scalar alpha.

  This is consistent with, and structurally contained in, the previously closed
  Fourier-Mukai / isometry route.
Qed.

ExternalResult SpecialCyclesDoNotSupplyGenericRMOperator:
  Orthogonal-Shimura special cycles parameterize loci with additional special
  endomorphisms / special vectors, and in the K3 realization these detect
  Noether-Lefschetz-type Picard jumps and related arithmetic cycles on the base.
  They do not by themselves construct a codimension-two cycle on the square of
  every generic K3 fiber realizing a pre-existing non-isometric scalar in the
  commutant.

Theorem shimura_hecke_route_does_not_algebraize_alpha:
  The arithmetic geometry of the one-dimensional RM period locus supplies:

    - the algebraic moduli/period curve,
    - orthogonal/GSpin Hecke correspondences on that curve,
    - special cycles detecting additional algebraic classes at special loci,
    - the Kuga-Satake abelian scheme after passing to the GSpin realization.

  None of these facts alone produces an algebraic cycle

    Z_alpha in CH^2(X x X)_Q

  whose action on T(X)_Q is multiplication by alpha.

  The primitive scalar alpha lies in the commutant of the orthogonal group, while
  Hecke transport comes from the group itself. Recovering alpha as a cycle on the
  K3 square therefore still requires a separate algebraicity input.
Qed.

KugaSatakeReduction:
  Passing from the orthogonal Shimura curve to the Kuga-Satake abelian scheme does
  not close the gap unconditionally. The relevant Kuga-Satake Hodge embedding is
  an absolute-Hodge / motivated correspondence, but for general K3 surfaces its
  algebraicity remains a conjecture.

  If an algebraic Kuga-Satake correspondence were available for the present
  rank-18 transcendental lattice, one could try to transport suitable algebraic
  tensors on the abelian side back to X. Without that algebraic transfer, the
  Shimura/Kuga-Satake realization does not imply algebraicity of alpha on X x X.

  Recent unconditional Kuga-Satake algebraicity results cover special low-rank or
  special geometric K3 families; they do not cover this very general Picard-rank-4,
  transcendental-rank-18 degree-six F_13-RM family.

Important limitation:
  This theorem does NOT rule out a genuinely new non-similarity codimension-two
  correspondence on X x X. It only closes the idea that such a correspondence is
  automatically supplied by the orthogonal Shimura curve, its Hecke operators,
  its standard special cycles, or the presently known unconditional Kuga-Satake
  algebraicity theorems.

Boundary:
  Fourier-Mukai/isometry routes are closed
  finite-degree rational-isogeny similarity routes are closed
  orthogonal Shimura/Hecke transport route is closed
  standard special-cycle-on-the-base route is insufficient
  generic Kuga-Satake transfer remains conditional in this rank-18 setting
  arbitrary non-similarity codimension-two correspondence remains open
  family-specific invariant-cycle algebraicity remains the weakest missing bridge

First missing object:
  an algebraic codimension-two correspondence on a very general F_13-RM fiber
  inducing alpha, obtained by a mechanism not restricted to orthogonal similarity
  transport and not relying on an unproved general Kuga-Satake / Hodge-conjecture
  algebraicity step.