Standalone exclusion of the H11 residual-tail state in the homogeneous q=4,
height-two multiplicity-one, depth-one order-13 deviation-two program.

SCOPE:
  Continue only from the four-state multiplicity-one Hilbert frontier and the
  completed H00/H10 closures.

  Let

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by exactly four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Ccore := S/Qsat,

  and retain

    dim Ccore=2,
    depth_m(Ccore)=1,
    e(Ccore)=1.

Treat only the H11 state

    (u1,u2)=(1,3).

Thus

    dim_C (Qsat)_1 = 1,
    dim_C (Qsat)_2 = 5,
    dim_C Q_2 = 4.

The earlier Hilbert-floor reduction described H11 through a residual Artinian
numerator beginning t+t^2.  This file proves that no actual four-independent-
quadric H11 ideal exists, before any higher residual tail is needed.

No H01 or q<=3 branch is entered.
No tangent-space estimate is made.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE UNIQUE SATURATED LINEAR FORM
--------------------------------------------------------------------------

Choose a nonzero linear form

    l in (Qsat)_1.

Then

    l*S_1 subset (Qsat)_2

is four-dimensional.

Put

    L2 := l*S_1,
    V  := (Qsat)_2,
    W  := Q_2.

Thus

    dim L2 = 4,
    dim V  = 5,
    dim W  = 4,
    W subset V.

Theorem H11_quadratic_fourplane_is_not_all_l_m:
  One has

    W != L2.

Proof:
  If W=L2=l*S_1, then because Q is generated by its degree-two part,

    Q=l*m.

  Hence Q is contained in the height-one prime (l), so

    ht(Q)<=1,

  contradicting the standing ht(Q)=2 hypothesis.
Qed.

Corollary H11_fourplane_meets_lS1_in_dimension_three:
  One has

    dim_C(W intersect L2)=3.

Proof:
  Two distinct hyperplanes W and L2 inside the five-dimensional vector space V
  meet in dimension three.
Qed.

--------------------------------------------------------------------------
2. EVERY H11 FOUR-QUADRIC IDEAL HAS THE FORM (lU,q)
--------------------------------------------------------------------------

Multiplication by l identifies S_1 with L2.  Therefore there is a unique
three-dimensional linear subspace

    U subset S_1

such that

    W intersect L2 = l*U.

Choose

    q in W \ L2.

Theorem H11_exact_quadratic_presentation:
  One has

    W = l*U + C*q

and therefore

    Q=(l*U,q).

Moreover q is not divisible by l.

Proof:
  The intersection lU has dimension three and q supplies one independent fourth
  direction in W.  Since Q is generated by W, the ideal equality follows.

  Finally q notin l*S_1 by construction, so l does not divide q.
Qed.

Corollary H11_Q_is_contained_in_a_linear_quadric_complete_intersection:
  One has

    Q subset (l,q).
Qed.

--------------------------------------------------------------------------
3. SATURATION FORCES THE COMPLETE INTERSECTION
--------------------------------------------------------------------------

The ideal

    (l,q)

is saturated.

Indeed, l is linear and q is not divisible by l, so l,q form a homogeneous
regular sequence in the polynomial ring S.  Hence S/(l,q) is a two-dimensional
complete intersection and is Cohen--Macaulay of depth two.  In particular it
has no homogeneous maximal-ideal torsion, which is equivalent to saturation of
(l,q).

Theorem H11_saturation_is_exactly_l_q:
  One has

    Qsat=(l,q).

Proof:
  Since

    Q subset (l,q)

and (l,q) is saturated, minimality of saturation gives

    Qsat subset (l,q).

  Conversely, l belongs to Qsat by the H11 assumption u1=1, while q belongs to
  Q and hence to Qsat.  Therefore

    (l,q) subset Qsat.

  The two containments give equality.
Qed.

This conclusion uses only the exact dimensions

    dim (Qsat)_1=1,
    dim (Qsat)_2=5,
    dim Q_2=4,

plus ht(Q)=2.  No residual-tail classification is needed.

--------------------------------------------------------------------------
4. THE FORCED SATURATION HAS MULTIPLICITY TWO
--------------------------------------------------------------------------

Theorem H11_forced_complete_intersection_has_multiplicity_two:
  One has

    e(S/(l,q))=2.

Proof:
  The pair l,q is a complete intersection of degrees one and two.  Its
  multiplicity is the product of those degrees:

    1*2=2.
Qed.

Corollary H11_contradicts_the_multiplicity_one_branch:
  The H11 state cannot occur.

Proof:
  The standing multiplicity-one hypothesis says

    e(Ccore)=e(S/Qsat)=1.

  But the previous two theorems give

    Qsat=(l,q)

and

    e(S/Qsat)=2.

  Contradiction.
Qed.

--------------------------------------------------------------------------
5. EXACT H11 EXCLUSION
--------------------------------------------------------------------------

Theorem q4_height2_multiplicity_one_depth_one_H11_is_empty:
  There is no homogeneous ideal Q in S satisfying simultaneously

    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    e(S/Qsat)=1,
    depth_m(S/Qsat)=1,
    (u1,u2)=(1,3).

Proof:
  Sections 1--3 force

    Qsat=(l,q)

with deg(l)=1 and deg(q)=2.  Section 4 then forces multiplicity two, contradicting
multiplicity one.
Qed.

Corollary H11_residual_tail_is_vacuous:
  The previously open H11 Artinian-reduction tail

    t+t^2+...

has no realizable four-quadric instance.  There is therefore no need to classify
its higher coefficients for the q=4 height-two multiplicity-one branch.
Qed.

--------------------------------------------------------------------------
6. UPDATED MULTIPLICITY-ONE FRONTIER
--------------------------------------------------------------------------

The four initial states were

    H00: (u1,u2)=(0,3),
    H01: (u1,u2)=(0,2),
    H10: (u1,u2)=(1,4),
    H11: (u1,u2)=(1,3).

The current status is now

    H00: tangent-closed,
    H10: tangent-closed,
    H11: empty,
    H01: open.

Thus H01 is the only remaining multiplicity-one depth-one Hilbert state.

IMPORTANT_NONCONCLUSION:
  This file does NOT analyze H01.
  It does NOT close the full multiplicity-one depth-one branch yet because H01
  remains open.
  It does NOT close q=4 height two.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H00_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H10_tangent_closed.
  q4_height2_multiplicity_one_depth_one_H11_empty.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

NEXT_ACTIONS:
  1. Leave H00, H10, and H11.
  2. Stay in q=4 height-two multiplicity one.
  3. Enter only H01: (u1,u2)=(0,2).
  4. Use that D is generated by two degree-one classes with Artinian reduction
     beginning 2*t+t^2.
  5. Stop at the first exact residual-module or saturation obstruction; do not
     enter q<=3.
