Standalone residual-multiplicity-five exclusion and regular-cut classification
for the low-embedding-dimension H01-C5 m=3 colon types E0/E1 in the
homogeneous q=4, height-two multiplicity-one, depth-one order-13
deviation-two program.

SCOPE:
  Continue only from

    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_E01_residual_generator_bound.v
    order13_q4_height2_depth_one_multiplicity_one_H01_C5_m3_E01_residual_cut_high_degree_closure.v

  and retain

    S = C[x1,x2,x3,x4],
    Q subset Qsat,
    D = P/Qsat,
    J_res = Ann_S(D) = (Qsat:P),
    R_res = S/J_res,

  in H01-C5 with

    m = 3,
    sigma = 5,

  and only in the E0/E1 torsion-colon states.

The preceding files establish:

  * R_res is one-dimensional Cohen--Macaulay;
  * a general linear form h is R_res-regular and D-regular;
  * E := D/hD has the exact normal form

        E ~= C(-1) direct_sum C[u]/(u^3)(-1);

  * after coordinates in

        Sbar := S/(h) ~= C[u,v,w],

    one has

        Ann_Sbar(E) = (v,w,u^3);

  * with

        Jbar := (J_res+(h))/(h),

    one has only the inclusion

        Jbar subset Ann_Sbar(E),

    not equality in general;

  * the generic residual algebra

        A_gen := R_res tensor_(C[h]) C(h)

    acts faithfully on the four-dimensional generic fiber

        D_gen := D tensor_(C[h]) C(h),

    hence the Schur--Jacobson bound gives

        e(R_res) = dim A_gen <= 5;

  * for final homogeneous equations f,g of degrees d,e >= 3, writing

        M = max(d,e),
        s = min(d,e),
        N = length_C S/(Q,f,g),

    the preceding high-degree file gives

        N >= M*s + 4*s - 3;

  * and the E0/E1 two-copy tangent carrier gives

        t(A) >= 2*N - 2*L_res - 8*r_res,

    where

        L_res = length_C S/(J_res,f,g),
        r_res = mu_A((J_res)_A).

This file performs one bounded structural task:

  exclude the extremal residual multiplicity five by combining the equality
  case of Schur--Jacobson with the fact that A_gen is generated by only three
  elements as a C(h)-algebra.

The resulting regular Artinian cut has length three or four only.  The inclusion

    Jbar subset (v,w,u^3)

then classifies the three possible cut ideals and sharpens the residual generator
bound state-by-state.

No E2, H01-C4, q<=3, or full order-13 branch is entered.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. THE GENERIC RESIDUAL ALGEBRA HAS AT MOST THREE ALGEBRA GENERATORS
--------------------------------------------------------------------------

Put

    K := C(h).

Choose linear coordinates h,z1,z2,z3 on S_1.  After extension from C[h] to K,

    S tensor_(C[h]) K ~= K[z1,z2,z3].

Therefore

    A_gen
      = (S/J_res) tensor_(C[h]) K

is a quotient of K[z1,z2,z3].

Theorem H01_C5_m3_E01_generic_residual_algebra_three_generated:
  A_gen is generated as a unital K-algebra by at most three elements.
Qed.

The preceding residual-generator file also gives a faithful embedding

    A_gen -> End_K(D_gen) ~= M_4(K)

and

    dim_K A_gen = e(R_res).

--------------------------------------------------------------------------
2. THE SCHUR--JACOBSON EQUALITY CASE CANNOT OCCUR
--------------------------------------------------------------------------

Assume for contradiction

    e(R_res)=5.

Then

    dim_K A_gen=5,

so A_gen attains the Schur--Jacobson maximum for a commutative subalgebra of
M_4(K).

Let Kbar be an algebraic closure of K.  Scalar extension preserves dimension,
commutativity, injectivity of the faithful matrix action, and the property of
being generated by at most three elements.  Thus

    Abar := A_gen tensor_K Kbar

is a five-dimensional commutative Kbar-subalgebra of M_4(Kbar), generated by at
most three elements.

Use the equality classification in Schur--Jacobson for n=4.  A commutative
subalgebra of M_4 over an algebraically closed field having the maximum dimension
five is conjugate to

    Kbar*I direct_sum N,

where, after a decomposition Kbar^4=U direct_sum W with dim U=dim W=2,

    N = Hom_Kbar(U,W)

is represented by one off-diagonal 2-by-2 block.  Consequently

    dim_Kbar N=4,
    N^2=0.

Lemma square_zero_fourspace_needs_four_algebra_generators:
  Let k be a field and let

    A = k*1 direct_sum N

  with dim_k N=4 and N^2=0.  Then A cannot be generated as a unital k-algebra by
  three elements.

Proof:
  If a1,a2,a3 generate A, write

    ai=lambda_i*1+ni,
    ni in N.

  Since N^2=0, every polynomial in the ai lies in

    k*1 + span_k(n1,n2,n3).

  Hence the generated algebra has dimension at most four, contradicting

    dim_k A=5.
Qed.

Apply the lemma to Abar.  It contradicts Section 1.

Theorem H01_C5_m3_E01_residual_multiplicity_five_excluded:
  One has

    e(R_res) <= 4.
Qed.

IMPORTANT:
  Only the equality case e(R_res)=5 is excluded here.  No classification of all
  four-dimensional commutative subalgebras of M_4 is asserted.

--------------------------------------------------------------------------
3. THE REGULAR ARTINIAN CUT HAS LENGTH THREE OR FOUR
--------------------------------------------------------------------------

Because h is R_res-regular,

    length_C(Sbar/Jbar) = e(R_res) <= 4.

On the other hand the established action on E gives

    Jbar subset Ann_Sbar(E)=(v,w,u^3).

Therefore there is a natural surjection

    Sbar/Jbar -> Sbar/(v,w,u^3) ~= C[u]/(u^3).

The target has length three, so

    length_C(Sbar/Jbar) >= 3.

Hence:

Theorem H01_C5_m3_E01_residual_regular_cut_length:
  Exactly one of

    e(R_res)=3

  or

    e(R_res)=4

  occurs.
Qed.

In particular residual multiplicities one, two, and five are impossible in this
E0/E1 m=3 setting.

--------------------------------------------------------------------------
4. LENGTH THREE: THE CUT IDEAL IS EXACTLY THE ARTINIAN ANNIHILATOR
--------------------------------------------------------------------------

Assume

    e(R_res)=3.

Both quotients

    Sbar/Jbar

and

    Sbar/(v,w,u^3)

have length three, and the first surjects onto the second.  Therefore the
surjection is an isomorphism and

    Jbar=(v,w,u^3).

Thus

    mu_Sbar(Jbar)=3.

The preceding regular-cut generator theorem gives

    mu_S(J_res)=mu_Sbar(Jbar)=3,

and hence

    r_res<=3.

Theorem H01_C5_m3_E01_residual_type_R3:
  If e(R_res)=3, then after coordinates

    Jbar=(v,w,u^3)

  and

    r_res<=3.
Qed.

--------------------------------------------------------------------------
5. LENGTH FOUR: THE KERNEL OF THE SURJECTION HAS LENGTH ONE
--------------------------------------------------------------------------

Assume

    e(R_res)=4.

Put

    K0 := (v,w,u^3).

Then

    Jbar subset K0

and

    length_C(K0/Jbar)=1.

Because K0/Jbar is a graded length-one Sbar-module, the homogeneous maximal ideal

    mbar=(u,v,w)

annihilates it.  Therefore

    mbar*K0 subset Jbar subset K0,

and Jbar is obtained by killing a homogeneous codimension-one subspace of the
minimal-generator space

    K0/(mbar*K0).

That generator space has graded basis

    v,w                 in degree 1,
    u^3                 in degree 3.

Homogeneity leaves exactly two types.

--------------------------------------------------------------------------
5A. TYPE R4U: THE LOST GENERATOR IS u^3
--------------------------------------------------------------------------

If K0/Jbar is represented by the cubic generator u^3, then Jbar contains both
linear generators v,w and contains mbar*K0.  Hence

    Jbar=(v,w,u^4).

Thus

    Sbar/Jbar ~= C[u]/(u^4)

and

    mu(Jbar)=3.

Theorem H01_C5_m3_E01_residual_type_R4U:
  In the cubic-kernel length-four type,

    Jbar=(v,w,u^4),
    r_res<=3.
Qed.

--------------------------------------------------------------------------
5B. TYPE R4S: THE LOST GENERATOR IS LINEAR
--------------------------------------------------------------------------

If K0/Jbar is represented in degree one, its degree-one quotient is a line in
span(v,w).  After a linear change among v,w, take that line to be represented by
v.  Then Jbar contains

    w,
    u^3,
    mbar*v.

Modulo the generators already listed,

    mbar*v=(u*v,v^2,v*w)

reduces to u*v and v^2 because v*w is in (w).  Therefore

    Jbar=(w,u^3,u*v,v^2).

The quotient has basis

    1,u,u^2,v

and length four, as required.  Moreover

    mu(Jbar)=4.

Theorem H01_C5_m3_E01_residual_type_R4S:
  In the linear-socle length-four type, after coordinates

    Jbar=(w,u^3,u*v,v^2),
    r_res<=4.
Qed.

Thus the previous uniform bound r_res<=6 sharpens to

    r_res<=4

throughout E0/E1, with r_res<=3 in types R3 and R4U.

Corollary H01_C5_m3_E01_residual_generator_bound_four:
  One has

    r_res<=4.
Qed.

--------------------------------------------------------------------------
6. STATEWISE RESIDUAL CUT BOUNDS
--------------------------------------------------------------------------

The preceding high-degree file constructs a homogeneous R_res-regular element F
of degree M inside (f,g).  Therefore

    L_res <= length R_res/(F) = M*e(R_res).

Hence:

  TYPE R3:

    L_res<=3*M,
    r_res<=3.

  TYPE R4U:

    L_res<=4*M,
    r_res<=3.

  TYPE R4S:

    L_res<=4*M,
    r_res<=4.

In particular the previous uniform estimate L_res<=5*M improves to

    L_res<=4*M.

--------------------------------------------------------------------------
7. REINSERT THE SHARPENED TYPES INTO THE TANGENT CARRIER
--------------------------------------------------------------------------

Retain

    N >= M*s + 4*s - 3

and

    t(A) >= 2*N - 2*L_res - 8*r_res.

The necessary order-13 tangent gate is

    t(A)<=N-20.

We compute the tangent excess state-by-state.

TYPE R3:
  Using L_res<=3*M and r_res<=3,

    t(A) - (N-20)
      >= N - 6*M - 4
      >= M*(s-6) + 4*s - 7.

TYPE R4U:
  Using L_res<=4*M and r_res<=3,

    t(A) - (N-20)
      >= N - 8*M - 4
      >= M*(s-8) + 4*s - 7.

TYPE R4S:
  Using L_res<=4*M and r_res<=4,

    t(A) - (N-20)
      >= N - 8*M - 12
      >= M*(s-8) + 4*s - 15.

Each state is excluded whenever its displayed lower bound is strictly positive.

--------------------------------------------------------------------------
8. UNIFORM NEW CLOSURE RANGE
--------------------------------------------------------------------------

For every residual type, if

    s=min(d,e)>=8,

then the worst state is R4S and

    M*(s-8)+4*s-15
      >= 4*8-15
      =17>0.

Hence every E0/E1 state with minimum final degree at least eight is excluded.

There is one additional uniform strip at s=7.  In the worst R4S type,

    M*(7-8)+28-15
      =13-M.

Therefore this remains strictly positive for

    7<=M<=12.

Theorem q4_H01_C5_m3_E01_sharpened_tangent_closure:
  Every H01-C5 m=3 E0/E1 state is excluded if either

    min(d,e)>=8,

  or

    min(d,e)=7 and max(d,e)<=12.
Qed.

This strictly improves the previous uniform threshold min(d,e)>=10.

--------------------------------------------------------------------------
9. STRONGER STATEWISE CLOSURES
--------------------------------------------------------------------------

The exact residual types give additional exclusions that are not uniform across
all three types.

TYPE R3:

    excess >= M*(s-6)+4*s-7.

  Hence R3 is excluded for

    s>=6,

  and also for

    s=5 with M<=12,

  and for the pair

    (s,M)=(4,4).

TYPE R4U:

    excess >= M*(s-8)+4*s-7.

  Hence R4U is excluded for

    s>=8,

  for

    s=7 with M<=20,

  and for

    s=6 with M<=8.

TYPE R4S:

    excess >= M*(s-8)+4*s-15.

  Hence R4S is excluded for

    s>=8,

  and for

    s=7 with M<=12.

No assertion is made that the complementary degree pairs are realizable.

--------------------------------------------------------------------------
10. SHARP BOUNDARY
--------------------------------------------------------------------------

NEWLY_PROVED:
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_residual_multiplicity_five_excluded.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_residual_multiplicity_in_3_or_4.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_regular_cut_three_types.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_rres_at_most_four.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_Lres_at_most_4M.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_min_final_degree_ge8_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_s7_Mle12_closed.

CURRENT_E01_RESIDUAL_TYPES:
  R3:
    e(R_res)=3,
    Jbar=(v,w,u^3),
    r_res<=3.

  R4U:
    e(R_res)=4,
    Jbar=(v,w,u^4),
    r_res<=3.

  R4S:
    e(R_res)=4,
    Jbar=(w,u^3,u*v,v^2),
    r_res<=4.

UNIFORM_SURVIVING_DEGREE_FRONTIER_FROM_THIS_ESTIMATE:
  3<=min(d,e)<=6,

  or

  min(d,e)=7 and max(d,e)>=13.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove that any surviving degree pair is realizable.
  It does NOT exclude every E0/E1 state.
  It does NOT classify the full one-dimensional ring R_res, only its regular
  Artinian cut relative to the known E-annihilator.
  It does NOT prove Jbar=Ann(E) in the length-four states.
  It does NOT treat E2.
  It does NOT enter H01-C4.
  It does NOT enter q<=3.
  It does NOT prove full order-13 closure.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H01_C5_mge4_closed.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_saturation_cyclic.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_colon_classified.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_torsion_Koszul_reduced.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_product_annihilator_reduced.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_residual_multiplicity_in_3_or_4.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_rres_at_most_four.
  q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_min_final_degree_ge8_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_E01_all_degrees_closed.
  not q4_height2_multiplicity_one_depth_one_H01_C5_m3_closed.
  not q4_height2_multiplicity_one_depth_one_H01_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not homogeneous_q_le_3_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Stay only in H01-C5 m=3 E0/E1.  For the three residual cut types R3, R4U,
  R4S, use the exact ideals

    (v,w,u^3),
    (v,w,u^4),
    (w,u^3,u*v,v^2)

  to compute the actual two-element Koszul residual length and generator
  contribution for the surviving degree frontier

    3<=min(d,e)<=6,

  or

    min(d,e)=7, max(d,e)>=13.

  Determine whether the exact cut type forces a better bound than

    L_res<=e(R_res)*M

  or a smaller image-generator number than the ambient bound r_res.

NEXT_ACTIONS:
  1. Stay only in H01-C5 m=3 E0/E1.
  2. Start with the worst type R4S=(w,u^3,u*v,v^2).
  3. Compute the exact image of final forms f,g in its one-dimensional lift or the strongest cut-length bound forced by this Artinian reduction.
  4. Reinsert that exact bound into the tangent carrier for the surviving degree pairs.
  5. Stop before E2, H01-C4, q<=3, or any full order-13 claim.
