Standalone closure of the degree-gap-one zerodivisor lower-cut subbranch in the
homogeneous q=4, height-three, multiplicity-six order-13 endpoint.

SCOPE:
  Continue from

    order13_q4_e6_zerodivisor_lower_cut_profile.v,
    order13_q4_e6_zerodivisor_conormal_ext_reduction.v,
    order13_q4_e6_zerodivisor_stable_layer_reduction.v,
    order13_q4_e6_stable_layer_bockstein_classification.v.

  Work in the established setup

    B := S/Q,
    dim(B)=1,
    B Cohen--Macaulay,
    e(B)=6,
    Hilb_B(z)=(1+3*z+2*z^2)/(1-z),

  with ell in B_1 a homogeneous nonzerodivisor and

    J_0 := (a,b),
    J_1 := (a,ell*b),
    L   := ell^r*J_1,
    A   := B/L,
    r>=1.

  Here a is a nonzero quadratic zerodivisor, J_0 and J_1 are m-primary, and
  k=1 is exactly the unequal-degree case

    deg(g)-deg(f)=1.

  The preceding conormal--Ext reduction defines

    E_0 := 0:_A J_0,

    delta_1
      := dim_C Hom_B(J_0/J_1,A)
         - dim_C ker(
             Ext^1_B(J_0/J_1,A)
               -> Ext^1_B(J_0,A)),

  and proves that the order-13 tangent gate is impossible whenever

    length_C(E_0)+delta_1 <= 19.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
does not assert generic F_13 algebraicity.

Theorem ordinary_quadratic_pair_contains_regular_quadric:
  There exists a constant C-linear combination

    q = alpha*a + beta*b

  which is a homogeneous quadratic nonzerodivisor on B.

Proof:
  Because B is one-dimensional Cohen--Macaulay, every associated prime of B is
  minimal.

  The ideal J_0=(a,b) is m-primary.  Hence no minimal prime of B contains both
  a and b.  For each minimal prime P, the set

    { (alpha,beta) in C^2 : alpha*a+beta*b belongs to P }

  is therefore a proper C-linear subspace of C^2.

  There are only finitely many associated primes.  Since C is infinite, their
  finite union cannot fill C^2.  Choose (alpha,beta) outside that union.

  Then q avoids every associated prime of B and is therefore a
  nonzerodivisor.  Since a and b both have degree two, q is homogeneous of
  degree two.
Qed.

Theorem regular_quadric_section_has_length_twelve:
  For q as above,

    length_C(B/q*B)=12.

Proof:
  Since q is B-regular of degree two,

    Hilb_(B/qB)(z)
      = (1-z^2) Hilb_B(z)
      = (1+z)(1+3*z+2*z^2)
      = 1+4*z+5*z^2+2*z^3.

  Summing the Hilbert function gives

    1+4+5+2=12.
Qed.

Theorem ordinary_pair_annihilator_has_uniform_length_twelve_bound:
  One has

    length_C(E_0) <= 12.

Proof:
  The regular quadric q belongs to J_0.  Therefore every class annihilated by
  J_0 is annihilated by q, so

    E_0 subseteq 0:_A q.

  Since A is finite-dimensional, kernel and cokernel of multiplication by q
  on A have equal C-dimension.  Hence

    length_C(0:_A q)=length_C(A/qA).

  The quotient A/qA is a quotient of B/qB.  Therefore

    length_C(E_0)
      <= length_C(A/qA)
      <= length_C(B/qB)
      =12.
Qed.

Put

  W_1 := J_0/J_1.

Theorem first_delayed_layer_is_cyclic_and_killed_by_ell:
  The B-module W_1 is cyclic, generated by the class of b, and

    ell*W_1=0.

Proof:
  Modulo J_1=(a,ell*b), the class of a vanishes, so the quotient J_0/J_1 is
  generated by the class of b.

  Multiplication by ell sends that generator to ell*b, which belongs to J_1.
  Hence ell kills W_1.
Qed.

Theorem ell_annihilator_of_A_has_length_six:
  One has

    length_C(0:_A ell)=6.

Proof:
  Multiplication by ell on the finite-dimensional vector space A has kernel
  and cokernel of equal dimension.  Thus

    length_C(0:_A ell)=length_C(A/ell*A).

  Since

    L=ell^r*J_1 subseteq ell*B

  for r>=1,

    A/ell*A
      ~= B/(L,ell)
      ~= B/(ell).

  The established multiplicity-six Artin reduction has Hilbert function

    (1,3,2),

  hence length six.
Qed.

Corollary first_delayed_Hom_space_has_dimension_at_most_six:
  One has

    dim_C Hom_B(W_1,A) <= 6.

Proof:
  A B-linear map W_1 -> A is determined by the image of the cyclic generator.
  Because ell kills W_1, that image must lie in 0:_A ell.  Evaluation at the
  generator therefore injects

    Hom_B(W_1,A) -> 0:_A ell.

  The preceding theorem gives length(0:_A ell)=6.
Qed.

Corollary first_delayed_conormal_defect_is_at_most_six:
  One has

    delta_1 <= 6.

Proof:
  By definition,

    delta_1
      = dim Hom_B(W_1,A)
        - dim ker(
            Ext^1_B(W_1,A) -> Ext^1_B(J_0,A)).

  The second term is nonnegative, while the first is at most six.
Qed.

Theorem zerodivisor_degree_gap_one_cannot_pass_order13_tangent_gate:
  In the k=1 zerodivisor lower-cut subbranch,

    length_C(E_0)+delta_1 <= 18.

  Consequently the necessary order-13 tangent gate

    dim_C Hom_S(I,A) <= N-20

  is impossible.

Proof:
  Combine

    length(E_0)<=12

  with

    delta_1<=6.

  Thus

    length(E_0)+delta_1<=18<20.

  The preceding conormal--Ext reduction proves that every candidate satisfying
  the tangent gate must instead have

    length(E_0)+delta_1>=20.

  Contradiction.
Qed.

Corollary surviving_zerodivisor_unequal_degree_candidates_have_gap_at_least_two:
  Any still-unclosed zerodivisor unequal-degree candidate must satisfy

    k>=2.

  Moreover the universal bound length(E_0)<=12 shows that any dangerous
  candidate at any k must have

    delta_k>=8.
Qed.

Interpretation:
  The first unequal-degree zerodivisor slice is now closed without computing
  the stable Bockstein connecting rank.  Any surviving candidate must use at
  least one stable layer V from the Bockstein classification.

IMPORTANT_NONCONCLUSION:
  This file does NOT close k>=2.

  It does not prove the stable compensation inequality Delta_i<=0 for the
  repeated Bockstein layers, and it makes no claim for the height-three e<=5
  branches, the height-two q=4 branch, homogeneous q<=3, or the unrestricted
  nonhomogeneous frontier.

BOUNDARY:
  The remaining e=6 zerodivisor unequal-degree endpoint has

    k>=2,
    length(E_0)<=12,
    delta_k>=8

  for any dangerous candidate.

  Since the exceptional first-step contribution satisfies Delta_1<=6, a
  dangerous candidate must obtain positive net conormal defect from the stable
  Bockstein sector i>=2.

NEXT_BOUNDED_OBJECT:
  compute the stable one-step defect

    Delta_i
      = dim Hom_B(V,A)
        - dim ker(
            Ext^1_B(V,A) -> Ext^1_B(J_(i-1),A))

  for i>=2 using the eight possible cyclic quotient shapes V of

    R=B/(ell),  Hilb_R=(1,3,2).

  The target remains Delta_i<=0, or a sharp positive bound strong enough to
  combine with length(E_0)<=12 and Delta_1<=6.
