Standalone residual-linear classification for the multiplicity-three h=(1,2)
subbranch of the homogeneous q=4, height-three order-13 low-multiplicity
problem.

SCOPE:
  Continue from

    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_degree3_hvector_linkage_impossible.v

  and work only with

    S := C[x1,x2,x3,x4],
    R := S/(q1,q2,q3),

  where q1,q2,q3 form a homogeneous regular sequence of quadrics.

Let

  q := image of the fourth quadric in R,
  J := q*R,
  U := saturation(J),
  K := 0:_R q,
  B := R/J,
  T := U/J,
  Cbar := R/U.

Assume

  e(B)=3,
  h(Cbar/ell*Cbar)=(1,2)

for a general linear nonzerodivisor ell on Cbar.

The exact saturation-linkage table gives

  Hilb_T(t)=t+3*t^2+t^3,
  length_C(T)=5,
  T_n=0 for n>=4,
  m^3*T=0.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded structural step: classify the unique
linear class in the saturation hull U.  The result is an exact dichotomy.
Either U is principal over that linear class and the torsion has a faithful
length-five action quotient, or there is exactly one linear annihilator
direction and it forms an exact zero-divisor pair with the saturation class.
No tangent closure is claimed here.

Theorem exact_residual_Hilbert_series_for_e3_12:
  One has

    Hilb_K(t)=(2*t^2+t^3)/(1-t),
    Hilb_U(t)=(t+3*t^2+t^3)/(1-t).

  Consequently

    K_0=K_1=0,
    dim_C K_2=2,
    dim_C K_n=3 for n>=3,

    dim_C U_1=1,
    dim_C U_2=4,
    dim_C U_n=5 for n>=3.

Proof:
  The saturated core has

    Hilb_Cbar(t)=(1+2*t)/(1-t).

  Graded canonical-module reciprocity gives

    Hilb_omega_Cbar(t)
      =t*(1+2*t^(-1))/(1-t)
      =(t+2)/(1-t).

  The exact linkage theorem K(2)~=omega_Cbar therefore gives

    Hilb_K(t)=t^2*Hilb_omega_Cbar(t)
             =(2*t^2+t^3)/(1-t).

  Since

    Hilb_R(t)=(1+3*t+3*t^2+t^3)/(1-t)

  and Cbar=R/U,

    Hilb_U=Hilb_R-Hilb_Cbar
          =(t+3*t^2+t^3)/(1-t).

  Reading coefficients gives the displayed dimensions.
Qed.

Choose a nonzero homogeneous class

  v in U_1.

It is unique up to a nonzero scalar because dim_C U_1=1.

Put

  H_v := (0:_R v)/K.

The inclusion K subseteq 0:_R v is automatic because v belongs to U and
K=0:_R U.

Theorem exact_Hilbert_balance_for_the_linear_residual_defect:
  Multiplication by v gives

    Hilb_(U/vR)(t)=t*Hilb_(H_v)(t).

Proof:
  Multiplication by v identifies

    R/(0:_R v)(-1) ~= vR.

  Since

    0:_R v / K = H_v,

  one has

    Hilb_(vR)
      =t*(Hilb_R-Hilb_(0:_R v))
      =t*(Hilb_R-Hilb_K-Hilb_Hv).

  Direct substitution of the Hilbert series above gives

    t*(Hilb_R-Hilb_K)=Hilb_U.

  Therefore

    Hilb_(vR)=Hilb_U-t*Hilb_Hv.

  Because vR subseteq U, subtraction yields

    Hilb_(U/vR)=t*Hilb_Hv.
Qed.

Corollary principal_residual_is_equivalent_to_zero_annihilator_defect:
  One has

    H_v=0  iff  U=vR.
Qed.

Theorem the_linear_annihilator_defect_has_dimension_at_most_one:
  One has

    dim_C (H_v)_1 <= 1.

Proof:
  Since K_1=0,

    (H_v)_1=(0:_R v)_1.

  Suppose two independent linear classes w1,w2 in R_1 annihilate v.  Choose
  linear lifts of v,w1,w2 to S.  Then

    v*w1,
    v*w2

  are two linearly independent quadrics in the degree-two span of the defining
  regular sequence q1,q2,q3.  Independence follows because S is a domain and
  w1,w2 are independent.

  Extend these two products to a basis

    v*w1,
    v*w2,
    p3

  of that three-dimensional quadratic span.  Then

    (q1,q2,q3)=(v*w1,v*w2,p3).

  But the right-hand ideal is contained in

    (v,p3),

  an ideal generated by two elements and therefore of height at most two.
  This contradicts ht(q1,q2,q3)=3.

  Hence at most one independent linear annihilator direction exists.
Qed.

We now split by the only two possible values of dim(H_v)_1.

SECTION NO_LINEAR_ANNIHILATOR_DEFECT.

Assume

  (H_v)_1=0.

Theorem the_fourth_quadric_factors_through_v:
  There exists c in R_1 such that

    q=v*c.

Proof:
  The Hilbert-balance theorem gives

    dim_C(U/vR)_2=dim_C(H_v)_1=0.

  Hence U_2=(vR)_2.  Since q belongs to U_2 and has degree two, q=v*c for some
  linear c.
Qed.

Theorem the_residual_defect_is_finite_length:
  Both

    U/vR

  and

    H_v

  have finite length.

Proof:
  Since q=v*c, one has qR subseteq vR subseteq U.

  Let P be any nonirrelevant homogeneous prime.  Saturation does not change the
  localization of qR, so

    U_P=qR_P.

  Localizing the displayed inclusions gives

    vR_P subseteq U_P=qR_P subseteq vR_P,

  hence equality.  Thus U/vR is supported only at the irrelevant maximal ideal
  and has finite length.

  The Hilbert-balance identity

    Hilb_(U/vR)=t*Hilb_Hv

  then makes H_v finite length as well.
Qed.

Lemma annihilator_ideals_are_saturated_in_the_one_dimensional_CI:
  Both ideals

    K=0:_R U

  and

    0:_R v

  are saturated with respect to the irrelevant maximal ideal.

Proof:
  Choose a linear nonzerodivisor ell_R on the one-dimensional Cohen--Macaulay
  ring R.

  If x belongs to the saturation of K, then for some n

    ell_R^n*x belongs to K.

  Hence for every u in U,

    ell_R^n*x*u=0.

  Regularity of ell_R on R gives x*u=0, so x belongs to K.

  The same argument with U replaced by the single element v proves that
  0:_R v is saturated.
Qed.

Theorem no_linear_defect_forces_the_principal_residual:
  One has

    H_v=0,
    0:_R v=K,
    U=vR.

Proof:
  The preceding theorem makes H_v=(0:_R v)/K finite length.  Hence every class
  of 0:_R v modulo K is killed by a power of the irrelevant maximal ideal.
  Therefore every element of 0:_R v lies in the saturation of K.  Since K is
  saturated, 0:_R v subseteq K.  The reverse inclusion was already known, so

    0:_R v=K.

  Thus H_v=0.  The Hilbert-balance identity then gives U/vR=0.
Qed.

Put

  C0:=R/K.

Corollary principal_residual_has_a_length_five_action_quotient:
  Multiplication by v identifies

    C0(-1) ~= U=vR.

  With q=v*c put

    Z:=C0/c*C0.

  Then

    T ~= Z(-1),
    Hilb_Z(t)=1+3*t+t^2,
    length_C(Z)=5.

  Moreover in B=R/(v*c),

    Ann_B(T)=(K+cR)/(v*cR),
    B/Ann_B(T) ~= Z.

Proof:
  The kernel of multiplication by v is 0:_R v=K, so the first isomorphism is
  exact.  Quotienting U=vR by qR=v*cR gives

    T=U/qR ~= (C0/c*C0)(-1).

  The known Hilbert series

    Hilb_T=t+3*t^2+t^3

  gives Hilb_Z=1+3*t+t^2 and length five.

  Finally, a class r modulo v*c annihilates T exactly when

    r*v belongs to v*cR.

  This is equivalent to r-c*d belonging to 0:_R v=K for some d, hence to

    r belonging to K+cR.

  The quotient statement follows.
Qed.

END NO_LINEAR_ANNIHILATOR_DEFECT.

SECTION ONE_LINEAR_ANNIHILATOR_DEFECT.

Assume

  dim_C(H_v)_1=1.

Choose a nonzero w in (0:_R v)_1.

Theorem the_unique_linear_annihilator_forms_an_exact_zero_divisor_pair:
  One has

    0:_R v=wR,
    0:_R w=vR.

Proof:
  The quadratic product v*w vanishes in R, hence its nonzero lift belongs to
  the degree-two span of q1,q2,q3.  Rebase that regular sequence as

    v*w,
    p2,
    p3.

  Put D:=S/(p2,p3).  Since p2,p3,v*w is a regular sequence, v*w is a
  nonzerodivisor on D.  Therefore both v and w are nonzerodivisors on D.

  If f*v belongs to (v*w,p2,p3), then modulo (p2,p3)

    f*v=a*v*w

  for some a.  Cancelling the nonzerodivisor v on D gives

    f=a*w mod (p2,p3).

  Thus ((v*w,p2,p3):v)=(w,p2,p3).  The symmetric calculation gives the other
  colon.  Passing to R proves the claim.
Qed.

Corollary the_nonprincipal_residual_has_exact_Hilbert_defect:
  One has

    Hilb_(H_v)(t)=t/(1-t),
    Hilb_(U/vR)(t)=t^2/(1-t).

  In particular U is strictly larger than vR in dimension one.

Proof:
  Since 0:_R w=vR, multiplication by w identifies

    R/vR(-1) ~= wR=0:_R v.

  The quotient R/vR is the complete intersection

    S/(v,p2,p3)

  of degrees (1,2,2), so

    Hilb_(R/vR)=(1+2*t+t^2)/(1-t).

  Hence

    Hilb_(0:_R v)=(t+2*t^2+t^3)/(1-t).

  Subtract

    Hilb_K=(2*t^2+t^3)/(1-t)

  to obtain Hilb_Hv=t/(1-t).  The Hilbert-balance theorem then gives the
  formula for U/vR.
Qed.

Theorem the_fourth_quadric_does_not_factor_through_v_in_the_exact_pair_case:
  One has

    q notin vR.

Proof:
  Suppose q belonged to vR.  Since qR subseteq vR subseteq U and U is the
  saturation of qR, localization at every nonirrelevant homogeneous prime P
  would give

    vR_P subseteq U_P=qR_P subseteq vR_P.

  Thus U/vR would be supported only at the irrelevant maximal ideal and would
  have finite length.

  But the preceding corollary gives

    Hilb_(U/vR)=t^2/(1-t),

  which has infinite length.  Contradiction.
Qed.

END ONE_LINEAR_ANNIHILATOR_DEFECT.

Theorem exact_e3_12_residual_linear_dichotomy:
  Exactly one of the following occurs.

  PRINCIPAL_V:
    H_v=0,
    0:_R v=K,
    U=vR,
    q=v*c for some c in R_1,
    T~=Z(-1),
    Hilb_Z=1+3*t+t^2,
    length_C(Z)=5,
    B/Ann_B(T)~=Z.

  EXACT_PAIR_VW:
    dim_C(H_v)_1=1,
    0:_R v=wR,
    0:_R w=vR,
    Hilb_Hv=t/(1-t),
    Hilb_(U/vR)=t^2/(1-t),
    q notin vR.

Proof:
  The linear-defect theorem gives dim(H_v)_1 in {0,1}.  The two sections above
  classify the two values, and they are disjoint.
Qed.

Interpretation:
  The e=3, h=(1,2) linkage frontier no longer contains an arbitrary saturation
  hull.  The unique linear class v in U has only two possible behaviors.

  In the principal case it captures all of U and produces a faithful
  length-five action quotient with Hilbert function (1,3,1).

  In the nonprincipal case the obstruction is rigid: there is exactly one
  linear annihilator w, v and w are an exact zero-divisor pair, and the failure
  of principalness is the explicit one-dimensional tail

    Hilb_(U/vR)=t^2/(1-t).

IMPORTANT_NONCONCLUSION:
  This file does NOT close the e=3, h=(1,2) tangent branch.

  It does not classify the multiplication algebra of the length-five action
  quotient Z from its Hilbert function alone.  It does not yet pass the final
  cuts to their degree-one saturated-core predecessors.  It makes no claim for
  the remaining e=3, h=(1,1,1) row, q=4 height two, homogeneous q<=3, the
  unrestricted nonhomogeneous frontier, or generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e3_h12_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Analyze the tangent carrier separately in PRINCIPAL_V and EXACT_PAIR_VW.

NEXT_BOUNDED_OBJECT:
  Treat PRINCIPAL_V first.  Because

    Hilb_Cbar=(1+2*t)/(1-t),

  multiplication by a general parameter ell is an isomorphism from degree one
  onward.  Pull both final cuts back to degree-one predecessors, compute the
  resulting finite carrier over the exact length-five action quotient Z, and
  close it if its conormal deficit misses the order-13 tangent gate.  Do not
  enter EXACT_PAIR_VW unless the principal case is closed or exposes a genuine
  obstruction.
