Standalone closure of the s=1 branch for the homogeneous q=4,
height-two Cohen--Macaulay LINE CORE in the order-13 deviation-two branch.

SCOPE:
  Continue only from

    order13_q4_height2_cm_line_core_s1_rank2_excluded.v

  and retain

    S := C[l1,l2,z,w],
    J := (l1,l2),
    P := C[l1,l2],
    Q subset J,
    T := J/Q,

  with Q minimally generated by exactly four independent quadrics,
  ht(Q)=2, Qsat=J, and T finite length.

The preceding file treats

    s := dim_C Syz_1(Q)=1

and proves

    H := J^3*T/J^4*T ~= C(-4)^h,
    h in {0,1}.

It already closes every s=1 configuration except the single residual

    r=3,
    h=1,
    K3=H0*V direct_sum C*R3,
    H0=D*H1,
    R3=D*R2,
    gcd(H1,R2)=1,

where D,H1 are linear and R2 is quadratic.

This file rules out that residual by the canonical quartic compatibility
relation of the normalized r=3 first-conormal matrix.

The s=2 case is not treated here.
The depth-one saturated-core branch is not used.

This file is pseudo-formal mathematical documentation.  It is not Coq or Lean
and MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

Put

    V := Span_C{l1,l2}.

Theorem residual_s1_common_factor_makes_all_cubic_relations_D_divisible:
  In the residual r=3,s=1,h=1 case one has

    K3 = D*P_2.

  Consequently

    P_1*K3 = D*P_3.

Proof:
  The preceding file gives

    K3 = H0*V direct_sum C*R3
       = D*(H1*V + C*R2).

  The space P_2 has dimension three.  The subspace H1*V has dimension two.
  Since R3 is not in H0*V, the quadratic R2 is not in H1*V.  Therefore

    H1*V + C*R2 = P_2.

  Hence K3=D*P_2, and multiplication by P_1 gives P_1*K3=D*P_3.
Qed.

We now normalize the r=3 first-conormal matrix.

Theorem normalized_r3_quadratic_generators:
  After independent linear changes of bases in Span_C{z,w}, V and a constant
  change of the four quadratic generators, one may write

    q1 = z*l1 + h1,
    q2 = w*l1 + z*l2 + h2,
    q3 = w*l2 + h3,
    q4 = H0,

  with

    h1,h2,h3,H0 in P_2.

Proof:
  The first-conormal r=3 relation space is the nondegenerate hyperplane normal
  form established in the second-layer classification:

    Span_C{
      z tensor l1,
      w tensor l1 + z tensor l2,
      w tensor l2
    }.

  The fourth quadratic-generator direction is exactly the one-dimensional
  space Q_2 intersect J^2_2, generated by H0.  Lifting the three first initial
  forms adds only pure J^2 quadratic corrections h1,h2,h3, yielding the stated
  form.
Qed.

Theorem canonical_r3_pure_quartic_compatibility_relation:
  In the normalized form define

    C4 := l2^2*h1 - l1*l2*h2 + l1^2*h3 in P_4.

  Then

    C4 in Q_4 intersect P_4.

Proof:
  Directly,

    l2^2*q1 - l1*l2*q2 + l1^2*q3

  has z-coefficient

    l1*l2^2 - l1*l2^2 = 0

  and w-coefficient

    -l1^2*l2 + l1^2*l2 = 0.

  The remaining pure-transverse term is exactly C4.  Hence C4 belongs to Q and
  lies in P_4.
Qed.

Theorem residual_h1_forces_D_to_divide_the_quartic_compatibility:
  In the residual h=1 case,

    C4 in D*P_3.

  In particular D divides C4.

Proof:
  The preceding s=1 rank-two exclusion proves that h=1 forces

    Q_4 intersect P_4 = P_1*K3.

  The first theorem of this file identifies the right side with D*P_3.
  Since C4 belongs to Q_4 intersect P_4, it is divisible by D.
Qed.

Theorem residual_h1_produces_a_projective_zero_off_the_saturated_line:
  The residual r=3,s=1,h=1 configuration is impossible.

Proof:
  Choose a nonzero point

    [a:b] in P(V)=P^1

  with

    D(a,b)=0.

  Since H0=D*H1,

    H0(a,b)=0.

  Since D divides C4,

    C4(a,b)=0.

  Evaluate q1,q2,q3 at l1=a,l2=b.  Solving q1=q2=q3=0 for z,w is the linear
  system

    a*z                 = -h1(a,b),
    b*z + a*w           = -h2(a,b),
          b*w           = -h3(a,b).

  Its 3 by 2 coefficient matrix

    [ a  0 ]
    [ b  a ]
    [ 0  b ]

  has rank two for every nonzero pair (a,b).  A generator of its one-dimensional
  left kernel is

    (b^2, -a*b, a^2).

  Therefore the unique compatibility condition for the system is

    b^2*h1(a,b) - a*b*h2(a,b) + a^2*h3(a,b)=0,

  which is exactly

    C4(a,b)=0.

  Hence there exist z0,w0 satisfying q1=q2=q3=0.  Together with H0(a,b)=0,
  the projective point

    [l1:l2:z:w]=[a:b:z0:w0]

  is a common zero of q1,q2,q3,q4.

  But (a,b) is nonzero, so this point is not on the saturated line

    V(J)={l1=l2=0}.

  This contradicts

    Qsat=J,

  equivalently

    Proj(S/Q)=Proj(S/J).

  Therefore the residual h=1 case cannot occur.
Qed.

Corollary s1_forces_the_fourth_layer_to_vanish:
  If

    s=1,

  then

    H=J^3*T/J^4*T=0.

  Equivalently,

    h=0.

Proof:
  The preceding file already proves h in {0,1} and closes every h=0 case.
  The theorem above rules out the sole h=1 residual configuration.
Qed.

Corollary s1_closes_the_transverse_tower_at_J_cubed:
  If s=1, then

    J^3*T=0.

Proof:
  Since H=0,

    J^3*T=J^4*T=J*(J^3*T).

  The module J^3*T has finite length and J lies in the homogeneous maximal
  ideal.  Nakayama's lemma gives J^3*T=0.
Qed.

Corollary exact_s1_torsion_support_bound:
  In the s=1 branch the saturation defect has no J-adic layers beyond

    T/J*T,
    J*T/J^2*T,
    J^2*T/J^3*T.

  In particular

    J^3*T=0.
Qed.

IMPORTANT_NONCONCLUSION:
  This file closes only

    s=1.

  It does not treat

    s=2.

  Therefore it does not yet close the full q=4 height-two CM line core.
  No tangent-gate contradiction is claimed here.
  The depth-one saturated-core branch remains untouched.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_CM_conic_core_closed.
  q4_height2_CM_line_core_first_conormal_layer_classified.
  q4_height2_CM_line_core_second_J_adic_layer_classified.
  q4_height2_CM_line_core_s0_closed.
  q4_height2_CM_line_core_s1_closed.
  not q4_height2_CM_line_core_s2_closed.
  not q4_height2_CM_line_core_closed.
  not q4_height2_depth_one_core_closed.
  not q4_height2_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Treat only the remaining

    s=2

  line-core branch, where

    G=J^2*T/J^3*T ~= C(-3)^2

  and the fourth-layer rank currently satisfies

    0 <= h <= 4.

  Use the two independent linear syzygies to classify the pure-transverse cubic
  relation space K3=Q_3 intersect P_3, then bound or determine

    H=J^3*T/J^4*T.

NEXT_BOUNDED_OBJECT:
  Enter only s=2.  Determine the exact dimension and gcd profile of

    K3=Q_3 intersect P_3

  and use its quartic span P_1*K3 before attempting any deeper J-adic layer.
  Do not enter the depth-one deficiency branch.