Standalone torsion-self-action split for the multiplicity-five h=(1,2,2)
subbranch of the homogeneous q=4, height-three order-13 low-multiplicity
problem.

SCOPE:
  Continue from

    order13_q4_height3_e5_122_cyclic_torsion_annihilator_reduction.v
    order13_q4_height3_e5_122_quadratic_predecessor_split_reduction.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has

    h(Cbar/ell*Cbar)=(1,2,2).

  The preceding cyclic-torsion reduction proves, with

    J:=Ann_B(T),
    Z:=B/J,

  that

    T ~= Z(-1) as graded B-modules,
    Z ~= C[z]/(z^3),
    Hilb_T=t+t^2+t^3,
    length_C(Z)=3,
    length_C(T)=3,
    m_B^3*T=0.

  The preceding quadratic-predecessor split writes

    K_i:=(a,ell^i*b) subset Cbar,

  with a,b in Cbar_2, K_0=(a,b) m-primary, and in the remaining
  ZERODIVISOR_QUADRATIC_LOWER case a is a zerodivisor on Cbar.  It defines

    X:=Ann_A(T)=J/L,
    eta_i:=(N-3)-dim_C Hom_Cbar(K_i,X),

  and proves

    eta_k>=17

  for every candidate satisfying the necessary order-13 tangent gate, while

    eta_0<=13,
    Delta_i<=0 for every i>=2,

  where

    Delta_i:=dim Hom_Cbar(K_(i-1),X)-dim Hom_Cbar(K_i,X).

  Thus the only unresolved contribution was

    eta_1=eta_0+Delta_1.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one bounded structural split.  The natural map from
the embedded torsion ideal T to its faithful length-three action quotient Z has
only two possibilities.  If it is nonzero, the exact first-layer deficit is at
most sixteen and the order-13 tangent gate fails.  The only surviving case is
therefore the square-zero self-action case

    T^2=0.

No closure of that square-zero residual is claimed here.

Theorem natural_torsion_to_action_quotient_has_only_two_forms:
  Let

    pi:T -> Z=B/J

  be the map obtained by including T in B and then quotienting by J.

  Under graded B-module identifications

    T ~= Z(-1),
    Z ~= C[z]/(z^3),

  exactly one of the following holds:

    ZERO_SELF_ACTION:
      pi=0,
      ker(pi)=T;

    NONZERO_SELF_ACTION:
      pi is multiplication by a nonzero scalar multiple of z,
      ker(pi)=T_3.

Proof:
  By definition J=Ann_B(T), so the B-action on T factors through Z.  The target
  Z is also a Z-module in the evident way.  Hence pi is a graded Z-linear map

    Z(-1) -> Z

  of degree zero.

  Such a map is determined by the image of the degree-one generator of Z(-1),
  and that image must lie in

    Z_1=C*z.

  Therefore pi is either zero or multiplication by lambda*z for some nonzero
  lambda in C.

  In the nonzero case, multiplication by z on

    Z=C[z]/(z^3)

  has kernel the top line C*z^2.  Under the shift T~=Z(-1), this is exactly the
  degree-three line T_3.
Qed.

Corollary exact_torsion_annihilator_intersection_dichotomy:
  Exactly one of the following holds:

    ZERO_SELF_ACTION:
      J intersect T=T;

    NONZERO_SELF_ACTION:
      J intersect T=T_3.

Proof:
  The kernel of the natural map

    T -> B/J

  is exactly T intersect J.  Apply the preceding theorem.
Qed.

Corollary zero_self_action_is_equivalent_to_square_zero_torsion:
  The following are equivalent:

    pi=0,
    T subseteq J=Ann_B(T),
    T^2=0.

Proof:
  The first two statements are equivalent because ker(pi)=T intersect J.

  If T subseteq Ann_B(T), every element of T annihilates every element of T,
  so T^2=0.

  Conversely, if T^2=0, every element of T annihilates T and therefore belongs
  to Ann_B(T)=J.
Qed.

We now close the NONZERO_SELF_ACTION case.

SECTION NONZERO_SELF_ACTION.

Assume

  J intersect T=T_3.

Theorem choose_a_regular_quadratic_combination_inside_the_first_delayed_cubic:
  There exists lambda in C such that

    q0:=a+lambda*b

  is a nonzerodivisor on Cbar.

  For such a choice put

    q:=ell*q0.

  Then q is a homogeneous degree-three nonzerodivisor on Cbar and

    q belongs to K_1=(a,ell*b).

Proof:
  Since K_0=(a,b) is m-primary in the one-dimensional Cohen--Macaulay ring
  Cbar, its two-dimensional C-linear span is not contained in any associated
  prime.  The associated primes are the finitely many minimal primes of Cbar.
  Over C, a general constant combination a+lambda*b therefore avoids all of
  them and is a nonzerodivisor.

  The parameter ell is also a nonzerodivisor, so their product q is regular on
  Cbar.

  Finally

    q=ell*a+lambda*ell*b

  lies in the ideal generated by a and ell*b, namely K_1.
Qed.

Choose homogeneous lifts of ell and q0 to B and use the same symbol q for their
product in B.

Theorem regular_first_layer_cubic_has_kernel_exactly_T_in_B:
  One has

    0:_B q=T.

Proof:
  The element q has degree three, while m_B^3*T=0.  Hence q*T=0 and

    T subseteq 0:_B q.

  Conversely, if q*x=0 in B, projection to Cbar gives

    qbar*xbar=0.

  The preceding theorem makes qbar a nonzerodivisor on Cbar, so xbar=0.  Thus
  x belongs to T.
Qed.

Corollary regular_first_layer_cubic_has_one_dimensional_kernel_on_J:
  One has

    0:_J q=T_3,

  and therefore

    length_C(0:_J q)=1.

Proof:
  Since J is an ideal of B,

    0:_J q=J intersect (0:_B q).

  The preceding theorem identifies 0:_B q with T, and the standing
  NONZERO_SELF_ACTION assumption gives J intersect T=T_3.
Qed.

Theorem exact_regular_cubic_section_of_J_has_length_sixteen:
  One has

    length_C(J/qJ)=16.

Proof:
  The quotient B/J has finite length three.  Therefore J and B have the same
  one-dimensional multiplicity,

    e(J)=e(B)=5.

  Multiplication by the degree-three element q on J gives an exact sequence

    0 -> (0:_J q)(-3)
      -> J(-3)
      --q--> J
      -> J/qJ
      -> 0.

  The cokernel has finite length because q is regular on the saturated core.
  Taking the value at t=1 of the Hilbert-series identity gives

    length_C(J/qJ)
      =3*e(J)+length_C(0:_J q)
      =3*5+1
      =16.
Qed.

Theorem first_quadratic_delayed_deficit_is_at_most_sixteen:
  One has

    eta_1<=16.

Proof:
  The preceding quadratic-predecessor file proves the universal multiplication
  bound

    eta_1<=dim_C(0:_X K_1).

  Since q belongs to K_1,

    0:_X K_1 subseteq 0:_X q.

  Now X=J/L.  Multiplication by q on the finite-dimensional vector space X has
  kernel and cokernel of equal dimension, hence

    dim_C(0:_X q)=length_C(X/qX).

  But

    X/qX
      =J/(L+qJ)

  is a quotient of J/qJ.  The preceding theorem gives

    length_C(X/qX)<=16.

  Combining the inequalities proves eta_1<=16.
Qed.

Theorem every_nonzero_self_action_degree_gap_has_deficit_at_most_sixteen:
  For every k>=0,

    eta_k<=16.

Proof:
  If k=0, the preceding quadratic-predecessor reduction gives eta_0<=13.

  If k>=1, telescope

    eta_k=eta_1+sum_(i=2)^k Delta_i.

  The first-layer theorem gives eta_1<=16, while every Delta_i with i>=2 is
  nonpositive.  Therefore eta_k<=16.
Qed.

Corollary nonzero_self_action_case_is_closed:
  No NONZERO_SELF_ACTION candidate can satisfy the necessary order-13 tangent
  gate.

Proof:
  The tangent gate forces eta_k>=17, while the preceding theorem gives
  eta_k<=16.
Qed.

END NONZERO_SELF_ACTION.

We record the exact surviving residual in the linkage presentation.

Recall from the cyclic-torsion reduction

  R:=S/(q1,q2,q3),
  U=uR,
  K:=0:_R u,
  q4=u*c,
  B=R/(u*c),
  T=uR/(u*cR),

with

  C0:=R/K,
  Z~=C0/c*C0~=C[z]/(z^3).

Theorem square_zero_residual_is_linear_alignment_on_the_length_three_link:
  In ZERO_SELF_ACTION, the degree-one class of u in C0 is a scalar multiple of
  the degree-one class of c.  Equivalently,

    u belongs to K+cR.

  Consequently there is lambda in C with

    u-lambda*c in K,

  and therefore

    u^2=lambda*u*c

  in R.  In B=R/(u*c), this gives

    u^2=0.

Proof:
  The degree-one generator of T is the class of u.  ZERO_SELF_ACTION says its
  image in

    Z=R/(K,c)

  is zero.  Hence u belongs to K+cR.

  Since u and c both have degree one, homogeneity gives

    u-lambda*c in K

  for some scalar lambda.  Multiply by u.  Because K=0:_R u, the K-term dies,
  giving

    u^2=lambda*u*c.

  The final statement follows after quotienting by u*c.
Qed.

Interpretation:
  The unresolved e=5, h=(1,2,2) zerodivisor-lower branch is no longer the full
  three-value window eta in {17,18,19}.

  If the embedded cubic torsion acts nontrivially on itself, then

    J intersect T=T_3,

  and the regular cubic already present in K_1 gives the exact section bound

    length(J/qJ)=16.

  This forces eta_1<=16, after which every later degree-gap layer is
  nonpositive.  Hence that entire case misses the tangent gate.

  The only remaining case is

    T^2=0,

  equivalently

    T subseteq Ann_B(T),

  or, in the linkage model,

    u in K+cR.

  Thus the remaining obstruction is a concrete square-zero embedded-extension
  problem, not an arbitrary first-layer colon.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove the ZERO_SELF_ACTION / square-zero case impossible.

  Therefore it does NOT close the full e=5, h=(1,2,2) height-three branch.

  It makes no claim for the remaining h-vectors, q=4 height two, homogeneous
  q<=3, the unrestricted nonhomogeneous local deviation-two frontier, or
  generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e5_h122_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  In the unique surviving ZERO_SELF_ACTION case

    T^2=0,
    T subseteq J=Ann_B(T),
    u in K+cR,

  prove eta_1<=16, or exhibit the first exact square-zero core for which

    eta_1>=17.

NEXT_BOUNDED_OBJECT:
  Work only under T^2=0.  Use the induced square-zero extension

    0 -> T -> B -> Cbar -> 0

  together with

    T~=C[z]/(z^3)(-1)

  as a Cbar-module and the first-layer pair

    K_1=(a,ell*b).

  Determine whether the extra square-zero maps K_1->T force two additional
  Hom dimensions beyond the crude cubic-section bound eighteen.  Stop at the
  first exact multiplication type that can still reach eta_1=17.