Standalone colon/annihilator classification of the exact H10 endpoint in the
multiplicity-one, depth-one saturated core of the homogeneous q=4, height-two
order-13 deviation-two program.

SCOPE:
  Continue only from the current four-state multiplicity-one Hilbert frontier.
  Retain

    S := C[x1,x2,x3,x4],
    Q subset S,
    Q generated minimally by four independent quadrics,
    ht(Q)=2,
    Qsat := saturation(Q),
    Ccore := S/Qsat,
    T := Qsat/Q,

and the residual exact sequence

    0 -> D -> Ccore -> S/P -> 0,

with

    P=(l1,l2)

height two linear and

    D=P/Qsat.

Treat only the exact H10 state

    (u1,u2)=(1,4),
    Hilb_D(t)=t/(1-t).

No H00, H01, or H11 case is entered.
No tangent-space estimate is made.
No full q=4 or order-13 closure is claimed.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
MACHINE_VERIFICATION_OF_NEW_THEOREM is not claimed.

--------------------------------------------------------------------------
1. NORMALIZE THE SINGLE LINEAR MEMBER OF Qsat
--------------------------------------------------------------------------

Because

    u1=dim_C (Qsat)_1=1

and Qsat is contained in

    P=(l1,l2),

choose the basis of P_1 so that

    (Qsat)_1=C*l1.

Then

    l1 in Qsat,
    l2 notin Qsat.

Theorem H10_residual_is_cyclic_on_l2:
  The S-module

    D=P/Qsat

is generated by the degree-one class

    dbar := l2 mod Qsat.

Proof:
  Every f in P has a representation

    f=l1*a+l2*b.

  Since l1 is in Qsat, the term l1*a vanishes in D.  Hence

    f mod Qsat = b*(l2 mod Qsat).

  Thus dbar generates D.  It is nonzero because l2 is not in Qsat.
Qed.

--------------------------------------------------------------------------
2. THE EXACT COLON PRESENTATION
--------------------------------------------------------------------------

Define

    J := (Qsat:l2)
       = { f in S : f*l2 in Qsat }.

Theorem H10_colon_is_the_annihilator:
  One has

    J=Ann_S(D)=Ann_S(dbar).

Proof:
  Since D is cyclic on dbar, its annihilator is the annihilator of dbar.
  By definition,

    f*dbar=0 in D

if and only if

    f*l2 in Qsat.

  This is exactly the condition f in (Qsat:l2)=J.
Qed.

Theorem H10_exact_cyclic_presentation:
  Multiplication by l2 induces a graded isomorphism

    S/J(-1) ~= D.

Proof:
  Consider

    phi:S(-1) -> D,
    phi(f)=f*l2 mod Qsat.

  The previous cyclicity theorem makes phi surjective.  Its kernel is exactly

    (Qsat:l2)=J.

  Therefore the first isomorphism theorem gives

    S/J(-1) ~= D.
Qed.

Corollary H10_colon_quotient_Hilbert_series:
  One has

    Hilb_(S/J)(t)=1/(1-t).

Proof:
  The H10 hypothesis gives

    Hilb_D(t)=t/(1-t).

  Since the shift (-1) multiplies the Hilbert series by t,

    Hilb_D(t)=t*Hilb_(S/J)(t).

  Cancel t.
Qed.

--------------------------------------------------------------------------
3. J IS A HEIGHT-THREE LINEAR PRIME
--------------------------------------------------------------------------

Theorem H10_colon_has_three_independent_linear_generators:
  The degree-one space J_1 has dimension three.

Proof:
  The Hilbert series

    Hilb_(S/J)(t)=1/(1-t)

has degree-one coefficient one.  Since dim_C S_1=4,

    dim_C J_1=4-1=3.
Qed.

Let

    L:=(J_1).

Then L is generated by three independent linear forms, so after a linear change
of coordinates

    S/L ~= C[z]

and therefore

    Hilb_(S/L)(t)=1/(1-t).

Theorem H10_colon_is_generated_by_its_linear_part:
  One has

    J=L=(J_1).

Proof:
  Since L is contained in J there is a graded surjection

    S/L -> S/J.

  Both source and target have Hilbert series

    1/(1-t).

  Hence the kernel has zero Hilbert function in every degree and must vanish.
  Thus J=L.
Qed.

Corollary H10_colon_is_a_linear_point_prime:
  The ideal J is a height-three prime generated by three independent linear
  forms, and

    S/J ~= C[z].
Qed.

Theorem H10_l1_lies_in_the_colon_prime:
  One has

    l1 in J.

Proof:
  Since l1 is in Qsat and Qsat is an ideal,

    l1*l2 in Qsat.

  Therefore l1 belongs to (Qsat:l2)=J.
Qed.

Thus J is a projective point prime whose linear space contains l1.

--------------------------------------------------------------------------
4. RECOVER Qsat EXACTLY FROM THE COLON
--------------------------------------------------------------------------

Theorem H10_exact_saturation_normal_form:
  One has

    Qsat=(l1)+l2*J.

Proof:
  First,

    (l1)+l2*J subset Qsat,

because l1 is in Qsat and the definition of J gives l2*J subset Qsat.

  Conversely let f be in Qsat.  Since Qsat subset P=(l1,l2), write

    f=l1*a+l2*b.

  The first term l1*a is in Qsat, hence

    l2*b=f-l1*a

is in Qsat.  Therefore

    b in (Qsat:l2)=J.

  So f lies in (l1)+l2*J.
Qed.

Corollary H10_saturation_is_determined_by_one_point_prime:
  Once the pair

    P=(l1,l2)

and the height-three linear prime J containing l1 are fixed, the H10 saturated
ideal is forced to be

    Qsat=(l1)+l2*J.

No further higher-degree generator of Qsat is free.
Qed.

Corollary H10_degree_two_space:
  One has

    (Qsat)_2=l1*S_1+l2*J_1

and

    dim_C (Qsat)_2=6.

Proof:
  The normal form gives the displayed degree-two space.  The H10 bookkeeping
  already gives

    dim_C (Qsat)_2=2+u2=6.
Qed.

Thus the four-dimensional space Q_2 of original quadratic generators is a
codimension-two subspace of this forced six-dimensional quadratic space.

--------------------------------------------------------------------------
5. THE ONLY REMAINING INCIDENCE SPLIT
--------------------------------------------------------------------------

The colon classification leaves exactly one geometric incidence question:

    is l2 in J or not?

Both possibilities are compatible with the colon/Hilbert data proved above.
They must not be identified without an additional argument from the original
four-quadric ideal Q.

CASE H10-OFF:
  Assume

    l2 notin J.

  Since J_1 has dimension three and contains l1, choose independent linear forms
  m1,m2 such that

    J=(l1,m1,m2)

and

    l1,l2,m1,m2

is a basis of S_1.

Theorem H10_off_line_intersection_form:
  In CASE H10-OFF,

    Qsat=P intersect J

and equivalently

    Qsat=(l1,l2*m1,l2*m2).

Proof:
  The general normal form gives

    Qsat=(l1)+l2*(l1,m1,m2)
        =(l1,l2*m1,l2*m2).

  To identify the intersection, reduce modulo (l1).  In S/(l1), the image of J
  is prime and does not contain the image of l2.  Hence

    (l2) intersect Jbar = l2*Jbar.

  Lifting back to S gives

    (l1,l2) intersect J=(l1)+l2*J=Qsat.
Qed.

Geometrically, this is the saturated union of the line defined by P and the
projective point defined by J, with that point off the line.

CASE H10-ON:
  Assume

    l2 in J.

  Then P is contained in J.  Choose a third independent linear form m so that

    J=(l1,l2,m).

Theorem H10_on_line_embedded_form:
  In CASE H10-ON,

    Qsat=(l1,l2^2,l2*m).

Proof:
  Substitute J=(l1,l2,m) into

    Qsat=(l1)+l2*J.

  The product l1*l2 is redundant modulo (l1), leaving

    Qsat=(l1,l2^2,l2*m).
Qed.

Corollary H10_on_line_has_embedded_point_prime:
  In CASE H10-ON, J is an associated prime of Ccore=S/Qsat strictly containing
  the line prime P.

Proof:
  The submodule

    D ~= S/J(-1)

sits nontrivially inside Ccore by the residual exact sequence.  Therefore J is
an annihilator of a nonzero cyclic submodule of Ccore and hence an associated
prime.  Since P is properly contained in the height-three prime J, this is an
embedded projective point on the line support.
Qed.

IMPORTANT_NONCOLLAPSE:
  In CASE H10-ON one must not write

    Qsat=P intersect J,

because P subset J would make that intersection equal to P, while H10 has
nonzero residual D=P/Qsat.

--------------------------------------------------------------------------
6. SHARP H10 BOUNDARY
--------------------------------------------------------------------------

The exact cyclic endpoint H10 is now classified up to one incidence bit:

    D ~= S/J(-1),
    Ann_S(D)=J=(Qsat:l2),
    Hilb_(S/J)=1/(1-t),
    J is a height-three linear prime,
    l1 in J,
    Qsat=(l1)+l2*J.

There are exactly two resulting coordinate forms:

    H10-OFF:
      l2 notin J,
      Qsat=P intersect J,
      Qsat=(l1,l2*m1,l2*m2).

    H10-ON:
      l2 in J,
      P subset J,
      Qsat=(l1,l2^2,l2*m).

This file does NOT decide which incidence is realized by a four-independent-
quadric ideal Q whose saturation is Qsat.

It does NOT classify the codimension-two choice

    Q_2 subset (Qsat)_2.

It does NOT classify the higher J-adic/saturation defect layers T.
It makes no tangent-space estimate.
It does not close the multiplicity-one branch.
It does not close q=4 height two.
It does not close order 13.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  q4_height2_multiplicity_one_depth_one_H10_colon_classified.
  q4_height2_multiplicity_one_depth_one_H10_reduced_to_incidence_and_Q2_choice.
  not q4_height2_multiplicity_one_depth_one_H10_closed.
  not q4_height2_multiplicity_one_depth_one_closed.
  not q4_height2_full_closure.
  not full_order13_closure.

MISSING_OBJECT:
  Use the original four-dimensional quadratic generator space

    Q_2 subset (Qsat)_2,
    dim Q_2=4,
    dim (Qsat)_2=6,
    saturation(Q)=Qsat,

  to determine which of H10-OFF and H10-ON can actually occur and to classify
  the permitted codimension-two subspaces Q_2.

NEXT_ACTIONS:
  1. Stay inside H10.
  2. Split H10-OFF from H10-ON without identifying them.
  3. Impose only the four-independent-quadric condition on Q_2.
  4. Use saturation(Q)=Qsat as the next structural test.
  5. Stop before tangent-space estimates.
