Standalone cyclic-torsion/annihilator reduction for the multiplicity-five
h=(1,2,2) subbranch of the homogeneous q=4, height-three order-13
low-multiplicity problem.

SCOPE:
  Continue from

    order13_q4_height3_low_multiplicity_saturated_core_profile.v
    order13_q4_height3_low_multiplicity_conormal_rank_reduction.v
    order13_q4_height3_low_multiplicity_cyclic_connecting_reduction.v
    order13_q4_height3_e345_exact_saturation_linkage_table.v
    order13_q4_height3_e4_13_linear_core_closed.v

  Work only with

    S := C[x1,x2,x3,x4],
    I := Q+(f,g) homogeneous and m-primary,
    A := S/I,
    N := length_C(A)>=32,

  where Q is minimally generated by exactly four independent quadrics,

    ht(Q)=3,
    B:=S/Q,
    e(B)=5,

  and, with

    T:=H^0_m(B),
    Cbar:=B/T,

  a general linear nonzerodivisor ell on Cbar has Artin-reduction h-vector

    h(Cbar/ell*Cbar)=(1,2,2).

  The exact saturation-linkage table gives

    Hilb_T(t)=t+t^2+t^3,
    length_C(T)=3,
    m_B^3*T=0.

This is pseudo-formal mathematical documentation.  It is not Coq or Lean and
it does not assert generic F_13 algebraicity.

The purpose of this file is one structural reduction: identify the full
B-module structure of T and its annihilator, not merely its Hilbert function.
The resulting annihilator has codimension exactly three in every final Artin
quotient A.  Consequently the general two-generator tangent obstruction
sharpens from connecting excess six to connecting excess seventeen in this
h-vector.

Retain the three-quadric complete-intersection section model

  R:=S/(q1,q2,q3),
  q:=image of the fourth quadratic generator in R,
  J:=q*R,
  B=R/J,
  U:=saturation(J),
  Cbar=R/U,
  T=U/J.

Put

  K:=0:_R q.

The preceding exact linkage file proves

  U=0:_R K,
  K=0:_R U,
  K(2) ~= omega_Cbar,

and R is one-dimensional graded Gorenstein with

  Hilb_R(t)=(1+t)^3/(1-t),
  omega_R ~= R(2).

Theorem exact_residual_Hilbert_series:
  One has

    Hilb_(R/K)(t)=(1+t+t^2)/(1-t).

Proof:
  Since

    Hilb_Cbar(t)=(1+2*t+2*t^2)/(1-t),

  graded canonical-module reciprocity gives

    Hilb_omega_Cbar(t)
      =t*(1+2*t^(-1)+2*t^(-2))/(1-t).

  The linkage identity K(2)~=omega_Cbar therefore gives

    Hilb_K(t)
      =(2*t+2*t^2+t^3)/(1-t).

  Subtract this from

    Hilb_R(t)
      =(1+3*t+3*t^2+t^3)/(1-t)

  to obtain

    Hilb_(R/K)(t)
      =(1+t+t^2)/(1-t).
Qed.

Theorem K_is_saturated_and_the_residual_ring_is_CohenMacaulay:
  The ideal K is saturated.  Consequently R/K is one-dimensional
  Cohen--Macaulay.

Proof:
  Suppose x is homogeneous and some power of the irrelevant ideal sends x
  into K.  Choose a linear nonzerodivisor lambda on the one-dimensional
  Cohen--Macaulay ring R.  Then for sufficiently large n,

    lambda^n*x belongs to K=0:_R U.

  Hence for every u in U,

    lambda^n*x*u=0.

  Since lambda is R-regular, multiplication by lambda^n is injective on R, so

    x*u=0

  for every u in U.  Therefore x belongs to 0:_R U=K.

  Thus K is saturated.  The Hilbert series in the preceding theorem has
  positive eventual value three, so dim(R/K)=1.  Saturation removes H^0_m,
  hence depth(R/K)>=1.  Therefore R/K is Cohen--Macaulay.
Qed.

Put

  C0:=R/K.

Theorem the_length_three_residual_ring_is_Gorenstein:
  C0 is a one-dimensional standard graded Gorenstein ring.

Proof:
  The preceding theorem gives

    Hilb_C0(t)=(1+t+t^2)/(1-t).

  Choose a general linear nonzerodivisor lambda on C0.  Then

    C0/lambda*C0

  has Hilbert function

    (1,1,1).

  Any standard graded Artin C-algebra with this Hilbert function is generated
  by its one-dimensional degree-one piece.  If z spans degree one, then z^2
  spans degree two and z^3=0.  Thus its socle is exactly the one-dimensional
  degree-two piece, so the Artin reduction is Gorenstein.

  A regular linear reduction preserves Cohen--Macaulay type.  Hence C0 has
  type one and is Gorenstein.
Qed.

Theorem the_saturated_hull_is_a_principal_linear_R_module:
  There exists a homogeneous element

    u in U_1

  such that

    U=u*R,
    0:_R u=K,

  and multiplication by u gives a graded R-module isomorphism

    C0(-1) ~= U.

Proof:
  Since U=0:_R K,

    U(2)
      ~= Hom_R(R/K,R(2))
      ~= omega_C0.

  The preceding theorem says C0 is Gorenstein, so omega_C0 is a graded shift
  of C0.  The Hilbert series determines the shift uniquely.

  Indeed

    Hilb_U
      =Hilb_R-Hilb_Cbar
      =(t+t^2+t^3)/(1-t)
      =t*Hilb_C0.

  Therefore U is a cyclic graded C0-module generated in degree one and is
  isomorphic to C0(-1).  Let u be the image of 1 under this isomorphism.
  Then U=uR, and the kernel of multiplication R->uR is exactly K, so

    0:_R u=K.
Qed.

Theorem the_fourth_quadric_factors_through_the_linear_link_generator:
  There exists a homogeneous linear form

    c in R_1

  such that

    q=u*c.

  The image of c in C0 is a nonzerodivisor.

Proof:
  Since J=qR is contained in U=uR and q has degree two while u has degree one,
  there is a homogeneous c in R_1 with q=u*c.

  Under the isomorphism C0(-1)~=uR, the quotient

    T=U/J

  becomes

    T ~= (C0/c*C0)(-1).

  The exact torsion table gives

    Hilb_T=t+t^2+t^3.

  Hence

    Hilb_(C0/c*C0)=1+t+t^2,

  which is finite-dimensional.  Since C0 is one-dimensional Cohen--Macaulay,
  a homogeneous parameter is a nonzerodivisor.  Thus c is C0-regular.
Qed.

Corollary exact_cyclic_torsion_module:
  As a graded module,

    T ~= (C0/c*C0)(-1).

  Moreover C0/c*C0 is the unique standard graded Artin algebra with Hilbert
  function (1,1,1), hence

    C0/c*C0 ~= C[z]/(z^3)

  as a graded C-algebra.

  In particular T is cyclic, generated in degree one, and has the chain

    T_1 --z--> T_2 --z--> T_3 --z--> 0,

  with each displayed graded piece one-dimensional.

Proof:
  The first statement was obtained in the preceding proof.  A standard graded
  Artin algebra with Hilbert function (1,1,1) has one degree-one generator z,
  nonzero z^2 spanning degree two, and z^3=0.  This gives the displayed normal
  form and the cyclic chain.
Qed.

Theorem exact_annihilator_of_the_saturation_torsion_in_B:
  One has

    Ann_B(T)
      =(K+cR)/(u*c*R).

  Consequently

    B/Ann_B(T) ~= R/(K,c),

  and

    length_C(B/Ann_B(T))=3.

Proof:
  Write B=R/(u*c).  An element r modulo u*c annihilates

    T=uR/u*cR

  exactly when

    r*u belongs to u*cR.

  Under the isomorphism

    R/K -> uR,
    x mod K |-> u*x,

  this is equivalent to

    r mod K belongs to c*(R/K),

  namely

    r belongs to K+cR.

  This proves the annihilator formula.  Quotienting B by this annihilator gives

    R/(K,c)=C0/c*C0,

  whose Hilbert function is (1,1,1), hence whose length is three.
Qed.

Now return to the final two cuts.

Put

  L:=(f,g)B.

Theorem every_final_cut_annihilates_T_and_the_annihilator_descends_exactly:
  One has

    L*T=0,
    L subseteq Ann_B(T).

  Therefore, in A=B/L,

    X:=Ann_A(T)

  satisfies

    X=Ann_B(T)/L,
    A/X ~= B/Ann_B(T),

  and hence

    dim_C X=N-3.

Proof:
  Every final generator has degree at least three, while m_B^3*T=0.  Thus
  f*T=g*T=0 and L*T=0.  The inclusion into Ann_B(T) follows.

  Annihilators therefore descend through the quotient by L, and the quotient
  A/X is unchanged from B/Ann_B(T).  The preceding theorem gives its length
  three, so dim_C X=N-3.
Qed.

Corollary the_only_possible_final_cut_intersection_is_the_top_socle_line:
  One has

    L intersect T subseteq T_3.

  Since dim_C T_3=1,

    dim_C(L intersect T) in {0,1}.

Proof:
  The ideal L is generated in degrees at least three, so L has no degree-one or
  degree-two component.  The torsion T is concentrated in degrees one, two,
  and three.  Therefore any intersection can occur only in degree three.
Qed.

Choose an invertible constant GL_2(C) change of the final generators

  L=(h,k)

such that hbar and kbar are both nonzerodivisors on Cbar, as in the preceding
cyclic connecting reduction.

Theorem both_regularized_final_cuts_have_exact_kernel_T:
  Put

    D:=0:_B h,
    E:=0:_B k.

  Then

    D=E=T.

Proof:
  Since h and k lie in m_B^3, both annihilate T.

  Conversely, if h*x=0 in B, projection to Cbar gives

    hbar*xbar=0.

  Regularity of hbar forces xbar=0, so x belongs to T.  Hence D=T.  The proof
  for k is identical.
Qed.

Put

  Hh:=hB subseteq L,
  M:=L/Hh.

Theorem exact_e5_122_connecting_sequence:
  There is an exact sequence

    0 -> Hom_B(M,A)
      -> Hom_B(L,A)
      -> X
      --partial--> Ext^1_B(M,A).

  If

    sigma:=rank_C(partial),
    epsilon:=sigma-dim_C Hom_B(M,A),

  then

    dim_C Hom_B(L,A)=N-3-epsilon.

Proof:
  Multiplication identifies hB~=B/T because 0:_B h=T.  Hence

    Hom_B(hB,A)
      ~= Hom_B(B/T,A)
      ~= Ann_A(T)
      =X.

  Apply Hom_B(-,A) to

    0 -> hB -> L -> M -> 0.

  Exactness gives

    dim Hom_B(L,A)
      =dim X+dim Hom_B(M,A)-sigma
      =N-3-epsilon.
Qed.

Theorem order13_tangent_gate_forces_connecting_excess_seventeen:
  If the necessary order-13 tangent gate holds,

    dim_C Hom_S(I,A)<=N-20,

  then

    epsilon>=17.

Proof:
  Maps I->A that vanish on Q contain Hom_B(L,A), so

    dim Hom_S(I,A)>=dim Hom_B(L,A)=N-3-epsilon.

  Combining with the tangent gate gives

    N-3-epsilon<=N-20,

  hence

    epsilon>=17.
Qed.

Finally specialize the finite cyclic carrier from the preceding connecting
reduction.  Put

  Kh:=(h:k).

Since E=T, define

  P:=Kh/(T+hB).

The preceding cyclic reduction gives

  M ~= B/Kh,
  Hom_B(M,A) ~= 0:_A Kh,

and all connecting representatives factor through the finite A-module P.
Therefore

  epsilon
    <= dim_C Hom_A(P,A)
       - dim_C(0:_A Kh).

Corollary dangerous_candidate_requires_carrier_excess_seventeen:
  Every e=5, h=(1,2,2) candidate satisfying the necessary order-13 tangent gate
  must satisfy

    dim_C Hom_A(P,A)
      - dim_C(0:_A Kh)
      >=17.
Qed.

Interpretation:
  The h=(1,2,2) branch has no unknown saturation-torsion multiplication table.
  Its embedded defect is the shifted cubic string

    C[z]/(z^3)(-1),

  and its annihilator quotient has exact length three.

  This is much stronger than the generic low-multiplicity estimate

    length(A/Ann_A(D))<=14.

  Here the exact value is

    length(A/Ann_A(T))=3,

  so a dangerous candidate needs connecting rank excess at least seventeen,
  not merely six.

IMPORTANT_NONCONCLUSION:
  This file does NOT prove the carrier excess is at most sixteen and therefore
  does NOT close the e=5, h=(1,2,2) branch.

  It does not identify the finite module P explicitly for every quadratic-core
  degree-gap pair, and it does not classify the multiplication algebra of
  Cbar beyond what is forced by linkage.

  It makes no claim for the remaining h-vectors, q=4 height two, homogeneous
  q<=3, the unrestricted nonhomogeneous local deviation-two frontier, or
  generic F_13 algebraicity.

PROOF_STATUS:
  pseudo-formal mathematical documentation.

MACHINE_VERIFICATION_OF_NEW_THEOREM:
  not claimed.

BOUNDARY:
  not e5_h122_height3_closed.
  not q4_height3_low_multiplicity_tangent_closure.
  not full_order13_closure.

MISSING_OBJECT:
  An upper bound of sixteen on the exact finite carrier excess

    dim_C Hom_A(P,A)-dim_C(0:_A(h:k))

  for

    P=(h:k)/(T+hB),
    T ~= C[z]/(z^3)(-1),
    length(A/Ann_A(T))=3.

NEXT_BOUNDED_OBJECT:
  Pass the final-cut pair to the degree-two saturated-core predecessors

    K_i=(a,ell^i*b)

  using the h=(1,2,2) stabilization in degree two.  Split by whether the lower
  quadratic a is regular or a zerodivisor on Cbar, and determine whether the
  exact length-three annihilator quotient forces

    epsilon<=16.

  Stop at the first quadratic-core colon whose carrier can still reach
  seventeen rather than moving to another h-vector.
