Standalone reduction of the remaining rational degree-four Hodge problem on S^[n]
to self-adjoint Hodge endomorphisms of the K3 transcendental lattice.

This file is independent of ZeroDayClosure, required_classes.I,
ActuallyRequired, and inventory semantics.

Setup:
  Let S be a smooth complex projective K3 surface and X := S^[n] with n >= 4.

  Let
    V := H^2(X,Q),
    N := NS(X)_Q,
    T := T(S)_Q.

  Under the standard Hilbert-scheme splitting,

    V = N direct_sum T,
    N = NS(S)_Q direct_sum Q*delta,

  where 2*delta is the Hilbert-Chow exceptional divisor class.

  Let q denote the Beauville-Bogomolov form on V; on T it agrees with the
  K3 intersection form under the natural H^2(S) -> H^2(S^[n]) inclusion.

Theorem sym2_hodge_classes_split_into_divisor_and_transcendental_parts:
  The rational (2,2)-classes in Sym^2 V split as

    Hdg^4(Sym^2 V)
      = Sym^2 N direct_sum Hdg^4(Sym^2 T).

Proof:
  Expand

    Sym^2 V
      = Sym^2 N direct_sum (N tensor T) direct_sum Sym^2 T.

  Every class in N is rational of Hodge type (1,1), hence Sym^2 N consists
  of rational (2,2)-classes and is algebraic by products of divisors.

  A rational Hodge class in N tensor T would give a rational (1,1)-class
  in T. By definition T is the orthogonal complement of NS(S)_Q, and by
  Lefschetz (1,1) it contains no nonzero rational (1,1)-class.

  Hence Hdg^4(N tensor T)=0, leaving exactly the stated decomposition.
Qed.

Define

  E := End_Hdg(T).

ExternalResult ZarhinK3HodgeEndomorphismField:
  E is a number field, either totally real or CM.

  The polarization q identifies T with T^*(-2), and hence identifies
  Hodge tensors in T tensor T with Hodge endomorphisms of T.

  Under this identification, symmetric tensors correspond to endomorphisms
  fixed by the q-adjoint involution dagger.

  If E is totally real, dagger is the identity on E.
  If E is CM, dagger is complex conjugation on E.

Source:
  Yu. G. Zarhin,
  Hodge groups of K3 surfaces,
  J. reine angew. Math. 341 (1983), 193-220.

Define

  E_plus := { e in E : e^dagger = e }.

Theorem transcendental_sym2_hodge_sector_is_E_plus:
  There is a canonical Q-linear identification

    Hdg^4(Sym^2 T) ~= E_plus.

  Consequently:

    if E is totally real,
      E_plus = E;

    if E is CM with maximal totally real subfield E_0,
      E_plus = E_0.

  Therefore

    dim_Q Hdg^4(Sym^2 T)
      = [E:Q]       in the totally real case,

    dim_Q Hdg^4(Sym^2 T)
      = [E:Q]/2     in the CM case.

Proof:
  Use q to identify a tensor t in T tensor T with the endomorphism e_t
  obtained by contracting one factor against q.

  The Hodge condition on t is exactly that e_t preserve the Hodge structure.
  Interchanging the two tensor factors corresponds to q-adjoint.
  Hence t is symmetric exactly when e_t is self-adjoint.

  Apply ZarhinK3HodgeEndomorphismField for the description of dagger.
Qed.

ExternalResult BuskinHodgeIsometriesAlgebraic:
  Every rational Hodge isometry between projective K3 surfaces is induced by
  an algebraic codimension-two correspondence.

Source:
  Nikolay Buskin,
  Every rational Hodge isometry between two K3 surfaces is algebraic,
  J. reine angew. Math. 755 (2019), 127-150.

Theorem buskin_closes_CM_sym2_sector:
  If E is CM, every class in Hdg^4(Sym^2 T) is algebraic.

Proof:
  In the CM case, the Hodge-isometry elements are the elements u in E with

    u^dagger * u = 1.

  A CM field is spanned as a Q-vector space by its norm-one elements.
  Hence E, and therefore its self-adjoint subspace E_plus, is spanned by
  rational Hodge isometries.

  By BuskinHodgeIsometriesAlgebraic, each such isometry has an algebraic
  correspondence class on S x S.

  The universal incidence correspondence between S and S^[n] is algebraic
  and realizes the natural H^2(S) -> H^2(S^[n]) inclusion. Transporting the
  tensor class to X and applying cup product preserves algebraicity.

  Therefore every class in Hdg^4(Sym^2 T) is algebraic.
Qed.

Theorem buskin_does_not_close_general_real_multiplication_sector:
  Suppose E is totally real with [E:Q] > 1.

  Then Buskin's Hodge-isometry theorem alone algebraizes only the Q-line
  generated by the identity inside E; it does not algebraize all of E.

Proof:
  In the totally real case dagger is the identity, so a scalar Hodge
  endomorphism u in E is an isometry exactly when

    u^dagger*u = u^2 = 1.

  Since E is a field of characteristic zero, u^2=1 implies u=+1 or u=-1.

  Thus the Q-span of scalar Hodge isometries in E is only Q*id, whereas
  Hdg^4(Sym^2 T) ~= E has Q-dimension [E:Q] > 1.
Qed.

Corollary rational_degree_four_hodge_frontier_for_projective_k3_hilbert_schemes:
  Combine this file with projective_k3_q4_integral_hodge_algebraicity.v.

  For X=S^[n], n>=4:

    (1) every rational Hodge class in the quotient

          H^4(X,Q) / Sym^2 H^2(X,Q)

        has an algebraic lift;

    (2) every Hodge class in Sym^2 NS(X)_Q is algebraic by divisor products;

    (3) the only unresolved rational degree-four sector is

          E_plus ~= Hdg^4(Sym^2 T(S)_Q).

  In particular:

    - if End_Hdg(T(S)) is CM, the rational degree-four Hodge problem for
      X is closed by the quotient theorem plus Buskin;

    - if End_Hdg(T(S)) = Q, the transcendental symmetric sector is the
      identity/polarization line and is algebraic;

    - for general totally real multiplication of degree > 1, the remaining
      classes are precisely the non-scalar elements of E and are not settled
      by Buskin's isometry theorem.
Qed.

ExternalBoundary RealMultiplicationSelfProductHodgeProblem:
  The general Hodge conjecture for S x S in the real-multiplication case is
  not known merely from the Mukai-Buskin isometry theorem.

  Schlickewei proves it for specific real-multiplication K3 families, notably
  certain double covers of P^2 branched along six lines, but not for all K3
  surfaces with totally real Hodge endomorphism field.

Source:
  Ulrich Schlickewei,
  The Hodge conjecture for self-products of certain K3 surfaces,
  J. Algebra 324 (2010), 507-529.

Boundary:
  this file deliberately does NOT claim the full rational degree-four Hodge
  conjecture for every projective K3 Hilbert scheme
  Buskin concerns Hodge isometries, not arbitrary real-multiplication Hodge
  endomorphisms
  the CM and End_Hdg(T)=Q sectors are separated from the genuinely open
  totally-real degree > 1 sector
  no ZeroDayClosure semantics are used
  no required-class index is used
  this .v file is pseudo-formal mathematical documentation, not a Coq proof
