Standalone classification of the part of a totally-real K3 Hodge endomorphism field
that can be reached by Hodge-similarity methods.

This file is independent of ZeroDayClosure, required_classes.I,
ActuallyRequired, and inventory semantics.

Setup:
  Let S be a smooth complex projective K3 surface.
  Let
    T := T(S)_Q
  be its transcendental Hodge structure with polarization q.

  Assume
    E := End_Hdg(T)
  is a totally real number field.

  By Zarhin, the Rosati/q-adjoint involution on E is the identity.

Definition:
  For e in E^x, call e a scalar Hodge similarity if there exists
    lambda in Q^x
  such that
    q(e*x,e*y) = lambda*q(x,y)
  for every x,y in T.

Theorem totally_real_scalar_similarity_criterion:
  For e in E^x, the following are equivalent:

    (1) e is a scalar Hodge similarity of multiplier lambda in Q^x;

    (2) e^2 = lambda in Q^x.

Proof:
  Since the q-adjoint of e is e,

    q(e*x,e*y) = q(x,e^dagger*e*y) = q(x,e^2*y).

  Hence the similarity identity

    q(e*x,e*y) = lambda*q(x,y)

  for all x,y is equivalent, by nondegeneracy of q, to

    e^2 = lambda*id.
Qed.

Corollary nonrational_similarity_generates_quadratic_subfield:
  If e is a non-rational scalar Hodge similarity, then

    Q(e) = Q(sqrt(lambda))

  is a quadratic subfield of E.

Proof:
  e^2=lambda in Q and e notin Q, so the minimal polynomial of e over Q
  divides X^2-lambda and has degree exactly two.
Qed.

Define
  E_sim := Span_Q { e in E : e^2 in Q }.

Define
  E_2
as the compositum inside E of all quadratic subfields of E;
if E has no quadratic subfield, put E_2 := Q.

Theorem similarity_span_is_maximal_multiquadratic_subfield:
  E_sim = E_2.

  In particular, E_2/Q is a multiquadratic extension and is the maximal
  subfield of E generated by scalar Hodge similarities.

Proof:
  Every scalar similarity e lies either in Q or in the quadratic field Q(e),
  so E_sim is contained in the compositum E_2.

  Conversely, write E_2 as the compositum of quadratic fields

    Q(sqrt(d_1)),...,Q(sqrt(d_r)).

  A standard Q-basis of this multiquadratic field consists of products

    sqrt(d_{i_1}...d_{i_k}).

  Each such basis element has square in Q, hence is a scalar Hodge similarity
  by totally_real_scalar_similarity_criterion.

  Thus E_2 is contained in E_sim.
Qed.

Corollary odd_degree_similarity_ceiling:
  If [E:Q] is odd and greater than one, then

    E_sim = Q.

Proof:
  An odd-degree number field has no quadratic subfield, because the degree of
  every intermediate field divides [E:Q]. Hence E_2=Q.
Qed.

Corollary no_quadratic_subfield_similarity_ceiling:
  More generally, if E has no quadratic subfield, then scalar Hodge
  similarities span only

    Q*id

  inside E.
Qed.

Corollary quadratic_real_multiplication_is_similarity_generated:
  If
    E = Q(sqrt(d))
  is totally real quadratic, then

    E_sim = E.

  Thus algebraicity of the single Hodge similarity sqrt(d) together with
  the algebraic identity correspondence algebraizes the whole real
  multiplication endomorphism field E.
Qed.

ExternalResult VarescoQuadraticRMSimilarityFamilies:
  Mauro Varesco proves:

    If a K3 surface X is Hodge isometric to a K3 surface with a symplectic
    automorphism of order p=2 or p=3 and Q(sqrt(p)) is contained in
    End_Hdg(T(X)), then sqrt(p) is algebraic.

  In particular, if
    End_Hdg(T(X)) = Q(sqrt(p)),
  the Hodge conjecture holds for X x X.

  Varesco also proves that for K3 surfaces satisfying the Kuga-Satake Hodge
  conjecture, every Hodge similarity between transcendental lattices is
  algebraic.

Source:
  Mauro Varesco,
  Hodge similarities, algebraic classes, and Kuga-Satake varieties,
  Mathematische Zeitschrift 305 (2023), article 69,
  Theorem 0.1 / Theorems 2.1, 2.9, 2.15 and Theorem 5.3.

Corollary quadratic_RM_closed_for_Varesco_families:
  In the p=2 and p=3 families covered by Varesco, if

    E = Q(sqrt(p)),

  then every element of E is algebraic as a Hodge correspondence.

  Therefore the remaining Sym^2(T) Hodge sector from
  projective_k3_sym2_hodge_endomorphism_reduction.v is algebraic for these
  K3 surfaces, and the rational degree-four Hodge problem for S^[n] is closed
  after combining with the already-proved quotient and divisor sectors.
Qed.

Corollary exact_similarity_method_ceiling_for_general_RM:
  Even under a hypothetical theorem saying that every scalar Hodge similarity
  of T(S) is algebraic, the similarity method alone would algebraize at most

    E_2 subset E.

  Therefore, when E != E_2, the complementary Q-vector directions in E cannot
  be reached merely by proving algebraicity of scalar Hodge similarities.

  A genuinely stronger input would be required: algebraicity of arbitrary
  Hodge endomorphisms, or a construction expressing those endomorphisms by
  algebraic correspondences not arising from scalar similarities.
Qed.

Boundary:
  this file does not claim algebraicity of every Hodge similarity for every K3
  Varesco's general similarity theorem is conditional on the Kuga-Satake Hodge
    conjecture, which is not known for arbitrary K3 surfaces
  the p=2 and p=3 algebraicity statements apply only under Varesco's stated
    symplectic/Hodge-isometry hypotheses
  the doubled/block-matrix orthogonal trick is deliberately not used because
    abstract realization as a larger Hodge structure does not automatically
    produce projective K3 surfaces carrying the needed algebraic projections
  no full Hodge conjecture is claimed for general totally-real multiplication
  no ZeroDayClosure semantics are used
  this .v file is pseudo-formal mathematical documentation, not a Coq proof
