Standalone discriminant-form and gluing calculation for the Picard-rank-one
quartic K3^[n] quotient-Hodge lattice.

This file depends only on the lattice calculation recorded in
quartic_picard_one_hodge_lattice_primitive_closure.v and is independent of
ZeroDayClosure, required_classes.I, ActuallyRequired, and inventory semantics.

Setup:
  Let n >= 4 and m := n - 1.

  Let
    N := Z*gamma direct_sum Z*xi direct_sum Z*eta_H
  with Gram matrix
    diag(2m, -2m, 4).

  Let
    L := Q4(S^[n],Z)_Hdg ~= U direct_sum <4>
  be the primitive closure of N, with

    A := (gamma + xi)/2,
    B := (gamma - xi)/(2m),

  so that
    gamma = A + m*B,
    xi    = A - m*B,
    A^2 = B^2 = 0,
    <A,B> = 1,
    eta_H^2 = 4.

Define dual generators of N:

  gamma_dual := gamma/(2m),
  xi_dual    := -xi/(2m),
  eta_dual   := eta_H/4.

Then

  A_N := N^dual / N
      ~= Z/(2m)Z direct_sum Z/(2m)Z direct_sum Z/4Z.

Represent a discriminant class by
  (a,b,c)
with respect to
  (gamma_dual, xi_dual, eta_dual).

Theorem quartic_picard_one_natural_lattice_discriminant_form:
  The discriminant quadratic form of N is

    q_N(a,b,c)
      = a^2/(2m) - b^2/(2m) + c^2/4
        mod 2Z,

  and the associated bilinear form is

    b_N((a,b,c),(a',b',c'))
      = a*a'/(2m) - b*b'/(2m) + c*c'/4
        mod Z.

Proof:
  The Gram matrix of N is diagonal with entries
    2m, -2m, 4.
  Invert the diagonal Gram matrix and evaluate the induced forms on N^dual/N.
Qed.

Theorem quartic_picard_one_gluing_subgroup:
  The class of

    B = (gamma - xi)/(2m)

  in A_N is

    h := (1,1,0).

  It has exact order 2m and is isotropic:

    q_N(h) = 0 mod 2Z.

  Hence

    H := <h> subset A_N

  is an isotropic subgroup of order 2m.

Proof:
  By the chosen dual generators,

    B = gamma_dual + xi_dual.

  Therefore [B] = (1,1,0).
  Its order is 2m because both first coordinates have exact order 2m.
  Finally

    q_N(1,1,0)
      = 1/(2m) - 1/(2m)
      = 0.
Qed.

Theorem quartic_picard_one_gluing_recovers_primitive_closure:
  The even overlattice of N associated to H is exactly L.

Proof:
  Adjoining a representative B of h to N gives N + Z*B.
  Since

    A = gamma - m*B,

  the resulting lattice contains A, B, and eta_H.
  Therefore it contains

    Z*A direct_sum Z*B direct_sum Z*eta_H = L.

  Conversely N and B are already contained in L.
  Hence the overlattice is exactly L.
Qed.

Theorem quartic_picard_one_gluing_orthogonal_complement:
  The orthogonal complement of H in A_N is

    H^perp
      = { (a,b,c) : a = b mod 2m }.

Proof:
  Pair (a,b,c) with h=(1,1,0):

    b_N((a,b,c),h)
      = (a-b)/(2m) mod Z.

  This vanishes exactly when a = b mod 2m.
Qed.

Theorem quartic_picard_one_primitive_discriminant_form:
  The discriminant group of the primitive closure is

    A_L ~= H^perp / H ~= Z/4Z.

  Under this identification, the residual generator is the class of

    eta_dual = eta_H/4,

  and the discriminant quadratic form is

    q_L(c) = c^2/4 mod 2Z.

  Thus the gluing removes the two Z/(2m) discriminant directions and leaves
  exactly the discriminant form of U direct_sum <4>.

Proof:
  Every element of H^perp has the form (a,a,c).
  Subtract a*h to reduce it to (0,0,c).
  Hence H^perp/H is generated by (0,0,1) and is cyclic of order 4.
  Restricting q_N to this residual coordinate gives c^2/4 mod 2Z.
Qed.

Corollary quartic_picard_one_gluing_index_check:
  The gluing subgroup has size

    |H| = 2m = 2(n-1),

  agreeing with

    [L:N] = 2(n-1).

  Moreover

    |A_N| = 16m^2,
    |A_L| = 4,

  and

    |A_N| / |H|^2 = 4 = |A_L|.

Proof:
  Immediate from the discriminant groups and |H|=2m.
Qed.

Boundary:
  this is an exact lattice-arithmetic consequence of the previously stated
    Markman Hodge-isometry input
  no ZeroDayClosure semantics are used
  no historical payload is identified
  no uniqueness claim is made for arbitrary isotropic subgroups of A_N
  the subgroup H here is the exact gluing subgroup for the explicit inclusion
    N subset L determined by gamma, xi, eta_H
  this .v file is pseudo-formal mathematical documentation, not a Coq proof
