Standalone Nakajima formula for c2(O_S^[n]) on Hilbert schemes of points.

This file is independent of ZeroDayClosure, required_classes.I,
ActuallyRequired, and inventory semantics.

Setup:
  Let S be a smooth projective surface and X_n := S^[n].
  Let
    T_n := O_S^[n] = p_* O_Z
  be the rank-n tautological algebra bundle on X_n.

  Let q_m(alpha) denote Nakajima's creation operators on

    H := direct_sum_{n >= 0} H^*(S^[n],Q),

  and let |0> denote the vacuum in H^0(S^[0],Q).

ExternalResult LehnTotalChernGeneratingSeries:
  For a line bundle L on S,

    sum_{n >= 0} c(L^[n])
      = exp(
          sum_{m >= 1} ((-1)^(m-1)/m) q_m(c(L))
        ) |0>.

  In particular for L = O_S,

    sum_{n >= 0} c(T_n)
      = exp(
          q_1(1)
          - (1/2) q_2(1)
          + (1/3) q_3(1)
          - (1/4) q_4(1)
          + ...
        ) |0>.

Source:
  Manfred Lehn,
  Chern Classes of Tautological Sheaves on Hilbert Schemes of Points on Surfaces,
  Theorem 4.6.

Degree convention:
  q_m(alpha) shifts cohomological degree by

    deg(alpha) + 2m - 2.

  Hence for alpha = 1,

    deg q_1(1) = 0,
    deg q_2(1) = 2,
    deg q_3(1) = 4,

  and q_m(1) has degree at least 6 for m >= 4.

Theorem tautological_c1_nakajima_formula:
  For n >= 2,

    c1(T_n)
      = - 1 / (2 * (n-2)!)
          q_2(1) q_1(1)^(n-2) |0>.

Proof:
  Extract cohomological degree 2 and Hilbert weight n from
  LehnTotalChernGeneratingSeries.

  The only positive-degree contribution is one copy of
    -(1/2) q_2(1).

  The remaining Hilbert weight n-2 is supplied by

    exp(q_1(1)),

  whose weight-(n-2) coefficient is

    q_1(1)^(n-2)/(n-2)!.
Qed.

Theorem tautological_c2_nakajima_formula:
  For n >= 4,

    c2(T_n)
      = 1 / (3 * (n-3)!)
          q_3(1) q_1(1)^(n-3) |0>
        +
        1 / (8 * (n-4)!)
          q_2(1)^2 q_1(1)^(n-4) |0>.

Proof:
  Extract cohomological degree 4 and Hilbert weight n from
  LehnTotalChernGeneratingSeries.

  Since deg q_m(1)=2m-2, the only degree-four possibilities are:

    (i) one q_3(1), carrying coefficient +1/3;

    (ii) two q_2(1)'s, each carrying coefficient -1/2.

  The exponential contributes the factorial 1/2! in case (ii), so

    (1/2!) * (-1/2)^2 = 1/8.

  All remaining Hilbert weight is supplied by q_1(1), giving

    q_1(1)^(n-3)/(n-3)!

  in case (i), and

    q_1(1)^(n-4)/(n-4)!

  in case (ii).

  No q_m(1) with m >= 4 can occur because its cohomological degree is
  at least 6.
Qed.

Small-n specializations:
  n = 2:

    c2(T_2) = 0

  because rank(T_2)=2 but the degree-four term of Lehn's series has no
  Hilbert weight 2 contribution.

  n = 3:

    c2(T_3) = (1/3) q_3(1)|0>.

  n >= 4:

    use tautological_c2_nakajima_formula above.

Corollary primitive_A_minus_B_exact_nakajima_formula:
  On the Picard-rank-one quartic K3 branch, recall

    [c2(T_n)]_Q4 = A - B.

  Therefore for n >= 4,

    A - B
      = [
          1 / (3 * (n-3)!)
            q_3(1) q_1(1)^(n-3) |0>
          +
          1 / (8 * (n-4)!)
            q_2(1)^2 q_1(1)^(n-4) |0>
        ]_Q4.

  Together with

    B = [[Z_s]]_Q4,

  this gives

    A
      = [[Z_s]]_Q4
        + [c2(T_n)]_Q4

  with c2(T_n) now expressed canonically in Nakajima operators.
Qed.

Chow-theoretic status:
  Maulik and Negut extend Lehn's operator formalism from cohomology to
  Chow groups for Hilbert schemes of points on a smooth projective surface.
  For K3 surfaces, their theorem also proves injectivity of the cycle class
  map on the subring generated by the relevant small tautological classes.

Sources:
  Davesh Maulik and Andrei Negut,
  Lehn's formula in Chow and Conjectures of Beauville and Voisin,
  especially Theorem 1.2, Theorem 1.6, and the Chow Nakajima operators.

Boundary:
  this is a canonical Nakajima-correspondence formula
  the two displayed Nakajima terms are not claimed here to be single
    irreducible effective codimension-two subvarieties
  B already has the stronger geometric interpretation B=[[Z_s]]_Q4
  no simpler canonical effective cycle for c2(T_n) is asserted
  no ZeroDayClosure semantics are used
  no required-class index is used
  no unrestricted Hodge conjecture is claimed
  this .v file is pseudo-formal mathematical documentation, not a Coq proof
